### ISSUE TITLE
dbclick and mouse right click

### ISSUE THREAD

**Issue by uyson** [angular-ui/ui-grid#1001]
How can I binding dbclick and mouse right click on the row?

thanks

**Comment by Ruud-cb** [comment]
This doesn't work because it is not the same scope? It does fire in the directive, (console log) but it does not reach my function.

rowtemplate:

	<div 
		 ng-right-click="rightclicked()"
		 ng-repeat="(colRenderIndex, col) in colContainer.renderedColumns track by col.uid"
		 ui-grid-one-bind-id-grid="rowRenderIndex + '-' + col.uid + '-cell'"
		 class="ui-grid-cell"
		 ng-class="{ 'ui-grid-row-header-cell': col.isRowHeader }"
		 role="{{col.isRowHeader ? 'rowheader' : 'gridcell'}}"
		 ui-grid-cell
		 >
	</div>

app:

    var app = angular.module("app", ['ngTouch', 'ui.grid', 'ui.grid.resizeColumns', 'ui.grid.moveColumns']);
    //$animate will destroy the column rearrange for the table. So don't use it, or only in the controller.
    app.directive('ngRightClick', function ($parse) {
        return function (scope, element, attrs) {
            var fn = $parse(attrs.ngRightClick);
            element.bind('contextmenu', function (event) {
                scope.$apply(function () {
                    console.log('rightclickdirect', fn, event);
                    event.preventDefault();
                    fn(scope, { $event: event });
                });
            });
        };
    });

controller:

    this.gridOptions = {
        data: self.data,
        columnDefs: self.tableColumns,
        enableColumnResizing: true,
        enableColumnMenus: false,
        rowTemplate: '/Templates/rowtemplate.html',
        onRegisterApi: self.registerApi
    };

    var tableController = function ($scope) {
        $scope.rightclicked = function () {
            console.log('right click');
        };

    };
    angular.module('app').controller('tableController', ['$scope', tableController]);

html

    <div class="container" ng-app="app" ng-controller="tableController as tc">
        <div ui-grid="tc.gridOptions" class="myGrid"  ui-grid-move-columns ui-grid-resize-columns>
        </div>
    </div>
