### ISSUE TITLE
Dynamic Aggregate Template

### ISSUE THREAD

**Issue by adamvaul** [angular-ui/ui-grid#1015]
This is an enchancement.

At our company, we have a large set of numerical data.  When we group the data in a grid, we like to show aggregates at each level.  In addition, we like our grids to be able to easily add or remove columns dynamically.

It would be nice if the aggregateTemplate was actually a function that could return a dynamic html template.  Doesn't that sound awesome?

That way we could code a function for each aggregate to look at it's own rows, and generate html for itself that contains aggregates for itself.

**Comment by RipuGuleria** [comment]
can you give any example for this as i am getting the same issue.
many thanks.

**Comment by adamvaul** [comment]
Sorry, I don't have any example for you right now.  I opened this issue a year ago and don't have code for it anymore.
