### ISSUE TITLE
Loading mask using custom template

### ISSUE THREAD

**Issue by pedromarce** [angular-ui/ui-grid#1025]
Hi,

I have a requirement to show somehow the load of server data to be populated in a grid, I know it is a very simple request but couldn't find how or if it is possible to do it easily at this moment.
Before attempting to write my own version of it I thought it would be good to double check I am missing something.
And if it is actually missing, my idea is to define a new templateURL-like option when defining the grid to be used as loading mask, and a loading option (boolean value) that would decide the visibility of the mask.
Let me know if that would be something interesting to add as a pull request or a better approach you might think of.

Regards,

**Comment by jpwits** [comment]
Hi...I've got the same issue, however I they do need an edit mask, so I added a new template to the cache and run it in my controller (injected $templateCache):
var addtemplate = function ($templateCache) {
         $templateCache.put('ui-grid/cellMask',
            "<div><form name=\"inputForm\"><input type=\"text\" ng-class=\"'colt' + col.uid\" ui-mask=\"99:99\" placeholder=\"placeholder\" ui-mask-placeholder ui-grid-editor ng-model=\"MODEL_COL_FIELD\"></form></div>");
    };
    addtemplate($templateCache);

It is a hard coded mask 99:99 (Time) for now. Now everything works fine, except that when I edit the field it shows a blank mask, however it does show the correct ng-model values on not edit, please help

(think this will also be cool to add as a editableCellTemplate, out of box)

Jos
