### ISSUE TITLE
TabIndex not working

### ISSUE THREAD

**Issue by prem-pal** [angular-ui/ui-grid#1042]
I am not sure how the tabIndex works. I have links in the rows of my ng-grid, but some how I am not able to access them using TAB key.

See plunker here:http://plnkr.co/edit/cCcuBqd7RuZ0SHvz4BZp?p=preview

When I am on input text box and when I click tab button, the focus should move to links in the grid, in this case "myLink", but it does not :(

**Comment by dsushmasagar** [comment]
Consider the grid width is 400px, and it has four columns. All column width is 100px. then tabbing between columns are working as expected.

'http://plnkr.co/edit/2yMGLTY1L69lGwY7W667'
Similar kind of grid with the same 400 px width. It has 4 columns. But Consider each column has 300px width, then tabbing between columns are not working. It is tabbing out only within the column which are visible on the screen. Please find the plunker here.

'http://plnkr.co/edit/HtWt7soGrpGwTtP7khaB'
I am not sure why this is happening. I am displaying almost 20 columns in the ng-grid, and would like to implement the tab out to column functionality. But couldn't. Can someone help me on this issue.

**Comment by letsexploremore** [comment]
Tabbing across the row is not happening. While tabbing across each row which has a text field in it. Focus on the text field is getting lost after few tabs. It jumps to some other record set, it doesn't follow order. Can someone help on it.

**Comment by marianoce** [comment]
i've a similar problem, tab works great until it reach the first column of the second Row, i don't know why but that cell gets skipped
