### ISSUE TITLE
Access sorted array data

### ISSUE THREAD

**Issue by parliament718** [angular-ui/ui-grid#1056]
I need to access the array of sorted data after sorting a table since the original is unchanged.

There is an `gridOptions.ngGrid.filteredData` but no `gridOptions.ngGrid.sortedData`

How can I access the sorted array?

**Comment by SET001** [comment]
also it can be accessed in `ngGridEventSorted` event like this - ` e.targetScope.renderedRows`

**Comment by moulding** [comment]
the second issue described here is a real issue.  Sometimes columns will not sort (not sure if the sort itself worked but the updated rendering didn't, or something else), but removing the tempData fixes (or rather avoids) this bug.  I don't know for sure how to reproduce this issue, but the one thing that all non-sorting columns have in common is strings-with-spaces.  If the column is just a string or a number the sort works fine, but if the column is a bunch of words (strings separated by spaces), then the sort seems to only move one row then quits.

**Comment by c0bra** [comment]
@Moulding is this just in ng-grid (v2) or v3 as well?
