### ISSUE TITLE
allow to specify column width with em, ex units

### ISSUE THREAD

**Issue by thkoch2001** [angular-ui/ui-grid#1065]
I'm aware that this might not be trivial. But I've columns with a fixed number of characters and thus it would make sense to specify the column width in em or ex.

**Comment by PaulL1** [comment]
This is a useful request, but not really in the current roadmap.  We have far too many good ideas in the repository already, giving the impression that we have a project riven with defects.

Accordingly, I am leaving the enhancement tag on this, but closing it.  If someone would like this functionality, we'd welcome a pull request that adds it.
