### ISSUE TITLE
rowHeight and virtualizationThreshold

### ISSUE THREAD

**Issue by steeeveb** [angular-ui/ui-grid#1071]
Maybe this isn't really an issue but I'd like to share what happened in my project with grids.

For maybe 3 months we had a problem with the scrolldown and scrollup of the grid. Actually when you arrive at the end of the rendered rows the scrolldown simply jump at the end of the grid, skipping a lot of rows.
In order to resolve the issue we set the virtualization threshold to the same value of the max selectable pagination.

Obviously this is an issue when you have to increase the pagination size to 1000 :)

After a lot of investigation I've been able to understand.
In my grid options there was the rowHeight written as string and not as integer.
The bad thing is that if you use a string, '30' for example, the row height become correctly 30 (so you think it isn't a problem) but the algorithm behind the virtualization threshold become completely broken.

Maybe it can be safer to add a check on rowHeight property or some kind of type enforcement.

**Comment by csvan** [comment]
Having this exact same problem, it's still an issue in 3.x
