### ISSUE TITLE
Cannot discard cell changes with Esc with angular 1.2

### ISSUE THREAD

**Issue by mrzasa** [angular-ui/ui-grid#1090]
This issue is related to in-place cell editing (Edit On Focus Cell Selection Example: http://angular-ui.github.io/ng-grid/#/cellSelection) -- after editing I cannot discard changes with Esc key.

Tested on browsers: FF 25, Chrome 30 (both linux)
Angular: 1.2.14, 1.2.15
ng-grid: 2.0.7

Steps to reproduce:

1. Edit a cell in grid (lets say there was a value A and we put there B).
1. Push Esc key.

Expected result: the cell returns to previous value (to value A).
Actual result: new value is still in the cell (cell contains value B)

Plunker: http://plnkr.co/edit/uJGfsGiYTjixxhsNtFUc?p=preview

The bug is not present when using with angular 1.0.

**Comment by swalters** [comment]
Closing Old 2.x issues as no one is maintaining it
