### ISSUE TITLE
 Cannot read property '$$phase' of null

### ISSUE THREAD

**Issue by alexkids24** [angular-ui/ui-grid#1104]
Uncaught TypeError: Cannot read property '$$phase' of null ng-grid.js:328
domUtilityService.digest ng-grid.js:328
domUtilityService.BuildStyles ng-grid.js:296
domUtilityService.RebuildGrid ng-grid.js:324
(anonymous function)

Always happens this error, when you switch or change the window.

Just check the object nullity of "$scope" and "$scope.$root"

Regards

Alex

**Comment by getuliojr** [comment]
Has it been fixed and where is the fix ?

**Comment by kashesandr** [comment]
Have the same issue.. Are there a fix for that?

**Comment by htetmyomyint** [comment]
I have same issue. There's no solution yet?
