### ISSUE TITLE
Group by column with boolean values shows 'null' for false

### ISSUE THREAD

**Issue by lario** [angular-ui/ui-grid#1168]
When grouping by a column with boolean values the grouping is not correct.

http://plnkr.co/edit/FeTf4DN7hIx7ZJSdQgTO?p=preview

When grouping by the 'test' column instead of getting 3 groups: 'true', 'false' and 'null' 'false' and 'null' are grouped together into 'null'

https://github.com/angular-ui/ng-grid/blob/master/src/classes/rowFactory.js#L198 should check if val != null

**Comment by swalters** [comment]
Closing old 2.x issue as all current development is on 3x. 

If someone really needs this fix for 2.x, my advice is to fork and fix it.  Sorry, I know it's not ideal, but it is the best we can offer with limited resources.
