### ISSUE TITLE
Re-sizing window or using the FlexibleHeightPlugin causes aggregate rows to forget their "collapsed" state 

### ISSUE THREAD

**Issue by mburbea** [angular-ui/ui-grid#1173]
If you look at the grouping example here:
http://plnkr.co/edit/Bo11ckeWFiMyJ4tyLVWC?p=preview
Group by name and then expand all groups.
If you then resize the panel it will collapse all the groups. 
The flexible height plugin can cause the same effect to happen.Also searching can make this happen.

The issue is that the re-size eventually cause the "getGrouping" method to be called which will kill the agg cache, causing all the aggregate rows to be recreated defaulting them to "collapsed".

**Comment by Ozius** [comment]
Hi,

Anyone found a solution for this? I am trying to understand the source but I have not managed to solve this.

**Comment by PaulL1** [comment]
I suspect that there aren't many (if any) people looking at it.  Most attention is on the new 3.0 version.

**Comment by swalters** [comment]
Closing old 2.x issue as all current development is on 3x. 

If someone really needs this fix for 2.x, my advice is to fork and fix it.  Sorry, I know it's not ideal, but it is the best we can offer with limited resources.
