### ISSUE TITLE
filterText give wrong results when column's cellFilter contain multiple filters

### ISSUE THREAD

**Issue by sorsh** [angular-ui/ui-grid#1185]
In columnDefs I define a column that have a cellFilter with multiple filters.
That column cell values get rendered correctly with these filters.

The problem 
When I assign text in filterText (example : "1"), the rows do not get filtered correctly. Rows that suppose to be visible disappeared.

This happen because "searchEntireRow" does not support multiple filters in cellFilter.

The problem in function "searchEntireRow" come from the following lines - 
if (c && c.cellFilter) {
                        s = c.cellFilter.split(':');
                        f = $filter(s[0]);
                    }
                    if (pVal !== null && pVal !== undefined) {
                        if (typeof f === "function") {
                            var filterRes = f(pVal, s[1]).toString();
                            result = condition.regex.test(filterRes);
                        } else {
                            result = condition.regex.test(pVal.toString());
                        }
                        if (result) {
                            return true;
                        }
                    }

When cellFilter = "filterName1:param1|filterName2:param2"
then s will be [filterName1, param1|filterName2, param2]
meaning the filtering will happen with filterName1 and "parm1|filterName2" as parameters.

**Comment by yccteam** [comment]
What do you think about using the columnsFilters feature for this?
https://github.com/yccteam/ui-grid/tree/columnsFilters 
It supports multiple filters...
