### ISSUE TITLE
3.0 and font icons

### ISSUE THREAD

**Issue by mg1075** [angular-ui/ui-grid#1196]
Please consider _dropping_ the use of `ui-grid` fonts.

If folks are going to use font icons, they most likely would use fontawesome icons. 
Having another set of font icons seems like a duplication of effort. 
Then on top of that, there's the issue of inconsistency in appearance on sites that 
now have to use both `ui-grid` icons and fontawesome icons. 

My two cents: seems like it would be best if `ui-grid` kept its focus on the grid and not on branching out into its own set of font icons. If it does have to have a dependency on font icons, it should have a dependency on fontawesome, rather than a smaller and less widely applicable set of its own.

**Comment by jbodeen67** [comment]
I'd settle for them to just work.

**Comment by PaulL1** [comment]
Have you looked at the font tutorial?  Are they working for you on the tutorials in general?  If so, it's likely that it's a problem in your installation.

**Comment by maxisam** [comment]
in case anyone use fontawesome, here is the less file to replace the icon less file


 [class^="ui-grid-icon"]:before, [class*=" ui-grid-icon"]:before {
  font-family: "FontAwesome";
  font-style: normal;
  font-weight: normal;
  speak: none;
 
  display: inline-block;
  text-decoration: inherit;
  width: 1em;
  margin-right: .2em;
  text-align: center;
  /* opacity: .8; */
 
  /* For safety - reset parent styles, that can break glyph codes*/
  font-variant: normal;
  text-transform: none;
     
  /* fix buttons height, for twitter bootstrap */
  line-height: 1em;
 
  /* Animation center compensation - margins should be symmetric */
  /* remove if not needed */
  margin-left: .2em;
 
  /* you can be more comfortable with increased icons size */
  /* font-size: 120%; */
 
  /* Uncomment for 3D effect */
  /* text-shadow: 1px 1px 1px rgba(127, 127, 127, 0.3); */
}

.ui-grid-icon-blank::before {
  width: 1em;
  content: ' ';
}


.ui-grid-icon-plus-squared:before {
    content: '\f0d4';
}
/* 'ì' */
.ui-grid-icon-minus-squared:before {
    content: '\f146';
}
/* 'ì‘' */
.ui-grid-icon-search:before {
    content: '\f002';
}
/* 'ì’' */
.ui-grid-icon-cancel:before {
    content: '\f00d';
}
/* 'ì“' */
.ui-grid-icon-info-circled:before {
    content: '\f05a';
}
/* 'ì”' */
.ui-grid-icon-lock:before {
    content: '\f023';
}
/* 'ì•' */
.ui-grid-icon-lock-open:before {
    content: '\f09c';
}
/* 'ì–' */
.ui-grid-icon-pencil:before {
    content: '\f040';
}
/* 'ì—' */
.ui-grid-icon-down-dir:before {
    content: '\f0d7';
}
/* 'ì˜' */
.ui-grid-icon-up-dir:before {
    content: '\f0d8';
}
/* 'ì™' */
.ui-grid-icon-left-dir:before {
    content: '\f0d9';
}
/* 'ìš' */
.ui-grid-icon-right-dir:before {
    content: '\f0da';
}
/* 'ì›' */
.ui-grid-icon-left-open:before {
    content: '\f053';
}
/* 'ìœ' */
.ui-grid-icon-right-open:before {
    content: '\f054';
}
/* 'ì' */
.ui-grid-icon-angle-down:before {
    content: "\f107";
}
/* 'ìž' */
.ui-grid-icon-filter:before {
    content: '\f0b0';
}
/* 'ìŸ' */
.ui-grid-icon-sort-alt-up:before {
    content: '\f160';
}
/* 'ì ' */
.ui-grid-icon-sort-alt-down:before {
    content: '\f161';
}
/* 'ì¡' */
.ui-grid-icon-ok:before {
    content: '\f00c';
}
/* 'ì¢' */
.ui-grid-icon-menu:before {
    content: '\f0c9';
}
/* 'ì£' */
.ui-grid-icon-indent-left:before {
    content: '\f03b';
}
/* 'î €' */
.ui-grid-icon-indent-right:before {
    content: '\f03c';
}
/* 'î ' */
.ui-grid-icon-spin5:before {
    content: '\f110';
}
/* 'î©¡' */

**Comment by jaredwilli** [comment]
@maxisam thank you, that helped me fix my issue!

**Comment by niks191991** [comment]
Hi,

I have a requirement of placing the sorting icons to left side of each column and I am able to do that by overriding the header cell template. However, I have another requirement of showing an icon(fa-sort) from font awesome when the data is not sorted. I am able to place an icon by overriding a grid directive(uiGridVisible) which was removing and adding a class. But still I don't have an option to include any custom or font-awesome icon. Any solution for this will be really helpful.

**Comment by artuc** [comment]
@maxisam you are one of the good guys.
Thanks, that helped a lot.

**Comment by fatifleu** [comment]
i cant fix it can someone help me to how to change to minus ou plus icon of ui-grid

**Comment by mportuga** [comment]
@fatifleu http://plnkr.co/edit/ZqW3v1O0dLeQCOfr7f1u?p=preview
