### ISSUE TITLE
Edit on focus on cell giving an error  n.focus is not a function

### ISSUE THREAD

**Issue by sreejithss** [angular-ui/ui-grid#1198]
Error: n.focus is not a function .link/<@http://localhost:8080/portal-mgr/lib/angular-ui/ng-grid.min.js:2 $RootScopeProvider/this.$get</Scope.prototype.$broadcast@http://localhost:8080/portal-mgr/lib/angular/angular.js:12220 n@http://localhost:8080/portal-mgr/lib/angular-ui/ng-grid.min.js:2 r@http://localhost:8080/portal-mgr/lib/angular-ui/ng-grid.min.js:2 createEventHandler/eventHandler/<@http://localhost:8080/portal-mgr/lib/angular/angular.js:2613 forEach@http://localhost:8080/portal-mgr/lib/angular/angular.js:310 createEventHandler/eventHandler@http://localhost:8080/portal-mgr/lib/angular/angular.js:2612

**Comment by wentwog** [comment]
I too was having the issue and including jquery before angular helped, thanks.
