### ISSUE TITLE
ng-grid or ui-grid? I am lost

### ISSUE THREAD

**Issue by Tyvain** [angular-ui/ui-grid#1200]
Hello,

I was using this configuration (it is working):
"ng-grid": "latest" in bower.json. (wich download the 2.0.11 version).

I would like to change for the 3.0 version so I changed into:
"ng-grid": "3.0"

It doesn't work an I see this error: "Failed to instantiate module ngGrid due to:"

Also it seems like the name of service is now ui-grid (I san this in package.json of ng-grid 3.0: "name": "ui-grid",   "version": "3.0.0").
But in the doc I still see ng-grid (here: https://github.com/angular-ui/ng-grid/wiki).

I am a bit lost lost:
- why is ng-grid lastest 2.0.1 when there is a 3.0 version?
- what is difference between ui-grid and ng-grid?
- why isn't it compatible (whatever version I put in my bower, it should work no?)

Thank you.

**Comment by uideveloperui** [comment]
hi, my project requirement is that we only use ui-grid. I understand that ui grid is a just a new version(ng-grid is older and ui-grid is newer). i am using UI-Grid as below 
 <div id="grid1" ui-grid="gridOptions"

But for pagination , i have written directive that uses  ng-class and ng-click.. are this part of ui-grid or ng-grid..with these directives am I still using ui-grid?
