### ISSUE TITLE
selectAll working as selectVisible why?

### ISSUE THREAD

**Issue by goldserg** [angular-ui/ui-grid#1203]
I use example from home http://angular-ui.github.io/ng-grid/
I want to select all rows on all pages, for this I changed the basic template

checkboxHeaderTemplate: '&lt;input class="ngSelectionHeader" type="checkbox" ng-show="multiSelect" ng-model="allSelected" ng-change="toggleSelectAll(allSelected, <b>true</b>)"/&gt;',

http://plnkr.co/edit/Kt3J9bRuYD0pxQ9grU3x?p=preview

why when you go to other pages (including back to the first page) - all rows are to be unselected, but selectAll checkbox still selected?

**Comment by syedrehman** [comment]
HI PauiL 1

Thank you very  much for your help to everyone here. I am facing the same issue. Could u please help me out
Thanks
