### ISSUE TITLE
Multiselect only if Ctrl-Key is pressed

### ISSUE THREAD

**Issue by tjamin** [angular-ui/ui-grid#1211]
It would be really nice if ng-grid would support a mode where multiselect only works if for example the Ctrl-Key is pressed.

There is a working but dirty solution: http://stackoverflow.com/a/19318301/1536921
A native feature of ng-grid would be much nicer.

**Comment by Daeamon** [comment]
`
            $scope.ctrl = false;
            angular.element($window).bind('keydown', function (e) {      
                if (e.ctrlKey)
                {
                   $scope.ctrl = true;
                }
            });    
            angular.element($window).bind('keyup', function (e) {      
                if (e.keyCode == 17)
                {
                   $scope.ctrl = false;
                }
            });

            $scope.rowClick = function (row, $event) {      
                var rowEntity = row.entity,
                    rowIsSelected = row.isSelected,
                    selectedRows = $scope.gridApi.selection.getSelectedRows();
                $timeout(function () {
                    if (!$scope.ctrl)
                    {
                            $scope.gridApi.selection.clearSelectedRows();
                            if (!rowIsSelected) {
                                $scope.gridApi.selection.toggleRowSelection(rowEntity);
                            }
                    } else
                    {              
                        $scope.gridApi.selection.toggleRowSelection(rowEntity);
                    }  
                });
            }
`
