### ISSUE TITLE
ng-blur doesn't work in editableCellTemplates in angular 1.2.16 (latest stable)

### ISSUE THREAD

**Issue by pipermatt** [angular-ui/ui-grid#1217]
http://plnkr.co/edit/JHFXPz?p=preview

It works fine in the text box below the grid, but not in the grid. When I set the angular version to 1.2.15 it works in both.

**Comment by AdamDiment** [comment]
Any more news on this? I'm on angular 1.3.14 and ng-blur is not working with ng-grid with a cell 
template editor
