### ISSUE TITLE
new ui.grid > 100% width question

### ISSUE THREAD

**Issue by j-walker23** [angular-ui/ui-grid#1234]
ng-grid has been awesome, thank you for the hard work. 

Quick question, will the new ui.grid have the 100% width responsiveness that ng-grid 2.07 had. With ng-grid i would just set a height, and the width would auto to the width of its parent. Sorry if i just missed it but It looks like the ui.grid examples all have hard coded widths is why is am asking.

**Comment by Apxdono** [comment]
Well when using width: 100% on grid element, and parent width changes via css ( eg hiding sidebar that leads to stretching content to full size) the resize plugin does jack..
