### ISSUE TITLE
Columns Stacked

### ISSUE THREAD

**Issue by terjokhin** [angular-ui/ui-grid#1237]
I tried the simplest example with my play 2 appication. And get this look
![nggrid](https://cloud.githubusercontent.com/assets/1447374/3227370/300cb810-f07a-11e3-8133-02ea7f02b8b7.png)

It's very strange, cause I have added angular/jquery as webjars, and ng-grid also as webjars. 

Columns look stacked and without styling.

**Comment by karunanithi** [comment]
Go to nggrid.css and check backgroud-image,ngGroupedByIcon  url, those got messed up when we use build tool. we don't use that so commented out, now no issue.   

/* Not in use but causing grid columns collapsing issue
.ngGroupIcon {
  background-image: url("data:image/png;
    base64,iVBORw0KGgoAAAANSUhEUgAAAA4AAAANCAYAAACZ3F9/AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAadEVYdFNvZnR3YXJlAFBhaW50Lk5FVCB2My41LjEwMPRyoQAAAEFJREFUKFNjoAhISkr+h2J5JDZODNXGwGBsbPwfhIGAA8bGh6HaGBiAGhxAGJmN");
  background-repeat: no-repeat;
  height: 15px;
  width: 15px;
  position: absolute;
  right: -2px;
  top: 2px;
}
.ngGroupedByIcon {
  background-image: url("data:image/png;
    base64,iVBORw0KGgoAAAANSUhEUgAAAA4AAAANCAYAAACZ3F9/AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAadEVYdFNvZnR3YXJlAFBhaW50Lk5FVCB2My41LjEwMPRyoQAAAElJREFUKFNjoAhISkr+R8LyaHwMDNXGwGBsbPwfhoGAA5mPDUO1oWpE52PDYE0g");
  background-repeat: no-repeat;
  height: 15px;
  width: 15px;
  position: absolute;
  right: -2px;
  top: 2px;
}*/
