### ISSUE TITLE
How to disable a row ?

### ISSUE THREAD

**Issue by Outlivier** [angular-ui/ui-grid#126]
Hi !
First, thanks for your good work on this grid.
I would like to disable a row based on certain item properties to prevent user to check or select a specific element.
I tried to return false in beforeSelectionChange (if item was not selected before), it works for selection, but not for the checkbox as the user can still check or uncheck the element.
Simplified example : http://plnkr.co/edit/P0uCVASjjedeab1mICmE
So how to disable a row ?
Thanks !

**Comment by liagnaiju** [comment]
Hi,I also neeed checkboxCellTemplate , but  i don't know how to use.
Could you give me an example?
Thanks!
