### ISSUE TITLE
Cannot read property 'find' of null

### ISSUE THREAD

**Issue by shader** [angular-ui/ui-grid#1277]
I'm getting an error when I use an ng-grid inside of a ui.router template and use the $state.go() method to transition:

TypeError: Cannot read property 'find' of null
    at self.setDraggables (ng-grid-2.0.11.debug.js:1040:37)
    at angular.js:14158:28
    at completeOutstandingRequest (angular.js:4337:10)
    at angular.js:4638:7

If I manually type in a different routing url, the error does not occur. When I use $state.go(), it seems that the relevant method is being called twice for each table, once with grid.$root = null, and once with it properly set. Since I have grids on both of the templates, I'm not sure if its the grids I'm replacing or adding that have the problem. Based on the fact that self.setDraggables only seems to be called from $on('$destroy'), its probably the former.

**Comment by ReinierGielen** [comment]
+1

**Comment by lethalsheeep** [comment]
+1

**Comment by imbalind** [comment]
I'm closing since we're not supporting 2.x anymore. If anyone is willing to take on this, feel free to fork.

**Comment by pk8848597** [comment]
wat？？
