### ISSUE TITLE
If the options of ng-grid changes, ng-grid will not apply it

### ISSUE THREAD

**Issue by freewind** [angular-ui/ui-grid#128]
I want to configure the ng-grid on runtime, but it won't apply to ng-grid.

See this demo: http://plnkr.co/edit/Dk2eFA?p=preview

In the modal, when I click the `change grid options` button, I replaced original data source, but nothing happens.

And also some other options e.g. `columnDefs`, I hope I can modify it and reflect it to ng-grid immediatly, because it's useful for a "grid designer" with ng-grid.

**Comment by masoom** [comment]
Hi @freewind  @timothyswt , I have ran into a similar issue with ng-grid where I want to update my column headers dynamically based on the user click. It works when I use a normal table with ng-repeat="heading in gridHeaders">{{ heading }}, but when I include ng-grid the grid cells becomes empty and the columns headers remain static.

Here is the JS Fiddle http://jsfiddle.net/masoom/svcxh6hu/7/

My problem on stackoverflow - http://stackoverflow.com/questions/29165191/ng-grid-angularjs-how-to-update-the-column-headers-in-ng-grid

**Comment by loykianos** [comment]
Greetings, I am trying to update my multiSelect option using this method, but it also doesn't seem to work. 

Basically, I just use something similar to this, gridOptions = { data: 'myData',  multiSelect: 'multiSelect }
and update $scope.multiSelect but with no success. The option is always true. 

Isn't this supposed to work for all grid options? It would be helpful either way. 

Thanks!

**Comment by PaulL1** [comment]
ng-grid or ui-grid?

If ui-grid, then I think the tutorial has an example of toggling multi-select on and off dynamically.

**Comment by loykianos** [comment]
Let me check, yeah, I am in the correct forum. Haha

So yeah, I need to make multiSelect dynamic, so I use it as shown above. A function changes $scope.multiSelect accordingly, but it doesn't seem to have any impact on the grid.

It definitely works on data for example, since I use filters, paging etc.

**Comment by PaulL1** [comment]
:-).  This forum covers both ui-grid and ng-grid.  And sometimes people aren't sure which one they have.  ng-grid is less well supported these days.  I would have thought you needed to change $scope.gridOptions.multiselect, but it's been a while since I used ng-grid.

**Comment by loykianos** [comment]
Oh right, but I do use ngGrid. If I remember correctly ngGrid was the older version which was renamed to ui-grid, or something? Would I maybe be better off switching to ui-grid? Sorry for going off-topic, but if ngGrid isn't supported anymore, better sooner than later.

**Comment by PaulL1** [comment]
In general, yeah, moving to ui-grid is a good idea.  ng-grid doesn't support angular 1.3 I think, let alone 1.4.  ui-grid (3.0) is due for release very soon, and is more flexible and has more configuration options than ng-grid.  There is a bit of work in the upgrade though, depending on how much you've used some of the more elaborate functions.  ui-grid.info has lots of info and tutorials.

**Comment by samson-zz** [comment]
I tried the approach mentioned here but when I specify columnDefs as a string, I get the error:
TypeError: f.options.columnDefs.forEach is not a function

Having the same issue where refreshing the grid shows the proper revised columnDefs but saveState does not see the new properties.
