### ISSUE TITLE
Creating ng-grids dynamically

### ISSUE THREAD

**Issue by ivanpg** [angular-ui/ui-grid#1294]
I have a problem creating ng-grids dynamically:

The next function loops through each element of $scope.dataSparqlResponses (each element is an array of data) and put the value of the iteration in $scope.dataSparqlAux. And $scope.dataSparqlAux is the variable used in the grids (data input). The problem is that in each iteration this variable ($scope.dataSparqlAux) is reassigned, so in the template I can only see the last grid with data.

controller.js
![problema1](https://cloud.githubusercontent.com/assets/4881660/3560944/5f18d18a-099c-11e4-94a2-63016a373ffc.png)

template.html
![problema2](https://cloud.githubusercontent.com/assets/4881660/3560948/acebb8a0-099c-11e4-9eed-94bf8095edfb.png)

is possible to do something like this?
![problema3](https://cloud.githubusercontent.com/assets/4881660/3560949/5ac390a6-099d-11e4-8a38-96509146372b.png)

How can I fix this to create grids and display information dynamically? 

Regards and thanks for your time.

EDIT: here a plunker with a sample of the problem http://plnkr.co/edit/zYtuMW4TKW053YoDY0kg?p=preview

**Comment by vishnumvn** [comment]
http://jsbin.com/yixom/5/watch?js,output
I can't able to open the solution. please paste in here.
