### ISSUE TITLE
How to change the grid width

### ISSUE THREAD

**Issue by freewind** [angular-ui/ui-grid#131]
Html code:

```
<div class="gridStyle" style="width:{{gridWidth}}px;height:800px" ng-grid="gridOptions"></div>
```

When I change the `$scope.gridWidth`, the grid won't be changed, unless I modify the `gridOptions.columnDefs`.

Is there any way to trigger the grid to let it resize? Or just make the grid resizeable?

**Comment by dpaul1031** [comment]
sorry to say... teh link above to teh plugins is a 404 error
position: absolute; doesn't work.  when you change the size of the container...
