### ISSUE TITLE
[Uncaught TypeError: Cannot read property 'style' of null] when resizing a column to outside the grid

### ISSUE THREAD

**Issue by tomcsmith1990** [angular-ui/ui-grid#1327]
Using ng-grid-2.0.11.min.js:

To reproduce:
1. Set 'enableColumnResize' to true in the grid options.
2. Click and hold the cursor down between two columns to resize the column.
3. Drag the cursor outside of the grid.
4. Release the cursor <== ERROR.

Expected behaviour: there is no error, and the column does not resize.
Actual behaviour: there is an error [Uncaught TypeError: Cannot read property 'style' of null], and the column does not resize.

The Plunker below illustrates this issue. With the console open to view Javascript errors, attempt to resize a column and release the cursor over the editor window (on the left hand side).

http://plnkr.co/edit/T6UgoFvhlH1jvAI3yK7z?p=preview

**Comment by wboyle01** [comment]
Unfortunately, this issue still persists in 2.0.14.
