### ISSUE TITLE
Row re-ordering feature (drag/drop to move rows)

### ISSUE THREAD

**Issue by swalters** [angular-ui/ui-grid#1359]
Add a feature that allows user to rearrange rows by drag/drop much like we do for drag/drop columns #946.

**Comment by goleafs** [comment]
just curious, is this one going to happen?

**Comment by PaulL1** [comment]
Only if someone builds it.  Nobody is currently working on it, so probably only if someone new decides to work on it and submits a PR.

**Comment by c0bra** [comment]
Honestly the only hard thing is making sure it plays nice with all thee other features. The actual drag and drop and reordering is pretty straightforward.

**Comment by tedhohio** [comment]
What about dragging and dropping from one instance of a grid to another?

**Comment by homerjam** [comment]
https://github.com/cdwv/ui-grid-draggable-rows

**Comment by PaulL1** [comment]
Wow, awesome.  I haven't tried it out, but you actually built a plugin using @c0bra's plugin architecture.  I think that makes you the first!!

**Comment by c0bra** [comment]
I think he used his own architecture, but @homerjam is definitely one of the first to write a plugin that I've seen!

**Comment by homerjam** [comment]
I'd love to take credit but this is actually @cdwv's work. I just posted it here as it seemed relevant and potentially useful. Would there be any possibility of integrating it? Or do you think its best as a plugin?

**Comment by c0bra** [comment]
I think best as a plugin. We're wanting to keep core as slim as possible, and honestly a lot of the features that we have currently would be best done as plugins.

**Comment by JLLeitschuh** [comment]
Should we consider adding a 3rd party plugin list to our readme?

**Comment by skrajewski** [comment]
I'm creator of https://github.com/cdwv/ui-grid-draggable-rows, project is maintained so if you have any questions or problems with the plugin please let me know - I will try to help you.

Many thanks to @homerjam for a lot of improvements!

**Comment by swalters** [comment]
closing as @skrajewski meets the requirements. A link to that repository has been added to third party features list.
