### ISSUE TITLE
Row template example not working?

### ISSUE THREAD

**Issue by axschech** [angular-ui/ui-grid#1368]
http://ui-grid.info/docs/#/tutorial/4.1_custom_row_template

I can't seem to get this code to work in my project, and it looks like it's broken on the site too.

Is it wrapped in a $timeout function because of the $http.get? Why not use a promise instead?

Also, the table doesn't seem to render when you apply a custom row template.

**Comment by mikila85** [comment]
ever solved this issue?

**Comment by FlavorScape** [comment]
Have the examples been updated? I can't get the row templates to show anything at all. Using the "default"
'<div ng-style="{\'cursor\': row.cursor, \'z-index\': col.zIndex() }" ng-repeat="col in renderedColumns" ng-class="col.colIndex()" class="ngCell {{col.cellClass}}" ng-cell></div>'

**Comment by ackimwilliams** [comment]
@FlavorScape are you still having an issue where where you are unable to set a custom rowTemplate?

**Comment by FlavorScape** [comment]
I was able to, but had to reference the src for the [templates](https://github.com/angular-ui/ui-grid/tree/master/src/templates/ui-grid). It's just that the example code no longer work, so I guess it's not a huge deal, other than the examples seem to exist in a few places, it's easy to miss this tidbit.

**Comment by ksgupta-adobe** [comment]
I am trying to use the default example given at https://github.com/angular-ui/ui-grid/wiki/templating for the row template. When I put that template as grid row template, I get nothing displayed. I can see the commented ng-repeat inside row for 'col in renderedColumns' as @c0bra commented above long back.  I am using angular "1.5.6" and ui-grid "3.2.9". Has this been fixed?
