### ISSUE TITLE
FireFox editableCellTemplate throws error when the cell is edited second time

### ISSUE THREAD

**Issue by Dhana-Krishnasamy** [angular-ui/ui-grid#1408]
I have a cell template of type number, It works normally when I click and edit first time. The second time on same cell throws (TypeError: current is null          angular.js:12923).  However same code works on Chrome and (even on) IE and older version of FireFox (v20).

There is another user who faced a same issue and his jsfiddle: http://jsfiddle.net/zlaja1983/38hPb/
http://stackoverflow.com/questions/23939184/firefox-editablecelltemplate-only-enabling-editing-one-time

AngularJS v1.2.21
ng-grid-2.0.12
jQuery v2.1.1
firefox v30

**Comment by alainbryden** [comment]
That's a shoddy way to close bugs. Yes, it's still a bug. All you have to do is take the fiddle we posted and update the link to angular js to see that.
