### ISSUE TITLE
Bug: scrollbars on MacOS not calculated correctly

### ISSUE THREAD

**Issue by adamchenwei** [angular-ui/ui-grid#1460]
See the tutorial's grid example, when scroll around the middle length, you will see the grid vertical line will mismatch between the heading divider and the data divider. I think that's a pretty critical appearance issue. Let me know anyone think its a quick solution for that!

I used Chrome on Mac

**Comment by Kamaraju333** [comment]
I still see the issue with 3.0.7 version , i dont scrollbars in Mac chrome
