### ISSUE TITLE
Allow dynamic resizing of grid when container changes width

### ISSUE THREAD

**Issue by ofairfoul** [angular-ui/ui-grid#1488]
With unstable version. When re-sizing the browser window the ui grid viewport width is fixed at its initial value. Even though the width is set to auto or percentage value.

**Comment by ravihegde** [comment]
@c0bra Nice module. However, 250ms polling is really heavy and the grid behaves sluggish on low end computers. I think a better thing to do will be to allow the users to notify grid about resize. A resize message broadcast directed to the grid should do the job. That will avoid polling.

**Comment by PaulL1** [comment]
There is already a method for that, called handleWindowResize I think.  If you are happy using that you should not need to use autoResize.

**Comment by icfantv** [comment]
For anyone seeing this, we were able to adequately solve this by using responsive CSS (@media) to define the width and height of the grid.  The best part about this solution is that it requires no resize event handling.

**Comment by sugir93** [comment]
most of the data in my table is hidden, how to show all the data in the grid itself, even if the string is too long also?

**Comment by iMolodec** [comment]
$(window).trigger('resize');

**Comment by ingenious-pawan** [comment]
ui-grid change height with when ever browser resized so you can trigger resize event using javascript window.dispatchEvent(new Event('resize'));

**Comment by ts46235** [comment]
I tried PaulL1's recommendation for using handleWindowResize but it did not work. the auto-resize directive does work for me but I'm using it just to fix the problem of when my grid is shown AGAIN after it has already been shown/rendered correctly and then hidden and re-shown (just table border and header blocking appear). I'd rather not have the timer running every 250ms and just run once after the div is visible again.

**Comment by zmrfzn** [comment]
I recently was trying to use this resize feature and found out that there is an issue with it. 
if we have set width in columnDefs, the grid is not resized and over flows the container itself. (attached screenshot). 
it does not happen when we have not defined the width in the columnDefs. 

![uigrid-autoresize-bug](https://user-images.githubusercontent.com/13682115/30819956-2b82fc54-a23e-11e7-9299-17979a86dd16.png)
