### ISSUE TITLE
Only 5 columns render when data and columns loaded asynchronously - current unstable

### ISSUE THREAD

**Issue by ofairfoul** [angular-ui/ui-grid#1497]
When columns and data are loaded asynchronously only the first 5 columns are rendered for the first row to arrive. Subsequent rows are rendered with the entire data.

```
module.exports = function(){

  var createRow = function(){
    var row = {};
    for(var j = 0; j < 50; j++)
    {
      row['col'+j] = 'data';
    }
    return row;
  }

  function GridController($scope, $interval){

      var that = this;

      $scope.gridOptions = {
        data: this.data,
        columnDefs: this.columnDefs
      };

      // load columns asynchronously
      $interval(function(){
        for(var i = 0; i < 50; i++){
          that.columnDefs.push({name:'col'+i, width:100});
        }
      }, 2000, 1);

      // load rows asynchronously
      $interval(function(){
        that.data.push(createRow());              
      }, 4000);
  }

  GridController.prototype.data = [];
  GridController.prototype.columnDefs = [];

  GridController.$inject = ['$scope', '$interval'];

  return GridController;
}();
```

Result
![2014-09-04 16_45_38-greenshot](https://cloud.githubusercontent.com/assets/6035375/4152050/4480fb52-344b-11e4-8b35-725a33629c36.png)

**Comment by johnedvard** [comment]
I am facing the same issue with the 4.0.2 version of angular-ui-grid. When I load data asynchronously I only get the first four columns visible. When I resize the last column all the way to the right, and scroll horizontally inside the grid, all the hidden columns appear. I tried using the gridApi.refresh() approach, but to no avail. 

The main difference is that I load all columns and all rows at the same time.

**Comment by johnedvard** [comment]
I upgraded to angular-ui-grid 4.0.4 and also angular 1.6.4, but I am still facing the same issue. I have the same behaviour as described in my previous comment.

Are there anyone who can confirm that the bug has vanished? Maybe I am doing something wrong on my end.

**Comment by j2kenton** [comment]
I am experiencing the same issue. An update would be very helpful :)
`v4.6.2`
(AngularJS `v1.6.10`)
Thanks!
