### ISSUE TITLE
CellTemplate for jquery-ui datepicker giving error Uncaught Missing instance data for this datepicker

### ISSUE THREAD

**Issue by manjunathvadavi** [angular-ui/ui-grid#1510]
when i use enableCellEditOnFocus:true,
The date picker giving the  error like "Uncaught Missing instance data for this datepicker in ng-grid"

http://plnkr.co/edit/6h5JIJeCkARNGWQgzeJ9?p=preview   

Please set enableCellEditOnFocus:true, in the gridOptions

**Comment by yrojha4ever** [comment]
http://plnkr.co/edit/h6yd2vR2xBJCthcxrLGr?p=preview is working.
How to make cell as normal text once value is set to input field from datepicker?
