### ISSUE TITLE
Create a columnDef.enableColumnMenu and GridColumn.enableColumnMenu

### ISSUE THREAD

**Issue by swalters** [angular-ui/ui-grid#1515]
colDef.enableColumnMenu should override gridOptions.enableColumnmenu.

@novice3030 will submit a PR for this

**Comment by mikacalvo** [comment]
you should update the wiki : https://github.com/angular-ui/ui-grid/wiki/Defining-columns
there is no mention of that option I just lost 15min to find it 😢
