### ISSUE TITLE
2.0: The easy way to modify row height dynamically？

### ISSUE THREAD

**Issue by yuezheng** [angular-ui/ui-grid#1523]
Hello.
This my current grid show via ng-grid:
![currentgrid](https://cloud.githubusercontent.com/assets/1791214/4245184/adf52bae-3a30-11e4-8435-58960d0f6d14.png)
There some text  was cut because it too long. I want to show unbroken data in each cell, so I add some style for grid:

```
.ngCell  {
  display : table-cell;
  height: auto !important;
  overflow:visible;
  position: static;
}
.ngRow {
  display : table-row;
  height: auto !important;
  position: static;
}
.ngCellText{
  height: auto !important;
  white-space: normal;
  overflow:visible;
}
```

After setted this style, the grid show like this:
![fullgrid](https://cloud.githubusercontent.com/assets/1791214/4245562/413b63ba-3a3b-11e4-91a6-779f4c325c4b.png)
The text show complete. But the style of grid goto irregularity.
Now I want achieve that effect: 
In general, after the grid loaded, it show like the frist picture above. If one cell's text too long, when mouse hover or on click, then heighten the row which current cell at, so that it could display complete data.

Now, I binded click event at a cell, to get parent row element in JQuery, then change it css like above.
The code just like:

```
cellTemplate: '<div class=ngCellText ng-click="transform($event)" ng-bind="row.getProperty(col.field)"></div>'

$scope.transform = (event) ->
  clicked = angular.element(event.target)
  targetRow = clicked.closest('div[class^="ngCell"]').parents('div[class^="ngCell"]').parent()
  // TODO: set new css style for the targetRow
```

This way is very complex, and can not achiev effect I wanted.
Is there a simple solution？

**Comment by github4es** [comment]
I'm currently using ui-grid - v3.0.7.  I'm also looking for a way to have all rows at a set height and when someone clicks on the cell, then resize the row to auto-height and wrapping the cell contents.  any ideas?

**Comment by hanishw** [comment]
Do we have a plunker for this? @yuezheng
