### ISSUE TITLE
Fit row height to content

### ISSUE THREAD

**Issue by mikhail-eremin** [angular-ui/ui-grid#157]
I found issue for that but it is closed now because of "there is a plugin" (https://github.com/angular-ui/ng-grid/issues/21). 
But what that plugin does in only make all table row heights bigger if table is too small for screen(and by the way it's very buggy in that work). It is not a solution at all!

Equal fixed height of row for whole table is a bad idea in case of inconsistent table data. For example, i can have a list in a cell, so row should have a bigger height, or there can be a picture, or it can be only a short strings so we don't need row to be very big. I can't hide contents to popover or so, ngGrid should have option to make it visible, like all tables do!

I was so happy when i found ngGrid, it's cool component, really thanx! :+1:  But dynamic row height issue is critical for our project, so i can't use it now(
Don't let us go back to jqGrid please

**Comment by juristr** [comment]
If you don't have the necessity of dynamic heights based on the cell content, then you can simply set the `rowHeight` property to whatever suits your needs

```javascript
 $scope.gridOptions = { 
    ...
    rowHeight: 35,
    ...
  };
```

**Comment by getuliojr** [comment]
I am still usina ng—grid ok some code, but have forked it to have dynamic rowHeight and os working Just fine.

**Comment by Asrapromact** [comment]
Can anyone please help me with this height problem in ui-grid . Have tried different css approaches , but nothing worked till now . Any help would be appreciated , Thanks 
![grid](https://cloud.githubusercontent.com/assets/10829543/11337070/20802e70-9210-11e5-8608-833e6cf73371.jpg)

**Comment by rupalkotak** [comment]
@getuliojr- i tried to make ur solution work for me but unfortunately it is not working..seems I am missing something.....how does the grid determine that the row height needs to be dynmic!..pls help

**Comment by getuliojr** [comment]
Have you tried the new version 3.x to check if it works for you ? I am only using this grid on my old apps. Have moved to material design already. When I patched the code I have not generated test cases so It was not accepted. If this grid is still being used and this solution is required I can fork its latest version with my patch. I am still using it on my old apps and it still works just fine.

**Comment by rupalkotak** [comment]
thanks for the reply. I don't think the UI grid also supports variable row height. I have pulled ur code from this location https://github.com/getuliojr/ng-grid. I could not understand how you are telling the grid to have dynamic height for each row...can you tell me a brief overview of the solution...
