### ISSUE TITLE
3.0: Feature: saveState

### ISSUE THREAD

**Issue by PaulL1** [angular-ui/ui-grid#1572]
A feature that allows the grid state to be extracted, including filters, sorts, column orders (once they're changeable), visible columns, column widths, and perhaps selected column/row.  

A matching method that allows that state to be reapplied to the grid.  

This would allow an application to request the grid's current state, and store it somewhere.  On returning to the page it could reapply that state.

It would also be useful to extract information such as column widths or filters if some custom work was being completed.

**Comment by kolesnik** [comment]
Please, create release with this feature

**Comment by webia1** [comment]
+1 That's a must be feature,..

**Comment by PaulL1** [comment]
I think was done in 2014, this is a very old issue and this functionality went production a long time ago.

**Comment by webia1** [comment]
thanks to your proposal, I think,..

**Comment by LeonanCarvalho** [comment]
We already have this feature in the stable release?
