### ISSUE TITLE
3.0: i18n doesn't change on change of language

### ISSUE THREAD

**Issue by PaulL1** [angular-ui/ui-grid#1583]
In the i18n tutorial we provide a dropdown for people to select alternate languages.  The page itself changes, but none of the headers nor menu items appear to change.  There is a TODO note on the page saying that we still need to deal with headers refreshing, it's not clear to me whether that was expected to also apply to menu items.

Probably low-priority, because it probably works fine on initial render, and it's unlikely that many users would change language on the fly.

**Comment by TMadMac** [comment]
It's just what I need today : dynamically change language.

From now, pagination footers and column headers (for which I provide a translation) are not translated when calling i18nService.setCurrantLanguage()

**Comment by totszwai** [comment]
how do we set the grid to a specific language at start up? the example seems to set the grid wrapper to a specific language.

**Comment by PaulL1** [comment]
The tutorial covers that.
