### ISSUE TITLE
[3.0] ui-grid 'ui.grid.selection' messing up grid display

### ISSUE THREAD

**Issue by juliekirwin** [angular-ui/ui-grid#1601]
I'm trying out the ui.grid.selection on my grid and it's behaving oddly(see picture below). My code is very bare bones at this point so not sure what would be breaking it if it's on me. I followed the tutorial http://ui-grid.info/docs/#/tutorial/210_selection

Controller:

``` Javascript
$scope.shiftGrid = {
        enableSorting: true,
        enableFiltering: true,
        enableCellEditOnFocus: true,
        enableRowSelection: true,
        columnDefs: [
          { field: 'ShiftID', displayName: 'Shift ID', type: 'number', width: '20%', enableCellEdit: true },
          { field: 'ShiftDesc', displayName: 'Description', type: 'string', width: '50%', enableCellEdit: true },
          { field: 'Capacity', displayName: 'Capacity', type: 'number', width: '30%', enableCellEdit: true },
        ]
    };

    $scope.shiftGrid.multiSelect = true;
```

HTML:

``` HTML
<div ui-grid="shiftGrid" ui-grid-selection ui-grid-edit ui-grid-cellnav class="myGrid"></div>
```

Here's the picture:
![image](https://cloud.githubusercontent.com/assets/3643156/4405409/9f3cc31c-44ba-11e4-87ae-809f34a46b16.png)

**Comment by RedDroid** [comment]
This issue still exists in chrome. it works fine in other browsers but it still seems to appear in chrome.

**Comment by jfuehner** [comment]
I see this as well in FireFox. Any update or workaround? I'm using v3.0.0-RC.18-270d031. Also, when I view the selection tutorial on the ui-grid.info site it's jacked up too...

**Comment by naijenn** [comment]
I'm using v3.0.0-RC.20 and having this issue on Mac OS 10.8.5 and 10.10 using FF, Chrome, and Safari

It the best case its glitchy.

**Comment by plessbd** [comment]
I am also having this issue, I have found that it seems to be fine if you specify the data at the creation of the grid, but when you load the data through an ajax call after the controller loads it causes the grid to not display properly until a window resize.
