### ISSUE TITLE
The ability to remove the 'Hide Column' option in the column menu

### ISSUE THREAD

**Issue by wattsbn** [angular-ui/ui-grid#1604]
As the title suggests, I would like the ability to remove the 'Hide Column' option from the column drop down menu. I really want to turn it off for all my columns, but I would imagine being able to turn it off per column would be more flexible for other people. The docs provide an example of how to add more options to the menu, but not a way to remove the built-in ones. Since there doesn't seem to be a built-in way to add the columns back, I don't really want to give the users a way to remove them. I would also like the ability to remove the 'Remove Sort' menu item. One of my grids only has one sortable column and it doesn't really make sense to be able to remove the sort direction in that case.

I think the best solution would be to allow us to override the built-in menu items in the column menu both globally and for individual columns. This would let us remove menu items that we don't want (like 'Hide Item'), provide icons that match our applications theme, or allow for us to use different localization implementations. However, this is also probably the most work, and I really only need the ability to remove specific menu items for now.

**Comment by Jangular** [comment]
I'm just learning Angular & UI grid, a follow-up question, can the angle-down icon be completely disabled or hidden so users can't do any sorting, etc. Thanks.

**Comment by PaulL1** [comment]
If you disable sorting on the grid - refer the gridOptions in the api documentation: http://ui-grid.info/docs/#/api/ui.grid.class:GridOptions

**Comment by BrianHutchison** [comment]
Agreed with @Jangular, would like some way to not show any menu options or icons on the column heading. I have a column where clicking on the icon takes you to a different page, and its not appropriate to sort it, hide it, move it, etc.

**Comment by j2L4e** [comment]
As it took me some time to figure it out and most of my google searches turned up this page:

The column hiding can be disabled by setting

`enableHiding = false` on the column's colDef.

**Comment by cortezcristian** [comment]
thanks @j2L4e

**Comment by Hasnaa-Ibraheem** [comment]
Would you please add this option: "enableHiding = false" on grid level, not only columnDef level?
Also I'd appreciate that you remove the reserved empty space for "Hide Column" option if the option is disabled.
Thanks in advance.

**Comment by mmilito** [comment]
Hi, just checking also on the ability to re-add a hidden column without refreshing the page?

**Comment by Hasnaa-Ibraheem** [comment]
Hi mmilito
You can add a column without refreshing the page by adding this line to your script:
$scope.gridApi.core.notifyDataChange( uiGridConstants.dataChange.COLUMN );
I tried it and it works fine with me, check the tutorial website: http://ui-grid.info/docs/#/tutorial/113_adding_and_removing_columns

**Comment by kr99** [comment]
A grid-level option for this would make a lot of sense.

**Comment by HaakonH** [comment]
This would be great to have, so reposting as I need as well:
 :+1: I'm just learning Angular & UI grid, a follow-up question, can the angle-down icon be completely disabled or hidden so users can't do any sorting, etc. Thanks.

**Comment by mariohmol** [comment]
enableHiding = false is not working for me.. tested in column and grid level..

 ```
  $scope.gridOptions = {
          appScopeProvider: this,
          enableHiding: false,
          data: []
      };


$scope.gridOptions.columnDefs = [{
          name: 'topic',enableHiding: false,

```

I had to fix this manually:

 ```
.ui-grid-column-menu-button{
  display: none;
}
```

**Comment by mariohmol** [comment]
Tested using `gridMenuShowHideColumns` as http://ui-grid.info/docs/#/api/ui.grid.class:GridOptions ..  do not work as well

**Comment by Olegarius** [comment]
Hi guys.
Can I propose again my working solution for this case?
First, we must override some method from ui-grid.
```
(function () {
    'use strict';

    angular
        .module('ui.grid')
        .service('UIGridOverrideService', ['uiGridColumnMenuService',
          function (uiGridColumnMenuService) {
              //overriding ui-grid service methodfor column menu customization
                uiGridColumnMenuService.setColMenuItemWatch = function ($scope) {
                    var deregFunction = $scope.$watch('col.menuItems', function (n) {
                        if (typeof (n) !== 'undefined' && n && angular.isArray(n)) {
                            n.forEach(function (item) {
                                if (typeof (item.context) === 'undefined' || !item.context) {
                                    item.context = {};
                                }
                                item.context.col = $scope.col;
                            });

                            $scope.menuItems = n;
                        }
                        else {
                            $scope.menuItems = $scope.defaultMenuItems;
                        }
                    });

                    $scope.$on('$destroy', deregFunction);
                }
          }]);
})();
```
Next, include UIGridOverrideService to your controller. And use it in the grid. For example:
```
    angular
      .module('app')
      .controller('BetsController', ['$rootScope', '$scope', 'UIGridOverrideService',
          function ($rootScope, $scope, UIGridOverrideService) {

//generate column menu
               function getColumnMenuItems() {
                  var columnMenuItems = [{
                      title: 'Hide Column',
                      icon: 'ui-grid-icon-cancel',
                      action: function () {
                          var columns = $scope.gridOptions.columnDefs;
                          columns.forEach(function (item) {
                              if (item.name == this.context.col.name) {
                                  item.visible = false;
                              }
                          });

                          $scope.gridApi.grid.refresh();
                          if ($scope.subGridApi) {
                              $scope.subGridApi.grid.refresh();
                          }

                      }
                  },
                  {
                      title: 'Show All Columns',
                      icon: 'ui-grid-icon-menu',
                      action: showColumns
                  }];
                  return columnMenuItems;
              }
             //..... grid initialization

              $scope.gridOptions = {
                  enableColumnMenus: true,
                  columnDefs: [
                    {
                        name: 'Date',
                        displayName: 'Bet Date',
                        width: 180,
                        menuItems: getColumnMenuItems()
                    },
                    {
                        name: 'Id',
                        displayName: 'Bet ID',
                        width: 100,
                        menuItems: getColumnMenuItems()
                    },
                    //.....
             }
            //...... set grid data and other your code
           function showColumns(){
                //your code for showing all grid columns
           }
}

```
You can also use the same way to add custom sorting or something else.
Hope, somebody it helps.

**Comment by adamjaffeback** [comment]
I'm still seeing this as an issue with 4.4.9. I've tried the following [grid-level (GridOptions)](http://ui-grid.info/docs/#!/api/ui.grid.class:GridOptions) solutions, per documentation, to hide the "X Hide Column" dropdown on a column:
- gridMenuShowHideColumns = false, credit https://github.com/angular-ui/ui-grid/issues/1604#issuecomment-232694423. [Plunkr](http://embed.plnkr.co/SGEnov/)
- enableGridMenu = false.

The following solutions work as [column-level (GridOptions.columnDef)](http://ui-grid.info/docs/#!/api/ui.grid.class:GridOptions.columnDef) options:
- enableHiding = false [Plunkr](http://embed.plnkr.co/zVtbG3T14oTKmtWiEj4P/)
- enableColumnMenu = false
