### ISSUE TITLE
Hide scroll bars when they are not being used

### ISSUE THREAD

**Issue by wattsbn** [angular-ui/ui-grid#1618]
You can look at the simple example provided in the docs.
http://ui-grid.info/docs/#/tutorial/101_intro

In that example, both scroll bars are disabled because the content is neither long enough nor wide enough for them to be used. I think it would look much better to dynamically hide them when they are not needed. Typically I could just mess with a couple overflow css properties and get my desired effect, but I can't do that here since you are using custom scroll bars.

**Comment by henry74** [comment]
Under enableHorizontalScrollbar it says:

enableHorizontalScrollbar

uiGridConstants.scrollbars.ALWAYS by default. This settings controls the horizontal scrollbar for the grid. Supported values: uiGridConstants.scrollbars.ALWAYS, uiGridConstants.scrollbars.NEVER

But uiGridConstants is not defined.  What's the proper way to remove horizontal scrollbars now?

**Comment by henry74** [comment]
I've also tried:
```
enableHorizontalScrollbar: false
```
Still shows up.

**Comment by PaulL1** [comment]
This issue is closed, so it's not that likely to get a response.

**Comment by henry74** [comment]
Figured it out from here: http://stackoverflow.com/questions/26937776/using-ui-grid-constants-to-disable-scrollbars

Need to inject uiGridConstants into your controller if you want to use it.
