### ISSUE TITLE
selectItem(index, state) / selectRow(index, state) functions have unexpected behavior

### ISSUE THREAD

**Issue by OrenHasbani** [angular-ui/ui-grid#1635]
I build a component that you can move items from one group to another. the component has 2 groups, each one of them displayed as nggrid. i want to show the items that have been moved so after the transfer i use the selectRow function to select them. unfortunately sometimes the grid select more items (including the items that i wanted). 
first i thought it is related to the fact that the grid was filtered (by filterOptions.filterText='someFilterString'), but then i understaned that it happened also when the grid is scrolled down. 
I had to go inside nggrid (v2.0.13) code and than i saw that selectRow function goes over rowCache array (in the same length as gridoptions.data) and if an item in the array has a clone (attribute that represent another item), the function select the clone as well. from debugging i understand that more or less a clone of an item is an item that the grid displays right now or in the last moment.

Why there is such a mechanism? i couldn't find a thread that talks about it. it would be great if someone will tell me that i do something wrong :) and if not, its a bug?

Thanks, 
Oren.

**Comment by imbalind** [comment]
I'm closing since we're not supporting 2.x any longer. If anyone is willing to take on this, feel free to fork.
