### ISSUE TITLE
Toggle all selected/unselected

### ISSUE THREAD

**Issue by wattsbn** [angular-ui/ui-grid#1636]
Currently when you enable the selection as described in the docs ([210](http://ui-grid.info/docs/#/tutorial/210_selection)), there is a selection column that is added to the grid. This column looks nice and I would like to use it. However, I would like to add a checkbox in the header to select/unselect all the rows. Since I am not the one defining the column definition, I cannot supply my own headerCellTemplate. I would be willing to make my own selection column, but I would need to hide the one that gets auto added by the directive.

I would like one of the following:
- Have the toggle all selected/unselected checkbox in the header built-in the selection column
- Let me change the headerCellTemplate of the selection column before the grid gets rendered
- Add a way to keep the selection api without adding the selection column to the grid

**Comment by tzweiner** [comment]
How can I programmatically check/uncheck the Select All checkbox at header row?

Here's my scenario. 
I'm loading the grid with rows in it. I click the Select All checkbox and everything works as expected. I go to next page. None of the rows there are selected, as expected, but the Select All checkbox at the top is still selected. The "ui-grid-all-selected" class is not removed on pagination. So I need to a way to unselect it.

Thanks.

**Comment by PaulL1** [comment]
I think there's a select all method in the api for selection.

**Comment by tzweiner** [comment]
Are you talking about selectAllRows? This will select all (visible) rows in the grid. I don't necessarily want to do that after paging. 

Unless maybe you're implying that once the header checkbox is clicked, it pretty much means that user intends to select all rows even those on subsequent pages (loaded via external pagination), for which I'd have to call the selectAllRows method to select those newly loaded rows. That makes it ok then for the header checkbox to stay selected.
In that case, is there a method to check if the header checkbox has been clicked?

**Comment by tzweiner** [comment]
Here's a plunkr of what i'm describing.
http://plnkr.co/edit/8sSShyUIk1gF10O5rrHX?p=preview

Click the header checkbox. - That will select all rows
Go to page 2
See how all rows are unselected but the header checkbox is still selected. I'd like that to also be unselected.

**Comment by tzweiner** [comment]
oh, i just saw this in the documentation:

Note that the selectAll does not watch for new data, so if you are using the selectAll
function and you add data to the grid, you need to check `grid.api.selection.getSelectAllState`, and if it is currently
ticked, then manually call `grid.api.selection.selectAllVisibleRows` after your data has been added.

**Comment by tzweiner** [comment]
This is probably ok for many use cases but for our scenario with external pagination this is not the best scenario because the user ends up selecting rows that are not yet retrieved.

**Comment by PaulL1** [comment]
I think there are two possible "sensible" uses:
1. Consider selectAll to mean "select everything in this grid, including things I can't see".  In that case, when you load more data externally, you need to check the selectAll state, and select the newly loaded rows appropriately.

2.  Consider selectAll to mean "select everything in this current page".  In that case, you need to clear the selectAll box upon pagination, so you'd need to call `clearSelectedRows` upon loading a new page.  http://ui-grid.info/docs/#/api/ui.grid.selection.api:PublicApi

**Comment by tzweiner** [comment]
Correct. The second case you describe is what I was looking to implement - "select everything visible on this current page". That's when I ran into the issue of the select-all checkbox at the header row being always selected, and then I asked the question here how to toggle it.
See my plunkr that shows what I'm talking about.
http://plnkr.co/edit/8sSShyUIk1gF10O5rrHX?p=preview

I need a way to also uncheck the select-all checkbox at header row.

**Comment by lebolo** [comment]
Was there a solution to this? Particularly @PaulL1's second scenario:

> Consider selectAll to mean "select everything in this current page". In that case, you need to clear the selectAll box upon pagination, so you'd need to call clearSelectedRows upon loading a new page. http://ui-grid.info/docs/#/api/ui.grid.selection.api:PublicApi

`clearSelectedRows` doesn't work because the user may have previously selected rows on the new page (assuming you externally handle which rows are selected via some other key/identifier) and I don't want to clear them. Instead, if not all rows are selected on the new page, then I'd like to just deselect the "select all" icon (or possibly set `grid.selection.selectAll = false` so that the directive/ng-class logic can handle it).

**Comment by kerendot** [comment]
Trying my luck... is there any solution for this?  -> 
"a way to uncheck the select-all checkbox at header row."
I am also struggling with a case that "selectAll" is checked, and then the view changes (more rows are added due to data loading or to filter changing),  so now the "selectAll" shouldn't be checked. Is there a way to programmatically toggle it?
