### ISSUE TITLE
grid refresh events

### ISSUE THREAD

**Issue by pr1ntr** [angular-ui/ui-grid#1641]
Not sure where else to look for the answer to this. I can't for the life of me figure out how to get an event for when the grid is done rendering. Is there some way to do this? I am trying to apply some jquery stuff on elements inside the grid, but alas dont know when they are ready.

**Comment by cfsilence** [comment]
This issue is not resolved.  rowsRendered and renderingComplete are firing before the row elements are available in the DOM.  Can this be reopened?

Here's a test case (check console output):

http://jsfiddle.net/xaw6k6m0/

**Comment by nadavelyashiv** [comment]
+1

**Comment by vincent-ollivier-everysens** [comment]
+1
This is always a hard problem ! It leads to some crash on my production App, probably on slow computers. 
Because some filtering has to be made ***after*** Grid is rendered !

**Comment by nadavelyashiv** [comment]
A not very good alternative I use now because of this issue, is $watch the actual HTML within the grid, look for '.ui-grid-row' elements, and once I find them I remove the $watch. Very consuming but I couldn't get anything else to work.
