### ISSUE TITLE
Row selection by double click

### ISSUE THREAD

**Issue by gwin003** [angular-ui/ui-grid#1646]
Previous versions of ngGrid allowed for row selection whenever you double clicked on any cell in a particular row. It would be nice to have this feature implemented in v3.

I believe current double clicking on an editable grid will allow the user to edit that cell? Depending on the gridOptions, it would be nice to specify what the double click functionality is. If 'ui-grid-edit' is not present on the grid, the default functionality should be selection on double click. 

One click on a cell in the row highlights the whole row, double click fires some selection event for that row..

**Comment by smithscripts** [comment]
I also have a need for double clicking on the entire row not just the cell. I need to pass the entire row entity when the user double clicks on the row, not just cell specific information.  Any examples of this?

P.S. Not everyone is using this grid for mobile apps...

**Comment by gwin003** [comment]
Here is the solution I used: http://developer.the-hideout.de/?p=113

Basically it is registering a plugin in ngGrid that watches for double clicks within the grid viewport. When the double click event is fired, it grabs the first selected row and sees that as the row that was double clicked.
