### ISSUE TITLE
Fire event to controller from ui-grid?

### ISSUE THREAD

**Issue by mmuruev** [angular-ui/ui-grid#1674]
I have something like this 

``` html

   $scope.clicker = function(id){
    alert ("Has been clicked", id);
    console.log('Id',id);
  };
  $scope.gridOptions = {
    enableSorting: true,
    columnDefs: [
      { field: 'name', 
         cellTemplate: '<div class="ui-grid-cell-contents"><span><a ng-click="clicker(row)">{{COL_FIELD}}</a></span></div>' },

```

 But it never show me any <a> in the grid as my clicker() never invoked. Is this a bug?

**Comment by henry74** [comment]
The external scopes documentation seems to be empty (http://ui-grid.info/docs/#/tutorial/305_externalScopes) Where can I read to understand how to use this functionality?

**Comment by PaulL1** [comment]
It has been replaced by appScope.  http://ui-grid.info/docs/#/tutorial/305_appScope

**Comment by henry74** [comment]
For others that run into this - I found my answer here: https://github.com/angular-ui/ng-grid/wiki/Templating

**Comment by henry74** [comment]
@PaulL1 Thank you.  Looks like the Templating wiki is a bit dated as well.  I'll switch to appScope - appreciate the redirection.

**Comment by saurabhkohli** [comment]
Please put a redirection from getExternalScope() page reference to the appScope page. It might help new users like me to reach the correct page. Thanks in advance.
