### ISSUE TITLE
Disable "toggle" for row selection?

### ISSUE THREAD

**Issue by pimenovoleg** [angular-ui/ui-grid#1714]
I want only "select" current row (without "unselect" by click again). How its possible ?

thanks.

**Comment by dalbir** [comment]
If row is already selected (Set from saved list) and we want to prevent  user for unselect then you can try this :

gridApi.selection.on.rowSelectionChanged($scope, function (row) {
            if (!row.isSelected) {
                if (row.entity.is_disabled == 1) {
                    row.isSelected = true;
                }
            }}
