### ISSUE TITLE
Race condition: onRegisterApi

### ISSUE THREAD

**Issue by smajl** [angular-ui/ui-grid#1717]
E.g. http://ui-grid.info/docs/#/tutorial/308_external_filtering is not working because `gridApi.core` is not ready when `onRegisterApi` callback executes.

The example uses `$interval` to overcome this (like rly?), but you need to set the delay to 500ms or so to make it work.

Using `$interval` is madness, so does anyone have some **proper solution** or is it planned to sync `onRegisterApi` callback with other critical parts of the module? Thanks.

**Comment by AnirudhaGohokar** [comment]
Thanks Paul. Setting timeout to 0 has solved the issue when using `ng-if`.

    $interval(function () { $scope.gridApi.core.notifyDataChange(uiGridConstants.dataChange.COLUMN); }, 0);

**Comment by seasagar** [comment]
can onRegisterApi function capture event occur inside cellTemplate?
O have a cell template with text field and I want to read old value and new value using "beforeCellEdit" and "afterCellEdit" event.
I believe onRegisterApi does not work with template(header template or cell template)
