### ISSUE TITLE
Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by vondrc** [angular-ui/ui-grid#1741]
Hi, I am using ui-grid in my app and getting this error.

My grid settings:

``` javascript
gridCtrl.controller('gridCtrl', ['$scope', '$http', function ($scope, $http) {
        $scope.gridOptions = {
            enableColumnResizing: true,
            enableSorting: true,
        };

        $http.get('ticket-list-data.json').success(function (data) {
            $scope.gridOptions.data = data;
        });
    }]);
```

``` html
<div id="grid1" ui-grid="gridOptions" class="gridStyle"></div>
```

Here is whole error mesage.

TypeError: Cannot read property 'data' of undefined
    at new <anonymous> (http://localhost:8383/app/bower_components/angular-ui-grid/ui-grid.js:2250:41)
    at invoke (http://localhost:8383/app/bower_components/angular/angular.js:3966:17)
    at Object.instantiate (http://localhost:8383/app/bower_components/angular/angular.js:3977:23)
    at http://localhost:8383/app/bower_components/angular/angular.js:7281:28
    at http://localhost:8383/app/bower_components/angular/angular.js:6670:34
    at forEach (http://localhost:8383/app/bower_components/angular/angular.js:332:20)
    at nodeLinkFn (http://localhost:8383/app/bower_components/angular/angular.js:6657:11)
    at delayedNodeLinkFn (http://localhost:8383/app/bower_components/angular/angular.js:6933:11)
    at compositeLinkFn (http://localhost:8383/app/bower_components/angular/angular.js:6105:13)
    at nodeLinkFn (http://localhost:8383/app/bower_components/angular/angular.js:6705:24)

**Comment by alokkarma** [comment]
Remove this comma (,) which is after true. enableSorting: true,
It will work fine

**Comment by kevin-friedheim** [comment]
@qazimir  did you feel like an idiot when this happened to you? I sure did! :anguished:

**Comment by uoc1691** [comment]
Does this means we can't use the ui-router and use the controller instantiation in the state. I'm having issues when I do this. I have a console error : Cannot read property 'data' of undefined. But the data is populated.

**Comment by PaulL1** [comment]
That error typically means you've defined your data object incorrectly, or on the wrong object.  It's a standard javascript error, and it says that it's attempting to find the property "data" on an object that is undefined at the time it's trying to access it.  Have you followed the examples closely?

**Comment by uoc1691** [comment]
html
`<div id="grid1" ui-grid="catController.gridOptionsCategories" class="grid"></div>`

controller
`(function(){
    "use strict";

    angular.module('ngAdminConsoleApp').controller('CategoryController',
        [
            '$rootScope', '$log', 'CategoryDataService', '$q',
            function ($rootScope, $log, CategoryDataService, $q) {
                var ctrl = this;

                $log.debug('CategoryController initialized!');

                ctrl.gridOptionsCategories = {
                    enableSorting: true,
                    data: []
                };                

                CategoryDataService.getCategories().then(function (response) {
                    ctrl.categories = response.result.categories;
                    ctrl.gridOptionsCategories.data = ctrl.categories;
                });

                //ctrl.categories = categories;

                //ctrl.gridOptionsCategories = {
                //    enableSorting: true,
                //    columnDefs: [
                //        { name: 'Name', field: 'name' },
                //    ],
                //    data: ctrl.categories
                //};

            }
        ]);

})();`

**Comment by PaulL1** [comment]
I don't see catController defined anywhere?

**Comment by shershen08** [comment]
having same issue, does **ui-grid** work without **controllerAs** syntax ?

**Comment by mbokil** [comment]
It does work with contollerAs syntax. I am using it currently with UI Router. I found you must set the gridOptions at the scope level first if you are adding data via REST. 

```
//in your controller
var vm = this;
vm.gridOptions = {};

//in your HTTP callback
vm.gridOptions.data = res.data;

//HTML
<div id="grid1" ui-grid="myControlerAsName.gridOptions" class="grid"></div>
```

**Comment by rockbass2560** [comment]
Thanks @mbokil , your solution worked for me.

**Comment by thargenediad** [comment]
Also, make sure your ui-grid directive value...

        <div ui-grid="gridOptions"></div>

...matches the name of your options object:

        $scope.gridOptions = {};

🤦
