### ISSUE TITLE
how to set column width autofit

### ISSUE THREAD

**Issue by byunru** [angular-ui/ui-grid#1771]
target 3.0.0-rc

I need a way for dynamic data that to populating a grid, based on some input, the number of columns return from server will be different, in this case, how to set column width as autofit, fit with longest data or column name.

**Comment by PaulL1** [comment]
This is a useful request, but not really in the current roadmap.  We have far too many good ideas in the repository already, giving the impression that we have a project riven with defects.  This also seems a pretty low volume requirement - having columns automatically grow would have some issue when your data can be of unknown width - most UI designers would be reluctant to do this.  Wrapping would be more useful.

Accordingly, I am leaving the enhancement tag on this, but closing it.  If someone would like this functionality, we'd welcome a pull request that adds it.

**Comment by Den-dp** [comment]
Hey there,
I wanna create a `plugin` which should add the "autofit" functionality as described there.

For now I have more less performant solution for calculating the optimal widths. This is basicaly a function which accepts `gridOptions.colDefs` and `gridOptions.data` and returns modified `colDefs` with pre-calculated width.

But I'm curious what is the best place to put this logic? So I'm serching for a convenient callback (or something like that) in ui-grid api, which
* fires when the data is rendered
* and also has an access to both `colDefs` and `data`

**Comment by csvan** [comment]
+1
