### ISSUE TITLE
Hiding and styling scrollbars

### ISSUE THREAD

**Issue by bgaisford** [angular-ui/ui-grid#1772]
I've been unable to hide the horizontal scroll bar, is it possible hide scroll bars via grid options?  In addition, is it possible to style the scroll bars?

**Comment by PaulL1** [comment]
I think all the scrollbar logic has changed substantially, so I'm putting this back into the pool.

**Comment by bgaisford** [comment]
*sigh*

**Comment by yorch** [comment]
Any plans to allow scrollbar style customization (outside of what's supported by the browser)?

**Comment by nkoterba** [comment]
👍 On allowing styling of scrollbars or at least a tutorial on how to do it.

In the past, you would bring in usually a Jquery Scrollbar container and hook it up to the element container but I'm not sure if that's even possible with angularjs.

**Comment by mobichel** [comment]
@nkoterba,

Here is example how to modify html & less to get styled scrollbars: #5951

**Comment by mobichel** [comment]
Here is example how to stlye scrollbar without modification in ui-grid: [https://jsfiddle.net/mobichel/qpnfL06n/4/](url)
