### ISSUE TITLE
Force grid to resize dynamically

### ISSUE THREAD

**Issue by bakayolo** [angular-ui/ui-grid#1774]
QUID about a possibility to force the grid to resize without need to use "ui-grid-auto-resize" which impact performance because of timer (just need to resize first time grid is loaded) ?

**Comment by miwillhite** [comment]
I also have the problem where `onRegisterApi` is not getting called. I am explicitly compiling the `ui-grid` element (using `$compile`)…and the grid renders, everything seems okay. But that function is never called.

**Comment by omayhemo** [comment]
Zombie thread...

I have this problem today, and cannot solve it with any of the prescribed methods.

**Comment by dofun12** [comment]
hey omayhemo, try this:
`$timeout(function(){`
	$scope.gridApi.core.handleWindowResize();
},200);`
After you set the data object.

Worked for me...

**Comment by jfoshee** [comment]
I also tried to use the `handleWindowResize()` API with no joy.  However, the *auto-resizing* directive worked for me:
http://ui-grid.info/docs/#/tutorial/213_auto_resizing

**Comment by jaypalkadam** [comment]
Hi guys please anybody help me  to fix my issues

pinned column height issue
![image](https://cloud.githubusercontent.com/assets/4994840/22774825/d54833b8-eece-11e6-92e1-ac1ebdde5a9d.png)

**Comment by trendzsoft** [comment]
Hi PaulL,
I have the same issue but if we set the fixed width to the grid it works fine but I dont want grid to have fixed width as it should be responsive

**Comment by trendzsoft** [comment]
$('.ui-grid').css('width', screen.width);
    </script>
    <script src="lib/angular/grid/ui-grid.min.js"></script>
    <script>
    $('.ui-grid').css('width', '100%');
    </script> this work forme

**Comment by thargenediad** [comment]
The $timeout technique worked for me in 2018 with angular-ui-grid@4.6.2!   Thanks!
