### ISSUE TITLE
Scrolling large data set of 1.000 rows, causes flickering

### ISSUE THREAD

**Issue by wendeldw** [angular-ui/ui-grid#1779]
Using release candidate 3.0.0-rc.12. The grid has drawing issues when using the scrollbar in combination with large data set. 

ui-grid-canvas, has a small percentage of hidden rows. 5% top and 5% at the bottom, so the viewpoint is showing 90% of the rows. Is it possible to increase the size of the canvas? Say 80% hidden. This will probably solve my case.

**Comment by Bo98** [comment]
Is there something that changed for ui-grid to struggle to keep up while ng-grid is fine? The ng-grid example seems to work fine so there's surely something that's causing the issue in ui-grid rather than just acceleration settings?

**Comment by Bo98** [comment]
Should I open a new issue about this or is this already known?

**Comment by PaulL1** [comment]
I think that's an unfair comparison, the ng-grid plunker has only 4 columns and no additional features being used (such as edit etc).  Compare the large dataset tutorial: http://ui-grid.info/docs/#/tutorial/404_large_data_sets_and_performance, which flickers a little, but is generally good.

I you look at the performance monitoring in chrome the time is all disappearing into angularjs, mostly directive compilation.  There's not a huge amount we can do about that.

**Comment by Bo98** [comment]
I am seeing similar performance in the large dataset tutorial to the ui-grid plunker - especially on mobile.

The ui-grid plunker is also only using 4 columns and no additional features unless I'm missing something that's making the comparison unfair.

**Comment by PaulL1** [comment]
Ah, then I was probably comparing to the similar discussion on another issue which had 100 columns x 100 rows and all features enabled.

I suspect some of the lack of interest comes from "Hopefully it is not architecture mistake in the core design." which isn't the kind of comment that makes people who've spent 1-2 years building this happy.

**Comment by salvois** [comment]
Hello, I'm experiencing the same problem on a v3.1.1 grid of about 20 columns and about 1700 rows, edit enabled on the last four columns, cell navigation.
I see the issue has been closed but working it around with either excessRows or virtualThreeshold makes the initial rendering very slow.
Is there something else I could try?
Thank you,
Salvo
