### ISSUE TITLE
Serverside paging, can't unselect items

### ISSUE THREAD

**Issue by MaitreDede** [angular-ui/ui-grid#1784]
Hi,

On the "Server-Side Paging Example" I do these steps :
 - on first page, select first item (-> selected = 1)
 - go on second page
 - go back to first page
 - select first item

the "selected" is 2, instead of "0".

So when changing page, we can't deselect selected items...

Do I have missed something ?

**Comment by imbalind** [comment]
I'm closing since we're not supporting 2.x any longer. If anyone is willing to take on this, feel free to fork.
