### ISSUE TITLE
How to disable console log?

### ISSUE THREAD

**Issue by andresriancho** [angular-ui/ui-grid#1787]
ui-grid is filling my console log with debugging information which is useless (at least for me, now):
![screenshot from 2014-10-10 17 41 47](https://cloud.githubusercontent.com/assets/865200/4598832/e1ced1e8-50bd-11e4-82af-da283403f7f8.png)

How may I disable these messages?

**Comment by MissFishie** [comment]
@PaulL1 "it'd be ideal for it to automatically set LOG_DEBUG_MESSAGES to false when we build a distribution release"  <-- Is this being worked on?  It appears it is true right now in the latest unstable build.
