### ISSUE TITLE
Error: Controller 'uiGrid', required by directive 'uiGridRow'?

### ISSUE THREAD

**Issue by archerchiu** [angular-ui/ui-grid#1791]
Hello, I found an error when grid in bootstrap modal. As the grid in modal show the first time, everything is fine, but the second time rendering always print the error log: Error: [$compile:ctreq] Controller 'uiGrid', required by directive 'uiGridRow', can't be found! ... in console. Could you give me some hint or suggestions?
![2014-10-13 09-00-58](https://cloud.githubusercontent.com/assets/2604264/4608174/ab1e6790-5274-11e4-9c3b-57150cabb17b.png)

**Comment by wtilton** [comment]
I'm getting the same error with a modal. Only happens the second time I open the window. I'm adding rows to the grid through a $scope.$on event. Not sure what the difference would be. I'm guessing some kind of issue with it cloning or copying the grid object. The grid itself works fine, just throws the nasty error. If I put together a plunkr or jsfiddle how high would the priority be on this? 

Right now I get around it by passing in an object that contains the grid.data. It works for one grid. Problem is, I need to update a grid on another controller. My broadcast has no knowledge of the other grid (which is a good design IMHO). Tying the data this way is also coupling the grid and other controller together which sucks.

I'd even go with a way to just suppress the error. I might look into this next as there seems to be nothing "bad" happening to the grid to affect its usability or function. Everything's working fine.

```javascript
        function addFacility(newFacility) {
			var broadcast = { facilityId: newFacility.facilityId, areaSize: newFacility.usingSize, tenantId: data.tenantId, tenantName: data.tenantName, data: tf.facilityTenants.data };
			tf.newAreaSize = 1;
			tf.newDescription = '';
			common.$broadcast('newFacility', broadcast);
		}

		$scope.$on('newFacility', (event, newFacility) => {
			if ('data' in tf.facilityTenants) {
				newFacility.data.unshift(newFacility);
			} else {
				newFacility.data = [newFacility];
			}
			_.remove(tf.availableFacilityTenants, (facility: fResponse.IFacility) => {
				return facility.facilityId == newFacility.facilityId;
			});
		})
```

**Comment by aceb694** [comment]
I am getting the same 'Error: [$compile:ctreq] Controller 'uiGrid', required by directive 'uiGridHeaderCell', can't be found!' error described above when trying to implement a custom filter modal. The same error is reproducable in the custom filter tutorial (http://ui-grid.info/docs/#/tutorial/306_custom_filters). These errors don't seem to cause any functionality problems but it would be great to have a way to get rid of them. 

Produced by my custom filter modal:
![image](https://cloud.githubusercontent.com/assets/10951233/10037565/02eb0908-6186-11e5-90d8-ff6b05f252a3.png)

Prouded by the custom filter modal in the Grid UI tutorial (click on the '...' on the Age header). The error will display on the second time.
![image](https://cloud.githubusercontent.com/assets/10951233/10037554/c9a76876-6185-11e5-86c7-5820f2d00007.png)

**Comment by MaximShoustin** [comment]
Have the same issue with `$mdDialog` of Angular material

**Comment by patrickPatterson** [comment]
i am having this problem as well, i believe it's a conflict with something else

**Comment by miranl** [comment]
I also have this issue.

**Comment by pacificeyes** [comment]
I also can see this issue under custom filters. If you click the age column button again after filtering.

**Comment by patrickPatterson** [comment]
Hi guys, I solved the error with.. <div data-ng-if="!refresh" data-ui-grid="whatever.gridOptions"></div>

the bit of ng-if refresh was what I needed. it's a part of angular.

**Comment by thucnc** [comment]
please open another ticket for this error, I got the same issue.

**Comment by yuxiaomin** [comment]
I got the same issue too.

**Comment by yccteam** [comment]
Guys - when you have an error, try to reproduce them on plnkr. If you can't, it is probably something with your code. If you can, someone could actually look into them. Can anyone reproduce this on plnkr?

**Comment by yuxiaomin** [comment]
The issue shows up when use ui-grid with modal(I use angular strap, http://mgcrea.github.io/angular-strap/) . When the modal is dismissed the HTML DOM of the modal is removed but angular scope of the modal is not destroyed and left over. At this moment the error will start to happen. 

If I open and close the modal repeatedly I can see this error more and more times.

**Comment by Nidhintt** [comment]
Is there any solution for this issue, Or any alternative method ?

**Comment by kirill-korepanov** [comment]
I am getting the same error "Controller 'uiGrid', required by directive 'uiGridRow', can't be found!"
http://plnkr.co/edit/Kq09kuEF2vFJyjwQ5uxC

**Comment by jmls** [comment]
getting the same error - but with no modal. I just did a gulp rebuild on my app and it started happening

**Comment by nkoterba** [comment]
Seeing the same thing on our app...no modal.

We are showing multiple "grids" in tabs.  When the user rapidly switches between tabs, sometimes this error gets thrown.  Will troubleshoot more but according to boilerplate angular error documentation, uiGrid controller is not yet created when uiGridRow is being rendered.  Perhaps its in the destroy, that before leaving a tab, a uiGridRow is trying to render or access its uiGrid controller, but the uiGrid controller has already been disposed?

**Comment by andrewMuntyan** [comment]
Sami issue.

Trying to add 
```
vm.gridOptions.rowTemplate = function(){
  return '  <div class="ui-grid-cell" ng-class="{ 'ui-grid-row-header-cell': col.isRowHeader }"  ui-grid-cell></div>' 
}
```

**Comment by sinuheg** [comment]
@yuxiaomin how do you destroy the angular scope when you close the modal?

**Comment by yuxiaomin** [comment]
scope has the destroy method

Thanks,
Xiaomin Yu

2016-08-10 14:03 GMT-05:00 Sinuhe Guerra <notifications@github.com>:

**Comment by JZehet** [comment]
maybe this helps

https://github.com/angular-ui/ui-grid/issues/4421#issuecomment-243482069

**Comment by edlahoz** [comment]
Essentially, all you need to do is destroy the scope when closing the modal. Instead of using $scope.$parent, store that in a variable like: var myscope = $scope.$parent and then on closing function just do myscope.$destroy();

**Comment by hungtranpg** [comment]
I still get this issue.
It also happens on your example at here: http://ui-grid.info/docs/#/tutorial/306_custom_filters
