### ISSUE TITLE
GridMenu ToolTip

### ISSUE THREAD

**Issue by trokohl** [angular-ui/ui-grid#1827]
All menu-items(column an grid) are definded in html like this:

<li
ng-repeat="item in menuItems"
ui-grid-menu-item action="item.action"
title="item.title"
active="item.active"
icon="item.icon"
shown="item.shown"
context="item.context"
template-url="item.templateUrl" >
</li>

With the attribute title="item.title" all items become the tooltip "item.title".

Is there a workaround or solution for this problem? 
Perhaps, renaming the attribute from title to data-title or whatever can fix this issue.

**Comment by Mansuro** [comment]
Is this fix supposed to allow us to add tooltips to the grid menu elements? because I've tried using the title attribute to create tooltips and it doesn't seem to work
