### ISSUE TITLE
scrollTo() method

### ISSUE THREAD

**Issue by TomKaltz** [angular-ui/ui-grid#183]
Should be able to scroll to a certain row via an instance method.  Also should be able to read the scrolling position somehow.

**Comment by mikila85** [comment]
timothy, you added the ability to scroll to a certain row, can you give a use case example?
i dont understand from the code in "added in 29b3bcb".

**Comment by dprothero** [comment]
Agreed. There doesn't seem to be an obvious or documented way to scroll the grid from code anymore.

**Comment by dprothero** [comment]
My hack/workaround for now...
```
gridApi.grid.element[0].getElementsByClassName("ui-grid-viewport")[1].scrollTop = 0;
```

**Comment by PaulL1** [comment]
I think you're mixing 2.x and 3.0.  The majority of this issue relates to 2.x I think, the last one from @dprothero looks like 3.0/ui-grid code.

For @dprothero, the cellNav feature provides the scrollTo functionality, and I believe that swalters is currently in the process of moving it into core.

**Comment by dereklin** [comment]
@dprothero Did you find a better solution?  I am using a similar hack:
```
gridApi.grid.element[0].getElementsByClassName("ui-grid-viewport")[0].scrollTop = rowIndex * 25;
```
For me, I want to show the selected (at rowIndex) at the top of the grid view.

**Comment by dereklin** [comment]
@dprothero The hack doesn't work after the user sorts the table.
@PaulL1 gridApi.core.scrollTo works to some degree.  It will select the row, but it won't try to make the selected row the first row in the viewport...

**Comment by dereklin** [comment]
My solution is to decorate uiGridDirective and then override the scrollTo and scrollToIfNecessary methods.  The key is set up the scrollEvent.y according my business rule.

**Comment by dereklin** [comment]
I was not able to get the precise landing pixel.  But I spotted the usage of
```
visibleRowCache.indexOf
```
So I went back with the hack.  This time, I am using something like this to get the rowIndex:
```
                rowIndex = gridApi.grid.renderContainers.body.visibleRowCache.indexOf(tableConfig.gridApi.grid.rows[rowIndex]);
                gridApi.grid.element[0].getElementsByClassName("ui-grid-viewport")[0].scrollTop = rowIndex * gridApi.grid.options.rowHeight;

```

**Comment by Saransh27** [comment]
rowIndex = gridApi.grid.renderContainers.body.visibleRowCache.indexOf(gridApi.grid.rows[rowIndex]);
                gridApi.grid.element[0].getElementsByClassName("ui-grid-viewport")[0].scrollTop = rowIndex * gridApi.grid.options.rowHeight;

Even above code is not working for me..did anyone solve it? In My case it works for 2-3 elements but after that it scrolls to end of the grid.
