### ISSUE TITLE
ng-click does not work from within cell template

### ISSUE THREAD

**Issue by robertjchristian** [angular-ui/ui-grid#184]
(Markup is lost due to markdown.  Not sure how to correct this.  Easiest way to read this issue is to click "edit")

Works from inside grid:

cellTemplate:'a href="{{url}}">{{description}}</a>'

Works from outside of grid:

<a ng-click="goto({{ur}}])">{{description}}</a>

Does not work from inside grid:

cellTemplate:'<a ng-click="goto({{url}})">{{description}}</a>'

Couple things to note:

Using latest ng-grid.
This is the same regardless of element (tried with div, button)
I can copy the exact rendered html from within the cell and paste it outside, and it works as expected.

Must be something to do with interception of ng events??

**Comment by askanhan** [comment]
The document for external scopes are no more available. Is that not in use anymore? Which way should be followed for ng-click in cell as of 3.0.7?

**Comment by hisland** [comment]
@askanhan the new post [Tutorial: 305 Accessing Scope in templates](http://ui-grid.info/docs/#/tutorial/305_appScope) 
UI-Grid uses isolate scope, so there is no access to your application scope variables from a row or cell template. By default, the parent scope of the ui-grid element is assigned to a property on $scope.grid named appScope. 

If you need another reference other than $scope.$parent, then use gridOptions.appScopeProvider. This reference will be assigned to grid.appScope. 

$scope.grid.appScope is available in all templates that the grid uses. 
In a template, you access the scope using grid.appScope property

`$scope.showMe = function(){ alert('some');}`
`ng-click="grid.appScope.showMe()"`

**Comment by PramodDutta** [comment]
Hope this works 👍  http://plnkr.co/edit/GspLkfJSonV6IMTmyIm4?p=preview

**Comment by nirmalabis** [comment]
Hi,

ng-click event not working on table cell and table row using "angular-bootstrap-grid-tree" . Also it is not working with dynamic data without pressing f5.
Can anyone provide a solution

Thanks in advance
