### ISSUE TITLE
Variable row heights and the vertical slider

### ISSUE THREAD

**Issue by jsun01** [angular-ui/ui-grid#1887]
I found this 2 unsolved but closed issues https://github.com/angular-ui/ng-grid/issues/21, https://github.com/angular-ui/ng-grid/issues/157.
I find your ng-grid super component - all my respect, 
but I'd like to reopen the topic of variable row heights, because I think it is a KO feature, which unnecessarily forces many developers to search for another component. 
It's a pity, that this nice component is missing the basic feature, which has also e.g. basic html table.
Why there is a cellTemplate feature, when I can't see cellTemplate content of multiple rows ? 
Restriction to use cellTemplate only for 1 row narrows the possibilities quite a lot.

I made some hacks to bring it to work and have some suggestions at the end of this text to bring it to ng-grid.
1. custom css to turn on word-wrapping (it's not quit this topic, but it's correlated - whe you have long row, it breaks to multiple)
   .ui-grid-cell-contents {
   white-space: normal;
   }
2. custom css to turn on automatic row height
   .ui-grid-cell {
   height: auto !important;
   }

3.
1. and 2. worked well - rows were wrapped and row heights automatically adapted.
I didn't found any other problem except of that the vertical slider wasn't shown ok (too low), because it still counted the rowHeight=30.
So in ui-grid.js (unstable) in  var Grid = function Grid(options) { ... 
I added this row 
self.options.rowHeight = options.rowHeightCustom || self.options.rowHeight;
Then it was possible to set the rowHeightCustom from Controller to the right value.
This hack brought to work correctly the vertical slider but only for equal row heights.

4.
At the first look the vertical scrollbar height in ui-grid.js is counted in 
function updateNativeVerticalScrollbar() { ... ...  rowContainer.getCanvasHeight()  ... }
and the getCanvasHeight() itself counts height as:
self.visibleRowCache.forEach(function(row){  ret += row.height;   });
And there is the unlucky constantly fixed row.height set to 30.
For variable row heights:
On of the ways to get the row height for each row is e.g. in angular.module('ui.grid').directive('uiGridCell', ...
there is info $elm[0].offsetHeight / $elm[0].clientHeight
So for each row you can get the highest uiGridCell height value and set it as a variable row height (+ margins/padding eventually).
Taking it in account in getCanvasHeight() 
self.visibleRowCache.forEach(function(row){  ret += row.variableHeight;   });
the scrollbar might work fine.
If this would be settable in column definition with something like:
variableHeight : true;
It could still be kept the old functionality but also introduced the new one - at least for testing by community ;).

I didn't test all cases and situations and had only very short time to investigate it, but at the first glance it doesn't seem to be that much re-work to bring the variable row height to run. 
I realize the ng-grid authors know best the background and all the struggle with the code to fix this.
I don't know if the above will navigate to the solution that fits the concept or not - but - maybe it helps as one of the ways ;).

**Comment by azharak** [comment]
I had a requirement where common/similar values in some grid cells are to be merged. Something like:

Name | Courses
------------ | -------------
Monica | Maths
       | English
Rachel | Physics
   | Chemistry
   | Biology

(The above table does not show the cells _Monica_ and _Rachel_ merged; but lets assume they are).

I implemented it as follows:

1) Changed following templates in `ui-grid.js`:
a) `ui-grid/ui-grid`: Disabled height styling for `.ui-grid-row` and `.ui-grid-cell`. Modified height value for `.ui-grid-vertical-bar`.
```javascript  
  $templateCache.put('ui-grid/ui-grid',
    . . .
    // Disabled following:
    //"    .grid{{ grid.id }} .ui-grid-row, .grid{{ grid.id }} .ui-grid-cell, .grid{{ grid.id }} .ui-grid-cell .ui-grid-vertical-bar {\n" +
    //"      height: {{ grid.options.rowHeight }}px;\n" +
    //"    }\n" +

    // Added following:
    "    .grid{{ grid.id }} .ui-grid-cell .ui-grid-vertical-bar {\n" +
    "      height: {{row.height ? row.height: grid.options.rowHeight}}px;\n" +
    "    }\n" +
    "\n" + 
    . . . 
```
b) `ui-grid/uiGridViewport`: Added style for row height (compensation for disabling styling for `.ui-grid-row` above).
```javascript  
  $templateCache.put('ui-grid/uiGridViewport',
    "<div role=\"rowgroup\" class=\"ui-grid-viewport\" ng-style=\"colContainer.getViewportStyle()\"><!-- tbody --><div class=\"ui-grid-canvas\"> <div ng-repeat=\"(rowRenderIndex, row) in rowContainer.renderedRows track by $index\" class=\"ui-grid-row\" style=\"height: {{row.height ? row.height: grid.options.rowHeight}}px;\"  ng-style=\"Viewport.rowStyle(rowRenderIndex)\"><div role=\"row\" ui-grid-row=\"row\" row-render-index=\"rowRenderIndex\"></div></div></div></div>"
  );
```
c) `ui-grid/ui-grid-row`: Added style for cell height (compensation for disabling styling for `.ui-grid-cell` above).
```javascript  
  $templateCache.put('ui-grid/ui-grid-row',
    "<div ng-repeat=\"(colRenderIndex, col) in colContainer.renderedColumns track by col.uid\" ui-grid-one-bind-id-grid=\"rowRenderIndex + '-' + col.uid + '-cell'\" class=\"ui-grid-cell\" style=\"height: {{row.height ? row.height: grid.options.rowHeight}}px;\" ng-class=\"{ 'ui-grid-row-header-cell': col.isRowHeader }\" role=\"{{col.isRowHeader ? 'rowheader' : 'gridcell'}}\" ui-grid-cell></div>"
  );
```

2) Used cell template for the split cell:
```javascript  
  $scope.gridOptions = {
    columnDefs: [
      { field: 'name' },
      { field: 'courses' ,
    	cellTemplate: '' 
          + '<div>'
          + '  <div ng-repeat="course in row.entity[col.field] track by $index" class="ui-grid-cell-contents" title="TOOLTIP">'
          + '    {{course CUSTOM_FILTERS}}'
          + '  </div>'
          + '</div>'
      }
    ]
  };
```

3) Set row height for each row:
```javascript  
  $scope.gridOptions.onRegisterApi = function( gridApi ) {
      $scope.gridApi = gridApi;
      
      $scope.gridApi.grid.registerRowBuilder(function(row, gridOptions) {
    	  if (angular.isArray(row.entity.courses)) {
    		  row.height = gridOptions.rowHeight * row.entity.courses.length;
    	  }
      });
  };
```

A data like following will be rendered with rows with varying heights:
```javascript  
  $scope.gridOptions.data = [
    {
        "name": "Monica",
        "courses": ["Maths", "English"]
    },
    {
        "name": "Rachel",
        "courses": ["Physics", "Chemistry", "Biology"]
    }
  ];
```

![image](https://cloud.githubusercontent.com/assets/15811100/11113286/99343a00-8941-11e5-8eed-40787e6dd452.png)

**Comment by fatebook1004** [comment]
Hi azharak, the above solution is working fine in Chrome.. But not working in IE. Can you please provide a solution for IE...

Waiting for your response..

**Comment by doubleac** [comment]
For IE use <ng-attr-style> instead of <style>

**Comment by fatebook1004** [comment]
@doubleac Thanks. It is working fine. Can I know if the above solution works for fixed grid height and external pagination..?

Dynamic row height is actually working, but the problem is there are 61 rows in the grid and only some columns are getting visible. There are lots of space left at the bottom of the grid. On scrolling up and down, some rows are getting visible and invisible. 

Can you please help me with this..?

**Comment by shamimafridi** [comment]
Excelent  @azhar2205 your solution worked for me.

**Comment by shamimafridi** [comment]
@fatebook1004 I also has the same issue you have. did you found any solution?
