### ISSUE TITLE
expandable grid error when expanding

### ISSUE THREAD

**Issue by jmorrisIII** [angular-ui/ui-grid#1907]
When I click to expand the grid i get an error "TypeError: Cannot read property 'expandableRowHeight' of undefined" and "TypeError: Cannot read property 'rowExpandableTemplate' of undefined". I referenced 'ui.grid.expandable' in my app.js. Any Ideas?

**Comment by kcaron-cst** [comment]
For whoever might stumble on this having issues with the expandable grid: the `expandableRowScope` in the tutorial is not used so it may be a red herring with your debugging.
