### ISSUE TITLE
Shouldn't scrollTo api be in core module?

### ISSUE THREAD

**Issue by OrenHasbani** [angular-ui/ui-grid#1953]
If i want the scrollTo api I need to add the feature cellNavigation.

In my opinion it's a core api.

Someone has an idea how to scroll the grid programmatically without add cellNavigation feature?

**Comment by nonZero** [comment]
@PaulL1 cellNavigation do change the the UI quite a lot.
For example, when using selection with `enableRowSelection`, and `enableRowHeaderSelection`, adding CellNavigation does not allow to select rows anymore.

There should be an easy way to use `scrollTo` without cellNavigation.
