### ISSUE TITLE
exporterPdfPageSize not working

### ISSUE THREAD

**Issue by edenchen123** [angular-ui/ui-grid#1969]
ui.grid.exporter  --> GridOptions  -->exporterPdfPageSize    not working

root cause:  forgot to set it to pdfmake config

var docDefinition = {
                        pageOrientation: grid.options.exporterPdfOrientation,
//add this line
                        pageSize: grid.options.exporterPdfPageSize,
                        content: [{
                            style: 'tableStyle',
                            table: {
                                headerRows: 1,
                                widths: headerWidths,
                                body: allData
                            }
                        }],
                        styles: {
                            tableStyle: grid.options.exporterPdfTableStyle,
                            tableHeader: grid.options.exporterPdfTableHeaderStyle
                        },
                        defaultStyle: grid.options.exporterPdfDefaultStyle
                    };

**Comment by fahussain** [comment]
I see the issue has been fixed but when I change the pageSize, the exported pdf is always A4 size. Am I missing something?
