### ISSUE TITLE
export functionality should be able to export sorted data

### ISSUE THREAD

**Issue by edenchen123** [angular-ui/ui-grid#1972]
export functionality should be able to export sorted data

**Comment by csharpengineer** [comment]
Yes, but what about when data is paged?  I have paged data and I would like to export all rows using the current sort.  I have tried temporarily changing the page size to fit all rows, calling export on visible rows and then setting the page size back, however even with a notification to grid that the page size has changed, the exporter still exports just the current page.

**Comment by PaulL1** [comment]
I believe there is now an option to get all paged data before export, it does require handling a callback.

**Comment by csharpengineer** [comment]
Ah, thanks.  Is this `exporterAllDataPromise`?

**Comment by PaulL1** [comment]
Sounds right.

**Comment by ruhaise** [comment]
hey, how to use exporterAllDataPromise ?

thanks in advance

**Comment by ruhaise** [comment]
function exportData() {

            $scope.exportDatalist = _.filter($scope.gridApi.grid.rows, (o) => {
               return o.visible;
            });
            var entities = _.map($scope.exportDatalist, 'entity');
            alasql.promise('SELECT * INTO XLSX("Log_Details.xlsx",{headers:true}) FROM ?', [entities]);
        }

I'm using this to export the data from the grid, now the filtered data across all pages can be retrieved, but only problem i cant export it as sorted, any way to make the sorting work as well, what i mean is i filtered something and applied a sort, then when i call this function it returns the filtered rows but the data is not returned sorted as well, thanks

**Comment by nisharamj** [comment]
@csharpengineer @PaulL1 Could you please show here the sample code, can be used to resolve this problem?
