### ISSUE TITLE
ui-grid-icon-ok is broken

### ISSUE THREAD

**Issue by Manduro** [angular-ui/ui-grid#1975]
The css uses `c361` for the "ok" icon:
`.ui-grid-icon-ok:before {
  content: '\c361';
}`

Versus the svg font file that uses `e800`:
`<glyph glyph-name="ok" unicode="&#xe800;">`

I don't have a clue where this problem is located in the sources, so I'm not able to fix this with a PR.

**Comment by goprimelending** [comment]
for me c362 appears in ui-grid-unstable.css but content: '\e800'; appears in ui-grid-stable.css

**Comment by MaximeCheramy** [comment]
I had the same issue because I've downloaded http://ui-grid.info/release/ui-grid-unstable.svg instead of http://ui-grid.info/release/ui-grid.svg (i'm using http://ui-grid.info/release/ui-grid-unstable.css).

Is it a deprecated link?
