### ISSUE TITLE
hiding the columns: false

### ISSUE THREAD

**Issue by nikitaVillemson** [angular-ui/ui-grid#1979]
I tried
enableColumnMenus: false,
gridMenuShowHideColumns: false,
enableHiding: false
None worked.
The only thing I have in menu is hide and it is active.

**Comment by arashsoft** [comment]
@PaulL1 Sorry for commenting on a closed issue. But, gridMenuShowHideColumns:false is not working. Even in your plunker I can see the "Hide Column" in the menu.
