### ISSUE TITLE
Disable Subgrid Expand if Subgrid is blank?

### ISSUE THREAD

**Issue by countrdd** [angular-ui/ui-grid#1990]
Is there a way to disable the expand button or even hide the + if there is no data in the subgrid?

For example.

I am using it to display items in a product kit on an invoice.
If the innvoice line item is NOT a product kit then I don't want to display the + to expand the row.

**Comment by jshah85** [comment]
Is this resolved? Looks like solution was proposed but no update here or at #2396 since Dec 19, 2014. Please update us by how to fix issue? Demo page doesn't say anything about this.

**Comment by swalters** [comment]
I don't think this solution protects against lazy loaded subgrid data.  This is also assuming your expanded data is a grid, which it doesn't have to be.  It can be anything.

**Comment by jpuri** [comment]
This plunkr has workaround to prevent subgrid from expanding using the GridApi events and methods.

http://plnkr.co/edit/wuCkQdva1iPzgp2hYmBL?p=preview

**Comment by DmitryEfimenko** [comment]
I have a scenario when a condition resulted from an ajax request determine whether the grid is expandable or not. So the following does not work:
```javascript
scope.gridOptions = {
    data: [ { name: 'some data' } ]
}

performAsyncMethod(function(response) {
    if (response.someCondition == true) {
        scope.gridOptions.expandableRowTemplate = 'subgridTemplate.html';
        scope.gridOptions.expandableRowHeight = 150;
    }
});
```
and yes, since the subgrid can be anything, I don't think that solution proposed by @KylePDavis is viable.

**Comment by RamsudanDongol** [comment]
Is this issue still open/fixed? I was working with UI grid. some of my data do not have have sub grid datas and some do but the grid renders subgrid anyways.

**Comment by idoo** [comment]
@RamsudanDongol still oppened

**Comment by doudoumasta** [comment]
Hi,
I also realy need the feature  to hide "+" when row's subgrid is empty. Do you have any idea when this issues will be available? Or an temporary solution?

Thx a lot!!

**Comment by donduni** [comment]
+1

**Comment by alqu** [comment]
+1
There is a setting for the tree called `showTreeExpandNoChildren`, but not for the expandable feature.

**Comment by BramDecuypere** [comment]
+1

**Comment by JayHuang** [comment]
This PR seems to cause the Expand All button/icon to disappear and show "Expandable Buttons" in its place.

**Comment by cbojaca** [comment]
+1

**Comment by arnjmllr** [comment]
temp workaround:
```javascript
for (var i = 0; i < data.data.length; i++) {
                if (data.data[i].departmentsWithRole.length == 0) {
                    data.data[i].departmentsWithRole.push({ departmentName: "No rows were returned.", roleName: "" });
                }
                data.data[i].subGridOptions = {
                    columnDefs: [{ name: "Department", field: "departmentName" }, { name: "Role", field: "roleName" }],
                    data: data.data[i].departmentsWithRole
                }
            }

**Comment by safani** [comment]
+1

**Comment by hugsbrugs** [comment]
You just have to hide expandable default column
```javascript
$scope.gridOptions = {
    enableExpandableRowHeader: false
```
and create you own column with custom cellTemplate
```javascript
columnDefs: [{ 
    name: 'expand',
    cellTemplate: '<span ng-show="row.entity.count_dup == 0"><i class="fa fa-times"></i></span>' +
    '<span ng-show="row.entity.count_dup > 0" class="cursor"' +
    'ng-click="grid.api.expandable.toggleRowExpansion(row.entity)">' + 
        '<i ng-hide="row.isExpanded" class="fa fa-plus"></i>' + 
        '<i ng-show="row.isExpanded" class="fa fa-minus"></i>' +
    '</span>',
```
whta else ? ;)

**Comment by Perfect-Web** [comment]
+1
