### ISSUE TITLE
Angular 1.3 bind-once performance

### ISSUE THREAD

**Issue by ofairfoul** [angular-ui/ui-grid#2005]
For performance improvements in our project I have overridden the headerCellTemplate and cellTemplate to use angular 1.3 bind-once syntax {{:: }} for their values, which has almost halved the number of watchers which ui-grid uses.

Obviously this means that dynamic updates are not updated automatically and only shown when the cells are rendered and destroyed through virtualization. But a workaround is to remove and re-add the updated rows when updates come through. Also this breaks editing as discussed here. https://github.com/angular-ui/ng-grid/issues/727#issuecomment-54176122

However, I would like to know is there is anything else I should be aware of why this may not work?

Thanks

**Comment by PaulL1** [comment]
This is a useful request, but not really in the current roadmap.  We have far too many good ideas in the repository already, giving the impression that we have a project riven with defects.

Accordingly, I am leaving the enhancement tag on this, but closing it.  If someone would like this functionality, we'd welcome a pull request that adds it.
