### ISSUE TITLE
long column headers should have the option to wrap

### ISSUE THREAD

**Issue by DaveSysomos** [angular-ui/ui-grid#2017]
Column header text does not wrap. If my header text is longer than the data, the header text gets truncated with ellipsis. I'd like it to wrap to a second line (i.e. all column headers will be two lines high).

I've tried every which way to do this but can't seem to get the right combo.
If I set the HeaderRowHeight to 60 it just overlaps the first row.
And no matter what I do (including turning off whitespace: no-wrap), I can't get the text to wrap.

**Comment by PaulL1** [comment]
This is a useful request, but not really in the current roadmap.  We have far too many good ideas in the repository already, giving the impression that we have a project riven with defects.

Accordingly, I am leaving the enhancement tag on this, but closing it.  If someone would like this functionality, we'd welcome a pull request that adds it.
