### ISSUE TITLE
Internal grid rendering uses different height than overall outline

### ISSUE THREAD

**Issue by Dev63** [angular-ui/ui-grid#2023]
When using flex-grow to ensure that the grid takes 100% of the height available, it correctly shows its outline, but then draws its internals as if the height available had been calculated with every hidden div on the page actually shown.  The result is that the footer gets drawn in the middle of the table, raised by the vertical amount of any hidden div.

![image](https://cloud.githubusercontent.com/assets/9340860/4929992/284bfde6-655c-11e4-84dd-1eea8c38d8e2.png)

If you resize the window, everything then draws correctly. It's just the initial setup that is incorrect.  Unfortunately, calling gridApi.handleWindowResize() or gridApi.refresh() does nothing, probably because it detects that the window hasn't actually changed size.

Here's a [plunker showing these flex-grow problems with ui-grid](http://plnkr.co/edit/uUUuiBZF7xQiHCgTSG8R?p=preview).  It uses a slightly modified form of the code from ui-grid tutorial 101.  By clicking the "Toggle Hidden" button, you can see that when the hidden div is shown, the table draws properly.  Well, it would, except someone just published on the unstable branch a problem with the bottom scrollbar getting drawn a bit too high, but I assume that will be resolved shortly.

I could imagine that it might be tricky to fix this, but sure would appreciate a workaround, or even a call that would actually force the grid to redraw.

**Comment by PaulL1** [comment]
This is a useful request, but not really in the current roadmap.  We have far too many good ideas in the repository already, giving the impression that we have a project riven with defects.

Accordingly, I am leaving the enhancement tag on this, but closing it.  If someone would like this functionality, we'd welcome a pull request that adds it.
