### ISSUE TITLE
Tabbing between onscreen and offscreen cells do not work.

### ISSUE THREAD

**Issue by johanjordaan** [angular-ui/ui-grid#2026]
When you have a grid with many columns (Enough so that some of the columns are offscreen) and the cell contents for the row is all editable controls like input boxes or dropdowns then tabbing between the cells works except if you try and tab to the next cell and it is 'offscreen'. 

Has anybody encountered this?

PS: I am using a custom row template and manage the tab indexes in the template using $index.
PPS: This is on nggrid 2.x

**Comment by imbalind** [comment]
I'm closing since we're not supporting 2.x any longer. If anyone is willing to take on this, feel free to fork.
