### ISSUE TITLE
Footer is overlapped by scrollbar

### ISSUE THREAD

**Issue by rupampatel2006** [angular-ui/ui-grid#2030]
In new release (3.0.14),  Footer gets overlapped by scrollbar which was working perfectly in previous release. Scroll can be turned off but if both are required together, its an issue.

http://ui-grid.info/docs/#/tutorial/105_footer
![image](https://cloud.githubusercontent.com/assets/5253675/4941435/0995708a-65e3-11e4-8502-46b7c1bdc279.png)

Thanks in advance.

**Comment by aqkhana2002** [comment]
any help ?

![image](https://user-images.githubusercontent.com/5283983/50120443-a7d51900-02a9-11e9-9db6-58b894ffb765.png)
