### ISSUE TITLE
ui-grid rc 3.0.0-rc14 Expandable module disabled

### ISSUE THREAD

**Issue by 01willtx** [angular-ui/ui-grid#2034]
I have 2 grids on in the view, 1 expandable, 1 not. 

```
  $scope.gridOptions = {
        data: [],
        columnDefs: hotelColumnDef,
        enableColumnResize: true,
        showFilter: false
    };

    $scope.gridExpdOptions = {
        data: [],
        columnDefs: officeColumnDef,
        enableColumnResize: true,
        showFilter: false
    }

    $scope.gridExpdOptions.expandable = {
        rowExpandableTemplate: '/../../Scripts/app/partialViews/rowExpandableTemplate.html',
        expandableRowHeight: 150
    }
```

This is the error in the console upon page load: 
   You have not set the expandableRowTemplate, disabling expandable module 

This was not present in rc-12. I'm using angular 1.2.26

**Comment by avuthubhargavreddy** [comment]
hi im getting same error like
You have not set the expandableRowTemplate, disabling expandable module
although i used same name

**Comment by liujiusheng** [comment]
@avuthubhargavreddy have you deal with it?
