### ISSUE TITLE
Ability to set selection on initialization

### ISSUE THREAD

**Issue by wattsbn** [angular-ui/ui-grid#2038]
I would like to select the first row in the grid whenever it is initialized. I tried using the `renderingComplete` event but the rows are not ready by that time. Talking with @c0bra, he seemed to think the best/easiest solution might be to create an api callback/event for when the visible rows are changed. I could then listen for the first time this to be called/fired.

**Comment by anandvihar** [comment]
@wattsbn  , i also have the same problem, can you help me by giving an example how did you accomplish it. I have to select all rows .

**Comment by wattsbn** [comment]
@anandvihar It has been a while but it looks like im simply just listening to the event I added. I am keeping track of wither or not its the first time rows are actually rendered or not and passing that to a separate function to do the actual selecting.

    var first = true;
    gridApi.core.on.rowsRendered($scope, function() {
        if (gridApi.grid.renderContainers.body.visibleRowCache.length === 0) { return; }
        selectRows(first)
        first = false;
    });
