### ISSUE TITLE
using a url in cellTemplate in columnDef causes grid to malfunctions.

### ISSUE THREAD

**Issue by joshmackey** [angular-ui/ui-grid#2053]
If I include the html inline, it works fine, but as soon as its a remote file, the entire grid malfunctions having the headers be only a few pixels in height and the contents of the grid be invisible.

**Comment by prathik457** [comment]
I am also facing this issue. 
I wanted auto-focus on the input element on click of filter button(external filter). So I explicitly defined the headerCellTemplate in columnDefs. I am keeping the html code in a separate template and I am trying to reference the in columnDefs.
In the console it says fetching URL and does not actually apply the template in the header.
