### ISSUE TITLE
TypeError occurs with ui-grid and Date type cells

### ISSUE THREAD

**Issue by pmariduena** [angular-ui/ui-grid#2055]
I'm using ui-grid to show many rows of data (about 8 columns). Some of the columns are Dates. The Date columns coming back from a REST is JSON, and is encoded in the following way:

{..."myDate" : "2014-11-10", ....} as per what I understand is required for angular to interpret this as a Date. 

This shows up properly in the grid upon request completion. However, when I try to double-click on the cell to edit the date, I do get the Date picking widget....BUT, there is a JavaScript error in the Console:

TypeError: Object doesn't support property or method 'getTime'
   at Anonymous function (http://localhost:9091/bower_components/angular-ui-grid/ui-grid.js:11309:15)
   at ngModelWatch (http://localhost:9091/bower_components/angular/angular.js:17776:9)
   at $digest (http://localhost:9091/bower_components/angular/angular.js:12533:21)
   at $apply (http://localhost:9091/bower_components/angular/angular.js:12806:13)
   at beginEdit (http://localhost:9091/bower_components/angular-ui-grid/ui-grid.js:11109:15)
   at dispatch (http://localhost:9091/bower_components/jquery/jquery.js:5094:6)
   at handle (http://localhost:9091/bower_components/jquery/jquery.js:4765:5)

On Google Chrome, the Date appears to have been correctly modified. But on IE11, we never even get the Date picking widget. Here is my partial html, controller, services, etc.

template:

```
    <!--3rd party javascript-->
    <script type="text/javascript" src="bower_components/jquery/jquery.js"></script>
    <script type="text/javascript" src="bower_components/angular/angular.js"></script>
    <script type="text/javascript" src="bower_components/angular-route/angular-route.min.js"></script>
    <script type="text/javascript" src="bower_components/angular-resource/angular-resource.min.js"></script>
    <script type="text/javascript" src="bower_components/angular-ui-grid/ui-grid.js"></script>
    <script type="text/javascript" src="bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js"></script>
    <script type="text/javascript" src="bower_components/bg-splitter/js/splitter.js"></script>
    <script type="text/javascript" src="bower_components/angular-spinner/angular-spinner.min.js"></script>
    <script type="text/javascript" src="bower_components/spin.js/spin.js"></script>
```

<div>
 ...
 <div ui-grid="gridOptions"  ui-grid-edit ui-grid-resize-columns ui-grid-row-edit ui-grid-cellnav ui-grid-selection>
    </div>
</div>

controller JS:
angular.module('myControllers')
    .controller('firstController', ['$scope', '$filter', '$log', '$q', '$interval', 'RowService',
        function ($scope, $filter, $log, $q, $interval, RowService) {
...
            $scope.myOverridesData = RowService.query();
            $scope.gridOptions = {
                columnDefs: [
...
                 {field: 'fDate', displayName: 'First Date', type: 'date', enableCellEdit: true, cellFilter: 'date:"dd-MMM-yyyy"'},
                    {field: 'sDate', displayName: 'Second Date', type: 'date', enableCellEdit: true, cellFilter: 'date:"dd-MMM-yyyy"'},
                    {field: 'tDate', displayName: 'Third Date', type: 'date', enableCellEdit: true, cellFilter: 'date:"dd-MMM-yyyy"'},
...
              ],
                data: "myData",
                //enableCellEditOnFocus: true,
                enableCellSelection: true,
                enableColumnResizing: true,
                enableFiltering: true,
                enableGridMenu: true,
                enableRowSelection: true,
                minRowsToShow: 50,
                multiSelect: true,
                rowHeight: 20,
                rowEditWaitInterval: 200,
                showFooterRow: false
            };
....

services JS:
'use strict';

var myServices = angular.module('myServices', ['ngResource']);

myServices.factory('RowService', ['$resource',
    function ($resource) {
        return $resource('/app/rows', {
            query: {method: 'GET', isArray: true},
...
      });
    }]);

It appears either angular, or ui-grid, is not properly identifying model objects as Dates, even when they are Dates. Please fix this, as IE11 is broken without this.

**Comment by xavifuefer** [comment]
Hi, I want to implement filtering for dates i.e. less than, greater that and equal to... but not sure how to do it. Do I have to set the term to a Date object? a string? Any clue?

**Comment by PaulL1** [comment]
I think you could try a date object.  But I think (from memory) it tries to convert whatever it's given into a number, and then uses that.  But if you give a Date, and the column itself contains Dates, then it'll probably convert both into numbers and it'd work OK.  If not, suggest raising a new issue rather than commenting on an old closed one...

**Comment by PaulL1** [comment]
This plunker seems to work fine with date objects: http://plnkr.co/edit/mtrzeRXD2oOmoDPg09my?p=preview

**Comment by xavifuefer** [comment]
thank you so much @PaulL1 I'll take a look at the plunker

**Comment by tasnimpulikkal** [comment]
angular.js:11655 Unable to assign type from data, so defaulting to string, Im getting this error for Date while populating data in UIgrid.

**Comment by tasnimpulikkal** [comment]
My code is :   for(i = 0; i < data.length; i++){ data[i].Date = new Date(data[i].Date);} , that displays nan infact
