### ISSUE TITLE
Clear search button problem in RTL mode

### ISSUE THREAD

**Issue by nik-kashi** [angular-ui/ui-grid#2058]
Clear search button problem in RTL mode

![image](https://cloud.githubusercontent.com/assets/4746836/4989726/658e4b16-6992-11e4-80e5-30bbefe04bed.png)

for RTL mode , clear search bottun should be shown in left side of text box, like this:
![image](https://cloud.githubusercontent.com/assets/4746836/4989756/f8539c58-6992-11e4-9c53-7f14f1dc1042.png)

I resolve my problem using this CSS
`.ui-grid[dir=rtl] .ui-grid-filter-container .ui-grid-filter-button {
    right: auto;
    left: 37px;
}`

because of source code CSS is written in LESS I can't change it and create a pull request!

**Comment by MadUser** [comment]
Is it only me or IE11 still has this issue. it looks like it ignores the rtl css and override it with the former css.
