### ISSUE TITLE
Wrapping ng-grid inside another directive doesn't seem to work

### ISSUE THREAD

**Issue by ffesseler** [angular-ui/ui-grid#206]
http://plnkr.co/edit/W6mvXyAXYqeKkLU0FFWx?p=preview

From what I understand, nggrid compiles function is watching the parent scope data attribute to build rows.
However, when you wrap nggrid inside another directive which has its own scope, the data attribute doesn't exist on the directive scope.

**Comment by HEILEEN** [comment]
Hi guys, i try to implement this example but show me the next error:
Error: [$compile:multidir] Multiple directives 
But i dont know which compeonet colission :(

**Comment by HEILEEN** [comment]
Excelent, i fixed my error just change replace : true, for false and woala! thanks so much for your help
