### ISSUE TITLE
 cellClass is not updating instantly

### ISSUE THREAD

**Issue by sujaychakraborty** [angular-ui/ui-grid#2070]
Hi,

Objective : want to highlight edited cell and mark them as red color if value is chnaged.

Editing the grid and change the random cell value. 
Add a flag(isDirty = true;) to rowEntity from afterCellEdit.
Based on the isDirty value seting the cellClass to red in columnDefs. 

Observation : cellClass is not updating instantly but it's updating the previously edited cellClass when edit another new cell.

code snippet :

$scope.gridModelAssets = {
        enableSorting: true,
        columnDefs: [
            { name:'fieldName', displayName:"Assets Field Name",enableCellEdit:false, width:'200'},
            { name:'value', displayName: 'Value',width: '200',enableCellEdit:'true', cellFilter:"currency:\'&#x20B9&nbsp;\'",
            cellClass:function(grid,row,col){
                if(row.entity.isDirty){
                   return 'red';
                }
            }
            }
        ]
    };

```
$scope.gridModelAssets.onRegisterApi = function(gridApi){
    $scope.gridApiAssets = gridApi;
    gridApi.edit.on.afterCellEdit($scope,function(rowEntity, colDef, newValue, oldValue){
        if(newValue != oldValue){
            rowEntity.isDirty = true;
        }
        $scope.$apply();
        $scope.gridApiAssets.core.refresh();
    });
}; 
```

**Comment by squarewave24** [comment]
I have the same issue (cellClass not updating instantly). Tried your approach but calling notifyDataChange gives me this error: "Notified of a data change, but the type was not recognised, so no action taken, type was: [object Object]"   I verified that both parameters passed are valid

                  if (newValue != oldValue) {
                        rowEntity.dirty = true;
                        gridApi.core.notifyDataChange(gridApi.grid, uiGridConstants.dataChange.EDIT);
                    }

**Comment by PaulL1** [comment]
I don't think you include gridApi.grid.

**Comment by duahaudo** [comment]
It should be `gridApi.core.notifyDataChange(uiGridConstants.dataChange.EDIT);`
