### ISSUE TITLE
ngEventProvider assignEvents method adds duplicate watchers 

### ISSUE THREAD

**Issue by amanmahajan7** [angular-ui/ui-grid#2075]
Every time ngEventProvider.assignEvents is called (for example when you update columns), it add another watcher for 'renderedColumns'

self.assignEvents = function() {
        ....................
        $scope.$on('$destroy', $scope.$watch('renderedColumns', function() {
            $timeout(self.setDraggables);
        }));
    };

This is affecting performance as it triggers the digest cycle multiple times. We should add a flag to make sure that this watcher is only  added once.

**Comment by swalters** [comment]
Closing old 2.x issue as all current development is on 3x. 

If someone really needs this fix for 2.x, my advice is to fork and fix it.  Sorry, I know it's not ideal, but it is the best we can offer with limited resources.
