### ISSUE TITLE
CellTemplate not working with html templates

### ISSUE THREAD

**Issue by xaguzman** [angular-ui/ui-grid#2078]
Using ui-grid [v3.0.0-rc.15](https://github.com/angular-ui/ng-grid/releases/tag/v3.0.0-rc.15)

CellTemplates do not seem to work property when using a non-string template.

I defined an html-template:

``` html
<script type="text/ng-template" id="readParamNameCell.html" >
                <div class="ui-grid-cell-contents" tooltip="{{COL_FIELD}}">{{ COL_FIELD }}</div>
        </script>
```

This is how I am assigning it to my cellTemplate:

``` javascript
cellTemplate: 'readParamNameCell.html'
```

Whenever I access my page, I am getting a console error:

>    Syntax error, unrecognized expression: <div class="ui-grid-cell-contents" tooltip="{{grid.getCellValue(row, col)}}">{{ grid.getCellValue(row, col) }}</div>
>     at Function.Sizzle.error (http://localhost:50140/Scripts/jquery-1.9.1.js:4421:8)
>     at tokenize (http://localhost:50140/Scripts/jquery-1.9.1.js:5076:11)
>     at select (http://localhost:50140/Scripts/jquery-1.9.1.js:5460:11)
>     at Function.Sizzle (http://localhost:50140/Scripts/jquery-1.9.1.js:3998:9)
>     at jQuery.fn.extend.find (http://localhost:50140/Scripts/jquery-1.9.1.js:5576:11)
>     at jQuery.fn.jQuery.init (http://localhost:50140/Scripts/jquery-1.9.1.js:196:38)
>     at jQuery (http://localhost:50140/Scripts/jquery-1.9.1.js:62:10)
>     at compile (http://localhost:50140/Scripts/angular.js:6824:25)
>     at http://localhost:50140/Scripts/angular-ui/ui-grid.js:3763:31
>     at Array.forEach (native) angular.js:11358(anonymous function) angular.js:11358$get angular.js:8445processQueue angular.js:12922(anonymous function) angular.js:12930$get.Scope.$eval angular.js:14123$get.Scope.$digest angular.js:13939$get.Scope.$apply angular.js:14227bootstrapApply angular.js:1487invoke angular.js:4152doBootstrap angular.js:1485bootstrap angular.js:1505angularInit angular.js:1399(anonymous function) angular.js:25579jQuery.Callbacks.fire jquery-1.9.1.js:1037jQuery.Callbacks.self.fireWith jquery-1.9.1.js:1148jQuery.extend.ready jquery-1.9.1.js:433completed

However if I provide it as a string...it works:

``` javascript
cellTemplate: '<div class="ui-grid-cell-contents" tooltip = "{{COL_FIELD}}" tooltip-append-to-body="true" tooltip-popup-delay="400" >{{ COL_FIELD }}</div>'
```

**Comment by scientificraj** [comment]
That solved the issue. Thanks.

**Comment by ctthang** [comment]
Upgrade jquery to 1.11.2 to solve the issue.

**Comment by shashankGopannagari** [comment]
Hello guys,

Adding to this,  I am gettring problem with `uib-popover-html `and `uib-popover-template ` in  ui-grid

could you please provide me a one example. 


IN ui-grid i want show popover with   html content

**Comment by happyharshit1** [comment]
Hi
how can i get an image as tooltip,
please help me out as i am new to angular-js ,

Thanks
