### ISSUE TITLE
Enable the use of native checkboxes in ui-grid-selection

### ISSUE THREAD

**Issue by pmq** [angular-ui/ui-grid#2090]
Hi there, we're evaluating a migration from 2.x to 3.x and wondering whether ui-grid-selection will at some point support an option to use native checkboxes instead of the div with '\c362'?
Many thanks!

**Comment by bharathkarthi09** [comment]
@pmq Hi, 
I need your help 
 we're evaluating a migration from 2.x to 3.x and wondering whether ui-grid-selection will at some point support an option to use native checkboxes instead of the div with '\c362'?

can i know the example of this.
