### ISSUE TITLE
uiGridConstants not available ?!

### ISSUE THREAD

**Issue by bhochberger** [angular-ui/ui-grid#2112]
Hi, 
i tried to use the new Constants for the Scrollbars like this:

```
  $scope.gridOptions.enableHorizontalScrollbar = uiGridConstants.scrollbars.ALWAYS;
```

all I get is an error 'uiGridConstants is not defined'

```
  $scope.gridOptions.enableHorizontalScrollbar = 1;
```

is working fine. Facing the fact that the sources are changed very often, i would feel more comfortable using those constants instead of the specific values. But how can i achieve this?

Here is a plunker:

http://plnkr.co/edit/h0ewAZK616rKCH3T62te?p=preview

**Comment by leverettj** [comment]
Not intending to stir trouble, but as the maker of a component, the team should keep a reference to this constants object available within the object model at all places where it will be used.  It makes the component easy to use, and thus increases it's popularity.
