### ISSUE TITLE
Can not change aggregateTemplate once set.

### ISSUE THREAD

**Issue by Sventric** [angular-ui/ui-grid#2122]
We have a grid view of project hours with periods in a selected range of dates.

Say a view of weeks between now and next month or months between now and 6 months from now.

We use grouping to group the projects per type and in those period-columns in the grouping-row we sum up the hours of that column for that type of projects.

So we have a dynamically columns count and where i set up those columns i also set up the aggregateTemplate, but even though i set this on the gridOptions it does not get processed.

**Comment by swalters** [comment]
Closing old 2.x issue as all current development is on 3x. 

If someone really needs this fix for 2.x, my advice is to fork and fix it.  Sorry, I know it's not ideal, but it is the best we can offer with limited resources.
