### ISSUE TITLE
Delete Selected row

### ISSUE THREAD

**Issue by calvinKG** [angular-ui/ui-grid#2125]
Hi 

How do you delete selected row?
 In the ng-grid I used to do it like this: 

 var index = $scope.Data.indexOf(schID);
                            $scope.gridOptions.selectItem(index, false);
                            $scope.Data.splice(index, 1);

**Comment by blowsie** [comment]
@PaulL1 The links provided no longer have any code for the handling of deleting rows, where can I find the latest example?

**Comment by PaulL1** [comment]
The example above from calvinKG shoudl work.  Essentially all you need is to splice to remove the row from your data.  If you need to find a specific row, then the indexOf gives you the index in the data, and setting the row to not be selected is wise.
