### ISSUE TITLE
how to highlight a row using ng-mouseenter/leave in a rowTemplate?

### ISSUE THREAD

**Issue by jmcmichael** [angular-ui/ui-grid#2129]
Thanks for this fabulous datagrid, I'm enjoying working with it and so far it looks like it has all the features we'll need (and more).

I'm working on a simple grid with listing items that will change the application's state when a row is clicked. I've figured out how to call a function when a row is clicked using ng-click and getExternalScopes to call a function that changes the state, but I'm having trouble showing a highlight effect on the entire row using ng-mouseenter/leave and ng-class. It works to some extent, but only highlights the cell, not the row.

My rowTemplate currently looks like:

``` javascript
$scope.gridOptions = {
rowTemplate: "<div ng-repeat=\"(colRenderIndex, col) in colContainer.renderedColumns track by col.colDef.name\" \
ng-mouseleave=\"hover=false\" \
ng-mouseenter=\"hover=true\" \
ng-click=\"getExternalScopes().rowClick(row)\" \
class=\"ui-grid-cell\" \
ng-class=\"{ 'ui-grid-row-header-cell': col.isRowHeader, 'rowHover': hover }\" \
ui-grid-cell></div>"
}
```

I'm currently unsure of how to toggle a class on the actual row and not a cell.

**Comment by tonny008** [comment]
.ui-grid-row:nth-child(odd):hover .ui-grid-cell{background:red}
.ui-grid-row:nth-child(even):hover .ui-grid-cell{background:red}

**Comment by Goodwin-Git** [comment]
Wow! @tonny008 you nail it !!!

Thank you!

**Comment by jazlopez** [comment]
@tonny008 answer is working. 

I will go with this option instead of replacing a lot of rowTemplate code.

**Comment by skybutter** [comment]
I tried @tonny008 answer.  It is only working for even row, but not odd rows.

**Comment by UnnamedSong** [comment]
Finally I found it.
@tonny008 Thank you very much!

**Comment by Cdvalencia** [comment]
i have done it, this:
.ngCanvas > div:hover { background: #ddd; }

this work me. well

**Comment by nkantkumar** [comment]
It works for me using css only
.ui-grid-row:nth-child(even):hover .ui-grid-cell{background:#F5F5F5}
.ui-grid-row:nth-child(odd):hover .ui-grid-cell{background:#F5F5F5}

**Comment by alpeshmail** [comment]
Css is making a sense for row hover color on mouse enter and leave.
hover color is working fine for regular columns, when we do the ping on left column using ui-grid-pinning directives then it didn't work as expected, hover color comes for either non-pinging/ping section but not for both together.

**Comment by lbntly** [comment]
@alpeshmail I'm experiencing the same issue, have you found a workaround for this?

**Comment by gjkamstra** [comment]
Same problem as @alpeshmail and @lbntly, did somebody find a solution?

**Comment by lbntly** [comment]
@gjkamstra Yeah, I ended up setting a custom `rowTemplate` in `gridOptions`. This is my template:

`<div
	ng-repeat="(colRenderIndex, col) in colContainer.renderedColumns track by col.uid"
	ng-mouseover="grid.appScope.hoveredIndex = rowRenderIndex"
	ng-mouseleave="grid.appScope.hoveredIndex = null"
	ui-grid-one-bind-id-grid="rowRenderIndex + '-' + col.uid + '-cell'"
	class="ui-grid-cell"
	ng-class="{'ui-grid-row-header-cell': col.isRowHeader, 'your-hover-class': grid.appScope.hoveredIndex === rowRenderIndex}"
	role="{{col.isRowHeader ? 'rowheader' : 'gridcell'}}"
	ui-grid-cell>
</div>`

Then in css make `.your-hover-class` have whatever styling you want. (In my case it was a highlight color for the background color.)

It's not ideal, but it doesn't seem to affect performance in any notable way.

**Comment by gjkamstra** [comment]
Thanks @lbntly 
Works fine. Plunkr for reference:
http://plnkr.co/edit/bMLVkcXPCC2TMieUg6LB?p=preview

**Comment by viswa588** [comment]
Hi, i am using ag-grid, onkeypress i need to change the background color but the row is already selected. is any event to find that event

**Comment by saurajit** [comment]
@nkantkumar Your solution is working great for the grids without the selection checkbox, but with selection checkbox, it does not.

Reason is that the checkbox column is wrapped in a completely different wrapper
