### ISSUE TITLE
Support custom getRow comparison logic

### ISSUE THREAD

**Issue by eirenik** [angular-ui/ui-grid#2138]
This is just an "enhancement" request, but it would be nice to be able to provide a "comparison" function for getRow to use in this filter call instead of the hard-coded function.
<pre>
var rows = this.rows.filter(function (row) {
  return row.entity === rowEntity;
});
</pre>
It would be nice to be able to pass such a comparison function into selectRow, passing it along to getRow, so one could write:
<pre>
function byName(a,b) { return a.name === b.name; }
...
selectRow({name:'Foo'}, byName);
</pre>
Alternatively, permitting an Array.find()-compatible function directly might be most-efficient and flexible:
<pre>
selectRow(function (element, index, array) { 'Foo' === element.name; });
</pre>
Or, somewhat more elegantly:
<pre>
function byName(name) { return function (element, index, array) { name === element.name; }; }
...
selectRow(byName('Foo'));
</pre>
This can be considered related to the other issues I opened about row.entity not being === to the gridOptions.data entity.  I did look at the enableRowHashing option, and it seems that the hash is placed into the object used by row.entity without making it into the original in gridOptions.data -- which is a great thing if it means hashing only happens on the "virtual" displayed rows and copies of entities, and not on the original data.

**Comment by PaulL1** [comment]
This is a useful request, but not really in the current roadmap.  We have far too many good ideas in the repository already, giving the impression that we have a project riven with defects.

Accordingly, I am leaving the enhancement tag on this, but closing it.  If someone would like this functionality, we'd welcome a pull request that adds it.
