### ISSUE TITLE
expandableRowTemplate does not support Angular directives

### ISSUE THREAD

**Issue by eirenik** [angular-ui/ui-grid#2146]
The documentation for expandable rows describes them as being for "sub grids", but this functionality could be used to support more robust master/detail data presentation.

This does not work:

<pre>expandableRowTemplate:  '&lt;div&gt;&lt;button ng-click="alert(1);"&gt;Alert&lt;/button&gt;Etc...&lt;/div&gt;',</pre>

Also, templates could support {{}} interpolation -- ideally within the scope of the row-entity.

**Comment by rajivdey1** [comment]
Hi,
I am facing the same issue below given is my rowtemplate which doesnot work any click on the subgrid  triggers the click even instead of only triggering on clicking on button

     expandableRowTemplate: '<div> <input type="button" value="Delete" class="k-button" id="btnDelete" ng-click="{{$event.stopPropagation();grid.appScope.DeleteFile()}}" /><div ui-grid="row.entity.subGridOptions"  ui-grid-selection style="height:150px;"></div></div>',
