### ISSUE TITLE
ui.grid.pagination + filters only work with visible data rows, not the full dataset

### ISSUE THREAD

**Issue by singhparmjit** [angular-ui/ui-grid#2166]
see Plunker for demo:  http://plnkr.co/edit/bT9MxF?p=preview

When ui.grid.pagination is enabled with filter options the data that is currently visible is being filtered correct but rest of the data is disregared.

**Comment by kpats** [comment]
I know it's a closed issue as it didn't receive any response.
But is it possible to do so? If not in the UI grid itself then any suggestion for a workaround? 
I have a huge data and I need it to be filtered across whole data set and not just the displayed data..

**Comment by trollboy** [comment]
yeah, we feed in a *large* data set and let the user paginate through it in lieu of scrolling through all 10k rows.  Right now we're taking the data, feeding it to ui-grid, and on user input filtering it outside of ui-grid and then re-loading the grid.  This is painful, slow and awkward.
