### ISSUE TITLE
Expandable row with enableExpandable = false renders the expandable column 

### ISSUE THREAD

**Issue by MarkOfSine** [angular-ui/ui-grid#2167]
Even with the config setting enableExpandable = false the expandable column is still being rendered (which perhaps implies other expandable functionality is also being executed unnecessarily?)

Current quick fix is to also set enableExpandableRowHeader = false.

**Comment by kellymredd** [comment]
Hey, looks like I'm late to the party but I'm still seeing this issue in ui-grid - v3.0.0-rc.22 - 2015-06-15. 

Is this being addressed or should a new issue be opened?

**Comment by DmitryEfimenko** [comment]
I'm also late to the party, but yes, in the scenario when some asynchronous logic is in charge whether table is expandable or not, setting neither `enableExpandable` nor `enableExpandableRowHeader` is working. I still see header and it attempts to expand if I click on it.
Example:
```javascript
$http.get('someUrl').success(function(response) {
    if (!response.shouldBeExpandable) {
        $scope.gridOpts.enableExpandable = false;
        $scope.gridOpts.enableExpandableRowHeader = false;
    }
});
```
I think this issue should be reopened.
