### ISSUE TITLE
Grid Menu items should support "disabled" mode

### ISSUE THREAD

**Issue by eirenik** [angular-ui/ui-grid#2173]
For user-experience reasons it is desirable to be able to show menu items in a "disabled" state so the position of items on the menu remains constant, regardless of which items are valid at that moment.

**Comment by PaulL1** [comment]
This is a useful request, but not really in the current roadmap.  We have far too many good ideas in the repository already, giving the impression that we have a project riven with defects.

Accordingly, I am leaving the enhancement tag on this, but closing it.  If someone would like this functionality, we'd welcome a pull request that adds it.
