### ISSUE TITLE
Why DIVs, why not table/ tr/ td?

### ISSUE THREAD

**Issue by prashantjain68** [angular-ui/ui-grid#218]
To the developers of ngGrid,

I was wondering why you guys decided to use DIVs instead of table/ tr/ td tags? The browser does an excellent job of sizing, wrapping etc. 

We are looking for a table/ tr based solution. Is it possible that we can change the DIV's display type to table (assuming you are aware that there are display types table, table-row, table-cell etc).

Thanks
Prashant Jain

**Comment by hohwille** [comment]
For the record:
Handsontable is using HTML Tables and archieves a lot of the features with that:
http://handsontable.com/
Here is a demo from me with several features mixed:
http://rawgit.com/hohwille/30c3d427d987ef48b962/raw/434ef520c51d42596dc66a76a9420138933dcd68/gistfile1.html

However, I still understand that supporting features such as grouping is really tricky and table element could even make it worse in that case. Especially I also love the width resize behavior of ui-grid and I can not say if that would also work as smooth with tables:
http://rawgit.com/hohwille/cf6c031675755940cb9c/raw/83df8f536d70796b06a1ed1a0ba59b3a563dc924/gistfile1.html

**Comment by hohwille** [comment]
Please be aware that using DIV instead of TABLE is also causing accessibility problems. 
Blind people using screen-readers do not get a clue of what an ui-grid actually is and what data it contains. Unfortunately accessibility is not on the list of prioritized features of open-source hackers.
See also #696.

**Comment by PaulL1** [comment]
I think accessibility is on our prioritised list: #2840.  At the moment the problem is that we don't have any developers with experience of accessibility that have contributed time to adding it to this open source project.  :-)

**Comment by Downchuck** [comment]
Basic ARIA tags are certainly in reach of your average dev. I'm glad to see that you're prioritizing accessibility. Keyboard accessibility is part of WCAG.   ARIA is more about making sure you're using reasonable HTML attributes on your content.

**Comment by PaulL1** [comment]
As noted on #2840, we'd welcome contributions to accessibility.  At the moment we are prioritising getting to 3.0, so those items marked as 3.0 are getting attention.  But I'm sure it would be reasonably easy for someone to submit some PRs with the necessary tag changes.
