### ISSUE TITLE
[ui-grid 3.0.0-rc16] Enhancement: Implement a 'ui-grid-bootstrap-date-editor' directive

### ISSUE THREAD

**Issue by pmariduena** [angular-ui/ui-grid#2196]
I've looked all over the web, and this is the best I can find in terms of what you need for your cellTemplate, but it doesn't work:
$scope.gridOptions = {
  columnDefs: [
...
  {field: 'firstDate', displayName: 'First Date', editableCellTemplate: '<input type="text" datepicker-popup="{{datePicker.format}}" ng-model="COL_FIELD" datepicker-append-to-body=true />',
...
]};

When I double click on the cell to edit it, it goes blank, and double clicking on other cells doesn't end the edit action (only using the scroll wheel on my mouse does!!).

I also get no calendar pop-up when I double-click on the cell to edit it.

However, on a plunkr from someone else, it seems to work somewhat well (but again, the edit never ends here either).

http://plnkr.co/edit/8udsvZSokG5v37xicyuz?p=info

**Comment by pmariduena** [comment]
Any updates on whether anyone has created this directive yet?

**Comment by hummorsa** [comment]
it would be nice to have this :smiley:, just a little remainder. thanks.

**Comment by ariera** [comment]
+1 for this :D

**Comment by diabolicfreak** [comment]
+1

**Comment by ashwin027** [comment]
+1

**Comment by sameershenai** [comment]
+++1

**Comment by roisafirorichard** [comment]
+1

**Comment by thefewminutes** [comment]
please add this enhancement!

**Comment by jamesdhakera** [comment]
Any updates on this enhancement ?

**Comment by samirakazemi** [comment]
it would be nice to have it! please add this enhancement!^_^

**Comment by jainrocks** [comment]
I am new to unit testing in the angularJS. How to do the unit testing of such directive??

**Comment by jamesdhakera** [comment]
@surabhi-batra can you update your implementation in a plunker or something, i am not able to implement it

**Comment by karthik04** [comment]
+1

**Comment by azakharo** [comment]
+1
