### ISSUE TITLE
display cell value when mouse over/hover the cell within ng-grid

### ISSUE THREAD

**Issue by juststarted** [angular-ui/ui-grid#220]
Thanks to Tim, I was able to change the cell background color in ng-grid whenever I hover over it, by the use of cellClass within columnDefs and .css file.

So my next goal is to be able to display the cell value within ng-grid whenever I mouse over/hover.  I have set the columnDefs.width to a certain and sometimes the data value is longer than the column width.  So what's showing up is with the ecllipse.  I would like to place my cursor over it and have a tooltip in a way to display the extended value within the cell.  How do I do that?

Thanks!

**Comment by erikeckhardt** [comment]
Also note that in your columnDefs you can do [`cellTooltip: true`](http://ui-grid.info/docs/#/tutorial/117_tooltips).
