### ISSUE TITLE
afterSelectionChange fired multiple times with check box selection

### ISSUE THREAD

**Issue by visionarchitect** [angular-ui/ui-grid#221]
When You click on grid row then try to select row with checkbox - afterSelectionChange  is fired twice.

When You try to uncheck it happens too - it somehow selects row back by himself

http://plnkr.co/edit/hkDfuJVZRiKv9XXHoabJ

Here I calculate number of events fired
Single click in checkbox increments number by one
Click after clicking row increments two times

**Comment by jozhi** [comment]
tks, so I am here to get inspiration.

beforeSelectionChange:$scope.selectRow,


$scope.selectRow = function(rowItem, event){
	console.log(rowItem)
	return true;
};
