### ISSUE TITLE
grouping not working without debug data (2.x)

### ISSUE THREAD

**Issue by cdkeito** [angular-ui/ui-grid#2210]
Adding to the app (for more [infos see](https://code.angularjs.org/1.3.3/docs/guide/production))
```
.config(['$compileProvider', function ($compileProvider) {
      $compileProvider.debugInfoEnabled(false);
}])
```

```
self.onHeaderMouseDown() { // not only this
...
var headerScope = angular.element(headerContainer).scope();
...
}
```
scope() will return undefined, 
and with self.colToMove left to undefined, self.onGroupDrop() will do nothing.

from [angular docs](https://docs.angularjs.org/api/ng/function/angular.element):
>scope() - retrieves the scope of the current element or its parent. Requires Debug Data to be enabled.

**Comment by mooyah** [comment]
I am experiencing this problem as well. Will submit a pull-request once we find an appropriate workaround.

**Comment by mattslocum** [comment]
Pull Request here:
https://github.com/angular-ui/ng-grid/pull/3010

**Comment by imbalind** [comment]
Merged in.
