### ISSUE TITLE
Sort by Date Bug

### ISSUE THREAD

**Issue by sonicparke** [angular-ui/ui-grid#222]
When sorting a column that contains as date as a string like '2/02/2013' it's not sorting by month but by first character then the next. So the sort order is going like this:
1/22/2010
10/17/2010
12/17/2010
2/31/2010

etc.

Here's a plunker: http://plnkr.co/edit/zCkvcO?p=preview

**Comment by NomanChali** [comment]
@surajvpatil25 its working
