### ISSUE TITLE
Changing the Focus to a Cell

### ISSUE THREAD

**Issue by cks333** [angular-ui/ui-grid#2221]
We have a scrollto method in Angular UI-Grid which scrolls and brings the given row/col in our view if they are not in view.

What I need now is something which will give focus to the given row/col to. For example selecting the given row/col from a function. Possibly a scrollToFocus()?

I am using inline editing in the ui-grid and the focus has to go to a particular cell as per the user input in a cell and hence this need. Eg: User edit the data in A5 and the focus has to go to A6 automatically without the user manually clicking on the A6 cell.

For now, I managed to do a simple hack using JQuery to achieve this.  Every cell has its own div tag in ui-grid. I just introduced an id attribute based on the [PRIMARYKEY][COLUMN_NAME]. Then used the .focus() using JQuery to achieve the task. Works perfectly as required. Having said that, if we have a scrollToFocus(), it will be nice angularly !

**Comment by feralanPaladin** [comment]
Does anyone can manage to start editing wirh scrollToFocus method?

**Comment by vaibhavsharma27** [comment]
I am facing a problem when I add a row programatically and I use this scrollToFocus method. When there is no vertical scrollbar then I am getting focus on last added row, and when there is a scrollbar, I am getting the scrollbar at the last row, but there is no focus.

**Comment by BxB00T** [comment]
@feralanPaladin I was able to start editing in a hacky way by setting a custom cellClass to the cell i was aiming for, then I queried for this cell and did an element.dispatchEvent(dblClickevent) to simulate a click into the cell. 

https://stackoverflow.com/questions/18399215/how-to-programmatically-fire-a-dblclick-event-defined-with-addeventlistener
