### ISSUE TITLE
Hide/Remove default column menu items

### ISSUE THREAD

**Issue by Okazari** [angular-ui/ui-grid#2224]
Hi again,

I can't find how i can remove the "default" actions in the column menus (such as : Pin left, Pin right).

I know that plugins can add their own menu items, and that in the api you can add menu items, but I can't see any way to remove them.

I only want one option in the menu : Pin, no sort options etc...  (but I still want to sort with a click on the header) etc... 

Thanks.

**Comment by nesler** [comment]
I also have a use case, where I'd like to add some custom column menu options, but not show any of the default ones (sorting etc).

@Okazari did you ever get anywhere with this?

**Comment by Okazari** [comment]
@nesler We just forced our client to accept theses features, i cannot really help you on this sorry.

**Comment by nesler** [comment]
Allright..
@PaulL1 is it really not possible to hide menu items you don't want?
IMO this should be fully configurable. Yea, it's fine that the menu options appear by default, but it should be a requirement for a plugin to provide an option you could set to false, to hide the menu options.
I'm working on this for the most basic menu items, that I see in my use cases, but I can't cover everything with something generic, right?

**Comment by PaulL1** [comment]
I'm fine for it to be a requirement, so long as every contributor agrees.  :-)  

In other words, it's open source code, we generally get what people thought was useful for their particular plugin, and so long as it meets code quality standards we generally accept it and are grateful.  If you don't like the options a particular feature provides you can either submit a PR to improve them, or choose not to use that feature and write your own. 

I suspect you could write a rowsProcessor or columnsProcessor that edited the overall menus, but it would have it's fingers pretty far into the code.

**Comment by windmaomao** [comment]
I think all plugin developer should have an option to display menu entries. And if the core API support that, that'll be great.

**Comment by SkylarLK9998** [comment]
In addition to removing/hiding unwanted menu options, one should be able to add menu items that trigger features they create.
