### ISSUE TITLE
Intercepting a double-click event

### ISSUE THREAD

**Issue by mbcooper** [angular-ui/ui-grid#2228]
My client has a need to do some special processing when they double-click a row.  It seems to be consumed somehow ... Is there a way i can register an external callback on an event like a double-click?

--mike

**Comment by ComeOutToPlay** [comment]
I am having the same need also. But, I am using Angular ui-grid version 3.0.0-RC.18.

I want to implement a double-click event in an ui-grid table. In particular, I want to open a modal pop-up when double-clicking at a row. 

I tried to use a ng-dblclick directive inside the rowTemplate definition as is suggested by mbcooper, but 'dblclick' event is never fired.

Nevertheless, I found a solution, but using a directive created by my own. Can I do it better, without creating a directive?

Any comment would be appreciated.

**CODE:** 

My code at the Controller is as follows:  

    $scope.onDblClick = function(row) {
        var url = '//google.com';
        $window.open(url, "_blank", "height=600,width=800,toolbar=no,location=no,menubar=no,titlebar=no");
    }

	// Define the New Conflicts Simulation GRID behavior
	$scope.myGridOptions = {
		showFooter: false,
		enableSorting: true,
		multiSelect: false,
		enableFiltering: true,     
		enableRowSelection: true, 
		enableSelectAll: false,
		enableRowHeaderSelection: false,  
		enableGridMenu: true,
		noUnselect: true,
		onRegisterApi: function (gridApi){
            $scope.gridApi = gridApi;
		},
        rowTemplate: "<div ng-dblclick=\"onDblClick(row)\" ng-repeat=\"(colRenderIndex, col) in colContainer.renderedColumns track by col.colDef.name\" class=\"ui-grid-cell\" ng-class=\"{ 'ui-grid-row-header-cell': col.isRowHeader }\" ui-grid-cell dbl-click-row></div>"            

	}

(Where dbl-click-row indicates I am using the dblClickRow directive)

My code at the View is as follows:

    <div id="myGrid" ui-grid="myGridOptions" ui-grid-selection ui-grid-resize-columns class="gridTable" ></div>

My code at the Directive is as follows:

    var angularStartDirectives = angular.module('angularStart.directives', []);     
    
    angularStartDirectives.directive('dblClickRow', ['$compile', '$parse',  function($compile, $parse) {
      return {
        priority : -190, // run after default uiGridCell directive
        restrict : 'A',
        scope : false,
    
        compile: function($element, attr) {
      	
      		// Get the function at ng-dblclick for ui-grid
          	var fn = $parse(attr['ngDblclick'], /* interceptorFn */ null, /* expensiveChecks */ true);
    
    		return function ngEventHandler(scope, element) {
    
                element.on('dblclick', function(event) {
    
                  var callback = function() {
                  	
                  	if ($scope.gridApi.grid.selection.lastSelectedRow)
                  	{
                   		fn($scope, {$event:event, row: $scope.gridApi.grid.selection.lastSelectedRow.entity });
                   	}
                  };
    
                  $scope.$apply(callback);
    
            	}
            )};
    
    	}
    
    	};
    } ]);

**Comment by bielmenezes** [comment]
Hello  @ComeOutToPlay,

I'm resolving this need with the @mbcooper suggestion and it's working perfect for me.

Firstly, you have to informe the external-scope at the grid declaration, as follow:

<div ui-grid="gridOptions" ui-grid-paging  external-scopes="gridHandlers" ></div>

Secondly, you have to declare in your controller the 'external scope' (the gridHandlersin my case) attribute and its elements, as follow:

 $scope.gridHandlers = {
    	onGridDoubleClick : function(rowItem) {
    		//your function goes here
    	}
    }

And the final step is to declare the row template with the ng-dblclick attribute in the gridOptions:

    $scope.gridOptions = {
    	   ...
	    rowTemplate: '<div ng-dblclick="getExternalScopes().onGridDoubleClick(row)" ng-repeat="col in colContainer.renderedColumns track by col.colDef.name" class="ui-grid-cell" ui-grid-cell></div>',
}

I hope it can help you.

**Comment by ComeOutToPlay** [comment]
Thank you! 

My mistake was not to use external-scopes, and try to solve the problem with ng-dblclick only. 

ng-dblclick is never fired if you do not use external-scopes.

Thank you again for your clear explanation!!

**Comment by swalters** [comment]
FYI, in master, the external-scopes attribute and getExternalScopes() is no more.  

Now, the same scope that you assign gridOptions is assigned to grid.appScope.  If that doesn't work for you app, there is now gridOptions.appScopeProvider = whateverYouWant.  appScopeProvider will then be assigned to grid.appScope.

This will be detailed in the release notes for the next RC

**Comment by bielmenezes** [comment]
Hello @swalters,

Thanks for let us know this change before our code breaks!!

**Comment by ComeOutToPlay** [comment]
Hello @swalters,

How can I update my code, considering the appScopeProvider? What I am missing?

I have at the view:

```
<div id="myGrid" ui-grid="myGridOptions" ui-grid-selection ui-grid-resize-columns class="gridTable" ></div>
```
In the controller:

```

$scope.myGridOptions = {
    showFooter: false,
    enableSorting: true,
    multiSelect: false,
    enableFiltering: true,     
    enableRowSelection: true, 
    enableSelectAll: false,
    enableRowHeaderSelection: false,  
    enableGridMenu: true,
    noUnselect: true,
    onRegisterApi: function (gridApi){
        $scope.gridApi = gridApi;
    },
    appScopeProvider: { 
          onDblClick : function(row) {
               var url = '//google.com';
               $window.open(url, "_blank", "height=600,width=800,toolbar=no,location=no,menubar=no,titlebar=no");
          }
    },
    rowTemplate: "<div ng-dblclick=\"onDblClick(row)\" ng-repeat=\"(colRenderIndex, col) in colContainer.renderedColumns track by col.colDef.name\" class=\"ui-grid-cell\" ng-class=\"{ 'ui-grid-row-header-cell': col.isRowHeader }\" ui-grid-cell ></div>"
}

```

**Comment by tasnimpulikkal** [comment]
how to make a button click display a modal popup inside uigrid.

**Comment by c0bra** [comment]
@tasnimpulikkal http://brianhann.com/create-a-modal-row-editor-for-ui-grid-in-minutes/ this has instructions on opening a modal by clicking a button, specifically for a row editor but you could use the modal for whatever purpose you want.

**Comment by tasnimpulikkal** [comment]
@c0bra Thanks a ton for this share. Quick question. How can i disable the forms in the modal popup and just display one single field for example outside my forms ie eg: message field.

**Comment by c0bra** [comment]
You can alter the modal template and put whatever you want in it. The row
should be available in the modal controllers scope.

**Comment by asiam9** [comment]
@ ComeOutToPlay,

I used above code for popup window generation. when I double click on grid it's opening google window in new page. how can I open grid row details popup page.
I am new to angularjs, can you send me a sample code, that will help me more. 
Thank you.

**Comment by ComeOutToPlay** [comment]
Hello @asiam9 

When I show popup details, I use angular-ui-bootstrap. Please refer to Index.html.

  <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet"/>
  <script src="//angular-ui.github.io/bootstrap/ui-bootstrap-tpls-0.13.0.js"></script>

Here is an example:

http://plnkr.co/edit/cq7s9lKn90xTVgNxIC6b?p=preview

I hope it works for you!

**Comment by jaynaruto** [comment]
Thanks a lot! AppScopeProvider seems more useful. @ComeOutToPlay

**Comment by jeuvin** [comment]
I have this implementation for a modal popup on double click. The problem I'm having now is adding a  bootstrap daterange picker. I don't want to use the native datepicker. The fact that I'n assigning the appScope a function in the gridOptions is not allowing me to have a second assignment for bootstrap datepicker. How can I work around this or is there a better way to implement both,

[Here is my stackoverflow question with more details.
](http://stackoverflow.com/questions/35628616/problems-getting-bootstrap-daterangepicker-to-work-in-filterheadertemplate-with)

Here is an example plunker with the problem I'm having.

[Plunker](https://plnkr.co/edit/0ep0Giw69wKV2oP3zEii)

**Comment by cookatrice** [comment]
Thanks a lot for your comment. @ComeOutToPlay .
I use your writing. :)
but I have some question. Why use appScopeProvider option?
I search that option on docs (http://ui-grid.info/docs/#/api/ui.grid.class:GridOptions) and find that by default, the parent scope of the ui-grid element will be assigned. 
So in my case, I use just parent scope's function.

What is better benefit to use appScopeProvider option? 
Thanks again bro.

**Comment by VictorHPereira** [comment]
> Hello @ComeOutToPlay,
> 
> I'm resolving this need with the @mbcooper suggestion and it's working perfect for me.
> 
> Firstly, you have to informe the external-scope at the grid declaration, as follow:
> 
> ```
> <div ui-grid="gridOptions" ui-grid-paging  external-scopes="gridHandlers"/>
> ```
> 
> Secondly, you have to declare in your controller the 'external scope' (the gridHandlersin my case) attribute and its elements, as follow:
> 
> ```js
>  $scope.gridHandlers = {
>         onGridDoubleClick : function(rowItem) {
>             //your function goes here
>         }
>     }
> ```
> 
> And the final step is to declare the row template with the ng-dblclick attribute in the gridOptions:
> 
> ```js
>     $scope.gridOptions = {
>            ...
>         rowTemplate: '<div ng-dblclick="getExternalScopes().onGridDoubleClick(row)" ng-repeat="col in colContainer.renderedColumns track by col.colDef.name" class="ui-grid-cell" ui-grid-cell></div>',
> }
> ```
> 
> I hope it can help you.

@bielmenezes I'm new at angular and the way you explained it was super simple to understand!
Appreciated for your effort!!!

**Comment by jsV8** [comment]
https://javascripter.space/questions/utilizing-ng-repeat-ng-grid-and-ng-click-in-angular-a-comprehensive-guide
