### ISSUE TITLE
Cannot only disable pining right

### ISSUE THREAD

**Issue by Okazari** [angular-ui/ui-grid#2235]
Hello,

I'd like my user to be able to pin on the left, but not on the right. The only option is to disable pinning.

Is there any way to do that ?

Thx.

**Comment by PaulL1** [comment]
This is a useful request, but not really in the current roadmap.  We have far too many good ideas in the repository already, giving the impression that we have a project riven with defects.

Accordingly, I am leaving the enhancement tag on this, but closing it.  If someone would like this functionality, we'd welcome a pull request that adds it.

**Comment by cool5785** [comment]
Hello PaulL1, I have tried to add the option to hide Pin Left or Pin Right and raised pull request, kindly review.
