### ISSUE TITLE
How to clear selections?

### ISSUE THREAD

**Issue by summer-liu** [angular-ui/ui-grid#2243]
I'm using ngGrid in a modal. Each time when I open modal, I need to select some items and do some actions, but $scope.gridOptions.selectedItems keeps all the history of selections.

 When I try to clear the selections with $scope.gridOptions.selectedItems = [ ], next time nothing can be selected.  Is there a way to clear selections history each time I close the modal?

**Comment by shakhal** [comment]
Seems like it's
````
$scope.gridApi.selection.clearSelectedRows()
````
