### ISSUE TITLE
Need help hidding expandable buttons and the header.

### ISSUE THREAD

**Issue by Mako-L** [angular-ui/ui-grid#2245]
I want to hide the headers and the expandable buttons and I want to add a doubleClick() function on the row so that it expands when I double click it. I also want to put a page template instead of another grid template inside the expanded area . Do you guys think that it is possible? And how should I proceed. Thanks!

**Comment by chavag** [comment]
add "enableExpandableRowHeader: false" to grid options

**Comment by BajoriaNeha** [comment]
Thanks @chavag, it works add "enableExpandableRowHeader: false".

**Comment by em-pmane** [comment]
I want to hide header + sign only. Do you guys think that it is possible?How?

**Comment by BajoriaNeha** [comment]
@em-pmane : So far I understand your query, you want to use expand function with some other icon , you can use the following code:
$scope.gridOption = {
                    // Disable default expand Icon and column
                    enableExpandableRowHeader: true,
}
columnDefs = [{
// Add a new column with your icon
                        name: 'Expandable',
                        displayName: '',
                        headerCellClass: 'header-cell',
                        cellClass: 'center-align',
                        enableCellEdit: false,
                        enableFiltering: false,
                        width: '14%',
                        cellTemplate: "<div class=\"ui-grid-cell-contents expand-row\">" +
                        "<i class=\'icon-margin fa fa-pencil-square-o\' " +    
                        "ng-click=\"grid.api.expandable.toggleRowExpansion(row.entity)\"></i>" +
                        "</div>"
                    }],

where -> // fa fa-pencil-square-o is icon to expand/collapse row

**Comment by em-pmane** [comment]
@BajoriaNeha Thank You Neha, But  I don't want to use another icon rather I want to remove it but from column header only.Because with default state rows having + sign for rows expansion and for all rows expansion we have to use column header + icon.I want to remove that column header + icon only.

**Comment by BajoriaNeha** [comment]
@em-pmane : You can visit the below link, I hope it solve your problem.
http://plnkr.co/edit/zUQPKllFMMUNwl99tXCz?p=preview

**Comment by em-pmane** [comment]
@BajoriaNeha Thanks very much. This is what exactly I wanted.

**Comment by shashankGopannagari** [comment]
Thank you so much @BajoriaNeha
