### ISSUE TITLE
ui.grid autoResize blocks all protractor testing because it uses $timeout

### ISSUE THREAD

**Issue by jankoprowski** [angular-ui/ui-grid#2247]
Hi,

  After using ui.grid.autoResize HTML directive in ui-grid all protractor tests for our application 'hold' because under https://github.com/angular-ui/bower-ui-grid/blob/master/ui-grid.js#L10661-L10680 $timeout is used.

  It is well known protractor's waitForAngular problem and the solution is to use $interval with canceletion instead:

https://github.com/angular/protractor/issues/169

**Comment by mscharp** [comment]
After running into this issue and subsequently finding this thread, I can confirm that RC18 does fix this problem.  Thank you!
