### ISSUE TITLE
Select rows after setting data

### ISSUE THREAD

**Issue by MuadDib** [angular-ui/ui-grid#2267]
I have a need to select rows programmatically after data is loaded. For example select row0 as soon as data is loaded.

Data, when loaded, is obviously missing $$hashkey and thus unable to be selected. I created ugly workaround by calling select function with $timeout.

This doesn't work:

``` javascript
    $scope.gridOptions.data =  someData;
    $scope.gridApi.selection.selectRow($scope.gridOptions.data[0]);
```

This works:

``` javascript
    $scope.gridOptions.data =  someData;
    $timeout(function () {
        $scope.gridApi.selection.selectRow($scope.gridOptions.data[0]);
    },
    100)
```

I spent some time trying to find event after data is processed by ui-grid but I was unable to. If there is any more elegant solution it would be quite appreciated,

**Comment by deepfriedbrain** [comment]
Is there a "after data is rendered" event available now? Using timeout isn't an ideal approach, and I'm not able to find a better alternative. 

Thanks.

**Comment by GB11111** [comment]
I had to write a silly hack function to get the grid to refresh... it works.
	
gridRefreshSillyHack = function() {
		
		var tempRow= {
				column1: "",
				column2: "",
				column3: ""
			};
		$scope.myTableData.push(tempRow);
		
		$timeout(function () {
			$scope.myTableData.pop();	    
			},1
		);

		$timeout(function () {
                        // selectedRowIndex was set in grid options' afterSelectionChange 
			$scope.gridOptions.selectRow(selectedRowIndex, true); 
	    	},1
	    );
}

**Comment by zeodtr** [comment]
As of v3.0.0-rc.22, you can call `modifyRows` as follows:

```javascript
$scope.gridOptions.data =  someData;
$scope.gridApi.grid.modifyRows($scope.gridOptions.data);
$scope.gridApi.selection.selectRow($scope.gridOptions.data[0]);
```

No $timeout needed.

**Comment by tim-lukacik** [comment]
@zeodtr Thank you for the solution. Could someone clarify the use of `$scope.gridApi.grid.modifyRows($scope.gridOptions.data);`? I see I cannot use selectRow without calling that first.

**Comment by rokerlab** [comment]
Select only those rows who have boolean value after getting data?
