### ISSUE TITLE
[Updated] Horizontal scrolling performance is terrible in IE9

### ISSUE THREAD

**Issue by acostaf** [angular-ui/ui-grid#2273]
On this grid you may see the Horizontal and Vertical Scrollbar completely out of place, that just happens when you see it on IE9
![grid issue 2](https://cloud.githubusercontent.com/assets/1760318/5298103/1241a0c8-7baf-11e4-9336-8afa3a0044ba.png)

Same grid opened on Chome 41
![grid issue 3](https://cloud.githubusercontent.com/assets/1760318/5298102/1241a4a6-7baf-11e4-8c17-b3b916b5cbea.png)

In this grid taken from http://ui-grid.info/docs/#/tutorial/213_auto_resizing you also may see the same issue since I am opening it on IE9
![grid issue 1](https://cloud.githubusercontent.com/assets/1760318/5298104/12427714-7baf-11e4-8ccd-5b2d0ecfccea.png)

**Comment by PaulL1** [comment]
Could someone look at this on the latest unstable.  There have been quite a few changes gone in on scrolling which may resolve this.  Also, the grid menus are now positioned absolute, which should fix the popup menus.

**Comment by alexandery** [comment]
@PaulL1 I just checked one of the tutorial pages with IE9 and see that the scrollbars are in place, however there seems to be an issue with a horizontal scrolling - as if a scrollbar appears even when it doesn't need to be there and when engaged it does move columns but not the header.

Here is the screenshot:

![scroll ie9](https://cloud.githubusercontent.com/assets/3676316/5748059/1a32a5b4-9bfa-11e4-91cc-109584b05f90.png)

**Comment by swalters** [comment]
I can say that it is a total pig on IE9.  Unusable.  Maybe IE9 fires more scroll events than the other browsers and therefore we need to throttle it.

**Comment by c0bra** [comment]
Note to self: look at using `track by $index` on col repeater unless there's custom cellTemplates in the column defs, and alter the repeater template if a cellTemplate appears or all disappear from the column defs.

**Comment by c0bra** [comment]
Changing the topic of this bug as the scrollbar positioning in IE9 is fixed, but the horizontal performance issue is still present.
