### ISSUE TITLE
Add ability to retrieve unstable build via Bower

### ISSUE THREAD

**Issue by moberemk** [angular-ui/ui-grid#2276]
For internal development we'd like to use the unstable build of this component. Dependencies in our application are managed via Bower but we have no way to retrieve the unstable version using it that I can find; is there a way to make that available for use?

**Comment by kencaron** [comment]
@moberemk Old, but this is how I worked around this issue:

```
"angular-ui-grid": "https://github.com/angular-ui/ui-grid.info.git#gh-pages"
```

**Comment by pmariduena** [comment]
@kencaron Thanks for the tip. But that doesn't work at all. 
@PaulL1 I don't want to build the javascript code (though I admit I have read the developer instructions). Seems it would be just as easy to copy all the release files down if I want the unstable version (at least for now).
