### ISSUE TITLE
GridMenu doesn't scroll columns if a long list

### ISSUE THREAD

**Issue by ghost** [angular-ui/ui-grid#2278]
If I enable the GridMenu and have a grid (as in my case) that has 35 columns, the menu does not scroll so I can't get to the bottom entries.On a 1280x1024 monitor, it shows about 25 of the columns.
![image](https://cloud.githubusercontent.com/assets/9431902/5304479/05194b50-7bc1-11e4-9ac5-2f5d9e220f9b.png)

**Comment by JasonWWalton** [comment]
@steverA was there a resolution to the problem you observed with the gridMenu, where if the grid doesn't extend all the way to the right side, the gridMenu appears at the right side of the page?  I'm seeing the same thing in IE9 and trying to track it down.

**Comment by steverA** [comment]
I haven't seen it in newer versions. I am seeing a problem of z-order with the latest being over and under other widgets on the page.

**Comment by JasonWWalton** [comment]
Thanks for replying.  Are you referring to newer versions of angular, or of the ui-grid?  (We have been using 1.3.7 and 3.0.0 rc18)

**Comment by steverA** [comment]
The grid – I’m using v3.0.0-rc.19-0fc6b21 - 2015-02-18
