### ISSUE TITLE
ui-grid 3.0 three-state sorting

### ISSUE THREAD

**Issue by buddyackerman** [angular-ui/ui-grid#2286]
New to version three is a the three-state sorting on the columns where the first click sorts ascending, the second click sorts descending and the third click turns sort off for that column.  Our users have found this confusing as no one knows what is supposed to happen when no sorting is selected.  In the version 2.x grid there was only two-state sorting i.e. it just toggled between ascending and descending with no state of “not sorted”.  

We are using external sorting on the grid so the issue is that when turning sorting off the grid basically just stays the same because the external sorting is not going to do any work to randomly sort things just to show the user that their action caused a change.

I would like to have the ability to configure the grid to use the "old" two-state sorting functionality.

**Comment by httpete** [comment]
This would be better if I could just configure this at the top level in gridOptions. Conceptually I want to not support 3 state sort anywhere, and logically there is just one place I should do that. We are using externalSorting true.

**Comment by fkoehler** [comment]
In my opinion this one is not solved. We want that the whole grid acts in a two state sorting mode. If you add "suppressRemoveSort" to every column than once you have activated that sort you can never remove it, meaning you can not change to one other column to sort against that.

To reproduce just add  "suppressRemoverSort: true" to at least two columns and try to sort by only one column and changing between the two.

**Comment by sjlynch** [comment]
Agreed, this is not a full solution. My users find the 3-sort confusing and I don't think I can push out an update until the bug pointed out by @fkoehler is fixed or a good workaround is found.. :(

**Comment by PaulL1** [comment]
OK, I'm going to look at this to come up with a different set of options that in combination give some more flexibility.  The problem I think I have is that when people say "I want a 2 state sort" they're ignoring the fact that for most columns, upon opening the page, they are unsorted.  If we say once you touch a column it must stay sorted, then you're saying you cannot return the page to the way it was when you opened it.

I think that the function people want that isn't base functionality at present is a `sortMinOneCol` option, which when set allows the sort to be removed from a column, but only if another column has sort being added.

I think that I need to rejig the options to give that outcome.  I think that the new options would be:

1.  `sortAtLeastOneCol` at the gridOptions level, which means that at least one column always has to have a sort
2.  `suppressRemoveSort` at the column level, which means that this column cannot have it's sort removed - it always is sorted asc or desc

**Comment by httpete** [comment]
PaulL1, yes - but we always come in with one column sorted. The behavior you describe is like a radio choice, it can come in unchecked but once checked, you can't uncheck it - only check another. totally legit.

**Comment by PaulL1** [comment]
@httpete: maybe totally legit, except if I want to sort on another column, then I want the sort on this column to go away.  Hence three states - this column is sorted ASC, it's sorted DESC, or it's not sorted (presumably because, in your case, you've sorted on another column).

**Comment by MaltiGumber** [comment]
Hello Everyone,
We are also facing the same problem. As per our requirement, we need [asc/desc] sorting on column.
Please suggest the solution.

**Comment by MaltiGumber** [comment]
I have added the code that is using above suggested options 'sortAtLeastOneCol' and 'suppressRemoveSort' on plunker. 

Here is the link http://plnkr.co/edit/dGnaoyhUtiwWCCgna2Xo?p=preview. 

Please suggest the solution as we are in very crucial stage of our project.

**Comment by boroth** [comment]
@MaltiGumber I don't think those options have been added. For now I'd recommend just specifying 
        suppressRemoveSort: true
for every column that you need to.

**Comment by mansa-dev** [comment]
Is there any good solution for removing 3 way sort, It is the most confusing feature.

**Comment by swalters** [comment]
this commit should address this issue.  https://github.com/angular-ui/ui-grid/commit/3eca46e99766eb0cc9f330948f68739dbf7d7bff
