### ISSUE TITLE
Play nice with bootstrap

### ISSUE THREAD

**Issue by jasedwards** [angular-ui/ui-grid#2290]
I saw this issue mentioned in a discussion about another issue but could not tell if one was specifically opened up for this.  If I give my grid a class of col-sm-12 the left is aligned correctly but the right side extends past the page.  I have tried doing a window resize and that will make it a little better but it still ignores the actual bootstrap column styling.

![image](https://cloud.githubusercontent.com/assets/5818023/5328839/047d8e6c-7d57-11e4-8d27-c07f540d97cb.png)

As you can see the grid hits the right border of the container and there should be a 15px margin.

**Comment by PaulL1** [comment]
I'm wondering about whether we (someone) should create a bootstrap feature, which adds styles and formatting for bootstrap, and perhaps uses the bootstrap editors for the edit feature as well.  It seems like a lot of people would use the grid with bootstrap, so if it doesn't play nice we should deal with it.
