### ISSUE TITLE
Can you pass (non string) arguments to a cell filter?

### ISSUE THREAD

**Issue by wgorder** [angular-ui/ui-grid#2296]
What I would like to be able to do is either provide a function to the cell filter (essentially for formatting text)

```
  cellFilter: function(arg1) {
    console.log("arg1" + arg1);
  }
```

or better yet call a filter defined elsewhere but pass it a variable from the scope needed in the filter logic like shown here:
http://stackoverflow.com/questions/14841897/how-to-pass-param-to-a-filter-function-in-angular-js

Are either of these possible currently?

**Comment by revathisamanthula** [comment]
@wgorder 
Will you please share Document Link Or Plnkr.
