### ISSUE TITLE
[3.0] Handling row double click event

### ISSUE THREAD

**Issue by Bhimisetty** [angular-ui/ui-grid#2314]
Can we handle the row double click event in UI-grid?

**Comment by Coralma** [comment]
@c0bra and @Bhimisetty I try the  http://plnkr.co/edit/l35YGxU5MKfghTm9du8R?p=preview sampler but it doesn't work. Did the latest ui-grid version change the way of custom cell template?

**Comment by c0bra** [comment]
@Coralma `getExternalScopes()` was changed a while back. I've updated the plunker to reflect the change.

**Comment by JasonRodman** [comment]
Is there no way to intercept a double click on a row?
