### ISSUE TITLE
Scrolling to top issue

### ISSUE THREAD

**Issue by MakoMakox** [angular-ui/ui-grid#2317]
I'm trying to make a row scroll to top and expand when i double click it I'm having issues with the scrolling part I found 
```javascript
$scope.scrollTo = function() {
    var grid = $scope.gridOptions.ngGrid;
    grid.$viewport.scrollTop(grid.rowMap[$scope.index] * grid.config.rowHeight);
};
```
But I can't seem to find a way to access $viewport . Do you guys know a way of doing this? Thanks a lot!

**Comment by imbalind** [comment]
I'm closing since we're not supporting 2.x anymore. Anyone willing to take on from here, feel free to fork.
