### ISSUE TITLE
Expandable Grid Rows in 2.x

### ISSUE THREAD

**Issue by gwin003** [angular-ui/ui-grid#2333]
I am looking to add expandable rows to the pre-3.0 repository of ng-grid. I have looked at the functionality in 3.0 but it looks like release is still a ways off. Is there anyone currently working on this?

What we would like to do is show some content under the row that would essentially be details about the item in the grid that the user expanded. Using aggregates or grouping would not accomplish what we are trying to do.

This is functionality that we will need, so if no one is working on it, I will also create a pull request once the functionality is complete.

**Comment by codyharrington** [comment]
@gwin003 if you want to maybe add what you've got to your github page, others can look at it, and possibly help make it more generic and get a pull request ready

**Comment by imbalind** [comment]
I'm closing this since we're not supporting 2.x anymore. Anyone wiiling to take on from here, feel free to fork.
