### ISSUE TITLE
Select All icon is not unchecked after calling clearSelectedRows.

### ISSUE THREAD

**Issue by sahil-kapoor** [angular-ui/ui-grid#2334]
Hi,

Steps:
1. Goto http://ui-grid.info/docs/#/tutorial/210_selection , first grid
2. Click on the selectAll Icon in the header not the button, It will select all the rows . Behaviour  is as expected.
3. Now click on clear All button. It will unselect all the rows. Problem is header check box icon does not get unselected. 

class 'ui-grid-all-selected' is not removed after calling clearSelectedRows().

**Comment by anandvihar** [comment]
Its fixed.

**Comment by PaulL1** [comment]
Excellent.
