### ISSUE TITLE
Class ui-grid-disable-selection when enableRowHeaderSelection: false

### ISSUE THREAD

**Issue by f2net** [angular-ui/ui-grid#2335]
I think that we shouldn't add the ui-grid-disable-selection on each cell when enableRowHeaderSelection is false, because this prevents setting the cursor:pointer for the direct row selection.

**Comment by PaulL1** [comment]
This is a useful request, but not really in the current roadmap.  We have far too many good ideas in the repository already, giving the impression that we have a project riven with defects.

Accordingly, I am leaving the enhancement tag on this, but closing it.  If someone would like this functionality, we'd welcome a pull request that adds it.
