### ISSUE TITLE
In ui-grid and not ng-grid, for downloading the csv file, no option give filename along with format niether the file is getting download with .csv as an extension

### ISSUE THREAD

**Issue by gunjanr17** [angular-ui/ui-grid#2336]
I am using ui-grid in my application. For exporting the data in csv format and then downloading why we have two clicks and why not on export button only the files get downloaded?

Also the file which is getting download has its name as "download". Can we change this to   download.csv in ui-grid.js for all ui-grid users or we already have any option for giving a specific file name with extension?

**Comment by hoonto** [comment]
I know this is closed, but to help others to get around the limitation, of client-side generated download filename and extension, I used this trick and has worked quite well: 

http://stackoverflow.com/questions/16376161/javascript-set-file-in-download

pulling the data out of the link provided and then decoding and passing it to the function described in the above link with the desired filename.

**Comment by PaulL1** [comment]
I think code similar to that example is in the latest unstable.
