### ISSUE TITLE
Move-Column feature is not working

### ISSUE THREAD

**Issue by AdityaJitu** [angular-ui/ui-grid#2354]
Hi,
In the demo application I am not able to move columns from one position to other.  I am trying this from the [this url](http://ui-grid.info/docs/#/tutorial/310_column_moving) from ui-grid website.

**Comment by jaskaye17** [comment]
Hey @jpuri,
 I am still having issues with being able to move columns in the Chrome browser even after your update. Firefox appears to be working fine as well as IE. I am simply testing with the following plnkr demo: http://plnkr.co/edit/GRDSonyeetWsTkpC76xn?p=preview

**Comment by jpuri** [comment]
I just checked your plunker in chrome and its working. Can you please check again.

**Comment by jaskaye17** [comment]
@jpuri Thanks for your response. I was also having a similar issue with column re-sizing re: #2550 . It appears for some reason that it is my computer or dev environment that is having an issue with both movableColumns and columnResizing features. From other's feedback it appears that movable columns is working.

**Comment by jpuri** [comment]
ok...what issue are you getting ? Are column moving/ resizing not happening or happening incorrectly. If you can explain, might be I can help.

**Comment by cmaxo** [comment]
When I try this is Firefox I see the shadow of the column header moving with the mouse drag so I can see where to place the column. When I try this in the latest chrome (39.0.2171.99 m) on windows pro 8.1 I don't see any shadow nor do I see the columns rearrange after releasing the drag. I checked in the console and there are no javascript errors. It simply doesn't respond. This is both on the plunker and the tutorial.

**Comment by jpuri** [comment]
Hi @cmaxo ,
Moving column does shows up in Chrome. But yes I agree moving column does not shows up in IE, thats a known issue, and I am working to fix that up.
