### ISSUE TITLE
scrolling with large amount of columns,columns disappear after sort  

### ISSUE THREAD

**Issue by gotenxds** [angular-ui/ui-grid#2357]
Hi,
In the demo application I move the scrollbar to last column "coll499" when i click on the column header 
to sort the data,the column disappaer
the grid before i clicked
![image](https://cloud.githubusercontent.com/assets/3519520/5452385/f2e7a2d6-8522-11e4-91d1-21d707178256.png)
after the click
![image](https://cloud.githubusercontent.com/assets/3519520/5452375/ba55ce5c-8522-11e4-82cd-9aea031208bb.png)
I am trying this from the  [this url!](http://ui-grid.info/docs/#/tutorial/191_horizontal_scrolling) from ui-grid website.

note:in my project its also disappear when try to edite the one of the last few column

**Comment by leo009394** [comment]
hi @c0bra 
I still have found the same issue when a cell is in edit. Have you fixed this issue or I missed something
Here is the <a href="http://plnkr.co/edit/QzLtW9rvgTkSVdazRlCJ?p=preview">plunker</a>

**Comment by stefan-leye** [comment]
I have the same issue

**Comment by Niranthari** [comment]
hi @c0bra  i still have the issue regarding the scroll bar disappears while i am trying to edit the cell could you pls help me.its very urgent.Thanks in advance
