### ISSUE TITLE
Trigger download of csv/pdf export file programatically.

### ISSUE THREAD

**Issue by ghost** [angular-ui/ui-grid#2391]
We should add a method to start downloading the export file after the csv/pdf file is constructed. Right now we're relying on a doom manipulation, but it would be great to add this kind of event to the API, or at least pass a callback function when the csv file is ready. This it's not a bug, more likely a feature request.

**Comment by knownasilya** [comment]
Which part is the one pertaining to Safari?@cssensei

**Comment by cssensei** [comment]
@knownasilya
The ```html5 A[download]``` part +
```
         // Workaround for Safari 5
         var eventObj = document.createEvent('MouseEvents');
         eventObj.initEvent('click', true, true);
         a.dispatchEvent(eventObj);
```
