### ISSUE TITLE
beforeSelectionChange - Called Twice upon 'Shift + click' 

### ISSUE THREAD

**Issue by kevinsoltis41** [angular-ui/ui-grid#2392]
From their docs "Note: when shift+ Selecting multiple items in the grid this will only get called once and the rowItem will be an array of items that are queued to be selected."

When I attempted to replicate the 'Shift + click' functionality; I get the function called once from the initial click, and then (2) once where rowItems is an array of selected items, and then once for the second click - rowItem is the item where I selected.

I've listed a plunker below where I attempt to show my question by counting number of times we enter the beforeSelectionChange function:
<a href="http://plnkr.co/edit/Jmdh1nXDIZ5t3Z8Mj6SP?p=preview">Plunker</a>

**Comment by swalters** [comment]
Closing old 2.x issue as all current development is on 3x. 

If someone really needs this fix for 2.x, my advice is to fork and fix it.  Sorry, I know it's not ideal, but it is the best we can offer with limited resources.
