### ISSUE TITLE
Setting default grid options globally

### ISSUE THREAD

**Issue by startprojekt** [angular-ui/ui-grid#2393]
Hey,
I think I encountered an error in the docs
http://ui-grid.info/docs/#/api/ui.grid.class:GridOptions in the Example section below. There is an example code on how to set some default options for all the grids in an app.
So after trying this code out the browser raises an error:

``` javascript
app.config(function($provide){
 $provide.decorator('GridOptions',function($delegate){
     return function(){
       var defaultOptions = new $delegate();
       defaultOptions.enableColumnMenus = false;
       return defaultOptions;
     };
   })
});
```

Plunker: http://plnkr.co/edit/RTqCusUVnNzo7uWAwqk1?p=preview

So I found a way to solve it:

``` javascript
app.config(function($provide){
 $provide.decorator('GridOptions',function($delegate){
   var gridOptions;
      gridOptions = angular.copy($delegate);
      gridOptions.initialize = function(options) {
        var initOptions;
        initOptions = $delegate.initialize(options);
        initOptions.enableColumnMenus = false;
        return initOptions;
      };
    return gridOptions;
 });
});
```

http://plnkr.co/edit/dGfyzPyidDNhOYSLGIBy?p=preview

It works by overriding and extending the initialize method on GridOptions factory with our default settings.

**Comment by ticlaudeberube** [comment]
How about overriding global configuration within controllers local grids?  This option is not possible as is.

**Comment by sgchris** [comment]
ticlaudeberube, any news about the overriding default settings issue?

**Comment by ticlaudeberube** [comment]
I believe that works already.

Claude Bérubé, PMP, PSM
claude.berube@gmail.com
514-529-0338

*http://cberube.azurewebsites.net/ <http://cberube.azurewebsites.net/>*

2016-03-21 8:24 GMT-04:00 Gregory C. <notifications@github.com>:
