### ISSUE TITLE
plunker for server side paging example is busted

### ISSUE THREAD

**Issue by DaveSysomos** [angular-ui/ui-grid#2395]
The plunker example on the github page: http://angular-ui.github.io/ng-grid/ is not fully functioning. (plunkr itself is here: http://plnkr.co/edit/50vJrs?p=preview)

If you manipulate the page size control (5,10,15), the grid does not react by re-rendering with a different number of records (i.e. always five and only five records).

Mysteriously, the on-page example (250,500,1000) works fine. The .js code is essentially identical, which means that the problem will be in the versioning of the dependencies - probably ng-grid plugin itself. 

This bug is dynamiting my development because I'm heavily into the paging controls right now.

**Comment by imbalind** [comment]
I'm closing this since we're not supporting 2.x anymore. Anyone wiiling to take on from here, feel free to fork.
