### ISSUE TITLE
How can I pass a variable to a dataCell template.

### ISSUE THREAD

**Issue by vuhailuyen1991** [angular-ui/ui-grid#2422]
Here is my code: 
$scope.itemsGridOptions.columnDefs = [
      { name: 'id' }
      { name: 'name' }
      { name: 'description' }
      { name: 'seller.email', displayName: 'Seller' }
      { name: 'actions', displayName: 'Actions', cellTemplate: 'app/Items/itemAction.html' }
    ]

In the last column how can i pass a variable into the template so i can utilize later?

**Comment by kcaron-cst** [comment]
Just curious what the status of external scopes is looking to be for RC19 seeing that  http://ui-grid.info/docs/#/tutorial/305_externalScopes is gone.

For quick reference, this is how it appears at RC18. https://raw.githubusercontent.com/angular-ui/ng-grid/v3.0.0-RC.18/misc/tutorial/305_externalScopes.ngdoc

**Comment by PaulL1** [comment]
it has been replaced by appScope, which is now the 305 tutorial.
