### ISSUE TITLE
[3.0] Blank spacing in grid when pagination happened

### ISSUE THREAD

**Issue by Bhimisetty** [angular-ui/ui-grid#2434]
I am able to see the unnecessary white space in the grid. But i have enough records to show. Following is the scenario.
I kept the default paging sizes as 25,50 and 75.
Once the records are bind, Make sure we have at least enough records to enable pagination. I have 500 records. Default page size set to 25. When i changed the size from 25 to either 50 or 75, i am seeing the blank space at the bottom of the grid. Once i perform mouse scroll it will be disappear.

**Comment by Bhimisetty** [comment]
I am using chrome V 39.0.2171.95. The issue is in paging 
http://ui-grid.info/docs/#/tutorial/215_paging
Just followup the procedure that i have mentioned in the issue. It reproduces yet.

**Comment by brianchance** [comment]
Hmmm. Not sure. I can only recreate the issue if I scroll first, then change the items per page. The page is getting changed and the rows rendered. It almost looks like it is auto scrolling to the end? @PaulL1 is there any code that remembers the scroll point?

**Comment by PaulL1** [comment]
Only in celNav I think, and I assume you're not using cellNav here?

**Comment by brianchance** [comment]
not at all.

**Comment by chenghsuan** [comment]
I have the same problem and try to resolve.  it is work for me to set `virtualizationThreshold`  as  `pagingPageSize` . [Plunker](http://plnkr.co/edit/kD5xuVuOGaWu0sXzLZ5v?p=preview)

**Comment by Bhimisetty** [comment]
I see. If it could be handled at the framework level instead of writhing the code at developer end, that would be very useful i think so. Anyhow thanks for the solution @chenghsuan.

**Comment by brianchance** [comment]
@chenghsuan - based on your plunker, this would be pretty easy to add. 

@PaulL1 - want one of us to add this?

**Comment by PaulL1** [comment]
I think we have a larger underlying issue, this may work, but I'm not sure it's the fix.  We have 2-3 different issues that all relate to some rows not showing on scroll.

**Comment by Bhimisetty** [comment]
Closing as this feature is removed from the site.
