### ISSUE TITLE
addRowHeaderColumn doesn't refresh rows when using templates

### ISSUE THREAD

**Issue by Pirfox** [angular-ui/ui-grid#2435]
So i wanted to use my own templates for a rowHeaderColumn, but it don't show right after the addRowHeaderColumn. It only show after an action that refresh the rows (moveColumn, filter ,...etc)

Here the plunker to see it : http://plnkr.co/edit/s6IrNGEsDbw0kOki5Y3Z
Sorting a column will do.

**Comment by kcaron-cst** [comment]
@PaulL1 Is that [latest plunkr](http://plnkr.co/edit/oAeWUdgNGGefqGpgCrAx?p=preview) still working? I only see the one header row, and commenting out the `$scope.gridApi.core.addRowHeaderColumn` line doesn't seem to make a difference. Was just poking around for an example of `addRowHeaderColumn`

In any case I'm really looking to have a a [`columnFooter`](http://ui-grid.info/docs/#/tutorial/105_footer) except one that displays near the top, right under the regular column headers, but the out of the box functionality might fly.
