### ISSUE TITLE
Getting Started Guide Issue

### ISSUE THREAD

**Issue by SalasSanchez** [angular-ui/ui-grid#2553]
I have realized that the very beginning of the getting started guide (here: http://angular-ui.github.io/ng-grid/) has two connected mistakes that make the process confusing. 

In step 2. of the guide, it says: "Add references to ngGrid's javascript and css files." This includes a hyperlink to https://github.com/angular-ui/ng-grid . But there are no javascript and css files in this repo that correspond to the files that appear in the demo code, "ng-grid.css" and "ng-grid-1.3.2.js", or to anything similar to that.

I found these files here: https://github.com/angular-ui/ng-grid/tree/2.x, instead. Note the different version.

Later, in step 3, it goes on: Where you declare your app module, add ui.grid: 
angular.module('myApp',['ui.grid']);  

But it only works if you add 'ngGrid' instead. (Maybe with version 1.3.2 what you needed was "ui.grid", but I don't know which way this should go)

**Comment by PaulL1** [comment]
I think you're stuck between 2.x and 3.0.  Most of our documentation now relates to 3.0, which means ui-grid and using the ui-grid files.  

Where exactly is the getting started guide that you are referring to?

**Comment by SalasSanchez** [comment]
Yes, I realize the version change.... 
I am using this guide here:
http://angular-ui.github.io/ng-grid/

**Comment by mportuga** [comment]
Closing as ng-grid is no longer being supported.
