### ISSUE TITLE
row selection checkbox broken when $compileProvider.debugInfoEnabled(false);

### ISSUE THREAD

**Issue by kether667** [angular-ui/ui-grid#2555]
reproduced here:
http://plnkr.co/edit/H90xVdHYOGpAIdW2IkWp?p=preview

debugInfoEnabled removes ng-scope class in row.js:35 you are expecting this class to be present

    ngRow.prototype.toggleSelected = function (event) {
        ...
	    //check and make sure its not the bubbling up of our checked 'click' event 
	    if (element.type === "checkbox" && element.parentElement.className !== "ngSelectionCell ng-scope") {
		    return true;
	    }
    ...
    };

this is invalid

**Comment by PaulL1** [comment]
I suspect we should check just for a partial match on `ngSelectionCell`.

**Comment by kether667** [comment]
yes, that would solve the problem.
