### ISSUE TITLE
Problem with older IE version

### ISSUE THREAD

**Issue by pilow** [angular-ui/ui-grid#256]
Hey,

I try using ng-grid for a web application.

Actually i had to face problems using AngularJS on IE7. I put the Shim and made everything compliant to it.

But when using ng-grid, the datas overflows the div that contains them.

The scrollbar is here and datas are binded to the div correctly, just that it doesnt fit the div :/

If you had a way to resolve this I would really appreciate it ! ^^

Rgds

**Comment by ctysingh** [comment]
check the prerequisite section which says that it support IE9+
