### ISSUE TITLE
Allow passing options to "cellFilter" column def property

### ISSUE THREAD

**Issue by cleon26** [angular-ui/ui-grid#2564]
Hello,

I'm working on formatting some data in the grid.  We have a series of custom filters which normally work using an options object.

{{ aValue | myCustomFilter : { opt1: true, opt2: 0, opt3: 'mike' } }}

This seems to work properly, if we set up the "cellTemplate" like this:
cellTemplate: '<div>{{ row.entity.aValue | myCustomFilter : { opt1: true, opt2: 0, opt3: "mike" } }}</div>'

If I use something like this, it seems to work properly:
cellFilter: 'myCustomFilter : "blah blah blah"'

However, is there a way to pass an object instead (this doens't work, just gives me null):
cellFilter: 'myCustomFilter : { opt1: true, opt2: 0, opt3: "mike" }'

Thanks in advance.

**Comment by PaulL1** [comment]
The cellFilter variable is set on the column as a whole, so if you wanted your cellFilter to vary per cell then it might be tricky.  Ultimately all the code does is a string substitution of whatever you pass in within your cellFilter variable into the cell template.  The relevant code is as follows.

default cellTemplate:
```
  <div class="ui-grid-cell-contents">{{COL_FIELD CUSTOM_FILTERS}}</div>
```

Code that replaces CUSTOM_FILTERS with whatever you pass in:
```
          col.cellTemplatePromise = gridUtil.getTemplate(col.providedCellTemplate);
          templateGetPromises.push(col.cellTemplatePromise
            .then(
              function (template) {
                col.cellTemplate = template.replace(uiGridConstants.CUSTOM_FILTERS, col.cellFilter ? "|" + col.cellFilter : "");
              },
```

So, I think the art is to fiddle around with the code to get the result you are looking for in terms of ending up with a cell that has `{{ row.entity.aValue | myCustomFilter : { opt1: true, opt2: 0, opt3: "mike" } }}`

I could have a play with a plunker, but don't have time today to make one.  But I'd suggest that setting cellFilter to `"myCustomFilter : { opt1: tru, opt2: 0, opt3: \"mike\" }"` should work given what the code is doing.

**Comment by cleon26** [comment]
I managed to get this working by getting it from the external scopes, rather than redefining the entire cellTemplate.  It might not be the prettiest, but it worked in my case.  I feel more comfortable defining the cellFilter than the cellTemplate for a simple scenario like this because I'd expect the default cellTemplate to change eventually (which would cause a lot of regression in my case)
 
  cellFilterArgs: { format: 'YYYY-MM-DD' },
  cellFilter: 'myDateFormatter : grid.appScope.columnFilters.startDate',
  //cellTemplate: '<div>{{ row.entity.startDate | myDateFormatter : { format: "YYYY-MM-DD" } }}</div>'

**Comment by c0bra** [comment]
I've updated the title to reflect the requested enhancement

**Comment by PaulL1** [comment]
This is a useful request, but not really in the current roadmap.  We have far too many good ideas in the repository already, giving the impression that we have a project riven with defects.

Accordingly, I am leaving the enhancement tag on this, but closing it.  If someone would like this functionality, we'd welcome a pull request that adds it.
