### ISSUE TITLE
Column divider double-click expands to fill entire table

### ISSUE THREAD

**Issue by Dev63** [angular-ui/ui-grid#2567]
I'm not sure when this started (before Dec 19), but double-clicking on a column divider now expands the column to become the entire visible width of the table.

This occurs when the table resides in a flex-grow div.  See very simple [plunker](http://plnkr.co/edit/kunuC4dHm4WBGF8wXwzv?p=preview).

**Comment by PaulL1** [comment]
OK, I can see that it behaves as described in your issue.  And if you remove the flex box then it resizes to the data visible in the column.

I'm not exactly sure how we'd go about fixing this, css is really not my thing.  But a brief google suggested that we can break out of the flex box by setting `position: absolute`, which probably isn't what you had in mind.  Alternatively, we have to make the resizing flex box aware, and I don't know how we'd do that.

**Comment by Dev63** [comment]
@PaulL1 Can you give me a pointer or a brief explanation of how this is implemented today, so I can think a bit about how you might solve the issue?  In a non-browser world, I would have implemented it calculating the width of the contents of each cell, then setting the width to the max.  But that's clearly not what you're doing.  I'm not in a position to examine the source and try to figure it all out, but if you give me a high-level overview, I'll give it some thought.  

I use flex-grow all over the place, for various reasons.  The most important of which is that I want the table to use as much space on the page as available, and not hard-code some value that will be frustrating to the user who has a big screen, and not frustrating to the user with a smaller screen who then ends up with 2 scrollbars (one for the table, and one for the page).  I think flexboxes are becoming increasing popular, so it would be good if ui-grid were compatible with this standard element.

**Comment by PaulL1** [comment]
Well, short answer is I don't know - I haven't spent any time on resize!!  But the code is in the resize feature, which isn't a lot of code: https://github.com/angular-ui/ng-grid/tree/master/src/features/resize-columns

I think the lines of code that are probably doing it are around line 475 of the js:
```
        // On doubleclick, resize to fit all rendered cells
        $elm.on('dblclick', function(event, args) {
          event.stopPropagation();
```

I'd guess if you whacked a breakpoint in there, and then looked at the difference in behaviour between flexbox and not flexbox, it would give you some hints.  And actually, now that I've looked this far, no doubt I could do the same.  But I'll leave it to you if you're keen to give it a go.

**Comment by Dev63** [comment]
@PaulL1 Here's something that may point you in the right direction: if you change `FakeElement` line 9344 in the current complete unstable js from

    angular.element(document.body).append(newElement);

to

    angular.element(document.body).after(newElement);

the temporary div that is being created to calculate the width of each cell will escape the flex-grow and calculate correctly.  However, I don't know what else calls that `FakeElement` routine, AND my "solution" has a nasty side effect of jiggering the table out of its bounds: you'd either need to prevent that or do a built-in table redraw.

Anyway, I hope this is enough to enable you to easily solve it in an elegant way. 

FYI, the actual calculation difference is at line 17394 (inside a call to `gridUtil.fakeElement`, a few lines into the dblclick function you referenced): `e.attr('style', 'float: left')`  Going into this line, `e[0].clientWidth` is very large; afterwards this number is set to the desired width in the standard case, but unchanged when in a flexbox.  There's a comment right above that says "Make the element float since it's a div and can expand to fill its container".  Somehow the flex container is automatically expanding the div to take up all remaining space ... hmm, that's what they're supposed to do, except that it's expanding horizontally when the direction for growth is specified as vertical.

**Comment by PaulL1** [comment]
This is a useful request, but not really in the current roadmap.  We have far too many good ideas in the repository already, giving the impression that we have a project riven with defects.

Accordingly, I am leaving the enhancement tag on this, but closing it.  If someone would like this functionality, we'd welcome a pull request that adds it.
