### ISSUE TITLE
allow ng.Aggregate to be expanded by default

### ISSUE THREAD

**Issue by clkao** [angular-ui/ui-grid#258]
if aggregation state is changed, all rows are collapsed.  there should be an option to allow expanded rows by default.

another nice to have feature is keeping the expanded/collapsed state when aggregation changed in non-disruptive ways - adding field to groups, and removing last filed from groups.

**Comment by aplocher** [comment]
What happened with this?  Did this functionality get removed?  I can't get it to work or find any recent information on it.
