### ISSUE TITLE
in-row aggregation

### ISSUE THREAD

**Issue by clkao** [angular-ui/ui-grid#259]
aggregation headers currently constitue their own rows at the moment.  it'd be nice to be able to show the aggregated field in-replace as a column - like rowspan.  we can still have the collapse/expand arrows in the leading column indicating aggregation.

for example: 
![lycalendar](https://f.cloud.github.com/assets/69736/276248/3390ca1e-90a7-11e2-89a4-1771037fccc8.png)

**Comment by trupti18** [comment]
Hi, Hasp the ROWSPAN feature added to ui-grid or not? I am not able to find any information about it.
