### ISSUE TITLE
error in removing divs containing ng Grid using remove() menthod in Angularjs

### ISSUE THREAD

**Issue by madasuk** [angular-ui/ui-grid#2615]
I have few tabs (Angularjs UI boot strap tabset) in my UI, when I click any tab, I remove the previously drawn charts and tables in a div, using remove() method in Angularjs. The divs contains c3 charts, ng grid tables, etc. It is working fine when it comes to remove the divs if they contain c3 charts, but if the div contains ng Grid tables I am getting error. The following is my code and error, How can I fix it?

Tabs Code :

<tabset>
    <tab heading="***" snap-toggle ng-click="openSnapDrawer();"> </tab>
    <tab ng-repeat="eachTab in d3DashboardTabs" heading="{{eachTab.tabName}}" select="createDashboradsforeachTab(dashboardData, eachTab)"> </tab>
    <tab heading="GoogleMap" select="drawGoogleMap(dashboardData)"> </tab>
</tabset>

Controller Code :

$scope.createDashboradsforeachTab = function(dashboardData, eachTab) {

    // Remove All the Previously Drawn Charts/Tables in chartsDiv
    var chartDivs = angular.element(document.querySelectorAll('.chartsDiv'))

    var cntChartDivs = chartDivs.length;

    if (cntChartDivs) {
        while (cntChartDivs > 0) {
            angular.element(chartDivs[cntChartDivs - 1]).remove();
            cntChartDivs = cntChartDivs - 1;
        }

    }

}

Error :

TypeError: Cannot read property 'off' of null
    at HTMLDivElement.<anonymous> (https://localhost/dashboard3/js/d3angular/ng-grid.debug.js:1008:31)
    at HTMLDivElement.jQuery.event.dispatch (https://localhost/js/jquery-1.9.1.js:3074:9)
    at HTMLDivElement.elemData.handle (https://localhost/js/jquery-1.9.1.js:2750:46)
    at Object.jQuery.event.trigger (https://localhost/js/jquery-1.9.1.js:2986:12)
    at jQuery.fn.extend.triggerHandler (https://localhost/js/jquery-1.9.1.js:3683:24)
    at removePatch [as remove] (https://localhost/dashboard3/js/d3angular/angular.js:2247:21)
    at Scope.$scope.createDashboradsforeachTab (https://localhost/dashboard3/js/controllers.js:699:54)
    at https://localhost/dashboard3/js/d3angular/angular.js:10694:21
    at Scope.isolateScope.(anonymous function) [as onSelect] (https://localhost/dashboard3/js/d3angular/angular.js:6565:26)
    at TabsetCtrl.ctrl.select (https://localhost/dashboard3/js/d3angular/ui-bootstrap-tpls-0.12.0.js:2993:17) 

My controllers.js:699 line is :

angular.element(chartDivs[cntChartDivs - 1]).remove();

Any suggestions please ...

**Comment by madasuk** [comment]
I don't even though the tab code is visible in edit mode it is not appearing in the question appearance. 
<tabset>
    <tab heading="***" snap-toggle ng-click="openSnapDrawer();"> </tab>
    <tab ng-repeat="eachTab in d3DashboardTabs" heading="{{eachTab.tabName}}" select="createDashboradsforeachTab(dashboardData, eachTab)"> </tab>
    <tab heading="GoogleMap" select="drawGoogleMap(dashboardData)"> </tab>
</tabset>

**Comment by PaulL1** [comment]
It's pretty hard to debug without a plunker.  Have you considered upgrading to 3.0 (ui-grid) instead?

**Comment by madasuk** [comment]
Sure PaulL1, I will try to replicate in a plunker and update here. Yes, I am considering to shift to ui-grid, but currently as ui-grid is in Beta version, my Manager is not favorable to use it, till the stable version is released.

**Comment by madasuk** [comment]
I don't know the reason but changing  angular.element(chartDivs[cntChartDivs - 1]).remove(); to  chartDivs[cntChartDivs - 1].remove(); has solved the problem. Do you see any problem with this solution,  if I use it to remove the previous grids? Otherwise for now it is working fine for me.

**Comment by PaulL1** [comment]
Presumably it means that whatever you have within chartDivs is already an angular element, although I thought that you could call angular.element() on something that was already an element and it would just leave it alone.  Maybe that isn't true.  I don't see any reason that wouldn't work, and it sounds like it is working.

**Comment by imbalind** [comment]
I'm closing since no news for almost a year.

**Comment by franbenz** [comment]
I think this issue is happening the second time you open the custom filter for age in [this tutorial](http://ui-grid.info/docs/#/tutorial/306_custom_filters).
[Here](https://github.com/angular-ui/ui-grid/blob/master/misc/tutorial/306_custom_filters.ngdoc#L147) is the call to angular.remove().
Apparently this does blocks you from using the custom filter repeatedly.

**Comment by franbenz** [comment]
I've replaced remove with detach, and it seems to avoid the error. But maybe this is not cleaning up each grid that was created previously.
