### ISSUE TITLE
add allowCellFocusCondition

### ISSUE THREAD

**Issue by smithscripts** [angular-ui/ui-grid#2623]
Would it be possible to add a "allowCellFocusCondition". This would solve my problem with toggling in and out of edit mode. I would then get row select behavior in non-edit mode and cell select behavior in edit mode. Like so:

allowCellFocus: function ($scope) {
            return $scope.col.grid.appScope.view.isEditing;
        },

**Comment by PaulL1** [comment]
This is probably a little more complex than it sounds, we'd be happy to accept a pull request to add this, but at the moment we're focused on fixing defects to get to a 3.0 release.

**Comment by PaulL1** [comment]
This is a useful request, but not really in the current roadmap.  We have far too many good ideas in the repository already, giving the impression that we have a project riven with defects.

Accordingly, I am leaving the enhancement tag on this, but closing it.  If someone would like this functionality, we'd welcome a pull request that adds it.
