### ISSUE TITLE
accessing DOM elements within grid

### ISSUE THREAD

**Issue by DaveC426913** [angular-ui/ui-grid#2651]
There's lots of tweaks I want to enhance ng-grid with, so I need access to the DOM after it's been rendered.

eg.
1] I want to change the markup of the ngHeaderButtonArrow to use a font-awesome icon.
2] I want to make the show/hide of the columns sticky, by trapping the checkbox changes in ShowColumnMenu. I'll store/restore the values as needed.

I've tried several methods for waiting until after the grid is rendered to go looking for DOM elements, but I haven;t found a method that's reliable.

**Comment by PaulL1** [comment]
I assume this relates to ng-grid and not ui-grid?  Have you considered upgrading to ui-grid?

**Comment by DaveC426913** [comment]
Upgrading will be put into the pipeline as a task, but not until it's gone from beta to gold.

**Comment by DaveC426913** [comment]
So is there any solution to this? All I'm looking for is a place in my code where I can reliably know that the grid and its sub elements have been rendered. Currently, when I go looking for it (console.log($('.gridStyle'));) I get back the ol' 'prevObject' element, which is an indication that the selector found no existing element.

**Comment by swalters** [comment]
Closing old 2.x issue as all current development is on 3x. 

If someone really needs this fix for 2.x, my advice is to fork and fix it.  Sorry, I know it's not ideal, but it is the best we can offer with limited resources.
