### ISSUE TITLE
cellNav in 3.0.0-rc.18: multiple selection with shift+click is not supported.

### ISSUE THREAD

**Issue by mkefd** [angular-ui/ui-grid#2653]
Hi Angular UI team,
Thank you for the great work!

After upgrade to 3.0.0-rc.18 we noticed then while using cellNav feature the multiple selection with ctrl+click works great, but shift+click is not supported. Unfortunately this lead to overriding the core shift+click behavior. Are there any chances to use cellNav feature to extend the core functionality by turning on arrow keys but inherit the click behavior from the core?

**Comment by mkefd** [comment]
@PaulL1 please, look at my comment in #2109 about `evt.stopPropagation()` for click event.

**Comment by ProSpartan** [comment]
Using 4.x and this is still an issue. Documentation on cellnav says that when using modifierKeysToMultiSelectCells, the ctrl and shift key should work. Ctrl works as expected, but shift does not. Shift will work on header selection with the checkboxes, but not individual cells.
