### ISSUE TITLE
Auto resize incorrect for multiple grids

### ISSUE THREAD

**Issue by KevReece** [angular-ui/ui-grid#2667]
We have multiple grids on the same page. 
With a single grid, when you double click a column border, the width auto fits the data.
But with multiple grids, it auto fits the largest data in any of the grids, with the same column index.

jsFiddle: http://jsfiddle.net/gqye2ygg/

**Comment by PaulL1** [comment]
Ah, I see you're 2.x, rather than 3.0.  I suspect this works in 3.0, would you consider upgrading?

**Comment by swalters** [comment]
Closing old 2.x issue as all current development is on 3x. 

If someone really needs this fix for 2.x, my advice is to fork and fix it.  Sorry, I know it's not ideal, but it is the best we can offer with limited resources.
