### ISSUE TITLE
How to add summary row in ng-grid

### ISSUE THREAD

**Issue by jagadiz61** [angular-ui/ui-grid#2703]

**Comment by PaulL1** [comment]
http://ui-grid.info/docs/#/tutorial/105_footer

**Comment by jagadiz61** [comment]
Thanks paul i need summary row for  while grouping

**Comment by PaulL1** [comment]
Is that with 2.x or 3.x?  3.x doesn't have grouping as yet.

**Comment by jagadiz61** [comment]
i using ng-grid 2.x and how to set  dynamic field name  in aggregate function .this is my project.
http://plnkr.co/edit/FQepdgFKtYqAVilvEwXZ?p=preview
In this example lots +=subrow.entity.lots; 
I need to change column in dynamically..
ex lots +=subrow.entity.selllots;  or lots +=subrow.entity.buylots;

**Comment by jagadiz61** [comment]
Or how to call column index in  aggregate function

**Comment by PaulL1** [comment]
You may want to consider upgrading to 3.0, which offers aggregation in the footers and grouping now.
