### ISSUE TITLE
Correct way to create additional functions for ng-click within ng-grid

### ISSUE THREAD

**Issue by giosakti** [angular-ui/ui-grid#271]
Is there a way to create additional functions to be used by button located within the ng-grid?

for example I have this grid over here which have row specific button:

![ng-grid](https://f.cloud.github.com/assets/524078/289707/6f3cb102-92c0-11e2-9f73-1f5b7d4c5769.jpg)

I created that using this piece of code:

``` javascript
      cellTemplate: '<a href="" class="btn btn-small btn-link" ng-click="editUser({{row.getProperty(\'id\')}})"><i class="icon-edit" /> Edit</a><a href="" class="btn btn-small btn-link"><i class="icon-trash" /> Delete</a>'
```

``` javascript
ng-click="editUser({{row.getProperty(\'id\')}})"
```

I don't know where to put this editUser function because when I do that within the controller that houses ng-grid, the function would not working.

**Comment by Sandip9021** [comment]
you can use  ng-click="grid.appScope.myfunction()"  instead of ng-click="myfunction()" , then it will work, 

Check the below link for more information :  
http://ui-grid.info/docs/#/tutorial/305_appScope
