### ISSUE TITLE
Remove shading effects from menu items

### ISSUE THREAD

**Issue by wendeldw** [angular-ui/ui-grid#2733]
Please consider removing the shading effects from the stylesheet. Although it is a matter of personal taste, nowadays looks are leading towards flat design.

**Comment by PaulL1** [comment]
It would probably be nice to make it switchable, although I'm not sure if maybe it's just easier for people to override the style in their css.

**Comment by PaulL1** [comment]
This is a useful request, but not really in the current roadmap.  We have far too many good ideas in the repository already, giving the impression that we have a project riven with defects.

Accordingly, I am leaving the enhancement tag on this, but closing it.  If someone would like this functionality, we'd welcome a pull request that adds it.
