### ISSUE TITLE
z-index issue in Grouping in ng-grid with jQueryUI

### ISSUE THREAD

**Issue by w3ashwin** [angular-ui/ui-grid#2737]
While grouping in ng-grid with jQuery UI, it automatically sets the z-index for all the elements in the DOM.

If you can view the example given in http://angular-ui.github.io/ng-grid/ under "Grouping Example - jQueryUI", Keeping aside the developer tools.

Initially all the elements in the DOM will have its own z index if its defined. Once you drag and drop the column for grouping in ng-grid and then peep into the DOM, you can see all the elements in the DOM has a z-index set starting from 1 till the end of the tree.

![ng-grid](https://cloud.githubusercontent.com/assets/6702850/6128372/2a01d214-b15b-11e4-90a6-a26fdfeb859f.PNG)

..and this is not reverting back even after ungrouping it.

**Comment by hstarorg** [comment]
I have same problem.

**Comment by swalters** [comment]
Closing old 2.x issue as all current development is on 3x. 

If someone really needs this fix for 2.x, my advice is to fork and fix it.  Sorry, I know it's not ideal, but it is the best we can offer with limited resources.
