### ISSUE TITLE
can i search two column  data  in single filter  text on ng-gird

### ISSUE THREAD

**Issue by jagadiz61** [angular-ui/ui-grid#2745]

**Comment by PaulL1** [comment]
If you mean ng-grid, then yes, you put the column names in the filter box - something like 'gender: male age:30'

If you mean ui-grid, then not in a single filter text, you put the filter against each individual column. So you'd put 'male' in the gender column filter, and 30 in the age column filter.

**Comment by jagadiz61** [comment]
thanks paul.. can i filter age is less than 20  or greater than 20....?
