### ISSUE TITLE
Migrating to 3.0

### ISSUE THREAD

**Issue by dovk** [angular-ui/ui-grid#2764]
Can you please add more documentation on how to migrate usage such as 
     ng-cell
     ng-repeat="col in renderedColumns"
     ng-click="$root.getData(row.entity.rowNumber,col.field);"
or CSS elements that were used such as 
     ng-style="{ 'cursor': row.cursor }"
     ng-class="col.colIndex()"
     class="ngCell {{col.cellClass}}"
     class="ngVerticalBar"
     ng-style="{height: rowHeight}"
     ng-class="{ ngVerticalBarVisible: !$last }"

**Comment by PaulL1** [comment]
We'd be happy to accept a pull request for this update, at the moment we're quite focused on fixing bugs rather than writing upgrade documentation.

**Comment by dovk** [comment]
Thanks a lot.
Unfortunately I don't have the in-depth knowledge and background but I have been able to make something nice.
If it's possible for you to do private consulting regarding the migration I would be happy to pay for  your services.
I do want to move on to ui-grid because of both functionality (for example import/export to CSV) as well as the UI design, and dropping the jQuery dependency.
So if this is possible, please let me know.
I've enclosed what I've done, it's not that much so I hope you can help.
Thanks again, Dov
[cid:image001.png@01D048B1.6291FBD0]

**Comment by PaulL1** [comment]
This is a useful request, but not really in the current roadmap.  We have far too many good ideas in the repository already, giving the impression that we have a project riven with defects.

Accordingly, I am leaving the enhancement tag on this, but closing it.  If someone would like this functionality, we'd welcome a pull request that adds it.
