### ISSUE TITLE
Cell template & Sorting in UI Grid

### ISSUE THREAD

**Issue by gunjanr17** [angular-ui/ui-grid#2798]
I have a cell template applied on a column. Can I sort the data of this column based on multiple criteria who's value is being displayed on this cell.

For eg: I have a cell template which displays the issue priority and issue creation date.
Can I apply sorting on this column based on high priority and older date.

**Comment by c0bra** [comment]
I believe there's been a request for this before. What we probably need to do is bind the sortingAlgorithm call to an object that provides both the row objects for the sort.

**Comment by PaulL1** [comment]
This is a useful request, but not really in the current roadmap.  We have far too many good ideas in the repository already, giving the impression that we have a project riven with defects.

Accordingly, I am leaving the enhancement tag on this, but closing it.  If someone would like this functionality, we'd welcome a pull request that adds it.
