### ISSUE TITLE
Edit On Focus Cell Selection Example broken

### ISSUE THREAD

**Issue by skeenan** [angular-ui/ui-grid#284]
The 

> Edit On Focus Cell Selection Example 

on your examples page doesn't work.

http://angular-ui.github.com/ng-grid/

Tested on OSX Chrome & Firefox

Cheers

**Comment by sumeetsonawane11** [comment]
Single click not working on dropdown in cell template instead I need to double-click to edit the dropdown?
How can I always need a single click for my dropdown
