### ISSUE TITLE
issue in using ng grid in custom directive

### ISSUE THREAD

**Issue by madasuk** [angular-ui/ui-grid#2861]
ng grid is not displaying the data when I am trying to use in my custom directive. Please find my plunker at http://plnkr.co/edit/Ofa9YhfHQJg92TOjBZQZ?p=preview.

**Comment by madasuk** [comment]
Hi c0bra, I am not clear about the status of this issue (added to this 2.x.next milestone). Is there any mistake I am doing or ng grid can't be used the way I am trying to use?

**Comment by PaulL1** [comment]
In general 2.x doesn't have a lot of support, none of the original 2.x team remain as part of the project, the newer members are all more familiar with 3.0.  It probably indicates that we're waiting for someone who knows something about 2.x to provide some advice - and that what you're doing doesn't have a simple answer.  You could consider upgrading to 3.0, which tends to have better support.

**Comment by imbalind** [comment]
I'm closing this since we're not supporting 2.x anymore. Anyone wiiling to take on from here, feel free to fork.
