### ISSUE TITLE
v2 / v3 performance comparison

### ISSUE THREAD

**Issue by metaman** [angular-ui/ui-grid#2880]
Hi guys,

Great work on the major re-write!  Just wondering if you have any stats on performance differences between v2 and v3? It would be much easier to persuade people to make the switch if there were some expected perf. improvements (which i am sure there are).  Apologies if you have already posted details but I haven't come across any yet.

**Comment by c0bra** [comment]
I'm not sure if there's measurable statistics that we can use. Maybe we can try some side-by-side gifs of user actions to show the differences.

And we probably wouldn't publish anything like that until 3.0 is released.

**Comment by PaulL1** [comment]
I think one measure we can point to is the performance of filtering very large datasets: #2574

**Comment by PaulL1** [comment]
This is a useful request, but not really in the current roadmap.  We have far too many good ideas in the repository already, giving the impression that we have a project riven with defects.

Accordingly, I am leaving the enhancement tag on this, but closing it.  If someone would like this functionality, we'd welcome a pull request that adds it.
