### ISSUE TITLE
Option to disable multi-column sorting

### ISSUE THREAD

**Issue by smehrbrodt** [angular-ui/ui-grid#2913]
Would be good to have an option to disable multi-column sorting.
That means, when you sort one column, all others should be reset to no sorting (currently this requires manual user interaction).

**Comment by PaulL1** [comment]
I thought that's what it does by default, and you have to shift+click to get multi-column.  Or do you mean when using the menus?

**Comment by smehrbrodt** [comment]
I was using the menus. Clicking the column headers doesn't do anything.

**Comment by PaulL1** [comment]
In the tutorial?  http://ui-grid.info/docs/#/tutorial/102_sorting?  It works for me - what browser are you using?

**Comment by smehrbrodt** [comment]
Oh, it indeed works in Chromium (v40), but not in Firefox (v38) (both on Linux).

**Comment by PaulL1** [comment]
It might perhaps work a bit better now - I did some work on the handlers, and if you had some touch handlers creeping in it previously could have been flakey.

**Comment by AdamDiment** [comment]
Using Chrome 43.0.2357.124, external sorting via the menus adds to the sortCols array - I would also like an option to disable multi sort. Thansk

**Comment by don-p** [comment]
I would also like an option to disable multi sort.

I am not referring to resetting the sort state by clicking a column header.  I am specifically requesting the ability to disable multi-column sorting, so that there is one and only one sort column, and the sortPriority will not be displayed in the header.

**Comment by mborca** [comment]
Yes please, I also need this feature.

**Comment by pdemanget** [comment]
+1

**Comment by jaredwilli** [comment]
+1

**Comment by abigail1000** [comment]
+1

**Comment by radu-jakab** [comment]
+1

**Comment by Sarah4VT** [comment]
+1

**Comment by spaceribs** [comment]
+1

**Comment by JLLeitschuh** [comment]
Instead of leaving +1 please add votes using the github ZenHub.io plugin.
If you really want to see this feature please claim it. Come talk to us on gitter about how you want to implement it and then open a PR.

**Comment by PareshSolankiMI** [comment]
style.
	.ui-grid-sort-priority-number{
		font-size: 0 !important;
	}

**Comment by spaceribs** [comment]
@PareshSolankiMI while that hides the functionality, it doesn't disable the ability to shift click multiple columns

**Comment by lauwrentius** [comment]
this one works for me.

`gridApi.core.on.sortChanged( $scope, function(grid, sortColumns){
	while(sortColumns.length >1){
		sortColumns[0].unsort();
		sortColumns.shift();
	}
});`

**Comment by miguelchico** [comment]
Agree, please include an option to disable and avoid manual interaction.

**Comment by ATrogolo** [comment]
Any news?

**Comment by bee0060** [comment]
Now we can use `suppressMultiSort` to disable it.
