### ISSUE TITLE
ignoring certain values while sorting

### ISSUE THREAD

**Issue by kitensei** [angular-ui/ui-grid#2917]
I don't know if this is possible (nor logical) but I have the following case:

A product list containing 100 products, 50 of them are ranked from 1 to 50 (representing the most ordered products in the last 20 days), the 50 remaining products don't have this value (NULL).

When sorting this RANK column, I would like (ideally) to sort 1 -> 50 ASC (so non ranked are in the bottom) but when sorting DESC, I would also like the non ranked to be at the bottom.

Is there a way of achieving this ? I have thought of manually editing data while sorting to change their rank from something like -1 to 100000 to be sure they'll be sorted correctly, but when displaying more than 1500 items I think this will cause useless overhead.

**Comment by PaulL1** [comment]
I think I recall that custom sort functions give you control over the null behaviour if you don't call `sortHandleNulls`.

**Comment by kitensei** [comment]
Sorry for late reply, I am trying that

**Comment by PaulL1** [comment]
I don't think there is, unfortunately.

**Comment by kitensei** [comment]
Ok nvm, I'll just use it as is for now, hope to see this in a future release :)

**Comment by Rhathe** [comment]
#4455 the direction is passed as a parameter to sortingAlgorithms
