### ISSUE TITLE
Pre Load Values in grid

### ISSUE THREAD

**Issue by aksharak** [angular-ui/ui-grid#2928]
Hi,
I have 2 grids where on click of the row in Grid 1 the values of the clicked row are populated as columns in grid 2 as seen in the plunker: http://plnkr.co/edit/eehYJIB5A3eiuVutbl1c?p=preview
Once you click the values are getting populated. But before i click the grid is empty. How to have the field 1 value already populated before the click and on click of the row, respective field 2 values of Grid 1 to be populated in Grid 2. 

Thanks.

**Comment by PaulL1** [comment]
In ui-grid you do this with onRegisterApi and then the selection API.  I'm not sure how to do it in 2.x.
