### ISSUE TITLE
afterSelectionChange does not use $apply if the change is triggered by keyboard (2.0.11)

### ISSUE THREAD

**Issue by tjamin** [angular-ui/ui-grid#2957]
As the title of this issue describes the afterSelectionChange is not fired within an $apply call if the row selection change is triggered by the keyboard. If the selection change is triggered by clicking another row afterSelectionChange is fired within an $apply call.

**Comment by imbalind** [comment]
I'm closing this since we're not supporting 2.x anymore. Anyone wiiling to take on from here, feel free to fork.
