### ISSUE TITLE
Change value of a cell in 1 Grid reflect in the other.

### ISSUE THREAD

**Issue by aksharak** [angular-ui/ui-grid#2960]
Hi,
I have an ng-Grid where on click of a row the entire data is brought to another ng-grid. now on change of value in the grid is not reflecting the same in the grid 2. Any idea how to achieve that?

For ex: http://plnkr.co/edit/D28wlkPqDsr7b0Ov8HXJ?p=preview

In the plunker on click of a row on the top grid the the row data is displayed as columns. Now if we edit the name in the top grid and click outside the grid the grid 2 should be updated with the same value. how to achieve that?

**Comment by PaulL1** [comment]
That's a very unusual design.  Usually if you're doing list-detail in that way, you'd make the second grid editable not the first.

If I click on the first row and edit it, then click on the second row, and back to the first row, then the second grid is correctly updated with the desired value.

You appear to have broken the edit feature a bit though - the editors aren't going away when I click on different cells.

**Comment by aksharak** [comment]
Ok.. i understand your point. here is the updated Plunker: http://plnkr.co/edit/eehYJIB5A3eiuVutbl1c?p=preview. How to make the right column value editable where the left column value is city?

**Comment by swalters** [comment]
closing old issue
