### ISSUE TITLE
Autoprefixer?

### ISSUE THREAD

**Issue by DrewML** [angular-ui/ui-grid#2971]
Howdy,

I wanted to check if the Angular-UI team would be interested in a PR to implement Autoprefixer?

It looks like, at the time of this writing, all the less files within the repository have vendor prefixes hard-coded in. This is not ideal, as those vendor-prefixes will become stale code as browsers begin dropping the prefixed versions of the CSS features you are utilizing, and you drop support for those older browsers.

As a small added bonus, it will also cause a very small reduction in the size of this repository.

I would love to submit my first contribution to the project, and thought this could be a good start. Just wanted to make sure y'all would be interested in this before dedicating the time.

**Comment by c0bra** [comment]
That sounds pretty good to me. Currently we're using mixins from LESS elements: http://lesselements.com

It would be nice to retain any of the mixins that do more than vendor prefixing. Just looking at them I'm not sure if there are any, but there may be...

**Comment by DrewML** [comment]
No problem -- I'll make sure not to remove any mixins that provide functionality besides prefixing.

A question on that front, however -- are y'all manually copying down mixins from *lesselements.com*, or are you pulling them down from a package manager? Basically what I'm trying to get at is, would it be acceptable to remove vendor prefixing from the mixins from *lesselements.com* in this project?

**Comment by c0bra** [comment]
@DrewML sorry for not responding for so long; I just came back across this issue.

I manually copied the mixins down, so whatever you want to do for to automate prefixes is fine with me.
