### ISSUE TITLE
Update Grid value based on update of another grid & cell color change in NG-Grid

### ISSUE THREAD

**Issue by aksharak** [angular-ui/ui-grid#2990]
Hi,
I have a 2 Grid where on click of a row in Grid 1, the values in the grid are transferred to another grid. Now in Grid 2, there is a textbox where i can edit the values. Once i editing them the textbox background becomes red. Now on click of save how do i update the same value in grid 1 ? And also without click of save, if i click on another row in Grid 1, The red color is retained in the textbox. Since this is a new value and value has not changed it should be white. How to achieve this? Here is the plunker for the above problem: http://embed.plnkr.co/WUg173JQYXceTrsTu7kD/preview

Thanks,

**Comment by imbalind** [comment]
I'm closing this since we're not supporting 2.x anymore. Anyone wiiling to take on from here, feel free to fork.
