### ISSUE TITLE
Angular-ui pinning columns in subgrid as per parent dynamically

### ISSUE THREAD

**Issue by njosh** [angular-ui/ui-grid#3019]
in my case if a column is moved or pinned same changes should reflect in sub grid also.I have written a function for this which changes the properties in subgrid as per parent but not able to find any event which occurs on pinning of columns on parent grid so that i can call my function.currently i am using this event

$scope.gridApi.core.on.rowsRendered($scope,$scope.pinSubGridColumns)

its working but is fired too many times and the view is getting distorted.Also if i pin columns in parent grid then sub grid columns starts after these columns but i want subgrid columns aligned as per parent so if i have id column in parent grid then subgrid id column should be below it even if it is pinned.how can i achieve this?

here is the demo on plunker : http://plnkr.co/edit/AKUFxTaJ2c3fLvl7AZin?p=preview

**Comment by PaulL1** [comment]
It looks to me like your use case is one that would be better handled by grouping than by expandable, as your subgrids are using the same columns and layout as the core grid.  Grouping is also more performant and better supported than expandable.

**Comment by njosh** [comment]
As my main rows will also have data in them.I don't think i can achieve this through grouping.

**Comment by PaulL1** [comment]
@njosh: you may want to take a look at the new treeView feature.  It may meet your use case.

**Comment by njosh** [comment]
Thanks for your suggestion.We needed sorting also so tree view will not be useful in that case.now we have removed subgrid and are adding sub rows dynamically in main grid on expand.

**Comment by PaulL1** [comment]
This is a useful request, but not really in the current roadmap.  We have far too many good ideas in the repository already, giving the impression that we have a project riven with defects.

Accordingly, I am leaving the enhancement tag on this, but closing it.  If someone would like this functionality, we'd welcome a pull request that adds it.
