### ISSUE TITLE
Pinned column doesn't align on scroll with the rest of the grid

### ISSUE THREAD

**Issue by roedit** [angular-ui/ui-grid#3022]
Scrolling to the bottom of the grid there's a difference between the pinned column and the rest of the grid . 
Here is the plunker for it : 
http://plnkr.co/edit/s36dFIFuqwsOHG1NnhVl?p=preview
And also a print for it: 
![gridissue](https://cloud.githubusercontent.com/assets/8833239/6663226/1b6f4a06-cbcd-11e4-8857-16098d1997d9.jpg)

**Comment by PaulL1** [comment]
@swalters: are you looking at this with your scrolling changes?  Assigning to you just in case you are.  :-)

**Comment by PaulL1** [comment]
This only happens where the body has a scrollbar, the pinned container doesn't, and the scroll event is over the pinned container.  The pinned container goes all the way to it's bottom, the body doesn't quite reach the bottom.  Scrolling over the body instead will get you all the way to the bottom.
