### ISSUE TITLE
ng-grid keyboard navigation for groups

### ISSUE THREAD

**Issue by yogeshp** [angular-ui/ui-grid#3029]
Hi,
In one of our functionality we have grouping inside ng-grid. If all groups are expanded and focus is on ngViewport then we can navigate through all rows using UP and DOWN key. However if groups are collapsed then we are not able to get idea where is selection.Also found that we are not able to expand and collapse rows using keyboard. Is there any work around we have so that we navigate groups and expand-collapse using keyboard.

**Comment by PaulL1** [comment]
Do you mean ng-grid or ui-grid?

**Comment by yogeshp** [comment]
I am using ng-grid 2.0.11

**Comment by PaulL1** [comment]
OK, there's not much support at the moment for 2.x, attention has very much shifted to 3.0.  Having said that, the grouping is very new in 3.0 and I doubt that keyboard actions are working there either.
