### ISSUE TITLE
Column Menu Items Order

### ISSUE THREAD

**Issue by roedit** [angular-ui/ui-grid#3030]
Hi,
As an enhancement could there be an order property for the column menu so that we could set the order of the menu items?
Thanks.

**Comment by PaulL1** [comment]
Yeah, I actually need this myself, so I'll probably end up doing it.

**Comment by PaulL1** [comment]
This is a useful request, but not really in the current roadmap.  We have far too many good ideas in the repository already, giving the impression that we have a project riven with defects.

Accordingly, I am leaving the enhancement tag on this, but closing it.  If someone would like this functionality, we'd welcome a pull request that adds it.
