### ISSUE TITLE
Web Workers

### ISSUE THREAD

**Issue by kpau** [angular-ui/ui-grid#3057]
Hello,

It would be nice to implement Web Workers into the grid, which will handle the data grouping/sorting/etc.
This will increase the performance, and the application won't freeze when the grid is manipulating large amount of data.
Maybe add config option to choose whether to use web workers or not.

My idea is to pass the data to a single web worker, which will do all data manipulations (sort, group, filter...). The main thread will pass commands via postMessage().
The main thread will have access only to renderedRows[], and the worker - to all rows.
Using postMessage() the threads will communicate: the main thread will request portion of the data which will be rendered, and the worker will give it.

Best regards,
Kristiyan

**Comment by PaulL1** [comment]
That's an interesting idea.  I don't think it's a priority in our current work program, but we probably wouldn't refuse a well constructed PR that added this as an option.

**Comment by PaulL1** [comment]
I don't believe this is on our current workplan, and unlikely to surface in 3.0.  I'm marking for consideration in 4.0, even then I'm not sure it's going to work well even just for sorting/filtering - we can't render until the sort/filter finishes, so whilst we'd get browser responsiveness back, we'd not necessarily make the user a lot happier.

**Comment by PaulL1** [comment]
This is a useful request, but not really in the current roadmap.  We have far too many good ideas in the repository already, giving the impression that we have a project riven with defects.

Accordingly, I am leaving the enhancement tag on this, but closing it.  If someone would like this functionality, we'd welcome a pull request that adds it.
