### ISSUE TITLE
Cell navigation keys setup

### ISSUE THREAD

**Issue by roedit** [angular-ui/ui-grid#3067]
Hi,
This is a feature request.
Could you please allow the user to set the own keys setup for the grid navigation.
Thanks.

**Comment by PaulL1** [comment]
I'll mark this as an enhancement, but I should warn you that this isn't likely to be high on the work program - I think S508 compliance would be much higher, and we're not doing that at the moment either.

**Comment by PaulL1** [comment]
This is a useful request, but not really in the current roadmap.  We have far too many good ideas in the repository already, giving the impression that we have a project riven with defects.

Accordingly, I am leaving the enhancement tag on this, but closing it.  If someone would like this functionality, we'd welcome a pull request that adds it.
