### ISSUE TITLE
Column Header Separator Missing

### ISSUE THREAD

**Issue by NavneetJoshi** [angular-ui/ui-grid#3068]
In my grid column header separator is missing for the last pinned column.I am facing this issue when i set both  these properties  for a column

enableColumnResizing: false,
pinnedLeft: true

so currently i have to enable resizing for that column to resolve this.Please look into this.

**Comment by PaulL1** [comment]
Any chance of a plunker demonstrating this?

**Comment by NavneetJoshi** [comment]
plunker : http://plnkr.co/edit/kEkiFBS4MpXaUpXh1Wut?p=preview

I think the problem is when i am defining this grid inside table in my project its working fine if i enable column resize but in the plunker its behaving very weirdly even if i remove pinning.

**Comment by NavneetJoshi** [comment]
plunker : http://plnkr.co/edit/kEkiFBS4MpXaUpXh1Wut?p=preview

I think the problem is when i am defining this grid inside table in my project its working fine if i enable column resize but in the plunker its behaving very weirdly even if i remove pinning.

**Comment by PaulL1** [comment]
OK, I've stripped the plunker down to the minimum to demonstrate the problem: http://plnkr.co/edit/e4Kaw1c2WnxWhEY26yqq?p=preview

Basically it's the embedding within the table that does it - as soon as I take it out of the table it works.

**Comment by PaulL1** [comment]
This is a useful request, but not really in the current roadmap.  We have far too many good ideas in the repository already, giving the impression that we have a project riven with defects.

Accordingly, I am leaving the enhancement tag on this, but closing it.  If someone would like this functionality, we'd welcome a pull request that adds it.
