### ISSUE TITLE
Toggle table cells to be editable

### ISSUE THREAD

**Issue by chamviptela** [angular-ui/ui-grid#3096]
I've created a table that is non-editable. When toggling an 'Edit' button, I want to change all the cells to editable. When the user clicks 'Edit', I've tried changing the column definition to enableCellEdit and called grid.refresh(), grid.queueGridRefresh(), notifyDataChange('column'),  and changed the grid.columns.colDef & called columnRefreshCallback(grid) but none have worked for me. Could you tell me what i'm missing and/or doing wrong? 

thanks.

**Comment by PaulL1** [comment]
Looking at the code for the edit feature, the enableCellEdit property is evaluated only once, at initial cell render.  It therefore will be quite difficult to toggle between editable and non-editable.  You might be able to achieve it by destroying then re-rendering the enclosing div, which should re-render the entire grid.  That's probably not ideal though.

**Comment by chamviptela** [comment]
Thanks for the prompt response Paul. Indeed, the workaround is not ideal. I will plop ui-grid in a directive and destroy and compile a ui-grid on demand sort of. I'll check out the performance and see if that can satisfy my use case. thanks again.

**Comment by uguryilmaz** [comment]
check out this plunker

http://plnkr.co/edit/md9AOA64Zn67KqhNmhZT?p=preview
