### ISSUE TITLE
Disable either Pin Left and Pin Right functionality on ui-grid

### ISSUE THREAD

**Issue by Ni3u** [angular-ui/ui-grid#3110]
Is it possible to disable either Pin Left or Pin Right functionality of ui-grid?

**Comment by PaulL1** [comment]
Currently you can disable all pinning, or enable all pinning.  But not individually the pin left or pin right.

**Comment by PaulL1** [comment]
This is a useful request, but not really in the current roadmap.  We have far too many good ideas in the repository already, giving the impression that we have a project riven with defects.

Accordingly, I am leaving the enhancement tag on this, but closing it.  If someone would like this functionality, we'd welcome a pull request that adds it.
