### ISSUE TITLE
Feature request: Passing custom aggregationTypes

### ISSUE THREAD

**Issue by santialbo** [angular-ui/ui-grid#3134]
*This can be done by using custom templates and having some outer logic but it would be very nice it could be done within the definiton of the grid.*

It would be nice if it was possible to pass custom aggregationType functions. The one that I need is a weighted average, weighted on the value in another field. I'm thinking of an interface like the following:
 
```javascript
columnDefs = [
  {
    field: 'value',
    aggregationType: {
      label: 'wavg',
      fields: ['value', 'count'],
      aggregation: function(values, counts) {
        // return values_i*counts_i/sum(counts);
      }
    }
]
```

Any thoughts?

**Comment by PaulL1** [comment]
My recollection of the aggregation logic is that this would be possible, as it basically calls a function passing in the array of visible rows.  But someone would need to take the time to make a PR that did it.

**Comment by arjshiv** [comment]
@PaulL1 Do you mind if I take the time to do this ? I love your project and would really like to contribute

**Comment by PaulL1** [comment]
Absolutely, go ahead.

**Comment by arjshiv** [comment]
Awesome. Could you assign me to this ? I'm starting to go through the source code and should have something for you this week/weekend (unless you have a tighter timeline)

**Comment by PaulL1** [comment]
We can't assign somebody who doesn't have direct contribution ability - but rest assured nobody else is likely to jump on this (it's been unassigned since March last year).  Let me know if you need any advice.

**Comment by arjshiv** [comment]
No worries. Thanks for offering to help - I'm sure I'm going to need it :)

**Comment by arjshiv** [comment]
So should I start with the code is aggregateColumn in grouping.js to get a feel for how aggregation works ? I assume the interface itself is within the ColumnDef code, so perhaps the best way is for me to start playing with a toy grid in a debugger to see how the control flows.

**Comment by PaulL1** [comment]
Yes, that's a good idea.

For grouping, the basic flow is that every time something happens in the grid (rows change, column defs change, someone expands or collapses a group etc) we run a render cycle (can't remember the exact name of that, but somewhere in the doco or the readmes I wrote something about render cycles).

As part of that, it runs a rows processor.  That rows processor sorts the data by the grouped column, then runs through all the rows calculating all the header rows and applying the finalisation logic.

So actually, the bulk of this code is in the grouping.js, and the interface into the core is quite lightweight - mostly the rows processor and creating the header rows.  The rowsProcessor framework is quite elegant and pluggable.

The logic for aggregating is pretty standard row by row processing, keeping a running total, and writing it out whenever it finds a change in the group value.  When it writes it out it applies the finaliser.  My recollection is that I ended up storing the raw values into the cell, and then there's a filter that applies the formatting function, but I may have done it as a one time process as part of writing out the value.  Either way, it's tied into that rowsProcessor logic.

**Comment by arjshiv** [comment]
Hold on - this seems to be already supported in https://github.com/angular-ui/ui-grid/blob/master/src/features/tree-base/js/tree-base.js lines 554 - 624 . Am I missing something ?

```js
/**
         *  @ngdoc object
         *  @name customTreeAggregationFn
         *  @propertyOf  ui.grid.treeBase.api:ColumnDef
         *  @description A custom function that aggregates rows into some form of
         *  total.  Aggregations run row-by-row, the function needs to be capable of
         *  creating a running total.
         *
         *  The function will be provided the aggregation item (in which you can store running
         *  totals), the row value that is to be aggregated, and that same row value converted to
         *  a number (most aggregations work on numbers)
         *  @example
         *  <pre>
         *    customTreeAggregationFn = function ( aggregation, fieldValue, numValue, row ){
         *      // calculates the average of the squares of the values
         *      if ( typeof(aggregation.count) === 'undefined' ){
         *        aggregation.count = 0;
         *      }
         *      aggregation.count++;
         *
         *      if ( !isNaN(numValue) ){
         *        if ( typeof(aggregation.total) === 'undefined' ){
         *          aggregation.total = 0;
         *        }
         *        aggregation.total = aggregation.total + numValue * numValue;
         *      }
         *
         *      aggregation.value = aggregation.total / aggregation.count;
         *    }
         *  </pre>
         *  <br/>Defaults to undefined. May be overwritten by treeAggregationType, the two options should not be used together.
         */
        if ( typeof(colDef.customTreeAggregationFn) !== 'undefined' ){
          col.treeAggregationFn = colDef.customTreeAggregationFn;
        }

        /**
         *  @ngdoc object
         *  @name treeAggregationType
         *  @propertyOf  ui.grid.treeBase.api:ColumnDef
         *  @description Use one of the native or grid-level aggregation methods for calculating aggregations on this column.
         *  Native method are in the constants file and include: SUM, COUNT, MIN, MAX, AVG. This may also be the property the
         *  name of an aggregation function defined with {@link ui.grid.treeBase.api:GridOptions treeCustomAggregations}.
         *
         *  <pre>
         *      treeAggregationType = uiGridTreeBaseConstants.aggregation.SUM,
         *    }
         *  </pre>
         *
         *  If you are using aggregations you should either:
         *
         *   - also use grouping, in which case the aggregations are displayed in the group header, OR
         *   - use treeView, in which case you can set `treeAggregationUpdateEntity: true` in the colDef, and
         *     treeBase will store the aggregation information in the entity, or you can set `treeAggregationUpdateEntity: false`
         *     in the colDef, and you need to manual retrieve the calculated aggregations from the row.treeNode.aggregations
         *
         *  <br/>Takes precendence over a treeAggregationFn, the two options should not be used together.
         *  <br/>Defaults to undefined.
         */
        if ( typeof(colDef.treeAggregationType) !== 'undefined' ){
          col.treeAggregation = { type: colDef.treeAggregationType };
          if ( typeof(gridOptions.treeCustomAggregations[colDef.treeAggregationType]) !== 'undefined' ){
            col.treeAggregationFn = gridOptions.treeCustomAggregations[colDef.treeAggregationType].aggregationFn;
            col.treeAggregationFinalizerFn = gridOptions.treeCustomAggregations[colDef.treeAggregationType].finalizerFn;
            col.treeAggregation.label = gridOptions.treeCustomAggregations[colDef.treeAggregationType].label;
          } else if ( typeof(service.nativeAggregations()[colDef.treeAggregationType]) !== 'undefined' ){
            col.treeAggregationFn = service.nativeAggregations()[colDef.treeAggregationType].aggregationFn;
            col.treeAggregation.label = service.nativeAggregations()[colDef.treeAggregationType].label;
          }
        }

```

**Comment by PaulL1** [comment]
Hmm.  That may be true.  We did quite a bit of work on this a while ago, so perhaps so.  For some reason I thought it was asking for something beyond that when I looked yesterday.

Well, that makes you successful already!!  Maybe you should try a harder one.....

**Comment by arjshiv** [comment]
Haha - sure. I'll scout around for another request :+1:

**Comment by arjshiv** [comment]
For reference - this was completed in #3302
