### ISSUE TITLE
Set window resize listener to be debounced

### ISSUE THREAD

**Issue by moberemk** [angular-ui/ui-grid#3158]
Currently the window resize handler function is called every time a resize event is fired, which from what I've found can cause performance issues due to how many times that event gets called while a user is trying to resize their window. Be it either as an option or with a sensible hardcoded default (say, 200-300ms?), I think the the resize handler function should only be called after resizing has halted so that it doesn't absolutely tank application performance.

Heck it currently even makes debugging a pain--I set a breakpoint in the `gridResize` function in Chrome dev tools and resizing the window causes the page to crash entirely.

**Comment by PaulL1** [comment]
Is this in 2.x or 3.x?  I can't see this function in 3.x so I'm assuming 2.x?

**Comment by moberemk** [comment]
It's in `uiGridDirective`; it's set in https://github.com/angular-ui/ng-grid/blob/master/src/js/core/directives/ui-grid.js and attached on line 243, and seems to be in the Master branch as well as the unstable release JS file

**Comment by imbalind** [comment]
Better to link with a fixed commit and with line encoded.

Function is now at https://github.com/angular-ui/ui-grid/blob/dd30be46fa49832a2753330d8f98cb11c602b3d3/src/js/core/directives/ui-grid.js#L335

Anyhow i'm trying with current version on Firefox 40+ and I got acceptable performance (with quite a big grid).

I'm closing this for now as a wontfix, if you still experience issues just feel free to reopen it.
