### ISSUE TITLE
Get filtered data

### ISSUE THREAD

**Issue by lachyn** [angular-ui/ui-grid#318]
Hello, sorry for my newbie question, but I cannot figure out how to get filtered data from the table. For example I want to run some action on all rows which remained after I applied filter. I already found how to do it with selected rows, but in this case I am lost.. Thanks for any suggestion.

**Comment by patriciocordova** [comment]
$scope.myGridOptions.ngGrid.filteredRows is not available. How do we access filtered data?

**Comment by pradapkumar** [comment]
var filterChanged = false;

$scope.gridApi.core.on.filterChanged($scope, function() {
    filterChanged = true;
});

$scope.gridApi.core.on.rowsVisibleChanged($scope, function() {
    if(!filterChanged){
        return;
    }
    filterChanged = false;
    // The following line extracts the filtered rows
    var filtered = _.filter($scope.gridApi.grid.rows, function(o) { return o.visible; });
    var entities = _.map(filtered, 'entity'); // Entities extracted from the GridRow array
    $scope.total = _.sumBy(entities, function(o) {
        return parseInt(o.price);
    });
});
