### ISSUE TITLE
getRow implementation and row class

### ISSUE THREAD

**Issue by Shanna7463** [angular-ui/ui-grid#3186]
I am using a pub/sub service and based on the data I receive I need to highlight the corresponding row.  So basically I have several columns (Unique User Id, Name, Age, Gender)...the pub/sub service is going to send a Unique User Id and I need to then highlight the corresponding row.  What is the best way to go about doing this?  I've been going through the ui-grid API but I don't see a way to search a specific column.  I see the getRow function, but I'm not sure what the rowEntity value should be. 

Thanks for any guidance!

**Comment by PaulL1** [comment]
There are a few different ways to go about this, and it depends what you mean by highlight.

1. If the call only gives you a single id that you need to select (selection feature), you can go through the data array and find the row in your array that you want to highlight.  You can then pass that to selectRow to select it

2. If you want to highlight it, you could set a cellClass or a rowClass that highlights that row.  That basically means you'll have a callback function that is called for each row, and in the callback you'll return true if the row.entity.id === yourId.  The custom templates examples or cellClass examples might give some ideas there

**Comment by Shanna7463** [comment]
Thanks for the quick response! Scenario 1) was exactly what I needed.  I am trying to implement what you suggested, but the row never gets highlighted...it hits my alert so the matching row is being detected but my selectRow call doesn't seem to be working.  Here is what I have:

    for(var i=0; i <= 10; i++) {
        	  if ($scope.gridOptions.data[i].name == $scope.featureId) {
        		  //select row
        		  $scope.name = $scope.gridOptions.data[i].name;
                  alert($scope.name);
        		  $scope.gridApi.selection.selectRow($scope.gridOptions.data[i]);
        		  break;
        	  }

Do you see any issues with my implementation?

Thanks!

**Comment by PaulL1** [comment]
Main issue is a timing one.  If you look at the selection tutorial we do a similar thing, but the trick is that we set the data, then do a $timeout, then set the selection.  We can't call the selection on the rows until the grid has had the chance to ingest the data, which happens in a $digest cycle - using $timeout puts you into the next $digest cycle, so it will be done by then.

**Comment by Shanna7463** [comment]
I believe adding the $timeout worked.  However I ran into another issue...I need to add a check to see if the row I am searching for is already selected (since a publish happens when a row is selected).  I tried adding this simple check, but it doesn't seem to be working: 

        if($scope.gridOptions.data[i].isSelected) {					
		alert("Row Selected");
        }

I've also tried using getSelectedGridRows, but it also isn't working correctly for me (I'm sure I'm just implementing it wrong)...multiselect is false, so I think if I call this is should just return an array with a single value, correct?

    $scope.selected = $scope.gridApi.selection.getSelectedGridRows();
    alert("Selected Rows: " + $scope.selected[0].Name);

**Comment by PaulL1** [comment]
I think the problem in your latter code is that the property is `name` not `Name`.  But otherwise getSelectedGridRows should work fine.

**Comment by c0bra** [comment]
@Shanna7463 Did you have any luck with your issue?

**Comment by kaushikyasaswy** [comment]
row.entity.<field_name> is not an option at a group level. Is there a workaround for this?
