### ISSUE TITLE
Grid rows occasionally showing up disorganized under grid container

### ISSUE THREAD

**Issue by dprothero** [angular-ui/ui-grid#3202]
This one is hard to describe. Every once-in-a-while, my grid will show up like the picture below. It's very rare. I have seen it occur in IE 11 and Chrome 41. Refreshing the page makes the problem go away and the grid renders properly.

![image](https://cloud.githubusercontent.com/assets/1897006/6975056/107ad7b8-d94d-11e4-98ff-8198ba91342d.png)

My grid tag looks like this:
```
<div ui-grid="results" ng-show="results.data.length &gt; 0" style="width:100%;"
  ui-grid-selection ui-grid-exporter ui-grid-resize-columns ui-grid-move-columns
  ui-grid-save-state ui-grid-pagination>
</div>
```

Any thoughts as to what *might* be happening so I can try to come up with a consistent repro?

**Comment by c0bra** [comment]
If you remove all the plugins does the problem go away?

If not, how are you fetching data and initializing the grid? It looks like the header has the right column widths but the rows aren't getting the styles.

Is also make sure you're using the latest RC.

**Comment by dprothero** [comment]
It happens so rarely, it would be hard to troubleshoot via process of elimination. At this point, my customer is pretty excited about all the features the grid does have that they're willing to live with the occasional need to refresh the page to fix the grid (thankfully, it's an internal app).

As for getting data into the grid, I'm initializing the grid with the data property set to null. I wait for some user input, make an $http call, and then set the data property in the success callback.

Since it is so difficult to reproduce, is there any other diagnostic information I can gather when I do observe the behavior again (beyond just a screenshot)? Perhaps some strategically placed logging code?

**Comment by c0bra** [comment]
Are you asynchronously providing anything other than data? Column definitions? Templates?

I would put a breakpoint before you load the data and then step through to see if you can target where this is happening maybe.

Thinking of that, do you see a flash of properly styled columns before they end up like this? And do they stay the same if you sort or filter?

**Comment by dprothero** [comment]
Just following up on this. I really wish I could answer your questions, but it's not consistently reproducible, so debugging it is out of the question. When it does happen, it seems to be when we have already given it some data and are providing it new data to replace what it's been displaying.

**Comment by PaulL1** [comment]
I've seen behaviour that is unusual when giving new data that replaces the old and doing one of a few things:

- replacing columnDefs but using the same names.  This might be fixed recently with track by uid
- replacing data by overwriting the object reference, but not defining using `gridOptions.data = 'data'`

Are either of those potentially things that you're doing?

**Comment by dprothero** [comment]
I'm not doing the first one, but the second one looks like what I'm doing.

1. I start off by setting gridOptions.data = null (but also have the grid hidden)
2. The user performs a search and in the success() callback from my $http request, I set data to the results that come back from the call.

It seems to work (most of the time). Is there some other way I should be trying to accomplish this?

**Comment by PaulL1** [comment]
I think the safest way is that you always put your data into `$scope.data`, and you set your gridOptions to `$scope.gridOptions.data = 'data';`.  Finally, make sure you declare your $scope.data up front (this shouldn't be necessary, but sometimes I've seen problems that might be related to it).

So you'd end up with something like http://ui-grid.info/docs/#/tutorial/105_footer

**Comment by dprothero** [comment]
Thanks @PaulL1, I finally got around to trying this and so far I have not seen this behavior again.
