### ISSUE TITLE
2 Auto-Resize Expandable Grids continuously resize/redraw

### ISSUE THREAD

**Issue by nomad2358** [angular-ui/ui-grid#3203]
I've created two auto-resize, expandable grids (one in each tab of a bootstrap tabset) via directives.  When the grid container height is less than about 1000px, the grid continuously resizes/redraws.  If the height is increased to more than 1000px, the redraws stop.  It also stops if the auto-resize or expandable features are taken out.  I also tried using controllers instead of directives without any change in behavior.

I've reproduced the problem on plunker (http://plnkr.co/edit/uTz1Xb20B8cOEwsYnBFV?p=preview).

Any thoughts?

**Comment by mportuga** [comment]
Could not reproduce:
http://plnkr.co/edit/cvizdmT2E9bLSMXyjMv5?p=preview
