### ISSUE TITLE
Tab Index Recyling after reaching URL

### ISSUE THREAD

**Issue by MakamRavi** [angular-ui/ui-grid#3204]
Can anyone please tell me how to recycle through grid cells using tab after reaching URL and also unable to to navigate the fields outside grid.
 Even not getting focus for icons(eg:-add,delete) when tabbing.Icons are getting skipped when tabbing through fields.Working fine for text fields.
Also added the following in gridoptions.
 noTabInterference: true,
 tabIndex: 0,
          

The updated plunker is http://plnkr.co/edit/LWodGQtcIOPJFH6YOJZT?p=preview

Any help would be greatly appreciated.

**Comment by AgDude** [comment]
This issue was moved to angular-ui/ng-grid-legacy#10
