### ISSUE TITLE
filter grid data using external input field search 

### ISSUE THREAD

**Issue by ashokalluri123** [angular-ui/ui-grid#3205]
i want to filter the data in grid, using outside of the grid control i mean one textbox which is located of the grid .
I had seen ngGrid is working fine with filterOptions ,
Filter by all columns with single textbox.
but it is not working in ui.Grid 
Help me how to achive it using ui.Grid ,

Looking for forwaded reply .

**Comment by aikrez** [comment]
You can try with external filtering see 308_external_filtering in the tutorial

**Comment by ashokalluri123** [comment]
i want to place a textbox outside of the grid throught that i want to perform filtering

**Comment by PaulL1** [comment]
This is not possible in ui-grid, ui-grid provides filter per column.  Refer also to #2481.

**Comment by tech-no-logical** [comment]
how 'legal' is it to do something like 

$scope.gridApi.grid.columns[1].filter.term = myString;

to trigger a (hidden) filter from outside the grid ? a quick experiment shows me this 'works'...

**Comment by PaulL1** [comment]
I think this is OK.  Strictly speaking this isn't part of the API, but I know a lot of people do it, so we aren't going to change that setup without telling people.

**Comment by tech-no-logical** [comment]
ok, thanks. for future reference if anybody needs the workaround : 

expose the gridApi 

    $scope.gridOptions.onRegisterApi = function (gridApi) {
      $scope.gridApi = gridApi;
    }

bind the external inputs to the filter's term directly

    <input type="text" ng-model="$scope.gridApi.grid.columns[1].filter.term" />

hide the internal filters 

    .ui-grid-filter-container { display: none!important; }

and there you go. also, if you want to filter on a hidden column, you'll need to trigger a refresh after the searchterm has changed by doing

    $scope.gridApi.grid.queueGridRefresh();

**Comment by skubski** [comment]
I followed the technique described by <b>tech-no-logical</b> but instead had to use:

<code>
 &lt;input type="text" ng-model="controllerAs.gridApi.grid.columns[0].filters[0].term"&gt;
</code>

I'm not sure if this supported in the long term but this workaround definitely works.

**Comment by adamcadaver** [comment]
I can not get this fix by @tech-no-logical or @skubski working - is there a plunkr somewhere implementing this?

**Comment by icfantv** [comment]
Our solution was a lot more simple than this.  We bound our filters to a common object literal, say gridFilterObj, and then on our grid columns, you define the `filter` property:

```
      filter: {
        noTerm: true,
        condition: function(searchTerm, cellValue) {
          let result = true;

          // insert your condition here that uses $scope.gridFilterObj.<your_filter_field>
          // you ignore the "searchTerm" parameter because you're using your own filters instead

          return result;
        }
      }
```

And then you just watch the filter object for changes:
```
  $scope.$watchCollection('gridFilterObj', function() {
    $scope.gridApi.grid.refresh();
    
    // this just ensures you scroll to the top of the grid when the filters change.
    $scope.gridApi.core.scrollTo($scope.gridOptions.data[0], $scope.gridOptions.columnDefs[0]);
  });
```

We still needed the CSS to hide the filter row.  Unfortunately, `enableFiltering` is tightly coupled the menu option to clear all the filters and you cannot provide custom hooks.  See #4923 for more information as well as [this SO article](http://stackoverflow.com/questions/34585762/when-using-external-grid-filtering-how-do-i-hide-the-clear-all-filters-grid-m).

**Comment by merzikain** [comment]
I was having trouble making this work for my use case. I wanted a set of buttons instead of a text field for filtering a couple of columns. Their values were either A or B so a button made more sense than a text field.

The first thing that I had to make sense of from the posts here is the line:

`    $scope.gridApi.grid.columns[N].filter.term;`

It took a while to figure out that N needed to be the key of the column I wanted to filter on. Sure, it should be "obvious" but it took a while for me to go "Duh, I need to change that". It wasn't explicitly stated anywhere so I wanted to state it here.

The next issue I had was that I was setting enableFiltering:true on my field but it apparently didn't like it being sent at the field level without it being set "globally" for the gridOptions object. I had to change my gridOptions so that I had gridOptions.enableFiltering = true; and then explicitly turn it off on the fields I did not want filtered.

    $scope.gridOptions = {
        enableFiltering: true,
        columnDefs: [
            {field:'field1', ..., enableFiltering:false},
            {field:'field2', ..., enableFiltering:false},
            {field:'field3', ..., enableFiltering:false},
            {field:'field4', ..., enableFiltering:true}
        ]
    };

After that I had no trouble, my buttons worked fine. Hopefully that'll help anyone else who may have similar issues trying to make sense of how external filtering can be implemented.

**Comment by mjknight50** [comment]
@merzikain 
 I am trying to do something like you are describing but I can't quite make it work.

I have a button that calls this:
   ```
vm.filterRequests = function () {
        vm.gridOptions.data = $filter('filter')(vm.gridOptions.data.columns["requestedBy"], vm.somevalue, undefined);
    };
```

Here is my table:

```
vm.gridOptions = {
        enableFiltering: true,
         columnDefs: [
            { field: 'proposalName', cellClass: "ui-grid-vcenter" },
            { field: 'requestedBy', cellClass: "ui-grid-vcenter" },
            { field: 'requestType', cellClass: "ui-grid-vcenter" },
            { field: 'requestStatus', cellClass: "ui-grid-vcenter" },
        ],
    };

```

In your write-up you say that N should be the key of the column I want to sort on, but what is that syntax?  Is it the column name?  The column number as an integer?  I tried both ways.

ReferenceError: requestedBy is not defined

**Comment by merzikain** [comment]
It needs to be the integer key for the field. Though I'm not sure why that didn't work when you tried it.

Since making that post I implemented pagination which changed the way I had to filter the list so I'm not doing it exactly the same as before. Now it's in a getPage() function that filters the values as part of the pagination.

**Comment by misald** [comment]
I need to filter out two column by default those are,

columnDefs: [{
                field: 'roleName',
                name: '​Role',
                enableHiding: false,
                headerCellClass: 'text-left',
                cellClass: 'text-left',
                width: 300,
                filter: this.gridService.defaultTextFilter(),
                menuItems: this.gridService.defaultTextMenu()
            }, {
                field: 'programName',
                name: 'Program Name',
                enableSorting: false,
                enableHiding: false,
                enableFiltering: false,
                headerCellClass: 'text-left',
                cellClass: 'text-left',
                width: 200,
                filterHeaderTemplate: selectFilterTemplate,
                filter: this.gridService.defaultSelectFilter(),
                menuItems: this.gridService.defaultSelectMenu()
            }]

and where should i add this,

$scope.gridApi.grid.columns[N].filter.term;
