### ISSUE TITLE
Grid showHeader isn't working

### ISSUE THREAD

**Issue by YonatanKra** [angular-ui/ui-grid#3213]
I've got a demo for this:
http://plnkr.co/edit/1fX6ZuqUt7xANO1P7MMG?p=info
Toggle button changes the "showHeader", but nothing happens after changing the showHeader.

**Comment by PaulL1** [comment]
This looks to me like an instance of #1819.  Not all of our options are able to by dynamically set.

**Comment by ghiscoding** [comment]
Is there a way to do it with current UI-Grid version or is it still not possible?

**Comment by camdav** [comment]
Have you found a solution?
