### ISSUE TITLE
Selecting rows in sub-grids (selection is not maintained when you scroll up or down of parent row)

### ISSUE THREAD

**Issue by rameshkv** [angular-ui/ui-grid#3247]
Hi,

I have experiencing the issue with sub grid selection, I have main grid row selection as well as subgrid selection. my goal is to select parent row and subgrid of that parent row ( subgrid has many row)
when I click selection of subgrid rows, it does selects but when I move vertical scroll up and scroll down to parent row. the selection of subgrid gets removed.

Could you please address this issue. we have big trouble on this.. problem is we have some devices shown as in main gird rows, when you click on the main grid rows it should expand with sub grid and should show of sub devices. Finally we have to add whatever we select in main grid row and sub grid. 

To reproduce this issue, please find the below attachments, i have taken the example for UI grid tutorial.

![step1](https://cloud.githubusercontent.com/assets/8971467/7067800/a2f6383c-deeb-11e4-9b5a-14188aa2893a.png)
![step2](https://cloud.githubusercontent.com/assets/8971467/7067804/ac2ddc52-deeb-11e4-80af-47586c756772.png)
![step3](https://cloud.githubusercontent.com/assets/8971467/7067817/c0f8356a-deeb-11e4-8277-3887eb11fa43.png)

**Comment by rohillaanshul** [comment]
was this issue fixed ?
I am seeing similar behavior in ui-gird 4.2.2
