### ISSUE TITLE
Feature, add css class to header columns when moving column

### ISSUE THREAD

**Issue by ChrisSchmidt1991** [angular-ui/ui-grid#3249]
Hello, 
It would be nice to have  css classes in the header columns for the new/old & left/right positions while moving the column.
![csscolumnmovingexample](https://cloud.githubusercontent.com/assets/11062161/7070837/8888d3ba-deaf-11e4-8b9c-3c71a423c93a.png)

In the picture above we are able to add a blue border to the possible new position to let users know where the column will be placed and light blue highlighted the column that is moving

Thanks

**Comment by PaulL1** [comment]
This is a useful request, but not really in the current roadmap.  We have far too many good ideas in the repository already, giving the impression that we have a project riven with defects.

Accordingly, I am leaving the enhancement tag on this, but closing it.  If someone would like this functionality, we'd welcome a pull request that adds it.
