### ISSUE TITLE
Ensure that a column is visible when a ui-grid is first displayed (and columns are pinned)

### ISSUE THREAD

**Issue by muhmud** [angular-ui/ui-grid#3256]
Would be it possible to mark a column to say you wanted the grid scrolled such that the column was visible when the grid is first loaded?

**Comment by PaulL1** [comment]
Look at the scrollTo api (it used to be called scrollToIfNecessary).  You'd do this by waiting on the gridApi (onRegisterApi), then once you have both that and your data has been loaded, you then call scrollTo on the specific column.  You can pass null for the row.

**Comment by muhmud** [comment]
Hmm, can't quite get this to work. I can see scrollTo methods on gridApi.cellNav, but when I call them:

gridApi.cellNav.scrollTo(null, colDef);

they don't do anything. The docs say the scrollTo methods should be on Grid, but can't find them there.

**Comment by PaulL1** [comment]
You may need to upgrade to unstable - these changes were very recent.

**Comment by muhmud** [comment]
Yeah, I'm using the unstable version, which I took a copy of a couple of weeks ago. There seems to be two issues here, one which is my fault, and the other that I think is a bug, which may have been fixed since I took my copy.

It seems that I was calling scrollTo() in onRegisterApi() but before the grid was fully loaded as you mentioned I should do initially. Is there an event for "GridReady" or, more specifically for my case, an event for columnDefs changed? Found this by seeing that this.columns was empty when getColumn() was called by scrollTo().

However, getting passed this, the scrollTo call still didn't work. Debugging into scrollToIfNecessary(), it looks like rightBound doesn't correctly take into account pinned columns, as neither if's in the gridCol section near the end of the function get called into, and a scrollEvent doesn't get fired. Unpinning columns fixes the issue.

Would you say this has been fixed in a newer version? Thing is I had to hack my copy to make something else work, so updating is not going to be straightforward.

Cheers,
Muhmud.

**Comment by muhmud** [comment]
Sorry, it's not rightBound that's the problem, but rather columnRightEdge.

This fixes the issue (but doesn't take into account right-pinned columns):

var pinnedLeftColumnWidth = 0;
if (grid.renderContainers.left) {
  for (var i = 0; i < grid.renderContainers.left.renderedColumns.length; ++i) {
    pinnedLeftColumnWidth += grid.renderContainers.left.renderedColumns[i].drawnWidth;
  }
}

var columnRightEdge = columnLeftEdge + gridCol.drawnWidth + pinnedLeftColumnWidth;

**Comment by PaulL1** [comment]
It may not be resolved - @swalters, is this suggestion something we'd want to add?

**Comment by brucemackenzie** [comment]
I'm seeing the same issue. Look forward to the result of your investigation :)

**Comment by tonyeung** [comment]
I think this may be related. I'm trying to scroll to a newly inserted row on page load. 
Long story short, no scrolling.

Here's a plnkr repro: http://plnkr.co/edit/pz2gACcGc3glqCs0mZlP?p=preview
Expected behavior is to scroll to Hilda Crane.

relevant code lines are listed below: 
```
    $scope.gridOptions = {
      ...,
      onRegisterApi: function (gridApi) {
          $scope.gridApi = gridApi;
          $scope.gridApi.core.on.rowsRendered(null, scrollTo);
      }
    };
```
and
```
    function scrollTo(gridApi) {
      var rows = $scope.gridApi.grid.renderContainers.body.visibleRowCache;
      rows.forEach(function (row) {
          if (row.entity.name === 'Hilda Crane') {
              console.log("found hilda");
              console.log(row.entity);
              //$scope.gridApi.core.scrollTo(row.entity, null);
              $scope.gridApi.cellNav.scrollToFocus(row.entity, null);
          }
      });
    }
```

**Comment by PaulL1** [comment]
I believe the selection tutorial has something similar - it selects a specific row.  The key is I think to use a $timeout or $interval.  I'm also not entirely sure that the way you're calling your scrollTo method will work - I don't see how gridApi is getting passed to it.

**Comment by tonyeung** [comment]
@PaulL1 i only stuck the gridapi there because when i put in (a,b,c,d,e) just for grins while blackboxing, i saw that it was being passed there. The code itself doesn't use the gridapi being passed in, but the one that's attached to $scope. 

I had to change two things to make this work.
Once is that I have to pass in a row from the actual data that's on gridOptions, and two is wrap it in a $timeout. My testing indicates that BOTH of these things have to be there or it won't work.
For future reference this is a sample: http://plnkr.co/edit/6jsWPxB5w0m4UArU7ik1?p=preview

Thanks for pointing me in the right direction.
