### ISSUE TITLE
Add cancelable event rowSelectionChange

### ISSUE THREAD

**Issue by viveleroi** [angular-ui/ui-grid#3289]
It's necessary for us to make a decision about whether the user may change row selections (for example a row selection might load data into an editor, and if they change the selection we must prompt for unsaved changes).

Event  `rowSelectionChanged` is insufficient because the selection changes have already occurred. 

Forcing the selection back to the previous row is less efficient, but would work, however `grid.selection.lastSelectedRow` doesn't appear to be accessible externally so we'd have to track this separately.

Update: I see that `grid.selection.lastSelectedRow` is available on the row object, however it's apparently updated to point to the currently selected row during the rowSelectionChanged event, so it's not the correct "last" selected row for this context.

**Comment by PaulL1** [comment]
If you really need to get at `grid.selection.lastSelectedRow`, you can use `gridApi.grid.selection.lastSelectedRow`.  Which doesn't answer the bigger question, but might help.

**Comment by viveleroi** [comment]
Unfortunately `grid.selection.lastSelectedRow` is updated before this event fires to the newly selected row, so it's useless for this usecase.

**Comment by SoftInvent** [comment]
Hope this can help others.
I really needed this feature and added my own customization to my local version of ui-grid.js. I'm not sure I play by all the rules, but it seems to work.
I added a "rowSelectionChange" event to the events.selection object so the event gets registered with the publicApi and added a few lines of code in the "toggleRowSelection" function.
To cancel a row change, the event handler must call "preventDefault()" on the passed event object.

The following code is for the event registration (around line 24410 in ui-grid.js v3.1.0) :

```javascript
var publicApi = {
	events: {
		selection: {
			//CUSTOM CODE BEGIN
			/**
			 * @ngdoc event
			 * @name rowSelectionChange__
			 * @eventOf  ui.grid.selection.api:PublicApi
			 * @description  is raised before the row.isSelected state is changed
			 * @param {GridRow} the row that was selected/deselected
			 * @param {Event} cancelable event object if raised from an event
			 */
			rowSelectionChange: function (scope, row, evt) {
			},
			//CUSTOM CODE END
			/**
			 * @ngdoc event
			 * @name rowSelectionChanged
			 * @eventOf  ui.grid.selection.api:PublicApi
			 * @description  is raised after the row.isSelected state is changed
			 * @param {GridRow} row the row that was selected/deselected
			 * @param {Event} event object if raised from an event
			 */
			rowSelectionChanged: function (scope, row, evt) {
			},
			/**
			 * @ngdoc event
			 * @name rowSelectionChangedBatch
			 * @eventOf  ui.grid.selection.api:PublicApi
			 * @description  is raised after the row.isSelected state is changed
			 * in bulk, if the `enableSelectionBatchEvent` option is set to true
			 * (which it is by default).  This allows more efficient processing
			 * of bulk events.
			 * @param {array} rows the rows that were selected/deselected
			 * @param {Event} event object if raised from an event
			 */
			rowSelectionChangedBatch: function (scope, rows, evt) {
			}
		}
	},
```
and this is for the toggleRowSelection (around line 24763 in ui-grid.js v3.1.0):

```javascript
toggleRowSelection: function (grid, row, evt, multiSelect, noUnselect) {
	var selected = row.isSelected;

	if (row.enableSelection === false && !selected) {
		return;
	}

	//CUSTOM CODE BEGIN
	//Raise the rowSelectionChange event
	grid.api.selection.raise.rowSelectionChange(row, evt);
	if (evt.isDefaultPrevented()) {
		return;
	}
	//CUSTOM CODE END

	var selectedRows;
	if (!multiSelect && !selected) {
		service.clearSelectedRows(grid, evt);
	} else if (!multiSelect && selected) {
		selectedRows = service.getSelectedRows(grid);
		if (selectedRows.length > 1) {
			selected = false; // Enable reselect of the row
			service.clearSelectedRows(grid, evt);
		}
	}

	if (selected && noUnselect) {
		// don't deselect the row
	} else {
		row.setSelected(!selected);
		if (row.isSelected === true) {
			grid.selection.lastSelectedRow = row;
		}

		selectedRows = service.getSelectedRows(grid);
		grid.selection.selectAll = grid.rows.length === selectedRows.length;

		grid.api.selection.raise.rowSelectionChanged(row, evt);
	}
},
```

**Comment by yccteam** [comment]
Looks like a nice solution. 
So far I've kept my last selection at all times (I've added my own "currSelection" array).  There is some logic involved though so you solution might do the trick better.

Only issue is with the `preventDefault` which might cause some undesired effects.   We'd might do with  creating a method that changes some parameter? Like: `shouldPreventChange()`, which would change `preventChange`.

```
//CUSTOM CODE BEGIN
    //Raise the rowSelectionChange event
    grid.api.selection.raise.rowSelectionChange(row, evt);
    if (grid.api.selection.shouldPreventChange()) {
grid.api.selection.shouldPreventChange(false);
        return;
    }
    //CUSTOM CODE END
```
Seems like a very useful event.
Would you like to post a PR for this?

**Comment by SoftInvent** [comment]
Thanks for your reply Yonatan. 

I too, am a bit concerned about the effects of ```preventDefault``` and agree that a method, as you suggest, should be sufficient.

Regarding the PR, I must admit that I've never contributed to open source projects before and I need to learn what it involves before I can submit a PR.
I've started reading the docs for contributing to ui-grid, but haven't got that much spare time, so it may take a while before I'm up to speed and ready to contribute.

**Comment by yccteam** [comment]
I'm also quite new to gitHub myself :)
There are instructions on how to do that, althuogh I must admit it has its learning curve...
