### ISSUE TITLE
Reset grid state to default

### ISSUE THREAD

**Issue by ravishivt** [angular-ui/ui-grid#3293]
We have the option to save and restore the grid state but no option to restore the state back to its default.  Is there a signal I can listen to on initial grid load to save the initial default state.  The onRegisterApi event occurs too early to populate the grid state and the other events I've found are too chatty.

**Comment by PaulL1** [comment]
There isn't currently an event after onRegisterApi.  There is rowsRendered, but that depends on when your data arrives, which may not be the right timing for you.

I have had some success with doing a $timeout of 0 from within onRegisterApi.  Is that sufficient for your purposes?

**Comment by ravishivt** [comment]
The $timeout of 0 within onRegisterAPI sorta works but not fully.  Initialization events still fire after the $timeout event occurs such as filterChanged.  I'd prefer to have an event when the table is fully loaded and stabilized with all filters processed.

**Comment by yuanda** [comment]
That's what I want too. I'd like to add a restore to init state button to my grid too.

**Comment by pinna72** [comment]
I need too. It could be nice to have the restore feature. Please do it.

**Comment by typicalphoenix** [comment]
I was able to find a way around this hooking into this event
`onRegisterApi: function (gridApi) {`
                    `    $scope.studentSearchGridApi = gridApi;`
                    `    gridApi.core.on.rowsRendered($scope, function () {`
                       `     saveDefaultGridState();`
                   ` });`
Then I used this function to store the default state, make sure to use an if statement
`var saveDefaultGridState = function () {`
               ` if (!$scope.defaultState) {`
                    `$scope.defaultState = $scope.studentSearchGridApi.saveState.save();`
               ` }`
            `};`
Then I can call this function to load the defaults
`var loadDefaultGridState = function () {`
               `$scope.studentSearchGridApi.saveState.restore($scope, $scope.defaultState);`
            `};`
