### ISSUE TITLE
Total Items in footer issue

### ISSUE THREAD

**Issue by richtmat** [angular-ui/ui-grid#332]
Total Items in the footer does not show the $scope.pagingOptions.totalServerItems I configured.
Instead, it reads from grid.config.totalServerItems.

**Comment by varshaan0sharma** [comment]
I got this issue fixed by updating totalServerItems on every paging action

**Comment by nkantkumar** [comment]
I used $scope.gridApi.grid.option.totaltems and it is started working

**Comment by blakerego** [comment]
I agree with @nkantkumar:  $scope.gridApi.grid.option.totalItems properly sets the footer's totalItem count.
