### ISSUE TITLE
Create bower package for unstable version

### ISSUE THREAD

**Issue by AlexBen** [angular-ui/ui-grid#3337]
Hi! We are using unstable version of ui-grid in our development phase and also using bower for dependency management. 
Can you please create package for unstable version (includes .js, .css and fonts files) for simple using with bower.json?

**Comment by Greenek** [comment]
In my opinion it should be just one repository, with bower.json and git hooks for making automatic builds after each commit. Then it's much easier to switch between stable and unstable releases (and single commits).

**Comment by gavioto** [comment]
I thinks bower ui-grid unstable version support for bower will help testing new versions, not only RC
