### ISSUE TITLE
Header column and data column are misaligned in IE9 when there are too many columns

### ISSUE THREAD

**Issue by dereklin** [angular-ui/ui-grid#3342]
Here is the jsfiddle link: http://jsfiddle.net/76fhfzcx/1/

Bascially, I have many columns that the grid is wider than the screen.  In IE9, the header columns and data columns are misaligned.

I did some searching, but the misalignment issue was about scrolling.  In my case, it's just when the grid is first displayed.

Is there a fix or workaround?

Thanks!

**Comment by dereklin** [comment]
I have added jsfiddle link:

http://jsfiddle.net/76fhfzcx/1/

(I had to embed all my js code in the HTML section ...)

**Comment by kolesnik** [comment]
+1 - similar with IE9

**Comment by melcor76** [comment]
I had problems with misalignment in IE9 when the header text was longer than the column width.
My solution was to shorten the text.

**Comment by PaulL1** [comment]
@c0bra: I think you were looking at something like this.  Is this something you've already dealt with?

**Comment by mdsauer** [comment]
I am seeing the same problem.  You can also recreate by adding columns in the "Adding and remove columns" tutorial.  (As a side note, in that tutorial the horizontal scroll does not appear to be adjusting as I assume it should.  That aspect appears to not work in Chrome as well.)

**Comment by anandvihar** [comment]
I am also facing the similar problem

**Comment by gabrieldocarmosantana** [comment]
I had the same issue in IE9 and  i Solve Setting the same width of the title like width the collum.

If the width of the collum was less than width of the size of the title the problem occours in ie9.

**Comment by mportuga** [comment]
ie9 is no longer supported.
