### ISSUE TITLE
Any way to move the horizontal scrollbar below the footer row??

### ISSUE THREAD

**Issue by himsraw** [angular-ui/ui-grid#3347]

**Comment by PaulL1** [comment]
Not currently, no.  If we could have put it below the footer we would have.

**Comment by himsraw** [comment]
Is it a big issue achieving that? I was trying my hands but was not successful. Has anyone else achieved that?

**Comment by samsmithnz** [comment]
I agree with himsraw. Why is this so technically challenging? Most tables I've used have the scroll below the footer.
