### ISSUE TITLE
 filter dropdowns

### ISSUE THREAD

**Issue by rmyemul** [angular-ui/ui-grid#3349]
The drop down is not working properly when I change the page-size  5 to 10 its not showing  10 rows of data  and you can check your self with your example also  http://plnkr.co/edit/50vJrs?p=preview specifically look at the drop down from 5 to 10 there would be no effect from that. 
  I hope you will help early as early  as

**Comment by PaulL1** [comment]
I would look at upgrading to ui-grid.  The pagination works and is supported.
