### ISSUE TITLE
ng-grid page goes blank issue

### ISSUE THREAD

**Issue by sunil123-github** [angular-ui/ui-grid#3351]
When try to drag the ng-grid columns,  whole page going blank. Whats the solution for this.

**Comment by PaulL1** [comment]
Is this with 2.x?  Do you have a plunker?

**Comment by sunil123-github** [comment]
Yep its happening with 2.x . I dnt use plunker.

**Comment by sunil123-github** [comment]
Yep its happening with 2.x . I dnt use plunker.
