### ISSUE TITLE
Ng-grid tabbing issue

### ISSUE THREAD

**Issue by leelakrish** [angular-ui/ui-grid#3352]
Consider the grid width is 400px, and it has four columns. All column width is 100px. then tabbing between columns are working as expected.

http://plnkr.co/edit/2yMGLTY1L69lGwY7W667

Similar kind of grid with the same 400 px width. It has 4 columns. But Consider each column has 300px width, then tabbing between columns are not working. It is tabbing out only within the column which are visible on the screen. Please find the plunker here.

http://plnkr.co/edit/HtWt7soGrpGwTtP7khaB

I am not sure why this is happening. I am displaying almost 20 columns in the ng-grid, and would like to implement the tabbing functionality

**Comment by PaulL1** [comment]
I'd consider upgrading to ui-grid, I'm pretty sure this works there.

**Comment by leelakrish** [comment]
The application is almost ready with ng-grid, I am missing only this functionality. Now moving to ui-grid would be costly. Am I missing to include any other option in ng-grid to make that work.

**Comment by leelakrish** [comment]
This is not working in ui-grid though. https://github.com/angular-ui/ng-grid/issues/3451
