### ISSUE TITLE
Unusual behaviour when data not initially provided (in some situations)

### ISSUE THREAD

**Issue by AnselmeR** [angular-ui/ui-grid#3355]
Hello,

I use the grid with a button that give to users the ability to toggle the **filtering** feature.
The code behind is the following:
```javascript
$scope.toggleFiltering = function() {
  $scope.grid.gridOptions.enableFiltering = !$scope.grid.gridOptions.enableFiltering;
  $scope.grid.gridApi.core.notifyDataChange( uiGridConstants.dataChange.COLUMN );
};
```
The problem is, once the **selection** feature is enabled, toggle **filtering** makes the grid not fully rendered:

Case when **filtering** is off:
![ui-grid-selection-filtering-off](https://cloud.githubusercontent.com/assets/10243639/7314367/149537da-ea64-11e4-80c1-e97810f94769.png)
 
Case when **filtering** is on:
![ui-grid-selection-filtering-on](https://cloud.githubusercontent.com/assets/10243639/7314376/28406a8e-ea64-11e4-934d-093c1d5cf64f.png)

The column menu is displayed as if filters have been correctly rendered.

I suspect the selection feature to refresh the grid at the end of the digest cycle but keeping older  layout settings.

Would someone know how to fix this behavior?

Thanks,

**Comment by PaulL1** [comment]
I think this is working on the filtering tutorial?  That would suggest there's something different being triggered by your code - which probably means a plunker is the best way to diagnose it.

**Comment by AnselmeR** [comment]
You're right
Here is the related plunker
http://plnkr.co/z3SrcFGY8eEFHFCnCELr

**Comment by PaulL1** [comment]
Very interesting behaviour.  What I'm finding is that if you set the data using `$scope.gridOptions.data = 'data';` right up front when initialising the controller, then it works reliably well:
http://plnkr.co/edit/zDWA6eUjE5CYmUdWRjtr?p=info

If you don't specify the data upon initial grid render though, and then specify it using `$scope.gridA.gridOptions.data = 'data';` when the data is retrieved, then it doesn't work, and in fact is even more broken that it is in your example:
http://plnkr.co/edit/qa29b3qxLuprxebaDOUR?p=preview

There's something fundamentally messed up in how we're interacting with data in that situation.

Finally, if I set it along the lines of how you've been setting it, which is setting the array itself when the data is retrieved `$scope.gridA.gridOptions.data = data;`, then I get the behaviour you get - without selection the grid works reliably, with selection it occasionally works and occasionally doesn't.
http://plnkr.co/edit/ULyiZIKwfL7aMuRtH6z9?p=preview

**Comment by c0bra** [comment]
Note to self: This may have something to do with how we set up the `$watch` on initialization. If you pass a string in late, post-init then the grid might barf.
