### ISSUE TITLE
horizontal scroll adding elements dynamically which is affecting tab functionality

### ISSUE THREAD

**Issue by maxy4u** [angular-ui/ui-grid#3357]
http://plnkr.co/edit/HtWt7soGrpGwTtP7khaB?p=preview

my tab wont go post third cell by default as third cell will be appended dynamically if i scroll. By tab i mean tabkey usage so the focus on third cell is not going

**Comment by AgDude** [comment]
This issue was moved to angular-ui/ng-grid-legacy#8
