### ISSUE TITLE
Unable to reach last ~3 rows when scrolling down with mouse over left pinned column 

### ISSUE THREAD

**Issue by SebN10** [angular-ui/ui-grid#3362]
When scrolling down with mouse in the grid having the mouse pointer over column pinned to left, the page will start scrolling down without the grid reaching the last ~3 rows. When scrolling with pointer over the content, right pinned column or over scrollbar it will reach the last grid row before scrolling the page. This issue is replicable in the 203_pinning tutorial.

**Comment by PaulL1** [comment]
I'm not getting this issue on that tutorial, it scrolls to the bottom either way.  However, I do get a related issue (I believe), which is that when scrolling with the Mac trackpad over the left pinned container I'm getting some scrolling propagating to the parent, and some scrolling the grid itself.  It works cleanly when over the body container.

@swalters, is this something that you were looking at?

**Comment by swalters** [comment]
Try this again in latest 3.1 release
