### ISSUE TITLE
Bower does not fetch less files

### ISSUE THREAD

**Issue by salarmehr** [angular-ui/ui-grid#3368]
Getting the package using bower, does not download the less files. What is the correct way to use bower and have less files?

**Comment by c0bra** [comment]
Currently the bower repo doesn't include less files. There have been requests from different people to either include them or leave them out.

If anyone has comments/suggestions for making everyone happy please add a comment here.

**Comment by PaulL1** [comment]
@c0bra, I don't see what harm could be caused by including the less files in the bower repository.  People who don't want to use them don't have to.  It seems that where people want to override styles then having the less files gives them that ability, if we distribute only the css then it's harder.

**Comment by salarmehr** [comment]
Actually, less files are necessary for minification. ui-grid use font-face, I need a less variable to set vendor path. Similar to what I do for font-awesome. Currently I have to modify ui-grid css files manually which will undo on next bower update action. Also, including css files in a less file does not embed it, only links to it.

**Comment by salarmehr** [comment]
@c0bra Did you make any decision regarding the issue?

**Comment by JLLeitschuh** [comment]
Re opening:
- [ ] Bower still doesn't fetch less files. This may require a new release candidate?
- [ ] The release file doesn't have the less files for the features in it. Have a look: https://github.com/angular-ui/ui-grid.info/tree/gh-pages/release/src/less

**Comment by JLLeitschuh** [comment]
Unfortunately, this is still slightly broken.
There is currently no way to setup your npm directory so that bootstrap is in the right location so that the includes can be resolved.
