### ISSUE TITLE
Tree View + Footer Issues: detached footer and wrong sum

### ISSUE THREAD

**Issue by dereklin** [angular-ui/ui-grid#3385]
Here is the plunker: http://plnkr.co/edit/XIv8YLl9AMHLQuhYrnLX?p=preview

Problems:

1. The footer is "detached" from the content.  How do I attach the footer to the last row of the grid?
2. When you expand the tree, the sums are wrong.  How do I aggregate on the parent rows only?

**Comment by dereklin** [comment]
I am thinking I can programmatically calculate the height by the number of rows I'll have to fix the white space issue.

And for the summing, are there custom events I can listen when the user clicks on the Expand and Collapse?  If so, I can listen to those events and remove the parent amounts on expansion.

**Comment by PaulL1** [comment]
I think the footer behaviour is as expected - it's tied to the bottom of the grid and doesn't scroll.  It sounds like you're really asking for the grid height to change based on the row height, and the grid doesn't do dynamic heights, so you'd need to do that in code.

Aggregation and treeView don't currently work together, nor do sorting and treeView.

**Comment by dereklin** [comment]
@PaulL1 Can I listen to custom events when user clicks on Expand or Collapse?  Can I then figure out how many rows there are?

**Comment by PaulL1** [comment]
There aren't currently expand or collapse events in the treeView.

**Comment by dereklin** [comment]
@PaulL1 In that case, I'll try using jQuery to bind click events to them.  Does that sound right to you?

Also, do you have any examples of calculating the grid height based on number or rows?  Is that also a jQuery thing?  I don't see that is an option like gridOptions.gridHeight...

**Comment by PaulL1** [comment]
The height of the grid is usually set in your css, if you don't set it in the css then I think it is calculated based on minRowsToShow or something like that.

I personally wouldn't have my grid change height on clicking, I think that will work fine on short trees, but once the tree starts scrolling it will be confusing.  The grid very much works within a viewport, and I think the visual representation should match that behaviour.  

Are you expecting to keep increasing the grid height to show all currently expanded rows, or expecting that at some point the grid would start to scroll?

**Comment by dereklin** [comment]
@PaulL1 this particular grid won't expand more than what's in the plunker.  I have got two expand/collapse points.  They are fixed.

It seems to me that the ui grid is a lot more powerful than what I am using it for in this case.  Should I just write my own custom directive?

But we really would like to be re-using the ui-grid for scenarios, big or small.

I'll try minRowsToShow before using jQuery...  When I change minRowsToShow  after the grid is loaded, I can fire some event to ask to grid to "re-build", right?

**Comment by PaulL1** [comment]
grid.refresh would be the big hammer.  Or gridApi.core.handleWindowResize.

**Comment by dereklin** [comment]
@PaulL1 I updated the plunker: http://plnkr.co/edit/6ds2yEUjracwUFgETZix?p=preview

gridApi.core.handleWindowResize is not working for me.

How do I use grid.refresh?

**Comment by PaulL1** [comment]
I don't think you can change minRowsToShow dynamically, it's used to set the grid height upon initialisation, then the grid keeps that height.  Autoresize may be of some help, but I'm not sure that it changes grid height or only grid width.  I think you can explicitly change grid height by setting height on the grid element, then calling resize: 
  http://plnkr.co/edit/nNGymQVRQjNbbC1zmPTL?p=preview

**Comment by dereklin** [comment]
@PaulL1 OK. Thank you for pointing that out.  On the click events, the code has treeViewButtonClick.  I was thinking if I can some how decorate this function, by decorating the service, and add my own functionality there.  Do you know how I can go about it?

**Comment by dereklin** [comment]
I decorated uiGridTreeViewService.  It works on my local (but it's not flexible, not scalable at all -- I am still trying ways to get rid of the hard coding...)

However, it's not working on plunker for some reason:

http://plnkr.co/edit/aRUtdspqKCpobhNIPrit?p=preview

**Comment by dereklin** [comment]
OK.  Here is my latest attempt, it's coming together.  Please let me know if you see any issues: http://plnkr.co/edit/bOhBuNCToYxUi4c1VaKY?p=preview

**Comment by PaulL1** [comment]
This is a useful request, but not really in the current roadmap.  We have far too many good ideas in the repository already, giving the impression that we have a project riven with defects.

Accordingly, I am leaving the enhancement tag on this, but closing it.  If someone would like this functionality, we'd welcome a pull request that adds it.
