### ISSUE TITLE
Grid content get mess when resize the column-rc20

### ISSUE THREAD

**Issue by ZhengkunWang** [angular-ui/ui-grid#3388]
choose any resizable column, drag the resize indicator on the right side of the column to the left before the column, the grid content will get mess.

![1](https://cloud.githubusercontent.com/assets/4729415/7405897/11146226-ef2c-11e4-8ad7-6081557f0686.png)

![2](https://cloud.githubusercontent.com/assets/4729415/7405898/1352c9f6-ef2c-11e4-9f2f-67234ecb9290.png)

**Comment by boydwang** [comment]
I have found a way to solve it, set the minWidth for each column and then the user can't drag the indicator from right to left, that will prevent this issue

**Comment by kaelhem** [comment]
This issue should be re-opened as it break all the grid. The fix of @boydwang is working, but it's a workaround.
In my app, we are using a large amount of grids, and fortunately all of them are encapsulated in a directive. So I was able to add a watcher on the columnDefs to patch the minWidth for all columns. But having to add a watcher for this is... hu... not really the better solution I think.

**Comment by boydwang** [comment]
OK, agree with @kaelhem , could any one shield some light for this?

**Comment by mportuga** [comment]
No longer reproducible since all columns now have a default minWidth.
