### ISSUE TITLE
Please publish UI Grid to NPM

### ISSUE THREAD

**Issue by jinder** [angular-ui/ui-grid#3402]
Could you please publish the new UI Grid to NPM?  I can't seem to find it on there at the moment.

**Comment by c0bra** [comment]
We'll take that under advisement. Is there a reason that the bower package doesn't work for you? Would you want just the bower package duplicated to npm or something different?

**Comment by jinder** [comment]
Yes, the existing bower package pushed to NPM should be fine.  An increasing number of front-end projects now publish directly to NPM (http://blog.npmjs.org/post/101775448305/npm-and-front-end-packaging).  [Angular](https://www.npmjs.com/package/angular) and [other Angular-ui projects](https://www.npmjs.com/package/angular-ui-router) now have official NPM distributions too.

Two reasons for me personally: 1) I prefer having just one package manager for all my dependencies 2) we have an internal corporate mirror of the NPM registry, but not one for bower.  I understand this is probably not a concern for others :)

**Comment by andrexx** [comment]
Another reason
http://beletsky.net/2015/04/npm-for-everything.html

**Comment by LoicMahieu** [comment]
+1 Like @jinder I prefer use only NPM as package manager and I was surprised to not found `ui-grid` on NPM as `ui-router` is already in place.
Please publish it with the same convention than `ui-router`: his package name is `angular-ui-router`. (Current [package.json](https://github.com/angular-ui/ng-grid/blob/master/package.json#L2) looks: `ui-grid`)

**Comment by LoicMahieu** [comment]
Workaround is to install via Github: `npm install angular-ui/ng-grid`

**Comment by LoicMahieu** [comment]
Maybe the better way would be to publish https://github.com/angular-ui/bower-ui-grid on npm.

**Comment by PaulL1** [comment]
@c0bra: whilst this might help some people, it's not that it doesn't work with bower.  Will this make our release process longer/more complex, or does it just get automated with the rest and remain largely push button?  If the latter then I guess I'm supportive, but probably not as a high priority.

**Comment by rewiredpictures** [comment]
+1 to this. I echo @jinder sentiments.  I wouldn't think this would make releases any more complex. It's essentially just publishing the same package you do to bower to the npm registry. Also FYI `ui-grid` is still an available on npm. May want to snatch it: https://www.npmjs.com/package/ui-grid

**Comment by theodorejb** [comment]
Hopefully ui-grid can be added to npm as part of the 3.0 release. We use npm exclusively to manage our front-end dependencies, and this is the only dependency that isn't available there.

**Comment by c0bra** [comment]
@rewiredpictures Thanks for the tip. I think we can use the base of the bower repo build task for doing the same thing on NPM.

**Comment by aciccarello** [comment]
+1 for npm publish.

**Comment by tuchk4** [comment]
+1

**Comment by rewiredpictures** [comment]
It looks like this package made it's way into npm. Yay thanks! One problem is that the `main` property in the `package.json` is set to multiple files which is not supported by npm.

**Comment by aciccarello** [comment]
Ah, I see. Its published as [angular-ui-grid](https://www.npmjs.com/package/angular-ui-grid).

And as @rewiredpictures said, the "main" should point to just one file. I think it should point to an index.js file requiring the source code and exporting the name like the angular sub-modules do.

````
require('./ui-grid');
module.exports = 'ui.grid';
````

A "repository" and "bugs" property in `package.json` along with a proper `README.md` would probably be good for viewing on the npm website too.

**Comment by c0bra** [comment]
@aciccarello Thanks for the notes. I'll get this done for the next release. The README, repo and bugs 

- [ ] Use single file for main prop in npm package.json

**Comment by benoror** [comment]
+1 for supporting CommonJS package management!

##### Motivation

I'm in the process of refactoring an app to support modern tooling like Webpack & ES6.

##### Code Change

A small change is needed to support CommonJS:

```
/* commonjs package manager support (eg componentjs) */
if (typeof module !== "undefined" && typeof exports !== "undefined" && module.exports === exports){
  module.exports = 'angular-md5';
}
```

* [ui-router snippet](https://github.com/angular-ui/ui-router/blob/master/release/angular-ui-router.js#L9)
* or [UMD (Universal Module Definition)](https://github.com/umdjs/umd)

I have done PRs for some dependencies I have:

* https://github.com/wix/angular-tree-control/pull/152
* https://github.com/gdi2290/angular-md5/issues/8
  * https://github.com/gdi2290/angular-md5/pull/9
* https://github.com/muratcorlu/angular-urlify/pull/1
* https://github.com/tarkanlar/Angular-Urlify/pull/1

##### Sources

* [Using Angular 1.x With ES6 and Webpack by Jesus Rodriguez](http://angular-tips.com/blog/2015/06/using-angular-1-dot-x-with-es6-and-webpack/)
* [Webpack & Angular by Shawn McKay ](http://www.shmck.com/webpack-angular-part-3/)
* [Angular and Webpack for Modular Applications by @kentcdodds](https://egghead.io/series/angular-and-webpack-for-modular-applications)
* [NPM for Everything](http://beletsky.net/2015/04/npm-for-everything.html)

**Comment by JLLeitschuh** [comment]
There are lots of things that need to be taken care of and not enough developers to go around at the moment. If you know how to make the build better please join us on [gitter](https://gitter.im/angular-ui/ui-grid).
We welcome help making this project better.

**Comment by benoror** [comment]
Just as a note, I was able to include it as Webpack + ES6 with:

```
import uigrid from 'angular-ui-grid/ui-grid.js';
import 'angular-ui-grid/ui-grid.css';

/** ... **/

export default angular.module('app.module.xyz', [
    'ui.grid',
    'ui.grid.autoResize',
    'ui.grid.pagination',
    'ui.grid.selection',
    'ui.grid.edit',
    'ui.grid.rowEdit'
   /** etc **/
  ])
```

**Comment by Avien** [comment]
@benoror I am trying to import ui-grid to my webpack project but I get this error:

 
ERROR in ../app-ui-common/~/angular-ui-grid/ui-grid.ttf?
    Module parse failed: /Users/avi/SVN/afs/app-ui-common/node_modules/angular-ui-grid/ui-grid.ttf? Line 1: Unexpected token ILLEGAL
    You may need an appropriate loader to handle this file type.
    (Source code omitted for this binary file)
     @ ./~/css-loader!../app-ui-common/~/angular-ui-grid/ui-grid.min.css 2:14784-14809

However I do have the proper loader for images and fonts:
 { test: /\.(ttf|eot|svg|otf)$/, loader: "file?" },

Any ideas?
Thanks

**Comment by Avien** [comment]
Solved it
Since I am using the extract-text-webpack-plugin I was missing the file-loader in the extract method:
```javascript
{ test: /\.css$/, loader: ExtractTextPlugin.extract("css","file")}
```

**Comment by JLLeitschuh** [comment]
This is still a problem because travis doesn't do a push automatically yet.

**Comment by icfantv** [comment]
@c0bra - i am still not seeing an `index.js` file in the source or in the package provided by NPM.  would you accept a PR for this?  thanks.

**Comment by Fost** [comment]
+

**Comment by d-amit** [comment]
+1

**Comment by mportuga** [comment]
@icfantv We are definitely willing to accept a PR for this.

**Comment by ManiAmuthan** [comment]
when i tried to import in my Angualr2 component " import * as uiGrid from "angular-ui-grid"; ". i got the below issue. 
      cannot find module 'angular-ui-grid'.

After searching over internet thet suggested me to install "@types/angular-ui-grid" but i got the below issue.
'@types/angular-ui-grid' is not in the npm registry.

is there is any other option to fix this.
My requirement is to create a simple ui-grid using Angular2 and web pack2.

**Comment by icfantv** [comment]
@maniamuthan, please do not hijack threads with your own support requests.  This is considered very poor form.  You would be better served by posting your question to stackoverflow.
