### ISSUE TITLE
wrong position of column menu for the last column

### ISSUE THREAD

**Issue by gboros** [angular-ui/ui-grid#3413]
if the last column is small, the column menu will move to the previos column

![before](https://cloud.githubusercontent.com/assets/767773/7452613/9d5df5a0-f268-11e4-983d-b1c6ceed0c98.png)

I think this is caused by this commit : https://github.com/angular-ui/ng-grid/pull/2629 , if I remove the
margin, it looks as expected

![after](https://cloud.githubusercontent.com/assets/767773/7452645/f5c2fd44-f268-11e4-9273-059ad0967556.png)

**Comment by c0bra** [comment]
1) What exactly are we supposed to be seeing in your screen shots? By "column menu" do you mean the *button* that opens the column menu?

2) Is a grid that narrow even usable? You can't read any columns at all...

**Comment by gboros** [comment]
1) yes, you can see in the first screenshot that it misplaced;
2) well, I used your example to explain the problem, but we actually do have an application
with a small last column, and that is where we see the problem;

**Comment by c0bra** [comment]
Oh OK, I think I see it.  To rephrase, the column header button that opens the drop-down column menu is visually "shifting" to the left when the column is below a certain width.
