### ISSUE TITLE
Add support for multi-column headers (column grouping)

### ISSUE THREAD

**Issue by reflectsoftware-org** [angular-ui/ui-grid#3414]
It would be great to have support for multi-column headers. Perhaps this exists and if so, point me to the documentation or samples showing it. Otherwise here is a working demo from competing product:

http://demos.telerik.com/kendo-ui/grid/multicolumnheaders

Thanks
Callon

**Comment by PaulL1** [comment]
I think a duplicate of #963, also discussed in http://stackoverflow.com/questions/29564283/any-better-approaches-in-achieving-multi-column-grouping-in-ui-grid-header.  It's not overly complex, but there are traps in column moving and resizing once you group columns.

We'd welcome a PR in this area.

**Comment by faris-git** [comment]
Does _**ui-grid**_ supports expanding columns? I couldn't find this feature in documentation. It would be really great if it exist else is it in next future version?

**Comment by subhashkotu** [comment]
@PaulL1 do we have a PR in place for this?

**Comment by raghu185** [comment]
Is this 
http://stackoverflow.com/questions/29564283/any-better-approaches-in-achieving-multi-column-grouping-in-ui-grid-header.
still the best approach to implement grouped column headers in UI Grid.
