### ISSUE TITLE
Add support for multiple aggregationTypes in column footer

### ISSUE THREAD

**Issue by calloncampbell** [angular-ui/ui-grid#3418]
Currently the column footer only support one aggregationType (avg, count, sum, min, max). I want to show more than one. For example I want to show one columnFooterCell with AVG and then another for COUNT. See below for an example:

![image](https://cloud.githubusercontent.com/assets/4095080/7462750/f2a40c7a-f281-11e4-8f1d-bcdc23b2075c.png)

**Comment by PaulL1** [comment]
This is a useful request, but not really in the current roadmap.  We have far too many good ideas in the repository already, giving the impression that we have a project riven with defects.

Accordingly, I am leaving the enhancement tag on this, but closing it.  If someone would like this functionality, we'd welcome a pull request that adds it.
