### ISSUE TITLE
Is there any way to reduce size of dist file?

### ISSUE THREAD

**Issue by iyel** [angular-ui/ui-grid#3421]
Minified file size is ~250 KB and it is just too much. Is there any way to make custom build? Or any advice on this?

for e.g. even angular.min.js size is 123 KB

**Comment by swalters** [comment]
yes, we plan on eventually offering separate .js files based like ui-grid.core.js, ui-grid.cellnav.js, etc.  Just need someone with time to change the grunt build?  Volunteers?

**Comment by sirago** [comment]
Any update on this?

**Comment by yugansh20** [comment]
Any updates??

**Comment by loupiz** [comment]
+1

**Comment by mportuga** [comment]
We have no updates on this as of yet. But pull requests are welcomed.

**Comment by mportuga** [comment]
This was done. I recommend using version 4.4.1.
