### ISSUE TITLE
Grid pager count not fully translated

### ISSUE THREAD

**Issue by fredl11** [angular-ui/ui-grid#3430]
The grid pager count-div is always displayed with the English word "of", e.g. `1 - 25 of 5120 items` or in German: `1 - 25 of 5120 Einträge`.

The not translated code is in line 24224 of v3.0.0-rc.21:

``` html
...<div class=\"ui-grid-pager-count\"><span ng-show=\"grid.options.totalItems > 0\">{{showingLow}} - {{showingHigh}} of {{grid.options.totalItems}} {{totalItemsLabel}}</span></div>...
```

**Comment by PaulL1** [comment]
To fix this we just need to replace `of` with `{{ofLabel}}`, and add code into pagination.js at about line 346 to create the `ofLabel`.  Then put appropriate translations into each translation file.

Are you keen to do a PR that provides this?

**Comment by plel** [comment]
Thanks for the info. I don't have the time right now, so if you want this fixed, please don't wait for my PR. I'll be working on a project that uses the grid later next month again and may try to provide a fix then.
