### ISSUE TITLE
[columnMenu] support for sub-menus

### ISSUE THREAD

**Issue by AgDude** [angular-ui/ui-grid#3433]
This has been discussed a few times in the past, so I am opening a ticket for discussion about what the api should look like. I am most interested in using this on the columnMenu, but it should be implemented on the gridMenu also.

I think the feature is needed for a good implementation of grouping. The column menu gets really cluttered with all of the aggregation options.

**Comment by christrude** [comment]
Something like this would be simple to implement I think. 

menuItems: [{
    title: 'Outer Scope Alert',
    icon: 'ui-grid-icon-info-circled',
    context: $scope,
    subMenuItems: [{
        title: 'Inner Scope Alert',
        icon: 'ui-grid-icon-info-circled',
        action: function($event) {
            this.context.blargh(); 
        },
        context: $scope
    }
}]

**Comment by PaulL1** [comment]
This is a useful request, but not really in the current roadmap.  We have far too many good ideas in the repository already, giving the impression that we have a project riven with defects.

Accordingly, I am leaving the enhancement tag on this, but closing it.  If someone would like this functionality, we'd welcome a pull request that adds it.

**Comment by ajentering** [comment]
@PaulL1 , @AgDude Hi i have tried the same but submenuitems are not displayed , any idea ?

![image](https://cloud.githubusercontent.com/assets/28683141/26032163/ee79372c-38a9-11e7-872f-a5348b0b8d8d.png)

this is want i want to achive:
![image](https://cloud.githubusercontent.com/assets/28683141/26032168/23ecb1d6-38aa-11e7-97af-92bc99bd35a7.png)
