### ISSUE TITLE
[moveColumn] header bounce back when reaching right edge

### ISSUE THREAD

**Issue by sunz7** [angular-ui/ui-grid#3448]
On grid with horizontal scrolling, if we move columns inside of grid, everything is working. But as soon as we drag the header and reach the right edge of grid, the header just bounce back. And we lost it.
Here is a plunker: I tried both rc21 and unstable. 
http://plnkr.co/edit/IUcIXrJ5TVcYuNYABtCB?p=preview

**Comment by cleversonpuche** [comment]
I have the same problem. Waiting for solution...

**Comment by avinashhota** [comment]
Hi, Please let me know, when the fix for the below mentioned issue, would be release and in which version. Looking for a quick reply.

**Comment by mermonkey** [comment]
sorry to just +1, but... +1... same issue here...

**Comment by Faltek** [comment]
Exactly the same problem.

**Comment by avinashhota** [comment]
If possible any work around available
