### ISSUE TITLE
Pinning and navigation issue

### ISSUE THREAD

**Issue by leelakrish** [angular-ui/ui-grid#3459]
When you pin a column in ui-grid the cell navigation selection is not visible after 4th column. 

http://plnkr.co/edit/so8HIWpvrnqdXyr668km

**Comment by PaulL1** [comment]
Are you saying that when you use cell nav and the arrow keys to go to the right, that we lose the cellNav when the grid scrolls?  If so, I don't think that's unique to pinning, it's a current defect with cellNav.

**Comment by leelakrish** [comment]
The First column is pinned to the left, now select the second cell in the first row. Then press right arrow key to navigate to the next column. When you keep navigating to other cells, the cell selection is not visible. the cell selection is not visible only when I pin the column.

**Comment by c0bra** [comment]
@leelakrish Can you try with RC22 and see if it's any better?

**Comment by leelakrish** [comment]
It is still behaving in the same manner how It was working with the older version.

**Comment by mportuga** [comment]
No longer reproducible
http://plnkr.co/edit/WnZPj99xztlZQ4repBMK?p=preview
