### ISSUE TITLE
Using ui-grid inside angular-ui-bootstrap tab

### ISSUE THREAD

**Issue by ComeOutToPlay** [angular-ui/ui-grid#3481]
Hello,

I have three grids, each one in a bootstrap tab. When I click from tab to tab, I can see how the columns are compressed into a small space, and then adjusted correctly.

I am using this style class for the grid:

     .gridTable {
        background: white; 
        width: 100%; 
     }

and this attributes for the grid:

    ui-grid-cellNav ui-grid-resize-columns ui-grid-move-columns ui-grid-pinning ui-grid-selection ui-grid-exporter ui-grid-auto-resize

Here is my example:

http://plnkr.co/edit/73k0n2MzVgZpfUez6VTx?p=preview

I would like to avoid this rendering effect, when changing from tab to tab, and I would like to continue using ui-grid-auto-resize.

Any comment will be appreciated

Fernando

**Comment by ComeOutToPlay** [comment]
Hello.

My mistake was using the grid width with percentages. It works better if the width is fixed in pixels.

    .grid {
      width: 500px;
      height: 400px;
    }

Even though, I observe a rendering effect in the height of the grid, when passing from tab to tab.

Here is my new plunkr:

http://plnkr.co/edit/xrfqAyUai7AyAVehT4am?p=preview

Best regards 

Fernando

**Comment by PaulL1** [comment]
Best practice is to use ng-if on tabs, so the grid only renders when the tab is clicked on.  Some information on this can be found in http://ui-grid.info/docs/#/tutorial/108_hidden_grids

**Comment by ComeOutToPlay** [comment]
Hello Paul,

I tried adding an ng-if and it worked like a charm if each tab is loaded completely when is clicked on. 
But, I want to read the grid information from my backend only once. 

In my new plunker I load each tab info the first time is clicked on, and it works ok if you do not resize. When I resize the navigator, the auto-resize-feature does not help.

So I used jquery to calculate the grid size.

  $(window).resize(function(){

      $scope.$apply(function(){

          setGridSize('grid1', window.innerWidth * 0.94 + 'px');
          setGridSize('grid2', window.innerWidth * 0.94 + 'px');
          setGridSize('grid3', window.innerWidth * 0.94 + 'px');                    
      });

  });  

Here is my new plunkr. It works acceptable, but I did not find a way to solve the small flickr effect  observed at the grid height (even when the I have the grid height fixed). I think it comes from an automatic calculation of height that occurs when the grid is rendered.

http://plnkr.co/edit/COxXmijAIueSVzet17th?p=preview

Thank you very much!!!

Fernando

**Comment by PaulL1** [comment]
Surely you can load the data on page load, and still render the grid when the tab is clicked on?

If you do this: http://plnkr.co/edit/9ZwfHTiPEPJEzAeG9pIJ?p=preview then the flicker goes away.  I've set the size on the parent div, not the grid itself, so it can be set before the ng-if renders the grid.  And I've removed the auto-resize, as it was causing a flicker the third time (?) I went to the grid.  I wonder whether you really need auto-resize, v's just manually detecting a real window size change and calling handleWindowResize (which is all autoResize really does).

**Comment by ComeOutToPlay** [comment]
Hello Paul,

I tested the last plunkr and it happens this to me after resizing the window and clicking on tabs a few times:

![test](https://cloud.githubusercontent.com/assets/5622990/7684009/459a7cf2-fd59-11e4-9d99-9c05a603e8d0.png)

Tomorrow I will continue testing including your suggestions, because I don't really need auto-resize. I can set widths by myself like you did.

Your grid component is really good, and I find a solution for this particular case, I'll let you know.

Thank you for your cooperation!!

Fernando

**Comment by c0bra** [comment]
@ComeOutToPlay did you have any luck? Thanks.

**Comment by ComeOutToPlay** [comment]
Hello @c0bra 

I am using my code as in my previous Plunkr http://plnkr.co/edit/COxXmijAIueSVzet17th?p=preview

I could not find a way to solve this issue.

Fernando

**Comment by ComeOutToPlay** [comment]
I use this workaround

http://plnkr.co/edit/BFUsq0lBvY1N9Y8HjaLA?p=preview

Hope it helps.

Fernando
