### ISSUE TITLE
data with key '(A B)' fails

### ISSUE THREAD

**Issue by lfrohman** [angular-ui/ui-grid#3488]
In the tutorial, 101 Intro to UI-Grid, if I change the Example app.js file to the text below, change the "firstName" to "(A B)", the table fails, nothing appears except the border:
-----
var app = angular.module('app', ['ngTouch', 'ui.grid']);

app.controller('MainCtrl', ['$scope', function ($scope) {

  $scope.myData = [
    {
        "(A B)": "Cox",
        "lastName": "Carney",
        "company": "Enormo",
        "employed": true
    },
    {
        "(A B)": "Lorraine",
        "lastName": "Wise",
        "company": "Comveyer",
        "employed": false
    },
    {
        "(A B)": "Nancy",
        "lastName": "Waters",
        "company": "Fuelton",
        "employed": false
    }
];
}]);

**Comment by PaulL1** [comment]
The way we build the parse for accessing entities doesn't appear to like brackets in an attribute name.  Is there some particular reason you wanted to do this?  It seems somewhat unusual.

**Comment by lfrohman** [comment]
I was using ng-grid to replace an existing table in converting our project
to angular,
and I don't have control over the attributes, they already had parenthesis
and a space. I was able to code a workaround, just wanted to let you know
about the error.
ng-grid is very useful for our project, thanks.

**Comment by hvallee** [comment]
Hi, we're having the same issue. We're importing tables from Wikipedia, and when features titles contain brackets, we've got the same error.
Do you have planned to fix this? If not, what's your advice to avoid that?
It's important that we keep the exact title in data, one way or another.

**Comment by PaulL1** [comment]
You may find that flatEntityAccess fixes this - worth a try.

**Comment by hvallee** [comment]
I had to make some ajustements in the code but flatEntityAccess finally solved my problem, thank you for the tip !!

**Comment by PaulL1** [comment]
Looks fixed, closing.
