### ISSUE TITLE
Pin columns to right?

### ISSUE THREAD

**Issue by roblarsen** [angular-ui/ui-grid#349]
I have a requirement to pin a column to both the right and left of the grid. I'm hoping I can get some insight on the  best way to implement that.

Thanks!

**Comment by quikchan** [comment]
This still not working, i need to pin the last column in my grid, why this is not a feature? I can't understand why this is not implemented..
I tried the @roblarsen  it almost fix my problem, it pinned the right column but the footerTemplate stop working (grid total item counter and pagination).

**Comment by PaulL1** [comment]
There's a simple reason this is not a feature: you haven't coded it and submitted it as a pull request, and nobody else seems to want it as much as you do.

You could try upgrading to ui-grid 3.0, which does have pinning as a feature.
