### ISSUE TITLE
Should not do autoAdjustHeight() when the grid element is auto-resizable by css

### ISSUE THREAD

**Issue by zeodtr** [angular-ui/ui-grid#3500]
On `uiGridDirective`'s `post()` function, `autoAdjustHeight()` is called when the height of the grid element is not sufficient.

But when the grid element is auto-resizable by css, it is unneccessary and even harmful.

An html element becomes auto-resizable when it's css attributes are set as follows (at least for the height):

* position: absolute
* bottom: 0 (or any value)

But since `autoAdjustHeight()` sets the height to a fixed value, the auto-resizability goes away.

So, there should be some guard code to prevent unneccesary `autoAdjustHeight()`.

My suggestion is as follows:

            var autoHeightByCss =
                ($elm.css('position') === 'absolute') &&
                ($elm.css('bottom') !== undefined);
            if ((! autoHeightByCss) &&
                grid.gridHeight < grid.options.rowHeight && grid.options.enableMinHeightCheck) {
              autoAdjustHeight();
            }

I've applied the above code to my project, and it works well.

**Comment by zeodtr** [comment]
Sorry, I didn't see that `grid.options.enableMinHeightCheck` exists.

**Comment by zeodtr** [comment]
But maybe the code I suggested has some value, since it automatically prevents the undesirable effect.

Can it be reached to the main code base?

**Comment by PaulL1** [comment]
@c0bra, do you want to take a squiz and see if this is useful?

**Comment by c0bra** [comment]
@zeodtr The automatic adjustment of height only occurs on grid init though, right? So the grid is not really auto-resizable but it dynamically initiates its height to fit content.  Am I correct?

**Comment by zeodtr** [comment]
@c0bra Let me explain my situation further.

In my case, the ui-grid is placed on a tabbed page that' not initially visible. (It's on the second tab, and the first tab is initially shown) In that case, the (real) height of the ui-grid is 0, since it is hidden. But the ui-grid will be resized automatically to fit that tab when the tab becomes visible, since the ui-grid's css property is { position: absolute, bottom: 0 }.

But the autoAdjustHeight() function intervenes too early (while the tab is not visible and so the actual height of the ui-grid is 0), and set the height to the minimum allowable value, thus disables { bottom: 0 }.

So, autoAdjustHeight() should not be called when the css of the ui-grid is { position: absolute, bottom: 0 (or any value) }.

**Comment by PaulL1** [comment]
The normal form is to use an ng-if on the hidden tab, so that the grid doesn't attempt to render until the user actually clicks on the tab.  This avoids problems of this nature, and has the side effect of making your application more performant (particularly if there is a grid on each tab, you're only rendering the grid that is actually visible).

**Comment by PaulL1** [comment]
Answer given, no response for some months.  Closing.

**Comment by zeodtr** [comment]
Sorry for late response. I thought your suggestion is a workaround, rather than a solution.

In fact, I've done my own workaround. I've replaced 'display: none' with 'visibility: hidden' so the size remains the same regardless of visibility. But ng-if can be used when performance suffers.
