### ISSUE TITLE
Pagination bar icons 

### ISSUE THREAD

**Issue by salarmehr** [angular-ui/ui-grid#3506]
Current css-based icons on pagination bar are not smooth. Why are not glyphs in the ui-grid font  used for them as well?

**Comment by PaulL1** [comment]
Probably because the person who submitted the pagination feature chose not to use them.  Happy to accept a PR to update them.

**Comment by salarmehr** [comment]
@PaulL1  If I update the style to use font-awesome icons, is there any chance you merge the commit?

**Comment by PaulL1** [comment]
Yeah, so long as it's using the fontello setup etc.

**Comment by PaulL1** [comment]
PR doesn't work, and looks to have some MS-specific stuff in it.  Closing, we can reopen if someone wants to do the work to fix the PR.
