### ISSUE TITLE
Tabbing to next cell when editing

### ISSUE THREAD

**Issue by specialjyo** [angular-ui/ui-grid#351]
I have a grid, all cells are editable, I'd like when I press the tab key to move to the next cell in the row, I dont see this ability as a config option, curious of the best way to implement.

**Comment by dsushmasagar** [comment]
Consider the grid width is 400px, and it has four columns. All column width is 100px. then tabbing between columns are working as expected. 

http://plnkr.co/edit/2yMGLTY1L69lGwY7W667 
Similar kind of grid with the same 400 px width. It has 4 columns. But Consider each column has 300px width, then tabbing between columns are not working. It is tabbing out only within the column which are visible on the screen. Please find the plunker here.

http://plnkr.co/edit/HtWt7soGrpGwTtP7khaB
I am not sure why this is happening. I am displaying almost 20 columns in the ng-grid, and would like to implement the tab out to column functionality. But couldn't. Can someone help me on this issue.

**Comment by arunprabhus** [comment]
This is not working in IE - http://plnkr.co/edit/pGUZduChPmG7Pg1AregU?p=preview Please suggest if you have any way to fix it

**Comment by craigeddy** [comment]
@arunprabhus what version of IE are you seeing this in? I just tried your plunk in IE 11 and it seems to be working.

**Comment by arunprabhus** [comment]
@craigeddy IE 11 it is not working go to any of the item listed and use tab 
eg: doubleclick on ID column 1 now it is editable field  now use tabl till address you can see it is working after address you have to double click again to get editable field.
