### ISSUE TITLE
UI-Grid disables all angular-animate animations

### ISSUE THREAD

**Issue by jinder** [angular-ui/ui-grid#3523]
According to the [angular documentation](https://docs.angularjs.org/api/ng/service/$animate), the `$animate.enabled()` function takes the element as the first parameter.  However, in the ui-grid-util.js file, the parameters are the wrong way round for `enableAnimations`/`disableAnimations`.  This results in all animations being disabled when these functions are called.  

Instead, the functions should be:

```
    // Disable ngAnimate animations on an element
    disableAnimations: function (element) {
      var $animate;
      try {
        $animate = $injector.get('$animate');
        $animate.enabled(element, false);
      }
      catch (e) {}
    },

    enableAnimations: function (element) {
      var $animate;
      try {
        $animate = $injector.get('$animate');
        $animate.enabled(element, true);
        return $animate;
      }
      catch (e) {}
    },
```

(I would submit a PR, but a corporate firewall prevents me from doing so).

**Comment by c0bra** [comment]
This is because there's a breaking change in Angular 1.4 that swapped the parameter order.

When we update for 1.4 this will be fixed.

**Comment by ticlaudeberube** [comment]
Was that fixedÉ Because, all animate.css animations are not working ounce the grid is inited.

**Comment by jinder** [comment]
Can confirm that as of v3.0.5 this is now fixed.
