### ISSUE TITLE
Columns to the right of Image Cells disappear while Horizontally Scrolling

### ISSUE THREAD

**Issue by JLLeitschuh** [angular-ui/ui-grid#3527]
Plunker demonstrating bug:  http://plnkr.co/edit/WhyKGn

System specs: Chrome 42.0.2311.152 (64-bit) on MacBookPro running OSX Yosemite

As you scroll to the right in this example you'll notice that the columns on the left start disappearing.
This seems to be related to how the headers that are disappearing are shortened and using ellipses. If you change the column width so that the column header names are no longer shortened (ie set `dataElementsAfterImagesWidth = 75`) the problem disappears.

**Comment by PaulL1** [comment]
Looks like there's something busted in virtualisation to me.  @swalters, @c0bra - have you seen this before?  Broadly speaking it looks to me like the virtualisation window is being miscalculated, so some visible columns aren't actually there.
