### ISSUE TITLE
Where's the documentation for headerRowTemplate ?

### ISSUE THREAD

**Issue by RichardAlan** [angular-ui/ui-grid#353]
I noticed there seem to be a few places in the config document where you refer to the following:

"See github wiki for more details"

However when I check the wiki I cannot find anything. Also in the config options there are many links in the right hand column but none seem to link to examples. I'm very interested to use some of these options but wish they were documented. Without documentation then they are not really usable :-(

**Comment by daviskoh** [comment]
+1

**Comment by bborowin** [comment]
@c0bra the link you provided 404's - is there a new place where the documentation can be found?

**Comment by c0bra** [comment]
@bborowin Sorry, 2.x code got moved to its own branch. It's here now: https://github.com/angular-ui/ng-grid/blob/2.x/src/templates/headerRowTemplate.html
