### ISSUE TITLE
Filter input validation

### ISSUE THREAD

**Issue by streamnsight** [angular-ui/ui-grid#3554]
RC21 unstable release:
Filter Input dialog box does not seem to be typed with the column type
for example if I have a column of type="number", the input field is still a field of type'"text".

Input validation behavior (green / red cues) fails.
How to force the filter input to be of the same type as the column type?

**Comment by PaulL1** [comment]
This isn't functionality we currently have. However, you can build custom filter directives, and use any widget type that you wish.

**Comment by streamnsight** [comment]
I ended up modifying the type="" line in the code that was hard coded to "text" to account for type.

**Comment by imbalind** [comment]
I'm closing since it's solved by custom template.
