### ISSUE TITLE
Expanded Grid and IE error

### ISSUE THREAD

**Issue by pjlasl** [angular-ui/ui-grid#3558]
We recently added the expandable functionality to our grid. Love it! I am seeing one peculiar thing with IE (and only IE). When the grid is expanded the following message is thrown in the console.
TypeError: Unable to get property 'on' of undefined or null reference
   at Anonymous function (http://localhost:8080/fw/lib/ui-grid-unstable.min.js:11:13908)
   at Anonymous function (http://localhost:8080/fw/lib/ui-grid-unstable.min.js:7:19722)
   at $emit (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular.min.js:127:424)
   at Anonymous function (http://localhost:8080/fw/lib/ui-grid-unstable.min.js:7:20713)
   at renderingComplete (http://localhost:8080/fw/lib/ui-grid-unstable.min.js:7:16948)
   at post (http://localhost:8080/fw/lib/ui-grid-unstable.min.js:6:30944)
   at Anonymous function (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular.min.js:70:132)
   at $ (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular.min.js:70:197)
   at B (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular.min.js:59:255)
   at Anonymous function (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular.min.js:66:231) 

It does not impact anything. The expanded grid is displayed along with the content, but the message is thrown every time. Any ideas?

**Comment by PaulL1** [comment]
It sounds like it's trying to register an event handler (so something like grid.api.core.on.xxxxx), and the thing it's trying to register on doesn't exist.  That could often mean a feature wasn't enabled but we're trying to listen on it.  Funny that it's IE only, perhaps a timing issue.

If you use the unminified version, and then work out which line of code it is that throws the error, then it should be reasonably easy to diagnose.

**Comment by pjlasl** [comment]
Thanks for the feedback. I'll see if I can pull down the unminified code and figure it out.

**Comment by c0bra** [comment]
@pjlasl did you have any luck?

**Comment by PaulL1** [comment]
Information sought, no response for some months.  Closing.

**Comment by zendu** [comment]
I see the same issue. Issue is in anonymous function, so unminified version also does not help.

            $scope.gridOptions = {
                paginationPageSizes: [10, 25, 50, 100],
                paginationPageSize: 10,
                enableSorting: true,
                onRegisterApi: function (gridApi) {
                    $scope.gridApi = gridApi;
                },
                enableHorizontalScrollbar: uiGridConstants.scrollbars.NEVER,
                enableVerticalScrollbar: uiGridConstants.scrollbars.NEVER,
                minRowsToShow: 0,
                enableColumnMenus: false
            };

My controller gets columns from another call. that call populates columnDefs and at the end calls notifyDataChange(). This is where null reference exception is thrown.

            // add each visible field as column in UI Grid
            $scope.visibleFields.$promise.then(function (visibleFieldsResponse) {
                $scope.gridOptions.columnDefs = [];
                angular.forEach(visibleFieldsResponse, function (visibleField) {
                    $scope.gridOptions.columnDefs.push({
                        name: visibleField.systemLabel,
                        field: visibleField.fieldId,
                        enableSorting: true
                    });
                });

                // notify grid of column change event
                $scope.gridApi.core.notifyDataChange(uiGridConstants.dataChange.COLUMN);
            });
