### ISSUE TITLE
Translation of custom menu items

### ISSUE THREAD

**Issue by cedejic** [angular-ui/ui-grid#3562]
Hi,

I am using angular translate and am trying to translate custom menu actions. I can translate all the grid columns as it is supposed to be. I've noticed in ui-grid-menu-button.js in method setMenuItemTitle you are translating only column titles with use of gridMenuTitleFilter (as promise).
Shouldn't gridMenuTitleFilter be used for all menu items? Could you please help me and tell me how can I translate custom menu items' names dynamically?

**Comment by PaulL1** [comment]
Can you not translate the title before you provide it to the grid, perhaps by using `$translate.instant`?  I didn't apply the filter to custom menu items because I thought that people already had control of the titles.

**Comment by cedejic** [comment]
Hi Paul, thank you for your reply. I did what you suggest, but that is only one time deal. Language in the app can be changed dynamically, so if menu title translation is supplied when creating custom menu item, and then language is changed, the translation remains the same. If gridMenuTitleFilter translated all menu items (columns + custom), everything would be fine. When language is changed, column names and menu column names are immediately translated which is perfect. Custom menu items' titles remain the same.

**Comment by PaulL1** [comment]
ui-grid doesn't currently support dynamic language translation.  Refer #1583.

The best workaround at present would be to put the grid inside an ng-if, then toggle the ng-if off (which would destroy the grid), wait for a $timeout(0), then toggle the ng-if back on.  That should pick up the new language.

**Comment by cedejic** [comment]
Currently, everything is dynamically translated except custom items. So if I change language, column menu items ('col:' + columnName) are translated in grid, but custom items remain the same. If custom items were reachable by gridMenuTitleFilter I believe it would all be dynamically translated. Anyway, I will try out your suggestion. Thank you for your help.

**Comment by c0bra** [comment]
@cedejic Any luck solving your issue?

**Comment by cedejic** [comment]
Hi c0bra,

sry for not answering before, did not have any luck with this. I still believe gridMenuTitleFilter would be the best way to translate all menu titles.

**Comment by c0bra** [comment]
@PaulL1 @cedejic So should we close this for now as #1583 covers dynamic changes?

**Comment by PaulL1** [comment]
On the tutorial http://ui-grid.info/docs/#/tutorial/104_i18n the column menus are not dynamically translated - changing the language does not change the menus.  Are you sure your column menus are changing?

It wouldn't be huge to change custom items to use the filter, so I'll do it, but I doubt it will solve your overall problem.

**Comment by cedejic** [comment]
I am trying to translate grid menu items, in which there are column names. They are changed dynamically, as are headers in columns.

Here is an example http://plnkr.co/edit/nnBaepUGnpZbIEEz6Gsn?p=preview. By default it is in german. Please open grid menu and you will see 2 custom menu items (randomly wrote "QR drucken" and "Optionen") and all the headers that appear in the grid. Then click "QR drucken" and you should get alert with the message "QR drucken".
If you change language to english, all headers in grid and grid menu are translated. 2 custom menu items are not translated, but if you click on them alert will show translated messages. I needed to translate those 2 custom actions.

So I guess those custom menu items can not be translated dynamically as column headers are. 
@c0bra you can close this issue if you want. Thank you both for your time and help.

**Comment by vinjenzo** [comment]
I needed to translate on the fly (without page refresh) those custom menu items such as "sort ascending" or "hide column" as well as "items per page" and such in the pager.

I wrote an hack/workaround directly in the source code so sharing if it might help.


first at grid definition a new event to handle language changed on the fly (for example via _angular dynamic locale_):


```
              onRegisterApi: function(gridApi) {

                gridApi.registerEvent('language', 'changed');
                 gridApi.language.on.changed($scope, function(language) {

                       $rootScope.$gridLanguage = language;

                  });
```


then in a controller after language changed raise that event (in my case on $localeChangeSuccess from _angular dynamic locale_)  :

```

            $scope.$on('$localeChangeSuccess', function (e, locale) {

                $scope.$View.GridApi.language.raise.changed(locale);

            });
```


and here the hacks, where the texts need a refresh, for example adding in **uiGridColumnMenu** directive link function:

      $scope.$watch('$parent.$root.$gridLanguage', function () {
          if ($scope.$parent.$root.$gridLanguage !== undefined) {
              $scope.menuItems = uiGridColumnMenuService.getDefaultMenuItems($scope);
          }
      });

or the same for **uiGridPager**

```
          $scope.$watch('$parent.$root.$gridLanguage', function () {

              if ($scope.$parent.$root.$gridLanguage !== undefined) {
                  $scope.sizesLabel = i18nService.getSafeText('pagination.sizes');
                  $scope.totalItemsLabel = i18nService.getSafeText('pagination.totalItems');
                  $scope.paginationOf = i18nService.getSafeText('pagination.of');
                  $scope.paginationThrough = i18nService.getSafeText('pagination.through');
              }

          });
```

**Comment by deepakvidhate** [comment]
hi vincenzo.  i have done the suggested code to translate menu items.  i can see in the console that the translation text for the appearing.  I am facing issue as the text is stuck to english on the grid on the page. please could you suggest
Thanks
