### ISSUE TITLE
Editable subgrid does not work

### ISSUE THREAD

**Issue by knptl33** [angular-ui/ui-grid#3563]
I need functionality same as grid cells like on double click editing functionality for subgrid columns.

I have tried enableCellEdit: true feature for subgrid but its not working for subgrid its working only for grid columns.

i have tried using expandableRowScope for use of scope in subgrids but its not working how can i inherit grid editing functionaity for subgrid ?

If there is subgrid editing is not available and want to make it that way what are the steps should be taken please advice.

Please help me I'm trying to solve this for hours and in the thread there is no working full example :(

thanks.

**Comment by PaulL1** [comment]
You'd need to provide a plunker showing what you've done so far so that people can contribute.  I'd suggest it's most likely that you haven't included the edit directive on the subgrid template, but I can't be sure without seeing it in a plunker.

**Comment by PaulL1** [comment]
Information sought, no response for some months.  Closing.
