### ISSUE TITLE
CellNavigation broken in latest unstable master

### ISSUE THREAD

**Issue by therealtomas** [angular-ui/ui-grid#3589]
CellNavigation works fine for me in   \* ui-grid - v3.0.0-rc.21 - 2015-04-28, but in latest unstable  \* ui-grid - v3.0.0-rc.21-baaf1c0 - 2015-05-25, navigation with arrowkeys doesnt work, also console outputs:
TypeError: uiGridCtrl.focus is not a function

    at module.directive.compile.post (http://localhost:9000/bower_components/angular-ui-grid/ui-grid.js:13409:40 <> )

**Comment by PaulL1** [comment]
Is this related to #3536?  Do you have this issue in the tutorials?

**Comment by therealtomas** [comment]
Yes it seems related to #3536

**Comment by goleafs** [comment]
same issue here, this occurs when using 
ui-grid-edit
ui-grid-row-edit

Object doesn't support property or method 'focus' Error Details: <div class="ui-grid-viewport ng-isolate-scope" ng-style="colContainer.getViewportStyle()" ui-grid-viewport="">

**Comment by Daiverspb** [comment]
When                            ui-grid="gridOptions"
                                     ui-grid-auto-resize
                                     ui-grid-edit
is no errors, but add 
                                     ui-grid-cellnav
and show errors:
TypeError: uiGridCtrl.focus is not a function
    at module.directive.compile.post (/ui-grid.js:13539:26)

**Comment by bmatto** [comment]
+1

**Comment by danielmiller-nl** [comment]
I believe this is fixed as of 3.0.6 (and possibly earlier).
