### ISSUE TITLE
IE9 - header column widths different than body on Filtering tutorial

### ISSUE THREAD

**Issue by c0bra** [angular-ui/ui-grid#3593]
Here's an example. Note company header is wider than its columns in the body.

![Example](http://i.imgur.com/LaZj6bu.png)

**Comment by kolesnik** [comment]
similar issue was reported in #3342

**Comment by kolesnik** [comment]
is it connected with IE9 handling of cell CSS "box-sizing: border-box;" ?

**Comment by MaksimSimkin** [comment]
Any ideas how it could be  solved?

**Comment by mportuga** [comment]
Removed IE9 support.
