### ISSUE TITLE
Smoother scrolling through clusterize

### ISSUE THREAD

**Issue by ruhley** [angular-ui/ui-grid#3598]
[Clusterise.js](http://nexts.github.io/Clusterize.js/) has a much smoother scrolling than ui-grid. Maybe it could be implemented in the future.

**Comment by c0bra** [comment]
Clusterize apparently does the same thing we do: virtualization.  It's probably just that UI-Grid does a lot more than just show rows. There's a bunch of extra API behind it, which increases memory load.

There may be some improvements in Clusterize's virtualization code, though.

**Comment by PaulL1** [comment]
This is a useful request, but not really in the current roadmap.  We have far too many good ideas in the repository already, giving the impression that we have a project riven with defects.

Accordingly, I am leaving the enhancement tag on this, but closing it.  If someone would like this functionality, we'd welcome a pull request that adds it.
