### ISSUE TITLE
Footer Aggregates only calculate for current page when using Pagination

### ISSUE THREAD

**Issue by JLLeitschuh** [angular-ui/ui-grid#3599]
For example if you use `aggregationType: uiGridConstants.aggregationTypes.sum` on a numerical column and also have pagination enabled the aggregate is only calculated for the page that is viewable.
Instead it should calculate the aggregates for the entire dataset.
Example (I modified the existing pagination demo in the documentation):
http://plnkr.co/edit/L8X5ak?p=preview

**Comment by PaulL1** [comment]
In general I've always believed the key use case for pagination is with server side paging.  And aggregation cannot calculate on the full data set if some of it is still on the server.  Arguably it could be done for client side paging, but I'm not sure it makes sense to do so.

In general the rule for aggregation is that it aggregates the **visible** data, and when data is off page it isn't visible.

**Comment by JLLeitschuh** [comment]
Wouldn't the expectation be that if you are using the default client side aggregation that you have the entire dataset. Since the built in aggregation simply won't work if some of your data is server side isn't the expectation that the dev would have to add their own custom aggregate calculator?
As such, shouldn't the built in functionality work with the entire data set that it knows about by default?

**Comment by PaulL1** [comment]
By that logic, we'd aggregate the full set even when some of the data is filtered out?  The current intent and implementation is that aggregation aggregates the currently visible rows.  Pagination works by making some of the rows invisible.

**Comment by JLLeitschuh** [comment]
No. Because a filter is applied to reduce the amount of data so you can see a summary of that filter's application. Paging can be applied for a variety of different reasons that have nothing to do with this.
Two examples:
- Accessibility: Even if you could have the entire grid loaded on the page you may not want to have all 10k rows because it makes the page much harder to work with on a screen reader.
- Avoiding scrollbars: If you want a fixed height grid and don't want to have a scrollbar, instead you want paging.

**Comment by PaulL1** [comment]
Yes, but the point is that this is all applied with rowsProcessors.  Aggregation doesn't know why the rows are invisible, just that they are.  There is some capability with "visibilityReason" that I added at one point to know why a row is invisible, but that's not currently implemented in core - it's only used on user driven hiding.

**Comment by JLLeitschuh** [comment]
Right. I understand why the page is doing it. What I'm saying is that the functionality should be different.

So how does the grid know whether to make an element visible if you are removing a filter and you have pagination on. When you remove a filter then the pagination hiding is still there so there hast to be some sort of mechanism in place to determine if an element is being filtered out.

**Comment by PaulL1** [comment]
Pagination is a rowsProcessor, it re-runs all the rowsProcessors whenever you change a filter.

I'm not saying it perhaps wouldn't be nice to be different.  I'm just saying the way it's built right now it would be quite hard, and I think it works for some people's use cases (i.e changing it might result in some people saying "that's not what I expected").

**Comment by mportuga** [comment]
Is it possible to at least add a toggle? I mean, his pull request already gives you the ability to aggregate the entire data set if you have it available. Then why not take advantage of it? We could have both. That way if a user only wants to only sum the current page for server side paging then they can use your current implementation of it, but if they have all the data locally and are just trying to avoid a scrollbar, they can select JLLeitschuh's aggregation service.

**Comment by JLLeitschuh** [comment]
I could probably add this as a PR at some point after I'm done with accessibility. However it'll have to be on my backlog until I get that done.

**Comment by timstuyckens** [comment]
+1

**Comment by PaulL1** [comment]
This is a useful request, but not really in the current roadmap.  We have far too many good ideas in the repository already, giving the impression that we have a project riven with defects.

Accordingly, I am leaving the enhancement tag on this, but closing it.  If someone would like this functionality, we'd welcome a pull request that adds it.

**Comment by HarpoMarx69** [comment]
Had the same requirement and solved it with this custom aggregation function in columnDefs:

```
aggregationType: function ()
{
	if(!self.gridApi)
		return 0;
	var sum = 0;
	for (var i = 0; i < self.gridApi.grid.rows.length; i++) {
		sum += self.gridApi.grid.rows[i].entity.sumTotal;
	}
	return sum;
},
```
This calculates with all filtered rows even of invisible rows of other pages.

**Comment by bmcilw1** [comment]
Thanks @HarpoMarx69! That worked for me. If you're trying to do this over multiple columns simply add additional parameters to grab the current column name for where you have sumTotal

**Comment by likaiwalkman** [comment]
@HarpoMarx69 's solution works! If you still want to keep pagination and filter functionality working well.
You should use gridApi, visibile is the judgement to tell you if the row is filtered or not. :+1:
