### ISSUE TITLE
angular ui-grid v3.0.0-RC.18 remaining columns to resize after column width is resized manually

### ISSUE THREAD

**Issue by dhollan7** [angular-ui/ui-grid#3611]
After resizing a coulmn to be smaller I want the remaining columns to adjust their width to take up the entire space of the grid. There should never be any white space. How do I achieve this behavior?

The behavior I want is on this demo from ui-grid:
http://ui-grid.info/docs/#/api/ui.grid.resizeColumns.directive:uiGridColumnResizer

Currently when I resize a column all columns maintain their size an the right side of the grid has white space.

**Comment by c0bra** [comment]
That would need to be an enhancement to the resizing feature, and not one that everyone would want so it would need to be toggle-able. If you're interested in attempt a pull request or maybe discussing it in the gitter channel that would be a good next step.

**Comment by JLLeitschuh** [comment]
This is a problem experienced with autoResizing as well.
