### ISSUE TITLE
Custom/Dynamic Column Names?

### ISSUE THREAD

**Issue by dereklin** [angular-ui/ui-grid#3613]
Here is my plunker: http://plnkr.co/edit/rgBFkIbkrQlhwQRlbSnV?p=preview

In my app.js, on line 19, imagine all my columns are dynamic.  The column names can change on each page load.  What is the best way to create custom column names?

I can always parse the data before setting up the gridOptions.  But I don't want to do that if there is an easier way.

**Comment by PaulL1** [comment]
Usually if you just don't provide column defs then it will automatically assign names based on the data.  But if you want to control things like column widths and settings then yes, you need to create columnDefs and therefore you need to parse the data to create them.  http://plnkr.co/edit/H85baBjyTsxWZHjZpINU?p=preview

**Comment by dereklin** [comment]
Actually, in my particular use case, the server is returning the column names in the first row.
Like this:
http://plnkr.co/edit/gDf2Buh1dVZD2nFyfQtY?p=preview

Should I just prepare the data before setting the gridOptions?

**Comment by c0bra** [comment]
@dereklin Yes you'll need to set up the column names before you define your grid options.

There's no deep watch on the `columnDefs` so if you just internally change properties the changes won't be reflected in the grid.
