### ISSUE TITLE
how to install `ng-grid-flexible-height` with bower?

### ISSUE THREAD

**Issue by anthonyettinger** [angular-ui/ui-grid#3614]
How do I install `ng-grid-flexible-height` with bower?

**Comment by c0bra** [comment]
You probably can't, and it's unlikely that you'll be able to in the future.

With UI-Grid, though, any features set up in their own repos will be available as bower packages.

**Comment by AgDude** [comment]
This issue was moved to angular-ui/ng-grid-legacy#7
