### ISSUE TITLE
Ng-grid support for newer Angular versions

### ISSUE THREAD

**Issue by thvd** [angular-ui/ui-grid#3617]
Will Ui-Grid get support for Angular 1.3.x and 1.4.x? Because the bower.json still 'advices' me to use Angular ~1.2.16. That being said, Angular just released 1.4.0. I also checked the [angular-1.3](https://github.com/angular-ui/ng-grid/labels/angular-1.3) label, but there are no outstanding issues. So, the question is, is there any reason to recommend 1.2.x as there are already 2 newer minor versions?

**Comment by PaulL1** [comment]
ng-grid or ui-grid?  For ng-grid, the short answer is probably no - there's nobody actively working on upgrading the angular support level.  Although if someone submitted a pull request with any necessary fixes, it would probably be accepted.

If ui-grid, then it does already support 1.3.

**Comment by thvd** [comment]
Sorry, I meant Ui-Grid. Nice to hear that Ui-Grid does support 1.3! So we can upgrade the Angular version in Bower.json to `>=1.2.16 <= 1.3.x`. And how about support for the new Angular 1.4.0 version?

**Comment by PaulL1** [comment]
Current support is documented in http://ui-grid.info/docs/#/tutorial/100_preReqs.  1.4 isn't on there yet, and I'm not aware whether anyone has tried 1.4.  You could be the first to try though.  :-)

**Comment by thvd** [comment]
See #3618 for a pull request to allow users install Ui-Grid with Angular 1.3.x.

**Comment by benoror** [comment]
A quick glimpse at [docs.angularjs.org/guide/migration](https://docs.angularjs.org/guide/migration) doesn't seem to break anything fundamental.

Actually my biggest blocker for upgrading is [AngularUI Bootstrap](https://github.com/angular-ui/bootstrap/issues/3633#issuecomment-105909927)

**Comment by tuhoojabotti** [comment]
I'm using Angular 1.4 with ui-grid and it works like a charm.

**Comment by benoror** [comment]
So far seems to work for me also, what is pending?

**Comment by wesleycho** [comment]
Closing, as this does not seem to be an issue - if there is a 1.4 issue, please open a separate issue with the requisite details/reproduction.

**Comment by RbkGh** [comment]
I tried with 1.4.9 and the rendering is problematic with the column names.
