### ISSUE TITLE
dynamically calculate height of the grid not working

### ISSUE THREAD

**Issue by aimeehwang** [angular-ui/ui-grid#3622]
I am trying to set the grid height based on the grid rows. The height seems have been set successfully given the grid border. But the grid content is only showing the first 4 rows. And this only happens when there is more than 30 rows(not a exactly number).

I made a plunker based on my code, the only difference is my actual project is repeatedly showing all the grids and plunker has only 2 grids. 

http://plnkr.co/edit/xK99JEMqsT7cxz8m4LxT?p=preview
In this plunker, 2 grids are using the same way of calculating and setting heights but the first one rendered fine and the second one looks like the content is truncated.

**Comment by Jacquelin** [comment]
Hi 

Try this plnkr : http://plnkr.co/edit/GBZ97xVcWI3ZV6bk1Ick?p=preview
It's seem working, but it's really low to show. the trick is to set the height in the onRegisterApi callback

**Comment by DmitryEfimenko** [comment]
@Jacquelin Am I wrong to say that this approach basically disables virtualization and thus might have negative performance impact?

**Comment by Jacquelin** [comment]
@DmitryEfimenko , You are right. Ui-grid is made to manage virtualization. There is no good solution to calculate the height. It's just a trick :)

**Comment by derekm** [comment]
We are currently using ui-grid in a similar manner, and we'd like to conquer the performance issues of re-drawing a ui-grid as large datasets are swapped in & out.
