### ISSUE TITLE
In continuation to Issue #3547.

### ISSUE THREAD

**Issue by shrameec** [angular-ui/ui-grid#3626]
I just mentioned the way my data is and asked what all changes I need in this code to get my requirement implemented.

As mentioned in very beginning I had added below code to my js

for(i = 0; i < data.length; i++){
data[i].lastChangeTimestamp = Date(data[i].lastChangeTimestamp);

and this was returning date of below format and then UI-Grid is unable to sort the data on the complete grid:

data[i].lastChangeTimestamp = Date(data[i].lastChangeTimestamp);
data[i].lastChangeTimestamp =Fri May 22 2015 09:50:51 GMT+0530 (India
Standard Time)

I have updated the plunker also with the same.
http://plnkr.co/edit/eas5mPb7Yd9phHEazs0D?p=preview
Please check now.

**Comment by c0bra** [comment]
Your plunker is throwing an error: `ReferenceError: data is not defined`.You need to define data before you use it.

**Comment by shrameec** [comment]
plunker has been updated

**Comment by c0bra** [comment]
@shrameec Looks like that's not a grid issue. You need to do `new Date(...)` rather than just `Date(...)`.

**Comment by shrameec** [comment]
I have tried even that but still remains the same.
Can you please check?

On Tuesday, June 2, 2015, Brian Hann <notifications@github.com> wrote:

> @shrameec <https://github.com/shrameec> Looks like that's not a grid
> issue. You need to do new Date(...) rather than just Date(...).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui/ng-grid/issues/3626#issuecomment-107998189>
> .
>


-- 
Thanks,
Shramee

Please don't print this e-mail unless you really need to.

**Comment by shrameec** [comment]
Facing this in plunker only and not in my actual code.

On Tuesday, June 2, 2015, shramee chopra <shrameechopra@gmail.com> wrote:

> I have tried even that but still remains the same.
> Can you please check?
>
> On Tuesday, June 2, 2015, Brian Hann <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> @shrameec <https://github.com/shrameec> Looks like that's not a grid
>> issue. You need to do new Date(...) rather than just Date(...).
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/angular-ui/ng-grid/issues/3626#issuecomment-107998189>
>> .
>>
>
>
> --
> Thanks,
> Shramee
>
> Please don't print this e-mail unless you really need to.
>
>

-- 
Thanks,
Shramee

Please don't print this e-mail unless you really need to.

**Comment by c0bra** [comment]
1. The plunker hasn't been updated with `new Date`.
2. When I put in `new Date` I find that I can sort the date column just fine.
