### ISSUE TITLE
Searching filtered data

### ISSUE THREAD

**Issue by Penetrator80** [angular-ui/ui-grid#3627]
I use ng-grid 2. Why searching the data takes place only on the page, but not in all  records? how to avoid it?

**Comment by PaulL1** [comment]
It's not at all clear what you mean.  If you mean only data available to the grid, then the grid can only search what it can see.  If you're running some sort of paging with data on the server, then the grid cannot search data that's on the server.

**Comment by Penetrator80** [comment]
I mean that grid reads all data. but search only data which are provided on page. it is bad

**Comment by c0bra** [comment]
Do you mean that you're using paginagtion and filtering and when you apply a filter it only filters the data on the current page, rather than on the entirety of the grid's data?

**Comment by Penetrator80** [comment]
Yes, Boss! in 3rd version is this issue too?

**Comment by PaulL1** [comment]
In 3.0 it filters before it does pagination, so if all the data is on the UI, it should page the data after filtering.

**Comment by c0bra** [comment]
We'll take a PR for this against the 2.x branch but other than that a fix is not likely.

**Comment by AgDude** [comment]
This issue was moved to angular-ui/ng-grid-legacy#6
