### ISSUE TITLE
displayName of empy string defaults to field property name

### ISSUE THREAD

**Issue by c0bra** [angular-ui/ui-grid#363]
e.g.

```
{ displayName: '', field: 'id' }
```

Will show "id" instead of nothing for the column header row. column.js should probably check that displayName is undefined for using the field property, rather than just this || switch:

```
self.displayName = colDef.displayName || colDef.field;
```

**Comment by Wangchengchao** [comment]
ui-grid colDef.name or colDef.field property is required
