### ISSUE TITLE
Grouping: change grouping order with move columns

### ISSUE THREAD

**Issue by AgDude** [angular-ui/ui-grid#3632]
It would be nice to let users change the order of grouping by dragging the columns. Consider this example which is currently a bit of  pain for the user:

* Grouped on three columns
* Inadvertently removed grouping on the first (or just wanted to look at it and changed my mind)
* To regroup in the same order, I need to remove all of the grouping and re-group all three columns in the same order I had before.

**Comment by PaulL1** [comment]
This is a useful request, but not really in the current roadmap.  We have far too many good ideas in the repository already, giving the impression that we have a project riven with defects.

Accordingly, I am leaving the enhancement tag on this, but closing it.  If someone would like this functionality, we'd welcome a pull request that adds it.

In this particular case, it's reasonably clear that we're bad at building drag and drop logic - refer column move as an example.  So probably not likely to be successfully implemented any time soon.
