### ISSUE TITLE
Right most columns moves to the next row Mozilla Firefox ESR

### ISSUE THREAD

**Issue by rameshsubramania** [angular-ui/ui-grid#3638]
Example below
http://plnkr.co/edit/9gkr2NkGpdyEdG6oV1Fs?p=preview

**Comment by c0bra** [comment]
I downloaded Firefox ESR 38.0.1 and tried your plunker and it looks fine to me.

Can you post a screenshot of what it looks like to you?

**Comment by rameshsubramania** [comment]
You are using the latest version probably that's why your are not able to see this issue my version is 24.6.0. PFA the screenshot I do understand you will not be able to help me much with backward compatability let me know if you can do something about it.
![grid](https://cloud.githubusercontent.com/assets/6197412/7943856/502bd610-0935-11e5-9a04-b3ff3f391cd1.PNG)

**Comment by c0bra** [comment]
I would suggest skimming the Firefox release notes and see if there were rendering/flow changes between 24.6.0 and the latest that affect borders, margins, positioning, etc.

**Comment by rameshsubramania** [comment]
My organization upgraded the browser to 38.1.1 and the grid works great here thanks.
