### ISSUE TITLE
3.0 rc21 doesn't support RequireJS Minifying

### ISSUE THREAD

**Issue by DieterLi** [angular-ui/ui-grid#3651]
I package the production distribution with RequireJS minifying, but found error 

```
Error: ENOENT, no such file or directory '[Project Path]/target/web/rjs/build/javascripts/ui-grid.js'. 
```

In my requirejs config they are following:

```
    paths: {
        'ui-grid': '../bower_components/angular-ui-grid/ui-grid.min'
    },
    shim: {
        'ui-grid': {
            deps: ['angular']
        }
    }
```

I'm using bower to manage all js packages. And the reference is pointing to the min.js file, but the error was with normal js file.

So I think RequireJS doesn't treat ui-grid js as a requirejs module. 

The project is built on Playframework(Scala) and RequireJS processing with sbt-rjs.

Currently, I have to manually copy the ui-grid.min.js to the javascripts folder alone with the requirejs main js file, which works fine with both of local environment and production distribution.

**Comment by c0bra** [comment]
I don't use RequireJS so this may be a silly question, but does it matter that you're using `ui-grid.min` and not `ui-grid.min.js` in your `paths`?

**Comment by DieterLi** [comment]
@c0bra RequireJS treats js files reference in a module management way. It take every referred js file as a module, not just a path reference, and every js file needs to be compatible with AMD, which can avoid the asynchronous loading missing for dependent js files.

As to js file path reference, it's almost okay, but sometimes it will fail when the ui-grid js loaded before angularjs file. While by RequireJS, such kind of issue won't happen.

So if ui-grid js file can be RequireJS compatible, it would be very great.

**Comment by myGitHubForum** [comment]
Yes. I would agree with DieterLi. 

I am also trying to configure using the requirejs but it is failing to load the module. 
When I try to add it to html file directly instead of requirejs it is throwing an error that angular is not loaded before ui-grid as the angular is configured inside main.js (requirejs) file.
