### ISSUE TITLE
Horizontal scroll bar positioning below footer

### ISSUE THREAD

**Issue by mehakjain** [angular-ui/ui-grid#3653]
Hi, 
Is there any way to move horizontal scroll bar from view port to render container in ui-grid?? Basically I want to move my horizontal scroll bar below footer.

**Comment by PaulL1** [comment]
No, this isn't currently possible.

**Comment by samsmithnz** [comment]
I'd like to be able to have the horizontal scroll bar below the footer too. I think it looks visually strange to have the scroll above the footer.

**Comment by PaulL1** [comment]
This is a useful request, but not really in the current roadmap.  We have far too many good ideas in the repository already, giving the impression that we have a project riven with defects.

Accordingly, I am leaving the enhancement tag on this, but closing it.  If someone would like this functionality, we'd welcome a pull request that adds it.
