### ISSUE TITLE
Persian Support / UTF-8 & Some UI Issue

### ISSUE THREAD

**Issue by deadmann** [angular-ui/ui-grid#3654]
I Have issues regarding following images....
1. with viewing, when i use css file it display it with empty button, and when i use min.css file it use some random Japanese char
2. export using pdf feel empty, but as i selected part of image you can see it's only encoding issue
3. csv convertor doesnt support persian either, even with exporterOlderExcelCompatibility: true, option.
![csvexport](https://cloud.githubusercontent.com/assets/1919241/7912036/5668f284-0853-11e5-9c23-ef00f41d2d89.png)
![html](https://cloud.githubusercontent.com/assets/1919241/7912037/566f0dea-0853-11e5-8b13-ee791c8b8bc8.png)
![pdfexport](https://cloud.githubusercontent.com/assets/1919241/7912039/567bd7fa-0853-11e5-9d29-3b9d8d147200.png)
![view-min-css](https://cloud.githubusercontent.com/assets/1919241/7912038/567acaea-0853-11e5-9d1b-e057d25e4312.png)
![view-css](https://cloud.githubusercontent.com/assets/1919241/7912095/cb98dd76-0853-11e5-8a1c-ae052bf59cdb.png)
![js](https://cloud.githubusercontent.com/assets/1919241/7912193/ddd83166-0854-11e5-9696-1341d6d12111.png)

**Comment by deadmann** [comment]
XML Ajax Response:
<ArrayOfNewAirline xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/AngularJs.Models"><NewAirline><AirlineCod>1</AirlineCod><AirlineLogo>../files/1atrak.jpg</AirlineLogo><AirlineNam>اترک اير</AirlineNam><AirlineNamEn>ATRAK air</AirlineNamEn></NewAirline><NewAirline><AirlineCod>2</AirlineCod><AirlineLogo>../files/2zagros.jpg</AirlineLogo><AirlineNam>زاگرس اير</AirlineNam><AirlineNamEn>ZAGROS air</AirlineNamEn></NewAirline><NewAirline><AirlineCod>3</AirlineCod><AirlineLogo>../files/3caspian.jpg</AirlineLogo><AirlineNam>کاسپين اير</AirlineNam><AirlineNamEn>CASPIAN air</AirlineNamEn></NewAirline><NewAirline><AirlineCod>4</AirlineCod><AirlineLogo>../files/4ata.jpg</AirlineLogo><AirlineNam>آتا اير</AirlineNam><AirlineNamEn>ATA air</AirlineNamEn></NewAirline><NewAirline><AirlineCod>5</AirlineCod><AirlineLogo>../files/5meraj.jpg</AirlineLogo><AirlineNam>معراج اير</AirlineNam><AirlineNamEn>MERAJ air</AirlineNamEn></NewAirline><NewAirline><AirlineCod>6</AirlineCod><AirlineLogo>../files/6download.jpg</AirlineLogo><AirlineNam>ايران اير</AirlineNam><AirlineNamEn>IRAN air</AirlineNamEn></NewAirline><NewAirline><AirlineCod>7</AirlineCod><AirlineLogo>../files/7iranairtour.jpg</AirlineLogo><AirlineNam>ايران اير تور</AirlineNam><AirlineNamEn>IRAN air tour</AirlineNamEn></NewAirline><NewAirline><AirlineCod>8</AirlineCod><AirlineLogo>../files/8naft.jpg</AirlineLogo><AirlineNam>نفت اير</AirlineNam><AirlineNamEn>NAFT air</AirlineNamEn></NewAirline><NewAirline><AirlineCod>9</AirlineCod><AirlineLogo>../files/9taban.jpg</AirlineLogo><AirlineNam>تابان اير</AirlineNam><AirlineNamEn>TABAN air</AirlineNamEn></NewAirline><NewAirline><AirlineCod>10</AirlineCod><AirlineLogo>../files/10kishair.jpg</AirlineLogo><AirlineNam>کيش اير</AirlineNam><AirlineNamEn>KISH air</AirlineNamEn></NewAirline><NewAirline><AirlineCod>11</AirlineCod><AirlineLogo>../files/11qeshmair.jpg</AirlineLogo><AirlineNam>قشم اير</AirlineNam><AirlineNamEn>QESHM air</AirlineNamEn></NewAirline><NewAirline><AirlineCod>12</AirlineCod><AirlineLogo>../files/12saha.jpg</AirlineLogo><AirlineNam>ساها اير</AirlineNam><AirlineNamEn>SAHA air</AirlineNamEn></NewAirline><NewAirline><AirlineCod>13</AirlineCod><AirlineLogo>../files/13mahan.jpg</AirlineLogo><AirlineNam>ماهان اير</AirlineNam><AirlineNamEn>MAHAN air</AirlineNamEn></NewAirline><NewAirline><AirlineCod>14</AirlineCod><AirlineLogo>../files/14ariya.jpg</AirlineLogo><AirlineNam>آريا اير</AirlineNam><AirlineNamEn>ARIA air</AirlineNamEn></NewAirline><NewAirline><AirlineCod>15</AirlineCod><AirlineLogo>../files/15farsair.jpg</AirlineLogo><AirlineNam>فارس اير</AirlineNam><AirlineNamEn>FARS air</AirlineNamEn></NewAirline><NewAirline><AirlineCod>16</AirlineCod><AirlineLogo i:nil="true" /><AirlineNam>قشم اير</AirlineNam><AirlineNamEn></AirlineNamEn></NewAirline></ArrayOfNewAirline>

**Comment by PaulL1** [comment]
The korean characters are a symptom of not installing fonts correctly: http://ui-grid.info/docs/#/tutorial/116_fonts_and_installation

The persian I'd probably need a plunker for, as I don't have any persian text to test with.  First question would be whether it's in the csv file that goes to Excel - i.e. is it exporter not formatting the file properly, or Excel not reading the file properly.

**Comment by deadmann** [comment]
how should i know that? 

and BTW, if you mean that font is not installed in my system, it is, cause i can see the example pages of these grids, but if you mean on my configuration,... i don't know...

i send persian using EF -> JSON

here's screen shot, which is more clear

![untitled](https://cloud.githubusercontent.com/assets/1919241/8018453/d90319d4-0c0b-11e5-8b67-1845d9fc1b8e.jpg)

And about font, i did this... but i didnt found any configuration for the preloaded ASP.NET Sample... though there is four file for font, so i assume it auto configure them

![untitled1](https://cloud.githubusercontent.com/assets/1919241/8018464/37ab03b6-0c0c-11e5-872f-c9f3d970aa07.jpg)

**Comment by PaulL1** [comment]
OK, starting with the fonts (Korean characters).  If the ui-grid.info site looks fine, but it doesn't when you're using it locally, then that means you haven't installed the ui-grid fonts in your build process correctly.  I'm not very familiar with ASP.NET, but I'd guess your browser will be giving some sort of error when it attempts to retrieve the ui-grid font files, and that error will probably tell you where it was looking for the font.  The tutorial I pointed to gives some tips on getting the fonts installed locally properly.

On the exporter, the way to check would be to open the csv file that has been downloaded using something other than Excel (say, with notepad or wordpad), and see whether it has the persian characters in it, or whether it has the wrong content.  If it has the right content in it, then likely it's that Excel is failing to import it.  If it has the wrong content in it, then it means the exporter isn't putting the persian content in there.

**Comment by deadmann** [comment]
Thank you, the problem was with font addressing

**Comment by deadmann** [comment]
Thank you, the problem was with font addressing,

But what about exporters?

**Comment by deadmann** [comment]
Thank you, the problem was with font addressing,

But what about exporters?

**Comment by PaulL1** [comment]
Did you get a chance to open the csv file in notepad or other editor, and see whether the data as exported from the grid correctly has persian characters?  If it does, then the problem is with Excel interpreting the csv.  If it doesn't, then could you provide a plunker that we can look at?

**Comment by deadmann** [comment]
i'm not sure, but i'm kinda to look for things..., sry for late answer, and though it's not a answer, my boss assign me a force project so i left it :|

**Comment by 8Mostafa0** [comment]
hi every body i testing something and its work for me i hope its work for you as well.
i change endcoding of csv file from UTF-8 to UTF-32 and all my Persian words appear very well.be lucky.
