### ISSUE TITLE
Add new row with Tab navigation (like Excel)

### ISSUE THREAD

**Issue by oriolpuig** [angular-ui/ui-grid#3668]
I'm using ngGrid on my project and I found a possible issue or new feature. 

I'm trying to add new row when you are at last cell of last row of the grid and you try to tab to next cell. Then, it will add new empty row on the grid and you could add new item.

Someone knows how can I do it?

Thanks,

**Comment by c0bra** [comment]
Yea that would be an enhancement to the edit feature.  Not terribly difficult though.

**Comment by uguryilmaz** [comment]
that would be awesome if you can add it.

**Comment by unkn0wn-kgb** [comment]
+1
Also how would I generally add a new row?

**Comment by PaulL1** [comment]
In general you add a row by adding an extra item to your data array.

Doing this in base is trickier than it looks, because we never modify the data array, but doing this would implicitly mean adding a new object to that array.  In importer I had need for something like this, and ended up writing it as a callback, as people will often want to call new on the new object.

**Comment by unkn0wn-kgb** [comment]
So say I want to have behaviour where I use cell navi and always want to have spare row at the bottom of the grid in that case you suggest I subscribe to navigation event and modify my original gridoptions.data and push empty object? Or is there is more elegant way of doing similar?

**Comment by PaulL1** [comment]
I think that's the easiest way to do it.  I'm not aware of a more elegant way.

**Comment by vigohe** [comment]
Where should I start digging to do this?

**Comment by unkn0wn-kgb** [comment]
At the end to solve this I just added empty object to gridOptions.data that adds empty row sort of hack but works

**Comment by dpinho17** [comment]
I need the same functionality and I implemented it the same way however once the virtualizationThreshold kicks in it starts causing focus issues which doesn't allow the user to continue working. Ideally it would just add a row and the user can continue to type in the cell they are in. Does anyone know of another way that won't cause focus issues when virtualization is on?

**Comment by unkn0wn-kgb** [comment]
@dpinho17 I had the same issue and I just keep 5 empty rows so if you use one I add one and there is always 5 spare rows that helps with visualization

**Comment by dpinho17** [comment]
Thanks For the quick response!,

That would work unless the user actually clicks the last row in which focusing issues occur again. This issue concerns us it seems virtualization and scrolling are causing issues when new rows are added. An Enhancement was mentioned in this thread is that still in the works?

**Comment by unkn0wn-kgb** [comment]
When user clicks on the last row you add another 5 and so on.
Also it does not have to be 5 it could be 100

**Comment by dpinho17** [comment]
So with the user clicks into an editable cell on the last row you don't notice any unfocusing issues? For us we implemented it in the Navigate even and wiht virtualization on it would sometimes focus the wrong cell or leave editing of the correct cell when the user clicked the last row. If we make it 5 rows it would be less likely for the user to click the last cell but if they do it still causes the same issues for us. Were you able to get around this issue? Where did you implement the adding of the row?

Thanks again for the help,
Dave
