### ISSUE TITLE
Select all checkbox on grid shrinks vertically when columns are resized

### ISSUE THREAD

**Issue by TomPacksize** [angular-ui/ui-grid#3672]
1 - Bind data to the grid with 3 or more columns using the options stated below.
2 - Re-size column width with mouse
3 - See the select all check box get compressed vertically and row headers get out of alignment with the rows in the grid.
Settings used in js controller:
     headerRowHeight: 36,
     enableColumnResizing: true,
     enableHeaderRowSelection: true,
     enableSelectAll: false,
     multiSelect: false,
     enableSorting : false,

**Comment by PaulL1** [comment]
Seems to be working here: http://plnkr.co/edit/du8nbhdfGalUu1vhjuvd?p=preview

Are you able to modify that plunker to demonstrate the issue?

**Comment by PaulL1** [comment]
Information sought, no further information forthcoming for some months.  Closing.
