### ISSUE TITLE
ng-grid without scroll not shows contents of all rows

### ISSUE THREAD

**Issue by devalkars123** [angular-ui/ui-grid#3679]
Hi, I am using ng-grid in our website, requirement not to show scroll of the ng-grid (ie. not to show grid scroll), rows at the end of grid are empty, (eg. out of 11 rows only 7 rows are displayed with the content)... i changed var EXCESS_ROWS = 6 to var EXCESS_ROWS = 9999, then it shows all rows,
can you please provide a way to change this variable or suggest workarround to fix this issue.

**Comment by PaulL1** [comment]
Are you using ng-grid or ui-grid?

Are you able to provide a plunker that demonstrates the issue?

**Comment by devalkars123** [comment]
Thanks for response, i am using ng-grid, found solution which worked for me, here is plunker for the fix http://plnkr.co/edit/tfS4Jce9XNRvM6hKqKq0?p=preview

**Comment by krishnanpanthayi** [comment]
the fix is not clear in plunker.

**Comment by knpus** [comment]
whats the fix, its not clear in plunker

**Comment by devalkars123** [comment]
1.  import the ng-grid-flexible-height.js
  <script type="text/javascript" src="ng-grid-flexible-height.js"></script>

2. Please note script.js at the end of script it has plugin added.

 $scope.gridOptions = {
        data: 'myData',
        enablePaging: true,
		    showFooter: true,
        totalServerItems: 'totalServerItems',
        pagingOptions: $scope.pagingOptions,
        filterOptions: $scope.filterOptions,
        plugins: [new ngGridFlexibleHeightPlugin()]
    };
