### ISSUE TITLE
  uiGridConstants.filter.SELECT does not have any effect

### ISSUE THREAD

**Issue by salarmehr** [angular-ui/ui-grid#3681]
Is adding the following to a column definition enough to have a category filter:

                filter: {
                    type: uiGridConstants.filter.SELECT,
                    selectOptions: [
                        {value: 'f', label: 'Female'},
                        {value: 'm', label: 'Male'}
                    ]
                }

I have added it and it has no effect. Also there is no error. What's wrong with it?

**Comment by PaulL1** [comment]
Check the tutorial. You also need to provide an editable cell template.

**Comment by PaulL1** [comment]
Response given, closing.
