### ISSUE TITLE
Rotate grid

### ISSUE THREAD

**Issue by hvallee** [angular-ui/ui-grid#3684]
Hello, I'm looking for a way to rotate the grid, it means that features would be placed horizontally and rows vertically. Is there a way to achieve this?
Because when we have data with a lot of features and just few rows, it could be very helpful.

![screenshot from 2015-06-03 16 27 06](https://cloud.githubusercontent.com/assets/9278242/7962397/6e41d5a4-0a0d-11e5-9f03-14bdb70b6b7e.png)

Thank you for your help !

**Comment by PaulL1** [comment]
I guess in theory if you overrode enough of the templates you could get this outcome, I'd expect it to be quite difficult and error prone though.

**Comment by FAMILIAR-project** [comment]
Thanks @PaulL1 for the answer. Have you got some existing examples/attempts in mind (for the sake of inspiration)?

**Comment by PaulL1** [comment]
No, I've never seen someone do this.  But in theory the grid can't tell whether it's horizontal or vertical.  In practice of course, it probably does assume that columns have width and rows have height, I personally wouldn't try to do this.

Actually, the more I think about it the less convinced I am that it would work.

**Comment by PaulL1** [comment]
This is a useful request, but not really in the current roadmap.  We have far too many good ideas in the repository already, giving the impression that we have a project riven with defects.

Accordingly, I am leaving the enhancement tag on this, but closing it.  If someone would like this functionality, we'd welcome a pull request that adds it.

**Comment by gayram2004** [comment]
Hi
I know this is coming up after two years. Are there any solution for presenting the ui-grid rows vertically.
