### ISSUE TITLE
how to export colors to pdfs and csvs

### ISSUE THREAD

**Issue by gindij** [angular-ui/ui-grid#3685]
Hi,

In my grid I am coloring the contents of certain cells and I want those colors to carry over when I export to PDF or CSV. Can I do this? If so, how?

Thanks in advance.

**Comment by PaulL1** [comment]
There's no automatic way to do it - the export goes back to the data to determine what to display.  But there is a formatting callback of some sort (I can't recall the name) that you can use to apply formats to any cell.   You would need to reimplement your logic within that callback.

**Comment by gindij** [comment]
Great thanks!

**Comment by billyaraujo** [comment]
The formatting callback is exporterFieldCallback?

Not certain how would be able to export color yet with this function.
