### ISSUE TITLE
comprehensive list of cellFilters?

### ISSUE THREAD

**Issue by gindij** [angular-ui/ui-grid#3687]
I'm trying to figure out how to format cell data with dollars, cents, euros,  percentages, and all kinds of other stuff but I can't seem to find a comprehensive list of the available cellFilters (so that I can use those instead of trying to write my own). Does anyone know where I can find something like this?

**Comment by PaulL1** [comment]
That's an angular thing.  The closest I've come is https://docs.angularjs.org/api/ng/filter

**Comment by PaulL1** [comment]
Closing - answer given, and no response for some months.
