### ISSUE TITLE
Datepicker is not working in firefox & IE explorer 

### ISSUE THREAD

**Issue by sailenkumar** [angular-ui/ui-grid#3691]
Datepicker is working in chrome but not working in  Firefox and IE. 
Header alignment is also getting changed on filter .
![datepicker](https://cloud.githubusercontent.com/assets/12409505/7982297/abfb5656-0ad3-11e5-8503-441e2de3187e.png)

**Comment by aikrez** [comment]
The datepicker control is only supported by browsers using Webkit -> Chrome. It is not officially in the HTML spec and is not supported by Firefox/IE
So you need to use a polyfill or a datepicker component

**Comment by PaulL1** [comment]
ui-grid uses html5 controls.  It explicitly notes in the tutorial that it won't work in some browsers, and that if you need a datepicker you need to create a custom edit template.

**Comment by PaulL1** [comment]
This is a useful request, but not really in the current roadmap.  We have far too many good ideas in the repository already, giving the impression that we have a project riven with defects.

Accordingly, I am leaving the enhancement tag on this, but closing it.  If someone would like this functionality, we'd welcome a pull request that adds it.
