### ISSUE TITLE
Grid selection change bounce

### ISSUE THREAD

**Issue by gokhanoner** [angular-ui/ui-grid#3699]
Like request #3619, is it possible to add a bounce to selection change ? When you enabled moving with up/down keys on the grid, and if you send a request on each change, I get a lot of unnecessary calls on server.

Or better, for all change events, maybe a bounce can be added some way, similar way?

**Comment by PaulL1** [comment]
In general we expect the end user to implement a debounce if they need one - not all use cases are the same and some need a debounce, some don't.

**Comment by PaulL1** [comment]
Response given, no further comment for some months. Closing.
