### ISSUE TITLE
Last column sort icon position

### ISSUE THREAD

**Issue by gokhanoner** [angular-ui/ui-grid#3700]
I see that last column sort icon is not in the same position with the other columns. Is there a specific reason for that ? And if possible how can we make it like others ?

This also effect horizontal scroll, when you focus on last column with keyboard, you cannot see the whole data, and scroll dont go to the end.

**Comment by PaulL1** [comment]
It's leaving room for the grid menu probably.

**Comment by PaulL1** [comment]
Closing.
