### ISSUE TITLE
viewing cell contents - ui-grid

### ISSUE THREAD

**Issue by gindij** [angular-ui/ui-grid#3704]
Hi,

This may not be a good question but I was looking through documentation/googling and could not find any way to view the contents of cell programmatically. Is there a simple way to do this?

**Comment by PaulL1** [comment]
No, not really.  You could use jqLite to get the cell element and look at it's .val, but usually I'd just do a getCellValue on the row,col, and ignore the filters.  It depends what you're trying to achieve.

**Comment by PaulL1** [comment]
Response given, no further information for some months.  Closing.
