### ISSUE TITLE
Filters disappear if ui-grid-selection and dynamic filters in columns are active

### ISSUE THREAD

**Issue by tazo90** [angular-ui/ui-grid#3705]
When use dynamic filters in columns and `ui-grid-selection` then filters in column disappear. 
Noticed that if remove `padding=5px` from `.ui-grid-cell-contents` then filter appear, but are not aligned (see below).
![grid](https://cloud.githubusercontent.com/assets/3165572/8011406/c112d308-0bb8-11e5-821f-cae92b72e244.png)

To fix it only helps to set `enableRowHeaderSelection: false`, then first column with checkboxes is hidden and the problem doesn't occur. 
![grid2](https://cloud.githubusercontent.com/assets/3165572/8011407/c339661a-0bb8-11e5-813e-33fa7d3b4f7a.png)

**Comment by PaulL1** [comment]
It's working for me here: http://ui-grid.info/docs/#/tutorial/116_fonts_and_installation

What version are you using?  Are you able to modify that plunker so that it demonstrates the issue?

**Comment by mearing** [comment]
@PaulL1 Do you mean that page rather than say http://ui-grid.info/docs/#/tutorial/401_AllFeatures?

**Comment by PaulL1** [comment]
Ah, no, I'd created a plunker from one of the pages and added selection to it.  I clearly failed to copy and paste the plunker.  Here: http://plnkr.co/edit/xncP5n01XcujozZYvqwF?p=preview

**Comment by DevQueen** [comment]
I'm having the same issue.  I opened an issue that I could not get filtering to work, then suddenly while testing searches on the page, the filtering appeared.  Then it disappeared again.  I do have selection activated as well.  Has anyone found a fix for this issue?

**Comment by Harry-Merrill** [comment]
Seeing the same thing here. Any updates on this would be awesome.

**Comment by fsscoc** [comment]
Same problem here.

**Comment by nicolasrosado** [comment]
I have the same probem.
Could you find a solution to fix this issue ?

**Comment by fsscoc** [comment]
I configure css property and this fix problem.

.ui-grid-header-cell{
height:60px;
max-height:60px;
}

**Comment by nicolasrosado** [comment]
This not fix my problem.
My problem is : when I arrived on the page, sometimes filters disappeared. But when I refresh my page filters appeared.  Has anyone found a fix for this issue ?

**Comment by meenakshijha** [comment]
I am facing the same issue too. If I use ui-grid-selection while rendering the grid , my custom filters doesn't show up at all. It took me two days to figure out that ui-grid-selection is causing this issue!

Has anyone found the solution to it? Please help. 

Thanks

**Comment by meenakshijha** [comment]
@fsscoc  Thanks. Your solution solved my problem. What a saviour!

**Comment by AgDude** [comment]
This is also discussed in #4891
Here is the plunker from that ticket: http://plnkr.co/edit/b4IXz5EaWgRvI3VaKDHn?p=preview

This issue seems to be an issue with the order in which things load. I have only seen this with selection and async loading of the grid data, but that combinatino does not always cause it to occur in my experience.
