### ISSUE TITLE
getTemplate function does not support full or relative urls

### ISSUE THREAD

**Issue by justin-romano** [angular-ui/ui-grid#3706]
```
      try {
        if (angular.element(template).length > 0) {
          return $q.when(template).then(s.postProcessTemplate);
        }
      }
```

angular.element(template) will crash if the template contains a / or :
So my suggested fix is:

```
      try {
        if (typeof(template) !== "string" && angular.element(template).length > 0) {
          return $q.when(template).then(s.postProcessTemplate);
        }
      }
```

I found this because I wanted to do this.

```
columnDefs: [
  {
    field: "Inventory.Description",
    displayName: "Description",
    enableCellEdit: true,
    editableCellTemplate: "templates/select.html",
```

**Comment by JLLeitschuh** [comment]
If you are able to fix this then a pull request would be greatly appreciated.

**Comment by mportuga** [comment]
This seems like a possible good solution, but I worry about losing support for templates as string. I will try to validate that still works first and then do this if I get a chance this week.

**Comment by mportuga** [comment]
This appears to be supported in the latest version:
http://plnkr.co/edit/xW0EUHTEjZzTiGRx
