### ISSUE TITLE
selectAllRows does not render the style of each row checkbox

### ISSUE THREAD

**Issue by brucejcw** [angular-ui/ui-grid#3709]
> $scope.gridApi.selection.selectAllRows();

I'm using this api to checkall, but the UI not correct, when the first time, only the header checkbox is checked.  If I using this api again, none of the checkbox will be checked, while I'm using 

> $scope.gridApi.selection.getSelectedGridRows()   

it seems all are checked.

So how to checkall as default?

![screen shot 2015-06-06 at 12 37 08 pm](https://cloud.githubusercontent.com/assets/8085088/8018320/0089b2c8-0c49-11e5-804e-7c937a3c2683.png)

**Comment by PaulL1** [comment]
It's not really clear what your problem is.  Could you try again to explain what it's doing and what you want it to do?

**Comment by Awakening-j** [comment]
@PaulL1 I solved my problem, but I'm not sure if it is the best way. My problem is how to make all the checkbox checked when the data is loaded, now I use $timeout after I load griddata, let me show you in plunker, So is it the best/right way to do it ? http://plnkr.co/edit/Eel592CZCbKtUdqKxzhB?p=preview

**Comment by PaulL1** [comment]
$timeout is the recommended way - just call selectAll from a $timeout after you load the data.  The data rendering will always take only 1 digest cycle, and a timeout of 0 ms will always run immediately after that digest cycle, irrespective of how much data you have.
