### ISSUE TITLE
Write api documentation tutorial

### ISSUE THREAD

**Issue by PaulL1** [angular-ui/ui-grid#3716]
Would provide links to key api documentation and explain some grid concepts

**Comment by AgDude** [comment]
I don't know how much time you were hoping to devote to this, but think it would be really helpful to put links to related the API docs within each tutorial page also.

While little more complicated, another api docs feature that would be nice is moving the currently viewed section to the top of the left pane. For example, if I am reading about pinning, I might read the options, but if I didn't search for pinning I now have to scroll way down the page to read about the columnDefs.
