### ISSUE TITLE
Exporting menu not visible on IE

### ISSUE THREAD

**Issue by dfiori** [angular-ui/ui-grid#3722]
Hi,
I developed a reporting web app using your UI Grid. I have some troubles including export features: on Chrome and FF it works perfectly both CSV and PDF. On IE there's no export voice in the grid menu.
Is it a bug or I miss something?

Thanks a lot

**Comment by PaulL1** [comment]
I don't have IE to check, but does the tutorial work fine for you on IE?

**Comment by dfiori** [comment]
Do you mean the example in the tutorial page? Yep, it seems work fine. So I think I missed something (config parameter, etc.) but I double check the code and I cannot find where the error is.

**Comment by PaulL1** [comment]
Yeah, but I can't see your code, so can't tell you what you've done wrong either.  :-)  Any chance of a plunker?

**Comment by dfiori** [comment]
It's a little bit hard to create a jsfiddle/plunker because the controller which handle the grid creation/data handling will use some other services/external configuration params.
I already tried to create a "clean project" and using the grid in the same way I done in the controller, but no error in that case. So I think there's something strange which cause this issue.
May be a incompatibility with externale lib?

**Comment by PaulL1** [comment]
If it doesn't do it when you create a plunker, it would suggest that something in your code is causing it.

**Comment by PaulL1** [comment]
Information sought, no response for some months.  Closing.
