### ISSUE TITLE
Full row selection

### ISSUE THREAD

**Issue by iyel** [angular-ui/ui-grid#3723]
Is it possible to toggle on multi select on checkboxes and turn it off when clicking on row. So that multi select will be available when clicking on checkboxes but one row will be selected (everything else will be deselected) if I click on row. (even more when ctrl pressed multi select will work in all cases)

Can you please give a hint how to implement that?

**Comment by PaulL1** [comment]
That's not a native feature, you'd have to somehow use an onSelection callback, and manipulate the rows.  Except you cannot easily tell whether they clicked on the row or the selection header.  So I'd guess this isn't possible.

**Comment by PaulL1** [comment]
Answer given, no response for some months.  Closing.
