### ISSUE TITLE
pagination controls

### ISSUE THREAD

**Issue by gindij** [angular-ui/ui-grid#3729]
Hi,

Not sure why, but pagination controls are appearing on top of the column footers (I'd like it to be below the grid footer). Any idea how I can fix this?

**Comment by PaulL1** [comment]
Seems to be working correctly here: http://plnkr.co/edit/Gi3vrnz58fTbYBwEtIjy?p=preview

Is there something you're doing differently?

**Comment by gindij** [comment]
I dont think so. In main.js, I have:
enablePaginationControls: true;
paginationPageSize: same as yours;
paginationPageSizes: same as yours;

I have included the appropriate directives and dependencies specified in the documentation.

I end up with something that looks like this:
![capture](https://cloud.githubusercontent.com/assets/6021161/8042670/9aee2c3a-0dd5-11e5-87e2-78e9f50ab803.PNG)

**Comment by gindij** [comment]
unless the enable pagination controls affects something, but I tried taking it out and I got the same effect.

**Comment by PaulL1** [comment]
Does the plunker I provided work fine for you?  If no, then perhaps it's your browser.  If yes, then perhaps you're missing some css or something?

**Comment by gindij** [comment]
your plunkr does work. but what css could i be missing? your main.css file only has one class set.

**Comment by PaulL1** [comment]
No idea, but my logic is that if the plunker works and your code doesn't work, then something must be different between the two, and it probably isn't a ui-grid defect.  I'd try adding things from your code to the plunker until it stops working, then whatever is the last thing you changed is the culprit.

**Comment by PaulL1** [comment]
Answer given, no response for some months.  Closing.
