### ISSUE TITLE
Show a List of custom Actions on cell  header click

### ISSUE THREAD

**Issue by canyon2015** [angular-ui/ui-grid#3732]
Is it possible to show a list of custom actions while clicking on header of the grid? something like what currently the sort icon does but for a different set of functionality?
What feature should I use?
Appreciate any sort of help

**Comment by PaulL1** [comment]
You can customise the column menu.   Refer http://ui-grid.info/docs/#/tutorial/303_customizing_column_menu

**Comment by canyon2015** [comment]
Thanks Paul. What if I need to show a list of actions on the click of a custom icon on header cell?
(BTW, I have no idea yet about how to show the icon itself)
Thanks

**Comment by PaulL1** [comment]
You could, but I think you'd be better to change the icon for the menu (which you could do reasonably easily with a custom template) rather than trying to build a new menu from scratch.

**Comment by canyon2015** [comment]
I agree with you. Thanks

**Comment by PaulL1** [comment]
Answer given, no response for some months.  Closing.
