### ISSUE TITLE
Extra Space on chrome browser 

### ISSUE THREAD

**Issue by sailenkumar** [angular-ui/ui-grid#3734]
![chrome_extra_space_issue](https://cloud.githubusercontent.com/assets/12409505/8051342/f93c226a-0e98-11e5-9d04-d5fbdbb33e96.png)
Extra space is coming betwwen the menu on chrome browser but works fine on Firefox.

**Comment by ncmalitha** [comment]
I also encountered this issue . It also has problems when the browser window is resized but im using ui-grid unstable

**Comment by JLLeitschuh** [comment]
A minimal plunker demonstrating the bug would be helpful.

**Comment by JLLeitschuh** [comment]
Possibly related to #3725

**Comment by PaulL1** [comment]
Information sought, no response for some months.  Closing.
