### ISSUE TITLE
Not all data is rendered inside ng-grid

### ISSUE THREAD

**Issue by vovkvlad** [angular-ui/ui-grid#3745]
I'm fetching data from the server, and receive 20 data-items. However, only 6 rows are rendered, and inside **ng-repeat** there are 6 of them. However the height of the canvas is calculated correctly All other items appears after resize of the window.
This issue is similar to: https://github.com/angular-ui/ng-grid/issues/860 , but using virtualizationThreshold  doesn't work for me.

I got ng-grid via npm and my current version is 2.0.1

**Comment by c0bra** [comment]
@vovkvlad ng-grid 2.0.1 is really old. If you're stuck with 2.x you need to update to the latest version, 2.0.14. Unfortunately npm is out of date, I know.

Also you could look at using ui-grid, the rewrite of ng-grid. It's available on bower and is in beta.

**Comment by vovkvlad** [comment]
@c0bra I've tried version 2.0.14 and with it i have nothing on the view until resize.

And moreover, after i resize and get everything in one view, in other views while trying to resize I have the next errors:

`Cannot read property '$$phase' of null ` in this part of code: 
`domUtilityService.digest = function($scope) {
        if (!$scope.$root.$$phase) {
            $scope.$digest();
        }
    };`

**Comment by Vinodang** [comment]
for ng-grid i think you need to call gridOptions.ngGrid.buildColumns(); for ui-grid you need to call gridApi.core.refresh();

**Comment by mportuga** [comment]
ng-grid is no longer supported.
