### ISSUE TITLE
suggestion: change font files path

### ISSUE THREAD

**Issue by brucejcw** [angular-ui/ui-grid#3751]
I'm using gulp to manage my project, and a standard dist folder structure is like:  
![screen shot 2015-06-11 at 7 21 48 pm](https://cloud.githubusercontent.com/assets/8085088/8105846/3a303d38-106f-11e5-813e-cbdfb89ae9e4.png)  

As in the screnshot, all the fonts will be moved to `fonts` folder, but in angular-ui-grid folder, all the `{css, fonts}` are in the same folder level,
![screen shot 2015-06-11 at 7 23 43 pm](https://cloud.githubusercontent.com/assets/8085088/8105909/b686cdac-106f-11e5-824a-af5da2c15b91.png)
![screen shot 2015-06-11 at 7 24 14 pm](https://cloud.githubusercontent.com/assets/8085088/8105911/b801f242-106f-11e5-8981-9a1b00114734.png)  

So it will cause (404) error, because the fonts path changed to `(../fonts/ui-grid.ttf)`, not `('ui-grid.ttf')`  
I suggest to create a `font foler` and `style folder` like `bootstrap` does,  Or any good way to config in `gulp`?

**Comment by jonathanhds** [comment]
+1

**Comment by serendipitic** [comment]
+1

**Comment by 700ghz** [comment]
+1
I got this problem when using Generator Gulp Angular.

**Comment by 700ghz** [comment]
Okay, I added task in gulp build:
```
gulp.task('fontsUiGrid', function() {
    gulp.src('./bower_components/angular-ui-grid/**/*.{ttf,woff}')
        .pipe(gulp.dest(path.join(conf.paths.dist, '/styles/')));
});

gulp.task('build', ['html', 'fonts', 'other', 'fontsUiGrid']);
```
And it worked!

**Comment by yahyakoc** [comment]
gulp build puts fonts into fonts directory.. but ui-grid seeking them in styles directory.. when you are going to fix this issue?

**Comment by algil** [comment]
+1

**Comment by Smelyj** [comment]
+1

**Comment by phvajjha** [comment]
+1

**Comment by otaviosoares** [comment]
+1

**Comment by peterlitvak** [comment]
+1
