### ISSUE TITLE
when fastWatch is true $scope.uiGrid.columnDefs.length watcher sets the columnDefs to the length of the array

### ISSUE THREAD

**Issue by lario** [angular-ui/ui-grid#3755]
The watch function called on columnDefs.length change sets the columnDefs to the new value (the length)

https://github.com/angular-ui/ng-grid/blob/master/src/js/core/directives/ui-grid.js#L70

**Comment by dambrouski** [comment]
I have the same issue as lario, it actually works fine in RC19, so I'm waiting to have this fixed before upgrading.

**Comment by PaulL1** [comment]
The fastwatch code is a bit alpha, but it shouldn't do that - I'll look this weekend.

**Comment by hhorstia** [comment]
Any news when this fix will be released? I'm having the same problem with using fastWatch

**Comment by MartijnWelker** [comment]
Any news ?
