### ISSUE TITLE
Sort order in custom column menu items

### ISSUE THREAD

**Issue by Grievoushead** [angular-ui/ui-grid#3759]
Is it possible to put custom column menu item as 1st item in menu?
![image](https://cloud.githubusercontent.com/assets/1427311/8118267/99253c54-1096-11e5-880a-1725b05cb6d3.png)

**Comment by JLLeitschuh** [comment]
Officially the only supported options for the menu are documented here: http://ui-grid.info/docs/#/api/ui.grid.class:GridOptions.columnDef

These options include:
title: controls the title that is displayed in the menu
icon: the icon shown alongside that title
action: the method to call when the menu is clicked
shown: a function to evaluate to determine whether or not to show the item
active: a function to evaluate to determine whether or not the item is currently selected
context: context to pass to the action function, available in this.context in your handler
leaveOpen: if set to true, the menu should stay open after the action, defaults to false

There is an option for order that doesn't seem to be implemented on the column menus but is implemented on the grid menus.
The default grid menu items have an order starting at 300. You could try using a negative number for the order value and see if that works.
