### ISSUE TITLE
Release state of features

### ISSUE THREAD

**Issue by AgDude** [angular-ui/ui-grid#3763]
According to the [3.0 milestone](https://github.com/angular-ui/ng-grid/milestones/3.0) we are getting close! We need to be more clear about the release state of each feature, because not all of the features will be ready. My intent is that after we have had sufficient input here, we should add a bootstrap alert on the API docs and Tutorial pages for all features which are not considered "stable"

alpha - This is in development, there will almost certainly be breaking api changes, or there are major outstanding bugs.
beta - We think this is ready, but it hasn't seen a lot of use, or has some known bugs
stable - There should no longer be breaking api changes without a deprecation warning

@c0bra @PaulL1 @swalters Please edit the table below as you see fit for features you lead.

Feature		        | Release state
-------------------        | --------- |
auto-resize-grid 	| beta
cellnav                     | stable
edit 				| stable
expandable 		| alpha
exporter 			| stable
grouping 			| beta
importer 			| stable
infinite-scroll 	        | beta
move-columns 		| alpha
pagination 		| alpha
pinning 			| stable
resize-columns 	| stable
row-edit 			| stable
saveState 		| stable
selection 			| stable
tree-base 		| beta
tree-view 			| beta

**Comment by PaulL1** [comment]
I've updated all them @AgDude, @c0bra, @swalters, feel free to modify my first guess.

**Comment by c0bra** [comment]
I noticed that all of them are snake-case except for saveState which is camelCase. Can we change that to be consistent?

**Comment by c0bra** [comment]
Other than that this all looks great to me. Can we start adding the alerts?

**Comment by AgDude** [comment]
I generated this table from the names of the feature directories/files in the repository, so the naming should be fixed there. There is inconsistency in naming conventions in the core also.

**Comment by c0bra** [comment]
ah-ha

**Comment by c0bra** [comment]
I'm going to go ahead and close this as this is all documented in README.md now.
