### ISSUE TITLE
Grid container not rendering properly

### ISSUE THREAD

**Issue by kmittal** [angular-ui/ui-grid#3764]
Since upgrading from RC20 to RC21- I am having the following layout issue.
![grid-layout](https://cloud.githubusercontent.com/assets/3634458/8132583/bcc87c52-10f0-11e5-89a5-64d444e2a90e.PNG)

On inspecting the DOM is ee that we have some margin being calculated dynamically through colContainer.getMargin('left'), which is putting margin-left of 30px. which is making the grid container move down.

I have attached the DOM too for reference.
![extra margin](https://cloud.githubusercontent.com/assets/3634458/8132620/f584abba-10f0-11e5-9279-5d544fe94574.PNG)

This only happened when i upgrade from RC20- to RC21. Anyone having any input/suggestion on this one?
Thank you.

**Comment by JLLeitschuh** [comment]
What OS/Browser are you experiencing this on? Also, can you provide a plunker to demonstrate the problem?

**Comment by PaulL1** [comment]
Information sought, no response for some months.  Closing.
