### ISSUE TITLE
Column Moving is not working fine with grouping header

### ISSUE THREAD

**Issue by bvsbharat** [angular-ui/ui-grid#3778]
when i drag the column 6 on the column 4th its moving the 6th column to 1st position .
see the image below.  

![blob](https://cloud.githubusercontent.com/assets/5091243/8154145/a145000c-1354-11e5-82ef-52d4ce613125.png)

**Comment by JLLeitschuh** [comment]
I'm unable to reproduce your problem in the demo: http://ui-grid.info/docs/#/tutorial/217_column_moving
If you are still having problems with it please provide a minimal plunk demonstrating the issue.

**Comment by PaulL1** [comment]
Information sought, no response for some months.  Closing.
