### ISSUE TITLE
ng-grid scrolling hiding the column header in IE10, when height is more then window size an

### ISSUE THREAD

**Issue by bvsbharat** [angular-ui/ui-grid#3779]
Grid having 14 column with scrolling, i gave the height of the grid as 2000px. 
Please see the below link  its happening when the height  of the grid is more then screen width. 
when i scroll the grid for other column to see i am getting hiding of the columns. 

link: http://plnkr.co/edit/HcDqJH?p=preview.

Note: issue with ie10 and 9

**Comment by c0bra** [comment]
Can you take a screenshot of what you're seeing? I can't get anything weird to happen in your plnkr in IE10.

**Comment by PaulL1** [comment]
Information sought, no response for some months.  Closing.
