### ISSUE TITLE
getAggregationValue() on hidden column

### ISSUE THREAD

**Issue by sebmaynard** [angular-ui/ui-grid#3780]
Hi,

I've got a few hidden columns in my grid; I'd like to include their aggregationValue in the footer of another column; I'm doing something like this in my footer template (the "units" column is hidden):

```
{{ col.getAggregationValue() | currency:'£' }}
( {{ grid.getColumn("units").getAggregationValue() | number }} )
```

But unfortunately the second aggregation value displays nothing...

Any ideas how I can get the aggregationValue on a hidden column? I tried calculating my totals when the grid is populated, but these don't update if a column is filtered... (but the non-hidden column does)

Thanks!

**Comment by sebmaynard** [comment]
I've figured out that I can register a row processor that will help:

    scope.gridApi.grid.registerRowsProcessor(myFunc, 200)

And in myFunc, add up the new totals and store in $scope; then in my new footer:

    {{ grid.appScope.totals["units"] }}

So this is all working fine; but it would be nice to avoid this and just use the hidden column aggregation :)

Thanks!

**Comment by ChaosFuuury** [comment]
@sebmaynard  Hi there ,could u please show me some Demo of using 'getAggregationValue()'?
Like how could u get the 'col'?
