### ISSUE TITLE
Suggestion: Grouping without white-spaces

### ISSUE THREAD

**Issue by askanhan** [angular-ui/ui-grid#3781]
It would be better if the grouping values shouldn't be necessary a column. So as shown in the image below, unnecessary whitespaces would be filled up with another column. A huge screen-saver.
Thus, the grouping values shouldn't be appear as a column, but just as a line for each-grouped feature.
![sugg](https://cloud.githubusercontent.com/assets/5607648/8161269/11d09d38-1376-11e5-80ed-d5685bdfa833.png)

**Comment by JLLeitschuh** [comment]
Do you mean like how Angular Grid does grouping? http://angulargrid.com/angular-grid-grouping/index.php

**Comment by askanhan** [comment]
Yep, this is exactly what i mean!

**Comment by PaulL1** [comment]
This is a useful request, but not really in the current roadmap.  We have far too many good ideas in the repository already, giving the impression that we have a project riven with defects.

Accordingly, I am leaving the enhancement tag on this, but closing it.  If someone would like this functionality, we'd welcome a pull request that adds it.
