### ISSUE TITLE
TypeError: styles is null

### ISSUE THREAD

**Issue by craftyInstigator** [angular-ui/ui-grid#3782]
This is an issue specific to Firefox that was detected in Firefox 38, and has been reproduced using ui-grid 3.0.0-rc.22:

If the ui-grid is located in an iframe, and that iframe is hidden via ng-show/hide (styled to display: none !important), there is an error in the console:

TypeError: styles is null

**Comment by JLLeitschuh** [comment]
It would be helpful if you were to provide a minimal plunker that demonstrates this issue.

**Comment by craftyInstigator** [comment]
http://plnkr.co/edit/pBmVUQbOu9ma5zCr89mF?p=preview
In Firefox just push the Hide button. I'm almost certain it's caused by the auto-resizing module, since I can't reproduce it without auto-resize.

**Comment by PaulL1** [comment]
Have you looked at the hidden grids tutorial?  http://ui-grid.info/docs/#/tutorial/108_hidden_grids

**Comment by craftyInstigator** [comment]
No, since it isn't related to my problem. The problem, as demonstrated in the plunker, has nothing to do with hiding the ui-grid. This is about a console error that occurs when the display of the whole iframe that happens to have ui-grid in it with auto-resizing is hidden. This is a defect on the auto-resizing module where it's missing a null check for the styles variable. This seems to be specific to Firefox, and the availability of the styles variable when an iframe display is none.

**Comment by craftyInstigator** [comment]
Is there any movement on this issue? It seems to be completely ignored for 3 months.

**Comment by JLLeitschuh** [comment]
If you think you have a solution please feel free to submit a pull request.

**Comment by TheBoef** [comment]
https://github.com/angular-ui/ui-grid/pull/5061

**Comment by mportuga** [comment]
Resolved by the following PR:
https://github.com/angular-ui/ui-grid/pull/5061
