### ISSUE TITLE
Suggestion: Is there a way by which all columns can be hidden on load? 

### ISSUE THREAD

**Issue by jayeshanandani** [angular-ui/ui-grid#3783]
Is there a provision by which we can  have all columns loaded hidden on load? or can we have options like uncheck all and check all in grid menu so that if no of columns are large they can be easily toggled for visibility.

**Comment by JLLeitschuh** [comment]
Grid options has an option to make calls on load using the `onRegisterApi` callback see: http://ui-grid.info/docs/#/api/ui.grid.class:GridOptions
You could easily hide all of the columns there. You could also easily add a button on the grid menu that would allow you to toggle all of the columns.

**Comment by PaulL1** [comment]
Another option would be to use a column builder, or a service within your application, that sets all columns to hidden in the column defs.

**Comment by jayeshanandani** [comment]
I got that onRegisterApi callback part. But I am confused how to hide over there? Is it to be done using loop? (one column at a time) or do we have a method to do it at go.
