### ISSUE TITLE
The e2e test libraries don't work with mocha

### ISSUE THREAD

**Issue by skarfacegc** [angular-ui/ui-grid#3794]
Looks like they're assuming jasmine.  Are there plans to support mocha?

**Comment by PaulL1** [comment]
Not that I'm aware of.  I've never used mocha, and know nothing much about it, but would be happy to look at a PR if there is one.

**Comment by skarfacegc** [comment]
it's actually less mocha and more the assertion library.  Jasmine has it's own built in assertion library (the expect ... ) stuff.  Mocha wants you to bring your own (the most common is chai afaik).  Chai uses a slightly different assertion style.  I'll see what I can do ...

**Comment by skarfacegc** [comment]
So making the test libs support both jasmine and mocha/chai shouldn't be too bad.  I may take that on.  Are there plans on making these libs a bit more baked into the release?  Manually copying the files into my test directory works but feels a bit crufty.  Any thoughts on how you want these to work in the future, and I can see if I can tackle that side as well.

**Comment by PaulL1** [comment]
I haven't really thought too much on how that would work - these sort of grew organically as an example based on the library I was using in my application, but they've become a bit more than that and I haven't given thought to how that would work.  It doesn't really feel right to put them in the dist folder/have them downloaded with bower, as they're not really runtime code.  But I haven't thought of some other way to make them auto-update, so open to ideas.

**Comment by skarfacegc** [comment]
a separate NPM module?

**Comment by PaulL1** [comment]
Could be - that'd make some sense.  Configuring that'd be an @c0bra question though.

**Comment by c0bra** [comment]
What's the end result you're wanting here?  To run the test suite in your own project?

**Comment by skarfacegc** [comment]
To be able to use the test methods provided in the e2e/gridTestUtils.spec.js to test my own grid.  They package some (seemingly) useful methods.  (I haven't actually worked with them yet as my current test rig isn't compatible)

**Comment by skarfacegc** [comment]
As an aside, I really like the idea of these modules.  I wish more projects would provide simplified testing tools.

**Comment by PaulL1** [comment]
Yes, the intention was that people could include them in their application and that it would abstract away from the grid internals a bit - so if we choose to change the repeater from `track by name` to `track by uid` we can change it in the library and we don't break everyone in userlands testing.  But that last step where they get a distributed test library isn't really there at the moment, so it's not quite seamless to them - they have to grab a new copy of the test library that matches the distributed bower files they have.

**Comment by skarfacegc** [comment]
That's why I was thinking an NPM module so dependencies can be tracked etc.  Im still pretty green with node in general, so I may be under-thinking this a bit.

**Comment by skarfacegc** [comment]
So I've started playing around with this.  I think the sane-est thing to do is create a library that essentially has a bunch of get methods.  This allows for handling of the actual assertions in any way folks want.  Thoughts?  Example below ...

     getHeaderColumns: function(gridId) {
          var headerCols = this.getGrid(gridId)
              .element(by.css('.ui-grid-header-cell-row'))
              .all(by.repeater('col in colContainer.renderedColumns track by col.colDef.name'));
          return headerCols;
      },

Using in a test (mocha/chai)

    it('should have 5 header columns', function() {
         var headers = gridTestUtils.getHeaderColumns('mainGrid');
         expect(headers.count()).to.eventually.equal(5);
     });

**Comment by PaulL1** [comment]
That, or create two versions of the test utils - another one for mocha?  

I seem to recall some of it was better with the expect in the library, usually where we expected something in a loop.

Paul Lambert
paul@planar.id.au
+61 411 385 488
+64 21 385 488

**Comment by c0bra** [comment]
I'd rather not duplicate effort and require someone (hint @PaulL1 Paul: it's you) to keep them updated and in sync. If we can make the library work for the majority of users, us included, by changing our testing format then I'm up for that.

Is that what this would require?

**Comment by PaulL1** [comment]
True.  Maybe there's a way to pass in or detect the expect syntax, then it would work with both?

**Comment by skarfacegc** [comment]
I'll play around with it.  I'll definitely send back what I get / find out.  I'm still early in this project and I don't know how hard I'm going to push the UI grid stuff but I may get a decent kernel of a module off the ground.

**Comment by mportuga** [comment]
@dlgski @jeremytowne @Southpaw17 Do you guys think this is worth it? I am inclined to drop this for now.
