### ISSUE TITLE
Persisting column config issue

### ISSUE THREAD

**Issue by shash8787** [angular-ui/ui-grid#3796]
I'm looking to persist the column config by using localstorage but the problem is if I have the selection checkbox within the columns, it keeps on adding the checkbox whenever I refresh the page. Is there a way I can remove the checkbox from the column config?

Thanks

**Comment by lpand** [comment]
I had sort of the same problem, and since the checkboxes column has a precise name i find it and skip it. I hope that can help you.

**Comment by shash8787** [comment]
How do you skip it? The column name for the checkbox column is a tick mark.

**Comment by lpand** [comment]
If with column config you meant column definitions, this is what i do

```Javascript
gridApi.grid.columns.filter(function noCheckboxes(col) {
      return col.name !== 'selectionRowHeaderCol'
}).map(function copyCol(col) {
     var colDef = col.colDef
     // ...
})
```

**Comment by shash8787** [comment]
Thanks for your help. I was able to implement it in ng-grid. Now I'm moving to ui-grid. How can I do this w/o asking the user to save and restore states?

Like the user moved columns. When comes back to this page, he should see the changed order of columns in the grid. This needs to be done for everything, ie, grouping, column show/hide etc

**Comment by lpand** [comment]
Actually, there's a better and straightforward way to get those columns which is [getOnlyDataColumns](https://github.com/angular-ui/ui-grid/blob/f2ed365/src/js/core/factories/Grid.js#L792).

To answer your question, you could simply set listeners for any event of interest. E.g. `groupingChanged` event.
