### ISSUE TITLE
Export data in excel format

### ISSUE THREAD

**Issue by debayan31** [angular-ui/ui-grid#3800]
Is this possible to export grid data in excel format?

Currently we can export data in CSV and PDF format.

**Comment by PaulL1** [comment]
CSV can be imported to Excel.  Excel format is not a documented format, so no we cannot export to it.

**Comment by debayan31** [comment]
Excel means .xls file.

There  may be a issue if I export a grid data which contains comma,semicolon or any special character then after impoting this to Excel, It may not open in desired format.

**Comment by PaulL1** [comment]
There may be an issue, but the csv format should quote or escape those things appropriately.  As noted, .xls isn't a documented/open format, so it's not really possible to build something that creates xls.  The normal method is to create csv.

**Comment by JLLeitschuh** [comment]
Actually .xls is a documented/open format:
jqwidgets actually supports xls output: http://www.jqwidgets.com/jquery-grid-export-to-excel/
The format is documented here: http://blogs.msdn.com/b/brian_jones/archive/2005/06/27/433152.aspx

That being said, someone would have to write an implementation to create an exporter for this.
We could alternatively have an optional dependency upon something like this:
http://jordiburgos.com/post/2013/javascript-export-to-excel.html

**Comment by PaulL1** [comment]
That's interesting, wasn't aware of that.  I do think that csv suits most purposes though - exporting to .xls just adds complexity I would have thought.

**Comment by uguryilmaz** [comment]
that would be awesome if someone implements this functionality. most of the companies uses excel export. and most of the grid components of various companies have this export function. i think ui-gird must have this function as well.

**Comment by JLLeitschuh** [comment]
We are open to pull requests to add enhancements.

**Comment by sunz7** [comment]
+1

**Comment by billyaraujo** [comment]
+1

**Comment by PaulL1** [comment]
This is a useful request, but not really in the current roadmap.  We have far too many good ideas in the repository already, giving the impression that we have a project riven with defects.

Accordingly, I am leaving the enhancement tag on this, but closing it.  If someone would like this functionality, we'd welcome a pull request that adds it.

**Comment by Mastanka** [comment]
+1

**Comment by sidd06** [comment]
+1

**Comment by Incognito-Nemo** [comment]
+1

**Comment by KennedyIhe** [comment]
+1

**Comment by laviyatziv** [comment]
+1

**Comment by dishant8** [comment]
+1

**Comment by ganeshvelanki** [comment]
+1

**Comment by billyaraujo** [comment]
Maybe saving the html as xls would be enough?

Example from: http://jordiburgos.com/post/2013/javascript-export-to-excel.html

somedata.xls
```
<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><!--[if gte mso 9]><xml><x:ExcelWorkbook><x:ExcelWorksheets><x:ExcelWorksheet><x:Name>undefined</x:Name><x:WorksheetOptions><x:DisplayGridlines/></x:WorksheetOptions></x:ExcelWorksheet></x:ExcelWorksheets></x:ExcelWorkbook></xml><![endif]--></head><body><table>
    <tbody><tr>
        <td>100</td>
        <td>200</td>
        <td>300</td>
    </tr>
    <tr>
        <td>400</td>
        <td>500</td>
        <td>600</td>
    </tr>
</tbody></table></body></html>
```

**Comment by chrisruddick** [comment]
+1

**Comment by anasanzari** [comment]
+1

**Comment by rbaras** [comment]
+1

**Comment by Scuttman** [comment]
+1

**Comment by yogeshkumarpa** [comment]
+1

**Comment by oyiadom** [comment]
+1

A nice compromise might be to add the tab-delimited format (TSV) as an export option.  This would work around the comma-related issue with CSV files but still enable users to open the file in Excel.  I suspect changing the delimiter from a comma (",") to a tab ("\t") in the source code is trivial.  From what I have seen, the ".txt" file extension (e.g. as opposed to ".tsv") is the standard for tab-delimited files.

**Comment by csvan** [comment]
I solved this by converting the standard CSV export to .xlsx via this lib: http://excelbuilderjs.com/. It is relatively simple for most cases.

**Comment by lreisoliveira** [comment]
@csvan  http://excelbuilderjs.com is down

**Comment by lreisoliveira** [comment]
About export to xls
+1

**Comment by csvan** [comment]
@lreisoliveira the maintainer shut it down. It was fine when I posted that.

**Comment by rawatshailender** [comment]
+1

**Comment by Romender** [comment]
+1

**Comment by gokhancelik** [comment]
I can achive using jx-xlsx https://github.com/SheetJS/js-xlsx
and FileSaver.
Running plunkr yere

http://plnkr.co/edit/DVhIUgGD04yDXtjp7ReW

**Comment by felrugai** [comment]
@gokhancelik  that's exactly what I needed. It works like a charm. Thank you!

**Comment by alejandrorossi** [comment]
+1

**Comment by dcm93** [comment]
@gokhancelik I am trying to use your excel exporter service but I can't figure out what is your property "e" in the range object in the addCell function. Thanks in advance!

**Comment by nashnight** [comment]
SheetJS Angular demo shows ui-grid import and export: https://github.com/SheetJS/js-xlsx/tree/master/demos/angular

**Comment by bobisch** [comment]
Apparently this functionality now exists in ui-grid proper, since [v4.0.11 (2017-11-20)](https://github.com/angular-ui/ui-grid/blob/75e2d103c4eac8992dcdc0b845dc37675e5066ea/CHANGELOG.md#v4011-2017-11-20), through the exporterMenuExcel and exporterExcel* options (due to merging in PR #6199 (Excel export), per @csvan or @monster910).

In fact, it appears to be enabled by default, even if the required support modules are not available.
To work it requires the "excel-builder" npm module and maybe some other dependencies.  That could be the source of some other issues reported - #6581, others?

The big problem, as mentioned above by @lreisoliveira, is that excel-builder is no longer supported.
It seems to be pretty dead.  See https://github.com/stephenliberty/excel-builder.js and the big *No longer maintained* statement at the top.

Question: should we be looking at a replacement for excel-builder?  Possibly SheetJS/js-xlsx - https://github.com/SheetJS/js-xlsx

Alternatively: Someone should take over excel-builder support or one of the (several) existing forks could be promoted as official?

Also, the "enhancement" and "waiting-response" tags and milestone are probably not appropriate for this issue anymore - it's confusing because  this thread comes up in searches and the reason for closing it makes it sound like it's still an issue.

**Comment by monster910** [comment]
XLSX is a good choice as it also has import/parse capabilities. It lacks the capabilities of excel-builder without a license. 

All open source is roll your own. Feel free to create a new branch and work on a new Excel export.
