### ISSUE TITLE
uiGridMenu doesn't show the menu

### ISSUE THREAD

**Issue by mc0re** [angular-ui/ui-grid#3803]
The definition of directive "uiGridMenu" includes a "link" property, which is set to a function. Inside this function there are following lines:
`var self = this;
...
self.showMenu = $scope.showMenu = function(event, args)...`
This fails at runtime, as `this` is `null`. When commenting out assignment to `self.showMenu`, the menu is shown fine. It seems there are no other consequences, so `self` could be removed.

**Comment by JLLeitschuh** [comment]
Would you be so kind as to provide an example (plunker) demonstrating the problem? The grid menu in the demo seems to be working fine: http://ui-grid.info/docs/#/tutorial/121_grid_menu

**Comment by mc0re** [comment]
The problem appears only in minified ("uglyfied") version of the site. So something happens during uglyfication, that prevents `this` reference to work.
But anyway, if this is unused code, remove it :-)

**Comment by JLLeitschuh** [comment]
Still not sure what problem you are seeing. I'm trying out the same example with the [minified version](http://plnkr.co/edit/LUofdp5YGsWa8yhrJrG6?p=preview) without seeing the problem. If you could provide an example that would be helpful.

**Comment by mc0re** [comment]
I meant a version, which is minified by our toolchain by using "uglify".

Sent from my Windows Phone
________________________________

**Comment by JLLeitschuh** [comment]
Our build process also uses [grunt-uglify](https://github.com/gruntjs/grunt-contrib-uglify). We are running v0.2.7
If you have a PR that passes all of the unit/e2e tests and/or an example of this problem appearing (in a plunk) that would be great.

**Comment by mc0re** [comment]
PR =?

Sent from my Windows Phone
________________________________

**Comment by JLLeitschuh** [comment]
Pull Request

**Comment by PaulL1** [comment]
Information sought, no response for some months.  Closing.
