### ISSUE TITLE
not showing all columns in pdf file when exported form UI grid

### ISSUE THREAD

**Issue by kushalt** [angular-ui/ui-grid#3806]
I used angular-UI grid which contains nearly 27 columns and when I exported it in to PDF file its not showing all columns also header and row text is not readable in PDF file so please let me know if any solution for same.

**Comment by c0bra** [comment]
@PaulL1 would this be yours?

**Comment by PaulL1** [comment]
When you say not showing, do you mean that it's squishing it to fit onto one page, and then you can't read anything?  If so, then this is expected behaviour - pdfMake always tries to fit the table into one page.  I'd be trying to export selected columns, not export all columns.

**Comment by kushalt** [comment]
Yes Paul , its squishing to fit in to one page so text in not readable in the table.

**Comment by PaulL1** [comment]
I think that's the expected pdfMake behaviour.  You'd need to look at the pdfMake documentation to see if you can change it to span multiple pages.

**Comment by PaulL1** [comment]
Answer provided, no response for some months.  Closing.
