### ISSUE TITLE
Drag and drop an item from an external container into UI-Grid

### ISSUE THREAD

**Issue by JonesXavi** [angular-ui/ui-grid#3813]
Hey,
I need to drag and drop some items from a hierarchy tree into Ui-Grid. Is this available? If not, please help to make this work? Or any other suggestions? This gives a major drawback in choosing ui-grid. Earliest help is much appreciated.

**Comment by c0bra** [comment]
What are you wanting to have happen? Add a new row when you drop on the grid?

**Comment by JonesXavi** [comment]
Yes, exactly. Drag and drop an item and add it in as a new row. 
Thanks in advance.

**Comment by PaulL1** [comment]
This is a useful request, but not really in the current roadmap.  We have far too many good ideas in the repository already, giving the impression that we have a project riven with defects.

Accordingly, I am leaving the enhancement tag on this, but closing it.  If someone would like this functionality, we'd welcome a pull request that adds it.
