### ISSUE TITLE
PDF export: define column widths

### ISSUE THREAD

**Issue by mc0re** [angular-ui/ui-grid#3814]
I'd like to have some of the columns in the exported table to be auto-width, others - star-width. How do I achieve that?
I tried (after checking pdfMake manual) to add `exporterPdfTableStyle: { widths: ['auto', 'auto', '*', 'auto', 'auto', 'auto'] }` to the grid options, but that didn't help, all columns have the same width.

**Comment by PaulL1** [comment]
I'm not sure what the difference between auto width and * width would be.  What is the behaviour you were expecting?

**Comment by mc0re** [comment]
I'm expecting, that the "auto" column will be as wide as its content, while the "star" column will take up the remaining space on the page. To my understanding, this is the behavior of "raw" pdfMake.


Sent from my Windows Phone
________________________________

**Comment by PaulL1** [comment]
If you take that same definition and feed it directly to pdfMake, do you get the behaviour that you expect?  I.e. is this a problem with pdfMake, with ui-grid, or maybe even with the way you're passing content in.  pdfMake does provide a sandpit that you can directly try document definitions out in.

**Comment by mc0re** [comment]
How do I get the definition you send to pdfMake, so I can inject the column widths and test it?

**Comment by PaulL1** [comment]
breakpoint in the code would be the easiest way.

**Comment by AgDude** [comment]
Closing due to lack of response.
