### ISSUE TITLE
No way to programmatically unfocus CellNav cells when data and columns change

### ISSUE THREAD

**Issue by jupake** [angular-ui/ui-grid#3815]
Im not sure if there's a way to do this. I update the grid with new data and new columns but the CellNav selection persists even after I call refresh or notifyDataChange with ALL constant. 

I tried setting focusedCells = [], but that didnt work. Calling $scope.gridApi.cellNav.scrollToFocus(null, null) also didnt work.

**Comment by JLLeitschuh** [comment]
This should get you what you want
`if (document.activeElement != document.body) document.activeElement.blur();`
Source: http://stackoverflow.com/questions/2520650/how-do-you-clear-the-focus-in-javascript

**Comment by jupake** [comment]
Unfortunately, this doesn't work. The selected cell still remains selected.

**Comment by JLLeitschuh** [comment]
This is the line creating the problem. https://github.com/angular-ui/ng-grid/blob/master/src/features/cellnav/js/cellnav.js#L940
It is because the event type in the event never gets set.
See the documentation here: https://docs.angularjs.org/api/ng/type/$rootScope.Scope#$on
This was added in aabcd4da564391296d182d78415ab51f9853df64

**Comment by UnitedFreetypeNetworks** [comment]
Trying using FreeType in stead of what your putting, I am very very knew at this, All glory goes to God for my mind and eyes up to all of you grew minds, and how you all work together ots crazy amazing, I know I prob don't have a clue here, bit I've learn to just got with it, and the lord has not lead my wrong yet.
sorry if o out my nose were I shouldn't of.😊

**Comment by andrew2net** [comment]
This work for me:
```
var dataCopy = $scope.data;
$scope.data = [];
$timeout(function(){ $scope.data = dataCopy; });
```

**Comment by vladnyc** [comment]
http://stackoverflow.com/questions/32238188/unselecting-cell-with-cellnav-in-ui-grid/33794254#33794254

**Comment by andrew2net** [comment]
I made couple functions in cellNav module:
 ```
/*
* Remove focus.
* @return {void}
*/
gridApi.cellNav.clearFocus();

/*
* Set focus on cell in row col position.
* @param {integer} rowIndex - Index of row.
* @param {GridColumn} col - Column object.
* @return {void}
*/
gridApi.cellNav.setFocus(rowIndex, col);
```
you can get modified  code from: https://github.com/andrew2net/ui-grid.git

**Comment by bazizten** [comment]
Don't know if it is exactly this you are after but it solved my problems :)
Somewhat hacky but here it is:
```javascript
gridApi.grid.cellNav.clearFocus(); //To get rid of the highlighting
gridApi.grid.cellNav.focusedCells = []; //To clear all focused cells
```

**Comment by julia-bougaev** [comment]
@bazizten We have the same issue. Where did you put your code?
