### ISSUE TITLE
Copy an existing row

### ISSUE THREAD

**Issue by hariharan01** [angular-ui/ui-grid#3816]
Hi,
I would like to implement copy functionality as like below
1. Select a row and click copy button
2. Existing row should be copied and inserted in to grid after the existing row and the copied row should be highlighted in different color so that user will edit the highlighted rows

I have done the work around as below which i want to know whether right or not?
But, i'm able to copy the record and i am not able to do the below two things
1. Unable to select the copied row 
2. Unable to highlight the copied row in different color

var selectedObject =  $scope.gridApi.selection.getSelectedRows();

```
        var newData=[];
        angular.forEach(selectedObject, function (data, index,colDef) {
            newData=angular.copy(data);
            newData.slNo=(1*newData.slNo)+1;
            newData.revNo='2';
             $scope.gridOptions.data.splice(data.slNo,0,newData); //Tried this to insert data
            //$scope.gridOptions.data.push(newData); // Tried this to insert in to data 
             $scope.gridApi.selection.toggleRowSelection(newData); // Tried this to enable selection
                   // $scope.gridApi.selection.selectRow(newData); //tried this to enable selection
                     colDef.cellClass='txtChange'; //Tried to change color
            });
```

**Comment by c0bra** [comment]
Do you have an example plnkr you're working from, or could you create a simple one by using one of the tutorials as a template? Click the "edit in plunker" button on this page to start with this one: http://ui-grid.info/docs/#/tutorial/106_binding

That'll make it a lot easier to help you.

**Comment by hariharan01** [comment]
Hi,
Thank you for your response.
I have created a plunker and provided inline comments in js file to understand the reason and issue
http://plnkr.co/edit/bHj2Y7prNgcQhcWq9rU1?p=preview

**Comment by syedrehman** [comment]
Hi Bro..

I am import data from excel into angular UI grid . I would like to check whether there are duplicate record in a Grid before saving the data. Could any one help me out,

Thanks

**Comment by miteshvmehta** [comment]
Hi,
I have updated this plunker example to save copied row after the row selection. Heres the working example.
http://plnkr.co/edit/elL88pdRg4aMOfyHdq88?p=preview
