### ISSUE TITLE
Detecting cellEdit, cell click (without editing cell), row selection events in UI grid

### ISSUE THREAD

**Issue by piu** [angular-ui/ui-grid#3820]
Hi ,

I am using UI Grid( Unstable version) along with Angularjs(1.3.14), and facing some issues while implementing with UI- Grid.I need different behavior on cell click / column wise behavior you can say. What I require to do is as below: 

 1) First Column - I need it to be editable so using <b> "ui.grid.edit " </b> and using events  <b> "afterCellEdit "  </b>  for the same this works fine 

2)Second column-  in grid, I need to have custom implementation like deletion, etc and hence need click event of cell, for this I added  <b>  cell template and added ng-click </b>  to it but this never fires may be due to edit module 

3)  Row Selection- On row selection I need to perform custom action loading to different view , hence added  <b>  "ui.grid.selection"  </b>  module and used  <b> "rowSelectionChanged"   </b> event, but this fires even on cell edit event.

Is there any way/ module to<i> detect these different events<b> (cellEdit, cell click (without editing cell), row selection)</b> </i> ?

**Comment by c0bra** [comment]
1. What does your ng-click look like and where is the click handler defined? If it's on your controller's scope you'll need to use `appScope` in your template to access it: http://ui-grid.info/docs/#/tutorial/305_appScope
2. If you use row selection with the row header rather than clicking on the row then you should be able to only have the selection event fire when the row is selected. I don't think you can do cell clicks for row selection AND for editing (on double-click). I think they interfere but maybe @swalters could clarify that.

**Comment by piu** [comment]
Thanks Cobra !!
1) And yes for ng-click I had handler defined in the scope and it worked with appScope in my template. So issue with ng-click is solved :+1: 

2)  The row selection works but it interferes with editing event, so as of now I have defined new action button on whose click I am managing job that I needed to do on row click. But id there is a better way to handle row selection event without it interfering with edit events then please suggest.

**Comment by sumeetsonawane11** [comment]
Single click is not fire when click on the dropdown present in one of the cell template : 
I have custom dropdown in one of the cell Template with 5 values in it. Initially single click work on my custom dropdown but second time i need to double-click to ON the dropdown.

I have used enableCellEditOnFocus: true in the gridOption for the single click.

Please suggest some solution.

**Comment by himajaM** [comment]
Can you please anyone suggest me how to replace thousand separator comma while **editing wijmo flexgrid cell editing in angular 2**
