### ISSUE TITLE
footerCellClass function gets called only once

### ISSUE THREAD

**Issue by alam123** [angular-ui/ui-grid#3823]
I need a way to show footer sum in red for negative numbers and black with positive numbers. I am trying to achieve this using footerCellClass. The problem is that it gets called only once even before the data is loaded.

**Comment by c0bra** [comment]
I tried this with a plunker and it looks like the function is getting called post-filter, but one digest too late: http://plnkr.co/edit/M4r1RE029TnRD48uSvc3?p=preview

**Comment by alam123** [comment]
Hi @c0bra ,

I made a small change to fix this locally. It seems to work. 


In uiGridFooterCell directive, 

1) Comment the following lines
            //if ($scope.col.footerCellClass) {
            //  updateClass();
            //}
2) Listen to rowsRendered to call updateClass

$scope.grid.api.core.on.rowsRendered( $scope, $scope.col.updateAggregationValue );
$scope.grid.api.core.on.rowsRendered( $scope, updateClass );

$scope.$on( '$destroy', dataChangeDereg );
