### ISSUE TITLE
making the entire row clickable

### ISSUE THREAD

**Issue by boazin** [angular-ui/ui-grid#3829]
I want to add a custom code on a row click (selection is only on selection)
Isn't there a more elegant way to do it other than overriding rowTemplate (by copy pasting it from the code and add ng-click)?

It doesn't sound really forward compatible (ui-grid-row.html might change in the future)

**Comment by JLLeitschuh** [comment]
You could use directive stacking (like this project does) to add additional functionality to the row directive.
Have a look at how the [features](https://github.com/angular-ui/ng-grid/tree/master/src/features) do this.
