### ISSUE TITLE
paginationPageSizes breaks if rowHeight is a string

### ISSUE THREAD

**Issue by avatarr** [angular-ui/ui-grid#3832]
![screen shot 2558-06-22 at 09 57 09](https://cloud.githubusercontent.com/assets/1640817/8274915/2d1de8e4-18c5-11e5-88ca-7b6f9f79cf68.png)

I have problem about "paginationPageSizes: [20, 50, 75]" when I have change number of view item in a footer like below picture 
![screen shot 2558-06-22 at 09 58 32](https://cloud.githubusercontent.com/assets/1640817/8274929/7f4e598c-18c5-11e5-9cfa-7d552c3795fe.png)

I get error about data cannot show follow by number of change eg. I have set default size = 20 it seem to woke fine and when I change other number a table show my data just 7 items  

Thank you.
Best regard

**Comment by JLLeitschuh** [comment]
Can you provide a plunker demonstrating the issue?

**Comment by avatarr** [comment]
Here is a my plunker  http://plnkr.co/edit/JtVDdO?p=preview

**Comment by JLLeitschuh** [comment]
Its because your row height is a string instead of a number.
When you use `rowHeight:  45` instead of `rowHeight:  "45",` your example works fine.
See your example but fixed: http://plnkr.co/edit/BO1yLW?p=preview

**Comment by avatarr** [comment]
Thank you and sorry of my mistake :P :+1:

**Comment by JLLeitschuh** [comment]
I'm thinking that an error should be thrown in the case that it is passed a string instead of a number? This should be a relatively easy fix.
