### ISSUE TITLE
Possible bug of core.refresh queueGridRefresh and general all refresh api

### ISSUE THREAD

**Issue by ghost** [angular-ui/ui-grid#3833]
Hello i'm new to javascript,  angular, ui-grid.

I'm using the UI-Grid v3.0.0-rc.22, angular v1.4.1
i have the following code in my project

```
$scope.uigridOptions = {
    enableSorting: false,
    enableRowSelection: true,
    multiSelect : false,
    enableRowHeaderSelection: false,
    columnDefs : [
    { field: 'Address', displayName: 'Physical Input',cellTemplate: '<div class="ui-grid-cell-contents ng-binding ng-scope">&nbspCard {{row.entity.AddrCard}} Input {{row.entity.AddrPin}}</div>', width: '30%',
        cellClass: function(grid, row, col, rowRenderIndex, colRenderIndex) {                 
          if (row.entity.Mapped == true)    {return 'blue';}
        }               
    },
```

to show some 'mapped' records blue with the aid of css.

but when i change the array of objects that the grid is bound to the records that are 'mapped' do not appear blue. In order to appear blue i have to scroll the item beyond the visible area of grid and when i get it back the the grid shows it blue.
I tried to call some refresh methods to force the grid to update its contents with no luck such as..

```
$scope.gridApi.grid.refreshCanvas();
$scope.gridApi.core.queueGridRefresh();
$scope.gridApi.core.refresh();
```

from the api manual i think what i need is `refreshCanvas()`.

Is it a bug of ui-grid or am i doing something wrong??

Best regards to all

p.s. i have register in angular the following

```
var wt520rApp = angular.module('wt520r_App', [
    'ui.router',
    'ui.bootstrap',
    'ui.grid',
    'ui.grid.selection'
]); 
```

**Comment by JLLeitschuh** [comment]
I just pulled in a a PR to fix this #3809
Take a look at the newest unstable and see if this is still a problem.

**Comment by goleafs** [comment]
I don't know if this is related, but we are seeing now (using unstable) that once a row enters edit, and is saved, it remains disabled.  the setSavePromise code was not changed yet suddenly the row never exits isSaving regardless if the promise is resolved or rejected.

**Comment by hngm** [comment]
I download and used ui-grid - v3.0.0-rc.22-3253caf - 2015-06-24
and unfortunately did not fix my issue.

I run all of the below code after a modal has closed.

modalInstance.result.then(function (ReturnData) {
  $scope.gridApi.core.queueGridRefresh();
  $scope.gridApi.core.refresh();
  $scope.gridApi.grid.refreshCanvas();
  $scope.gridApi.grid.refreshRows();
}

since i have also doubts of my code, i will continue experimenting and get back to you.

Thank you for you time and efforts
Best regards
