### ISSUE TITLE
ui-grid translation issues

### ISSUE THREAD

**Issue by loykianos** [angular-ui/ui-grid#3835]
Greetings, I have just stumbled upon a translation issue, where my grid is translated partially. 
The sort option menu seems to be translated correctly, but the pagination for example isn't. 

It looks like a refresh issue, since if I change the ui-router state and then return to the grid, it is translated correctly. But if the page is loaded entirely, the problem is back as shown bellow.

When initialized:

![beforegrid](https://cloud.githubusercontent.com/assets/4227423/8281997/8ba9368e-18ed-11e5-9074-8d071b2848c6.JPG)

after switching through states:

![aftergrid](https://cloud.githubusercontent.com/assets/4227423/8282001/998b4bac-18ed-11e5-9848-b7dfdd5a42da.JPG)

Let me also add that this only happens on a certain situation, which to be honest, I can't explain why.

**Comment by JLLeitschuh** [comment]
This looks like an initialization issue in your code. If you can provide a minimalist plunk demonstrating the issue we may be able to help you more.
