### ISSUE TITLE
Broken Stable/Unstable version selector in docs

### ISSUE THREAD

**Issue by JLLeitschuh** [angular-ui/ui-grid#3838]
I goofed up and didn't test this before making the PR. (Sorry)
The version selector (stable/unstable) in the docs has stopped working. It causes a large sequence of JS errors in the dev console.

**Comment by c0bra** [comment]
Did it ever work?

**Comment by PaulL1** [comment]
I thought it gave the wrong result (hence #3444), but I didn't think it gave console errors (although I don't remember specifically looking at that).

**Comment by JLLeitschuh** [comment]
I thought it used to work prior to my update.

**Comment by mportuga** [comment]
I see no console errors any more, so closing this issue. I will keep #3444 though.
