### ISSUE TITLE
Calling gridApi.treeBase.expandAllRows when gridOptions.data is still undefined

### ISSUE THREAD

**Issue by billyaraujo** [angular-ui/ui-grid#3841]
Calling expand all rows gives me this error in console although rows are expanded.

```
TypeError: grid.treeBase.tree.forEach is not a function
    at Object.service.expandAllRows (ui-grid.js:23896)
    at Grid.service.initializeGrid.publicApi.methods.treeBase.expandAllRows (ui-grid.js:23478)
    at Object.module.service.s.createBoundedWrapper [as expandAllRows] (ui-grid.js:9738)
    at projects.js:233
    at angular.js:14014
    at completeOutstandingRequest (angular.js:4300)
    at angular.js:4601
```

**Comment by JLLeitschuh** [comment]
What version of angular are you running?

**Comment by billyaraujo** [comment]
Angular version: 1.2.16

**Comment by JLLeitschuh** [comment]
Could you provide a plunker with a demo of this issue?

**Comment by billyaraujo** [comment]
http://plnkr.co/edit/7NxnBSyHAtowdnzwvM8P?p=preview

````
TypeError: Cannot read property 'treeBase' of undefined
    at app.js:22
    at angular.js:16380
    at completeOutstandingRequest (angular.js:4940)
    at angular.js:5328(anonymous function) @ angular.js:11699$get @ angular.js:8628(anonymous function) @ angular.js:16383completeOutstandingRequest @ angular.js:4940(anonymous function) @ angular.js:5328
editor-0.7.78.js:2 Event tracked Plunk Save Toolbar undefined undefined
```

**Comment by billyaraujo** [comment]
http://plnkr.co/edit/7NxnBSyHAtowdnzwvM8P?p=preview

```
TypeError: grid.treeBase.tree.forEach is not a function
    at Object.service.expandAllRows (ui-grid-unstable.js:24229)
    at Grid.service.initializeGrid.publicApi.methods.treeBase.expandAllRows (ui-grid-unstable.js:23811)
    at Object.module.service.s.createBoundedWrapper [as expandAllRows] (ui-grid-unstable.js:10054)
    at app.js:21
    at angular.js:14014
    at completeOutstandingRequest (angular.js:4300)
    at angular.js:4601(anonymous function) @ angular.js:9778$get @ angular.js:7216(anonymous function) @ angular.js:14017completeOutstandingRequest @ angular.js:4300(anonymous function) @ angular.js:4601
```

**Comment by JLLeitschuh** [comment]
This a bit more complicated than that. We would need to flag that expand all has been called an then expand it as the data value is updated.

**Comment by billyaraujo** [comment]
It would be good if you could just call like this:
      $scope.gridOptions.data = data;
      $scope.gridApi.treeBase.expandAllRows();

i.e. without timeout or have an autoexpand option in gridOptions.

**Comment by JLLeitschuh** [comment]
You need to wait for a digest cycle to complete before the data is actually loaded into the grid.
Here's an alternative workaround will get you what you want.
```
$scope.gridOptions.data = data;
$timeout($scope.gridApi.treeBase.expandAllRows);
```
What you really want is an option under grouping to start all expanded. This could potentially be an enhancement for the future.

**Comment by billyaraujo** [comment]
Yes, ideally would be the use of autoexpand option.

**Comment by vinograt** [comment]
in angular 1.4.4 a call:
```
$scope.gridOptions.data = data;
$timeout($scope.gridApi.treeBase.expandAllRows);
```
*sometimes* kills all the rows in grid (`$scope.gridApi.grid.rows` became `[]`)

**Comment by reemasaluja** [comment]
I am calling $scope.gridApi.treeBase.expandRow(selection)

selection: selected row:

Its not working,

**Comment by billyaraujo** [comment]
Just to add something, the $timeout option does not always work because you have to adjust the timeout time, which is a bit tricky.

**Comment by billyaraujo** [comment]
@reemasaluja 
          $scope.gridApi.treeBase.toggleRowTreeState($scope.gridApi.grid.renderContainers.body.visibleRowCache[0]);

**Comment by reemasaluja** [comment]
@billyaraujo : Thanks. Worked like a charm.

**Comment by PaulL1** [comment]
This is a useful request, but not really in the current roadmap.  We have far too many good ideas in the repository already, giving the impression that we have a project riven with defects.

Accordingly, I am leaving the enhancement tag on this, but closing it.  If someone would like this functionality, we'd welcome a pull request that adds it.

**Comment by cerdman** [comment]
The tree does not work properly even when resolving the promised data ahead of time. The behavior is indeterminate with large / network latent datasets.
