### ISSUE TITLE
Export to PDF not working

### ISSUE THREAD

**Issue by laduran** [angular-ui/ui-grid#3845]
I put a plunkr here: http://plnkr.co/edit/bFIZiUyO8BKjG5BV7xlA?p=info

Read the README.md file in the plunkr for steps to repro and actual/expected results.

Exporting sample data doesn't work for me. I was trying to reproduce a more specific problem that I saw in an earlier version of ui-grid which was that PDF files were not created when there were too many rows of data in my grid. HOwever, it appears now, export isn't working at all.

I also pulled my plunkr locally and ran it in WebStorm and I see the same problem happening.
Using rc22 version of ui-grid and 1.3.16 of Angular. I can attach a ZIP file of that project if it will help.

By the way, export to CSV seems to work OK.

OK. Just running the sample from here: http://ui-grid.info/docs/#/tutorial/206_exporting_data
I see the same issue.

**Comment by c0bra** [comment]
It's working for me in Chrome. Are you in IE, perchance? There's documented issues with creating PDFs with pdfmake.js in IE. I think we have a few issues for that.

**Comment by laduran** [comment]
Sorry, I should have indicated the browser. I am using Chrome build Version 42.0.2311.152 (64-bit)

**Comment by PaulL1** [comment]
It also works for me fine in Chrome within your plunker, and on the tutorial.  Is it working for you on the tutorial?  I know that plunker can sometimes give issues due to being in frames, although in this case that  doesn't seem to be the problem.  Perhaps some sort of Chrome security setting or popup blocker?  Do you get a console error of any sort?

**Comment by vijender1256** [comment]
@PaulL1 , @c0bra  I am using IE 11 and export to CSV works fine, but export to PDF is not working. Is this a bug ? I cannot export pdf in IE. Please reply at your earliest convenience.

**Comment by PaulL1** [comment]
It's supposed to be working, but it's never been tested that I'm aware of (I don't have IE).  What error are you getting?

**Comment by vijender1256** [comment]
@PaulL1  I am getting this error in my console

TypeError: Unable to get property 'Roboto-Italic.ttf' of undefined or null reference

but i added vfs_fonts.js, pdfmake.min.js to my bundle, i dont understand the error :)

**Comment by PaulL1** [comment]
Looks to me like it's trying to use a font that you haven't got installed.  I don't think that's the vanilla behaviour - is it working for you on the tutorials?  If so, perhaps you've used a font that's non-standard?

**Comment by vijender1256** [comment]
@PaulL1  For pdf export i need to have pdfmake.js to be installed  and I have done it and included in the scripts. and Roboto-Italic.ttf is in vfs_fonts.js and I have followed below tutorial:

https://github.com/angular-ui/ui-grid/blob/master/misc/tutorial/206_exporting_data.ngdoc

Thanks.

**Comment by PaulL1** [comment]
Yes, but does it work for you on the tutorial.  My question here is trying to work out whether it's broken in general terms (perhaps with your specific brower, or perhaps master has become broken recently), or whether it's something specific to your installation or your code.  If it's something specific to your code, then the next step will be to create a plunker, and see if that is also broken.

**Comment by vijender1256** [comment]
@PaulL1  it works fine in the tutorial with my browser, seems like its not the browser problem. but for some reason it gives me that error and I also mentioned the version of ui-grid i am using. Thanks for the reply

**Comment by PaulL1** [comment]
OK, then as expected we'll need to create a plunker.  Obviously I cannot debug an error that's only present on your local install.  :-)  

Most likely given it seems to be missing a font is some form of installation error, so perhaps you could work out which code file that error happens in, put a breakpoint in, and work out what object it expects to contain that font, and see if you can work out where it's expecting those fonts to be.

**Comment by vijender1256** [comment]
@PaulL1 Thank you, here is what i found out:
when i reference the script files directly in my _Layout.cshtml page it works alright:

   script src="~/Scripts/pdfmake.js"></script>
   script src="~/Scripts/vfs_fonts.js"></script>

Howerver when I am trying to register them in BundleConfig.cs, I am getting all sorts of errors. Seems like this is a bug I dont know but direct reference works but referecing through:

 bundles.Add(new ScriptBundle("~/bundles/pdfmake")
                          .Include("~/Scripts/pdfmake.js", "~/Scripts/vfs_fonts.js"));

and adding as 

@Scripts.Render("~/bundles/pdfmake") throws errors. Please let me know your thoughts :) and this article say the same:

https://github.com/angular-ui/ui-grid/blob/master/misc/tutorial/206_exporting_data.ngdoc

**Comment by PaulL1** [comment]
I think there is nothing left in here to resolve.....closing.
