### ISSUE TITLE
Unit test application that uses ui-grid

### ISSUE THREAD

**Issue by iyel** [angular-ui/ui-grid#3853]
What is the best approach to unit test controller which uses ui-grid?

**Comment by c0bra** [comment]
Are you wanting to actually unit test or do e2e tests on the resulting grid?

**Comment by jasonwr** [comment]
@c0bra please provide an example of a ui-grid unit test with Jasmine and an e2e with Protractor. I need to test the onRegisterApi internal function.

**Comment by mportuga** [comment]
@jasonwr All protractor tests are a part of the tutorial
See the End to End tab on the "Intro to ui-grid" page for example: http://ui-grid.info/docs/#/tutorial/101_intro

As for a Jasmine test, you can check most features unit tests.

**Comment by jasonwr** [comment]
👎
