### ISSUE TITLE
IE9 ui-grid column headings (titles) misaligned

### ISSUE THREAD

**Issue by hsiraj555** [angular-ui/ui-grid#3854]
IE 9 does not align the columns titles properly on top of each column. Furthermore, text-overflow:ellipsis does not work on column heading.

![ui-grid-ie9issue](https://cloud.githubusercontent.com/assets/13005510/8336743/8d8f226e-1a74-11e5-9a4b-689576fe27f0.png)

This issue can be observed by resizing the columns in following link using IE9:
http://ui-grid.info/docs/#/tutorial/204_column_resizing

I would appreciate if somebody has any idea why is this and what's the solution.

**Comment by c0bra** [comment]
I think IE9 has problems with the table-cell display type and max/min widths as we use them. Not sure if there's <IE10 styles that we can apply to fix it without breaking other things...

**Comment by joseabraham99** [comment]
@c0bra Have you find any solution for this alignment issue.

Thanks

**Comment by c0bra** [comment]
I have not had a chance to look at it yet.

**Comment by Bv202** [comment]
Hey,

Have you had a look at this issue already? I have exactly the same problem. In the meanwhile, is there some sort of workaround available?

Thanks!

**Comment by anandvihar** [comment]
Hi,

I am also facing the same problem. Please help me with providing some workaround.

**Comment by anandvihar** [comment]
@c0bra 
Hi,

Any update on this. This also happens if we increase the number of columns .

**Comment by Bv202** [comment]
Yup, this bug is very annoying and we're urgently looking for a fix here.

**Comment by chuge** [comment]
@hsiraj555 I fix it by a trick, bellow is the CSS. But I do not figure out the reason caused the bug. You can use this as temporary solution before the bug fixed.

.ui-grid-header-cell-wrapper {
          display: block;
 }

.ui-grid-header-cell-row {
          display: block;
 }
.ui-grid-header-cell {
          display: block;
          float: left;
}

**Comment by c0bra** [comment]
@chuge Thanks; I've included this in a IE9-only condcom.

**Comment by JLLeitschuh** [comment]
This was not fixed. This PR broke the build.

**Comment by prksean** [comment]
Hello, any update on this issue? I see this happening in Chrome as well.

**Comment by okonon** [comment]
same issue here adn @chuge 's workaround worked for me.

**Comment by SumeetKhandre** [comment]
Hi, the same issue is happening in Chrome browser also. Its happening because when we click on tab by navigating cursor in Inline filter, When it goes to last column, after that the alignment is not proper. When we scroll from left to right then it will work fine.

Please help us to resolve.

**Comment by adrianviegas** [comment]
Similar issues
#5629 
#6041
#4944

**Comment by mportuga** [comment]
Removed IE9 support.

**Comment by raghavs280** [comment]
The below css fixes the issue but it removes the filtering row in the Ui-grid
.ui-grid-header-cell-wrapper {
display: block;
}

.ui-grid-header-cell-row {
display: block;
}

.ui-grid-header-cell {
display: block;
float: left;
}

**Comment by apjaga** [comment]
To solve the header alignment issue add below mentioned code in your "ts" file
  onGridReady(params) {
        this.gridApi.sizeColumnsToFit();
    }
