### ISSUE TITLE
Checkbox doesn't select row (model)

### ISSUE THREAD

**Issue by LeonanCarvalho** [angular-ui/ui-grid#3869]
Until 3.0 isn't stable i'm using ngGrid yet and  I realize if I check a grid value using checkbox it's not  selected in rows model.

```html
<div class="ngSelectionCell"><input tabindex="-1" class="ngSelectionCheckbox" type="checkbox" ng-checked="row.selected"/></div>
```
We must use ng-model with ng-selected to be possible select using row click and checkbox click.
```html
<div class="ngSelectionCell"><input tabindex="-1" class="ngSelectionCheckbox" type="checkbox" ng-checked="row.selected" ng-model="row.selected"/></div>
```

Looking for confirmation.

**Comment by c0bra** [comment]
If it works for you then I'd say you're good. 2.x isn't likely to change at all.

**Comment by LeonanCarvalho** [comment]
Recently I had an experience where the user can select at ngRow and the checkbox by clicking exactly on the checkbox, as the event does not spread to the ngRow, then went in search of the cause and this was because by clicking the checkbox column nothing happened .

I need a confirmation if the use of ng-checked with the ng-model would redundant.

Anyway, in my opinion, ng-model is the best of the options.

**Comment by AgDude** [comment]
This issue was moved to angular-ui/ng-grid-legacy#5
