### ISSUE TITLE
ui-grid-selection directive race condition when ui.grid required twice

### ISSUE THREAD

**Issue by viveleroi** [angular-ui/ui-grid#3870]
In order to globally turn of all ui-grid debug logging, I was going to configure it in our root-level application module:

```
define(['angular', 'angularUIGrid'], function(angular) {
    var module = angular.module('ourApp', ['ui.grid']);

    module.config(['debug', 'uiGridConstants', function(debug, uiGridConstants) {
        uiGridConstants.LOG_DEBUG_MESSAGES = false;
        uiGridConstants.LOG_WARN_MESSAGES = debug;
    }]);
});
```

However, I began seeing a random and unpredictable error (likely a race condition, but I can't determine what would cause it) in our pages, which actually show the grids:

```
TypeError: Cannot read property 'on' of undefined
    at Object.$scope.gridOptions.onRegisterApi
```

The root-level controller really doesn't do anything other than define some constants, setup our environment. Each page controller sets up any grids:

```
define(['angular', 'angularUIGrid'], function(angular) {
    var module = angular.module('ourApp.module', ['ui.grid', 'ui.grid.selection']);

    module.controller('SomePageController', function($scope) {
        $scope.gridOptions = {
            onRegisterApi: function(gridApi) {
                // call to gridApi.selection.on.rowSelectionChanged
            }
        };
    })
});
```

The error goes away as soon as I remove the include of `ui-grid` from the root module, _or_ if I include `ui.grid.selection` at the root level too.

In debugging, it seems that when the error occurs, the ui-grid-selection directive `compile:pre` logic never fires - as if the module wasn't included. I'm unclear how that's possible because the page with the grid requires both `ui.grid` and `ui.grid.selection`.

**Comment by c0bra** [comment]
Do you have the full stack trace of the exception?
