### ISSUE TITLE
Currency symbols missing in ng-grid/src/js/core/constants.js

### ISSUE THREAD

**Issue by MattiJarvinen-BA** [angular-ui/ui-grid#3885]
`ng-grid/src/js/core/constants.js`

has TODO(c0bra): Create full list of these somehow. NOTE: do any allow a space before or after them?

Here's a list.
https://en.wikipedia.org/wiki/Currency_symbol#List_of_presently-circulating_currency_symbols

**Comment by c0bra** [comment]
Thanks @MattiJarvinen-BA. Are you perhaps interested in doing a PR? :)

**Comment by MattiJarvinen-BA** [comment]
Got my hands full at the moment and this is not critical in any way so I'm going to be a lazy bastard and say I'll pass but might do it in couple of months if this is still open.
