### ISSUE TITLE
Pinned columns are not included in export of visible data.

### ISSUE THREAD

**Issue by anilnatha** [angular-ui/ui-grid#3888]
I have encountered a bug when the "Export visible data to csv" option in the grid menu is chosen when the grid is using pinned columns. The problem is that if you have either the 'pinnedRight' or 'pinnedLeft' columndef options set, and choose the option 'Export visible data to csv" in the grid menu, the pinned columns will _not_ be exported to CSV. 

I tried the following to resolve the issue:
1. Setting the 'visible' columndef option for the two columns to 'true', but the problem persisted.
2. Setting the 'exporterSuppressExport' columndef option to false for the columns, but the problem persisted.

For both attempts listed above, I verified that this issue was due to the pinning properties, by removing the 'pinnedRight' and 'pinnedLeft' properties and sure enough, once removed, the columns exported just fine with the 'Export visible data to csv'

Based off the [pinning tutorial](http://ui-grid.info/docs/#/tutorial/203_pinning), I created a plunker example showcasing the issue which you can view [here](http://plnkr.co/edit/8U4I6nUKlcGDxYiztNr3?p=preview).

I first noticed this issue on my development machine, which is running the following:

Windows 7 Enterprise
UI-Grid: [v3.0.0-rc.22](https://github.com/angular-ui/ng-grid/releases/tag/v3.0.0-rc.22)
Angular: 1.3.16
Browsers:
 1. Chrome (Version 43.0.2357.130 m)
 2. Firefox ESR (version 31.7) which is equivalent to Firefox 38

Notes:
1. I have not tried the export of visible data to PDF, so it is entirely possible that this functionality may be working or may not be working with PDF exports.
2. For the application I am working on, I have two pinned columns, one of which needs to be exported, the other will be suppressed, so it's important that even if a user chooses the 'export visible data' option, that both the ''exporterSuppressExport' columndef option or the 'exporterSuppressColumns' gridoption still continue to suppress columns as needed.

**Comment by lebolo** [comment]
I've also encountered this bug during csv exporting.

Windows 7
Google Chrome 43.0.2357.132 m
UI Grid v3.0.0-rc.22
AngularJS 1.4.2

**Comment by PaulL1** [comment]
I suspect the problem is that visible data is exported from the body container.  It needs modifying to export left (if present), then body, then right (if present).

**Comment by sonphuong** [comment]
could you please tell me how to fix this? I need that

**Comment by JLLeitschuh** [comment]
This should be taken care of in the most recent release (3.0.6). If its not please feel free to reopen.

**Comment by anilnatha** [comment]
Thank you @JLLeitschuh for the status update and resolution. I'll try it out and report back in the coming days.

**Comment by dennym** [comment]
@JLLeitschuh Since anilnatha didn't reply back I take a step in. Upgraded to latest in bower available version 3.0.7 and it doesn't work for me. The pinned column is still not collected when exporting csv.

**Comment by anilnatha** [comment]
I've tested version 3.1.1 in my app and I can confirm that I can now export visible data for pinned columns.
