### ISSUE TITLE
Rare test failure from ui.grid.utilService.throttle

### ISSUE THREAD

**Issue by JLLeitschuh** [angular-ui/ui-grid#3890]
Every 1 in 100 times that I compile I get the following test failure.

```
PhantomJS 1.9.8 (Mac OS X 0.0.0) ui.grid.utilService throttle() prevents multiple function calls FAILED
    Expected 2 to equal 1.
    Expected 2 to equal 1.
```

Launching the build again without changes fixes the issue.

**Comment by JLLeitschuh** [comment]
This is actually not happening so rarely anymore.

**Comment by c0bra** [comment]
Does it happen if you test in a browser other than PhantomJS?

**Comment by JLLeitschuh** [comment]
I don't try it enough that way. This is when I'm running `grunt dev --fast`.
