### ISSUE TITLE
Grid state not restored when the grid is toggled between 2 tabs in ng-if

### ISSUE THREAD

**Issue by AdityaJitu** [angular-ui/ui-grid#3892]
Hi,
I am using v3.0.0-RC.18-92a8836 of UI-Grid.
I am having grid each in a single tab. As such I am having two tabs.  I am trying to save the state of the grid as & when the user changes the tabs.
Suppose the user resized the column of the grid in first tab then before moving to the 2nd tab I am saving the grid State in localStorage.
Then again after moving to the first grid I am trying to apply the state the I have saved in localStorage using the restoreState() function but the changes are not getting displayed.

I am toggling the grids using ng-if so that in DOM only a single grid persists.

**Comment by MattOakley** [comment]
Try this directive rather than ng-if.

This works as the scope isn't trashed.

 directive('gridSize', function ($timeout, gridUtil) {
     return {
        require: 'uiGrid',
        scope: true,
        link: function ($scope, $elm, $attr, uiGridCtrl) {

            function size() {
                var newGridHeight = gridUtil.elementHeight($elm);
                var newGridWidth = gridUtil.elementWidth($elm);

                uiGridCtrl.grid.gridHeight = newGridHeight;
                uiGridCtrl.grid.gridWidth = newGridWidth;

                uiGridCtrl.grid.queueGridRefresh();
            }

            var deReg = $scope.$watch($attr.gridSize, function(n, o) {
                if (!n) {
                    return;
                }

                size();
            });
          
                
            $scope.$on('$destroy', function () {
                deReg();
            });
        }
    };
 });

**Comment by PaulL1** [comment]
I think we'd need a plunker to help much with this.  saveState and restoreState appear to still be working fine, so presumably it's something in the way that you're applying it.

**Comment by AdityaJitu** [comment]
@Paul1 
It is working fine.  It was a minor mistake from my side.  Therefore I am closing this ticket.
