### ISSUE TITLE
Programmatically supplying column filter value

### ISSUE THREAD

**Issue by dekhaus** [angular-ui/ui-grid#3894]
Hi All. 

First time here / new ui-grid user. Really like it. 

Is it possible to programmatically supply the value of a column's filter? 

I have two ui-grids - one on page 1 and the other on page 2. 

I have a link in each row of a ui-grid on page 1 to page 2 and I'd like to pass along a parameter that pre-populates one of the column filters in the ui-grid on page 2. 

Thanks Dave

**Comment by JLLeitschuh** [comment]
There is a method in the public api that may be helpful: http://ui-grid.info/docs/#/api/ui.grid.core.api:PublicApi
`clearAllFilters()`
The documentation may need to be updated a bit.
I think that that function supports parameters.
Take a look at the raw documentation for the params https://github.com/angular-ui/ng-grid/blob/8f0cf4c/src/js/core/factories/Grid.js#L436

**Comment by PaulL1** [comment]
The filter tutorial provides an example of setting filters programmatically.  There are two tricks here:

1.  When setting it on a new grid, you can set colDef.filter, or colDef.filters[0].
2.  When setting it on a grid that is already rendered, you need to set it on the columns themselves - we don't overwrite current filter settings when you change the colDef filter, as the user may have changed them manually.  So set column.filters[0].
