### ISSUE TITLE
How to reload data received async?

### ISSUE THREAD

**Issue by darknos** [angular-ui/ui-grid#39]
When my page is loading I don't have any data available. Just requested it from cloud so I need to fill grid after data received.

I tried to "refresh" grid data by using $scope.$apply but without success...  :(

Did I missed something?

**Comment by arfankgp** [comment]
This plunker shows how to refresh ui-grid based on different data source. 
Note the use of columnDefs for declaring view based on data.  
http://plnkr.co/edit/6khgBVXnIXMDPjSSwLgl?p=preview
