### ISSUE TITLE
When "." present in data key then value doesn't appear in column

### ISSUE THREAD

**Issue by nishant8BITS** [angular-ui/ui-grid#3900]
I have header which contains "." in column header so when I tried with below data to see grid then S.No value is not present in column, But when I remove . from S.No then I am able to see the value for reproducing the issue I have added plnkr link.
   
Not Working for Below Data: 
```
    {
        "Marks": "15",
        "Name": "SONTI VENKATA SEETHARAMA KATYA .",
        "Practical Section": "P3",
        "S.No": "609",
        "Student ID": "2014A1PS264P",
        "id": 1
    }
```
Working For below Data: 
```
     {
        "Marks": "15",
        "Name": "SONTI VENKATA SEETHARAMA KATYA .",
        "Practical Section": "P3",
        "S No": "609",
        "Student ID": "2014A1PS264P",
        "id": 1
     }
```
Issue Demo:  http://plnkr.co/edit/sMFnQnZ7rVzPlxkIh3LG?p=preview

**Comment by JLLeitschuh** [comment]
That is probably because the dot operator has special meaning in angular.
You need to use the colDefs property in your grid options to get the `.` symbol to show up in the header text.

**Comment by nishant8BITS** [comment]
@JLLeitschuh  Thanks for your reply, But are assigning column header dynamically , we don't have predefined or static column header name.

**Comment by nishant8BITS** [comment]
@JLLeitschuh  : I found that when Field name contains . operator then it's assign type as Object even after value is type of string in first row, So I find type of field using typeof and then assign colDef.type , 

Below Modified code: 
```
  /**
   * @ngdoc function
   * @name assignTypes
   * @methodOf ui.grid.class:Grid
   * @description uses the first row of data to assign colDef.type for any types not defined.
   */
  /**
   * @ngdoc property
   * @name type
   * @propertyOf ui.grid.class:GridOptions.columnDef
   * @description the type of the column, used in sorting.  If not provided then the 
   * grid will guess the type.  Add this only if the grid guessing is not to your
   * satisfaction.  One of:
   * - 'string'
   * - 'boolean'
   * - 'number'
   * - 'date'
   * - 'object'
   * - 'numberStr'
   * Note that if you choose date, your dates should be in a javascript date type
   *
   */
  Grid.prototype.assignTypes = function(){
    var self = this;
    self.options.columnDefs.forEach(function (colDef, index) {

      //Assign colDef type if not specified
      if (!colDef.type) {
        var col = new GridColumn(colDef, index, self);
        var firstRow = self.rows.length > 0 ? self.rows[0] : null;
        if (firstRow) {
          if(col.field.indexOf('.') !== -1){
            colDef.type = typeof(firstRow.entity[col.field]);
          }else{
            colDef.type = gridUtil.guessType(self.getCellValue(firstRow, col));
          }
        }
        else {
          gridUtil.logWarn('Unable to assign type from data, so defaulting to string');
          colDef.type = 'string';
        }
      }
    });
  };

```

Still not working :( Any Idea I want to make it work even after . is present any help appreciated.

**Comment by masrawi** [comment]
I have the same problem. here is the plnkr http://plnkr.co/edit/K9K85Fr5143J6WE7ZRwu?p=preview

type assigned with no effect :-(

**Comment by JLLeitschuh** [comment]
Can you get a separate header object that has a list of headers and the header values you actually want.
This seems like an edge case that has a very simple work around.

**Comment by masrawi** [comment]
my use case is really simple. I have a header name with dots like ‚parent.name’ it is just a string and the value will come with the field {‚parent.name‘:‘test’} or even ‚parent.child.name‘ as name. so what is the workaround for this. This problem seems to be a showstopper for us

**Comment by PaulL1** [comment]
In general you cannot have a field name that has dots in it, the grid assumes this means you have a nested object (because we allow nested objects).

Exceptions here may be (you'd have to try):
 - using fastwatch and flatEntity may let you have names with . syntax in them
 - you could have a displayName with the . and the actual object name without
 - you could rename in code before passing to ui-grid

**Comment by masrawi** [comment]
thanks @PaulL1 setting flatEntityAccess:true on the gridOptions did the trick

**Comment by imbalind** [comment]
Closing as it look ok.

**Comment by windmaomao** [comment]
Amazing flag, "flatEntityAccess", whatever it is, it does the job !! thanks @masrawi

**Comment by letsbecometechie** [comment]
This worked for me.
https://github.com/angular-ui/ui-grid/issues/3900#issuecomment-135871898
