### ISSUE TITLE
Hide column method in api

### ISSUE THREAD

**Issue by zaknuces** [angular-ui/ui-grid#3902]
I need to hide / show columns of the grid after it is loaded (based on some permissions). I wasn't able to find a method in the grid api to call that can do it for me. 

As a workaround, i am doing what hide column context menu is doing. Something like:

```
this.gridApiInterface.grid.columns[0].colDef.visible = hasDeletePermission;
this.gridApiInterface.grid.columns[0].visible = hasDeletePermission;
this.gridApiInterface.grid.queueGridRefresh();
                    this.gridApiInterface.grid.api.core.notifyDataChange(uiGridConstants.dataChange.COLUMN);                    this.gridApiInterface.grid.api.core.raise.columnVisibilityChanged(this.gridApiInterface.grid.columns[0]);
```

Having a quick method to do it would help.

Secondly, it will also be worthwhile to expose method to update 'enableRowHeaderSelection' property to control the visibility of selection column.

**Comment by lpand** [comment]
https://github.com/angular-ui/ng-grid/blob/master/src/js/core/factories/Grid.js#L102
```Javascript 
grid.columns
 ```
https://github.com/angular-ui/ng-grid/blob/master/src/js/core/factories/GridColumn.js#L116
```Javascript
col.hideColumn()
```
https://github.com/angular-ui/ng-grid/blob/master/src/js/core/factories/GridColumn.js#L838
```javascript
col.showColumn()
```

**Comment by dabedur** [comment]
Thanks @lpand! Not sure who manages the ui-grid.info site, but it would be lovely if the [tutorial on adding/removing columns](http://ui-grid.info/docs/#/tutorial/113_adding_and_removing_columns) mentioned these extremely helpful functions.

**Comment by lpand** [comment]
I'm glad i helped you. Hey, you could make a pull request to fix that :).

**Comment by zaknuces** [comment]
Doing col.hideColumn or col.showColumn doesn't update the visible state of the column sometimes. I am unable to reproduce this behaviour consistently. However, when i add the following after showColumn or hideColumn:

grid.api.core.notifyDataChange(uiGridConstants.dataChange.COLUMN); 

it seems to work every time.

Is there any relation between them that is causing race condition?
