### ISSUE TITLE
SelectAll ChildRow with in group

### ISSUE THREAD

**Issue by susharma-equinix** [angular-ui/ui-grid#3911]
Hi All,

Is there an option to select all child rows with in the grouped column 
![actual](https://cloud.githubusercontent.com/assets/12180266/8470342/277866b8-20bc-11e5-9b67-3870be1daac2.jpg)

Please check the highlighted area in the image, When ever user clicks there all the child rows under that should be selected.

Let me know if this can actually be an enhancement it would be a wonderful feature to the grid where user can group the columns and select child rows i.e. selectAll under each column and perform desired operations.

**Comment by susharma-equinix** [comment]
Am doing something similar using this : 
$scope.gridOptions1.onRegisterApi = function (gridApi) {
		$scope.gridApi = gridApi;
		$scope.gridApi.selection.on.rowSelectionChanged($scope, function (row) {
			
			if(row.internalRow==true && row.isSelected==true){
				var childRows	= row.treeNode.children;
				for (var j = 0, length = childRows.length; j < length; j++) {
					var rowEntity	= childRows[j].row.entity;
					$scope.gridApi.selection.selectRow(rowEntity);
				}
			}
			
			if(row.internalRow==true && row.isSelected==false){
				var childRows	= row.treeNode.children;
				for (var j = 0, length = childRows.length; j < length; j++) {
					var rowEntity	= childRows[j].row.entity;
					$scope.gridApi.selection.unSelectRow(rowEntity);
				}
			}
			
		});
	}

**Comment by susharma-equinix** [comment]
I have also achieved this by using the below functions :

$scope.gridOptions1.onRegisterApi = function (gridApi) {
		$scope.gridApi = gridApi;
		$scope.gridApi.selection.on.rowSelectionChanged($scope, function (row) {
			if(row.internalRow==true && row.isSelected==true){
				var childRows	= row.treeNode.children;
				for (var j = 0, length = childRows.length; j < length; j++) {
					selectAllChildren($scope.gridApi,childRows[j]);
				}
			}
			
			if(row.internalRow==true && row.isSelected==false){
				var childRows	= row.treeNode.children;
				for (var j = 0, length = childRows.length; j < length; j++) {
					unSelectAllChildren($scope.gridApi,childRows[j]);
				}
			}
			
		});
	}
	
	function selectAllChildren(gridApi,rowEntity){
		if(rowEntity.children.length==0){
			gridApi.selection.selectRow(rowEntity.row.entity);
		}else{
			var childrens = rowEntity.children;
			for (var j = 0, length = childrens.length; j < length; j++) {
				selectAllChildren(gridApi,childrens[j]);
			}
		}
	}
	
	function unSelectAllChildren(gridApi,rowEntity){
		if(rowEntity.children.length==0){
			gridApi.selection.unSelectRow(rowEntity.row.entity);
		}else{
			var childrens = rowEntity.children;
			for (var j = 0, length = childrens.length; j < length; j++) {
				unSelectAllChildren(gridApi,childrens[j]);
			}
		}
	}

**Comment by lst88** [comment]
+1 on having this feature enabled.
Was there a specific reason this feature was disabled?

"Group header rows cannot be edited, and if using the selection feature, cannot be selected. "

**Comment by patriciocordova** [comment]
+1

**Comment by doctorsender** [comment]
+1

**Comment by monster910** [comment]
+1

**Comment by yadimon** [comment]
+1

**Comment by AjayanandLad** [comment]
+1

**Comment by alexey-vasyunin** [comment]
+1

**Comment by veica** [comment]
+1

**Comment by kamal-bhatt** [comment]
How can I select gropu level and travers all children?

**Comment by renfengmei** [comment]
+1
why not merged to master?

**Comment by jawaharlalt** [comment]
+1

**Comment by Kononchuk-B** [comment]
Hey, guys, I have achieved this with the next  code:
`
onRegisterApi: function (gridApi) {
                $scope.gridApi = gridApi;

                $scope.gridApi.selection.on.rowSelectionChangedBatch($scope, function (rows) {
                    rows.forEach(childRow => $scope.proceedParentSelection(childRow));
                });

                $scope.gridApi.selection.on.rowSelectionChanged($scope, function (row) {
                    $scope.proceedParentSelection(row);
                });

                $scope.proceedParentSelection = function(childRow) {
                    let parentRow = childRow.treeNode.parentRow;
                    parentRow.isSelected = parentRow.treeNode.children.every(child => child.row.isSelected)
                }
            }
`

**Comment by WuYouyan** [comment]
I don't recommend to use `gridApi.selection.unSelectRow` or `gridApi.selection.selectRow`, because they will call `toggleRowSelection()`, which will also raise  `rowSelectionChanged()`, so I prefered to use `GridRow.prototype.setSelected(boolean)` to select or un select row
