### ISSUE TITLE
cellNav navigate event fires two times on first click on cell in grid

### ISSUE THREAD

**Issue by dalibor983** [angular-ui/ui-grid#3917]
cellNav navigate event fires two times on first click on cell in grid

1. for current row and column and then
2. for first row and first column

After first click everything works fine.

My problem is I want to set selected row on row where clicked cell is but on first click I always got first row selected in grid wherever I click in.

**Comment by JLLeitschuh** [comment]
This should be fixed in my accessibility pull request.
This is probably caused because the event is set to fire on click and on focus.
I only saw this as a theoretical problem though. I never actually experienced it myself.
What browser/OS are you experiencing this problem with?

**Comment by dalibor983** [comment]
@JLLeitschuh chrome (windows 8)

**Comment by fk-mbc** [comment]
I have the same problem. It doesn't depend on the browser. FF also handles it in the wrong way. 
In my setup i activate cell-nav and selection. Then i use the 
gridApi.cellNav.on.navigate(scope, function (newRowCol, oldRowCol)  { ... });
to set the newRowCol.row.isSelected to true and the oldRowCol.row.isSelected to false. (Also scope.gridApi.grid.selection.lastSelectedRow = newRowCol.row and scope.gridApi.grid.selection.selectedCount = 1). It works very well on arrow navigation and click on cells. But the fist initial click on an row, that is not the first one, select the first one and the clicked row.
I tracked it and it is so, that the first iteration do the stuff we want - selecting the clicked row, but then there is a secound trigger, which selecting the first row. The cell is correct focused and i can start to navigate and it works.

Is there a way to initial select the first row with the cellnav and also focus it when data is loaded? So than the user can start navigation with the arrow key and also the problem don't happen.

**Comment by gaving** [comment]
:+1: 

Can confirm the same issue here, chrome (windows 8).

Works fine in IE11.

**Comment by JLLeitschuh** [comment]
This should have been resolved in #3850
Please try using the newest unstable and see if you still have this problem.

**Comment by dalibor983** [comment]
@JLLeitschuh Is there any unstable bower reopo for ui-grid or I need to clone master git repo and build it

**Comment by JLLeitschuh** [comment]
Not at the moment. Our release setup is a bit of a mess at the moment.
You can do a local release by doing: 
`grunt clean ngtemplates build cut-release update-bower-json`

**Comment by dalibor983** [comment]
@JLLeitschuh It works.
