### ISSUE TITLE
Update ngDocs of the module "infiniteScroll"

### ISSUE THREAD

**Issue by LuisLoureiro** [angular-ui/ui-grid#3920]
While trying to reset the scroll position of my grid using the function [PublicAPI.resetScroll(scrollUp, scrollDown)](https://github.com/angular-ui/ng-grid/blob/f2368cc/src/features/infinite-scroll/js/infinite-scroll.js#L125) I noticed that the documentation is not correct.
It says that this function returns a promise but instead it always returns _undefined_ because the function [uiGridInfiniteScrollService.adjustInfiniteScrollPosition(grid, percentage)](https://github.com/angular-ui/ng-grid/blob/f2368cc/src/features/infinite-scroll/js/infinite-scroll.js#L399) doesn't return anything. Furthermore, the documentation of this function is not correct too.

Do you want a PR?

Thanks

**Comment by PaulL1** [comment]
Yes, I think a PR would be useful.  Although we should check that it actually makes sense to return a promise, if this isn't really an asynch method then maybe better to just update the documentation?

**Comment by LuisLoureiro** [comment]
Well, both functions seem to be synchronous in spite of the existence of some *$timeout*s in the middle of these executions.
I'll return with a PR with just documentation updates.
I'll give a better check trying to realise if this isn't really an asynch method.

**Comment by imbalind** [comment]
@LuisLoureiro did you manage to come up with a PR?

I'm closing this since old and not updated.
