### ISSUE TITLE
Undesired grid menu animation change

### ISSUE THREAD

**Issue by brandonr1** [angular-ui/ui-grid#3921]
Basically the same as the column menu bug (#3436), but seems to be a grid menu problem as well.

When switching from 3.0.0-rc.20 to 3.0.0-rc.22, I noticed a change in the grid menu animation. It used to be nice and subtle, but it now comes down from the top of the page.

On my pages the problem doesn't happen when I use RC20 css with RC22 code.  When I use RC22 css the behavior presents itself. 

You can see it on the grid menu demo page (using Chrome ).
http://ui-grid.info/docs/#/tutorial/121_grid_menu

BTW, ui-grid is awesome!

**Comment by PaulL1** [comment]
Ah, that's a good finding.  I had assumed it was a css change, but I thought I did a bisect and didn't find it. Perhaps I did the bisect wrong.  If it's css it'd be much easier to fix.

Any chance you could work out which line in the css does it?  I'm guessing it's a position absolute or something like that somewhere on the menu css.

**Comment by brandonr1** [comment]
I'll double check to verify css is the most likely cause and dig in next week when I get back to work.  I hope it is on the easier side :)

**Comment by anilnatha** [comment]
I just began adding animation to my application and prior to adding the ngAnimate module to my app, I had no issues with the menu; however, after adding ngAnimate, I'm experiencing the same issue that brandonr1 is reporting running 3.0.0-rc.22 as well.

**Comment by anilnatha** [comment]
Just a side note: I really wish there was a way to disable animation for the grid, but because of this issue, I have to remove the animation module from my application entirely and forgo adding animation to the rest of my app because of the menu's jumpy behavior, unless there is a workaround that I'm unaware of.

Allowing developers to choose if they want the grid to use animation or not would be a step in the right direction, rather than forcing grid features to always be animated if the animation module is added to an app.

**Comment by mikyladewitt** [comment]
+1 I have the same problem. It would be great to be able to disable this for developers that use ng-animate, but don't want to have the column animation.

**Comment by antoinebrault** [comment]
gridOptions.onRegisterApi = function (gridApi) {
    $animate.enabled(gridApi.grid.element, false);
}

**Comment by anilnatha** [comment]
Thanks @antoinebrault! I'll give that a try!

**Comment by Maus3rVonDutch** [comment]
I think it's just a css issue. Not sure if this is the appropiate fix, but in the mean time you could apply this css to fix it as an alternative to disabled the animation altogether as mentioned above:
```
.ui-grid-contents-wrapper {
    overflow: hidden;
}
```

**Comment by markoffk** [comment]
Hello! What is the state of this bug? is it gonna to be fixed someday? Thanks!
