### ISSUE TITLE
keepLastSelected does not work when executed sort

### ISSUE THREAD

**Issue by porabh** [angular-ui/ui-grid#3926]
You can replicate issue here
http://plnkr.co/edit/wPKc3hpWkZitOH54kcOC?p=preview
Just change keepLastSelected on true

First select one row, try to deselect row, it isn't deselected that is OK.
Then sort one column. After that try to deselect row, row is deselected. 

Also if sortInfo is passed in gridOptions keepLastSelected does not working.

**Comment by AgDude** [comment]
This issue was moved to angular-ui/ng-grid-legacy#3
