### ISSUE TITLE
ui-grid v3.0.0-rc.22 - paginator - word "of" hardcoded

### ISSUE THREAD

**Issue by kdebski85** [angular-ui/ui-grid#3927]
I am using ui-grid v3.0.0-rc.22
A word "of" in the paginator should be translatable.
Currently it is hardcoded:

`{{showingLow}} - {{showingHigh}} of {{grid.options.totalItems}} {{totalItemsLabel}}`

**Comment by PaulL1** [comment]
I believe this is already fixed in master?

**Comment by JLLeitschuh** [comment]
Yes. It is fixed in master: https://github.com/angular-ui/ng-grid/blob/master/src/features/pagination/templates/pagination.html#L19
