### ISSUE TITLE
Problem when merging row with treeview.

### ISSUE THREAD

**Issue by bjaraujo** [angular-ui/ui-grid#3929]
The merged row has a title='123456789' but I get this also printed on the row header. How can I prevent this?

```
      rowTemplate: '<div><div ng-if="row.entity.merge">{{row.entity.title}}</div>' +
        '<div ng-if="!row.entity.merge" ng-repeat="(colRenderIndex, col) in colContainer.renderedColumns track by col.colDef.name" class="ui-grid-cell" ng-class="{ \'ui-grid-row-header-cell\': col.isRowHeader }"  ui-grid-cell></div></div>',
```

![untitled2](https://cloud.githubusercontent.com/assets/5067963/8501627/1fc37230-219f-11e5-8b02-25bb1e8f2fcb.png)

Plunker:
http://plnkr.co/edit/YESQKTfcAyNDZHNRNoVb?p=preview

**Comment by PaulL1** [comment]
You need to modify your cell template to check that it's in the body render container.  It's displaying once for each render container.  There's an example of this somewhere in the tutorials - maybe in the FAQ?

**Comment by billyaraujo** [comment]
Thanks for the reply. I have solved this just adding that label as treeLevel = 0. I couldn't find how to do it. Will keep searching...

**Comment by Shabin** [comment]
I am not sure whether Paul meant the same, but I was able to fix this by checking if the colContainer.name was body.
```
'<div ng-if="row.entity.merge && colContainer.name==\'body\'" class="ui-grid-cell" style="width:100%"><div class="ui-grid-cell-contents">{{row.entity.title}}</div></div>' +
'<div ng-if="colContainer.name!=\'body\' || (!row.entity.merge && colContainer.name==\'body\')" ng-repeat="(colRenderIndex, col) in colContainer.renderedColumns track by col.uid" class="ui-grid-cell" ng-class="{ \'ui-grid-row-header-cell\': col.isRowHeader }" ui-grid-cell></div>'
```

**Comment by Shabin** [comment]
I was able to make this work by checking whether colContainer.name equals body as given in this [tutorial](http://ui-grid.info/docs/#/tutorial/317_custom_templates).
```
'<div ng-if="row.entity.merge && colContainer.name==\'body\'" class="ui-grid-cell" style="width:100%"><div class="ui-grid-cell-contents">{{row.entity.title}}</div></div>' +
'<div ng-if="colContainer.name!=\'body\' || (!row.entity.merge && colContainer.name==\'body\')" ng-repeat="(colRenderIndex, col) in colContainer.renderedColumns track by col.uid" class="ui-grid-cell" ng-class="{ \'ui-grid-row-header-cell\': col.isRowHeader }" ui-grid-cell></div>'
```
