### ISSUE TITLE
Bettter terminology to name  stuffs

### ISSUE THREAD

**Issue by salarmehr** [angular-ui/ui-grid#3931]
Current config names are somehow awkward. I suggest using [Ext.grid.*](https://docs.sencha.com/extjs/5.1/5.1.1-apidocs/#!/api/Ext.grid.Panel) vocabulary if possible or add theirs as a synonym (It is the most mature grid widget in js world). e.g `enableFiltering` is `filterable` in ExtJS which seems better. Also using same vocabulary make migration from ExtJS (and a lot of other grid plugins which use the same lexicon) easier.

**Comment by PaulL1** [comment]
I don't think we can plan to do every change that might suit particular audiences.  One of our design goals was to ease the migration from 2.x, much of our terminology comes from there.  I think it's not possible to both achieve that and to achieve compatibility with ext.grid unfortunately.  

Closing, as I don't think anyone is going to do this, so it's just clutter.

**Comment by salarmehr** [comment]
◕︵◕
