### ISSUE TITLE
How can I limit the text in a column

### ISSUE THREAD

**Issue by boazin** [angular-ui/ui-grid#3933]
I want to have the amount of visible text in a column "show what fits..." (becuase I'm allowing resizing of cells)

Tried with `text-overflow: ellipsis` and nothing changes

How can I achive that?

Thanks

**Comment by c0bra** [comment]
What does "show what fits" mean, exactly?  The grid, by default shows ellipses for cells whose content overflows; you can see that here: http://ui-grid.info/docs/#/tutorial/103_filtering

Are you wanting something different or is it not working for you?

**Comment by boazin** [comment]
Hmm... well for some reason if there is too much text the cell just jumped to the next line.
Maybe it has something to do with the fact I have ui-grid-auto-resize?

**Comment by boazin** [comment]
You can see it in http://158.85.229.40:8080/. Although the text gets shorter width the width (with a JS code) - if you get below 1336px you start seeing the effect I'm referring to...

**Comment by JLLeitschuh** [comment]
Could you host your example in plunker instead of on an IP address?

**Comment by boazin** [comment]
Sorry for the delay (this bug was de-prioritized)
Apparently I had display:table so I can vertically center the text in the cells.
(and it doesn't work with ellipses)

Any ideas how can I make it both happen?

**Comment by boazin** [comment]
Well. For future reference. The height is in fixed size so I got it back to display:block and added a padding to the text so it will appear in the middle.
Thanks.

**Comment by ashishpatel02** [comment]
@c0bra , not working for me, do we need to set any property in ColumnDef to show limited amount of text?
