### ISSUE TITLE
Horizontal scroll too fast will cause blank

### ISSUE THREAD

**Issue by yiniesta** [angular-ui/ui-grid#3937]
I have 30 columns in my ui-grid table,when I scroll too fast will cause blank.I think this is related to the columns render,and I want to know how can I fix this problem? Thanks

**Comment by c0bra** [comment]
If you're not using custom cell templates you could try overriding the row template and altering it's column repeater to `track by $index` rather than `track by col.uid` : https://github.com/angular-ui/ng-grid/blob/master/src/templates/ui-grid/ui-grid-row.html

**Comment by yiniesta** [comment]
@c0bra Many thanks. Although scroll still cause blank,but it feel faster.

**Comment by susharma-equinix** [comment]
Hi Yiniesta,

Is this for ngGRID or uiGRID ?

In ui-grid even i have almost 30 columns but when i scroll, Column headers are not moving

**Comment by yiniesta** [comment]
@susharma-equinix I use uiGrid. what do you mean "Column headers are not moving"? If you drag the scroll bar fast, is it occur blank?
