### ISSUE TITLE
GridOptions.minimumColumnSize is not taken into account

### ISSUE THREAD

**Issue by mearing** [angular-ui/ui-grid#3941]
Looking at the API docs for Grid options (http://ui-grid.info/docs/#/api/ui.grid.class:GridOptions) there is an option of minimumColumnSize. This doesn't seem to be taken into account.

Searching through the code base for "minimumColumnSize" yields no actual logic. I think it soulld be taken into account in the updateColumnWidths method in GridRenderContainer: https://github.com/angular-ui/ng-grid/blob/master/src/js/core/factories/GridRenderContainer.js#L595

A plunkr example:
http://plnkr.co/edit/zpOUTXlSXCvbPbwOu0yZ

**Comment by veljkopopovic** [comment]
+1 on this ...

**Comment by JLLeitschuh** [comment]
It seems the actual setting is minWidth
http://ui-grid.info/docs/#/api/ui.grid.class:GridOptions.columnDef

It seems that the code and the docs need to be updated in order to fix this.

**Comment by dneuer** [comment]
The fix can't be to remove the option, right? I assumed the purpose of this option was to avoid having to specify a minWidth or width on every single column individually (annoying if you have lots of columns).

**Comment by betsydupuis** [comment]
+1
