### ISSUE TITLE
UI grid colored row-wise having problems on scrolling

### ISSUE THREAD

**Issue by yogi4yu** [angular-ui/ui-grid#3947]
I am coloring all rows of my ui grid depending on some flag, but the column colors appear mismatching upon scrolling down. Please see the screen shots.

https://plus.google.com/117223692780140475095/posts/ZAmqTLMgppf?pid=6168718197294224114&oid=117223692780140475095

**Comment by PaulL1** [comment]
Could you provide a plunker?  Are you using cellClass to do this, or using some other method?  CellClass is the supported way to do this, doing it in other ways is likely to cause problems when we scroll as there's no guarantee that the calculation will get reexecuted on scroll.

**Comment by yogi4yu** [comment]
I'll provide plunker later on , but I am using rowTemplate to color rows

**Comment by yogi4yu** [comment]
I'll provide plunker later on , but I am using rowTemplate to color rows

**Comment by yogi4yu** [comment]
I am also eager to know how to use cellClass to color whole row based on one cell value.

**Comment by PaulL1** [comment]
You apply the cellClass to every column.
