### ISSUE TITLE
Export visible data only export data in the first page

### ISSUE THREAD

**Issue by qitang** [angular-ui/ui-grid#3954]
Hi, I have used UI Grid to display more than 3000 rows. And after some cell filtering there are only 500 results. However when I try to export visible data as CSV, I only get the 50 rows from the very first page. I am wondering if there is a way to export all data after filtering not just visible data in the first page? Thanks a lot!!

**Comment by PaulL1** [comment]
Are you using pagination?  If so there's a fetch all data option for pagination before you export.

**Comment by qitang** [comment]
@PaulL1  yes, I am using pagination. But can u be more specific? Will that export all filtered data across all pages? Thanks!

**Comment by qitang** [comment]
BTW, I am using client side pagination

**Comment by PaulL1** [comment]
The fetch all option does get all data for all pages before exporting, yes.  Closing, as this is pretty old and is really a question not a defect.

**Comment by aiguofer** [comment]
I think the problem that @qitang was pointing out is that the 'export all' feature exports ALL data, not the filtered results.

For future reference, I've asked this in SO http://stackoverflow.com/questions/34190766/ui-grid-export-all-filtered-data-to-csv

**Comment by nareshurs** [comment]
I am in the same situation. We use client side pagination  and want to export filtered data with out user selecting 'select all' explicitly, can we export filtered records? I didn't even found workaround

**Comment by aiguofer** [comment]
@nareshurs the workaround is to create a pagination option with a number larger than the number of items in your dataset and use that and export visible rows. It's ugly, but it works

**Comment by nareshurs** [comment]
@aiguofer, Thanks for the details.

I have changed pagination size on the fly. It works as expected after sorting. However if I do export without sorting/filtering, it exports only 10 recrords. Though we change page size it is not taking unless I do a sort/filter/scroll.

**Comment by nareshurs** [comment]
It seems there is a delay in reflecting new page size. My plan was to change page size to some big number on fly, do export then reset back to original page size.

To address this delay I put setTimeout of 5ms it works, but could see changed page size to maximum number in **UI also** for that 5ms. Not sure how can we avoid this.

**Comment by ramprasadm** [comment]
Faced same issue while exporting filtered data to PDF/CSV. It is exporting only Visible Data/All Data, but not all filtered rows. Found an workaround to export filtered data, tweak the logic in **_getData()_** function in **ui-grid.js** solves my problem. Added a AND condition **_"row.visible_**" while preparing data for PDF/CSV. After this change I am able to export all the filtered rows to PDF/CSV.

Code Snippet **ui-grid.js**:
```
getData: function (grid, rowTypes, colTypes) {

rows.forEach( function( row, index ) {
            if (row.exporterEnableExporting !== false && row.visible) {
              var extractedRow = [];
```

Custom Filter:
```
$scope.filter = function() {
		  $scope.gridApi.grid.refresh();
	  };
	  
	  $scope.singleFilter = function( renderableRows ){
		      var matcher = new RegExp($scope.filterValue);
		      renderableRows.forEach( function( row ) {
		        var match = false;
		        [ 'name'].forEach(function( field ){
			          if ( row.entity[field] != null && row.entity[field].match(matcher) ){
			           match = true;
			          }
		        });
		        if ( !match ){
		          row.visible = false;
		        }
		      });
		      return renderableRows;
	  };
```

**Comment by saajshek** [comment]
Hi ramprasadm. Can you please share some more details about that getData function ? Do you have any fiddle available for that ?

**Comment by AnirudhaGohokar** [comment]
I was able to easily export filtered data across all pagination via [uiGridExporterService](http://ui-grid.info/docs/#/api/ui.grid.exporter.service:uiGridExporterService) service. 

```
//you can set it to ALL or VISIBLE or SELECTED
var columnsDownloadType = uiGridExporterConstants.ALL;

//get all the visible rows across all paginations
var filtered = _.filter(grid.api.grid.rows, function (o) {
    return o.visible;
});

//get the entities of each of the filtered rows
var entities = _.map(filtered, 'entity');

//get all or visible column headers of this grid depending on the columnsDownloadType
var exportColumnHeaders = grid.options.showHeader ? uiGridExporterService.getColumnHeaders(grid, columnsDownloadType) : [];

var exportData = [];
/**this lodash for-each loop will covert the grid data into below array of array format 
* [[{value:'row1col1value'},{value:'row1col2value'}],[{value:'row2col1value'},{value:'row2col2value'}].....]
* uiGridExporterService.formatAsCsv expects it in this format
**/
_.each(entities, function (row) {
    var values = [];
    _.each(exportColumnHeaders, function (column) {
        var value = row[column.name];
        values.push({value: value});
    });
    exportData.push(values);
});

//format the header,content in csv format
var csvContent = uiGridExporterService.formatAsCsv(exportColumnHeaders, exportData, ',');

//export as csv file
uiGridExporterService.downloadFile(grid.options.exporterCsvFilename, csvContent, grid.options.exporterOlderExcelCompatibility);
```

**Comment by ruhaise** [comment]
this work's bro, thanks very much!

**Comment by ruhaise** [comment]
I'm using angular ui-grid for large set's of data, now i'm able to export the filtered result's from all paginations,when i apply the sort functionality along with it, it works on the view but not on the imported file, that is the user again needs to sort it after the download using excel(which isn't convenient).

```
function exportFilteredData() {
            $scope.exportDatalist = _.filter($scope.gridApi.grid.rows, (o) => {
                return o.visible;
            });
            var entities = _.map($scope.exportDatalist, 'entity');
            alasql.promise('SELECT * INTO XLSX("Log_Details.xlsx",{headers:true}) FROM ?', [entities]);
        }
```
NB: Extra dependencies i have used

xlsx.js
underscore.js
alasql.js
