### ISSUE TITLE
How to highlight unique cell(refering row and col) in UI Grid using cellClass function?

### ISSUE THREAD

**Issue by rajulkansara** [angular-ui/ui-grid#3956]
I have given good explanation at below location.

http://stackoverflow.com/questions/31307825/how-to-highlight-unique-cell-in-ui-grid-using-cellclass-function

http://plnkr.co/edit/5xQoKiKIL8vY8EeLsJG5?p=preview

**Comment by JLLeitschuh** [comment]
As this is just a FAQ can I close this issue or do you have a specific problem?

**Comment by rajulkansara** [comment]
This is not faq. Problem that I have mentioned is seeming limitation of UI grid. (As far  as I have studied code behind. ). If my understanding is incorrect then I wish to have some directions from ui grid owners. Thanks.

**Comment by mportuga** [comment]
https://github.com/angular-ui/ui-grid/blob/master/planning_5.0.md
