### ISSUE TITLE
Hiding Options inside Grid menu

### ISSUE THREAD

**Issue by jonMullen** [angular-ui/ui-grid#3958]
Using ui-Grid v3.0.0 as of 2015-05-14

The Grid Menu I have shows the below 3 options when the menu button is pressed.

Export all Data as CSV
Export visible Data as CSV
Columns:

Is there a way to Hide what it displays so it only shows, Export all Data as CSV?

The code I currently have is

$scope.gridOptions= {
enableGridMenu; true
exporterMenuPdf: false,
exporterCsvFilename: 'export.csv',
columnDefs: $scope.columns,
};

I tried to add in exporterAllAsCsv: false but that did not take out that option.

**Comment by PaulL1** [comment]
There is an option to hide the hide/show columns.  There is not an option to remove the export visible, to achieve that you'd need to set the option that hides all exporter menu items, then manually add export all as csv as a custom menu item.

**Comment by jonMullen** [comment]
Ok thanks i will give that a try, i know i can hide individual columns but i want to hide the header that says Colums:

**Comment by AnirudhaGohokar** [comment]
Setting `gridMenuShowHideColumns `to false worked. Though its still showing "Export Visible Data As CSV" instead of just "Export All Data As CSV".

Is there a way to hide "Export Visible Data As CSV" grid menu. Tried setting `exporterMenuVisibleData `to false in `gridOptions `but didn't work.

Thanks

**Comment by laenas** [comment]
@AnirudhaGohokar I believe the only option at this time is to disable the existing options and add your own:

gridOptions:{
    exporterMenuCsv: false,
    gridMenuCustomItems: [{
        title: 'Export All Data As CSV',
        order: 100,
        action: function ($event){
            scope.gridApi.exporter.csvExport(uiGridExporterConstants.ALL, uiGridExporterConstants.ALL);
        }
    }]
}

**Comment by jamesdhakera** [comment]
@laenas how to do the same for export to pdf option ?

**Comment by krishtej23** [comment]
Hi all, I have "Clear all filters" in the grid menu and the requirement is that when user did not add any filters in the column headers then "Clear all filters" button from grid menu should be disabled. How can I achieve this? Thank you.
