### ISSUE TITLE
ui grid pdf creation error

### ISSUE THREAD

**Issue by gindij** [angular-ui/ui-grid#3963]
When I try to export my grid to a PDF and try to open the file, I get the following message 

![image](https://cloud.githubusercontent.com/assets/6021161/8623350/d93521be-26e5-11e5-85f4-ace761df88d6.png)

and Adobe shows me a blank pdf.

Any ideas as to what might be happening here?

my exporter settings:
 
![image](https://cloud.githubusercontent.com/assets/6021161/8623501/aa9c4354-26e6-11e5-9c7f-23c190be730f.png)

**Comment by PaulL1** [comment]
I'd try a breakpoint to grab the docDefinition, then put that docDefinition into the pdfMake testing page to see what's going on.

**Comment by gindij** [comment]
Sorry I'm pretty new to this... where would I break to find the docDefinition?

**Comment by PaulL1** [comment]
I'd open the ui-grid.js, and search for docDefinition.  I think it only appears in exporter, in a method called something like pdfExport.  The last step in that is to call pdfMake passing in that document definition.  Put a breakpoint there, and then grab the document definition, and paste that into the pdfMake testing page.

**Comment by PaulL1** [comment]
This is pretty old, and sounds like an upstream bug.  Advice given on how to diagnose, and no progress since then - closing.
