### ISSUE TITLE
ngGrid (aggregateTemplate)  -> ui grid 

### ISSUE THREAD

**Issue by beckhamk** [angular-ui/ui-grid#3964]
I am in the process of migrating various ngGrids for our application over to ui grid and have ran into and issue.  ngGrid had a gridOptions of aggregateTemplate which i could use the row template below.  In ui grid there is no aggregateTemplate, so i am at a loss if we can even have the grid looking the way it used to look.

The light blue rows are the aggregateTemplate. 
![grid1](https://cloud.githubusercontent.com/assets/13277551/8624258/9a0c2a18-2704-11e5-857c-9cce731dcd69.png)

```
                    aggregateTemplate: "<div ng-click=\"row.toggleExpand()\" ng-style=\"rowStyle(row)\" class=\"ngAggregate\">" +
                                    "    <span class=\"ngAggregateText\"><span class='ngAggregateTextLeading'>{{row.label CUSTOM_FILTERS}} ( {{GetEnglishValue(row)}} )" +
                                    "</span></span>" +
                                    "    <div class=\"{{row.aggClass()}}\"></div>" +
                                    "</div>" +
                                    "",
```

**Comment by PaulL1** [comment]
You can't do an aggregate template as such, but you can do a rowTemplate that looks at row.internalRow or row.treeLevel, and applies a different format depending on the values.
