### ISSUE TITLE
Cancelling on.navigate event

### ISSUE THREAD

**Issue by jacksumit** [angular-ui/ui-grid#3969]
Hi, we have a requirement where we want to cancel the navigate event based on certain conditions. For example say if user has clicked from one row to another then we want to validate the current row in focus first. If validation fails user should mot be allowed to move to another row. 

There is no $event available passed to method on on.navigate event. Could you pleasr advise how this can be acheived.

Regards
Sumit

**Comment by imbalind** [comment]
A validation proposal has been submitted in #4152
