### ISSUE TITLE
uiGridEventEndCellEdit not always triggered when using cellNav

### ISSUE THREAD

**Issue by phhau** [angular-ui/ui-grid#3971]
Hi,

we found a potential bug in UI-Grid 3.0 RC22. I created a plunker here:
http://plnkr.co/edit/lQHCFbuMEyl6gfGUv9HR?p=preview

We registered an Eventhandler for "uiGridEventEndCellEdit" that writes a log statement on the index.html page for every event.

 $scope.$on('uiGridEventEndCellEdit',function(data) {
    eventcount++;
    $scope.logs.push('catched uiGridEventCellCellEditEvent ' + eventcount);
});

This works quite well for most of the rows. However if you edit every cell in the first column by just selecting the cell via keyboard, start typing to enter a new value and then press "enter"  to get to the next cell, no uiGridEventEndCellEdit event is triggered for the last visible row. However the value itself is updated in the cell. 

It looks like the uiGridEventEndCellEdit kindof  "overlaps" with scrolling down. Is there maybe a workaround for this behaviour?

Regards,
Philip

**Comment by tonympls** [comment]
+1 
I seem to have run into the same issue.  Using ngGrid 3.1.0.  For both Enter and Tab (with ui.grid.cellNav) on the last row of grid, uiGridEventCellCellEditEvent is frequently (but not always) not called / triggered.

**Comment by mportuga** [comment]
Cannot reproduce on latest version:
http://plnkr.co/edit/O6s8deH5SJsM9Mlu17XI?p=preview
