### ISSUE TITLE
Selection not stable - randomly selected row

### ISSUE THREAD

**Issue by nadavelyashiv** [angular-ui/ui-grid#3976]
Whenever I play with selection (Firefox 38.0.5), rows are highlighted back and forth, and when I deselect all rows, suddenly a random row is selected on its own.
I thought a short video would demonstrate best what I'm saying:
http://tinypic.com/r/6gfxnd/8

**Comment by PaulL1** [comment]
I haven't seen this in any other situation.  Are you able to provide a plunker of that?

**Comment by nadavelyashiv** [comment]
I tried, but the code was flooded with internal configuration services, etc. It was hard to separate, plus I switched to the newer version of ui-grid so some code (of ng-grid) was lost...
