### ISSUE TITLE
Grid menu animation issue in Firefox 

### ISSUE THREAD

**Issue by rquiroz6** [angular-ui/ui-grid#3978]
When closing the grid menu in Firefox 39.0, the menu's fly-out animation gets 'stuck' above the grid, as seen in this screenshot:

![firefoxuigridmenu](https://cloud.githubusercontent.com/assets/11983747/8679752/6acecac0-2a11-11e5-897a-7dde38ec8bfd.PNG)

This issue occurs with the column menus as well.

**Comment by fberthel** [comment]
I can confirm this bug for Firefox 40.0.2

**Comment by tringuyenminh92** [comment]
i got this issue in FF ESR 38.2.0

**Comment by susharma-equinix** [comment]
Iam also facing the same issue. Can some one please look into this at the earliest. It would be very grate full if i can get an work around for the same temporarily.

**Comment by hohwille** [comment]
http://ui-grid.info/docs/#/tutorial/121_grid_menu
Still buggy in FF 41.0.1

**Comment by hohwille** [comment]
http://ui-grid.info/
also the regular sort menus do not work with FF. Only working with Chorme.
IE also works but without annimaiton.

Better disable animation gimmicks in FF than having this broken stuff.

**Comment by SoundLogic** [comment]
any easy fix in the meantime is to do the following in your app.js file (requires ngAnimate module):

```javascript
    app.config([
        '$animateProvider', function($animateProvider) {
            $animateProvider.classNameFilter(/^((?!(ui-grid-menu)).)*$/);
        }
    ]);
```

**Comment by veegandhi** [comment]
Run into the same issue , @SoundLogic solution works

**Comment by fberthel** [comment]
@SoundLogic  works like a charm, thanks :)
