### ISSUE TITLE
Disable negative value to insert in edit feature

### ISSUE THREAD

**Issue by GaurangGhinaiya** [angular-ui/ui-grid#3982]
Hello I want to stop inserting negative value in editing features.

for that i try this stupid thing ..

[PLUNKER](http://plnkr.co/edit/SMRtoKgEtlP6th6IVXCp?p=preview)

But it didn't work. 

how can i do that.

**Comment by JLLeitschuh** [comment]
Have a look at the api methods for intercepting an edit event.
http://ui-grid.info/docs/#/api/ui.grid.edit.api:PublicApi

**Comment by PaulL1** [comment]
Or consider building a custom editor that has validation to your requirements.

**Comment by GaurangGhinaiya** [comment]
@PaulL1  I think you should add features like HTML5 Input Types. Not only Type you also add min, max, pattern etc.

**Comment by imbalind** [comment]
Duplicate of #4152
