### ISSUE TITLE
Filter selects display only first letter of selected value, if selectOptions is loaded after  page is loaded.

### ISSUE THREAD

**Issue by MaksimSimkin** [angular-ui/ui-grid#3985]
It's known problem about ie9, see for example:
http://stackoverflow.com/questions/15576945/ng-options-populated-by-ajax-only-displaying-first-letter-in-ie

screenshot:

![image](https://cloud.githubusercontent.com/assets/10547823/8702338/90a95100-2b17-11e5-8209-c1a037c41ca9.png)

**Comment by mportuga** [comment]
Closed by https://github.com/angular-ui/ui-grid/pull/3928

**Comment by vasyldemchuk** [comment]
Are there any ways to show empty select filter? Just to fit the whole filter line and not having any gaps.
Thanks!
