### ISSUE TITLE
Scroll over contents, it shows blank space.

### ISSUE THREAD

**Issue by zestime** [angular-ui/ui-grid#3990]
UI-Grid is really helpful and awesome.
It is great UI component.

But, I get a problem with scrolling.
![screen shot 2015-07-16 at 19 06 41](https://cloud.githubusercontent.com/assets/978977/8720483/f601deba-2bed-11e5-82c7-9926052bddea.png)
It show grid well at first time. 
When I scroll down, the scrollbar thumb is getting small. 
And finally, I got empty space.
![screen shot 2015-07-16 at 19 06 56](https://cloud.githubusercontent.com/assets/978977/8720528/3dafebbc-2bee-11e5-8d96-5f172c25f657.png)

I tested at 'ui-grid - v3.0.0-rc.22-c1dead9 - 2015-07-15'.
The number of rows was 109.

**Comment by c0bra** [comment]
How are you strolling down? Using the mousewheel/trackpad? Dragging the scrollbar handle? Using the scrollbar arrows?

And can you recreate this in a plunker?

**Comment by zestime** [comment]
Sorry for late reply...
I try to make a sample with the scroll problem. [plunker](http://plnkr.co/edit/iv6jUPVoq70CEuzVJK18?p=preview)
And, I realize that it was exactly my fault. I missed css about this.
```css
.ysr-grid-patient .ui-grid-canvas {
  padding-top: 0;
}
```
It caused by me. 
Thanks for your advice to make it in plunker. :)

**Comment by joeburkey** [comment]
Bit late to the party here but I'm encountering this issue. Sometimes it just happens on a normal scroll down but it always happens when holding the mouse wheel to scroll down
