### ISSUE TITLE
Numbers do not sort correctly in 3.0 when applying a cellFilter

### ISSUE THREAD

**Issue by richardm** [angular-ui/ui-grid#3994]
The issue occurs when:
1) using $http.get to load data and then setting the data array, and
2) using a cellFilter to format a number as a string

Expected sort (desc):
$100,803, $3,777, ..., $491

Actual sort (desc):
$491, $3,777, ..., $100,803

I've reduced the issue as much as possible to this plnkr:
http://plnkr.co/edit/547Gzd

**Comment by richardm** [comment]
As a workaround, adding type: 'number' to the columnDef for this column causes it to sort correctly. This still appears to be a bug, though.

**Comment by PaulL1** [comment]
I think there was a recent change that sorted based on the filtered cell value, which I expect would cause it to be treated as a string.  I think that change was switchable though.  #3905.  Is that the cause of your issue?

**Comment by kassner** [comment]
@PaulL1 I just tested this with 3.0.4, the sorting is still treating the data as string. Using `cellFilter: 'number'`does not help at all.

**Comment by kassner** [comment]
@richardm I was able to make it work with the last unstable version. Please take a look on this fork: http://plnkr.co/edit/PstvYj?p=preview

I added `type: 'number'` in the column definition.

**Comment by marpontes** [comment]
I had the same problem and `type: 'number'` did the trick here on 3.0.5.

**Comment by khullah** [comment]
For dates is not working. Maybe because I use brazilian format (DD/MM/YYYY)
