### ISSUE TITLE
Grouping plus and minus icons not showing anymore

### ISSUE THREAD

**Issue by cryoutsolutions** [angular-ui/ui-grid#3997]
http://ui-grid.info/docs/#/tutorial/209_grouping
https://www.dropbox.com/s/252xdkcar6a9ogj/Screenshot%202015-07-17%2010.30.02.png?dl=0

Now I just noticed that no icon is showing anymore.

Thanks

**Comment by prdn** [comment]
:+1:

**Comment by PaulL1** [comment]
These look to be showing now.  Expecting that this is an artefact of the 3.0 release process.

**Comment by kevin-johar** [comment]
I'm still receiving this issue on 3.2.11
