### ISSUE TITLE
Cannot expand the rows in ui-grid-unstable

### ISSUE THREAD

**Issue by jpwits** [angular-ui/ui-grid#3998]
I've looked at the example and all the plunkr's below, but I do not see a checkbox on the left, by which I can expand the row, not in chrome or IE...am I missing the obvious...please help!

**Comment by jpwits** [comment]
Ok this is weird..got  the example going locally and the +/- icons are showing to expand...so no prob..

**Comment by c0bra** [comment]
It was probably just a icon font loading issue. Glad it's work for you now, though!
