### ISSUE TITLE
CSV import not displaying data but no errors

### ISSUE THREAD

**Issue by dreadeddev** [angular-ui/ui-grid#3999]
I am using UI-Grid with the minimised files locally and the import seems to happen and call my javascript call back but the grid isn't displaying anything

    controller('fleetImportController', [
            '$scope', '$http', '$interval', 'FleetImportService', function($scope, $http, $interval, fleetImportService) {
            $scope.data = [];
            $scope.gridOptions = {
                enableGridMenu: true,
                columnDefs: [
                    { name: 'LR/IMO_Ship_No', field: 'LR/IMO_Ship_No' },
                    { name: 'Name_of_Ship', field: 'Name_of_Ship' },
                    { name: 'Ship_Type', field: 'Ship_Type' },
                    { name: 'Built', field: 'Built' },
                    { name: 'TEU', field: 'TEU' },
                    { name: 'Gas_Capacity', field: 'Gas_Capacity' },
                    { name: 'Deadweight', field: 'Deadweight' },
                    { name: 'Flag', field: 'Flag' },
                    { name: 'Registered_Owner', field: 'Registered_Owner' },
                    { name: 'Status', field: 'Status' }
                ],
                data: 'data',
                importerDataAddCallback: function (grid, newObjects) {
                    $scope.data = $scope.data.concat(newObjects);
                    console.log($scope.data);
                },
                onRegisterApi: function(gridApi) {
                    $scope.gridApi = gridApi;
                }
            };
            var getImportCb = function(returnedData) {
                $scope.data = returnedData;
                console.log("REturn data: ", returnedData);

            };
           
            }
        ]);

**Comment by PaulL1** [comment]
Are you able to provide a plunker and a sample file?  Is it possible that the column names that are being created don't match the column names you've given - so it's displaying rows but each column has no matching data?

**Comment by dreadeddev** [comment]
I'll try and set one up this morning which uses the same local files. The column names are definitely matching, bear with me and I'll see if I can replicate in a plunker. Thanks @PaulL1

**Comment by dreadeddev** [comment]
Okay I tried to set one up with local files but then hit the Plunker Payload limit! However because of how I am using the grid it was actually one of the UI-Grid header styles that was set to 100% which was causing the data not to be shown - ui-grid-unstable.css line 106 - I would suggest removing the height=100%, it's not needed.
