### ISSUE TITLE
http://angular-ui.github.com/ng-grid has disappeared?

### ISSUE THREAD

**Issue by chander** [angular-ui/ui-grid#4001]
There are lots of folks still with code that is dependent on the (old) ng-grid (which ui-grid replaces), and pretty much ever plunkr example, and most of the usable examples of ng-grid are no longer available due to the URL returning a 404:

http://angular-ui.github.com/ng-grid

Any chance of this being restored?  

I know this isn't specifically a ui-grid issue, but I'm sure folks will have some trepidation about stepping into ui-grid if they know it's predecessor was summarily removed once it was superceded by ui-grid.

**Comment by PowerKiKi** [comment]
I suggest you join gitter, they said it should be restored at some point: https://gitter.im/angular-ui/ui-grid?at=55a94f1310521a7e52558107
