### ISSUE TITLE
Column width reset when updating grid.data

### ISSUE THREAD

**Issue by Samy-A** [angular-ui/ui-grid#4005]
In Version 3.01, I have the following problem:

When you manually change column widths, and then reset grid.data, the column widths reset to the values defined in code.

I didn't have this problem in v3.0.0-rc.21.

See the following plunker: http://plnkr.co/edit/R2JWg0YO75RKBklwU9vN?p=preview

Change a column width, and then click on the "Set data a" button, and the column width resets to the default values.

What am i  missing?

EDIT:

The same issue can be seen in the tutorial 401: http://ui-grid.info/docs/#/tutorial/401_AllFeatures

Change a column width and click on "Refresh Data": the column width resets.

**Comment by Samy-A** [comment]
@c0bra 

So I understand that this behavior is by design, though I don't get why anyone would want the column widths to reset to the coded values anytime the filter is changed, or the grid.data is changed.

I don't know how to file an "enhancement request" here, so I will write here what feature I would appreciate.

Essentially the behavior of the grid as in RC 21.

Could there be an option on the grid level not to fire the updateColumnWidths method every time the filter or the data changes? It worked great in RC 21, and it made it possible to allow users to save the state of the grid, so that the column widths were as they wanted. Now I can still restore the saved state, but it is lost once the filter is used, or data.grid updated.
Likewise, when users manually resize a column (a very desirable feature), that is lost the moment they use a filter.

Thanks

**Comment by Samy-A** [comment]
So this PR did it: https://github.com/angular-ui/ui-grid/pull/3897
While I can see the problem it solved, losing the ability to persist column widths when filtering or changing the data is also a problem.

For now I changed my own version of ui-grid-unstable.js:

In GridColumn.prototype.updateColumnDef :

```javascript
GridColumn.prototype.updateColumnDef = function(colDef, isNew) {
    var self = this;

    self.colDef = colDef;

    if (colDef.name === undefined) {
      throw new Error('colDef.name is required for column at index ' + self.grid.options.columnDefs.indexOf(colDef));
    }

    self.displayName = (colDef.displayName === undefined) ? gridUtil.readableColumnName(colDef.name) : colDef.displayName;
    
    var colDefWidth = colDef.width;
    var parseErrorMsg = "Cannot parse column width '" + colDefWidth + "' for column named '" + colDef.name + "'";

 if (!angular.isNumber(self.width)){ //this line I added
    if (!angular.isString(colDefWidth) && !angular.isNumber(colDefWidth)) {
      self.width = '*';
    } else if (angular.isString(colDefWidth)) {
      // See if it ends with a percent
...
```
I added the condition if (!angular.isNumber(self.width)), and for me that works out fine.

**Comment by PaulL1** [comment]
I think this PR probably shouldn't have been merged as it is - I'd also have a problem with this behaviour if I'd gotten around to upgrading.

I'd be happy to look at a PR that made this switchable, and that had the default behaviour as it was before.

**Comment by mage-eag** [comment]
Because we have faced the same problem, here is what we are currently using to get around it : https://github.com/mage-eag/ui-grid/commit/966c4d98bd7d0ab09e04936d564870cbeaa5c2a9.

Still need to find a solution to allow overriding the width only once when a column definition is changed (see #3880, which was the original issue) - do you think a flag set on the column definition and reset after the first call to `updateColumnDef` could be a proper solution ?

**Comment by Samy-A** [comment]
That should work.

If the flag is set to true, updateColumnDef works like in @mage-eag 's code or in mine. If the flag is not yet set (to true), updateColumnDef works like in the current version, and sets the flag to true.

I think this would solve both the problem in #3880 and the problem of not persisting column widths when filtering or updating grid.data.

**Comment by swalters** [comment]
Anyone have a PR ready to submit to fix this?

**Comment by SomeKittens** [comment]
@mage-eag I've created a PR using your code (referenced above).  Hope that's ok by you.

**Comment by mage-eag** [comment]
Sorry, went on vacation for a couple of weeks, thanks @SomeKittens for the PR :)

**Comment by Samy-A** [comment]
Back from vacation.

Many thanks @SomeKittens , works fine.
