### ISSUE TITLE
How to Indent on a column?

### ISSUE THREAD

**Issue by swapnapisati** [angular-ui/ui-grid#4007]
Is there a way to Indent a column based on Tree Level? I am using Tree View in my code and added spaces to the field itself to make it look like Indention. But, as HTML page itself collapses white spaces into 1 white space, my solution is not working. I also tried to add <pre>,<pre-wrap> tags along with whitespace: pre in the body and UI grid specific CSS in HTML. This was not helping either. 

Please help me. I am very new to HTML and Java-script itself. here is how I set it up. 
HTML:
![image](https://cloud.githubusercontent.com/assets/13419737/8778993/d0b79a6c-2eb5-11e5-97b4-4c255c162df1.png)

columndef in my Javascript. 

{ field: 'complete_name',  displayName: 'Master / Contractual / Investor Name' , width: 325,  cellClass:'left'}

**Comment by PaulL1** [comment]
Take a look at the code behind the indention of the + in the treeBase.  I think it's adding padding based on treeLevel.

**Comment by billyaraujo** [comment]
Can someone post an example on how to do this?

**Comment by swapnapisati** [comment]
Thanks Paul for your suggestion. 
Adding a cellTemplate with padding helped. Padding value will be added indent for each level. 

    columnDefs: [
      { field: 'complete_name',  displayName: 'Master / Contractual / Investor Name' , width: 350,  cellClass:'left',
    	  		cellTemplate:'<div style="padding:5px">{{row.entity[col.field]}}</div>'},

**Comment by billyaraujo** [comment]
Thanks. 

I ended up using ng-class with padding-left.

**Comment by PaulL1** [comment]
Sounds like this has a resolution, closing.
