### ISSUE TITLE
cellFilter: 'currency' with no decimal?

### ISSUE THREAD

**Issue by swapnapisati** [angular-ui/ui-grid#4008]
Hi, 

I have setup my column with cellFilter to currency. This works for commas and dollar sign, but, my requirement is to not have any decimal points too. I setup my data field as integer too. cellFilter:number works for commas but not '$' at the beginning on the value. 

{ field: 'net_aum',  displayName: 'Net AUM',  cellClass:'left', width: 120, cellFilter: 'currency'}

Thanks in Advance!!

**Comment by PaulL1** [comment]
This is a generic angular question.  I think there are some formatting options for currency filters, but more importantly, you can write a custom filter.  https://docs.angularjs.org/api/ng/filter/currency
