### ISSUE TITLE
grid width not filling out ngCanvas

### ISSUE THREAD

**Issue by bradrice** [angular-ui/ui-grid#401]
I have this set in my css:

.gridStyle {
    border: 1px solid rgb(212,212,212);
    height: 600px;
    /_max-height: 800px;_/
    width: 750px;
    margin: 1em;
}

For some reason I have an empty space at the right of the grid before the scroll bar. It seem like regardless I do it will not fill out. If I inspect the element I get this being specified:

.ng1368027839598 .ngRow {
width: 700px;
}

Why does it subtract 50 pixels from what I have specified? Can I over-ride it so the columns go the entire way across?

**Comment by adammatthewsmith** [comment]
Still seeing this in v3.0.7 on Windows for Chrome, FF, and IE.  Basically the same screenshot as jlnery.  Maybe a scroll-bar width calculation issue?

**Comment by sshkuratoff** [comment]
I'm still seeing this too but like this... using v3.0.7 MacOSx Chrome
![screen shot 2016-03-31 at 1 15 24 pm](https://cloud.githubusercontent.com/assets/5769876/14189538/aff78660-f742-11e5-8d0e-b59b930c88ae.png)

**Comment by poojacmore** [comment]
![problemwithuigrid](https://user-images.githubusercontent.com/11183873/40975585-c5a0bcdc-68cb-11e8-9baa-221d5765c898.png)

I am also facing same problem only on Chrome.
Any lead on how to fix this ?
