### ISSUE TITLE
E2E Tests: Failure + Safari 5 Incompatibility

### ISSUE THREAD

**Issue by JLLeitschuh** [angular-ui/ui-grid#4010]
The e2e tests fail because 103 has one more column then the test expects.
The e2e tests aren't compatible with Safari 5.
See my comments on this commit:
https://github.com/angular-ui/ui-grid/commit/f71f9dc2f19925641585eadb1de4ff2839afe886

**Comment by AgDude** [comment]
A while back we decided to drop support for old (non evergreen) browsers. Closing as won't fix.
