### ISSUE TITLE
How to sort the table icon has been shown

### ISSUE THREAD

**Issue by liwenkaifzk** [angular-ui/ui-grid#4015]

**Comment by JLLeitschuh** [comment]
There isn't enough information in your question for me to know how to help you.

**Comment by liwenkaifzk** [comment]
![qq 20150728094618](https://cloud.githubusercontent.com/assets/12439508/8921816/937e31a2-350d-11e5-92f4-defabc9f3057.png)
I want to let the sort icon always show

**Comment by JLLeitschuh** [comment]
There are actually three sort states. Sort ascending, sort descending and unsorted. You have to have a sort on a column for it to show up.

**Comment by liwenkaifzk** [comment]
I just want him to have all sorts of icons to display and then use, can you do it

**Comment by JLLeitschuh** [comment]
If you have a sort set on all of the columns then they will display. If there is not a sort on a particular column then it will not display.
