### ISSUE TITLE
No event to determine when the grid is fully loaded

### ISSUE THREAD

**Issue by gbecan** [angular-ui/ui-grid#4027]
We are extending ui-grid in our project by performing some operations after the grid is loaded.
However, we did not find an event to determine when the grid is ready.
Our current solution is to use $timeout.
This solution is only based on luck... We are either too fast or too slow.

Is it possible to create an event that would be fired after the complete load of the grid?

**Comment by lebolo** [comment]
I don't think there's another solution, it's been asked before. Some people use a `$timeout` (#3350 - although you say this may not work for you) or listen for `ngGridEventData` (https://github.com/angular-ui/ui-grid/issues/585#issuecomment-36341163 and http://stackoverflow.com/a/23442653/1370556). For what it's worth, the [selection tutorial](http://ui-grid.info/docs/#/tutorial/210_selection) uses `$timeout`.

**Comment by kranthikumar2555** [comment]
if you are using ui grid then event- gridApi.core.on.rowsRendered($scope,handler); will suit for you.

**Comment by rdkleine** [comment]
When handing gridApi.core.on.rowsRendered and calling gridApi.cellNav.scrollToFocs(<data>, <coldef>) does not result in the cell being selected. When using a timeout as gbecan suggested works but is not ideal.
The uiGridCellNavConstants.CELL_NAV_EVEN broadcast isn't bound to the cells when rowsRendered is called.

**Comment by nadavelyashiv** [comment]
+1
And if you try to use grid.modifyRows() then rowsRendered is fired multiple times, and still it doesn't work.
