### ISSUE TITLE
Build without certain features

### ISSUE THREAD

**Issue by sebakerckhof** [angular-ui/ui-grid#4030]
It's not immediately clear from the docs, but is it possible to build without certain features in order to reduce filesize?

**Comment by JLLeitschuh** [comment]
You pull down the repository and delete the feature files that you don't want built. Then do a grunt build.
This should theoretically work as the features don't have dependencies upon each other.

**Comment by mportuga** [comment]
Version 4.4.1 has addressed this problem.
