### ISSUE TITLE
how can i reset cell with old value

### ISSUE THREAD

**Issue by kandarpbhesaniya** [angular-ui/ui-grid#4036]
how  can i reset cell newvalue with oldvalue in case of promise.reject()

**Comment by kandarpbhesaniya** [comment]
are there any EXPERT to give my question's answer??

**Comment by JLLeitschuh** [comment]
You're going to need to provide context for us to understand what you are talking about.
Are you refering to using cell edit?
I suppose you could save a copy of the old value before it is changed and replace it in the dataset if the promise is rejected.

**Comment by kandarpbhesaniya** [comment]
for example :
app.controller('ctrl', ['$scope', '$http', '$q', 'uiGridConstants', function ($scope, $http, $q, uiGridConstants) {
   $scope.DataGrid = {
        enableSorting: false,
        enableHiding: false,
        enableColumnMenu: false,
        enableColumnResizing: true,
        columnDefs: $scope.Data,
        enableColumnResize: true,
    }
   $scope.DataGrid .onRegisterApi = function (gridApi) {
         $scope.DataGrid Api = gridApi;
         var promise = $q.defer();

         gridApi.edit.on.afterCellEdit($scope, function (rowEntity, colDef, newValue, oldValue) {
               if(condition)
               {
                    promise.resolve();
               }
               else
               {
                    // I want to set old value to cell
                     promise.reject();
               }
         });
   };

}]);
