### ISSUE TITLE
AutoResize does not work properly

### ISSUE THREAD

**Issue by askanhan** [angular-ui/ui-grid#4039]
I don't specified a width or height for the grid and used "ui-grid-auto-resize". It is working but not properly. There is just a small piece of grid over and therefore i see the scrollbars for that specific area which is defined by ui-layout splitter (i dont think the problem resides in ui-layout because it has no issues with my other components). What can i do in order to get away from that scrollbars? I also dont want to define a specific number for the height and width of the grid.

![z](https://cloud.githubusercontent.com/assets/5607648/8853761/97d1683c-315c-11e5-97dc-86e3cf26e8fc.PNG)

**Comment by c0bra** [comment]
Hard to debug without being able to see it live. Can you reproduce it in a plunker?

And is the problem that you have both horizontal and vertical scrollbars for the element containing the grid?
