### ISSUE TITLE
dynamically passing grid parameters to grid

### ISSUE THREAD

**Issue by gindij** [angular-ui/ui-grid#4040]
I am trying to determine value of the ui-grid="..." directive at runtime by getting a field of an object whose keys are ids and values are gridOptions configurations. It ends up looking like ui-grid=obj[id] but when I made this change, the grid no longer renders. Can the directive's value not be parsed at runtime? Do you know how I can fix this?

**Comment by EricCat** [comment]
@gindij  can you please paste your code here?

**Comment by mportuga** [comment]
Closing old issue as it doesn't sound like a bug.
