### ISSUE TITLE
Change the total item count when filtering with external pagination

### ISSUE THREAD

**Issue by lebolo** [angular-ui/ui-grid#4041]
In [ui-grid-grid-footer.html (v3.0.1)](https://github.com/angular-ui/ui-grid/blob/v3.0.1/src/templates/ui-grid/ui-grid-grid-footer.html), the _Total Items_ and _Showing Items_ logic use `grid.rows.length`.

```html
<div class="ui-grid-footer-info ui-grid-grid-footer">
        <span>{{'search.totalItems' | t}} {{grid.rows.length}}</span>
        <span ng-if="grid.renderContainers.body.visibleRowCache.length !== grid.rows.length"
              class="ngLabel">({{"search.showingItems" | t}} {{grid.renderContainers.body.visibleRowCache.length}})
        </span>
</div>
```

When filtering with external pagination, you get

![image](https://cloud.githubusercontent.com/assets/2286572/8856882/8bd9f754-313b-11e5-9ef6-b8996aa03381.png)

where _Total Items_ reflects the number of **filtered** items returned by the server. Instead, I want _Total Items_ to reflect the number of **possible** items on the server.

![image](https://cloud.githubusercontent.com/assets/2286572/8856906/c5fd0f84-313b-11e5-840f-465a1ddf6640.png)

I was thinking of using a custom `grid.options.gridFooterTemplate` that uses a new `grid.options.possibleItems` variable which gets set by the user.

```html
<div class="ui-grid-footer-info ui-grid-grid-footer">
        <span>{{'search.totalItems' | t}} {{grid.options.possibleItems}}</span>
        <span ng-if="grid.renderContainers.body.visibleRowCache.length !== grid.options.possibleItems"
              class="ngLabel">({{"search.showingItems" | t}} {{grid.renderContainers.body.visibleRowCache.length}})
        </span>
</div>
```

1. Any thoughts on this solution?
2. If others find this useful, should I try creating a PR to actually implement something like this?
  - The naming between _possibleItems_ and _totalItems_ is a bit confusing.
  - Should we fall back to using `grid.rows.length` if `typeof grid.options.possibleItems == 'undefined'` or something like that?

**Comment by PaulL1** [comment]
I haven't thought deeply about this, but I note that different people have different use cases - some want to show the visible items, some want to show the full set of items that are out there.  Depending on whether you're using internal or external pagination the behaviour can also be different.  So I'd probably look to something that makes this much more explicit, and supports each flavour of use.

**Comment by lebolo** [comment]
Thanks @PaulL1, I guess I'll leave this open a few days for feedback. If it doesn't get much activity, I'll close it out.

**Comment by bmazaheri** [comment]
Any progress or change on this? I'm facing the same situation and rather to use default footer instead of my custom footer.
