### ISSUE TITLE
pagination:Could not Page To Last

### ISSUE THREAD

**Issue by wmzy** [angular-ui/ui-grid#4045]
anularjs virsion: 1.2.28
angular-ui-grid virsion: 3.0.1

Other buttons are OK!

There is an unexpected:
```
Error: [$parse:syntax] Syntax Error: Token ')' is an unexpected token at column 19 of the expression [paginationApi.seek)] starting at [)].
http://errors.angularjs.org/1.2.28/$parse/syntax?p0=)&p1=is%20an%20unexpected%20token&p2=19&p3=paginationApi.seek)&p4=)
    at VALIDITY_STATE_PROPERTY (http://localhost:3000/lib/angular/angular.js:78:12)
    at Parser.throwError (http://localhost:3000/lib/angular/angular.js:10601:11)
    at Parser.parse (http://localhost:3000/lib/angular/angular.js:10554:12)
    at $get (http://localhost:3000/lib/angular/angular.js:11407:37)
    at chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1707:17
    at Array.forEach (native)
    at ngEventHandler (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1702:20)
    at nodeLinkFn (http://localhost:3000/lib/angular/angular.js:6752:13)
    at compositeLinkFn (http://localhost:3000/lib/angular/angular.js:6146:13)
    at compositeLinkFn (http://localhost:3000/lib/angular/angular.js:6149:13) <button type="button" ng-click="paginationApi.seek(paginationApi.getTotalPages())" ng-disabled="cantPageToLast()">
(anonymous function)	@	angular.js:10126
$get	@	angular.js:7398
nodeLinkFn	@	angular.js:6755
compositeLinkFn	@	angular.js:6146
compositeLinkFn	@	angular.js:6149
compositeLinkFn	@	angular.js:6149
nodeLinkFn	@	angular.js:6746
compositeLinkFn	@	angular.js:6146
publicLinkFn	@	angular.js:6042
newCompile	@	chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:2041
innerCompile	@	ui-grid.js:3064
(anonymous function)	@	ui-grid.js:20420
deferred.promise.then.wrappedCallback	@	angular.js:11682
deferred.promise.then.wrappedCallback	@	angular.js:11682
(anonymous function)	@	angular.js:11768
$get.Scope.$eval	@	angular.js:12811
$get.Scope.$digest	@	angular.js:12623
scopePrototype.$digest	@	chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1924
$get.Scope.$apply	@	angular.js:12915
scopePrototype.$apply	@	chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1987
done	@	angular.js:8450
completeRequest	@	angular.js:8664
xhr.onreadystatechange	@	angular.js:8603
```

**Comment by JLLeitschuh** [comment]
That is very strange. Try upgrading your version of angular and see if you still have the same problem.

**Comment by wmzy** [comment]
I have upgraded it to version 1.3.16.But the problem is still here.

**Comment by JLLeitschuh** [comment]
@c0bra @swalters @AgDude
Any of you have any ideas what would cause this? I'm looking at the code and not seeing a syntax error.
All of the examples work correctly.

@wmzy 
Can you create a plunker that re-creates this error?

**Comment by JLLeitschuh** [comment]
Can you pull down the most recent unstable build and see if you have the same problem as before? The logic behind paging has changed slightly now.

*Aside:* You'll also notice the button styling has also been changed a bit.

**Comment by wmzy** [comment]
Having found the cause, it is conflict with AngularJS Batarang.
But why your sample(http://ui-grid.info/docs/#/tutorial/314_external_pagination) no this problem?
This is my page,may be you need: http://test-wmzy.avosapps.com/#!/finance/wage-strategy
Plunker is unstable in China.

Thanks!

**Comment by JLLeitschuh** [comment]
I tried out your demo site http://test-wmzy.avosapps.com/#!/finance/wage-strategy and didn't see the error.
What browser are you experiencing the problem with?
Our sample (http://ui-grid.info/docs/#/tutorial/314_external_pagination) is running off of the latest unstable wich also has my recent pagination logic changes.
Try clearing your browser's cache. You can enable this to happen automatically when the console is open in the chrome dev settings.

**Comment by wmzy** [comment]
Have you  installed the AngularJS Batarang 0.8.5 ? Try toggling the enable button.
![_022](https://cloud.githubusercontent.com/assets/5526525/8949952/3b37c8c4-35ed-11e5-86b1-cd261215a0ce.png)

**Comment by JLLeitschuh** [comment]
I haven't had any luck getting Batarang to work so I uninstalled it. Try disabling the plugin and see if you still have problems.

**Comment by wmzy** [comment]
Disable the plugin there will no problem.

**Comment by JLLeitschuh** [comment]
I would file a bug report with Batarang then.
