### ISSUE TITLE
Last column disappearing upon edit

### ISSUE THREAD

**Issue by imbalind** [angular-ui/ui-grid#4046]
### Issue
Using a table with editing and cellnav with many columns (in this case it's 25) if I scroll to the last column and edit a field in the table, the last column disappears.

To reproduce, you need to have the browser in full screen (if using Chrome, Firefox is not working even when windowed).

Furthermore, it's working correctly if you run it from inside pluker edit mode.

I'm going on instinct here since we just started looking at ui-grid, but it seems to me that some measurement is failing and it believes the rightmost columns should be falling outside of the visible part of the table, so it doesn't render them.

### Environment
I tried with Firefox (38.0.5) and Chrome (44.0.2403.89 m) on Windows 7 Enterprise, it happens on both. Tried also with clients desktop using Chrome (don't know their version but quite up to date) on Windows XP, it was also affected.

Tried with both angularjs 1.4.3 and 1.3.0, I saw no difference.

### Plunker
http://run.plnkr.co/plunks/PU8B6By5kZfy1rAqfXml/

### Images
![image](https://cloud.githubusercontent.com/assets/2514478/8875920/984d5742-321c-11e5-8d76-555d3aa3a254.png)
![image](https://cloud.githubusercontent.com/assets/2514478/8875996/0d586b8a-321d-11e5-9dc0-921380064fb5.png)

**Comment by imbalind** [comment]
I started looking into it and I found the following.

The problem seems to be in function [adjustColumns](https://github.com/angular-ui/ui-grid/blob/424212cb43dbe34b86706c3355ebf07e1bfef547/src/js/core/factories/GridRenderContainer.js#L480) where arguments are `scrollLeft` and `scrollPercentage`.

When I scroll, both have a value and everything works ok; but, after an edit, only `scrollLeft` has a value while `scrollPercentage` is `null`.

Some ten lines below, if `scrollPercentage` is `null`, it's evaluated as `scrollLeft / self.getCanvasWidth()`.

For instance, in the picture you see above, values are something like:
```
scrollLeft = 2017
self.getCanvasWidth() = 3240
scrollPercentage = scrollLeft / self.getCanvasWidth() = 0.6225308641975309
```

This leads to a range whose max is around 24 while my rightmost column index is 25, so it doesn't get rendered.

I don't know yet where the value of `self.getCanvasWidth() = 3240` is too high or the `scrollPercentage` should have a value.

**Comment by imbalind** [comment]
I just saw that in [scrollHorizontal](https://github.com/angular-ui/ui-grid/blob/424212cb43dbe34b86706c3355ebf07e1bfef547/src/js/core/factories/GridRenderContainer.js#L378-380) the percentage is calculated as 
```
horizScrollPercentage = newScrollLeft / horizScrollLength
```
with 
```
horizScrollLength = (this.canvasWidth - this.getViewportWidth())
```
instead than merely dividing by `canvasWidth`.

Is this needed or something that needs to be fixed?

**Comment by bkirtika** [comment]
still Last column disappearing upon edit on updated version 3.0.4.

**Comment by bkirtika** [comment]
any updates ?
