### ISSUE TITLE
Less-than filter excludes all rows when erased manually and another filter is still applied on the same column

### ISSUE THREAD

**Issue by mage-eag** [angular-ui/ui-grid#4055]
This behaviour is reproducible on the [filtering tutorial](http://ui-grid.info/docs/#/tutorial/103_filtering) :

1. Filter the "Age" column on values greater than 1
2. Filter the same column on values lesser than 30
3. Erase the "less than" field manually (not using the dedicated button)

Result : all the rows are now filtered out.

The reason seems to be that the `term` value is not reset to `null` or `undefined` when the corresponding field is erased by hand, but is still taken into account because another filter on the same column still has a "valid" `term` value.

I managed to fix this by [testing for an empty string when number values are involved](https://github.com/mage-eag/ui-grid/commit/2914f1bfe41e008533a31879e0ecf593995eae48), but I'm not sure at all whether this is a convenient solution, or if this could bring unwanted side-effects.

Please let me know what are your thoughts about it, and whether I can create a PR with the [possible fix](https://github.com/mage-eag/ui-grid/commit/2914f1bfe41e008533a31879e0ecf593995eae48).

**Comment by alam123** [comment]
I have already raised this issue and submitted a pull request.

https://github.com/angular-ui/ui-grid/issues/3923
https://github.com/angular-ui/ui-grid/pull/4012

**Comment by mage-eag** [comment]
Oops sorry, I had seen  your PR but funnily did not make the connection .. thanks, will start using it right away :)
