### ISSUE TITLE
gridFooterTemplate  height issue.

### ISSUE THREAD

**Issue by ravivantaku** [angular-ui/ui-grid#4062]
Hi ,

I am using ui-grid (latest version ) and i need to display Total , Avg and Grand total line by line. To achieve this i used gridFooterTemplate property with custom template. The functionality is as expected as but i got footer height css issue. I tried to change the height of the grid footer but i couldn't get it. I have created a plunker to explain this issue.

http://plnkr.co/edit/ZExYs9OpXJCpESjm5X3G?p=preview 

Here is the image to show the issue.
![plunkerfooter](https://cloud.githubusercontent.com/assets/2960501/8925779/4ff3f0d2-3528-11e5-90d9-b9e599614c02.PNG)

Thanks in advance.

**Comment by ingshtrom** [comment]
+1. I am also seeing this issue. I thought it originally was a problem with using float styles, but I think there is a larger problem going on.

**Comment by ingshtrom** [comment]
I found a gridOption that allows you to set the height: `gridFooterHeight`. Here is a plunkr: http://plnkr.co/edit/dmnoA7XfMyePiZnaWHYw?p=preview.

I don't see any documentation on it. Can anyone verify if this is supposed to a public API?

Also, is there a reason we can't just control this via css?

**Comment by ravivantaku** [comment]
Thanks @ingshtrom. It's resolve my issue.
