### ISSUE TITLE
Angular version upper bound is specified as 1.3.16, not 1.3.17

### ISSUE THREAD

**Issue by jgilchrist** [angular-ui/ui-grid#4064]
[Here](https://github.com/angular-ui/ui-grid/blob/efb18688d3642bb968c7fb747d89ffe20a1fc6dc/lib/grunt/plugins.js#L311) the upper bound for Angular is specified as 1.3.16 - however, the README claims to support any 1.3.x version, so the upper bound should instead be 1.3.17.

**Comment by jgilchrist** [comment]
Seems like the bound should be `~1.3.16` to denote 'any patch level change above 1.3.16'?

**Comment by c0bra** [comment]
Bower refuses to work with a range from one version to another that isn't fixed to an explicit number; not sure why.

See this comment: https://github.com/angular-ui/ui-grid/issues/3925#issuecomment-119118630

**Comment by jgilchrist** [comment]
That's odd - if I run:

```
> semver.maxSatisfying(['1.3.16', '1.2.18'], '>=1.2.16 <=1.3.16')
'1.3.16'
```

Seems to work fine for me, as does:

```
> semver.maxSatisfying(['1.3.17', '1.2.18'], '>=1.2.16 ~1.3.16')
'1.3.17'
```

**Comment by c0bra** [comment]
You're right; weird.

```javascript
var semver = require('semver');
var bowersemver = require('bower-semver');

console.log('bower', bowersemver.maxSatisfying(['1.3.16', '1.2.18'], '>=1.2.16 <=1.3.16'));
console.log('semver', bowersemver.maxSatisfying(['1.3.16', '1.2.18'], '>=1.2.16 <=1.3.16'));
```

**Comment by jgilchrist** [comment]
Looks like you might be using conflicting syntaxes?

The `.x` syntax expresses a distinct constraint to using `<=`. If you remove the <= then you get the correct result.

```
// Undefined behaviour?
// Either that or it's saying 'less than any patch 1.3.x' so it picks a version in 1.2.x
> semver.maxSatisfying(['1.3.16', '1.2.18'], '>=1.2.16 <=1.3.x')
'1.2.18'

// Correct result
> semver.maxSatisfying(['1.3.16', '1.2.18'], '>=1.2.16 1.3.x')
'1.3.16'

**Comment by c0bra** [comment]
doh, I see. silly me

**Comment by jgilchrist** [comment]
Yeah, not a clue. `bower-semver` doesn't look like much more than a thin wrapper around semver. Their maxSatisfying function does some filtering based around pre-releases.

Thanks for the fix!
