### ISSUE TITLE
Save/restore selection state coming from data

### ISSUE THREAD

**Issue by gizbo** [angular-ui/ui-grid#4065]
Hello guys,
   Is there a way the save/restore grid selection state from the actual data (row.entity attribute). My scenario is somewhat complex to explain but roughly I have a view that has pages of grids... So I implemented external paging to only show 5 grids at a time. I implement the row selection to modified row.entity with  selected flag property. Is there a way to set the selection base on that flag property?

Thanks,
Yves

**Comment by mportuga** [comment]
Closing old issue.
