### ISSUE TITLE
Broken tutorial link homepage

### ISSUE THREAD

**Issue by clmntfrndz** [angular-ui/ui-grid#4068]
Hi, I think it's temporary but the tutorial link on the http://ui-grid.info/ (next to download) is currently pointing to http://127.0.0.1:9003/docs/#/tutorial.
Link in the navbar is ok though so it's not critical.

**Comment by Leo-g** [comment]
I get the same the thing even when you click on UI GRid link on  http://ui-grid.info/docs/#/api you get redirected to http://127.0.0.1:9003/

**Comment by dharmesh08** [comment]
Also getting redirect to http://127.0.0.1:9003/

**Comment by JLLeitschuh** [comment]
Should be fixed now.
