### ISSUE TITLE
Using windowing with external pagination

### ISSUE THREAD

**Issue by feralanPaladin** [angular-ui/ui-grid#4069]
Hi,

By studying your external pagination tutorial, I can manage to set an external pagination to my grid. But  my aim is to use windowing and get data of 3 pages (One page contains 10 rows, so I need to get 30 rows each time) with one call. Although I can get the data (30 rows), the grid cannot show them properly and show all the data that I received from external call (all the 30 rows). Additionaly the footer acts as there are no problem. (Shows the page size as 10 and the element interval as (1-10 of 987 items))

Thanks for your help.

**Comment by mportuga** [comment]
Closing old issue
