### ISSUE TITLE
[Bug] cellNav and rowHeight > 30 = top row not full visible

### ISSUE THREAD

**Issue by fk-mbc** [angular-ui/ui-grid#4070]
If you want to use another rowHeight than 30 and you navigate down all is fine, but when you navigate up, you only see a half of the top row.

To reproduce it:
1. click on any cell
2. use arrow key to navigate down until some rows on the top are gone
3. use arrow key to navigate up
4. if you reach the top row, you will only see the half of it

Configuration:
 $scope.gridOptions = {
    rowHeight: 55 //or any higher value than 30
 };

Here is the plnkr:
http://plnkr.co/edit/vhip1w?p=preview

**Comment by fk-mbc** [comment]
?

**Comment by fk-mbc** [comment]
After a lot of trying and searching through the features, i find out, that i need also specify the row height of the headerRow! The difference in scrolling up came from the 30px of the headerrow. That is bad! But as workaround, when someone also need to fix it, you have to specify the headerRowHeight with the same value of the rowHeight.
```javascript
scope.gridOptions.rowHeight = 55;
scope.gridOptions.columnFooterHeight = 55;
scope.gridOptions.gridFooterHeight = 55;
scope.gridOptions.headerRowHeight = 55;
```

**Comment by mportuga** [comment]
This doesn't really sound like a proper bug, but more of a nuance of having a different rowHeight compared to the headerRowHeight. Seeing as there is a workaround and this issue is quite old, I will be closing it.
