### ISSUE TITLE
Changes to gridMenuShowHideColumns aren't visible in open gridMenu

### ISSUE THREAD

**Issue by marshauf** [angular-ui/ui-grid#4072]
Hello,

changing the value of gridOptions.gridMenuShowHideColumns isn't reflected in an open grid menu.
To see the changes I need to call grid.gridMenuScope.toggleMenu() twice to close and open the menu again.

Thanks in advance.

**Comment by zmetcalf** [comment]
+1 - `getMenuItems` is only called under toggleMenu. I cannot figure where to run `uiGridGridMenuService.getMenuItems` so that it is called on initialization.

**Comment by PaulL1** [comment]
It's deliberately under toggleMenu.  We don't initialise it until someone tries to display it.  That also means that we getMenuItems every time we display, and therefore people can make those values somewhat dynamic.

**Comment by zmetcalf** [comment]
Sorry, I may have gotten ahead of myself there. `gridMenuShowHideColumns` is only referenced in `getMenuItems`. `getMenuItems` was only referenced in the toggle; having it in toggle makes sense of course. 

Should `getMenuItems` be run elsewhere or should an existing function supposed to reference `gridMenuShowHideColumns` elsewhere?
