### ISSUE TITLE
Customizer broken?

### ISSUE THREAD

**Issue by MattHoneycutt** [angular-ui/ui-grid#4079]
Am I missing something, or is the Customizer completely broken?  I tried changing to one of the other themes, and while the various variables in the text boxes change, there is no change in the appearance of the grid on the page.  And, if I change the value in one of the text boxes, nothing at all seems to happen.  If I change a variable, then try to download the CSS, the CSS is empty.

I tried this in Chrome, IE, and Firefox.

**Comment by JLLeitschuh** [comment]
Most up to date info on this is documented here: #4173
