### ISSUE TITLE
cellFilter's support to angular custom filter "filter:"

### ISSUE THREAD

**Issue by xforceco** [angular-ui/ui-grid#4081]
Does cellFilter support custom filter in the form of "filter:XXX"? It does not seem to work.

For example,
    cellFilter: 'filter:grid.appScope.stateFilter:this'

**Comment by JLLeitschuh** [comment]
http://ui-grid.info/docs/#/tutorial/306_custom_filters

**Comment by xforceco** [comment]
Sorry for the ambiguity, I am talking about the kind of expression angularjs allows in their filters
https://docs.angularjs.org/api/ng/filter/filter
With format, {{ filter_expression | filter : expression : comparator}}

But UI-GRID only supports filter that is declared as filter under controller

**Comment by mportuga** [comment]
Closing this as it is not a bug and it is old.
