### ISSUE TITLE
ui-grid-selection breaks filtering?

### ISSUE THREAD

**Issue by Bioto** [angular-ui/ui-grid#4086]
I'm trying to create a table using ui.grid, I have the table working correctly however the issue comes in when I try to enable filtering on the columns.

When I have ui-grid-selection directive on my table it disables the filtering input boxes for my columns. 

I have the following snippit for my calendar:

    <div external-scopes="clickHandler" ui-grid="tableService.options" class="myGrid" ></div>

My options are:

    enableColumnResizing: true,
    showColumnMenu: true,
    enableGridMenu: true,
    paginationPageSizes: [5, 10, 25],
    paginationPageSize: 5,
    enableRowSelection: true,
    enableSelectAll: true,
    selectionRowHeaderWidth: 35,
    rowHeight: 35,
    showGridFooter:true,
    columnDefs: [],
    multiSelect: true,
    gridApi: null,
    enableFullRowSelection: true,
    enableFiltering: true,

Without ui-grid-selection the table looks like:
[![Without ui-grid-selection][1]][1]

With ui-grid-selection the table looks like:
[![With ui-grid-selection][2]][2]

  [1]: http://i.stack.imgur.com/r6zXR.png
  [2]: http://i.stack.imgur.com/8EmnV.png

I can't see any documentation on using both filtering and selection. Am I missing something?

**Comment by lebolo** [comment]
This [tutorial](http://ui-grid.info/docs/#/tutorial/401_AllFeatures) shows multiple features enabled and working correctly. Did you add the module and directive for selection? From the [selection tutorial](http://ui-grid.info/docs/#/tutorial/210_selection):

> This grid example uses the ui-grid-selection directive to row selection. To enable, you must include the `ui.grid.selection` module and you must include the `ui-grid-selection` directive on your grid element.

```
angular.module('app', ['ui.grid', 'ui.grid.selection']);
```

```
<div ui-grid="gridOptions" ui-grid-selection class="grid"></div>
```

If not, check the console to see if any error messages are being printed out or try creating a plunker.

**Comment by Bioto** [comment]
Looks like you need to load the columndefs and set the data before the table is even loaded to get the selection + filtering working

**Comment by Magn3s1um** [comment]
To work around this issue, I added a dummy column defintion before the data was loaded: 

      $scope.gridOptions =
        {
            paginationPageSizes: [50, 100, 150],
            paginationPageSize: 50,
            useExternalPagination: true,
            enableGridMenu: true,
            enableFiltering: true,
            columnDefs: [{field: "test"}],

Then it allows me to set the columnDefs after making a request for data.
