### ISSUE TITLE
grid.appScope.functionName requires $scope to be brought into the controller

### ISSUE THREAD

**Issue by tonyeung** [angular-ui/ui-grid#4089]
If i write my angular controllers like so:

```
angular
    .module('app')
    .controller('Avengers', Avengers);

function Avengers() {
    var vm = this;
    vm.foo = 'bar';
}
```

and have a column defined like so

```
{  
   name:'Delete',
   width:75,
   pinnedLeft:true,
   enableCellEdit:false,
   cellTemplate:'<div class="ui-grid-cell-contents"> <button type="button" class="btn btn-xs btn-danger" ng-click="grid.appScope.removeRow(row)"><span class="glyphicon glyphicon-trash"></span></button> </div>'
}
```

I will need to bring in $scope in order to access the call to `removeRow(row)`

Is this required for every controller I have ui-grid in or am I missing something?

**Comment by swalters** [comment]
yes, scope is required.  we use $scope to destroy the listener on scope.destroy.  this is the only way that I know of to listen to a destroy event, even when using controller as syntax
