### ISSUE TITLE
Get selected row only through templates?

### ISSUE THREAD

**Issue by specialjyo** [angular-ui/ui-grid#409]
I modified my rowTemplate to tell me when a row is selected, is there another way to get the selected row object without the use of a template?

**Comment by sureshvsvb** [comment]
This is working for initial selection. When i change the data of the grid (through some API call) and try to do a new row selection, then previous selected items are retained and the new selections are appended to the previous list.
Setting the value of the selectedItems to [] is not working.

http://plnkr.co/edit/CncDWCktXTuBQdDVfuVv

Once the value is set after the initial load, it is not changing.
