### ISSUE TITLE
Selection row header with filtering, sorting, pinning, etc.?

### ISSUE THREAD

**Issue by lebolo** [angular-ui/ui-grid#4095]
Is it possible to have a selection row header with sorting, filtering, pinning, etc.?

I think the filter container in column headers has an _ngIf_ with `!col.isRowHeader`. But I'm not sure which template (if any) to modify in order to enable sorting, filtering, pinning, hiding, etc.

The end goal is to have a selection row header that I can sort (based on whether the row is selected or not), filter (only show selected or non-selected rows), hide and unpin if needed. It would also be nice to keep the _Select All_ functionality. If there's a better route, I'm open to suggestions.

I set up a [plunker](http://plnkr.co/edit/7oF4A0?p=preview) based on the custom row header tutorial, but again, not sure if this is the best route.

I've also asked this question on [SO](http://stackoverflow.com/q/31687827/1370556).

**Comment by swalters** [comment]
Ability to Filter the row selection is on the roadmap as I need it for my application.  Probably 2 or 3 weeks away.  We should enable sorting as well.  

Pinning - that makes no sense to me as it is pinned to the left already. 

Hiding - I guess we can add it to the list of available hidden fields...  Might be tougher than it sounds.

**Comment by lebolo** [comment]
Thanks @swalters, I'll close this issue then. I ended up just creating a column definition with custom header/cell templates in the meantime.

> Pinning - that makes no sense to me as it is pinned to the left already.

It would be nice to **un-pin** it if the user wants to for whatever reason, but I agree it's not a common use-case.
