### ISSUE TITLE
sort & grouping properties not fully documented

### ISSUE THREAD

**Issue by wesleycho** [angular-ui/ui-grid#4098]
The `grouping` property of `columnDef` is not documented at all - I'm not quite sure what are the options available here.

For the `sort` property for `columnDef`, the `priority` property is not documented, which appears to be necessary in order to have a default sort direction shown.

If some description of both are given, I'm more than willing to file a PR to improve the docs.

**Comment by PaulL1** [comment]
Grouping is documented here: http://ui-grid.info/docs/#/api/ui.grid.grouping.api:ColumnDef

The doco could stand to be updated for priority, although I think the tutorial shows it.

**Comment by wesleycho** [comment]
I found that grouping doc afterwards - I also saw the priority in the tutorial, but not in the API section (where I first looked).

What does the priority do though? I just set it to 0, but I'd need to understand what it does exactly in order to document it :) .

**Comment by lebolo** [comment]
There's a little documentation in http://ui-grid.info/docs/#/tutorial/102_sorting

> You can set an initial sort state for the grid by defining the `sort` property on your column definitions. The `direction` sub-property says which way to sort, and the `priority` says what order to sort the columns in (lower priority gets sorted first).

Would be good to have it in the API section, mentioning that it starts counting from 0 =) Thx!

**Comment by JLLeitschuh** [comment]
Actually, that PR only solves half of the problem with the documentation. Ah well...
