### ISSUE TITLE
Minified file size too big

### ISSUE THREAD

**Issue by hybmg57** [angular-ui/ui-grid#4099]
Minified file is like 300kb. Is there a way to separate them so you have something like 'core', 'export-csv', 'grouping' etc.

**Comment by swalters** [comment]
This is something that is on the roadmap.  Would be great if a grunt expert jumped in and created a PR to do this.

**Comment by JLLeitschuh** [comment]
I'll probably take a crack at this at some point but I don't have time right now. If anyone beats me to it I don't mind.

**Comment by hybmg57** [comment]
Probably need gulp version also

**Comment by Robinson7D** [comment]
Should not need both. Grunt alone will suffice.

**Comment by mportuga** [comment]
Closing as this is a duplicate of #3421
