### ISSUE TITLE
ng-mouseenter on rowTemplate

### ISSUE THREAD

**Issue by meixuexiang** [angular-ui/ui-grid#4102]
![qq 20150803173056](https://cloud.githubusercontent.com/assets/240876/9034867/8eb0591e-3a05-11e5-8777-5d8c47a65958.jpg)

demo: http://plnkr.co/edit/22RfEEcvBLK0OSKkWjiB?p=preview

**Comment by mportuga** [comment]
Closing since there is not enough information on this bug.
