### ISSUE TITLE
How can you expand rows by clicking on one of the colums of the row and not the '+' icon?

### ISSUE THREAD

**Issue by sanke93** [angular-ui/ui-grid#4106]
I am trying to expand the rows by clicking on one of the columns itself (and not the + sign). Is there any way to customize this so the row expands by clicking (as in the doc example) on a specific ID or a name?

Doc for expandable grid: http://ui-grid.info/docs/#/tutorial/216_expandable_grid

**Comment by bhrugs** [comment]
set row.isExpanded= true,
to make the row expand.

you can get this row, by this event 
gridApi.expandable.on.rowExpandedStateChanged($scope, function(row){
 row.isExpanded= true,//once you get the row object as param, set this isExpanded property to true
});

**Comment by manjunathmofs** [comment]
can use this if need
http://plnkr.co/edit/YnLVEUS4gmZWXjgsNXdU?p=preview
