### ISSUE TITLE
Font seems "blurry"

### ISSUE THREAD

**Issue by twjacobsen** [angular-ui/ui-grid#4118]
Hi,

I've been looking for the source of this annoyance for quite a while now, and I can't seem to figure out what's happening.

As far as I can tell, the ui-grid CSS don't do anything to my font, but maybe someone inhere can guide me in the right direction.

As the title says, the text in the ui-grid seems blurry, compared to using a regular table.

I've attached a screenshot, showing the issue:
![image](https://cloud.githubusercontent.com/assets/555812/9082280/37a82a8e-3b63-11e5-8adf-6d3dc4fb7fd2.png)

It's quite clear, that both headings and row-text are more "anti-aliased" in UI-Grid, rather than.

Note: I've not been able to reproduce the issue in Firefox, so it might be a Chrome, issue? How Chrome renders javascript-inserted DOM elements?
I tried pasting the test-div into various locations in UI-grid using the inspector, and the text never "smoothed" using this method. It only happens when UI-Grid is loading.

Just for clarity, here's a screenshot of UI-Grid without my custom CSS, and it's still clear how the row-text is rendered differently than the standard table above:
![image](https://cloud.githubusercontent.com/assets/555812/9082428/3b36ae7c-3b64-11e5-8577-0eb0f2ce207c.png)

**Comment by khamani** [comment]
I am also having exactly the same issue in Chrome. Have you find a solution for it?

**Comment by ben-henoida** [comment]
I am still seeing this problem in v4.0.6 with Chrome.
Have you found a solution for it?

It seems related to a 'ClearType / sub pixel rendering' (I gathered from https://graphicdesign.stackexchange.com/questions/930/why-does-anti-aliasing-in-black-characters-use-colors-other-than-gray-scale)
