### ISSUE TITLE
Column width issue on load

### ISSUE THREAD

**Issue by falcongforce** [angular-ui/ui-grid#4121]
I am not sure if this issue has already been reported, but there is an issue with the column widths on load when the grid is initialized while hidden and the data is loaded with ajax/timeout. Re-sizing the screen fixes the issue.
Here is a Plunker: http://plnkr.co/wHEcG91q7832yCYMk7i2

**Comment by swalters** [comment]
duplicate of https://github.com/angular-ui/ui-grid/issues/4005

**Comment by swalters** [comment]
Oops. posted to soon

**Comment by falcongforce** [comment]
Does anyone have a solution for this issue or a workaround?

Thanks

**Comment by lebolo** [comment]
I don't know specifically what you're running up against (got a Plunker?), but have you looked at the [tutorial](http://ui-grid.info/docs/#/tutorial/108_hidden_grids)? It lists some possible solutions.

**Comment by falcongforce** [comment]
Check out this plunk: http://plnkr.co/edit/wHEcG91q7832yCYMk7i2?p=preview

**Comment by lebolo** [comment]
I see, one solution is to use `ng-if` (mentioned in the above tutorial) instead of `ng-show`. However, keep in mind that [ngIf](https://docs.angularjs.org/api/ng/directive/ngIf) recreates the element/scope, so make sure to read up on it.

**Comment by falcongforce** [comment]
Thanks Luis. That was very helpful!

**Comment by lebolo** [comment]
For future users who have trouble with `ngIf`, you can also use the CSS [`visibility`](https://developer.mozilla.org/en-US/docs/Web/CSS/visibility) property via `ng-style="{visibility: gridOptions.data && gridOptions.data.length > 0 ? 'visible' : 'hidden'}"`
