### ISSUE TITLE
How to disable column / table sorting (initially enabled)? What is an API for that? 

### ISSUE THREAD

**Issue by iyel** [angular-ui/ui-grid#4127]

**Comment by tringuyenminh92** [comment]
have u tried to set $scope.gridOptions.enableSorting=false; ?

**Comment by iyel** [comment]
@tringuyenminh92 yes, no effect

**Comment by bertomaniac** [comment]
I'm having the same issue. I want to be able to disable sort completely depending on the page state where the grid is used. 
Could line 329 in `ui-grid-header-cell.js` be changed to something like this:
```
var dataChangeDereg = $scope.grid.registerDataChangeCallback( updateHeaderOptions, [uiGridConstants.dataChange.COLUMN, uiGridConstants.dataChange.OPTIONS]
```
so that `updateHeaderOptions()` is called if you change `gridOptions.enabledSorting` after it is initialized?

**Comment by DmitryEfimenko** [comment]
`$scope.gridOptions.enableSorting=false;` worked for me.
Please provide plunker showing the issue.

**Comment by bertomaniac** [comment]
@DmitryEfimenko,
Within the controller, if you initially set `$scope.gridOptions.enableSorting = false` this works fine.  However, for example if you initialize the controller with `$scope.gridOptions.enableSorting = true` and have a button on that same view that sets `$scope.gridOptions.enableSorting = false`, the grid column headers still show the triangles.

I will try to set up a Plunker here in a minute.

**Comment by iyel** [comment]
Take a look. I didn't tried yet but I guess it would help. http://stackoverflow.com/a/32525785?noredirect=1

**Comment by mportuga** [comment]
Closing as this is not a bug.
