### ISSUE TITLE
Suggestion: a more reliable solution for grids within tabs

### ISSUE THREAD

**Issue by groovy9** [angular-ui/ui-grid#4130]
Setup: Angular 1.4.3, ui-grid 3.0.1-d609a10, Semantic UI 2.0.7, Chrome 44 on Linux.

Having read all the docs and several discussions on the topic, the official suggestions (ng-if, auto-resize) both seem to have problems.

ng-if: doesn't reliably draw all rows present in the data on first navigating to the tab.  user has to scroll or resize to get them all to show

auto-resize: when scrolling down the data, then tabbing out and back in, grid is blank until resizing or rescrolling and previous scroll position is lost

both: intermittently, reloading the app (with a grid inside an inactive tab), then navigating to another browser tab, then navigating back to the app's browser tab, then clicking the previously inactive tab with the grid results in the grid being drawn with a large, blank header row and no data.  Remains broken until refreshing the app.

The only reliable solution I've found is to call:
```
$scope.gridApi.core.handleWindowResize()
$scope.gridApi.core.queueGridRefresh()
```
via a click handler on the tabs

The grid then gets reliably drawn in all circumstances so far and preserves the scroll state unless it's the first redraw since a window resize.  Code below.  The classes that don't start with "ard" are stock Semantic UI classes for controlling their tab sets.

```
<div class="ui container ardPage">
    <div class="ui top attached tabular menu" ng-controller="tabsController">
        <a class="active item" data-tab="employees" ng-click="employeesActive()">Employees </a>
        <a class="item" data-tab="vehicles" ng-click="vehiclesActive()">Vehicles</a>

    </div>

    <div class="ui bottom attached active tab segment ardTab" data-tab="employees">
        <div ng-controller='employeesController' class="ardGrid">
            <div ui-grid="gridOptions" class="ardGrid"></div>
        </div>
    </div>

    <div class="ui bottom attached tab segment ardTab" data-tab="vehicles" ng-controller="vehiclesController">
        <div class="ardGrid">
            <div ui-grid="gridOptions" class="ardGrid"></div>
        </div>
    </div>
</div>
```

```
.ardPage {
    height: 100%;
    padding-top: 1em;
}
.ardTab {
     height: calc(100% - 5em);
}
.ardGrid {
    height: 100%;
}
```

```
$scope.vehiclesActive = function () {
            $rootScope.$broadcast('vehiclesActive');
};
$scope.employeesActive = function () {
            $rootScope.$broadcast('employeesActive');
};
```

```
$scope.refresh = function() {
                $scope.gridApi.core.handleWindowResize();
                $scope.gridApi.core.queueGridRefresh();
};

$rootScope.$on('vehiclesActive', function () {
                $timeout($scope.refresh, 100);
});
```

Perhaps it's worth looking into altering the auto-resize directive to do what I've done above, chaining handleWindowResize and queueGridRefresh or similar, rather than forcibly redrawing everything even if a resize hasn't happened.

**Comment by zalayeto** [comment]
I'm facing the same issues. In my case, I tried to use the same workaround but the scroll state is not preserved.

**Comment by Parallax22** [comment]
Haven't tried your solution yet groovy9 but did want to add that I'm having the same issue maintaining scroll position in grids within tabs. For me it's specifically an IE issue (we support IE 9+). Save and restore state does work but cumbersome to implement on our many grids within tabs. AG Grid and others have the same problem maintaining scroll in tabs for IE (ui grid and others work fine in other browsers for us when in tabs or using ng-show). We have the same issue with ng-show in IE also that many folks have reported
