### ISSUE TITLE
treeview + selection feature clash: cannot expand tree without selecting the row

### ISSUE THREAD

**Issue by nickolas1** [angular-ui/ui-grid#4131]
When using a treeview grid with selectable rows, there is no way to manipulate the tree visibility without selecting rows with each interaction. 

E.g. in [this plunker](http://plnkr.co/edit/GTlvny2DZPn0pWU3DfNl?p=preview)
1. select the row with number = 3
2. expand the row with number = 2 to inspect its children

Row 2 is now selected; it seems preferable to disable selection in the treeview control column so that tree manipulation can take place independent of row selection.

**Comment by tringuyenminh92** [comment]
you could use enableRowSelection: false and enableRowHeaderSelection: true
So that there will be a checkbox column for selection. then when you expand one row. it will not select that row.

**Comment by nickolas1** [comment]
yes, that's a workaround for now, thanks. the visual clutter of a tree control column plus a selection column is a bit inelegant though, and not being able to use row selection isn't really satisfactory.

**Comment by briankir** [comment]
a bit old, and still a hack, but i figured i'd leave what i have here:

```javascript
  $scope.gridOptions.onRegisterApi = function( gridApi ) {
    var onRowsRenderedOff = gridApi.core.on.rowsRendered( null, function() {
      onRowsRenderedOff(); // run once
      triggerRowSelectOnClick( '#treeGrid' ); // requires '.ui-grid-canvas'
      // replace '#treeGrid' with yours
    } );
  };
```
...
```javascript
  function triggerRowSelectOnClick( yourGridId ) {
    $( yourGridId + ' .ui-grid-contents-wrapper > [role=grid] .ui-grid-canvas' )
    .delegate( '.ui-grid-row', 'click', function( ev ) {
      jqRow = $( this ); // '.ui-grid-row'
      var index = jqRow.index();
      var commonAncestor = jqRow.closest( yourGridId + ' .ui-grid-contents-wrapper' );

      var selectButtonQuery = [
        '.ui-grid-pinned-container', // left side class
        '[role=grid] .ui-grid-canvas', // redundant, but doesn't hurt
        '.ui-grid-row .ui-grid-selection-row-header-buttons' // select button class
      ].join( ' ' );
      var checkboxDiv = commonAncestor.find( selectButtonQuery );
      checkboxDiv.get( index ).click();
    } );
  }
```

**Comment by remmeier** [comment]
problem is in the current uiGridCell directive implemention:

 function registerRowSelectionEvents() {
              if ($scope.grid.options.enableRowSelection && $scope.grid.options.enableFullRowSelection) {
                $elm.addClass('ui-grid-disable-selection');
                $elm.on('touchstart', touchStart);
                $elm.on('touchend', touchEnd);
                $elm.on('click', selectCells);

                $scope.registered = true;
              }
            }

it disables tree expand button as well.

**Comment by wikola** [comment]
I found a solution without JQuery with a directive without touching the heart:

```javascript
app.directive('uiGridRow', [function () {
    return {
        //Base on class
        restrict: "C",
        //Require a parent directive uiGrid
        require: '^uiGrid',
        scope: false,
        link: function ($scope, $elm, $attr, uiGridCtrl) {
            /*jshint unused: true */
            $elm.on('click', function () {
                if (angular.isDefined($scope.row.entity.cunite)) {
                    uiGridCtrl.grid.appScope.select({item: $scope.row.entity});
                    $scope.$apply();
                }
            });
        }
    };
}]);
```

In scope controller:
```javascript
$scope.select = function (item) {
//Item = row entity
....
}
```

**Comment by kingcheez** [comment]
@wikola Does this override the `uiGridRow` from core `ui-grid`?

**Comment by wikola** [comment]
it is not a directive to add to your project. It is based on the class .uiGridRow

Date: Mon, 1 Feb 2016 08:52:30 -0800

**Comment by kingcheez** [comment]
@wikola OK, I got the PEBKAC fixed.

**Comment by kingcheez** [comment]
In case this helps anyone else, this is what I'm using (based on @wikola's message) to get the row to expand when clicked. Ideally, I'd detect only when the row header is clicked, but this is better than it not working at all.

```javascript
module.directive('uiGridRow', [function () {
  return {
    //Base on class
    restrict: "C",
    //Require a parent directive uiGrid
    require: '^uiGrid',
    scope: false,
    link: function ($scope, $elm, $attr, uiGridCtrl) {
      /*jshint unused: true */
      $elm.on('click', function () {
        if($scope.row.treeNode.children.length > 0)
          uiGridCtrl.grid.appScope.gridApi.treeBase.toggleRowTreeState($scope.row);
        $scope.$apply();
      });
    }
  };
}]);
```

**Comment by joterce** [comment]
If someone still looking for workaround about it i found a sulution:

```
angular.module("app", ["ui.grid.selection"]).config(function($provide) {

  $provide.decorator('uiGridSelectionService', function($delegate) {
    // let's copy original method
    var originalMethod = $delegate.toggleRowSelection;

    // let's ovveride method
    $delegate.toggleRowSelection = function(grid, row, evt, multiSelect, noUnselect) {
      if(!angular.element(evt.currentTarget).hasClass("ui-grid-row-header-cell")) {
        originalMethod(grid, row, evt, multiSelect, noUnselect);
      }
    };
    return $delegate;
  });
});
```

**Comment by mportuga** [comment]
This issue has been fixed by this PR:
https://github.com/angular-ui/ui-grid/pull/6633
