### ISSUE TITLE
Ui Grid Tree View - Show Tree Icon based on condition

### ISSUE THREAD

**Issue by pprabhu59** [angular-ui/ui-grid#4134]
Hello,

I am retrieving records from server (JSON). I do have a field in JSON which indicates the current row has children ( which i will trigger a server call  on row expanded event). How can i selectively show the tree icon.

Ex : if {"access_level_flag":"Y"} -> Show tree icon. (Suppose we have 10 records with  {"access_level_flag":"Y"} ).
Initially if i have 50 records loaded and  do a angular for loop to check if access_level_flag is' Y' and set $$treeLevel to 0.Only 10 records with tree icon will be displayed. 
Records with access_level_flag is' N' will get grouped inside records with access_level_flag is' Y'.

I don't want records with access_level_flag is' N to be grouped inside other rows. It should be individual rows.

UI should have 50 records with only 10 having tree icons.

**Comment by tringuyenminh92** [comment]
This is my cellTemplate for column that i want to show tree icon

  $scope.treeIconWithFieldTemplate = "<div class=\"ui-grid-cell-contents\" title=\"TOOLTIP\"><div style=\"float:left;\" class=\"ui-grid-tree-base-row-header-buttons\" ng-class=\"{'ui-grid-tree-base-header': row.treeLevel > -1 }\" ng-click=\"grid.appScope.toggleRow(row,evt)\"><i ng-class=\"{'ui-grid-icon-minus-squared': ( ( grid.options.showTreeExpandNoChildren && row.treeLevel > -1 ) || ( row.treeNode.children && row.treeNode.children.length > 0 ) ) && row.treeNode.state === 'expanded', 'ui-grid-icon-plus-squared': ( ( grid.options.showTreeExpandNoChildren && row.treeLevel > -1 ) || ( row.treeNode.children && row.treeNode.children.length > 0 ) ) && row.treeNode.state === 'collapsed'}\" ng-style=\"{'padding-left': grid.options.treeIndent * row.treeLevel + 'px'}\"></i> &nbsp;</div>{{COL_FIELD CUSTOM_FILTERS}}</div>"
  
you could see that you could use row.treeNode.children to make the condition.
please refer it and custom as you want.

**Comment by pprabhu59** [comment]
Thank You...will follow this approach and get back to you

**Comment by pprabhu59** [comment]
Thank You,

Was able to selectively display the tree icon based on condition. 
But rowExpanded event is not called on click of icon.
Or do we need to include a method and call raise rowExpanded  event.

**Comment by tringuyenminh92** [comment]
You need to define method to call expand event.
(in my case - my template, you see in the picture that ng-click= grid.appScope.toggleRow(.. )
so that i need to define method:
 $scope.toggleRow = function (row, evt) {
        uiGridTreeBaseService.toggleRowTreeState($scope.gridApi.grid, row, evt);
    };

    $scope.toggleExpandNoChildren = function () {
        $scope.gridOptions.showTreeExpandNoChildren = !$scope.gridOptions.showTreeExpandNoChildren;
        $scope.gridApi.grid.refresh();
    };

you could refer that in the tuts:http://ui-grid.info/docs/#/tutorial/215_treeView

**Comment by pavilion-data** [comment]
I  am tryig to use tree view to add row dynamically using the rowExpanded event but the new data does not show up in the grid, even though the gridOptions.data has it
any idea why it could fail?
