### ISSUE TITLE
ngAnimate disabled

### ISSUE THREAD

**Issue by inviolablegenesis** [angular-ui/ui-grid#4136]
I have downloaded the latest version of the ngAnimate and the ui-grid.
Whenever I call the grid the animation is being disabled. 
Any thoughts on this?

In my bower.json:
> "angular-ui-grid": "~3.0.0-rc.22"
> "angular-animate": "~1.4.4"
> "angular": "1.4.4"

Update 8/10/2015:
Even when I've set `"angular-ui-grid": "~3.0.1"` in my bower.json, animation will still not work.

**Comment by JLLeitschuh** [comment]
Angular 1.4 will not be fully supported until we do a new release. Animations had a breaking change that we had to resolve by coding a version check for.
#3647
#3658

**Comment by inviolablegenesis** [comment]
hello, is this resolved in 3.0.4? 
because i've noticed that this was not included in the fix.

**Comment by JLLeitschuh** [comment]
This should be fixed.  Yes. Closed by #4057
