### ISSUE TITLE
[Vertical Scroll bar hiding content] Different behavior between enableVerticalScrollbar: true and enableVerticalScrollbar: 1

### ISSUE THREAD

**Issue by dereklin** [angular-ui/ui-grid#4140]
Here is my plunker with enableVerticalScrollbar: true:
http://plnkr.co/edit/vyYoUIbxUuDSXsQY9zWs?p=preview

See that the vertical scroll bar is hiding the column content. (You might have to resize the plunker panel to see the hiding)

Now I change it to enableVerticalScrollbar: 1
http://plnkr.co/edit/WYZUxZHFGpa3RCaAyJDy?p=preview

Now it looks good.

For the doc, http://ui-grid.info/docs/#/api/ui.grid.class:GridOptions, I see that these two static values are used: uiGridConstants.scrollbars.ALWAYS, uiGridConstants.scrollbars.NEVER

However, I would expect enableVerticalScrollbar: true and enableVerticalScrollbar: 1 to work the same.

**Comment by mportuga** [comment]
No longer reproducible
