### ISSUE TITLE
not clear how to access the value of a column within a cell template

### ISSUE THREAD

**Issue by davidjnelson** [angular-ui/ui-grid#415]

**Comment by wenboBcoder** [comment]
hi,i'm have a problem about getCellValue(row,col),my code is 
cellTemplate:'<button type="button" class="btn-small ui-grid-cell-contents" ng-click="grid.appScope.del(grid.getCellValue(row,col))">delete</button>'
$scope.del=function(id){
console.log(id)
},
show the undefined,why?thank you in advenced(sorry ,my English is poor)

**Comment by wenboBcoder** [comment]
hi,i have a problem about getCellValue(row,vol), could you help me? the code is:
`cellTemplate:'<button type="button" class="btn-small ui-grid-cell-contents" ng-click="grid.appScope.del(grid.getCellValue(row,col))">delete</button>'`
` $scope.del = function(id) {
            alert(id)
        }`
but the finish is undefined;
thank you in advanced!

**Comment by rajeesh77** [comment]
cellTemplate:'<button type="button" class="btn-small" ng-click="grid.appScope.del(row.entity.ID)">delete</button>'

**Comment by rajeesh77** [comment]
`cellTemplate:'<button type="button" class="btn-small" ng-click="grid.appScope.del(row.entity.ID)">delete</button>'`
