### ISSUE TITLE
Excessive Watches being generated

### ISSUE THREAD

**Issue by swalters** [angular-ui/ui-grid#4153]
We are seeing as many as 3000 watches in UI-grid.  This shouldn't be the case since we only render the visible rows and columns plus a little extra for margin rows.

**Comment by PaulL1** [comment]
I did some work at one point on where watchers should exist: https://docs.google.com/document/d/1kHQrazl1ZA2OTA3HGm254PZo0-YqfcKImIZtq_pXi5o/edit?usp=sharing

For 20 rows/10 columns rendered, this should be around 1000.

**Comment by JLLeitschuh** [comment]
Is this created by a specific feature or is it in core?

**Comment by imbalind** [comment]
Tried with the following tuts (used [this answer](http://stackoverflow.com/a/18526757/2453383) to count).

What I did was:
- open the plunkr
- (load data if needed)
- count watches
- scroll a bit using mouse wheel, keys, dragging the scrollbar
- count watches while in the middle of the table
- scroll back to row1 col1
- count a last time

None of the tuts showed leakage and when I got back to r1-c1 the number of watches was always back to what it was when I opened the plunkr.
Here are the results I recorded.

- 190: 544 to 636
- 201: 1138 to 1342
- 210: 948 to 1028
- 301: 513 to 601
- 305: 250 to 306
- 319: 836 to 989
- 320: 1386 to 1657
- 401: 1465 to 1847

Numbers can grow quite high but I don't see anything that suggests a **leakage** problem. Any thought?

**Comment by JLLeitschuh** [comment]
Watcher counter for page:
https://chrome.google.com/webstore/detail/angular-watchers/nlmjblobloedpmkmmckeehnbfalnjnjk/related?hl=en

**Comment by mportuga** [comment]
@JLLeitschuh Yes
