### ISSUE TITLE
Custom editing template

### ISSUE THREAD

**Issue by gizbo** [angular-ui/ui-grid#4161]
Hi guys,
    I implemented a custom cell template in which I'm handling the editing of the cell with a custom directive. All that is for the ie problem with the html5 date type input... Anyway everything seems working except I'm not getting the call afterCellEdit.  I try broadcasting the uiGridEventEndCellEdit event manually and no luck.  How can I achieve that?
Thanks so much,
Yves

**Comment by danielo515** [comment]
Hello gizbo,

I'm interested on custom editing templates. I did not found any example, would you mind to share yours ? many thanks. 

Regards

**Comment by HipsterZipster** [comment]
+1
