### ISSUE TITLE
Resort after data change does not work

### ISSUE THREAD

**Issue by tjamin** [angular-ui/ui-grid#4176]
If you order the grid by a column and change the values of the array of that column the grid does not reorder.

I have created a plunkr which demonstrates it:
http://plnkr.co/edit/8rXzCYBn9c8TMvD64QlE?p=preview

The initial bound array contains three items with objects which contains a "num" property. The grid is sorted by that property. After 2 seconds the data will be updated but the grid does not resort the rows.

**Comment by crazyjat** [comment]
I am also looking for a solution to this issue.

**Comment by mportuga** [comment]
You have to manually trigger a sort in that case.
