### ISSUE TITLE
Columns not displaying properly 

### ISSUE THREAD

**Issue by NavneetJoshi** [angular-ui/ui-grid#4180]
Hi,

when I am setting minWidth property for the columns they are not displayed properly.Below is the plunker to replicate this issue : 

http://plnkr.co/edit/OraYwr4YyWsDNcFOqRZ7?p=preview

Please look into this

Thanks,
Navneet

**Comment by vvardhanz** [comment]
+1   I did faced same issue when using the minWidth property.
