### ISSUE TITLE
Expandable grid pinned columns are unpinned when scrolling

### ISSUE THREAD

**Issue by NavneetJoshi** [angular-ui/ui-grid#4181]
Hi,

when I pin a column in a sub grid and scroll below so that the sub grid is not visible and then scroll back then it reverts back to its original state.

Below is the plunker to replicate the issue : 

http://plnkr.co/edit/ZjAhmAS3tk3IVymPHEkI?p=preview

Please suggest on how can I preserve the state of subgrid while scrolling

Thanks

**Comment by mportuga** [comment]
That problem appears to be fixed in the latest version. However, the loading issue that people have mentioned prevents this from being useful.
