### ISSUE TITLE
Issue with the footer column sum when using along with the grouping  

### ISSUE THREAD

**Issue by vvardhanz** [angular-ui/ui-grid#4183]
I found footer column summing up all the vales not working appropriately when you using grouping based on rows.
I have a column refunds where i have set  aggregationType = uiGridConstants.aggregationTypes.sum and i have also used grouping  with 
treeAggregationType = uiGridGroupingConstants.aggregation.SUM. Whats happening is footer column total  is also adding up the group header total(Sum) resulting in value which is twice what it supposed to be. EX:  
 ![image](https://cloud.githubusercontent.com/assets/11964847/9256316/db858638-41bc-11e5-8830-f94b7f47b755.png)
   In the above example footer column total should be 100 irrespective of the grouping Sum on column1 and column2. Its just an header, it shouldn't  take the value of the header.

**Comment by coty-crg** [comment]
+1 Can confirm. The way I sort of got around this was by manually adding up the data and setting the footerCellTemplate to the sum - but for some reason this broke header filters from showing.

**Comment by alam123** [comment]
https://github.com/angular-ui/ui-grid/issues/3916

Don't use aggregationType. Just follow the grouping tutorial.

**Comment by coty-crg** [comment]
I've also tried with treeAggregationType, and I get the same results as OP.

**Comment by alam123** [comment]
Take a look at this

http://plnkr.co/edit/Qp9FYdmaZF6WGoP2hR3r?p=preview

**Comment by patriciocordova** [comment]
+1

**Comment by Sampath-Lokuge** [comment]
Please see this @vvardhanz  [Grouping](http://ui-grid.info/docs/#/tutorial/209_grouping)
