### ISSUE TITLE
Error on opening custom cell editor who's first element has no select method.

### ISSUE THREAD

**Issue by lukee910** [angular-ui/ui-grid#4193]
I use a custom editor template to edit a few cells. Everytime I open that cell editor it throws an error at [this line](https://github.com/angular-ui/ui-grid/blob/7d8af94c41baa0c7f81dce9fe7786dab814e9b8c/src/features/edit/js/gridEdit.js#L879) saying `TypeError: $elm[0].select is not a function`. Wich is true, the first element's `select` funtion is undefined.

Now my question: Am I doing something wrong here? And if not, shouldn't this error be handled? (If it's really a bug I'd love to create a pull request to fix it)

_This line:_

```
if ($scope.col.colDef.enableCellEditOnFocus || !(uiGridCtrl && uiGridCtrl.grid.api.cellNav)) {
    console.log($elm[0].select);
    $elm[0].select = function(){}
    $elm[0].select();
}
```

_My custom editor template, a simple-ish dropdown:_

```
<div>
    <form name="inputForm">
        <ol class="nya-bs-select form-control btn-sm inverse" ui-grid-edit-dropdown ng-model="MODEL_COL_FIELD" size="8" ui-grid-editor data-live-search="true" title="---">
            <li nya-bs-option="option in editDropdownOptionsArray" value="option.value" title="{{option.title || option.value}}">
                <a href>{{(option.title || option.value) === '' ? '---' : (option.title || option.value)}}</a>
            </li>
        </ol>
    </form>
</div>
```

**Comment by tomgutz** [comment]
https://github.com/angular-ui/ui-grid/pull/5045
