### ISSUE TITLE
aggregateTemplate in UI grid

### ISSUE THREAD

**Issue by mayurbais** [angular-ui/ui-grid#4195]
I was a fan of ng grid, and now I have upgraded to UI grid .

I want to know if there is anything like aggregateTemplate in UI grid which was there in ng-grid.
So that I can do something like this:

$scope.gridOptions = {
    aggregateTemplate: htmlAggregateTemplate
};

**Comment by JLLeitschuh** [comment]
Have a look at the footer tutorial

**Comment by mayurbais** [comment]
Thats not what I am looking for 
I have this...
![image](https://cloud.githubusercontent.com/assets/9245684/9278717/83deb7aa-4267-11e5-82a5-814a002494a1.png)


and I am looking for this : 

![image](https://cloud.githubusercontent.com/assets/9245684/9278727/9785e468-4267-11e5-88b2-2d4f00a4ddbd.png)

**Comment by PaulL1** [comment]
There's not an aggregate template as such, but in the grouping tutorials (maybe complex grouping?) there's an example of how to use an ng-if to decide what to show in the column based on whether it's a group header or not.

**Comment by tringuyenminh92** [comment]
i'm looking for @mayurbais 's concern too, but in tree view.
Could Ui-Grid' home page add more tutorials about custom row template and cell template.
E.g: merge 2 cell in one row.

**Comment by mayurbais** [comment]
Yes, that will be of great help for every one, and also if we can add it as
feature to this UI-grid. Kendo grid has it.

http://demos.telerik.com/kendo-ui/grid/aggregates

Regards,
Mayur
(c)323-873-2822
