### ISSUE TITLE
Row Entity data at a group level not available anymore

### ISSUE THREAD

**Issue by kaushikyasaswy** [angular-ui/ui-grid#4197]
Previously, I was able to access a row's entity data even at a group level using row.entity.field_name. This functionality dosent seem to exist anymore?

My particular need: For a column's cellClass function, I need to read the value of another field at the group level

**Comment by PaulL1** [comment]
It's not clear to me what value you'd want in that field.  If it's a group header row, and it's not a column that you grouped by, then you'd not expect every field in that group to have the same value.  

If it is a grouped or aggregated column, then you can get at the grouped or aggregated value using the syntax shown in the documentation for custom finalisers.

**Comment by kaushikyasaswy** [comment]
Let me make my example a bit more clear,

Consider the grid has 3 columns City, Population and Stats. City is an aggregation column. So the data has been grouped based on the city. Now I have three group rows corresponding to 3 cities, each having say 5 records. Population has "aggregation : sum". So at the city group level, I have both the city and the population displayed.
The task is to write a cellClass for Stats column using a blackbox that uses the city at the group level and the aggregated population at the group level and outputs a value that I need to display in the Stats column at the same group level again.

What i was using for previous version is somewhat like this:

grid.cloumnDefs.forEach(function(columnDef))
{
columnDef.cellClass = function(grid, row, col, rowRenderIndex, colRenderIndex)
{
if(column === Stats)
{
if row.expandedState !== undefined // Means its a grouping level
{
city = row.entity['city']
population = row.entity['population']
//blackbox
row.entity['stats'] = output value
}
}...

This dosent work anymore cause I cant use row.entity[column_name] at a group level. Also expandedState is not a property of row anymore.

Any help would be appreciated. Thanks!

**Comment by PaulL1** [comment]
Check out some of the doco around grouping:
http://ui-grid.info/docs/#/api/ui.grid.grouping
http://ui-grid.info/docs/#/api/ui.grid.treeBase

I think the properties you'd be looking for are:
  `row.treeNode.expanded` for the expanded state

  `row.entity[col.uid].value` for the value of the aggregation, there are some other things hiding inside `row.entity[col.uid]` that the finaliser puts there - it's basically the aggregation object.

You should also be able to call getCellValue, which knows all about the col.uid thing.

**Comment by kaushikyasaswy** [comment]
Ill try those out and get back with a solution. Thanks!

**Comment by UnitedFreetypeNetworks** [comment]
I think that if it is something that your not suppose to be hitting or work on, then maybe you should just leave it be, put it in Gods hands and what's meant to be shell be. Sometimes you can't always make or change things the way you'd like for them to. The Metrix is a very complex and genius and perfect all in its self. Keep up the good work..

**Comment by UnitedFreetypeNetworks** [comment]
I think that if it is something that your not suppose to be gitting or work on, then maybe you should just leave it be, put it in Gods hands and what's meant to be shell be. Sometimes you can't always make or change things the way you'd like for them to. The Metrix is a very complex and genius and perfect all in its self. Keep up the good work..

**Comment by kaushikyasaswy** [comment]
So I was able to use the col's uid and get the aggregation values. After doing my computations, I wanted to display the result in a COL at a grouprow level using : 
row.entity['$$'+COL_ID] = {value: 'my_result'};

This works fine initially; I can see the value at the group level in the col. When I expand the row, the value vanishes... when i scroll down and come back up, it reappears. 

Im not sure why the value isnt persistent. Any thoughts?

**Comment by PaulL1** [comment]
Did you get a resolution on this @kaushikyasaswy?
