### ISSUE TITLE
Access external-scopes in footerCellTemplate

### ISSUE THREAD

**Issue by zubin259** [angular-ui/ui-grid#4198]
I've got a pagination on in the ui-grid and I need to show column aggregation but there is a restriction in using aggregationTypes with the paginated grid. Hence to show total aggregated value for a given column, I'm using footerCellTemplate with my custom directive.. However, my custom directive doesn't get the access of external-scopes which I can get in case of cellTemplate (like $scope.grid.appScope) property..

How can I get the similar access of external-scopes in footerCellTemplate?

**Comment by avihaym** [comment]
Hi.. 
Here is my code : 
footerCellTemplate: '<div class="ui-grid-cell-contents">Total: {{grid.appScope.totalTime"}}</div>'

Hope its will help you or someone else.
