### ISSUE TITLE
Icons in IE 11 are all Korean characters

### ISSUE THREAD

**Issue by p-borman** [angular-ui/ui-grid#4208]
Using IE 11, navigate to one of your demos (http://ui-grid.info/docs/#/tutorial/104_i18n)
Where you would expect to see carrets, there are Korean characters.
Also in the dropdown, all the icons are also displayed as Korean characters.
The icons display fine in Chrome.

**Comment by lebolo** [comment]
Not sure if it's related, but there's a note about weird font issues at http://ui-grid.info/docs/#/tutorial/499_FAQ (which points to http://ui-grid.info/docs/#/tutorial/116_fonts_and_installation)

**Comment by swalters** [comment]
Your fonts aren't loading correctly.  If it is a current issue, please see your IE debug tools.  I can confirm it works fine in IE on my box.
