### ISSUE TITLE
Pagination footer overlaps last row

### ISSUE THREAD

**Issue by chadreed-intl** [angular-ui/ui-grid#4209]
When using the pagination controls, the pagination footer overlaps the last row of the grid. If there are 10 rows, only 9 will be visible. Please check out an [example].(http://plnkr.co/edit/TK9wU5gvxUU5Ltu0LUJw?p=preview)

I tried setting the height dynamically using an ng-style:
ng-style="{height: (gridOptions.pagingOptions.pageSize \* gridOptions.rowHeight) + 'px'}"
but I can't seem to figure out the pagination footer height correctly, while the header height is 30px;

**Comment by tringuyenminh92** [comment]
you should use the newest version, i got this situation when using version 3.01 
https://github.com/angular-ui/ui-grid.info/tree/gh-pages/release
please get the newest  .js and css files (3.0.4) on 13-08-2015

**Comment by chadreed-intl** [comment]
Got the newest files, and as you can see its still an issue. I even tried adding 'MinRowsToShow' on the gridOptions and it is not resolved.

http://plnkr.co/edit/TK9wU5gvxUU5Ltu0LUJw?p=preview

**Comment by AgDude** [comment]
I observed this on the tutorial page (version 3.1.1), the above plunkers do not show the issue for me. Browser: chrome 48 on windows.

1. Disable cache (not sure if this is important)
2. Load open tutorial page and wait for it to finish loading
3. Click "105 Footer" and wait for it to load.
4. Click "214 Pagination" and wait for it to load.
