### ISSUE TITLE
UI Grid and Angular DragDrop

### ISSUE THREAD

**Issue by inviolablegenesis** [angular-ui/ui-grid#4211]
can i have the rows have drag and drop functionality? 
the rows will be dragged and dropped to an outside element (not another grid, this time it's just a container). 

dragdrop: https://github.com/codef0rmer/angular-dragdrop

by the way, this is not reordering the grid.

**Comment by cjp666** [comment]
Did you work out how to do this?  I am after doing the same
I was using ng-grid and got that working but after upgrading to ui-grid I cannot get it to work

**Comment by inviolablegenesis** [comment]
@cjp666 I added a directive for the cell row. This directive is added in "rowTemplate" and in that row, I added the drag and drop options.

**Comment by cjp666** [comment]
thanks.  I will give it a try

**Comment by cjp666** [comment]
I have tried what you suggested but it appears to only drag within the ui-grid, I can't seem to get it to drag out of the grid and drop where I want it, any ideas will be much appreciated

http://plnkr.co/edit/Gwrw9v?p=preview

**Comment by inviolablegenesis** [comment]
@cjp666 you can add `appendTo: 'html'` in data-jqyoui-options.

**Comment by cjp666** [comment]
Excellent!  Thanks!!

**Comment by manojchoubisa** [comment]
Hi @cjp666, I am trying to drop a row onto another row, but before the drop take place and changes the order, i want to do some check between the two rows. But it has the event "rowDropped" in which the order is already changed. Please suggest me which is the best way to do checks before the order changes and if the check fails then I need to cancel the re-ordering.
Thanks
