### ISSUE TITLE
Minor glitch with scroll when cellNavigating

### ISSUE THREAD

**Issue by therealtomas** [angular-ui/ui-grid#4217]
When using arrows and cellnavigating to the last column to the right, which is virtualized, the scrollbar is not scrolled to the max.

I manage to reproduce this in the plunkr, and in the screenshot below I have navigated to the last column to the right, but the view has not scrolled 100% to the right, and therefore only 50% orso of the last column is visible. To get it showing i have to also scroll with the mouse.

http://plnkr.co/edit/1FkXR9YDwW9VZYGCGKUJ?p=preview

![screen shot 2015-08-18 at 16 09 45](https://cloud.githubusercontent.com/assets/2316118/9332170/a9cdc190-45c3-11e5-85bc-3934e6d20d0b.png)

**Comment by therealtomas** [comment]
Impact is when gridcanvas is larger than the browserwindow the user cannot really scroll to the right using arrowkeys, must use mouse to see the most right cell, works the same in plunker, test with width 900px and shrink browser window

**Comment by mportuga** [comment]
Not reproducible on latest version.
