### ISSUE TITLE
The ui-grid/dropdownEditor is flickering when rowHeight is reduced below 30

### ISSUE THREAD

**Issue by febyfours** [angular-ui/ui-grid#4221]
Currently using version 3.0.4.

The drop down flickers when using 'enableCellEditOnFocus' option in ui-grid. This happens only for the first row and when the rowHeight is set below 30.

Plunker Link : http://plnkr.co/edit/Jt0unCBkzpsAmP70vJyC?p=preview

**Comment by izaa** [comment]
I have this bug too but I haven't had time to look for a solution to this. 

Currently using version 3.0.7
