### ISSUE TITLE
Initialize $scope.gridOptions through config data from server

### ISSUE THREAD

**Issue by gohkhoonhiang** [angular-ui/ui-grid#4224]
Hi,

I have tried implementing the 'single filter' function based on your given tutorial. I am able to implement it without problems if I hardcode the $scope.gridOptions configs. However, when I start using server-side data to pass as gridOptions, I always get Error: $scope.gridApi is undefined on my $scope.filter function.

Here are my codes:

Get the gridOptions config data:
```
$http.get(gridUrl).then(function(response) {
    $scope.gridOptions = response.data;
    $scope.gridOptions.onRegisterApi = function(gridApi) {
        $scope.gridApi = gridApi;
        $scope.gridApi.grid.registerRowsProcessor($scope.singleFilter, 200);
    };
});
```

Single filter function based on tutorial:
```
$scope.singleFilter = function(renderableRows) {
    var value = $scope.filterValue ? $scope.filterValue.toLowerCase() : "";
    var matcher = new RegExp(value);
    renderableRows.forEach(function(row) {
        var match = false;
        $scope.gridOptions.columnDefs.forEach(function(field) {
            var val = row.entity[field.name] ? row.entity[field.name].toLowerCase() : "";
            if (val.match(matcher)) {
                match = true;
            }
        });
        if (!match) {
            row.visible = false;
        }
    });
    return renderableRows;
};
```

Watch for changes in the filterValue and call filter function
```
$scope.$watch('filterValue', function(newVal, oldVal) {
    $scope.filter();
});
$scope.filter = function() {
    $scope.gridApi.grid.refresh();
};
```

Would you advise what have I done wrong that caused the error?

Much appreciated.

**Comment by gohkhoonhiang** [comment]
Hi,

I have found out that I need to initialize `$scope.gridOptions` before making the POST request to get the config data.

This is what I did at the very first line inside my controller:
```
$scope.gridOptions = {
	onRegisterApi: function(gridApi) {
		$scope.gridApi = gridApi;
		$scope.grid = gridApi.grid;
		gridApi.pagination.on.paginationChanged($scope, function(
			newPage, pageSize) {
			paginationOptions.pageNumber = newPage;
			paginationOptions.pageSize = pageSize;
			getData();
		});
		$scope.gridApi.grid.registerRowsProcessor($scope.singleFilter, 200);
	}
};
```

However, in the `onRegisterApi` callback, I need to register `$scope.singleFilter`, which depends on `$scope.gridOptions.columnDefs`:
```
$scope.gridOptions.columnDefs.forEach(function(field) {
    // refer to comment above for full code
}
```
where `$scope.gridOptions.columnDefs` is not yet initialized.

Is there anyway to workaround this so that I can delay registering the `$scope.singleFilter` function?

Thank you.

**Comment by gohkhoonhiang** [comment]
Hi,

I have found out a way to workaround it, which is to provide the actual function to `$scope.gridApi.grid.registerRowsProcessor` as follows:

```
$scope.gridApi.grid.registerRowsProcessor(function(renderableRows) {
	var value = $scope.filterValue ? $scope.filterValue.toLowerCase() : "";
	var matcher = new RegExp(value);
	renderableRows.forEach(function(row) {
		var match = false;
		$scope.gridOptions.columnDefs.forEach(function(field) {
		    var val = row.entity[field.name] ? row.entity[field.name].toLowerCase() : "";
		    if (val.match(matcher)) {
		        match = true;
		    }
		});
		 if (!match) {
		     row.visible = false;
		 }
	});
	return renderableRows;
}, 200);
```

Somehow this works even though at this point I have not retrieved `$scope.gridOptions` from the server.

Thanks.

**Comment by Gikus** [comment]
Hello! I have a similar code and I think it renders matched data into a search field. I'm not savvy in programming and may be you could make some tweaks here.  I need it to show any entered data if such exist in the address list and not only exact match with all the uppercase and lowercase, commas and so on. Now it displays only exact match. The address list and the search bar: [http://wp3.it-do.pw72n.spectrum.myjino.ru/sample-page/] 

My code:

 ```
$http.get('/moduleOplata/data.php')
        .then(function (response) {
            $scope.gridOptions1.data = response.data;
        });

    $scope.filter = function() {
        $scope.gridApi.grid.refresh();
    };

    $scope.singleFilter = function( renderableRows ){
        var matcher = new RegExp($scope.filterValue);
        renderableRows.forEach( function( row ) {
            var match = false;
            [ 'adress'].forEach(function( field ){
                if ( row.entity[field].match(matcher) ){
                    match = true;
                }
            });
            if ( !match ){
                row.visible = false;
            }
        });
        return renderableRows;
    };
```

`<input ng-model='filterValue' class="search_block" placeholder="Введите адрес для поиска" ng-change="filter()"/>`
