### ISSUE TITLE
Enable a default sort direction in columnDefs 

### ISSUE THREAD

**Issue by jonathanboswell** [angular-ui/ui-grid#4242]
Looks like this feature existed in 2.0
https://github.com/angular-ui/ui-grid/pull/1864

I've gone through the javascript and maybe I'm missing it, but I can't find anyway of doing this.

Use case:
Financials almost always make sense to have the first click be DESC, we do a lot of sorting on various currency fields and currently have to click twice to get it to DESC

Thank you for all the great work!

**Comment by PaulL1** [comment]
http://ui-grid.info/docs/#/tutorial/102_sorting or http://ui-grid.info/docs/#/api/ui.grid.class:GridOptions.columnDef

You set the direction on the columnDef, in the sorting object.

**Comment by jonathanboswell** [comment]
Correct me if I'm wrong, but that sets the sort on the load, not the first click on a column header.

For example, let's say we have a grid with two columns "Clients" and "Revenue" on page load we want it to load clients alphabetically ascending. Like so:

$scope.gridOptions = {
  enableSorting: true,
  data: clientFactory.revenues
  columnDefs: [
            { field: 'clients', sort: { direction: 'asc', priority: 0 } },
            { field: 'revenue', cellFilter: 'currency' }
  ]
};

All well and good. The issue is that whenever we want to sort on "Revenue" by clicking on the header it will sort 'asc' with all the zero revenue clients first when really what we wanna see is all the highest revenue clients first. Sure we can click on the header again, but in a financial grid with 7 currency fields constantly having to double click the columns is not ideal. And if we add the sort object to the revenue field:
  columnDefs: [
            { field: 'clients', sort: { direction: 'asc', priority: 0 } },
            { field: 'revenue', cellFilter: 'currency', sort: { direction: 'desc' } }
  ]

...the page loads with all the clients sorted alphabetically and then revenue sorted with any clients that have the same name, which is not the solution.

This functionality appears to be in 2.x: https://github.com/angular-ui/ui-grid/pull/1864

And seems to be missing from 3.x

Again, hopefully I'm wrong about this, but I've thoroughly gone through the documentation and code and it seems to not exist anymore.

**Comment by PaulL1** [comment]
Ah, OK, I see.  This you can do by listening to the sort changed event, and altering the sort manually.  A bit clunky, but it will work.

**Comment by benheymink** [comment]
@jonathanboswell We had the same issue, and came to the same conclusion as PaulL1. We add a 'reverseSorted: true' to our columnDefs for particular rows, then listen for on.sortChanged events and adjust a query string parameter accordingly.

**Comment by jonathanboswell** [comment]
@PaulL1 @benheymink Thanks guys for the feedback. We'll try that out!

**Comment by jonathanboswell** [comment]
So a really easy way to achieve this is:
```
var reverseSort = function(a,b){
  if (a == b) return 0;
  if (a < b) return 1;
  return -1;
};

$scope.gridOptions.columnDefs = [
  { field: 'clients', sort: { direction: 'asc', priority: 0 } },
  { field: 'revenue', cellFilter: 'currency', sortAlgorithm: reverseSort }
]
```
Maybe a new feature request?

**Comment by jonathanboswell** [comment]
@gmaslov You're awesome! Code looks great. Looking forward to having this functionality built in now!

**Comment by Kusk01** [comment]
In ui grid 3.1.1

I am able to get the sort direction using sort : {direction: uiGridConstants.ASC},but when I click on one of the column to sort it, other column sort direction is now no longer visible.

So is there a way when I click on column header to sort it, other column sort direction should be visible all the time and it should not change till I clicked on the column to sort it.

Thanks
Kusum
