### ISSUE TITLE
pagination chinese translate [MISSING]

### ISSUE THREAD

**Issue by hxlniada** [angular-ui/ui-grid#4246]
![image](https://cloud.githubusercontent.com/assets/3838586/9427727/06565a22-49bf-11e5-89ff-b2f01183b8dc.png)
How can I handle it  manualy

**Comment by hxlniada** [comment]
http://plnkr.co/edit/n2peFyXPzoNAD19liwiT?p=preview

**Comment by hxlniada** [comment]
It should be "共"

**Comment by JLLeitschuh** [comment]
Feel free to open a PR to fix this.
