### ISSUE TITLE
Cannot hide a specific column's header

### ISSUE THREAD

**Issue by xforceco** [angular-ui/ui-grid#4247]
There is no option to hide specific column's header, 
or display an empty name

**Comment by ingshtrom** [comment]
You can set the columnDef property `headerCellTemplate`. See this plnkr: http://plnkr.co/edit/vMwpCb7t1leJHA2xbeMF?p=preview. The Company column is still showing data in the grid, but no header.

**Comment by tringuyenminh92** [comment]
or could set displayName: ' ' < one or two or .. spaces
