### ISSUE TITLE
Error is thrown when focusing a cell

### ISSUE THREAD

**Issue by mathiasdose** [angular-ui/ui-grid#4258]
We have identified that the error below is thrown when using dot notation in col.field e.g "1.Blabla". This occurs once you focus the cell.
![screen shot 2015-08-25 at 09 39 44](https://cloud.githubusercontent.com/assets/2345409/9461229/4aae6850-4b0d-11e5-95d0-c8d7345130ce.jpg)

The function below is what causing this error and was added in 9532de2bdb083a0bb40a6099924e98893ab354e7
```javascript 
RowCol.prototype.getIntersectionValueRaw = function(){
        var getter = $parse(this.col.field);
        var context = this.row.entity;
       return getter(context);
      };
```
9532de2bdb083a0bb40a6099924e98893ab354e7

**Comment by JLLeitschuh** [comment]
Do you have a plunker that I can use for testing? I'll see if I can fix this today.

**Comment by mathiasdose** [comment]
http://plnkr.co/edit/9ybwvU46hI88uJtqEeWG?p=preview

Just focus any of the cells and you will see the error in the console.

**Comment by UnitedFreetypeNetworks** [comment]
Please stop anulysing me for two hours and let me cope with me. I mean cone on, I do have feelings, and i am human and,nit test subject

Sent from my Windows Phone
________________________________
