### ISSUE TITLE
How to programmatically deselect the 'select all' checkbox?

### ISSUE THREAD

**Issue by mxreppy** [angular-ui/ui-grid#426]
Hi-

Another question, how do we clear the 'select all' checkbox?  I've got a button off-grid that process the selected rows and can clear the selection a variety of ways (setting the selected item array to zero length or calling 

```
$scope.gridOptions.$gridScope.toggleSelectAll(false);
```

but I can't seem to clear the 'select all' box.  I've tried

```
$scope.gridOptions.$gridScope.allSelected = false;
// or
$scope.gridOptions.allSelected = false;
```

but neither seem to affect the checkbox.  

thanks!

**Comment by endorphins** [comment]
I've found that both dimitrivalex and Hals9000 don't really work for me. They both uncheck the header's checkbox, but they also make it so that if you select the header's checkbox again it doesn't select all rows in the grid like it should (you would have to deselect it again before it worked). I've gotten Hals9000's workaround to fully work if i have the click event trigger 3 times, but it seems like that shouldn't be necessary.

Has anyone found a good solution to this?

**Comment by dezz727** [comment]
Hi there,

I've just found a solution.
Just replace *allSelected* with *$parent.allSelected* (or any name you want) in your custom checkbox header template:
`checkboxHeaderTemplate: '<input class="ngSelectionHeader" type="checkbox" ng-model="$parent.allSelected" ng-change="toggleSelectAll($parent.allSelected)"/>'`

Then use:
`$scope.gridOptions.$gridScope['allSelected'] = false;`

**Comment by kmittal** [comment]
@dezz727 : Any idea on how it can be done,if I don't use a checkboxHeaderTemplate?

**Comment by ulandgrant** [comment]
This is the solution I use to deselect selection's check all:
```
$scope.gridApi.grid.selection.selectAll = false;
```
This also assumes that you used onRegisterApi to register the api when you created the grid
```
$scope.gridOptions.onRegisterApi = function (gridApi) {
    $scope.gridApi = gridApi;
}
```
Note that this method will only unselect the select all checkbox. If you want to deselect everything else, you'll have to use the api to deselect those as well:
```
$scope.gridApi.grid.selection.clearSelectedRows()
```

**Comment by imadulhaque** [comment]
Would really appreciate if anyone can send controller code. Don't really know where to put toggleSelectALL function. I have tried different things but none is working. Apologies for my noviceness.
Many thanks.

**Comment by SyedZeenath** [comment]
dimitrivalax workaround solved my issue.

the other solutions, produced error of undefined.
workaround: 
`$("input.ngSelectionHeader:checkbox").prop('checked', false);`
