### ISSUE TITLE
Assigning PapaParsed JSON Objects to UI-Grid Data

### ISSUE THREAD

**Issue by Kaleb8812** [angular-ui/ui-grid#4264]
Hello, I am just simply trying to use papaparse to parse a local CSV file into JSON objects and then set those JSON objects to fill the UI-Grid. However, the papaparse functions are async and I am having a horrible time trying to get the UI-Grid to update with the new data. Any advice would be much appreciated. The code I am currently using is below:

```Javascript
$scope.addData = function(elements) { //This is a button that loads the csv file and kicks off the parsing.
        Papa.parse(elements.files[0], {
            config: config,
            complete: function (results) {
                console.log("Finished:", results.data);
                $scope.gridOpts.data = results.data; //Sets the parsed JSON objects equal to UI-Grid data.
            }
        });
    };
```

**Comment by PaulL1** [comment]
There's no particular reason that shouldn't work, assuming that the console log is writing out the results that you expect, and they're an array of objects in the format your grid expects.

You could try the old standard of:
```
  $scope.data = [];
  $scope.gridOpts.data = 'data';
  ..... grid initialisation stuff...
  ......papaparse stuff....
    $scope.data = results.data;
```

Sometimes people have problems with how they've declared their data and end up with pointer issues.  But that's the only thing that looks like it could be a problem.

Failing that, you could build a plunker that basically does the same thing, without papaparse.  So it just has a $timeout and sets $scope.gridOpts.data to some values after a period of time, to see whether that is working.

**Comment by Kaleb8812** [comment]
To address you first suggestion, that was my first attempt. Except when I set $scope.data = results.data it returns undefined because results.data is not defined outside of the papaparse asynchronous function. I have been trying to implement a call back for the function, or add promises but I have not been successful.

For your second suggestion, I think I actually found your $timeout code on another issue and tried this out:
```Javascript

        $scope.waiting = "Waiting...";
        $timeout(function () {
            $scope.gridOpts.data = [{name: 'Bob'}];
        }, 3000)
            .then(function () {
                $timeout(function () {
                    $scope.gridOpts.data = [{name: 'John'}];
                }, 3000);
                $scope.waiting = "Waiting again...";
            });
```
That worked just fine so I figured I could just insert it into the papaparse function to test to see once I loaded the file if the ui grid would act like it did above but it did not, my ui grid was just blank: 
```JavaScript
$scope.addData = function(elements) { //This is a button that loads the csv file and kicks off the parsing.
        Papa.parse(elements.files[0], {
            config: config,
            complete: function (results) {
                console.log("Finished:", results.data);
                $scope.gridOpts.data = results.data; //Sets the parsed JSON objects equal to UI-Grid data.
                $scope.waiting = "Waiting...";
                $timeout(function () {
                    $scope.gridOpts.data = [{name: 'Bob'}];
                }, 3000)
                    .then(function () {
                        $timeout(function () {
                            $scope.gridOpts.data = [{name: 'John'}];
                        }, 3000);
                        $scope.waiting = "Waiting again...";
                    });
            }
        });
    };
```

Thanks for the timely response btw.

**Comment by PaulL1** [comment]
OK, that gives a hint.  Perhaps the $scope that's inside the papaparse complete function isn't the $scope you're expecting?  Could you check that it's actually the right $scope.gridOpts that's getting updated?  Perhaps papaparse has somehow created a new scope?  (Although then you should get an error that $scope.gridOpts doesn't exist).

**Comment by Kaleb8812** [comment]
The scope is the same inside or outside of the papaparse function and I can add the results data to the $scope.gridOpts, so it exists and it's being updated... Is there something I am missing with update the ui-grid with this data or is it supposed to do that automatically? Or maybe is there a way to keep the ui-grid from even loading until the papaparse function has been kicked off so $scope.gridOpts.data doesn't have to update; It's just assigned in the papaparse function right off the bat.

**Comment by PaulL1** [comment]
It has a watch on it, there's no reason it'd be different whether it's updated from papaparse vs just updating in code.  So it's either a scope issue (so not the same object), or the format that you're assigning in isn't exactly what you think it is - maybe it has a parent object, maybe it's an object not an array, or something like that.

**Comment by Kaleb8812** [comment]
Digging in and trying some other things out I noticed if I simply assign a string element of the 2D array to the a "Test Header" in the ui-grid while still in the papaparse function, it appears the data variable that ui-grid uses becomes undefined. Would the .data that the papaparse library refers to be interfering with the ui-grid .data? Here's the code and a screen shot of the error from the console:
```Javascript
$scope.addData = function(elements) { //This is a button that loads the csv file and kicks off the parsing.
        Papa.parse(elements.files[0], {
            config: config,
            complete: function (results) {
                console.log("Finished:", results.data);

                //Sets grid opts = the parsed array
                $scope.gridOpts = results;

                //test to see if uigrid updates with the sring value in [0][0]
                var test = $scope.gridOpts.data[0][0];
                var myData = [
                    {
                        "Test Header": test
                    }
                ];

                $scope.gridOpts = {
                    enableSorting: true,
                    data: myData
                };
                console.log(test);

            }
        });
    };
```
![image](https://cloud.githubusercontent.com/assets/10465965/9501220/92ec89ac-4bef-11e5-9341-0aacf6baae87.png)
And one last note, as you can see the parsed data is a regular array not an object.

**Comment by PaulL1** [comment]
You've overwritten teh full gridOpts?  That would break lots of things I would expect.  Including the watchers on $scope.gridOpts.data.

**Comment by Kaleb8812** [comment]
My apologies I didn't mean to overwrite the gridOpts. So I re wrote the code with very simple syntax, and the table is still blank: 
```Javascript
 $scope.addData = function(elements) { //This is a button that loads the csv file and kicks off the parsing.
        Papa.parse(elements.files[0], {
            config: config,
            complete: function (results) {
                console.log("Finished:", results.data);

                //Sets grid opts = the parsed array


                //test to see if uigrid updates with the sring value in [0][0]
                var test = results.data[0][0];
                $scope.myData = [
                    {
                        "Test Header": test
                    }
                ];

                console.log("csv", test);
                console.log("myData", $scope.myData);
            }
        });
    };
```
and the HTML for reference:
```HTML
<div ng-controller="PhoneListCtrl">
        <div id="grid1" ui-grid="{ data: myData }" class="grid center-block"></div>
    </div>
```

**Comment by PaulL1** [comment]
Can you also provide the original gridOpts.  I just want to see whether you've set `$scope.gridOpts.data = 'myData';`

**Comment by Kaleb8812** [comment]
I do not have $scope.gridOpts.data = 'myData'; in my js file, because I was under the impression that the HTML handled that when I write:  ui-grid="{ data: myData }"

**Comment by PaulL1** [comment]
Ah.  That's probably where the issue is.  

In theory it might, but in practice I think that means you can't assign to $scope.gridOpts.data, because $scope.gridOpts may not exist.

I'd do the more standard grid options way, as all the tutorials do, and you'll probably find that things work.

**Comment by Kaleb8812** [comment]
I agree with your logic, and paying closer attention to the tutorials, I presume you meant this (the grid is still blank too):
```Javascript
//Added in the defined gridOptions
    $scope.gridOptions = {};
    $scope.gridOptions.data = 'myData';
    
    $scope.addData = function(elements) { //This is a button that loads the csv file and kicks off the parsing.
        Papa.parse(elements.files[0], {
            config: config,
            complete: function (results) {
                console.log("Finished:", results.data);

                //Sets grid opts = the parsed array


                //test to see if uigrid updates with the sring value in [0][0]
                var test = results.data[0][0];
                $scope.myData = [
                    {
                        "Test Header": test
                    }
                ];

                console.log("csv", test);
                console.log("myData", $scope.myData);
            }
        });
    };
```
HTML for reference
```HTML
<div ng-controller="PhoneListCtrl">
        <div id="grid1" ui-grid="gridOptions" class="grid center-block"></div>
</div>
```

**Comment by PaulL1** [comment]
Yes, in theory that's more likely to work.

**Comment by c0bra** [comment]
@Kaleb8812 I was able to get it working in this plunker: http://plnkr.co/edit/ud7vG6SxYbKGQFFCanBr?p=preview

Hopefully that helps!

**Comment by Kaleb8812** [comment]
Thank you so much I thought it might not be too hard. Your the best Brian!

**Comment by suriyaJaay** [comment]
@c0bra . can you pls update this  same [http://plnkr.co/edit/ud7vG6SxYbKGQFFCanBr?p=preview](url)
with local file upload option. it would save my day..

thank you
