### ISSUE TITLE
Vertical scrollable grid alignment issue when pin left of columns.

### ISSUE THREAD

**Issue by joseabraham99** [angular-ui/ui-grid#4267]
I am facing an issue with angular ui grid. Suppose there is a vertical scrollbar in the grid and I am doing a pin left of a column this issue exist. Thanks in advance for the fix.

![screen](https://cloud.githubusercontent.com/assets/848620/9486379/f445b0ae-4be3-11e5-910d-90049c1ed7e2.jpg)

**Comment by c0bra** [comment]
Can you give us details on what version you're using, what features you have enabled, etc?
