### ISSUE TITLE
Please add Tag for Release v3.0.5

### ISSUE THREAD

**Issue by kolesnik** [angular-ui/ui-grid#4269]

**Comment by ingshtrom** [comment]
Although the release and version bump was done, @JLLeitschuh ran into errors in Travis when publishing to NPM/Bower. I'm guessing that is why the tag hasn't been done yet. See the gitter channel and https://travis-ci.org/angular-ui/ui-grid#L704

**Comment by JLLeitschuh** [comment]
This should be taken care of. Let me know if this isn't resolved.
