### ISSUE TITLE
rowSelectionChanged event is not fired for selectAll checkbox

### ISSUE THREAD

**Issue by shash8787** [angular-ui/ui-grid#4272]
When you click the selectAll checkbox in the header to select/deselect all rows, is there any event which is fired? In ng-grid, afterSelectionChange was fired in both cases.

**Comment by dheerajvats** [comment]
Hi @shash8787 
I am facing the same problem.Did you find any solution to this?

**Comment by cteyton** [comment]
The event "rowSelectionChangedBatch" is fired when you select all rows. 
```javascript
$scope.grid1Api.selection.on.rowSelectionChangedBatch($scope, function(row) {
               $scope.grid1Api.selection.getSelectedRows().forEach(function(row) {
                           //Do something
                        });
                    });
```
I'm not sure it's fired when you deselect all, you need to check this :)

**Comment by dheerajvats** [comment]
Thanks @cteyton working fine for me ..
and it is being fired on deselect all

**Comment by PaulL1** [comment]
you can also set an option to ask it to call individually instead of in batch, if you're just going to do something in a loop anyway.
