### ISSUE TITLE
ngGridEventColumns for ui grid?

### ISSUE THREAD

**Issue by shash8787** [angular-ui/ui-grid#4274]
Is there an event which is fired always whenever I interact with ui-grid like when I group, sort, or filter? I'm using this event to persist the state of the grid and reload it when the user refreshes the page or comes back. Any help would be greatly appreciated.

Thanks

**Comment by hboylan** [comment]
Here you are good sir: https://github.com/angular-ui/ui-grid/wiki/Grid-Events

**Comment by shash8787** [comment]
Thanks but these events are for ng-grid and I don't see being fired or mentioned any where in ui-grid code.

**Comment by hboylan** [comment]
You are correct! My bad, these are what I'm using for sorting, pagination, and selection.

```javascript
grid.gridApi.core.on.sortChanged($scope, function(g, sortColumns){})
grid.gridApi.pagination.on.paginationChanged($scope, function(currentPage, pageSize){})
grid.gridApi.selection.on.rowSelectionChangedBatch($scope, function(rows){})
```

**Comment by adineag** [comment]
Is there any event which triggers when the columns are rearranged (not sorted) ?

**Comment by mportuga** [comment]
Closing as this is not a bug.
