### ISSUE TITLE
Angular 1.3.x no longer supported

### ISSUE THREAD

**Issue by jgilchrist** [angular-ui/ui-grid#4279]
Commit 5773d3a43 seems to have made it impossible for bower to resolve this project as supporting any 1.3.x versions.

**Comment by mikemccaughan** [comment]
This is literally a one-liner: change line 322 lib/grunt/plugins.js to:

`'angular': '>=1.2.16 <=1.4.x'`

if your intent is to allow angular 1.2.16 - 1.4.x, and not >=1.5.x.

**Comment by mportuga** [comment]
angular 1.3 is no longer supported by ui-grid. We are now only supporting 1.4.0 and up
