### ISSUE TITLE
include the footer in the grid when export data into pdf

### ISSUE THREAD

**Issue by glixingxian** [angular-ui/ui-grid#4284]
Is there a  way to include the footer in the Grid , for example, the _total and the average footer_?

I don't know how to include footers in the tutorial like [this](http://ui-grid.info/docs/#/tutorial/105_footer) into the exported pdf.

**Comment by PaulL1** [comment]
You'd need to custom code that - there isn't currently a way to export footers automatically.  But exporter gives you a lot of access to the docDefinition object, so you can put anything you like in there before passing to pdfMake.

**Comment by glixingxian** [comment]
Thank you! That's a good idea to use the docDefinition object! Maybe I will add some features and do a pull request.

**Comment by najarhasan** [comment]
can you please show me any example for the same

**Comment by hverlin** [comment]
How did you manage to do that ?
I tried with ``gridApi.col[].getAggregationValue()``, but this does not work as we do not have access to the gridApi when we define gridOptions.

Thank you in advance !
