### ISSUE TITLE
How to bind dropdownEditor to Column Value

### ISSUE THREAD

**Issue by zBestData** [angular-ui/ui-grid#4287]
I have a grid loaded from an ajax call, with one column using the dropdownEditor.  How do I get it to bind to the numerical value in the column and display the appropriate Description?

Thanks!

```
        $scope.gridOptions.columnDefs = [
            {
                name: 'ServiceID',
                displayName: 'Service',
                enableFocusedCellEdit: true,
                width: 100,
                type: 'number',
                editDropdownIdLabel: 'ServiceID',
                editDropdownValueLabel: 'Description',
                editDropdownOptionsArray: $scope.optionsList,
                editableCellTemplate: 'ui-grid/dropdownEditor'
            },
```

**Comment by webiks** [comment]
You can take a look at how I did it for the filter select: #4108 
Look at this part: https://github.com/webiks/ui-grid/blob/columnsFilters/src/features/uiColumnFilter/js/column-filter.js#L391

**Comment by zBestData** [comment]
@webiks ,  Yes, that is correct.  Looking at using the grid for adding/editing items on a billing Invoice.

The Lookup is for selecting a "Service" that should return a number value to the database.  When the grid is loaded, the dropdowneditor isn't binding to the value in the column.  Unedited cells should show the description, and editing the cell inserts an empty value.  I am thinking this should be something simple to do and I am just missing it somewhere.

![image](https://cloud.githubusercontent.com/assets/14015883/9562923/b5b3e12e-4e47-11e5-99b8-b971037d49f9.png)

**Comment by zBestData** [comment]
Also,  I am working for the online tutorials including the one at http://ui-grid.info/docs/#/tutorial/201_editable.  Not sure what I am missing.

**Comment by zBestData** [comment]
Update: 

Grid is now showing correct Description, but the dropdown is not mapping to the value received to the database and inserts a blank value at the top when cell is edited.  How do you set the selected index on the dropdown so it shows the current value when the user edits the cell?

 .filter('mapService', function () {
            return function (input) {
                if (!input) {
                    return '';
                } else {
                    return _servicesHash[input];  //servicesHash is an array created from database to match dropdown values
                }
            };

![image](https://cloud.githubusercontent.com/assets/14015883/9582470/88fcea44-4fd3-11e5-9985-82ec72c60524.png)
