### ISSUE TITLE
using i18n in ES with pagination.

### ISSUE THREAD

**Issue by facuxt** [angular-ui/ui-grid#4295]
Hello everyone.. im using ui.grid with i18n, im currently using 3.0.5 (recently updated). Im using language in 'es'  this is the html code

``` html
<div ui-i18n="{{lang}}">
      <div ui-grid="gridOptionsSimple" ui-grid-pagination></div>
 </div>
```

in the controller i set...

``` js
$scope.lang = 'es';
```

then... in ui-grid.js i added this code in line 21210

``` js
console.log(i18nService.getCurrentLang());
```

then in console i see...

``` js
"en"
```

what is happening here?

I was inspecting the code and all seems to be ok... the translations are in the file as follows...

``` js
...
        pagination: {
          sizes: 'registros por página',
          totalItems: 'registros',
          of: 'de'
        },
...
```

then the template is set like this

``` html
    <div class="ui-grid-pager-count-container">
        <div class="ui-grid-pager-count"><span ng-show="grid.options.totalItems > 0">{{showingLow}} <abbr ui-grid-one-bind-title="paginationThrough">-</abbr> {{showingHigh}} {{paginationOf}} {{grid.options.totalItems}} {{totalItemsLabel}}</span>
        </div>
    </div>
```

Those vars (paginationOf, totalItemsLabel, etc.. are being setted like this), you will see where i placed the console.log...

``` js
...
          $scope.paginationApi = uiGridCtrl.grid.api.pagination;
          $scope.sizesLabel = i18nService.getSafeText('pagination.sizes');
          $scope.totalItemsLabel = i18nService.getSafeText('pagination.totalItems');
          console.log(i18nService.getCurrentLang());
          $scope.paginationOf = i18nService.getSafeText('pagination.of');
          $scope.paginationThrough = i18nService.getSafeText('pagination.through');
...
```

p.s: i attack a screenshot to prove that the i18n is working at least partially.
![uigrid](https://cloud.githubusercontent.com/assets/7550822/9586826/6e657dbe-4ff5-11e5-953b-60b5270a438d.png)

p.s2: I can avoid this issue just putting this in my controller
i18nService.setCurrentLang('es');

but i dont know if that is the expected behavior... Feel free to ignore this issue if that's the case

**Comment by pavlalexandr** [comment]
I faced a such behavior too, also after minification all translated text has gone and I can watch only [MISSING] text instead of orinal
