### ISSUE TITLE
editableCellTemplate Edit Cell Value doesn't work

### ISSUE THREAD

**Issue by rjain-pivotal** [angular-ui/ui-grid#4296]
I am trying to create a editable cell as per the templating rules https://github.com/angular-ui/ui-grid/wiki/Templating

```
enableCellEditOnFocus: true, //enables the editor on a single click, if you use enableCellEdit: true you would have to doubleclick
```

And in the columndefs 
        { field: 'Tasks', enableCellEdit: true, cellTooltip: true, headerTooltip: true, width: '50%' , enableFiltering: false,
              editableCellTemplate: '<textarea style="width:100%" ng-class="\'colt\' + col.index" ng-input="COL_FIELD" ng-model="COL_FIELD"></textarea>'},

This doesn't work. 

Here is the Plunkr of my complete code (based on the Tutorial example) 
http://plnkr.co/edit/Fpqsdthu4FhyUoD5gGcL?p=preview

I have tried with Age (Number) and Name (Text Area)

Thanks, 
Rajesh

**Comment by HariAddepalli** [comment]
use ng-model="MODEL_COL_FIELD" instead of ng-model="COL_FIELD". This is a change happened between ng-grid and ui-grid.
