### ISSUE TITLE
cell navigation can the enter key be configurable somehow? (and not a navigation key)

### ISSUE THREAD

**Issue by jcompagner** [angular-ui/ui-grid#4304]
Hi,

this code:

https://github.com/angular-ui/ui-grid/blob/master/src/features/cellnav/js/cellnav.js#L463

There the enter key is used to go up or down (depending on shift) but thats not really what we like to have, because for us the enter key is the action (do your think on the current row/selection)

we already have TAB and ARROW keys just fine for us enter should be used as a action (just like mouse click)

**Comment by swalters** [comment]
I think you can use angular decorators to change the getDirection function to your own
