### ISSUE TITLE
Resizing not working when column width is set with a percentage

### ISSUE THREAD

**Issue by franciscopuyo** [angular-ui/ui-grid#4306]
Hi, I set a percentage as a column width but now it doesn't resize.

This one of my column definition.
{
     displayName: 'id',
     width: "20%",
     resizable: true,
     cellRenderer: function(params) {
        return params.data.id();
     }
}

**Comment by franciscopuyo** [comment]
In fact, percentage width only applies to the header. Items rows are set with width: 20%px;  In this case.

I think its a bug, its adding "px" prefix even if I set width as a percentage

**Comment by mportuga** [comment]
not reproducible:
http://plnkr.co/edit/v32HnqVEYEOEHmQlbQ6H?p=preview
