### ISSUE TITLE
Hide header in CSV export.

### ISSUE THREAD

**Issue by Andrew1431** [angular-ui/ui-grid#4307]
Hey there, developing a report that needs to be printed without headers, and it seems there is no work around for this in your project.

Even with 
    showHeader: false
the headers still show up once the file is CSV'd. Is there any way to work around this?

Thanks,
-Andrew

**Comment by PaulL1** [comment]
This should be a reasonably simple addition to the exporter code base - suggest a PR for it.

**Comment by Andrew1431** [comment]
I got it using an empty header config and Getdata(), then just sliced the
first carriage return out of the produced string. Thanks though

**Comment by PaulL1** [comment]
Looks like this has a resolution - closing.
