### ISSUE TITLE
Ui Grid Sorting

### ISSUE THREAD

**Issue by walid-jabri** [angular-ui/ui-grid#4311]
how can keep nulls at bottom of list when sorting

**Comment by JLLeitschuh** [comment]
No good way. Look through the source. Perhaps you can override a method in the API.

**Comment by zhenyi2697** [comment]
You can provide your custom sorting algorithms by using the option `sortingAlgorithm`
Here is a example:
    
    sortingAlgorithm: function(a, b) {
                    if (undefined === a && undefined === b) return 0;
                    else if (undefined === a) return -1;
                    else if (undefined === b) return 1;
                    else {
                        if (a < b) return -1;
                        else if (a > b) return 1;
                        else return 0;
                    }
                }

**Comment by walid-jabri** [comment]
@zhenyi2697 , thanks for your answer +1
