### ISSUE TITLE
Setting moveGroupColumn true causes crash of grid

### ISSUE THREAD

**Issue by mosheshp2** [angular-ui/ui-grid#4315]
I know that grouping is still beta, but I found small issue with simple fix,
on any usage of ui-grid, if you add to the options "moveGroupColumn = false", which needed for disabling the moving the grouped columns to the left, the grid crashes,
Solution for this, is in the beggining of the moveGroupColumns function, the return statement should return the columns variable, like this:
moveGroupColumns = function (grid, columns, rows){
       if ( grid.options.moveGroupColumns === false){
              return columns;
       }
//etc...
there is also immidiate solution for this by using angular decoratorlike this:

angular.module('common.grid').config([ '$provide', function( $provide ){
        'use strict';
        $provide.decorator( 'uiGridGroupingService', [ '$delegate', function( $delegate )
        {
            /**
             * this is fix for ui-grid bug, moveGroupColumns doesn't return columns when user disabled re-sorting in grouping
             * @type {Function|*}
             */
            var moveGroupColumnsFn = $delegate.moveGroupColumns;
            $delegate.moveGroupColumns = function (grid, columns, rows){
                if ( grid.options.moveGroupColumns === false){
                    return columns;
                }
                return moveGroupColumnsFn.apply(null, [grid, columns, rows]);
            };

            return $delegate;
        }]);
}]);

**Comment by PaulL1** [comment]
If this does indeed fix it, then I'd suggest a PR, which we'd welcome.

**Comment by mosheshp2** [comment]
I fixed it, 
I am trying now to run the grunt, and make the pull request...
