### ISSUE TITLE
Support custom template in select filter labels

### ISSUE THREAD

**Issue by pavithrancr** [angular-ui/ui-grid#4316]
I am using a select filter in the ui-grid header and would like the drop down list to have images to select from. That is, the select labels need to support custome templates.

 filter: {
            type: uiGridConstants.filter.SELECT,
            selectOptions: [ { value: 'amber', label: "<div>&nbsp;&nbsp;<img  src='modules/buysell/amber.png' /></div>" }, { value: 'amber-red', label: 'amber-red' }, { value: 'red', label: 'red'}]
            }

Is there a possibility to do this today? Or any workaround?                                           }

**Comment by mportuga** [comment]
You would need to create a custom filter directive for that.
