### ISSUE TITLE
When Installing with nuget, fonts are placed in a location the CSS cannot find

### ISSUE THREAD

**Issue by killyosaur** [angular-ui/ui-grid#4321]
When I install this via nuget, the fonts are placed in a Font folder that is not referenced in the css files at all resulting in a bunch of what appears to be Kanji.

**Comment by bryanbak** [comment]
I'm seeing the same thing. It seems like all the urls in the to the font files in the ui-grid css files should be prefixed with ../fonts. So something like url('ui-grid.woff') would be changed to url('../fonts/ui-grid.woff'). That's how it's done in the bootstrap 3 nuget package for all the glyphicons font files that are installed in the fonts directory.

**Comment by MatejQ** [comment]
This is no longer an issue, it should be closed.
