### ISSUE TITLE
ui-grid is not browserify compatible

### ISSUE THREAD

**Issue by sandeepseshadri** [angular-ui/ui-grid#4324]
```
browserify resources/assets/js/bank.js --debug
path.js:439
      throw new TypeError('Arguments to path.resolve must be strings');
      ^
TypeError: Arguments to path.resolve must be strings
    at Object.posix.resolve (path.js:439:13)
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:151:37
    at fs.js:334:14
    at FSReqWrap.oncomplete (fs.js:95:15)
```

my bank.js has just these 2 lines 

```
angular=require('angular');
require('angular-ui-grid');
```

Node
v0.12.7
npm 
2.11.3
browerify 
11.0.1

**Comment by nsantini** [comment]
on package.json the "main" property needs to be a string that points to the JS file to use. Currently has a list of paths.

**Comment by sbruno** [comment]
I also had this problem but doing a npm publish of an app using ui-grid.
package.json file is being overwritten with bower.json contents.
Iopened a bug: https://github.com/angular-ui/ui-grid/issues/4743

**Comment by gorankami** [comment]
I am using it with browserify in this way:

`require('angular-ui-grid/ui-grid');`

afterwards, I am adding 'ui.grid' to my module dependency.

**Comment by nicocube** [comment]
Same than @gorankami `require('angular-ui-grid/ui-grid')` worked for me with browserify-middleware.

After that I added `@import url("node_modules/angular-ui-grid/ui-grid.min.css");` into my css file parsed by browserify-css (I plugged it into my middleware), and everythings is working fine now.

In node.js :

    var router = express.Router()

    app.use(router)

    browserify.settings({
        insertGlobals: true,
        transform: [['browserify-css', {
            autoInject: true,
            rootDir: 'node_modules',
            processRelativeUrl: function(relativeUrl) {
                return thirdpartyPath+'/'+relativeUrl
            }
        }]]
    })
        
    router.get('/client.js', browserify('./_client.js'))

in `./_client.js`

    require('./_client.css')
    ...
    require('angular')
    require('angular-ui-grid/ui-grid')

in `./_client.css`
