### ISSUE TITLE
items per page translation in pagination

### ISSUE THREAD

**Issue by zyl-edison** [angular-ui/ui-grid#4330]
I think any text in pagination  is not translated for the first of when enter the page. For example 'items per page'. but when I switch between route, it will translate with missing translation for 'of'. Other parts like header menus works ok

**First time loading**
![screen shot 2015-09-06 at 11 09 27 am](https://cloud.githubusercontent.com/assets/2285679/9705857/d1ec18d4-5487-11e5-9d2d-6cd155fc3ebe.png)

**After switch the route back to the page**
![screen shot 2015-09-06 at 9 27 48 pm](https://cloud.githubusercontent.com/assets/2285679/9709309/363f979c-54de-11e5-96fc-b109b457fbb9.png)

**Comment by badreal** [comment]
+1

**Comment by radyz** [comment]
Using i18nService.setCurrentLang('<lang>') during app.run solved it for me. Then I just removed all html directives regarding i18n.

**Comment by JSlain** [comment]
+1
Switching the language at runtime still doesn't work.
Might have something to do with the usage of `ui-grid-one-bind-id-grid`
