### ISSUE TITLE
Build only selected modules

### ISSUE THREAD

**Issue by bojanbass** [angular-ui/ui-grid#4332]
Hi,

ui-grid library is quite large with all it's modules loaded. I'm wondering if it's possible to build a version with only core + some selected modules? I'm also confused with the library when using Bower, because there are ui-grid and angular-ui-grid packages available. Which one is the correct one?

**Comment by S-YOU** [comment]
their bower.json name as angular-ui-grid - https://github.com/angular-ui/ui-grid/blob/master/bower.json

**Comment by bojanbass** [comment]
Yes, but bower package points to this source:
https://github.com/angular-ui/bower-ui-grid

and minimized file ui-grid.min.js is 284 kb, which is quite a lot, so I wanted to exclude not needed modules if possible.

**Comment by bojanbass** [comment]
Still no proper answer for my problem... anyone? I'm looking for a solution to minimize the ui-grid library (javascript source) to load only the modules that I need. Minimized library takes 278 kb, which is a lot.

**Comment by mportuga** [comment]
Version 4.4.1 has addressed this problem.
