### ISSUE TITLE
Angular animate causes slowdown

### ISSUE THREAD

**Issue by jinder** [angular-ui/ui-grid#4333]
Not specifically a bug, but I think the documentation should be expanded to highlight that Angular Animate causes UI Grid to be a lot slower than it otherwise would be.  In particular, horizontal scrolling/column virtualization was dramatically slower with angular animate enabled.  Calling `$animate.enabled(element, false);` on the grid container seems to fix the problem.

**Comment by JLLeitschuh** [comment]
Thanks. If you want to add a PR that adds this to something like the FAQ page we'll take a look.
