### ISSUE TITLE
Set max selected rows number

### ISSUE THREAD

**Issue by ianaya89** [angular-ui/ui-grid#4339]
Is there a way to limit the number of rows that a user is allowed to select, if not there is a way to interrupt or avoid a row selection when a user select an specific number?

Thanks!

**Comment by aditya-vardhan** [comment]
There is no predefined function. But I made a function to restrict max selection:
check out this plunk: http://plnkr.co/edit/YhA0mGGJyzq2h2V4Tzin?p=preview

code if plunk does not work:

var rowsSelected = 0;
                    $scope.setSelectable = function() {
                      //$scope.gridApi.selection.clearSelectedRows();

                      $scope.gridOptions.isRowSelectable = function(row){
                      if (rowsSelected == 3)
                          return false;
                          else
                          return true;

                      };
                      $scope.gridApi.core.notifyDataChange(uiGridConstants.dataChange.OPTIONS);


                      $scope.gridApi.core.notifyDataChange(uiGridConstants.dataChange.EDIT);
                    };

                    $scope.gridOptions.onRegisterApi = function(gridApi){
                      //set gridApi on scope
                      $scope.gridApi = gridApi;
                      gridApi.selection.on.rowSelectionChanged($scope,function(row){
                        var msg = 'row selected ' + row.isSelected;
                        if(row.isSelected)
                    rowsSelected += 1;
                if(!row.isSelected)
                    rowsSelected -= 1;
                        if(rowsSelected == 3)
                        $scope.setSelectable();
                        if(rowsSelected == 2)
                        $scope.setSelectable();

                      });


                    };

**Comment by ramseyfeng** [comment]
Is is issue be fixed?
@aditya-vardhan Your plnkr is not working if i use shift to do the multi-selection.

**Comment by adityavardhan2017** [comment]
Yup @ramseyfeng it to work with checkbox. Try to look at docs at grid site to configure it with shift. I feel checkbox is enough for selection as you can select row with just mouse click

**Comment by ramseyfeng** [comment]
@aditya-vardhan I know you plunker is working if user only select by mouse clicking.
But if the grid has enabled the shift functionality, it is still an issue.
