### ISSUE TITLE
Aria notifier always stays visible

### ISSUE THREAD

**Issue by avishnyak** [angular-ui/ui-grid#4347]
In the file ```ui-grid/src/features/cellnav/js/cellnav.js```

These lines (800-801 & 808-809) end up leaving the aria value always visible.

```
ariaNotifier[0].style.visibility = 'hidden';
ariaNotifier[0].style.visibility = 'visible';
```

I would expect the ariaNotifier to not be visually visible to all users.

**Comment by swalters** [comment]
@JLLeitschuh thoughts?

**Comment by JLLeitschuh** [comment]
This is done intentionally. On some OS/Browser combos the element has to be toggled in order to get it to be read out.
The ariaNotifier uses the following styling:
https://github.com/angular-ui/ui-grid/blob/master/src/features/cellnav/less/cellNav.less#L24
This places the notifier far offscreen.

**Comment by avishnyak** [comment]
I figured out that I had an old copy of the CSS that wasn't updated with the latest build so this issue can be closed. Thanks for the info!
