### ISSUE TITLE
pagination don't work well with image in cell

### ISSUE THREAD

**Issue by TurtleFromBupt** [angular-ui/ui-grid#4348]
this is part of my code

$scope.gridOptions = {
enableSorting: true,
rowHeight:100,
paginationPageSize: 1,
columnDefs: [
  { field: 'id' },
  { field: 'image', cellTemplate:"<img width=\"50px\" ng-src=\"{{grid.getCellValue(row, col)}}\" lazy-src>"}
],
data:[
  {id:"1",image:"http://dreamatico.com/data_images/car/car-2.jpg"},
  {id:"2",image:""},
  {id:"3",image:""}
  ]

when i click "next page", the image didn't change. 
anyone know how to get over this?
this is my example on plunker
http://plnkr.co/edit/P7Qb9zSJGWPyXRPS9CYC

**Comment by mportuga** [comment]
I don't believe this is an issue with UI-Grid, but something about ng-src. What I learned was that when you have an actual text value for the image attribute, the grid will update it. But if you leave it empty, it won't in the following example, I achieved the desired behavior by using a null attribute for one of the cells.
http://plnkr.co/edit/Iv8JgaztNL87AvOmznWB?p=preview
