### ISSUE TITLE
Many Translations Missing [i18n]

### ISSUE THREAD

**Issue by alexnaldo** [angular-ui/ui-grid#4349]
The translate for many languages doesn't have all elements, like it :

pagination:
{
  of:'of'
}

**Comment by JLLeitschuh** [comment]
Yes, many people who create features don't create all of the translations. They are added by developers who need them.
We generally accept Pull Requests fairly quickly that add them for languages that are missing. If you would like to contribute this please feel free.

**Comment by mportuga** [comment]
This issue is addressed by pull request #6762
