### ISSUE TITLE
grid.appScope undefined in rowTemplate

### ISSUE THREAD

**Issue by isharsha** [angular-ui/ui-grid#4350]
EDIT: I am using ui-grid 3.0.1

Hi,

I need to be able to add/delete/update rows from a context-menu that has options on what to do to the row. I currently have the contextmenu bound to my entire grid as I can't figure out how to get just the row from a right click.

This is currently my rowTemplate:

"
<div
     ng-repeat="(colRenderIndex, col) in colContainer.renderedColumns track by col.uid"
     ui-grid-one-bind-id-grid="rowRenderIndex + '-' + col.uid + '-cell'"
     class="ui-grid-cell"
     ng-class="{ 'ui-grid-row-header-cell': col.isRowHeader }"
     role="{{col.isRowHeader ? 'rowheader' : 'gridcell'}}"
     oncontextmenu="console.log(grid);console.log(grid.appScope);"
     ui-grid-cell>
</div>
"

This is the Grid div (sorry for the formatting):
"

`````` html
<
            <div ng-controller="YTPrivateGrid" context-menu="menuOptions">
                <div id="grid" ui-grid="gridOptions" class="grid" ui-grid-cellNav ui-grid-pinning ui-grid-pagination ui-grid-exporter ui-grid-selection ui-grid-resize-columns >
                  <div class="no-data" ng-show="loading">
                      <div class="watermark">Loading Data...</div>
                  </div>
                  <div class="watermark" ng-show="gridOptions.data.length==0 && !loading && no_data_available">
                      No records found
                  </div>
                </div>
            </div>
/>```
"

The console logs grid and grid.appScope, but grid has content whereas grid.appScope is undefined.
I would prefer to be able to also have scope of my MenuOptions so that I can just add context-menu="MenuOptions" to the rowTemplate and be able act on it, but that is all scope issues from what I understand.

Does anyone have any idea as to why I am unable to get grid.appScope?
I would also very much appreciate other approaches to this problem which work for you guys and reasons for implementing it in such a way :)

Thanks!
``````

**Comment by lebolo** [comment]
Did you set `gridOptions.appScopeProvider` to something else or are you just doing it like [this tutorial](http://ui-grid.info/docs/#/tutorial/305_appScope)? Maybe create a plunker so we better debug?

**Comment by isharsha** [comment]
I've not set gridOptions.appScopeProvider to anything and yes, I am doing it like in that tutorial. 
I can't really put everything on plunker as this is part of a larger project for my company.

I will update the question with the grid div.
