### ISSUE TITLE
Grid data is not seen until the window is resized

### ISSUE THREAD

**Issue by RajaSreekanth** [angular-ui/ui-grid#4352]
I've migrated from ngGrid to use the latest ui-grid. When the page is loaded I see an empty grid, on checking the developer tools I realized that data is indeed come to the widget. When I resize the window the grid data is visible. This is happening when the page is loaded for the first time. Subsequent changes in the data are seen properly. I tried to change the default grid options, but they didn't fix the issue.

Not sure if this is already observed and reported, please let me know if I can do something to fix this.

**Comment by JLLeitschuh** [comment]
What are your grid options?

**Comment by ekaram** [comment]
+1 

vm.gridOptions = {
        enableFiltering: true,
        enableRowSelection: true,
        enableColumnMenus: false,
        enableRowHeaderSelection: false,
        multiSelect: false,
        data: rallies,
        paginationPageSizes: [
          10,
          20,
          30
        ],
        paginationPageSize: 15,
        enableVerticalScrollbar: uiGridConstants.scrollbars.NEVER,
        rowTemplate: '<div ui-sref="app.page" ng-repeat="col in colContainer.renderedColumns track by col.colDef.field" class="ui-grid-cell" ui-grid-cell></div>'
      };

**Comment by RajaSreekanth** [comment]
Sorry, for missing to reply earlier. We are not passing any additional parameters. 

gridOptions = {
            data: data.rows,
            columnDefs: data.columnNames,
            enableSorting: true
};

**Comment by Vinodang** [comment]
for ng-grid i think you need to call `gridOptions.ngGrid.buildColumns()`; for ui-grid you need to call `gridApi.core.refresh()`;

**Comment by bennettatoms** [comment]
@RajaSreekanth: Did you figure out how to fix this? I'm running into this exact issue now.

**Comment by abhinavsayan** [comment]
Have you defined the div width ? The issue goes away if you define the width.

**Comment by gsalisbury-advera** [comment]
@abhinavsayan - thanks a ton for this suggestion! None of the other answers to this bug worked for me.

**Comment by abhra007** [comment]
> Have you defined the div width ? The issue goes away if you define the width.

Where and how to define the width
