### ISSUE TITLE
Can't resize grid

### ISSUE THREAD

**Issue by DevQueen** [angular-ui/ui-grid#4355]
My grid only shows about 8 records.  I tried to re-size the grid by creating a class:

.myGrid{
    height: 1000px;
    width: 100%;
}
The width is fine, but the height doesn't change at all.  I event tried setting the height to 100% and still no change.  My data results is about 650 records which I am displaying 25 records per page, but only the first 8 show and I have to scroll to see the rest on each page.

**Comment by LaloHD** [comment]
DevQueen, what was your solution to this? i want my grid to be 100% of the height

**Comment by DevQueen** [comment]
I added the following to the ui-grid.css file:

.grid{
    width: 100%;
    height: 800px;
}

Hope that works for you.  I am using version v3.0.5 .

**Comment by LaloHD** [comment]
@cmichaelgraham handend his  [example](http://cmichaelgraham.github.io/ng-ui-grid-flexbox/index.html) from https://github.com/cmichaelgraham/ng-ui-grid-flexbox/tree/master/ng-ui-grid-flexbox but I haven't been able to use it on my project

**Comment by LaloHD** [comment]
there you go, with this example, you can get a responsive grid, http://www.spaprogrammer.com/2015/06/angularjs-ui-grid-vertical-resize.html
