### ISSUE TITLE
Ui-grid columns filter icon adjustment

### ISSUE THREAD

**Issue by RipuGuleria** [angular-ui/ui-grid#4369]
hi ,
i am using ui-grid. With every column i have given fixed width manually. But the filter icon behaving differently with each and every column.Why is it so.
here is my plunkr:- http://plnkr.co/edit/90V1ak9bSHDufWdVS9T9?p=preview

Thanks.

**Comment by JLLeitschuh** [comment]
Not really sure what the problem is. Nor what you want to see fixed.

**Comment by RipuGuleria** [comment]
hi
as you can see in the plunkr, that on last column  the filter icon appear in front of  the text. But with other columns it's appearing after the column text.

Thanks

**Comment by imnutz** [comment]
You should increase the width of the last column, for example: ```{width: 100}```

**Comment by RipuGuleria** [comment]
ok, but if i don't have the column records not more than  two or three characters. Then why should i need to increase that much height.

**Comment by imnutz** [comment]
You might need to add css for that last column, like this:
```
.ui-grid-column-menu-button-last-col {
    left: 40px;
}
```

**Comment by RipuGuleria** [comment]
Thanks for this valuable info. But what if this situation comes before last column . I have updated my plunkr

**Comment by RipuGuleria** [comment]
is there any setting to do it dynamically for all the columns
