### ISSUE TITLE
broken link (to localhost) on ui-grid.info site

### ISSUE THREAD

**Issue by sgbeal** [angular-ui/ui-grid#4372]
Site: http://ui-grid.info/docs/#/api

see the top/left link (labeled "UI Grid"). It goes to:

http://127.0.0.1:9003/

**Comment by JLLeitschuh** [comment]
I'm not experiencing the problem on my machine.
Try clearing your cache.

**Comment by Treysin** [comment]
I had this same issue a couple of times yesterday and actually just now too. It doesn't happen all the time and it's not always that specific URL redirecting to it. But it does redirect to 127.0.0.1.

**Comment by sgbeal** [comment]
My first use of the site ever was when i reported this problem, so cache
cannot be playing a role. i observed the localhost redirect on two subpages
but not the home page.

----- stephan
Sent from a mobile device, possibly from bed. Please excuse brevity, typos,
and top-posting.

**Comment by Atmos206** [comment]
This also occurs for me. Not just on API section, but also Tutorial section as well.

**Comment by sgbeal** [comment]
Just test again on a different machine (first visit to that site on this machine). Still pointing to localhost.

**Comment by JLLeitschuh** [comment]
I think this is fixed.
