### ISSUE TITLE
Unable to toggle row selection

### ISSUE THREAD

**Issue by jesper** [angular-ui/ui-grid#4375]
Reproduce in the tutorial:
http://ui-grid.info/docs/#/tutorial/210_selection

Clicking "toggle rowSelection" doesn't actually do it.

**Comment by lebolo** [comment]
It works for me (Win7 - Chrome 45.0.2454.85 m).

**Comment by jesper** [comment]
No luck here. Tried both Chrome (46.0.2490.13) and Firefox (40.0.3) on Ubuntu 15.04.

**Comment by jesper** [comment]
Doh, I misunderstood the feature. I thought it would enable/disable the checkbox column on the left. Clearly, this isn't the case/intention. Closing.
