### ISSUE TITLE
Possible Bug While Editing Cell With Value Derived From Filter

### ISSUE THREAD

**Issue by aarosil** [angular-ui/ui-grid#4378]
I think I may have found a minor bug, but not sure if I'm missing some options for this to work how I want.  

Basically, I have a calculated field in my grid, which depends on the value of 2 other fields (ie qty, price, and total).  Either of fields can be edited, if total amount is edited, the qty is recalculated based on the price

When the user clicks the field with the filter-derived value to edit it, and then clicks away, the field value is set to zero, and both `oldVal` and `newVal` arguments to `afterCellEdit` function are `undefined`.  If the user hits escape, it works normally and resets the value back to what it was before.   Also, if the cell was successfully edited already, the bug doesn't happen -- clicking to edit then clicking away also restores the correct previous value

Should clicking away also trigger `cancelCellEdit` does like hitting escape, is there some reason this can't work?  Is there any workaround for this bug?  I'm glad to help however possible.  I created a plunk demonstrating this behavior here: http://plnkr.co/edit/NuYq6l3RfodD1kRyeTB8?p=preview

**Comment by mportuga** [comment]
Clicking away works like submitting not like clicking away since that is the expected behavior for most grid users.
