### ISSUE TITLE
paginationPageSizes for more than 2 digit number not shown well

### ISSUE THREAD

**Issue by donnygunawan93** [angular-ui/ui-grid#4380]
![untitled](https://cloud.githubusercontent.com/assets/10414213/9898165/4ebda360-5c7a-11e5-9735-4d1642a43c72.png)

look at that 100 but like a 10

**Comment by JLLeitschuh** [comment]
What browser are you experiencing this with?

**Comment by JoshuaThompson** [comment]
I was able to recreate it in Chrome and IE11 using the pagination example on the ui-grid site. [plunk](http://plnkr.co/edit/BfjRKLSkucdOkRtQ1XKu?p=preview)

**Comment by JLLeitschuh** [comment]
Thanks for the PR! Merged in!
