### ISSUE TITLE
Grid does not resize

### ISSUE THREAD

**Issue by DevQueen** [angular-ui/ui-grid#4382]
I have a collapsible sidebar in my page.  If the sidebar is collapsed, the body of the page expands to 99% of the page.  When this happens, the grid does not resize.  Also, once the sidebar is again expanded and the body goes back to its original width, the grid still does not resize.  Here is an image of my issue:

![ui-grid issue](https://cloud.githubusercontent.com/assets/13017434/9912980/f5a4b750-5c6f-11e5-9cf1-00f5faa4dde7.png)

**Comment by swalters** [comment]
are you using the auto-resizing feature? http://ui-grid.info/docs/#/tutorial/213_auto_resizing

**Comment by DevQueen** [comment]
Didn’t know there was one.  Thanks!

[Beryl Small]

Beryl Small
IT / Programmer
985.629.5934 (D)
800.892.8179 (O)
985.892.8114 (F)
http://www.pecsafety.com/
This e-mail is confidential and is intended solely for the use of the recipient.  If you are not the intended recipient, be advised that you have received this e-mail in error and that any use, dissemination, forwarding, printing, or copying of this e-mail is strictly prohibited.

**Comment by DevQueen** [comment]
I added the auto-resize, but it is doing basically the same thing.  Is there anything special that I need to do besides injecting it in the module and including in the div with the grid?

[Beryl Small]

Beryl Small
IT / Programmer
985.629.5934 (D)
800.892.8179 (O)
985.892.8114 (F)
http://www.pecsafety.com/
This e-mail is confidential and is intended solely for the use of the recipient.  If you are not the intended recipient, be advised that you have received this e-mail in error and that any use, dissemination, forwarding, printing, or copying of this e-mail is strictly prohibited.

**Comment by DevQueen** [comment]
Nevermind.  It seems it took a minute to take effect.  It is resizing now.  Thank you so much for your help!


[Beryl Small]

Beryl Small
IT / Programmer
985.629.5934 (D)
800.892.8179 (O)
985.892.8114 (F)
http://www.pecsafety.com/
This e-mail is confidential and is intended solely for the use of the recipient.  If you are not the intended recipient, be advised that you have received this e-mail in error and that any use, dissemination, forwarding, printing, or copying of this e-mail is strictly prohibited.

**Comment by swalters** [comment]
That should do it.  I use it with a disappearing sidebar and it works for me.  Make sure you are not including grid width in the grid style and that position:relative.  It works for me that way so it's worth a shot.

**Comment by DevQueen** [comment]
Thank you!  You’re an angel!


[Beryl Small]

Beryl Small
IT / Programmer
985.629.5934 (D)
800.892.8179 (O)
985.892.8114 (F)
http://www.pecsafety.com/
This e-mail is confidential and is intended solely for the use of the recipient.  If you are not the intended recipient, be advised that you have received this e-mail in error and that any use, dissemination, forwarding, printing, or copying of this e-mail is strictly prohibited.
