### ISSUE TITLE
buildColumns / preCompileCellTemplates called each time grid data is changed

### ISSUE THREAD

**Issue by oriondean** [angular-ui/ui-grid#4386]
Hi,

I noticed that ui-grid dataWatchFunction rebuilds all columns and pre-compiles cell templates each time data is changed (see: [ui-grid.js:109](https://github.com/angular-ui/ui-grid/blob/caf8ae5e89c2e13dc242db23c9f2fc3435fefc4b/src/js/core/directives/ui-grid.js#L109)).

My understanding is that after the columns/cell templates have been built/compiled once then they do not need to be built/compiled again unless the column definitions change in any way.
There's already a watcher on the column definitions (see: [columnDefsWatchFunction](https://github.com/angular-ui/ui-grid/blob/caf8ae5e89c2e13dc242db23c9f2fc3435fefc4b/src/js/core/directives/ui-grid.js#L68)) that does this job already.

From my experiences, not building/compiling columns/cell-template each time data changes can improve performance significantly for grids that update data often.

Question: Is there any possible reason why columns need to be built each time data changes?
If not, i'm more than happy to submit a pull request to add this improvement!

Thanks

**Comment by badri77** [comment]
Hi, in converse to this issue, i am binding variable length data, so i am binding columns dynamically and also i have conditional styles and icons are being rendered on based the cell data. When, i rebind the data (which is different), the data is changing but not cell styles and icons. please let me know how to resolve this issue.
