### ISSUE TITLE
Urgent Problem - Scrumbled Grid 

### ISSUE THREAD

**Issue by dontforgettocompile** [angular-ui/ui-grid#4387]
![scrumbled grid](https://cloud.githubusercontent.com/assets/14331331/9934343/daca9cf6-5d50-11e5-8671-d7a285932e6f.png)

Hi :-)
i'm having some trouble with the ui-grid. its not always but pretty often. i come from a state an the grid looks scrumbled (sorry i dont know how to call that ;) )
i thought it would be some caching problem, so i added {reload: true} to my state.go. But the problem is still existing. Do you have heard of that before? is there an easy way to solve this?

Best Regards

**Comment by JLLeitschuh** [comment]
Are you using custom cell templates?

**Comment by dontforgettocompile** [comment]
no, rowTemplate to create a mouse hover effect

**Comment by JLLeitschuh** [comment]
Try using directive stacking instead, You will get better performance and you are less likely to have issues with future versions.

**Comment by dontforgettocompile** [comment]
what do you mean by directive stacking?

**Comment by cjp666** [comment]
I have a similar problem.  I have only one ui-grid on the screen.  When I scroll right and then left again it redraws correctly

![image](https://cloud.githubusercontent.com/assets/4498931/10103359/5956ef16-639b-11e5-9cc7-9d5ba2e64548.png)

**Comment by JLLeitschuh** [comment]
Have a look at how all of the features are written. You can define a
directive that extends the functionality of another directive.

**Comment by cjp666** [comment]
I'm sorry but I do not understand what you mean or are telling us what to do

**Comment by cjp666** [comment]
Figured out the problem I was having

My ui-grid was being loaded as part of an ng-include but the grid options where set-up beforehand and the data loaded later.  I have changed the code so that when the template url is set and the data loaded, I also set up the column definitions at this point which sorted the problem I was having

Hope this makes sense
