### ISSUE TITLE
How to get row on right click?

### ISSUE THREAD

**Issue by isharsha** [angular-ui/ui-grid#4388]
Hi,

I'm currently trying to select the row on right-click just like the grid does on left click, but I'm having trouble getting the row information.

Does anyone know a straightforward way to do this?

Thanks!

**Comment by JLLeitschuh** [comment]
Try using directive stacking to stack on top of the row directive. Then you can attach a right click event that retrieves the $scope.row
Hope that helps.

**Comment by isharsha** [comment]
Thanks, that works! This is my solution:

grid_row.html (this is my rowTemplate):

<div
     ng-repeat="(colRenderIndex, col) in colContainer.renderedColumns track by col.uid"
     ui-grid-one-bind-id-grid="rowRenderIndex + '-' + col.uid + '-cell'"
     class="ui-grid-cell"
     ng-class="{ 'ui-grid-row-header-cell': col.isRowHeader }"
     role="{{col.isRowHeader ? 'rowheader' : 'gridcell'}}"
    ng-right-click="hihi"
     ui-grid-cell>
</div>

and I use it with:

matrix.directive('ngRightClick', function($parse) {
    return function(scope, element, attrs) {
        var fn = $parse(attrs.ngRightClick);
        element.bind('contextmenu', function(event) {
            scope.$apply(function() {
              var selected_row = scope.$parent.$parent.row;
              selected_row.setSelected(true);
                event.preventDefault();
                fn(scope, {$event:event});
            });
        });
    };
});
