### ISSUE TITLE
Cell navigation does not show correct column if there is pinnedLeft column

### ISSUE THREAD

**Issue by htettwin** [angular-ui/ui-grid#4389]
When there are columns pinned to the left, the cell nav does not show correct column.
See plunker http://plnkr.co/edit/YJAu6irPzKgUURzsf1ju?p=preview

**Comment by swalters** [comment]
your plunker doesn't allow column pinning.  Is it updated to include that feature?

**Comment by htettwin** [comment]
Here is the plunker http://plnkr.co/edit/Kq6ao86GJ7j6cnMCd5Hb?p=preview. I think the issue is at line 2372 in core/factories/Grid.js. The value for columnRightEdge needs to take in account of the width of the pinned view port. The following seems to fix the issue.

var pinnedLeftWidth = self.renderContainers.left ? self.renderContainers.left.getViewportWidth() : 0;
var columnRightEdge = columnLeftEdge + gridCol.drawnWidth + pinnedLeftWidth;
