### ISSUE TITLE
ng-grid filter not working

### ISSUE THREAD

**Issue by esayli** [angular-ui/ui-grid#439]
Hello,

ng-grid filter not working.

I tried many examples. Here the example http://plnkr.co/edit/kcgoXx

If ı run the example , ı can't see any data.

But if I remove 

filterOptions: $scope.filterOptions,

in main.js , data shows up.

I used chrome and ie but doesn't change anything.

**Comment by Cdvalencia** [comment]
You must to add the next sentence on gridOpttions -> 
filterOptions: {filterText: '', useExternalFilter: false}


Hi! 

When your input change of text, you must to make next expression, on function created:
$scope.gridOptions.filterOptions.filterText = '<FIELD COLUMN YOUR TABLE>:'<VARIABLE or TEXT INPUT>';

'columna:textfilter' -> This send the filter automatically to the filter in ng-grind.

So, you add the next css:
.ngHeaderButton{
  display:none
}

the useExternalFilter: false is very important.

Luck.
