### ISSUE TITLE
Aggregation Sum Floating Point Rounding

### ISSUE THREAD

**Issue by ruhley** [angular-ui/ui-grid#4392]
When using ```aggregationType: uiGridConstants.aggregationTypes.sum``` in the column definitions with data that contains decimal places the footer can show very long decimal places (e.g. 0.30000000000000004)

http://plnkr.co/edit/zb9OKpnWWBJGJWGcAe7h?p=preview

**Comment by Samy-A** [comment]
You can add footerCellFilter: 'number:1' to your field definition to fix this.

**Comment by ruhley** [comment]
Great, thanks for that. For some reason I never made the link between a cellFilter and an angularjs filter. I also don't recall seeing an example passing in a variable like ```number:1```. Maybe this should be made more clear in the documentation.
