### ISSUE TITLE
Do you plan to migrate to gulp?

### ISSUE THREAD

**Issue by salarmehr** [angular-ui/ui-grid#4393]
Gulp is far faster and easier than grunt. Using it may encourage more developer to collaborate. Do you plan to use gulp soon?

**Comment by JLLeitschuh** [comment]
I think that our next big build conversion will be converting grunt-ngdocs over to angular's dgeni.
If you would like to propose a conversion strategy we'd be happy to take a look. If we like it you are welcome to implement the conversion.
