### ISSUE TITLE
Using .text() to set uiGridStyle is inefficient when using JQuery

### ISSUE THREAD

**Issue by rwilliams-scottlogic** [angular-ui/ui-grid#4396]
The uiGridStyle directive sets the content of the grid style tag, using .text().

While the JQLite implementation of text() simply sets textContent, JQuery's implementation will set it twice - once to clear it, then again to set it to the new value. This causes two assignments to textContent, each of which causes layout.

Using textContent is more performant for example when a burst of rows are added to a grid.

I see it was changed from textContent to text() in ade12ec98f82400ddbc25ac2676fc88e66408164,

**Comment by JLLeitschuh** [comment]
Can you check the blame and see if this was done this way to fix a bug?

**Comment by rwilliams-scottlogic** [comment]
I did look at the commit I linked; the commit message sounds like it was done to tidy up the content of the inline stylesheet only.

**Comment by JLLeitschuh** [comment]
If you want to make a PR I'll take a look.
