### ISSUE TITLE
Template for ui-grid incorrectly sets last row's bottom border

### ISSUE THREAD

**Issue by dbrink** [angular-ui/ui-grid#4413]
The bottom border on the last row is never made visible because the binding expression references grid.getTotalRowHeight() which isn't defined.

``` css
.grid{{ grid.id }} .ui-grid-row:last-child .ui-grid-cell {
   border-bottom-width: {{ ((grid.getTotalRowHeight() < grid.getViewportHeight()) && '1') || '0' }}px;
}
```

**Comment by RobPierce** [comment]
I see this has been around for a long time, I've come up with a slight tweak to this that should achieve the result that the logic here seemed to be trying to create, given the getTotalRowHeight function doesn't exist:

`.grid{{ grid.id }} .ui-grid-row:last-child .ui-grid-cell {
   border-bottom-width: {{ (((grid.getVisibleRowCount() * grid.options.rowHeight) < grid.getViewportHeight()) && '1') || '0' }}px;
}
`
I'll create a PR for this.

**Comment by mportuga** [comment]
https://github.com/angular-ui/ui-grid/pull/6515
