### ISSUE TITLE
How do set a default value for an undefined cell

### ISSUE THREAD

**Issue by epintos** [angular-ui/ui-grid#4419]
Hi,

I have a table with lots of columns and some rows may have undefined values so I want to show a default text instead of an empty cell. How can I set that value?

I would expect something like this:

``` javascript
columnDefs: [
    {name: 'Code', field: 'code', default: 0}
]
```

Thanks

**Comment by sbalay** [comment]
+1

**Comment by IcarusTalon** [comment]
Or even an option that allows you to leave an undefined field blank instead of showing an undefined error would be nice.

**Comment by Mady007** [comment]
+1

**Comment by lebolo** [comment]
+1

There's a [workaround](http://stackoverflow.com/questions/32725038/setting-a-column-default-value-on-angular-ui-grid), but was hoping for a `columnDef` parameter.
