### ISSUE TITLE
Last row will lose focus while edit after clicking

### ISSUE THREAD

**Issue by zuohaocheng** [angular-ui/ui-grid#4422]
In the example given by [tutorial 201](http://ui-grid.info/docs/#/tutorial/201_editable), there's an issue that last row will lose focus, when clicking the input box in edit mode. It can be reproduced in Chrome & IE, as the procedure below:

1. Scroll the grid to very bottom
2. Double click on any editable cell, to enter edit mode
3. Click anywhere inside the input box again
4. Focus will be lost

The root cause of the issue is, commit 91077e828f450bbb7cb0c76404686110f700e396 which fixes #3128 disables scrolling by set `grid.disableScrolling` when clicking on input element again (step 3). 

- Disables scrolling will cause absence of scroller, which triggers resize of grid viewport. 
- Then, a `scroll` event will be triggered by browser, thus triggers `scrollBegin`
- Event listener on `scrollBegin`(`deregOnGridScroll`) will get the event, and call `endEdit` to exit edit mode.

**Comment by awn70** [comment]
Will this fix find its way into the ui-grid master? 
I have a problem that looks very similar, dropdown in last row looses focus and can't be edited at all.

**Comment by imbalind** [comment]
This was merged at the end of september by commit 79e7cf2.

I'm closing this, the dropdown in last row issue is #4634
