### ISSUE TITLE
ColumnDefs as a string (dynamic columns) error.

### ISSUE THREAD

**Issue by vniko** [angular-ui/ui-grid#4431]
I'm trying to make dynamic columns. As per example https://github.com/angular-ui/ui-grid/wiki/Defining-columns
```
 $scope.myDefs = [{ field: 'firstName', displayName: 'First Name', width: "*", resizable: false},
                     { field: 'lastName', displayName: 'Last Name', width: "20%" },
                     { field: 'address', displayName: 'Address', width: "*" },
                     { field: 'age', cellClass: 'ageCell', headerCellClass: 'ageHeader', width: "**"}];
    $scope.gridOptions = {
        data: 'myData',
        columnDefs: 'myDefs'
    };
```

My code exactly is
```
$scope.myData = [];
        $scope.myDefs = [	{ field: "id", displayName:"ID" }, { field: "name", displayName: "WWW"}];

        $scope.gridOptions = {
            enableRowSelection: true,
            enableSelectAll: true,
            multiSelect : true,
            selectionRowHeaderWidth: 35,
            rowHeight: 35,
            showGridFooter:true,
            data: 'myData',
            columnDefs: 'myDefs'
        };

        $http.get('/500_complex.json')
            .success(function(data) {
                $scope.myData = data;

            });
```

HTML
```
<div ui-grid="gridOptions" ui-grid-selection  ui-grid-pagination  class="grid"></div>
```

And i have the following errors

1) TypeError: f.options.columnDefs.forEach is not a function
    at p.buildColumns (ui-grid.min.js?s=:7)
    at ui-grid.min.js?s=:7
    at angular.js:13168
2) TypeError: this.options.columnDefs.filter is not a function
    at p.getColDef (ui-grid.min.js?s=:7)
    at p.buildColumns (ui-grid.min.js?s=:7)
    at m (ui-grid.min.js?s=:7)
3) TypeError: this.options.columnDefs.filter is not a function
    at p.getColDef (ui-grid.min.js?s=:7)
    at p.buildColumns (ui-grid.min.js?s=:7)

If i change  columnDefs:  for the array instead of string it works just fine.

**Comment by swalters** [comment]
Do not define columnDefs as a string. this is old ng-grid behavior. 

Please note that the wiki is for ng-grid.  You should use http://ui-grid.info for reference
