### ISSUE TITLE
Change Color of Text in Filter Textbox

### ISSUE THREAD

**Issue by DevQueen** [angular-ui/ui-grid#4433]
Is there a way to change the color of the text typed in the filter textbox?  I received a request to change the header row background to dark blue with white text.  I was able to accomplish this, however, now the text in the filter textbox is also white and cannot be seen.  Any assistance is greatly appreciated.

**Comment by cjp666** [comment]
Have you tried something along the lines of setting these CSS values?

.ui-grid-header-cell {
	background-color: blue;
	color: white;	
}

.ui-grid-filter-input {
	color: blue;
}


![image](https://cloud.githubusercontent.com/assets/4498931/10103474/178b99d2-639c-11e5-8adb-9a13fd8a6e92.png)

**Comment by DevQueen** [comment]
Thank you!  I am new to CSS as well, so I appreciate your help.  The filter-input is what I needed.

Sent from my iPhone

On Sep 25, 2015, at 9:44 AM, "cjp666" <notifications@github.com<mailto:notifications@github.com>> wrote:


Have you tried something along the lines of setting these CSS values?

.ui-grid-header-cell {
background-color: blue;
color: white;

}

.ui-grid-filter-input {
color: blue;
}

[image]<https://cloud.githubusercontent.com/assets/4498931/10103474/178b99d2-639c-11e5-8adb-9a13fd8a6e92.png>

**Comment by cjp666** [comment]
No problem, glad to help.  I guess someone needs to close the issue
