### ISSUE TITLE
IE9 CellNav Problem When Navigete To Last Row

### ISSUE THREAD

**Issue by zvovk1** [angular-ui/ui-grid#4439]
Hi all.
Guys I have a problem with cell navigation in IE 9 (in Chrome it's OK);

Description: 
I have a grid with many items. And each row has 1 editable cell.
So when I focused in editable cell I hit "Enter" I navigate to editable cell in next row, and this works fine for visible rows, but not for last row. 
What I mean ? 
I mean that  when I focus into last visible cell and hit "Enter" grid provide auto scroll and select next row(which was invisible before) and focus on it and set value, but in next moment this active cell lost focus (feels like jQuery "blur" event post-works).

Please help with my issue.
Many thanks for your attention and help.

**Comment by mportuga** [comment]
Removed IE9 support.
