### ISSUE TITLE
I can't understand why my code doesn't work

### ISSUE THREAD

**Issue by carlosriveroib** [angular-ui/ui-grid#4443]
I'm trying to make a simple grid that allows cell edit, but I can't understand why my code doesn't work.
http://plnkr.co/6LZpH4s7E5TrgrDK8Lms

Thank you for help.

**Comment by cjp666** [comment]
Hi,

There are a few things wrong the main one being that you didn't included ng-grid as dependencies on your angular module

http://plnkr.co/edit/lDL1LqiyhzXE9xfylCjt?p=preview

**Comment by rive46** [comment]
Thank you, this works good.
But now I have a problem. I made an app created using Yeoman. I have the same code and when I include ng-grid as dependencies on my angular module, the grid doesn't work.

Thank you for help.

**Comment by cjp666** [comment]
I don't know anything about Yeoman but you definitely have 'ui.grid' and 'ui.grid.edit' as dependencies?  If so then I'm probably not going to be able to help much more without first learning Yeoman and I don't really have the time for that, sorry

**Comment by rive46** [comment]
It must be a library problem I guess.
If I use "var members = angular.module('app');" The grid shows but I can't edit.
If I use "var members = angular.module('app', ['ui.grid', 'ui.grid.edit']);" The grid doesn't show.
If I use "var members = angular.module('app', []);" The grid neither show.
