### ISSUE TITLE
exporterCsvFilename and exporterPdfFilename to accept function

### ISSUE THREAD

**Issue by ntgn81** [angular-ui/ui-grid#4446]
I would like to be able to set the name of the download file at the moment of downloading.

This allows me to set the name based on things I wouldn't have at the time of setting up the grid, such as:
- current time
- what's being downloaded

What I am thinking of is to make `exporterCsvFilename` and `exporterPdfFilename` to expect a function, in addition to string. When it's a function, it will `$q.when(grid.options.exporterCsvFilename())` to get the file name. Letting us make async calls if needed to name the download file.

I can put a PR together if this is a good option to have.

Thanks!

**Comment by PaulL1** [comment]
I'm pretty sure it grabs the filename at the point we try to save.  So you could equally hook onto one of the exporter callbacks, and set the filename in that callback.  That would require no code change.

**Comment by ntgn81** [comment]
Hmm could you please give me more pointers about the exporter callbacks? Here's where it seems to be using the filename, but I don't see any callback being used.

https://github.com/angular-ui/ui-grid/blob/master/src/features/exporter/js/exporter.js#L613

**Comment by PaulL1** [comment]
There are some callbacks when the data is processed (at least so I recall, I wrote it a fair while ago).  So not directly filename related, but they run before we do the file download, so you could put a filename derivation in there and it would always be before the file downloaded.

**Comment by ntgn81** [comment]
Thanks for looking into it, Paul.

The one relevant callback that I can see is `exporterAllDataFn`, which is only called when we export all data that need to come from server side.

**Comment by PaulL1** [comment]
Yes, sort of true.  For pdf, we have exporterPdfCustomFormatter.  For csv we really only get access to exporterFieldCallback.

I'd probably rather we introduced an exporterCsvCustomFormatter than something specific to filename - I think that would give more flexibility to do other stuff at the time of export.

**Comment by ntgn81** [comment]
Sure, that sounds great to have the callback to modify the downloaded content. Currently, exporterPdfCustomFormatter only allows us to modify the content though, not the file name.

Also, when it's not IE, we are not really downloading PDF, but just open the pdf in a new window. Is that what you meant?

Here's the line  that [exports pdf](https://github.com/angular-ui/ui-grid/blob/91bca52c6d835b529e3a4275e81e4e1adf86c0fc/src/features/exporter/js/exporter.js#L974)

```js
if (self.isIE()) {
  self.downloadPDF(grid.options.exporterPdfFilename, docDefinition);
} else {
  pdfMake.createPdf(docDefinition).open();
}
```

Would it be more consistent to make it download, taking the given filename for all browsers?

```js
if (self.isIE()) {
  self.downloadPDF(grid.options.exporterPdfFilename, docDefinition);
} else {
  pdfMake.createPdf(docDefinition).download(grid.options.exporterPdfFilename);
}
```

**Comment by shamveelcoder** [comment]
Hello Paul,
 I still see the concern raised by 'ntgn81' on chrome download isnt fixed. Do you think we can have those changes pushed in to ui.Grid ?
