### ISSUE TITLE
Tests cause PhantomJS to run out of memory in Windows 7 for Angular 1.3

### ISSUE THREAD

**Issue by bartkiewicz** [angular-ui/ui-grid#4447]
After making a fresh clone of the repo and running the necessary installations, and then running grunt, the tests will run up to angular 1.3. About 680 of the tests will run before PhantomJS crashes. Watching the memory in Task Manager, phantomjs.exe will climb to over 800MB. A similar occurrence happens with our builds machine after we upgraded from ngGrid/2.x to uiGrid/3.0. 

I am not sure if the issue is within angular 1.3, phantomJS 1.9.8, or uiGrid, but it seems like its something that only occurs within a Windows environment.

**Comment by mportuga** [comment]
I am not aware of anyone else experiencing this issue as of late, and since we no longer support angular 1.3 I am closing this issue. Feel free to reopen it if it still a problem
