### ISSUE TITLE
Resetting the default values such as pageSize, totalitems,etc in the ui-grid..xD

### ISSUE THREAD

**Issue by REIP** [angular-ui/ui-grid#4453]
Hello everybody,
I am using ui-grid for pagination on server side, in my page there are filters and two buttons (search and reset) in order to do searching, the search button works fine, but with the reset button there is a problem in the ui-grid. I want to set the pagesize with a value, but I tried with different ways. Can someone help me, thnx..xD? I have attached an image.

![30-09-2015 07-07-35 p-m-](https://cloud.githubusercontent.com/assets/6127838/10209974/0681114e-67a7-11e5-822c-09128bf0ff39.jpg)

**Comment by cjp666** [comment]
Can't you set $scope.gridOptions.paginationPageSize to what you want it to be and then do a $scope.gridApi.core.notifyDataChange(uiGridConstants.dataChange.OPTIONS);
