### ISSUE TITLE
Column resizing behaviour is unexpected

### ISSUE THREAD

**Issue by SlimDogs** [angular-ui/ui-grid#4462]
Situation:
- We have 5 columns.
- We select to resize last column (make it extra wide, so it would not even fit the screen)

At the moment such resize makes all previous columns to shrink. Why? I am resizing only the last column... Is there any option to permit such behaviour?

You can try that in you example page: http://ui-grid.info/docs/#/api/ui.grid.resizeColumns.directive:uiGridColumnResizer

**Comment by gethinoakes** [comment]
This has recently been raised within my team also, is there any particular reason column resizing works like this?

Thanks.
