### ISSUE TITLE
Horizontal Scrolling is not working

### ISSUE THREAD

**Issue by kvrr79** [angular-ui/ui-grid#4463]
Hi,

Horizontal Scrolling is not working. I am using the latest ui-grid (3.0.6) with the following options.
Some posts even mentioned about setting pager style to circumvent the issue with pagination. But still horizontal scrolling is not working. I am using external paging. Will anyone be able to help me in fixing the issue. I tried all possible combinations still it does not work.

.ui-grid-pager-panel {
    bottom: -3px !important;
}

            <div class="myGrid" ui-grid="gridOptions" ui-grid-pagination ui-grid-resize-columns ui-grid-move-columns ui-grid-pinning ui-grid-exporter ui-grid-importer ui-grid-edit ui-grid-selection></div>

            enableHorizontalScrollbar: 1,
            enableVerticalScrollbar: 1,
            enableColumnResizing: true,
            enableColumnReordering: true,
            enableGridMenu: true,
            useExternalSorting: true,
            useExternalPagination: true,
            paginationPageSizes: [25, 50, 75, 100, 500, 1000, 5000, 10000],
            paginationPageSize: 25,
            paginationCurrentPage: 1,
            enableFiltering: true,
            useExternalFiltering: true,

**Comment by kvrr79** [comment]
Issue got resolved. Looks like without minWidth each column gets minimized to fit in all columns to avoid scrolling. Set minWidth to have horizontal scrolling.

**Comment by SourabhRanka** [comment]
HI where to add minWidth property?

**Comment by mportuga** [comment]
In the columnDef: http://ui-grid.info/docs/#!/api/ui.grid.class:GridOptions.columnDef
