### ISSUE TITLE
Booleans (checkboxes) with Safari v9 (El Capitan)

### ISSUE THREAD

**Issue by EricWVGG** [angular-ui/ui-grid#4478]
I am finding that booleans — both with my own code, the tutorials, and various plunkers — do not work with the latest version of Safari 

Double-clicking a cell will bring up a checkbox, but checking it simply unfocuses the cell. The same pages work fine in Chrome, so I believe this is definitely a browser bug.

I do not have an older version of Safari available to test against “Yosemite” or “Mavericks”.

**Comment by EricWVGG** [comment]
The checkboxes do function correctly in iOS Safari 9, incidentally.

**Comment by farooqu** [comment]
This seems to be the same issue as #1785.
