### ISSUE TITLE
Please use native for loop instead of angular.forEach

### ISSUE THREAD

**Issue by ChristianLJ** [angular-ui/ui-grid#4481]
By using the native for() loop and not angular.forEach() (or the native forEach) it is possible to speed up the iterations by more than 60% in Chrome 45. This would indeed speed up the rendering of large datasets.

Test it: https://jsperf.com/angular-foreach-vs-native-for-loop/3

**Comment by wiibaa** [comment]
+1 out of curiosity, also relates to how angular might tune its forEach implementation in the future https://github.com/angular/angular.js/issues/12628

**Comment by swalters** [comment]
angular.forEach should not be used in ui-grid 3+ because we are ES5 and higher.  there are still some old code that has it and we'll be cleaning that up with native foreach

**Comment by PaulL1** [comment]
Except that we do use angular.forEach when iterating over an object rather than an array.  I've been caught out by that before when doing a search and replace to change things to array.foreach
