### ISSUE TITLE
TypeError: Arguments to path.resolve must be strings

### ISSUE THREAD

**Issue by t638403** [angular-ui/ui-grid#4484]
When using ui-grid as a npm module I got this error.

```
path.js:439
      throw new TypeError('Arguments to path.resolve must be strings');
      ^
TypeError: Arguments to path.resolve must be strings
    at Object.posix.resolve (path.js:439:13)
    at /home/erik/PhpstormProjects/df3-frontend/node_modules/resolve/lib/async.js:151:37
    at fs.js:334:14
    at /home/erik/PhpstormProjects/df3-frontend/node_modules/graceful-fs/graceful-fs.js:42:10
    at FSReqWrap.oncomplete (fs.js:95:15)

```

Possible solution/workaround:

I modified `package.json` so that key `main` was not this array: `["./ui-grid.js","./ui-grid.svg","./ui-grid.ttf", "./ui-grid.woff"]` but just the main js file.

```
{
    ...
    "main": "./ui-grid.js",
    ....
}
```

**Comment by mattjanssen** [comment]
Same issue. The same change to `package.json` fixed it.

Why is `main` set to an array of directories and files instead of just `main.js`?

```
  "main": [
    "./less",
    "./ui-grid.css",
    "./ui-grid.eot",
    "./ui-grid.js",
    "./ui-grid.svg",
    "./ui-grid.ttf",
    "./ui-grid.woff"
  ],
```
should be
```
  "main": "./ui-grid.js",
```

**Comment by nikulinsanya** [comment]
Still open??

**Comment by mportuga** [comment]
This issue has been resolved already and is being improved upon by the following PR:
https://github.com/angular-ui/ui-grid/pull/5918/files
