### ISSUE TITLE
Shouldn't the Exact filter condition be Case Sensitive?

### ISSUE THREAD

**Issue by Rumeth** [angular-ui/ui-grid#4486]
The Exact filter condition is currently case insensitive.

"Sample" is returning "SAMPLE, sample, Sample".

Shouldn't this filter condition be case sensitive?

"Sample" should return only "Sample".

**Comment by PaulL1** [comment]
There is a case sensitivity option on all filters. It defaults to not case sensitive.

Sent from my iPhone

On 7 Oct 2015, at 11:26 pm, Rumeth <notifications@github.com<mailto:notifications@github.com>> wrote:


The Exact filter condition is currently case insensitive.

"Sample" is returning "SAMPLE, sample, Sample".

Shouldn't this filter condition be case sensitive?

-

**Comment by kdeng** [comment]
I do believe you can customize your own regexp for exact filter condition.

**Comment by Rumeth** [comment]
Found it. Thank You. Just in case.

```
filter : {
          flags: { caseSensitive : true }
}
```

**Comment by raviji** [comment]
Its not working yet, also tried field in array but its get error "TypeError: Cannot read property 'match' of null"
