### ISSUE TITLE
Error when clicking on empty GroupPanel 

### ISSUE THREAD

**Issue by KeyHiter** [angular-ui/ui-grid#4488]
When you click on the empty group panel you get undefined exception when it tries to update group counter ..

self.fixGroupIndexes = function() {
        angular.forEach($scope.configGroups, function(item, i) {
            item.groupIndex = i + 1;
        });
you can validate item!== undefined but it still crash the grid adding an empty  group.

![ng-grid](https://cloud.githubusercontent.com/assets/14909167/10342377/6805b85c-6cde-11e5-9554-d3dfc0a937a2.png)

**Comment by mportuga** [comment]
This functionality has been removed.
