### ISSUE TITLE
Grouping fails when 'field' in columnDef is referred to some javascript object than a primitive type.

### ISSUE THREAD

**Issue by akshitSinghal1989** [angular-ui/ui-grid#4493]
Grouping fails when 'field' in columnDef is referred to some javascript object than a primitive type, having own custom sorting Algorithm and a cellFilter defined to show exact value from 'field' object.

Code At Plunker: 
http://plnkr.co/edit/ddpNlVneR7Wro2VeelD1?p=preview

Steps:- 
1) Group Address Column
2) Expand All
3) Check Grouping didn't worked as expected (It duplicates last item data for each group)

**Comment by akshitSinghal1989** [comment]
When I debugged the code, I found that there is an issue on how ui-grid creates GroupingHeaderCache Map. It directly uses the value referred by 'field' as a key to create map of header rows for grouped column. Which is always [object Object] in this case.

**Comment by akshitSinghal1989** [comment]
label:grid-grouping

**Comment by akshitSinghal1989** [comment]
Created a fix for this. Please review the following pull request:
https://github.com/angular-ui/ui-grid/pull/4494

**Comment by ankit5990** [comment]
+1
