### ISSUE TITLE
Sort Priority Numbers

### ISSUE THREAD

**Issue by huttereg** [angular-ui/ui-grid#4503]
The new sort priority numbers are pretty sweet, but I think it would be better if they didn't show up when there's only a single sort.

**Comment by zhenyi2697** [comment]
Agree with this ! + 1

**Comment by huttereg** [comment]
i've been using this to hide them. probably not the best, but does the trick
```javascript
$scope.$watch(
    function() {
        return $('.ui-grid-sort-priority-number').text() === '1';
    },
    function(single) {
        var priority = $('.ui-grid-sort-priority-number');
        single ? priority.hide() : priority.show();
    }
);
```

**Comment by stoplion** [comment]
+1

**Comment by thefridge111** [comment]
As an aside, if you want to completely hide them you can use:

`.ui-grid-sort-priority-number {
  font-size: 0;
}`

**Comment by JSGund** [comment]
+1
