### ISSUE TITLE
rowTemplate property name is misleading

### ISSUE THREAD

**Issue by erkanarslan** [angular-ui/ui-grid#4504]
I want to use a custom template for table rows. I tried to override rowTemplate field. However, I noticed that the template we override in rowTemplate field actually is not the row but each column in that row.

I want to add some html elements to each row and NOT to each column. How can I do that? I need to use a custom template for uiGridViewport which contains actual row template but I couldn't find the config property for that.

**Comment by ramirotw** [comment]
Doesn´t this help you https://github.com/angular-ui/ui-grid/wiki/Templating ?

**Comment by erkanarslan** [comment]
I have solved the problem. We don't have to edit only the div with ng-repeat in row template. We can wrap it with another HTML element like this:

````html
<div>
    <originial-row-template>
    <custom-html-element>
</div>
````
