### ISSUE TITLE
UI-Grid  issue with AngularAMD

### ISSUE THREAD

**Issue by meetsivakumar** [angular-ui/ui-grid#4505]
Hi, 

The issue comes when using AngularAMD to load controllers and templates dynamically otherwise not. 
The grid is not loading.

Sample code with the issue is present in the following URL
http://plnkr.co/edit/EqDJw61Koh8eEYcn8odw

**Comment by dehim** [comment]
3rd Party AngularJS Modules

3rd party AngularJS modules, meaning any module created using angular.module syntax, can be loaded as any normal JavaScript file before angularAMD.bootstrap is called. After bootstraping, any AngularJS module must be loaded using the included ngload RequireJS plugin.

define(['app', 'ngload!ui-grid'], function (app) {...});
I

**Comment by guntercn** [comment]
http://plnkr.co/edit/f41mWACfGPP8zYECifo8?p=preview
