### ISSUE TITLE
Maintain 100% width when resizing a column

### ISSUE THREAD

**Issue by viveleroi** [angular-ui/ui-grid#4509]
When resizing a column smaller than its initial width, the entire grid shrinks by the same width. 

I would like an option to refresh the grid sizes so that the column I've resized maintains its width, while the remaining columns are expanded so the grid itself remains 100% the parent width.

**Comment by cjp666** [comment]
Set the widths of the columns to "*" and they will be all fill the grid, when the user resizes a column the remaining ones that still have a width of "*" will fill the remaining space

**Comment by viveleroi** [comment]
I think markdown gobbled your comment but setting all of our fields to dynamic widths won't work because ui-grid doesn't have a separate `initialWidth`-type option - they all start out at equal widths. By defining a width, we have control over how they initially render but we'd like users to be able to resize them, while still maintaining 100%.

**Comment by jeznorth** [comment]
I'll second this request. This is the ONE feature our users need/want

**Comment by jaythomas** [comment]
This is a non-issue with auto width as @cjp666 said. Just use `minWidth` and `maxWidth` columnDef properties to keep the initial column widths in check.
