### ISSUE TITLE
UI Grid $scope.gridApi.core.refresh() not working

### ISSUE THREAD

**Issue by vaibhavchandra** [angular-ui/ui-grid#4516]
Hi i have a UI grid with editable rows and upon some editing values the rows should not be selectable. but the grid doesnt refresh unitil i relaod the view. i also tried  
$scope.gridApi.core.queueGridRefresh(). Can somebody tell me how?

**Comment by buddyackerman** [comment]
I'd like to see some response to this as I have the same problem.  I have external sorting enabled and after my data is sorted and applied to the grid sort I call $scope.gridApi.grid.refresh();  This only works if I have the grid scrolled to the very top or to the very bottom.  If it's anywhere in the middle of the list the sort doesn't work until I scroll the list a few pages one way or another.

**Comment by PaulL1** [comment]
If you've modified the data, the correct call to make is notifyDataChange, many of the tutorials have examples of this.  Refresh doesn't necessarily re-evaluate everything, as it's called in many places, and we try to avoid reevaluating all the logic unless we have to.

**Comment by buddyackerman** [comment]
That's great except that I get the following error:

        Notified of a data change, but the type was not recognised, so no action taken, type was: undefined

I'm executing the following:

        $scope.gridApi.grid.notifyDataChange(uiGridConstants.dataChange.ALL);

I also tried:

        $scope.gridApi.core.notifyDataChange(uiGridConstants.dataChange.ALL);

And, yes, I have uiGridConstants injected into my controller.

**Comment by buddyackerman** [comment]
Good news.  I noticed we were using version 3..0.0-RC.18 and when I updated it to 3.0.7 it starting working.

Thanks.

**Comment by PaulL1** [comment]
That error suggests you didn't include the constants properly or used the wrong name. Set a breakpoint on the code and check the value of the constant.

Sent from my iPhone

On 21 Nov 2015, at 9:40 AM, buddyackerman <notifications@github.com<mailto:notifications@github.com>> wrote:


That's great except that I get the following error:

    Notified of a data change, but the type was not recognised, so no action taken, type was: undefined


I'm executing the following:

    $scope.gridApi.grid.notifyDataChange(uiGridConstants.dataChange.ALL);


I also tried:

    $scope.gridApi.core.notifyDataChange(uiGridConstants.dataChange.ALL);


And, yes, I have uiGridConstants injected into my controller.

-
