### ISSUE TITLE
enableRowHeaderSelection:false prevents grouping checkbox click

### ISSUE THREAD

**Issue by MartijnWelker** [angular-ui/ui-grid#4521]
Disabling enableRowHeaderSelection in gridOptions prevents the grouping checkbox click event because it adds the "Pointer-events: none" css to .ui-grid-cell.ui-grid-disable-selection.ui-grid-row-header-cell

**Comment by srijken** [comment]
@MartijnWelker Is this the problem you're seeing? http://plnkr.co/edit/bytVkH0bM4U3rU4MnNF7?p=preview

**Comment by NewKimAll** [comment]
@sriken This is exactly the issue that I was seeing.
Putting that selector in my own CSS and setting `pointer-events: auto;` worked for me.  Not the ideal solution, but a workaround for now.

**Comment by srijken** [comment]
For completeness a plunk with the workaround: http://plnkr.co/edit/aEHiCpwUoqan52g3Qhcl?p=preview

Thanks!

**Comment by nmorel** [comment]
FYI, it also prevents the row selection on checkbox click when you have both enableFullRowSelection and enableRowHeaderSelection to true.

Here is a plunker : http://plnkr.co/edit/CEKDUU?p=preview

The workaround describes above also fix the issue.

**Comment by mportuga** [comment]
Issue has been fixed in version 4.4.3
