### ISSUE TITLE
Numeric Values in Column sorting as Strings

### ISSUE THREAD

**Issue by DevQueen** [angular-ui/ui-grid#4531]
I have been researching this most of the morning.  I see where others have had this issue but cannot find a definitive solution.  Do I have to write my own function to fix this issue?  I saw where someone said you could define a datatype in the columnDefs but I have been unable to find an example of such.  Thanks for any assistance!

**Comment by PaulL1** [comment]
You can set a type on the columnDef.  It is defined in: http://ui-grid.info/docs/#/api/ui.grid.class:GridOptions.columnDef

**Comment by wesleywarren** [comment]
Tip* You may be getting your JSON from a DB Query in PHP. If PHP is returning a query using **json_encode**, it will quote numbers saved as db type string. Then UI-Grid interprets them as strings EVEN if you have defined the column type as numeric. You can override this json_encode issue using JSON_NUMERIC_CHECK see http://php.net/manual/en/json.constants.php - it will strip the quotes from numerics
