### ISSUE TITLE
bootstarp menu is not working in ui-grid cell

### ISSUE THREAD

**Issue by kunsingh** [angular-ui/ui-grid#4536]
I have a gridOption like:
      {
          field: 'dummy'
          cellTemplate: "table.cell.with.menu.tpl.html",
          enableHiding: false,
          width: '*'
        }
And the table.cell.with.menu.tpl.html is:

&lt;div class="ui-grid-cell-contents dropdown">
    &lt;button class="btn btn-primary dropdown-toggle"
data-toggle="dropdown">Dropdown
        &lt;span class="caret">&lt;/span>&lt;/button>
    &lt;ul class="dropdown-menu">
        &lt;li>&lt;a href="#">HTML&lt;/a>&lt;/li>
        &lt;li>&lt;a href="#">CSS&lt;/a>&lt;/li>
        &lt;li>&lt;a href="#">JavaScript&lt;/a>&lt;/li>
    &lt;/ul>
&lt;/div>

The button is rendered in the cell perfectly ...but when I click on button no menu comes. It seems that it is coming in the background. I tried to set overflow: visible for ui-grid-cell and ui-grid-cell-contents but nothing worked.

**Comment by wesleycho** [comment]
You should try to reproduce this in a Plunker - it would help speed up response.

**Comment by kunsingh** [comment]
I found the solution. It was the style problem. You will have to override below style if you want to show a dropdown in ui-grid cell.
.ui-grid-cell {
  overflow: visible;
}
.dropdown-menu {
  left: unset;
  right: 0;
}
After including above style its working like a charm.
![screen shot 2015-10-20 at 10 02 14 am](https://cloud.githubusercontent.com/assets/5311286/10597948/c4c91e98-7711-11e5-9ff9-fa3adc31ed08.jpg)
