### ISSUE TITLE
Detect keyDown on grid

### ISSUE THREAD

**Issue by Havock94** [angular-ui/ui-grid#4541]
Hi,
I would like to detect a keydown event on the grid.
So far I've found the cellNav.on.viewPortKeyDown event but unfortunately it doesn't work with arrow keys/enter/esc and tab (default navigation buttons).

Is there a way to capture those keys too??
Thank you!

**Comment by dregan-gh** [comment]
We also had this requirement, the only way I could find to handle it was via global keyboard bindings since there isn't a 'html control' element to bind to.

**Comment by fallXone** [comment]
I've created a pull request to resolve this issue that will allow you to override any of the default events that the grid is handling.

**Comment by mportuga** [comment]
Closed by https://github.com/angular-ui/ui-grid/pull/5248
