### ISSUE TITLE
Selection: Checkbox does not select row when enableFullRowSelection: true is set

### ISSUE THREAD

**Issue by wesleycho** [angular-ui/ui-grid#4548]
When `enableFullRowSelection` is set to `true` with the selection module enabled, the checkbox does not allow for selection of the row - this is incongruous with the name, and when combined with the selectAll checkbox enabled, provides a combination that is a poor UX.

Row selection and checkbox selection should be configurable independently, or allow for the sensible combination of selecting either the column or the rest of the row to be the default experience.

Currently the only way to get the desired UX is to not use the selection checkboxes and to create a column in one's app with the checkboxes in a custom column.

**Comment by kolesnik** [comment]
I've expected the same issue in v3.0.7

**Comment by jibap** [comment]
Note that issue is new  in v3.0.7, it wasn't on v3.0.6

I am going to search in commits between 3.0.6 and 3.0.7 to try to resolve

**Comment by ccasad** [comment]
+1

**Comment by kenobi883** [comment]
Just as a note: it seems that a work-around proposed in another issue may work for this one as well: https://github.com/angular-ui/ui-grid/issues/4794#issuecomment-164390041

If it really is just CSS that's causing this, an override will do. I'm not sure that `!important` is necessary from what I have tried, but maybe there is a case for it.

**Comment by sukhoi1** [comment]
I can not select a row by clicking on the checkbox
enableFullRowSelection is set to true

**Comment by gzinger** [comment]
Yes, commented out that style and the problem went away.
Could it cause any other issues? I mean, why was it put there in the first place?

**Comment by easyest** [comment]
Problem still exists in v3.1.1

**Comment by krystian-3c** [comment]
+1
