### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by wesleycho** [angular-ui/ui-grid#4549]
Hello maintainers,

I see that the project has over 700 open issues - we have some pains with UI Grid at my company as well, some due to what I believe are incorrect implementations. In addition, activity with regards to existing issues seems to be very sparse.

Is there a need for help maintaining the project? If so, I am willing to volunteer some assistance with the project - I currently am leading development for [UI Bootstrap](https://github.com/angular-ui/bootstrap), and so have some experience with herculean tasks in turning libraries around. I can also potentially recruit people to assist as well.

If there is interest in my offer, I would need to be brought up to speed - I can be contacted via email as per my profile.

**Comment by PaulL1** [comment]
Wesley,

Yes, we'd love help (as with any project).  @JLLeitschuh has been very active recently, and probably has the best view of where we're at.  I've been offline for a while doing a major project, but that is drawing to a close, so I'll have some time to contribute again.

My observation is that part of the number of open issues is the number of enhancements or unproveable things that we hold open.  If someone suggests something and we think it's a good idea, we tend to leave it open.  That gives an impression of a big number of issues - but the number that are truly defects is typically much smaller.  There are also a lot of usage issues that are going through into the log and not getting closed - that's purely a workforce issue (i.e. time to answer them all).  If we were more active on stackoverflow we could probably be more aggressive in closing them and saying "this is a usage issue, post on stackoverflow".  We'd then build a pool of knowledge on there, which would also be useful.

**Comment by wesleycho** [comment]
What would the best way be for me to be able to start off assisting? If you all are in Slack, I am also found in the Angular Buddies Slack (I know I've seen @c0bra around there - I am also in the #angularjs channel as BahamutWC).

Just let me know so we can get the ball rolling - in the meantime, I can help with issue triaging and close some old/irrelevant issues.

**Comment by swalters** [comment]
Out gitter room is where you will find most of us.https://gitter.im/angular-ui/ui-grid  We can start a another room there if needed for project maintenance talk.  I'm traveling until Thursday of this week, but will be have some time to respond to any questions you might have.

Thanks for the offer. As Paul says, we would love to get some help.

**Comment by c0bra** [comment]
Dittos on thanks for the offer. More help would be great. Speaking for myself, finding regular time to keep up to date with the influx of issues has been pretty much a losing proposition.  It's good that people are using the project but bad that so many of them are needing help that they're not finding via the docs, SO, or another resource.
