### ISSUE TITLE
can not edit cell second time after promising in 'afterCellEdit' event

### ISSUE THREAD

**Issue by kandarpbhesaniya** [angular-ui/ui-grid#4565]
see my plunkr
http://plnkr.co/edit/fkJqM8at8odqXOTYZ8wV?p=preview

i am making some operation after cell edit in $scope.gridOptionsApi.edit.on.afterCellEdit() event
i set setSavePromise here but after that row is not editable more...

i want to edit row second time...

see my plunkr for better understanding

**Comment by michael34** [comment]
I have the same issue. Have you been able to solve it?

**Comment by michael34** [comment]
Ah, I think I solved it. You have to use gridOptionsApi.rowEdit.on.saveRow instead of gridOptionsApi.edit.on.afterCellEdit. See plunker: http://plnkr.co/edit/P0lAKFtaEzaM6hkgcJv9?p=preview

**Comment by michael34** [comment]
Full example with $http:
```javascript
                $scope.gridApi.rowEdit.on.saveRow($scope,
                                (rowEntity, colDef) => {
                                    const promise = $http.post('/Inventar/Update', entity)
                                         .then(function () {                               
                                              },function () {                                
                                         })
                                    $scope.gridApi.rowEdit.setSavePromise(rowEntity, promise);
                                    return promise;
                                });
```
