### ISSUE TITLE
headerTemplate seams not working in subGridOptions

### ISSUE THREAD

**Issue by pierospinelli** [angular-ui/ui-grid#4568]
I am using a grid marked with  ui-grid-expandable

When I set an headerTemplate in a subGridOptions for a sub grid, the title does not appears at all in the subgrid, and I can see just the cell headers.

What is the right way to obtain a custom title in a subgrid?

Tnx 4 any help

**Comment by mportuga** [comment]
Cannot reproduce in the latest version:
http://plnkr.co/edit/oKMBh0ACj5BFrWYOcQhJ?p=preview
