### ISSUE TITLE
AngularStrap tooltip not showing on grid

### ISSUE THREAD

**Issue by ocsike** [angular-ui/ui-grid#4569]
Hi,
I use this this template which is use AngularStrap tooltip:

input class="form-control" type="text" text="" ng-model="email" data-placement="bottom" data-type="info" data-container="body" data-trigger="focus" bs-tooltip="tooltip" 

The tooltip function:
     $scope.tooltip = {
  "title": "Hello Tooltip<br />This is a multiline message!",
  "checked": false
};

The tooltip must be showing when the input get focus.
The tooltip showing when not inside the grid, but when it is inside the grid not shows. No error or something happened.

**Comment by wesleycho** [comment]
Can you reproduce this in a Plunker?

**Comment by ocsike** [comment]
Sorry, I don't use Plunker before. You can download a zip from here: szantai.info/grid.zip  it contain the example,

**Comment by wesleycho** [comment]
We need a stripped down reproduction - downloading a zip is not going to work...that's a lot of work to have to debug through to try to figure out what is wrong, if it is even possible for us.

**Comment by ocsike** [comment]
I've created a plunk http://plnkr.co/edit/rHlAmRe7Z5TxfHIqRBTq?p=preview
