### ISSUE TITLE
How to cancel edit?

### ISSUE THREAD

**Issue by Havock94** [angular-ui/ui-grid#4571]
Hi,
I'm using the editOnFocus feature and I'm having an issue while trying to cancel edit on some cells.
For example I want to skip the second cell of a grid so the user will jump to the third cell of the row after modifying the first one.

I'm doing this by using the scrollToFocus but if the Tab button are pressed the focus goes automatically on the second cell, making it enter deep edit  (due to the editOnFocus). I would like to know how to programmatically cancel the Begin_Cell_Edit event. 

Will someone help me??
Thank you!

**Comment by swalters** [comment]
http://ui-grid.info/docs/#/tutorial/201_editable cellEditableCondition will probably do what you want
