### ISSUE TITLE
Tutorial: 404 Large Data Sets and Performance does not show 640,000 rows?

### ISSUE THREAD

**Issue by sjoerd222888** [angular-ui/ui-grid#4573]
In the tutorial it says there there 640,000 items in the grid. But if you look at the id's there are only 10,000 rows. if you have a look at the http service that is used to retrieve the data (http://ui-grid.info/data/10000_complex.json) you see that the json does only contain 10,000 items.

Where does the number 640,000 displayed at the bottom of the grid come from and how is it related to what is actually displayed.

**Comment by PaulL1** [comment]
It loads 10,000 items, then it doubles them, and doubles them again and so on until there are 640,000 items.

**Comment by sjoerd222888** [comment]
Got it :)

    for( var i=0; i<6; i++){
      data = data.concat(data);
    }

thx
