### ISSUE TITLE
Web page http://angular-ui.github.io/ui-grid/ contains old docs for NG-grid, but "github" button links to ui-grid code, which is confusing

### ISSUE THREAD

**Issue by DarthVanger** [angular-ui/ui-grid#4574]
Address of the page is ".../ui-grid/", but it shows the old docs (examples) for NG-grid, and its "github" button is pointing to ui-grid code.
I have spent some time trying to use those examples, thinking that it was for new UI-grid.

![screenshot_20](https://cloud.githubusercontent.com/assets/6686679/10729657/9ae35512-7bf3-11e5-80b2-c79d876b5c13.png)

Also this page with examples shows up in google, and is kinda confusing too.
![screenshot_21](https://cloud.githubusercontent.com/assets/6686679/10729675/b98f2afe-7bf3-11e5-9f28-1a45401a3927.png)

Please remove "github" link from there, and rename url to "../ng-grid", then it will be clear that this page is all about ng-grid, and not ui-grid!

**Comment by JLLeitschuh** [comment]
@c0bra Perhaps you know who to get in contact with to resolve this?

**Comment by mportuga** [comment]
Old page doesn't exist anymore, so this issue no longer applies.
