### ISSUE TITLE
Changing the cell border color

### ISSUE THREAD

**Issue by sonnyk22** [angular-ui/ui-grid#4579]
Is there a function or a way to change the active cell border color to a non-default color such as red, as shown below?  Also, to toggle back to the default color?  This will be helpful for displaying cells with invalid data.

Something like: grid.changeActiveCellBorderColor('#color')

![grid2](https://cloud.githubusercontent.com/assets/6744710/10740870/01a8e652-7bfb-11e5-8e96-4209d966f19f.png)

**Comment by rameshkumarsme** [comment]
custom.css:
.highlight { border-right: 1px solid; border-left: 1px solid; border-top: 1px solid; border-bottom: 1px solid; border-color: red !important; }

controller.js:

$scope.columns = [
			 { field: 'Name', displayName: 'Full Name', minWidth:25, cellClass: function(grid, row, col, rowRenderIndex, colRenderIndex) {
                        if (grid.getCellValue(row,col) === '2.71828182846') { /* change this condition based on requirement like >2 etc., */
                            return 'highlight';
                            
                        }
                        }}
}

**Comment by alexey-vasyunin** [comment]
Are there access to cell object to set own style?  For example, some js-script on page has eventlistener and it change random cell in the grid...  I mean that I want to control rows and cells not statically from template. Something like this:

var $scope = angular.element($("#checkedrequestgrid")).scope();
$scope.gridApi.grid.rows[5].entity.cellstyle(4, 'blueborder');
