### ISSUE TITLE
Remove code triggering scroll on each menu select

### ISSUE THREAD

**Issue by tirithen** [angular-ui/ui-grid#4581]
Each time toggling column visibility with the top right menu the menu is scrolled to the top. This gets impossibly annoying when having 20+ menu items. I made a PR for this here https://github.com/angular-ui/ui-grid/pull/4575 .

**Comment by fallXone** [comment]
Is there any update on this issue...?

**Comment by fallXone** [comment]
@mportuga  was this actually fixed by something?

**Comment by mportuga** [comment]
It was fixed by the following PR: https://github.com/angular-ui/ui-grid/pull/5946
