### ISSUE TITLE
When a column is hidden, it's filter still remains active without visual indication that is is active

### ISSUE THREAD

**Issue by tirithen** [angular-ui/ui-grid#4582]
If I filter a column and then hides it, the table is still filtered by that column filter, still there is no visuals indicating that filter exists. Either the filter should be removed when a column is hidden or all active filters on hidden columns should be visible somewhere.

To me the solution with removing a filter once a column is hidden seem like the easiest to understand and also easiest to implement.

I tried searching for this but failed to find any documentation or issues regarding this.

**Comment by mportuga** [comment]
While I agree that the easiest solution to understand is to remove a filter once the column is hidden, that would be a drastic change in behavior to what we have today. So perhaps we need to come up with a solution that shows filter information elsewhere when a column is hidden.

**Comment by mportuga** [comment]
Actually, both of the behaviors described above are possible today. See plunkers bellow:

* Remove filters: http://plnkr.co/edit/fdSXhDjpOBsTBLbiaEOA?p=preview
* Show filters for hidden columns: http://plnkr.co/edit/74QrAyDILGg3Yz9tqH7h?p=preview

So I do not believe this is a valid issue.
