### ISSUE TITLE
Dropdown in a celltemplate in AngularJS ui-grid

### ISSUE THREAD

**Issue by aksharak** [angular-ui/ui-grid#4584]
I have a grid and in 1 column am only getting 2 values. Either closed or Open. currently it is a normal grid so the user can enter any value. I want to force the user in selecting either Open or Closed from a dropdown rather than him typing. Also i have that grid pre-populated. So already few rows will have values as Closed or Open. So i want the dropdown to have the value as Closed or Open, based on the values coming in JSON when the grid loads. Please help. Thanks.

**Comment by imbalind** [comment]
This is what edit feature is about. Take a look at this [tutorial page](http://ui-grid.info/docs/#/tutorial/201_editable)

**Comment by hemalatha81** [comment]
I am trying to insert the uib dropdown in the column but the dropdown is not opening when we click on the dropdown icon Can you please help me
