### ISSUE TITLE
On Disabling row select i want to disable the edit option in that row. 

### ISSUE THREAD

**Issue by vaibhavchandra** [angular-ui/ui-grid#4592]
I disable rows upon particular results i cannot select them but they are still editable i have a dropwdown. User can change the value just cannot select the row i want to restrict the row editing as well.

**Comment by imbalind** [comment]
This is what cellEditableCondition is for. Take a look at [the API](http://ui-grid.info/docs/#/api/ui.grid.edit.api:ColumnDef).

I'm closing this since it is not a bug.
