### ISSUE TITLE
Disproportionately large table header

### ISSUE THREAD

**Issue by t638403** [angular-ui/ui-grid#4595]
I'm working on a project with an existing code base in which I have tried to embed ui grid. In this project the header of the ui grid is really large. My guess is that there exists some weird css in the project that triggers this behaviour, but I have not been able to pin it down. The grid simply works if I embed it in any other project. For this reason I can not provide a plunker. I have found a workaround however. I thought I post it here. It doesn't seem to affect the plugin in a bad way.

```
.ui-grid-contents-wrapper {
	height: auto;
}
.ui-grid-header-cell-wrapper {
	height: auto;
}
```

**Comment by imbalind** [comment]
I'm closing this since not an actual bug.
