### ISSUE TITLE
Trying to set row to top of grid

### ISSUE THREAD

**Issue by rmechamatadobe** [angular-ui/ui-grid#4599]
We're using the latest version of ui-grid.

On a master grid we click on a cell which pops up another ui-grid on top of the master ui-grid display some master-detail information.

We'd like to be able to scroll the clicked on link to the top in the master grid so it would always be visible when the detail grid is up.

I've seen some solutions using the viewport height and row heights with some math and then using the scrollTo functions to achieve something like this but what I've failing to see is how you get the Y position from the top of the viewport for the selected/clicked on cell/row.

Initial Grid State:
Top of Grid
1
2
3
4
5         Click on this cell.  (How do I get its y POS within the view port.) 
6
7
8
9
10
Bottom of Grid

Anticipated Grid State:
Top of Grid
5         Click on this cell.
6
7
8
9
10
Bottom of Grid

Any help would be greatly appreciated.

Feel free to send a response to rmecham@adobe.com as well.

**Comment by rmechamatadobe** [comment]
Some more info:
I've looked at this posts:
https://github.com/angular-ui/ui-grid/issues/3153

And we are using the infinite scroll option so I tried using the infiniteScrollService.adjustInfiniteScrollPosition function, which I believe I could get to work if I knew they Y position, or index from the top of the viewport for of the clicked on master grid cell/row.

**Comment by rmechamatadobe** [comment]
I was hoping that the visible flag in the row cache would really indicate whether or not the row was visible to the end user, but no luck.  My view port shows about 30 rows and my cache 200 rows and I looked at the visible flag of row 190, which is not really "visible" in the viewport, but it states that it is visible.

linkedFromGridGrid.renderContainers.body.visibleRowCache[190] = see screenshot

![screen shot 2015-10-29 at 2 57 35 pm](https://cloud.githubusercontent.com/assets/14283169/10831859/a3cc6ffe-7e4d-11e5-9244-dd5e71aa276a.png)

**Comment by PaulL1** [comment]
The visible flag indicates whether or not a row is or could be visible - ie it's not hidden, and if the user scrolls they would see the row.  There isn't an exposed method to see rows that are currently displayed on the screen.

**Comment by rmechamatadobe** [comment]
Thank you for the feedback.  Given what you've described is there any way to always scroll the "clicked on" row either at the top or bottom of the "displayed (visibile on the screen)" grid rows?  If I could achieve this then I could put a child/detail grid that's centered on top of the master grid and the the child/detail grid could be fairly large without overwriting the "linked from" cell.  Thank you in advance for any direction you can provide and have a wonderful day.

**Comment by rmechamatadobe** [comment]
Found a solution that doesn't require a rowTemplate:

Simply remove the grid selection functionality, on my amo-grid element I just remove the ui-grid-selection attribute and all is well at least for my application. 

In my wrapper directive:
    function AmoGrid($window) {
        return {
            restrict: 'E',
            template: '<div ng-include="vm.getTemplateUrl()"></div>',
            scope: {
                gridOptions: '=', // see http://ui-grid.info/docs/#/api/ui.grid.class:GridOptions for available gridOptions
                layout: '@',
                gridHeight: '@',
                gridId: '@',
                disableUiGridSelection: "@"
            },
            link: AmoGridLink,
            controller: AmoGridController,
            controllerAs: 'vm',
            bindToController: true,
            transclude: true
        };

In my directive controller:
            function getTemplateUrl() {
                var retValue = 'components/shared/amoGridDirective/amoGridTemplate.html';
                if (vm.disableUiGridSelection) {
                    retValue = 'components/shared/amoGridDirective/amoGridTemplateNoGridSelection.html';
                }
                return retValue;
            }

One template has the ui-grid-selection attribute the other does not:
This:
        <div ui-grid="vm.gridOptions" id="{{vm.gridId}}"
             ng-style="vm.dimensions"
             ui-grid-edit
             ui-grid-selection
             ui-grid-cellNav
             ui-grid-resize-columns
             ui-grid-move-columns
             ui-grid-auto-resize
             ui-grid-infinite-scroll>
        </div>

VS this
        <div ui-grid="vm.gridOptions" id="{{vm.gridId}}"
             ng-style="vm.dimensions"
             ui-grid-edit
             ui-grid-cellNav
             ui-grid-resize-columns
             ui-grid-move-columns
             ui-grid-auto-resize
             ui-grid-infinite-scroll>
        </div>

**Comment by niranjanpawar7** [comment]
working on ui-grid i want add scroll-bar on top of grid but ui-grid-viewport is after heading so i am not able to do set scroll top please help...
![test](https://user-images.githubusercontent.com/20677712/28308987-8cc323c2-6bc5-11e7-8b8d-04bf1335b773.png)

**Comment by niranjanpawar7** [comment]
is there any option in Ui-grid where i can set two scroll bar 1 for top and 1 for bottom..
