### ISSUE TITLE
cambiar el displayName dinamicamente

### ISSUE THREAD

**Issue by juancol88** [angular-ui/ui-grid#4600]
Cheers,

Currently I have a question and do not get this with the library and the following:
columnDefs: [
   {Field: 'Id' displayName 'Ids' ....}
]

change the displayName as achievement worth coming in or json data that populates the grid, and try dynamically allocating it with a foreach but sack several errors of this kind Error: colDef.name or property is required colDef.field

As you can be changed dynamically in a giant diplayName Json.

**Comment by PaulL1** [comment]
Is that content as you have it in your code?  If so, field is lower case, and you need a comma:

```
columnDefs: [
   {field: 'Id', displayName 'Ids' ....}
]
```

You always have to have a field or a name for every column, so if you used Field instead of field then that matches the error message.

**Comment by juancol88** [comment]
Sorry, it was a typing error in the post but I have correctly, my problem is the displayName property you must concatenate a date that is in json or data that populates the grid, the problem is that as not to add that date this in my json on displayName property.

**Comment by PaulL1** [comment]
I think you probably will need to provide a plunker then, as the problem sounds like it relates to code that you haven't provided an example of.

**Comment by juancol88** [comment]
http://run.plnkr.co/z444rYtoPmkzJKbK/

Thanks for answering, and believes the plunker example, my problem is that I have the following json:

 $ Scope.myData = {
          Id: "1103"
          fechaP0: 1441083600000,
          fechaP1: 1443675600000,
          fechaP2: 1446354000000,
          fechaP3: 1448946000000,
          fechaP4: 1451624400000,
          fechaR0: 1427864400000,
          fechaR1: 1430456400000,
          fechaR2: 1433134800000,
          fechaR3: 1435726800000,
          fechaR4: 1438405200000,
          nombreCategoria "ACCESSORIES"
          nombreReferencia "PROGRIP ART GLASS"
          p0: 0
          p1: 0
          p2: 0
          p3: 0
          p4: 0
          r0: 0
          r1: 0
          r2: 0
          r3: 0
          r4: 0
        }

All fields are well on the grid but my requirement is that the fechaP0 and fechaP1 field should be part of the display name. something like this I want, but not how.

$scope.gridOptions = {
        enableSorting: true,
        columnDefs: [{
             field: 'p0' Save 'Test 1' + 'fechaP0'
        }]
}

What I want to know is how to concatenate coming from my json on displayName.

**Comment by PaulL1** [comment]
How would this work when you have multiple rows?  It seems like you're trying to put a value from a single row into your header.....but which row?

If you only ever have one row, then I can see how this would work, but otherwise I'm a bit confused.

In general terms you can update the displayName after the grid renders by directly updating col.displayName (rather than colDef.displayName), but once I understand what you're trying to achieve I can probably help more.

**Comment by juancol88** [comment]
Thank you for responding, I want to make is that the displayName than a value that this preset in the options grid manually, if not that is a dynamic value that I would be assigned to the other side as a json or object.

**Comment by PaulL1** [comment]
OK, so if I'm interpreting correctly, you want some information coming back from the server that you use in the displayName, but it's not necessarily data from the rows.  

Try this plunker then:
http://plnkr.co/edit/9YrC57hDzLfL1JEsW7kI?p=preview

**Comment by juancol88** [comment]
Thanks for the help, this was what he wanted.
