### ISSUE TITLE
Missing icons in unminified CSS?

### ISSUE THREAD

**Issue by JayHuang** [angular-ui/ui-grid#4601]
Not sure if it's just me, but when I build the latest source, and grab the CSS from dist/release, the grid is missing all icons. Tried rebuilding multiple times, until I noticed that the minified CSS worked fine.

For example: `.ui-grid-icon-spin5:before{content:'\ea61'}` is in the minified CSS, but not in the unminified one.

**Comment by BerndWessels** [comment]
Hi @JayHuang 
That might be related to [this issue](https://github.com/angular-ui/ui-grid/issues/4658).
The icons are not defined anywhere in the current less files.
Cheers
Bernd

**Comment by mportuga** [comment]
This should be resolved in the latest version.
