### ISSUE TITLE
Fire a click event on headerCellTemplate

### ISSUE THREAD

**Issue by henry49100** [angular-ui/ui-grid#4602]
Hi 

I picked-up the tree-grid-view example and I made a column with checkboxes. I have now an issue and I really don't know what is the solution. 

![image](https://cloud.githubusercontent.com/assets/15050186/10842047/f27b8242-7eee-11e5-85e0-1e21dd70e6b3.png)

On the header row, I also put a checkbox that allows the user to check all the rows in the table. The result should be a whole checked check-box column. But it appears the ng-click event in the headerCellTemplate that I defined is not fired. Even if the event function may not have the right behaviour, I don't understand why this event is not fired. 

![image](https://cloud.githubusercontent.com/assets/15050186/10842205/18f054ec-7ef0-11e5-82ad-c4edf02fd857.png)

Can someone help me? Here's the plunker below, thanks in advance

http://plnkr.co/edit/HPECpegXmBE1duH6dve0?p=preview

**Comment by henry49100** [comment]
I'm really stupid, I just wrote "appScop" instead of "appScope" ! 

Really stupid indeed!

**Comment by imbalind** [comment]
I'm closing since the problem seems solved.
