### ISSUE TITLE
Angular ui grid treeview :-  Issue with all parent is automatically go  as a first child

### ISSUE THREAD

**Issue by dilip-borad** [angular-ui/ui-grid#4605]
First please check my this plunk
http://plnkr.co/edit/gA0vRP?p=preview

Like i've use exact guidelines and follows all instructions from Angular ui treeview.
All things is working proper but i need a different output rather than current one.

Currently on my data object i've set first "2627" one has a two childs[3601, 3602], so first one is looks like ok for me.
Then the second row "3226" is automatically come under as child of first row "2627".
But actually the second row not has any child so i think by default it's a parent right ?

When i've change the order of rows( Like swap full row "2627" as second row ) from my data object then first row is looks fine and then rest of all other parent which not has child element is comes under "2627".

I think you can understand my concern, about what i actually need.

Let me know if anything i've missed ?

**Comment by tringuyenminh92** [comment]
i think it would be better if you set level for you items. for ur example:
[{
      "id": 2627,
      "client_id": 182,
      "hasChild": true,
      "level": 1
    }, {
      "id": 3601,
      "client_id": 182,
      "parent_id": 2627,
      "level": 2
    }, {
      "id": 3602,
      "client_id": 182,
      "parent_id": 2627,
      "level": 2
    }, {
      "id": 3226,
      "client_id": 182,
      "level": 1
    }];

angular.forEach(data, function (item) {
                        //assign level by LeftValue
                        item.$$treeLevel = item.NodeLevel;
                    });
 $scope.gridOptions.data = data;
