### ISSUE TITLE
Edit On Focus and first/last row problem

### ISSUE THREAD

**Issue by Havock94** [angular-ui/ui-grid#4606]
Hi,
I'm having a problem with edit on focus enabled and the user reaches the first or the last cell.
The issue is easily reproducible. 

[http://ui-grid.info/docs/#/tutorial/301_editableOnFocus](Edit on focus)

Focus the address.city column so that you enter focus, reach the last cell and press the down arrow (or reach the first and press the up arrow)

The cell will leave edit mode.
Now try to press any key to enter edit mode again -> It will fail even if the cell is still focused (ui-grid-cell-focus).

How can this be fixed?

**Comment by mportuga** [comment]
No longer reproducible on latest version

**Comment by piyush21upadhyay** [comment]
Hi @Havock94 / @mportuga , 

I'm using ui grid-3.2.5 and facing the same issue while editing the last cell. I have added _clearFocusAfterEdit: true_ to gridOptions but it didn't work out. Do i need to make changes anywhere else? If you have any working example link/plunkr/code snippet that would be really helpful. Thanks.
