### ISSUE TITLE
Bug: when selection: true + grouping

### ISSUE THREAD

**Issue by billyaraujo** [angular-ui/ui-grid#4607]
When  selection is set to true, the grouping expand/collapse doesn't work properly.

http://plnkr.co/edit/6LlaQrXSnxhADTUOYfvJ?p=preview

If this isn't supported should give warning or something.

**Comment by billyaraujo** [comment]
If this isn't supported should give warning or something.

**Comment by swalters** [comment]
It works properly in this tutorial. Group on something and you can see it work.  Can you compare your gridOptions to this tutorial?  http://ui-grid.info/docs/#/tutorial/401_AllFeatures

**Comment by billyaraujo** [comment]
enableRowHeaderSelection: false,

**Comment by friedbizkvit** [comment]
"enableFullRowSelection: false" helps, but in my case i need full row selection to be enabled.

**Comment by billyaraujo** [comment]
me too.

**Comment by nickxbs** [comment]
The event is disabled by the selector ` .ui-grid-cell.ui-grid-disable-selection.ui-grid-row-header-cell{pointer-events: none;}`

**Comment by imbalind** [comment]
This also happens for selection header.

**Comment by billyaraujo** [comment]
Why is this closed?

**Comment by PaulL1** [comment]
It's not.

**Comment by billyaraujo** [comment]
Oh my bad. Sorry. Saw the close tag and thought it was.

**Comment by sreekumarp** [comment]
@bgou: is #4607 (current issue) is also resolved by @4693 fix ?
If yes any idea when this will be released ?

**Comment by bgou** [comment]
@sreekumarp I don't think this issue (#4607) is resolved yet. My reported issue (#4693) was closed as a duplicate to this one.

**Comment by fk-mbc** [comment]
I have the same problem: http://plnkr.co/edit/TLilMmj3yWnyOaDStVU9?p=preview
When i use suggested solution with enableRowHeaderSelection: false then i can open the groups, but doesn't have the ability to select a row on click.

**Comment by benjamin-wilson** [comment]
Proposed a fix: https://github.com/angular-ui/ui-grid/pull/4760

**Comment by imbalind** [comment]
Merged with commit f715767
