### ISSUE TITLE
gridrowSelectionChanged fires on swipe using iPAD, it is expected to fire only on click 

### ISSUE THREAD

**Issue by hp1983GIT** [angular-ui/ui-grid#4608]
we are using rowselectionchanged event to capture row-click to take further action which navigates to another page.

But on iPAD, even on swipe this rowselectionchanged event is fired. Due to this scrolling of the grid on iPAD has become cumbersome.

Please fix the code to identify swipe action and do not trigger rowselectionChanged event.

When I use ng-click on ui-grid-row, swipe doesn't invoke click event handler. So it works with ng-click.

Not sure what is wrong with rowselectionChanged event as I thought it is implicitly created on top of click event.

**Comment by Mooser** [comment]
I have seen this on every single iOS device I've looked at.

**Comment by MichalJakubeczy** [comment]
Temporary workaround is to use custom rowTemplate where you bind ng-click event to your controller's method and invoke select by calling gridApi method.

**Comment by pbrain19** [comment]
Anyone found a long term solution to this?

**Comment by yogeshgadge** [comment]
Just use a directive for the row and use click binding - get that scope and call it a day.
