### ISSUE TITLE
Custom Menu

### ISSUE THREAD

**Issue by JosephOR** [angular-ui/ui-grid#4609]
Hi, sorry this isn't the best place to ask but I've searched stack to no avail. 
What I am looking for is a way to customise the grid menu. the default, with some modifications can be found here http://ui-grid.info/docs/#/tutorial/121_grid_menu

what I am looking for though is a total custom menu, for example have a modal appear with the fields i can show or hide. Is there a way to make a custom menu using ui-grid? or is this something I would have to build from scratch?

Thanks,
joseph

**Comment by swalters** [comment]
you would have to build it as part of your application and make the needed calls to ui-grid
