### ISSUE TITLE
Responsive design using ng grid

### ISSUE THREAD

**Issue by rbansalit** [angular-ui/ui-grid#461]
How can we make ng grid responsive. So that it should be able to display proper on desktop as well as mobile.

**Comment by awerlang** [comment]
+1 for stacked columns as default.

>If someone is looking at a row as a complete record, then the stacked approach is fine, but if you're comparing fields across rows (looking for a security with a specific set of criteria) then it's not.

Wouldn't it be case for a grouping + drill-down? Or color-coding column content?

Anyways, having devices adapted for people (even excel people) is counterproductive, IMHO.

**Comment by tuhoojabotti** [comment]
I also vote for stacked columns plugin or built-in.

**Comment by ralberts** [comment]
+1 :-)
