### ISSUE TITLE
OnRegisterApi not being called?

### ISSUE THREAD

**Issue by brechang** [angular-ui/ui-grid#4619]
I have a modal that I want to display pre-selected rows in. However, I keep getting a 'cannot read 'grid' of undefined' error. The UI Grids are defined within the modal, and I declare two Grid Apis with two different names. I set breakpoints at OnRegisterApi, but for some reason the code skips over them. Here is what my code looks like: 

This launches the modal:

```
//edit user group
$scope.editSelectedGroup = function(){
    //get the selected row
    var row = $scope.gridApiInfo.selection.getSelectedRows();

    var modalInstance = $modal.open({
        animation: true,
        templateUrl: 'userGroupModal.html',
        controller: 'UserGroupModalController',
        resolve: {
            modalTitle: function () {
                return "Edit User Group"
            },
            allDepartments: function () {
                return $scope.allDepartments;
            },
            allRegions: function() {
                return $scope.allRegions;
            },
            isEdit: function(){
                return true;
            },
            row: function(){
                return row[0];
            }
        }
    });
```

Here is the relevant ModalController code

```
.controller('UserGroupModalController',function($scope,$modalInstance,$modal,$window,modalTitle,allDepartments,allRegions,isEdit,row,referenceDataService){

$scope.modalTitle = modalTitle;
$scope.isEdit = isEdit;
$scope.allDepartments= allDepartments;
$scope.allRegions = allRegions;

$scope.form= {
    value: "",
    description: "",
    departments: [],
    regions: []
};

$scope.departmentsGrid = {
    enableRowSelection: true,
    multiSelect: true,
    enableRowHeaderSelection: false,
    onRegisterApi: function(gridApi) { 
        $scope.deptGridApi= gridApi;
    },
    columnDefs: [
        {name: 'Name', field: 'name'}
    ],
    data: $scope.allDepartments
};

$scope.regionsGrid = {
    enableRowSelection: true,
    multiSelect: true,
    enableRowHeaderSelection: false,
    onRegisterApi: function(gridApi) {
        $scope.gridApiRegions = gridApi;
    },
    columnDefs: [
        {name: 'Name', field: 'name'}
    ],
    data: $scope.allRegions
};

if ($scope.isEdit){
    $scope.form.value = row.value;
    $scope.form.description = row.description;

    //pushing selected depts
    angular.forEach(row.departments, function(department) {
        var deptElementPos=angular.findIndexOf($scope.allDepartments, department.id);
        $scope.form.departments.push($scope.allDepartments[deptElementPos]);
    });

    //pushing selected regions
    angular.forEach(row.regions, function(region) {
        var regionElementPos=angular.findIndexOf($scope.allRegions, region.id);
        $scope.form.regions.push($scope.allRegions[regionElementPos]);
    });

    //setting pre-selected rows
    angular.forEach($scope.form.departments, function(department) {
        $scope.deptGridApi.grid.rows.map(function (row) {
            if (row.entity.id == department.id) {
                row.setSelected(true);
                $log.log("row selected: " + row.entity.id);
            }
        });
    });

    angular.forEach($scope.form.regions, function(region) {
        $scope.gridApiRegions.grid.rows.map(function (row) {
            if (row.entity.id == region.id) {
                row.setSelected(true);
                $log.log("row selected region: " + row.entity.id);
            }
        });
    });

    $scope.form.id = row.id;
}
```

})

When I click the button to launch the modal, no modal shows up - instead I get a console error saying that it 'Cannot read property 'grid' of undefined' at the line with $scope.deptGridApi.grid.rows.map, and as mentioned earlier OnRegisterApi is not being hit. Anyone have any advice? Thank you!

**Comment by imbalind** [comment]
Can you provide a plunkr? Without it it's very time consuming to address this kind of situations.

**Comment by billyaraujo** [comment]
This happens to me a lot. If I have a grid in a tab (for ex. tab#2) and tab#1 is showed on load, OnRegisterApi isn't called although I am already setting data to ui-grid so it is ready when the tab is clicked.

**Comment by gkdagk** [comment]
Same issue for me. OnRegisterApi is not called. The grid is binded, but the rows are not visible, but the footer shows item count and pagination

**Comment by codyhazelwood** [comment]
+1  This issue occurs if you follow the Angular 1.5 example for building tabs with components and then add the UI-Grid to a tab (even if it is loaded in the first tab).

**Comment by dreaddy** [comment]
Frustrated. Is there a working example somewhere?

**Comment by scicompth** [comment]
+1. This issue occurs to me only first time when i try to open the grid in a ui-bootstrap modal. From second time, it works well.

**Comment by Ton024** [comment]
I've got the same problem. When using Ui grid as a controller it is working. If I use it as a directive with isolated scope:
                               onRegisterApi: function (gridApi) {
                                    alert('x');
                                    $scope.gridApi = gridApi;
                                },
OnRegisterApi is not being called.

The reason of using it as a directive is to avoid double code for all other instances I'm using ui Grid for.

**Comment by mportuga** [comment]
@Ton024 can you provide a plunker demonstrating the issue?

**Comment by Ton024** [comment]
http://plnkr.co/edit/5sBVi0M9QCxdE1WrTNja?p=preview 
It was great reproducing this behavior to find out is was working ! Yeahhhh

So what I did was to use the 'modified'version from pluncker in my project. I do not know how it is done but, the trick could be to set:
                $scope.gridOptions = {
                        enableSorting: true,
                        columnDefs: heading,
                        data: list,
                        minRowsToShow: 12,
                        excessRows: 20,
                        multiSelect: false,
                        displaySelectionCheckbox: false,//;$scope.datagrid.select,
                        showGridFooter: true,
                        enableHorizontalScrollbar: 2,
                        enableVerticalScrollbar: 2,
                        onRegisterApi: function (gridApi) {
                            alert('x');
                            $scope.gridApi = gridApi;
                        },
                        appScopeProvider: $scope.myAppScopeProvider,
                        rowTemplate: "<div ng-click=\"grid.appScope.iconClicked()\"  ng-dblclick=\"grid.appScope.showInfo(row)\" ng-repeat=\"(colRenderIndex, col) in colContainer.renderedColumns track by col.colDef.name\" class=\"ui-grid-cell\" ng-class=\"{ 'ui-grid-row-header-cell': col.isRowHeader }\" ui-grid-cell></div>"
                    };
    first with list = [], just like heading=[] and then get the data and set list and heading. During the empty list the alert from within onRegisterApi was called. This gave me the clickevent on a row.

This issue can be closed! Reproduction is essentional!

**Comment by Ton024** [comment]
I have to say that using ui grid in a directive with isolated scope is in the first call succesfull. But when I change the variable's in the main controller there is no response in the grid directive:
            scope:
                {
                    datagrid: '=',
                    datalist: '=',
                    go: '@'
                },
 
In fact using a variable as go, after updating datgrid and datalist which are holding the data and grid parameters, an error occurs when trying to use $watch. I did solve it though. Using the broadcast feature within angular:
The main controller uses:
                    var msg = 'verkennergrid';
                    $rootScope.$broadcast(msg,dataList);

In the directive I listen to:
               scope.$on('verkennergrid', function (evt, data) {

Which starts the function to get the data from a webservice and handle it to the controller.

This works great.
