### ISSUE TITLE
Custom language template

### ISSUE THREAD

**Issue by sMoKeSz** [angular-ui/ui-grid#4632]
Hello, I don't know that this is an actual issue , or it was resolved but I'm asking if i can using an custom language template for the ui-grid. i want to use romanian and you don't have a translation for this yet, can i make a custom template and use it with the " i18nService.setCurrentLang('ro') "

**Comment by JLLeitschuh** [comment]
Yes. If you want to make it public then please consider opening a PR.
You could add it to the list of files here: https://github.com/angular-ui/ui-grid/tree/master/src/js/i18n

**Comment by sMoKeSz** [comment]
hello i need some help . what branch i need to fork ? and after i fork and push the file how can i merge with ur branch ?

**Comment by imbalind** [comment]
Merged in commit d619ad
