### ISSUE TITLE
Selection feature : selectAllVisibleRows()

### ISSUE THREAD

**Issue by kefengdeng-ibboost** [angular-ui/ui-grid#4633]
I am currently working on my customised selection header, which does select/unselect all by click event.

However, when I click on it, it calls "gridApi.selection.selectAllvisibleRows()", and highlight all rows in current render canvas. But the grid.selection.selectedCount is the total rows size, instead of total visible rows (the grid have 500 rows totally, and paginationPageSize is 50).

I am not sure whether it is a bug or I did something wrong.

Cheers

**Comment by imbalind** [comment]
Could you please reproduce this behaviour in a [plunkr](plnkr.co)?

**Comment by kefengdeng-ibboost** [comment]
After few times try, I might understand the method better. 

From my understanding, selectAllVisibleRows() will select all rows after filter, and selectAllRows() will select all rows without count filter conditions. If I am correct, this question is not a bug. 

Cheers

**Comment by imbalind** [comment]
Yes, I confirm visible in UI-grid means theoretically visible i.e. not filtered.

I'm closing this
