### ISSUE TITLE
Editing last row doesn't work correctly with dropdownEditor

### ISSUE THREAD

**Issue by dejvo** [angular-ui/ui-grid#4634]
version: 3.0.7
plunker: http://plnkr.co/edit/K9HZAXRchF6hbO3d3Zaw?p=preview

It is not possible to edit 'Gender' in the last row.
It works correctly if horizontal scrollbar is enabled.

**Comment by imbalind** [comment]
The bug seems related to navigation, even if this is obviously not a solution, you could just remove it if not needed.

**Comment by dejvo** [comment]
Yes, if navigation is not used it works, but I need the navigation.

**Comment by dalbir** [comment]
same problem here, but with first row

**Comment by dalbir** [comment]
I have find the solution - set the rowHeight that is comfort for dropdown

**Comment by dejvo** [comment]
Changing rowHeight doesn't seem to help. Can you create plunker?

**Comment by dalbir** [comment]
At that its not possible . Check with default row height and width. 

Good night

-----Original Message-----

**Comment by imbalind** [comment]
Maybe the problem is similar to the issue #4422 we had and that was closed.

**Comment by frankdenouter** [comment]
Problem still occurs on first row when rowHeight set smaller than 30px

**Comment by dejvo** [comment]
Solved in version 3.1.0 :-)
