### ISSUE TITLE
rowTemplate for tree view '+' column duplicity

### ISSUE THREAD

**Issue by dorrotman** [angular-ui/ui-grid#4638]
Hi,
I am using a custom rowTemplate very similar to the sample: http://ui-grid.info/docs/#/tutorial/317_custom_templates

However, on a row that should display a message and not the columns, I am seeing the message twice: Once in the row header (where the '+' sign is), and the other in the row itself to the right. It seems that the row header is processed as a different row with its own different columns.

Is there any way to detect within the custom row template that I am running as a header row template and ignore my message?

Plunker: http://plnkr.co/edit/osx29y9zsNft5pdunRfQ?p=preview

Thanks!

**Comment by PaulL1** [comment]
Yes, and I thought it was in one of the tutorials, but I can't see it easily.

You need to do an ng-if in your template, and you check for renderContainer == 'body' - but I can't remember the exact syntax to get at renderContainer from a cell, and need to go to work.  I can look later today, or you can google around a bit to see if you can find it.
