### ISSUE TITLE
Column not hiding 

### ISSUE THREAD

**Issue by gkdagk** [angular-ui/ui-grid#4642]
In this fiddle http://jsfiddle.net/kashjs/gt8Ljspf/ 
i have tried $scope.carsTableColumnDefinition[0].visible=false;
But it's not hiding.. Please guide me

**Comment by imbalind** [comment]
I'm afraid this is not the repository you are looking for.

Adapt-strap repository is [here](https://github.com/Adaptv/adapt-strap).
