### ISSUE TITLE
Editing ends when arrow keys are pressed (with cellnav enabled)

### ISSUE THREAD

**Issue by Bv202** [angular-ui/ui-grid#4644]
Hey,

I have another annoying issue...

The documentation clearly states:
"When combined with the editable feature, the left-right arrow keys will be subsumed when in "deep edit" mode, allowing you to move around within the text you're editing."

This doesn't seem to work. When an arrow key (left or right) is pressed, the editing ends and navigation to another cell happens.

Do I change this behavior?

**Comment by imbalind** [comment]
The key point here is "deep edit", although not much documented.

If you click another time on an already editable cell, you enter deep edit mode (you can say you are in deep edit mode if scroll bars disappear). 

I can confirm that if you are in "deep edit" behaviour is as expected, so I'm going to close this.
