### ISSUE TITLE
Cursor gets stuck in noneditable

### ISSUE THREAD

**Issue by ManojSridhar** [angular-ui/ui-grid#4647]
I have a div with data-mce-contenteditable set to false. I have image tag inside it. The cursor gets strucked inside the div and cannot add text in the tinymce once I select that div. The same issue is posted in http://www.tinymce.com/develop/bugtracker_view.php?id=5698 but no solution has been proposed yet. Please suggest any workaround for this issue.

**Comment by imbalind** [comment]
Is this related to ui-grid?

**Comment by ManojSridhar** [comment]
This is tinymce issue.  Mistakenly posted in ui-grid repository.
