### ISSUE TITLE
icons not defined in less files?

### ISSUE THREAD

**Issue by BerndWessels** [angular-ui/ui-grid#4658]
Hello
It seems that the icon definitions are not part of the ui-grid less files. Why is that? In my projects I only use less files and wanted to `@import '~angular-ui-grid/less/main.less';`. But to get that working I have to manually extract the icons from the `ui-grid.css` and add them to my own less files:

```
.ui-grid-tree-header-row {
font-weight: bold !important;
}

.ui-grid-icon-plus-squared:before {
content: '\c350';
}
/* '썐' */
.ui-grid-icon-minus-squared:before {
content: '\c351';
}
/* '썑' */
.ui-grid-icon-search:before {
content: '\c352';
}
/* '썒' */
.ui-grid-icon-cancel:before {
content: '\c353';
}
/* '썓' */
.ui-grid-icon-info-circled:before {
content: '\c354';
}
/* '썔' */
.ui-grid-icon-lock:before {
content: '\c355';
}
/* '썕' */
.ui-grid-icon-lock-open:before {
content: '\c356';
}
/* '썖' */
.ui-grid-icon-pencil:before {
content: '\c357';
}
/* '썗' */
.ui-grid-icon-down-dir:before {
content: '\c358';
}
/* '썘' */
.ui-grid-icon-up-dir:before {
content: '\c359';
}
/* '썙' */
.ui-grid-icon-left-dir:before {
content: '\c35a';
}
/* '썚' */
.ui-grid-icon-right-dir:before {
content: '\c35b';
}
/* '썛' */
.ui-grid-icon-left-open:before {
content: '\c35c';
}
/* '썜' */
.ui-grid-icon-right-open:before {
content: '\c35d';
}
/* '썝' */
.ui-grid-icon-angle-down:before {
content: '\c35e';
}
/* '썞' */
.ui-grid-icon-filter:before {
content: '\c35f';
}
/* '썟' */
.ui-grid-icon-sort-alt-up:before {
content: '\c360';
}
/* '썠' */
.ui-grid-icon-sort-alt-down:before {
content: '\c361';
}
/* '썡' */
.ui-grid-icon-ok:before {
content: '\c362';
}
/* '썢' */
.ui-grid-icon-menu:before {
content: '\c363';
}
/* '썣' */
.ui-grid-icon-indent-left:before {
content: '\e800';
}
/* '' */
.ui-grid-icon-indent-right:before {
content: '\e801';
}
/* '' */
.ui-grid-icon-spin5:before {
content: '\ea61';
}
```

Is this a bug or do I miss something here?

Cheers
Bernd

**Comment by crazyjat** [comment]
This does seem to be a bug and a big deal for those of us trying to use the less files.

Why has this not been addressed in almost a year?

Where do these styles come from?

**Comment by BerndWessels** [comment]
I think this project is dead. Otherwise an issue like this would have caused a huge outcry.

**Comment by crazyjat** [comment]
I'm confused. Are you claiming that the ui-grid project is dead?

**Comment by BerndWessels** [comment]
@crazyjat Since this issue has not been fixed in a year as you pointed out, I believe nobody can use this project properly using less. Without less there is no proper white-labeling. And as a result I doubt the project can be seriously used for production. And a project that is not production ready for such a long time is dead to me at least.

**Comment by c0bra** [comment]
The icons are defined by less that is generated by Fontello: http://fontello.com/

This was done when the icons were rapidly changing and having new ones added. Since they've stabilized quite a bit, the less could probably be used statically rather than generating it as part of the build.

**Comment by BerndWessels** [comment]
@c0bra Thanks for the info. I moved almost all my projects to `react` and `react-native` now. But for everybody else still on `angular` I would suggest you provide proper `less` support for this project.
Cheers
Bernd

**Comment by mportuga** [comment]
Closed by https://github.com/angular-ui/ui-grid/pull/5762
