### ISSUE TITLE
Recreate columnDefs not working

### ISSUE THREAD

**Issue by oriko** [angular-ui/ui-grid#4662]
Hi

I am creating custom columnDefs for my ui-grid, in my page I am switching between grids that have different columns. For the switch I am regenerating my column defs and my grid data, but for some reason some column props are not regenerated and keeps old defs (like cellTemplate).
Is there a way to clear all old columnDefs from my grid?

**Comment by imbalind** [comment]
It could heavily depend on the way you implemented this.

Could you please build a plunker?

**Comment by oriko** [comment]
Can you point me to the correct way?

**Comment by PaulL1** [comment]
I find the easiest way to be to wrap the whole grid html in an ng-if, with the ng-if relying on a variable `refresh`.  When I want to rebuild the grid I toggle `refresh` to false, which clears the grid.  I wait one digest cycle (i.e. $timeout(0) ) and then toggle refresh back to true again.  This clears the grid and rebuilds it.

**Comment by oriko** [comment]
Thanks PaulL1, you solved my problem
