### ISSUE TITLE
Edit on Focus does not focus input element on iPad

### ISSUE THREAD

**Issue by MichalJakubeczy** [angular-ui/ui-grid#4666]
When I use "Edit on focus" (combined ui.grid.edit with ui.grid.cellNav) functionality it works fine on all browsers I need except iPad.

After particular cell I would like to edit is clicked it is switched to edit mode, but input element is not focused. I need another click to focus the element and to make keyboard appear.

Issue can be simulated on your tutorial page as well: http://ui-grid.info/docs/#/tutorial/301_editableOnFocus

I think it is because iPad does not allow to focus element if focus is called from other than user-initiated event (http://stackoverflow.com/questions/5978470/ipad-html-focus). uiGridEditor directive uses timeout to focus the element, thus new call stack is started and iPad does not allow to focus it.

**Comment by dlgski** [comment]
I see your issue, but given what you answer in stackoverflow I don't think this is something to put into ui-grid.  Please provide a PR if you know of a good way to change this.
