### ISSUE TITLE
Working example of ui-grid that is IE 8 compatible?

### ISSUE THREAD

**Issue by chaumette** [angular-ui/ui-grid#4667]
I had no luck getting any version of angular grid to work with IE8. I am using MVC 4.5 with Bootstrap 3, any working example that is compatible with IE8 would save my week?

**Comment by PaulL1** [comment]
http://ui-grid.info/docs/#/tutorial/100_preReqs

IE9+ is required.

**Comment by Gargaroz** [comment]
What is the last IE8 compatible version of ui-grid?

**Comment by ericWenjp** [comment]
> Which is the last IE8 compatible version of ui-grid?

+1

**Comment by mattbrunetti** [comment]
😢
