### ISSUE TITLE
More than 2 levels of expandable grid - UI grid

### ISSUE THREAD

**Issue by Priya9136** [angular-ui/ui-grid#4668]
Hi ,I am trying to implement a expandable grid with more than 2 levels of nesting. I have issues in implementing the 2 grid.Can you help me with a detailed example.

**Comment by exorebug** [comment]
Hello

I would also like to know how to do this if it’s possible. I also have been trying to make a grid with multiple nested rows (up to 3 levels of nesting in my case). 

To clarify, what I’m trying to do is create a grid that represents a typical hierarchy of data for a patient in a DICOM context. This means each patient has multiple studies, each study multiple series and each series multiple instances.
So far I have followed the tutorial at http://ui-grid.info/docs/#/tutorial/216_expandable_grid and made a grid where for each patient I can see all the studies but I’m stuck trying to make it so for each study I have an additional subgrid for its series. 

I tried to do this following @jpuri’s instructions on issue #2648 but to no avail.

Any help would be appreciated.

**Comment by swalters** [comment]
closing old issue

**Comment by chetan-d-mahajan** [comment]
Can you please provide a reference to the resolution for this issue? It looks like this issue has been closed without any explanation or reference.

**Comment by mportuga** [comment]
Unfortunately, swalters is no longer active in the development team and I am not aware of his reasoning for closing it.

**Comment by coltonbrugger** [comment]
I had a problem with this at first, but realized it was a simple fix. Just be sure to add the `ui-grid-expandable` attribute on the expandable row's template to enable the expandable features within that sub-grid.

**expandableRowTemplate.html**
```<div ui-grid="row.entity.subGridOptions" ui-grid-expandable></div>```

Cheers.
