### ISSUE TITLE
when using treeView and "enableRowHeaderSelection:false" the plus (+) to expend tree row doesn't work

### ISSUE THREAD

**Issue by vgroisma** [angular-ui/ui-grid#4675]
when using treeView and "enableRowHeaderSelection:false" the plus (+) to expend tree row doesn't work.

this worked fine in version 3.0.6 but not working in 3.0.7

the topmost (+) to expend all rows works, but in every row it doesn't.

**Comment by billyaraujo** [comment]
I guess this is the same as #4607.

**Comment by bgou** [comment]
If you set it to false, isn't it the right behavior to actually disable the expand button?

**Comment by iblecher** [comment]
+1
