### ISSUE TITLE
data refresh on sort

### ISSUE THREAD

**Issue by coonsa2** [angular-ui/ui-grid#4676]
I have cell class functions for determining the coloring of certain cells in the grid, and upon sorting, the color stays in the same cell, even though the data changed. I am trying to us the following with no avail:

$scope.$on('ngGridEventSorted', function (event, data) {
            $scope.gridApi.core.notifyDataChange($scope.gridApi.grid, uiGridConstants.dataChange.COLUMN);
        })

**Comment by PaulL1** [comment]
That event looks like a 2.x event, but the notifyDataChange is a 3.x function.  

Sorting should already trigger a notifyDataChange though, so this shouldn't be happening.  Any chance of a plunker?

**Comment by coonsa2** [comment]
I cannot produce a plunker, since it is a very large enterprise app that uses the grid. 

For determining the cell class I am using this in the columndefs (cellClass):

              {
                  field: 'CorrectedPrice',
                  displayName: 'Correction to Current Price',
                  headerCellTemplate: 'app/Shared/Grid/EditableHeader.html',
                  enableCellEdit: true,
                  type: 'number',
                  cellTemplate: 'app/Shared/Grid/CorrectedCheckbox.html',
                  width: 100,
                  cellClass: function (grid, row, col, rowRenderIndex, colRenderIndex) {
                      return productCssService.GetCorrectedApprovalStatusBackgroundColor(grid, row, 'CorrectedApprovalStatusName');
                  },
                  filter: { condition: gridService.PriceFilter }
              },

Since the color is staying in the same cell, I am looking for an event function that triggers on the sorting. Is there any such function in 3.x? 

Here is the setting up of the grid options:

$scope.gridOptions = {
            enableRowSelection: true,
            selectionRowHeaderWidth: 30,
            selectionRowHeaderHeight: 50,
            enableColumnResizing: true,
            multiSelect: true,
            enableSelectAll: true,
            enableFiltering: true,
            rowEditWaitInterval: -1,
            rowHeight: 50,
            enableCellEdit: true,
            enableCellEditOnFocus: true,
            enableCellSelection: true,
            enableColumnResize: true,
            enableVerticalScrollbar: false,
            enableRowHeaderSelection: true,
            enableFullRowSelection: true,
            enablePaging: true,
            pagingPageSizes: iwDropDownService.pagingSizes,

I noticed I'm not using the enableSorting: true, despite the grid being able to sort. Could this be a root of the issue of notifyDataChange not being triggered on sort?

**Comment by coonsa2** [comment]
turning on enableSorting didn't fix the issue.

Here's the html where I am using to set up the grid, in case there is anything I can inject into there to deal with this issue

<div id="findProductGrid" ui-grid="gridOptions" class="grid"
                    ui-grid-edit ui-grid-row-edit ui-grid-cellnav ui-grid-selection
                    ui-grid-resize-columns ui-grid-auto-resize ui-grid-paging
                    external-scopes="$scope"
                    style="width: 100%; text-align: left;">
                </div>

**Comment by PaulL1** [comment]
Are you able to recreate it on the cellClass tutorial?  I think that has sorting enabled, or could have if you edited it in a plunker.

**Comment by coonsa2** [comment]
Looking through your link here https://github.com/angular-ui/ui-grid/blob/9d1a0b46e54983e09e0be8f89f9fac0ee74046e4/src/js/core/directives/ui-grid-cell.js

I see the following:

 // Register a data change watch that would get triggered whenever someone edits a cell or modifies column defs
          var dataChangeDereg = $scope.grid.registerDataChangeCallback( updateClass, [uiGridConstants.dataChange.COLUMN, uiGridConstants.dataChange.EDIT]);
          
          // watch the col and row to see if they change - which would indicate that we've scrolled or sorted or otherwise
          // changed the row/col that this cell relates to, and we need to re-evaluate cell classes and maybe other things
          var cellChangeFunction = function( n, o ){
            if ( n !== o ) {
              if ( classAdded || $scope.col.cellClass ){
                updateClass();
              }

              // See if the column's internal class has changed
              var newColClass = $scope.col.getColClass(false);
              if (newColClass !== initColClass) {
                $elm.removeClass(initColClass);
                $elm.addClass(newColClass);
                initColClass = newColClass;
              }
            }
          };

This seems to be what I am looking for, but I am unsure of how this cell change function is triggered

**Comment by PaulL1** [comment]
The cell change is triggered by a watch - so it'll be watching the col reference or the row reference to see if they change.  It should trigger on scroll, and therefore should refresh the class.  I'm pretty sure I wrote that, and I think I tested it on one of the tutorials - almost certainly the cellClass tutorial.  But I may not have tested for sorting.

**Comment by coonsa2** [comment]
Ah, the sortChanged event did the trick. Thanks
