### ISSUE TITLE
Dropdown menu includes extra item

### ISSUE THREAD

**Issue by Superiom** [angular-ui/ui-grid#4681]
The title says pretty much everything. My grid has 5 columns. However, the menu includes one extra item, called [MISSING]. It isn't defined anywhere, and it doesn't perform any action, it just sits there. When clicked, it outputs 'itemAction' in the Developer Console - same as every other item when clicked.

**Comment by imbalind** [comment]
Could you please build a plunker showing the issue?

**Comment by Superiom** [comment]
The problem was that I have forgotten to translate one of the menu items. I forgot to mention that in the question above. It turns out that, if you forget to include an item in the translate js, and you use it in the code, the item will be displayed as [MISSING].
