### ISSUE TITLE
ui-pagination seek method doesn't work

### ISSUE THREAD

**Issue by adoueb** [angular-ui/ui-grid#4684]
Hello,
I have a grid with the standard pagination.

I go to page 3 for example (277 items, 10 items per page).
I edit one item and come back to the page having restored the grid state and reassigned the data (same count and even same data in my current test case).

$scope.gridApi.pagination.seek(3) doesn't work because grid.options.totalItems is 0.

Could someone help me fix the problem ?
Regards.

**Comment by imbalind** [comment]
Could you please build a plunkr showing the issue?

**Comment by imbalind** [comment]
I'm closing this since no updates for more than a month.

**Comment by McMounir** [comment]
same problem gridApi.pagination.seek(N) and gridApi.pagination.getTotalPages() not working for me after switching from OData V3 to Odata V4 !! but i dont see the relation between OData And GridOption !!!

insterad of that gridApi.pagination.previousPage() still working very well.

any help please, thank you.
