### ISSUE TITLE
Memory leaks - grid object not getting destroyed

### ISSUE THREAD

**Issue by mloutraris-ge** [angular-ui/ui-grid#4687]
We have noticed that the grid data is not getting destroyed causing the memory to grow. You can see this by using the tutorial.

Steps to recreate: (using chrome with debugger window open)
1. Bring up the tutorial: http://ui-grid.info/docs/#/tutorial 
2. Using the profiler, take a heap snapshot. This will be the baseline.
3. Click on the 190 Large Dataset link on the left. Take another snapshot. Note that the heap size goes up.
4. Click to 098 Contributing to ui-grid.  Take another snapshot. Note that the heap size is still high.
5. Click on the 190 Large Dataset link on the left. Take another snapshot. Note that the heap size goes up even more.
6. Click to 098 Contributing to ui-grid.  Take another snapshot. Note that the heap size is still high.

Obviously you can keep this going for ever and it continues to grow.

If you look at the snapshots this is what I see:

1. Original profile:
![image](https://cloud.githubusercontent.com/assets/10615622/11137477/ef8614ca-8985-11e5-8cca-17880fefecbe.png)
2. After loading large data:
![image](https://cloud.githubusercontent.com/assets/10615622/11137499/32c79614-8986-11e5-9778-88503e56a8f2.png)
3. After going to 098 Contributing to ui-grid (grid was destroyed)
![image](https://cloud.githubusercontent.com/assets/10615622/11137523/764e1ee4-8986-11e5-94db-dccb246e24ea.png)
4. After going back to 190 Large Dataset link (data doubles):
![image](https://cloud.githubusercontent.com/assets/10615622/11137552/bbf40148-8986-11e5-92f8-4e0373c45d31.png)
5. After going to 098 Contributing to ui-grid (grid was destroyed)
![image](https://cloud.githubusercontent.com/assets/10615622/11137572/f89c5fa0-8986-11e5-99c0-05807640c52e.png)

We are seeing this in our application that uses the ui-grid. I have not been able to track down where the leak is. Has anyone seen this or knows the the issue might be?

Thanks

**Comment by imbalind** [comment]
I confirm this bug and I think I found the culprit.

At [line 46 of uiGridMenu](https://github.com/angular-ui/ui-grid/blob/9d1a0b46e54983e09e0be8f89f9fac0ee74046e4/src/js/core/directives/ui-grid-menu.js#L46) we access `this` inside of an `apply` method.

The `apply` method is called by angularjs' `cloneAndAnnotateFn` method wich calls the former using js' `apply` method but passing `null` as `thisArg` parameter.

As per [mozilla docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply#Parameters), calling `apply` with a `null` `thisArg` leads to using the `global` object as this inside the called function.

Thus we end up ( see lines 55 and 99 of uiGridMenu) putting some references into the `window` object, hence the memory leak.

I'm testing if removing the reference to `this` avoids the leak, as supposed.

**Comment by mloutraris-ge** [comment]
Hi imbalind,

Thanks for looking at this so quickly. I tested the fix and for me it did not clear out the objects on destroy. Did it work for you?

Thanks

**Comment by imbalind** [comment]
Yes it did, these are screenshot without my fix:

![leakage](https://cloud.githubusercontent.com/assets/2514478/11148204/9cfd8fe4-8a1b-11e5-9cf0-73f1cd837aba.PNG)

![leakageheaptimelines](https://cloud.githubusercontent.com/assets/2514478/11148206/a1e93332-8a1b-11e5-9426-2b35872fdaf6.PNG)

And this is the same activity after my fix:

![no-leakage](https://cloud.githubusercontent.com/assets/2514478/11148221/b5986ace-8a1b-11e5-8d47-4842c12eb8cf.PNG)

![no-leakageheaptimelines](https://cloud.githubusercontent.com/assets/2514478/11148224/b7646448-8a1b-11e5-8e43-7e14cc52040a.PNG)

Did you try the same case as before (fro and back between tuts 098 and 190)?

**Comment by mloutraris-ge** [comment]
Let me pull down the project and try. I plugged it into our app and it did not help, but that may mean that there are more issues. I will let you know, may take me a little bit to get that set up.

Thanks

**Comment by mloutraris-ge** [comment]
I am still seeing the issue with your new code:

Here is the code active:
![image](https://cloud.githubusercontent.com/assets/10615622/11152112/b7ad97ca-89fe-11e5-8a47-b31b78490cde.png)

Snapshot Before:
![image](https://cloud.githubusercontent.com/assets/10615622/11152147/ec29ce10-89fe-11e5-8310-a927d94051f5.png)

Snapshot after accessing 190_large_dataset:
![image](https://cloud.githubusercontent.com/assets/10615622/11152159/fd31e3b4-89fe-11e5-9061-33065628055a.png)
.
After going back to 098_Contributing… : objects and memory are still consumed:
![image](https://cloud.githubusercontent.com/assets/10615622/11152171/1063cd6c-89ff-11e5-9b78-4ef96f8e2f60.png)

**Comment by imbalind** [comment]
Ok, I sadly cannot help further since I cannot replicate it.

Did you do anything more than what we said before?

@oriondean were you able to reproduce it?

**Comment by mloutraris-ge** [comment]
All I did was setup to run locally. I can try again once there is a new build up on the ui-grid.info site.

**Comment by imbalind** [comment]
I was looking back at your first post. You showed there that objects double when you reopen tut 190 a second time. Strange enough, that doesn't happen to me with ui-grid.info website.

Could it be something local? Like, I see you're using Chrome, what version is it?

**Comment by oriondean** [comment]
Hey, 

Here's a screenshot of my heap snapshots after reproducing the steps described in the first comment:

![image](https://cloud.githubusercontent.com/assets/3110057/11163928/273d5388-8ada-11e5-813e-2cb35dae1bf1.png)

* Snapshot 1: Initial snapshot of 098
* Snapshot 2: Switched to 190 (first grid leaked)
* Snapshot 3: Switch to 098
* Snapshot 4: Switched to 190 (second grid leaked)
* Snapshot 5: Switched to 098
* Snapshot 6: Switched to 190 (third grid leaked)

You can see a steadily increase in heap size after each snapshot. Each time I switch to 190, a grid was created. When i switched away from 190, this grid was not cleared from the heap. This meant by Snapshot 6, there were three grids remaining in the heap when there should only be one.

Looking at the retainer tree, it seems GridColumn.prototype.hideColumn is responsible for keeping a reference to one of the Grid objects. This is because each time a GridColumn is constructed, it overrides the existing hideColumn method on all existing GridColumns (since it updates the prototype in its constructor!). The hideColumn method retains a reference to the last grid to construct it via the "self" variable that is declared in it's closure scope.

I'm working on a fix to this particular leak, but i pushed my initial changes a little too early!

**Comment by islabu** [comment]
I did all this 3 fixes and nothing changed! Maybe refer to 
https://github.com/angular-ui/ui-grid/issues/4802
