### ISSUE TITLE
Grouping and counting it's length with $row.treeNode.children error.

### ISSUE THREAD

**Issue by eabreusantos** [angular-ui/ui-grid#4690]
Sometimes when a columns is grouped and filtered with *value and I loop through its children, this list may contain invalid data that aren't either in the filter nor visible.

The image below contains a sample of what I've seen.
http://postimg.org/image/uzwmno8zh/

In the right, we see a console.log($row). By checking its treeNode children we may see a list containing invisible data and/or items that do not correspond to the actual filter.

In advance,
thanks.

**Comment by imbalind** [comment]
Could you please provide a plunker showing your issue?
