### ISSUE TITLE
$scope.gridApi.selection.unSelectRow(row.entity); doesn't work

### ISSUE THREAD

**Issue by flamant** [angular-ui/ui-grid#4700]
Hello,
on rowSelectionChanged event, I want to unselect grouping row when I select or unselect one of its children 

            var parentRow;
            var i = 0;
            console.log($scope.gridApi.grid.renderContainers.body.renderedRows)
            $scope.gridApi.core.getVisibleRows($scope.gridApi.grid).some( function(rowItem) {
            	i++;
            	console.log('i='+i+'   rowItem.treeLevel='+rowItem.treeLevel+'  rowItem.isExpanded='+rowItem.isExpanded);
            	console.log(rowItem);
            	if (rowItem.treeLevel == 1 && rowItem.treeNode.state == 'expanded') {
            		console.log('parent row selected');
            		parentRow = rowItem;
            	}
            	if(rowChanged == rowItem) {
            		console.log('parentRow unselected');
            			$scope.gridApi.selection.unSelectRow(parentRow.entity);

            		return true;
            	}
            
            });

But $scope.gridApi.selection.unSelectRow(parentRow.entity); doesn't work

Thank you in advance for your answers

**Comment by geovizcoder** [comment]
Me facing a similar issue.

**Comment by PaulL1** [comment]
Could you provide a plunker of this?  I suspect it's because the group parents aren't real rows in the data, but I would need to see it running to be sure.

**Comment by flamant** [comment]
Hi Paul it is very nice to answer,

here is the plunker with console.log output

http://plnkr.co/edit/IJfxjdn3LDBkAf10R6Uc?p=preview

**Comment by flamant** [comment]
Hi Paul, finally I used custom checkbox column so I have more control on it

    columnDefs: [
        { name: 'checkbox',field: 'checkbox', displayName: 'checkbox' , width: '2%' , cellTemplate: '<div  >     
        <INPUT ng-if="row.treeLevel != 0" type="checkbox" ng-model="row.checkbox"   
        ng-click="grid.appScope.manageClick(row)" ></div>' },
