### ISSUE TITLE
is it possible to have a paginationPageSize per page

### ISSUE THREAD

**Issue by flamant** [angular-ui/ui-grid#4701]
Hello,

I am facing an issue on pagination. I have a grid with 2 level of grouping row and I use pagination. If for example on the first page I expand the last grouping row I want to be able to see its chidren, so I increase paginationPageSize to see them. But it isn't satisfying because if I navigate to the second page and expand the first grouping row, the paginationPageSize is also changed and my row is displayed on the first page. So the solution would be to have a paginationPageSize per page. Thank you in advance for your answers

        $scope.gridApi.treeBase.on.rowExpanded(
    			$scope, function(row) {
    			var childrenLength = $scope.gridApi.treeBase.getRowChildren( row ).length;
    			console.log('rowExpanded childrenLength='+childrenLength);
    			if (row.treeNode.state == 'expanded') {    		
    			$scope.gridCapacityFileHeight += 30 * childrenLength;
    			$scope.gridOptions.paginationPageSize += childrenLength;
    			}
    			});
        $scope.gridApi.treeBase.on.rowCollapsed(
    			$scope, function(row) {
    			var childrenLength = $scope.gridApi.treeBase.getRowChildren( row ).length;
    			console.log('rowCollapsed childrenLength='+childrenLength);
    			if (!(row.treeNode.state == 'expanded')) {    		
        			$scope.gridCapacityFileHeight -= 30 * childrenLength;
        			$scope.gridOptions.paginationPageSize -= childrenLength;    				
    			}
    			});

**Comment by PaulL1** [comment]
I'm sorry, this isn't a feature that's currently provided within the grid, nor something that is on our roadmap.  We generally use grouping or pagination, but I've never really seen people use both in that way.
