### ISSUE TITLE
Horizontal and Vertical scroll bars

### ISSUE THREAD

**Issue by ColcerP** [angular-ui/ui-grid#4703]
Hello,
    I'm using the latest version of ui-grid now and I encounter an issue regarding the scroll bars. I didn't managed so far to show them only when it's need of them. If I change the CSS property overflow with auto, then they disappear but a redundant space is remaining in the right part of the grid (where the vertical scroll it should be). Can someone please help me with a solution for this.
![image](https://cloud.githubusercontent.com/assets/6659895/11171221/442a0c42-8bf3-11e5-88cd-d9e95e75dd60.png)

**Comment by kkozlowski89** [comment]
Hello,

you have to inject "uiGridConstants" in your controller and then:

gridOptions = {
            enableHorizontalScrollbar: scope.uiGridConstants.scrollbars.NEVER,
            enableVerticalScrollbar: scope.uiGridConstants.scrollbars.NEVER,
}

it's pseudo code :)

**Comment by ColcerP** [comment]
Yes, but if I use those two properties to hide the scroll bars, when the vertical scroll will be require it will take up from the last column width. I assume that a function is needed in order to add an extra right padding for the last column if the scroll is visible.

**Comment by ColcerP** [comment]
I found a workaround for the following issue.
First I disabled scrolls by overriding the overflow property (overflow-y: auto !important; overflow-x: hidden !important;). On the grid options I set the both enableHorizontalScrollbar and enableVerticalScrollbar  properties to false. Finally where the grid was used I wrote a ng-class calculated based on a function (please see below): ng-class="{'grid-scroll' : 'isVerticalScrollRequire(gridOptions)' }".

var isVerticalScrollRequire = function(gridOptions) {
                //Default row height
                var rowHeight = 40;

                if (gridOptions.rowHeight != null)
                    rowHeight = gridOptions.rowHeight;

                var gridHeight = heightGetter(false);
                
                if (gridHeight) {
                    var contentHeight = gridHeight - 40; //Subtract header height from grid.

                    contentHeight -= (gridOptions.data.length * rowHeight);

                    if (contentHeight < 0)
                        return true;

                    if (scope.expandableGridApi) {
                        var rowIndex = 0;
                        var rows = scope.expandableGridApi.grid.rows;

                        while (rowIndex < rows.length && contentHeight >= 0) {
                            if (rows[rowIndex].isExpanded) {
                                contentHeight -= gridOptions.expandableRowHeight;
                            }

                            rowIndex ++;
                        }

                        if (contentHeight < 0)
                            return true;
                    }
                }

                return false;
            }

**Comment by a2ron** [comment]
It would be a good idea to add the option WHEN_NEEDED, in order to show/hide the scrollbars just in case that they are needed. Something like that:

enableHorizontalScrollbar: scope.uiGridConstants.scrollbars.WHEN_NEEDED,
enableVerticalScrollbar: scope.uiGridConstants.scrollbars.WHEN_NEEDED,

**Comment by ColcerP** [comment]
WHEN_NEEDED is no longer a valid option for the enable scrollbar properties. Would be nice to have them available.

**Comment by jdrake3** [comment]
Sadly this option appears to continue to be unsupported.

**Comment by binal24** [comment]
WHEN_NEEDED option is not working. 
Is there any solution for hiding horizontal scrollbar ?
