### ISSUE TITLE
Exported CSV is not CSV conform with Excel

### ISSUE THREAD

**Issue by patrickbussmann** [angular-ui/ui-grid#4714]
Hey everybody,

I exported a csv file with the ui-grid export feature.
The values in it have line breaks (\n).
And this breaks the lines in the file so that Excel detect is as a own data set - which is wrong.

Do anybody know how to fix that problem?

Remove all line breaks before shouldnt be the only solution :+1: 

Example.csv:

	"Title","Description"
	"Example","a
	b
	c
	d
	e",

**Comment by patrickbussmann** [comment]
Example csv content:

	"Title","Description"
	"Example","a
	b
	c
	d
	e",

**Comment by PaulL1** [comment]
If you have line breaks in your data you'll probably have difficulty.  It's correct to format with quote marks and the line breaks inside - that's about as good as CSV gets.  But Excel doesn't interpret CSV all that well.  It doesn't help that CSV isn't a formal standard, so there's no specification.
