### ISSUE TITLE
onRegisterApi in a loop

### ISSUE THREAD

**Issue by tandvu** [angular-ui/ui-grid#4720]
I need to create multiple grids.

for (var i=0; i < myGrids.length; i++)
{
  var grid = myGrids[i];
  grid.gridOptions.onRegisterApi = function(gridApi){
    gridApi.selection.on.rowSelectionChanged(null, function (row){
      console.log("grid.guid: " + grid.guid);
    }  
  }
}

Only the last grid item of the array get called multiple times.  I know onRegisterApi is a callback function.  But how do we solve this problem?

Thank you,

Tan

**Comment by AgDude** [comment]
Please create a plunker demonstrating the issue. I will re-open this ticket when you provide more information.
