### ISSUE TITLE
uiGridExporterService.getData not applying cellFilter

### ISSUE THREAD

**Issue by Tim-Intellipharm** [angular-ui/ui-grid#4721]
The ```uiGridExporterService.getData``` is not applying ```cellFilter```. 

See this [plunker](http://plnkr.co/edit/4Rkml0rszYWkBSVCMuMx?p=preview) for an example

**Comment by PaulL1** [comment]
No, and it's not expected to.  There is a method to massage data by using the data callback, if you wanted to apply formatting or other logic.  This is illustrated in the tutorial: http://ui-grid.info/docs/#/tutorial/312_exporting_data_complex

Closing as this isn't a defect.

**Comment by Tim-Intellipharm** [comment]
I feel that your response is a cheap cop-out. I shouldn't have to run a data callback on the dozens of ui-grids throughout my website.

**Comment by PaulL1** [comment]
It's nice of you to share your opinion.
