### ISSUE TITLE
Text wrapping in Grid Cells

### ISSUE THREAD

**Issue by DevQueen** [angular-ui/ui-grid#4723]
I am having a problem in one of my grid where the text in the field is wrapping when the text overruns the field rather giving me the ellipses.  See example below:

![grid text wrap on hyperlink](https://cloud.githubusercontent.com/assets/13017434/11242283/7aeafb68-8dc6-11e5-903c-cce26aa65ca1.png)

Here is my controller code:

  $scope.gridOptions = {
        columnDefs: [
            {
                field: 'dteDateReleaseRequestedByCompany', displayName: 'Requested Date'
            },

      {
          field: 'vchCompanyName', displayName: 'Company Name', wordWrap: false,
          cellTemplate: '<div style="text-decoration:underline;color:blue;text-align:left;cursor:pointer" ng-click="grid.appScope.rowClick(row)">{{COL_FIELD}}</div>'
      },
      {
          field: 'CompanyID', width: 110, displayName: 'Company ID', visible:false
      },
      { field: 'vchOprCity', displayName: 'City' },
      { field: 'vchOprStateVchID', displayName: 'State' },
      {
          field: 'dteExpiresWithGracePeriod', displayName: 'Subscription', headerCellClass: 'center',
          cellTemplate: '<div style="text-align:center"><span ng-bind-html="row.entity[col.field] | getSubscription | trustedhtml"></span></div>'
      },
      {
          field: 'Action', displayName: 'Release Action', 
          cellTemplate: '<div class="btn-group" ng-init="row.entity.Action=0"><input ng-model="row.entity.Action" type="radio" value="0" style="width:20px">&nbsp;None&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input ng-model="row.entity.Action" type="radio" value="1" style="width:20px">&nbsp;Accept&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input ng-model="row.entity.Action" type="radio" value="2" style="width:20px">&nbsp;Decline</div>'

      },

        ],
        showGridFooter: false,
        //enableFiltering: true,
        enableSorting: false,
        paginationPageSizes: [20, 40, 60],
        paginationPageSize: 20,
        enableHorizontalScrollbar: uiGridConstants.scrollbars.NEVER,
        enableGridMenu: true,
        exporterCsvFilename: 'PendingReleases.csv',
        exporterPdfDefaultStyle: { fontSize: 9 },
        exporterPdfTableStyle: { margin: [10, 10, 10, 10] },
        exporterPdfTableHeaderStyle: { fontSize: 10, bold: true, italics: true, color: 'red' },
        exporterPdfHeader: { text: "Pending Release Requests", style: 'headerStyle' },
        exporterPdfFooter: function (currentPage, pageCount) {
            return { text: currentPage.toString() + ' of ' + pageCount.toString(), style: 'footerStyle' };
        },
        exporterPdfCustomFormatter: function (docDefinition) {
            docDefinition.styles.headerStyle = { fontSize: 22, bold: true, alignment: 'center' };
            docDefinition.styles.footerStyle = { fontSize: 10, bold: true, alignment: 'center' };
            return docDefinition;
        },
        exporterPdfOrientation: 'landscape',
        exporterPdfPageSize: 'LETTER',
        exporterPdfMaxGridWidth: 500,
        exporterCsvLinkElement: angular.element(document.querySelectorAll(".custom-csv-link-location")),
        onRegisterApi: function (gridApi) {
            $scope.gridApi = gridApi;

        }
    };

Here is my HTML:

![ui-grid html](https://cloud.githubusercontent.com/assets/13017434/11247330/39e177f8-8de1-11e5-9e4f-3270a799ce52.png)

I thought it may have been happening because I had specified a row height, so I tried removing that, but it still didn't solve the issue.  I'm using several grids in my project and this is the only one with this problem.

**Comment by DevQueen** [comment]
I'm still having this issue, however, I have since found out that the problem is my use of cellTemplate.  If I remove the cellTemplate from the field definition, the column text stops wrapping and I get the ellipses again.  However, I need to be able to click the field, so I have to use the cellTemplate.   Help with the issue is greatly appreciated.

**Comment by swalters** [comment]
Try adding ui-grid-cell-contents class to your template

**Comment by DevQueen** [comment]
Where do I put ui-grid-cell-contents?

**Comment by DevQueen** [comment]
Thanks much!!!  That worked!  Have a very happy New Year!

**Comment by varunkusuma** [comment]
Did adding class="ui-grid-cell-contents" in the div work? It doesn't work for me.

**Comment by tonysepia** [comment]
can someone clarify what happened here please? Where was the class added exactly? What was causing the problem?

**Comment by koustubhklkpvn** [comment]
Using ui-grid-cell-contents in the div class of cellTemplate worked for me. It didn't wrap my text and the hyperlink works fine.

For ex: in my component js file

columnDefs: [
{ field: 'field1', cellTemplate : '<div class = "ui-grid-cell-contents"> blah!! blah!! </div>
}
