### ISSUE TITLE
[ui.grid.expandable] Undocumented row.isExpanded option for ui.grid.GridRow

### ISSUE THREAD

**Issue by joeskeen** [angular-ui/ui-grid#4724]
When looking at the sample code for the expandable tutorial: http://ui-grid.info/docs/#/tutorial/216_expandable_grid, I came across a check for `row.isExpanded` (app.js line 76).  This option isn't documented anywhere in the API, but I have tested it in my own project and it seems to work as expected.
I noticed that `expandable` is marked as 'Alpha', so I am wondering if this isn't in the API because there are plans to change it, or just because no one has documented it yet.  I would be happy to contribute if it is the latter, as I would also like to add it to the DefinitelyTyped definition for ui-grid as well. (see https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/ui-grid/ui-grid.d.ts#L1488)

**Comment by PaulL1** [comment]
There is no current plan to change the expandable API, it's alpha because it doesn't really have any contributors that work on it, and it has a number of known defects.  We'd welcome a contribution that added documentation to the code.

**Comment by PaulL1** [comment]
Thanks, I've merged.
