### ISSUE TITLE
grid height calculated incorrectly when `enableFiltering === true`

### ISSUE THREAD

**Issue by nickescallon** [angular-ui/ui-grid#4726]
Case 1: No columnDefs
  - no columnDefs are specified, and `enableFiltering` is set to `true`
  - grid is 1 row's worth of height too short
  - [plnkr](http://plnkr.co/edit/DgkaZV173Ph1X4GMCj9J?p=preview) (should show 4 rows, only shows 3)

Case 2: enableFiltering && filter property in columnDef
 - columnDef is specified with a `.filter` property and `enableFiltering` is set to `true`
 - grid is 1 row's worth of height too tall
 - [plnkr](http://plnkr.co/edit/MD9Al098wMF0z5KNWm1a?p=preview)  (should show 4 rows, instead shows 5)

**Comment by AgDude** [comment]
Should be fixed by merged PR.
