### ISSUE TITLE
TypeError: Cannot read property 'on' of undefined  at Object.$scope.gridOptions.onRegisterApi

### ISSUE THREAD

**Issue by roshantarudkar** [angular-ui/ui-grid#4727]
I am using ni-grid and trying to use row edit feature..i am getting error at gridApi.rowEdit.on.saveRow...its giving cannot read property on of undefined..i have added all required js files but no clue why its giving me this error. can someone please help me.

i have below code snippet:

```
  $scope.gridOptions.onRegisterApi = function (gridApi) {
                //set gridApi on scope
                $scope.gridApi = gridApi;
                gridApi.rowEdit.on.saveRow($scope, $scope.saveRow);
            };



 $scope.saveRow = function (rowEntity) {
                // create a fake promise - normally you'd use the promise returned by $http or $resource
                var promise = $q.defer();
                $scope.gridApi.rowEdit.setSavePromise(rowEntity, promise.promise);

                // fake a delay of 3 seconds whilst the save occurs, return error if gender is "male"
                $interval(function () {
                    if (rowEntity.ExemptionCode === 5) {
                        promise.reject();
                    } else {
                        promise.resolve();
                    }
                }, 3000, 1);
            };
```

**Comment by PaulL1** [comment]
Are you able to make a plunker?

That code looks very similar to the tutorial - does the tutorial work for you?  I'd guess you haven't included the rowEdit directive on your grid definition in the html?

**Comment by roshantarudkar** [comment]
ya this code is similar to tutorial..i wanted to make sure its working when i pulled same code but it didnt..i added  ui.grid.rowedit in grid .

here is full code-

html-
<div ng-app="myApp">

    <div ng-controller="MainCtrl">
        <select ng-model="lang" ng-options="l for l in langs"></select><br>
        <div ui-i18n="{{lang}}">

            <p ui-t="groupPanel.description"></p>
            <button type="button" id="addData" class="btn btn-success" ng-click="addData()">Add Data</button>
            <div id="grid1" ui-grid="gridOptions" ui-grid-move-columns ui.grid.selection ui-grid-resize-columns ui-grid-edit ui.grid.rowedit ui-grid-cellnav ui-grid-pagination ui-grid-auto-resize ui-grid-exporter></div>
                    </div>
    </div>
</div>

js-
<script type="text/javascript">

    (function () {
        var app = angular.module('myApp', ['ngTouch', 'ngAnimate', 'ui.grid', 'ui.grid.moveColumns', 'ui.grid.edit', 'ui.grid.rowEdit', 'ui.grid.cellNav', 'ui.grid.pagination', 'ui.grid.resizeColumns', 'ui.grid.exporter', 'ui.grid.selection']);


        app.controller('MainCtrl', ['$scope', '$http', 'i18nService', '$interval', 'uiGridConstants', 'exemptcodeList', '$q', function ($scope, $http, i18nService, $interval, uiGridConstants, exemptcodeList, $q) {

            $scope.langs = i18nService.getAllLangs();
            $scope.lang = 'en';
            $scope.columns = [{
                field: "ExemptionCodeDesc",
                cellTooltip: 'Custom string', headerTooltip: 'Custom header string',
                headerCellClass: 'blue',
                displayName: "Exemption Description",
                width: 150,
                pinned: true,
                 },
                {
                 field: "PurposeCode.PurposeCode",
                 cellTooltip:function (row, col) {
                             return 'Name: ' + row.entity.ExemptionCodeDesc + ' Company: ' + row.entity.ExemptionCode;
                             },
                 headerTooltip:function (col) {
                            return 'Header: ' + col.displayName;
                            },
                 displayName: "Purpose Code",
                 width: 120,
                 enableSorting: false,
                 type: 'number',
                 filter: { placeholder: 'abc' }
                },
                {
                 field: "ExemptionCode",
                 headerCellClass: function (grid, row, col, rowRenderIndex, colRenderIndex) {
                                    if (col.sort.direction === uiGridConstants.ASC) {
                                        return 'red';
                                    }
                                },
                 displayName: "Exemption Code",
                 width: 120,
                 type: 'number'
               },
               {
                   field: "CountryCode",
                   displayName: "Country Code",
                   width: 120,
                   type: 'string'
               }],

            $scope.gridOptions = {
                enableRowSelection: true,
                enableSelectAll: true,
                selectionRowHeaderWidth: 35,
                exporterMenuCsv: true,
                enableColumnResizing: true,
                //  gridMenuTitleFilter: fakeI18n,
                enableGridMenu: true,
                showGridFooter: true,
                data: 'myData',
                enablePinning: true,
                gridMenuShowHideColumns: true,
                enableSorting: true,
                enableFiltering: true,
                paginationPageSizes: [10, 25, 50, 75],
                paginationPageSize: 10,
                columnDefs: $scope.columns,
                //onRegisterApi: function (gridApi) {
                //    $scope.gridApi = gridApi;
                //}
               
            };

            $scope.gridOptions.multiSelect = true;
            $scope.saveRow = function (rowEntity) {
                // create a fake promise - normally you'd use the promise returned by $http or $resource
                var promise = $q.defer();
                 $scope.gridApi.rowEdit.setSavePromise(rowEntity, promise.promise);
                alert('roshan');
                // fake a delay of 3 seconds whilst the save occurs, return error if gender is "male"
                $interval(function () {
                    if (rowEntity.ExemptionCode === 5) {
                        promise.reject();
                    } else {
                        promise.resolve();
                    }
                }, 3000, 1);
            };

                 $scope.gridOptions.onRegisterApi = function (gridApi) {
                //set gridApi on scope
                $scope.gridApi = gridApi;
                gridApi.rowEdit.on.saveRow($scope, $scope.saveRow);
            };

           



            };


            var promise = exemptcodeList.GetExemptCode();
            promise.then(function (result) {
                $scope.myData = result.Data;
            }, function (reason) {
                console.log("Failed-exemption Code");
            });

        }]);


        app.factory('exemptcodeList', function ($q, $http) {
            var url = "@Url.Action("LoadExemptionDetails", "TaxExempt")";
            var service = {
                GetExemptCode: function () {
                    var defer = $q.defer();
                    var promise = $http.get(url, {});
                    promise.then(function (result, status) {
                        defer.resolve(result.data);
                    }, function (reason) {

                        defer.reject("Error in loading state");
                    });

                    return defer.promise;
                },

                PostExemptCode: function (newExemptCode) {
                    var defer = $q.defer();
                    $http.post(url, JSON.stringify(newExemptCode)).then(function (value) {
                        console.log("TaxExempt Record inserted");
                        defer.resolve(newExemptCode);
                    },
                        function (reason) {
                            console.log(reason);
                        });

                    return defer.promise;

                },

            };

            return service;
        });


    })();
</script>

**Comment by akeucon** [comment]
I have the same problem that he cant read '.on' or menas it 'afterCellEdit ?
here is my code
http://plnkr.co/edit/wJKwbgvWAcIFiPR6z5oT?p=catalogue
the grid is working well sorting,showing data, editing(but not saving cause gridapi not working)

**Comment by samunt** [comment]
I have the same issue.
