### ISSUE TITLE
Column and Pinned Column Data Out Of sync on the IPad Browser

### ISSUE THREAD

**Issue by dharmusharma1981** [angular-ui/ui-grid#4731]
Hi 

After integrating the Ui grid in our project we got so excited  about the performance and feature it provide. Its scroll nice on desktop browser  but when we tried the same page on the ipad browser , the pinned column data does not scroll  vertically shows blank div and after a while when scroll slows down it refresh itself that look really clunky. The horizontal scroll also has issue with header its shows blank for some time and after a while its refreshes. 
 i am using the header templates and cell templates ,as i need to show images in the cell.
Do you guys  have any suggestion how can i fix this on ipad so that it works same as desktop.

**Comment by sleepydisaster** [comment]
I have similar problem on iPad.

**Comment by dlgski** [comment]
version 3.2.7 will address some scrolling issues.
