### ISSUE TITLE
Export to excel/csv server side in ui-grid?

### ISSUE THREAD

**Issue by roshantarudkar** [angular-ui/ui-grid#4732]
does ui-grid support server side export to excel/csv in ui-grid?

**Comment by PaulL1** [comment]
Yes, in the sense that you can add a menu item to the grid requesting a server side export, and you can then call a function that you write to send the data server side.

But ui-grid has no server side components, so you'd have to custom build all that.

**Comment by roshantarudkar** [comment]
Thanks Paul..
