### ISSUE TITLE
footerCellTemplate does not work with external html template

### ISSUE THREAD

**Issue by MangeshPimpalkar** [angular-ui/ui-grid#4744]
footerCellTemplate 

Using the inline html template in footerCellTemplate works fine but when we use the external html template as in below plunker it does not show anything.

http://plnkr.co/edit/jn7li64Ny6qrtKuIemK9?p=preview

Is there a problem with my plunker.

It seems there is a bug.

**Comment by imbalind** [comment]
Did you try it on your local machine? 

It seems like custom templating is broken with plnkr and ui-grid.

**Comment by MangeshPimpalkar** [comment]
@imbalind I am using ui-grid in my project.
All the other custom template works except for footertemplate.

Hence tried to reproduce on plunker and was able to reproduce it.

**Comment by imbalind** [comment]
@MangeshPimpalkar it seems like it works when you toggle it, can you confirm it?

If it's so it may be a matter of loading times, but I'm not an expert in this matter.

@c0bra do you know who could be the right person?

**Comment by MangeshPimpalkar** [comment]
@imbalind It seems to work when we toggle it but all the data is not rendered.
if remove the custom footer "footerCellTemplate: 'footer.html'" the data is rendered.It seems like a bug.
