### ISSUE TITLE
Examples page on Wiki is broken (404 error)

### ISSUE THREAD

**Issue by MangeshPimpalkar** [angular-ui/ui-grid#4745]
Examples page on Wiki is broken (404 error)

http://angular-ui.github.io/ng-grid/#basic

**Comment by PaulL1** [comment]
How did you get to that page?  It looks to be an ng-grid (2.x) page, which therefore wouldn't be expected to work, but perhaps the problem is that we have a link to it from somewhere?

**Comment by MangeshPimpalkar** [comment]
If you click on this below link and then click on Examples it takes to the error page.
https://github.com/angular-ui/ui-grid/wiki
