### ISSUE TITLE
How can I know whether ui-grid rendering is finished or not?

### ISSUE THREAD

**Issue by sinntar** [angular-ui/ui-grid#4746]
I need to do something after the data was rendered, is there any events i can capture, ? thanks.

**Comment by PaulL1** [comment]
Standard answer is renderingComplete plus one $timeout

Sent from my iPhone

On 21 Nov 2015, at 9:44 AM, sinntar <notifications@github.com<mailto:notifications@github.com>> wrote:


I need to do something after the data was rendered, is there any events i can capture, ? thanks.

-
