### ISSUE TITLE
Column header menu not showing

### ISSUE THREAD

**Issue by BaoyunChen** [angular-ui/ui-grid#4751]
![menu](https://cloud.githubusercontent.com/assets/14226689/11328239/73c5bee6-91da-11e5-8702-8671563ba3dd.PNG)

As the photo shows, the column menu is not shown.

Here is my setting of the grid:

angular.module('app.ReportCtrl',['ngSanitize','ngTouch','ngCsv','ui.grid.grouping','ui.grid','ui.grid.autoResize','ui.grid.resizeColumns', 'ui.grid.moveColumns', 'reportFilters', 'reportDirectives', 'ui.bootstrap','ui.sortable'])
.controller('ReportCtrl',function($http, uiGridConstants,uiGridGroupingConstants,$rootScope, $scope, $filter, $timeout, PropertyService, EventService, SearchService, FormService, DatabaseService, ReportService, $location, $locale, EventColors, $modal, $q){

$scope.gridOptions = {
        data: 'queryResult',
        enableSorting: true,
        showColumnFooter: true,
        enableColumnResize : true,

```
};
```

html:

 id="table" class="gridStyle" ui-grid='gridOptions'  ui-grid-auto-resize ui-grid-grouping ui-grid-resize-columns ui-grid-move-columns

when I click the button I get an error:
Error: [$compile:ctreq] Controller 'ngModel', required by directive 'ngFocus', can't be found!

When I click the button, there is no item in menuitem. 
![capture](https://cloud.githubusercontent.com/assets/14226689/11328244/8fe3aba6-91da-11e5-85cb-6cd47d2bd0dd.PNG)

Did I miss anything?

**Comment by imbalind** [comment]
Could you please make a plunker showing your issue?

**Comment by BaoyunChen** [comment]
Sorry I could not make one to display my problem
But I ended up deleting the ng-focus in the menu template and the menu shows up.
