### ISSUE TITLE
cellFilter and cellTooltip is confused

### ISSUE THREAD

**Issue by yuetyeelo2855** [angular-ui/ui-grid#4752]
If I want to custom the `cellTooltip` and `cellFilter` in same time, will be ignore the `cellTooltip` setting, the tooltip will be show the cell value and format with `cellFilter`

**Comment by PaulL1** [comment]
That shouldn't be the case. Could you provide a plunker demonstrating that?  And check that when you remove the cellFilter, the cellTooltip works properly?

**Comment by yuetyeelo2855** [comment]
Sorry, i think i have a mistake.  the problem is the `cellFilter` is also append to the `cellTooltip`.
[Code](http://plnkr.co/edit/twStBE?p=preview)
