### ISSUE TITLE
Stylized header cell tool tip

### ISSUE THREAD

**Issue by ColcerP** [angular-ui/ui-grid#4761]
Hello. Is there a way to add some styling over the cell tool tip. I would like to have something like in the screenshot. Thanks you :)
![tooltip](https://cloud.githubusercontent.com/assets/6659895/11344287/edab659c-9218-11e5-8191-755a06be9a80.png)

**Comment by PaulL1** [comment]
You would need to use a custom cell template, unless you can use a css class that just applies to all tooltips.
