### ISSUE TITLE
pdf is overlapped if have more columns to export

### ISSUE THREAD

**Issue by sinntar** [angular-ui/ui-grid#4763]
Hi,

i have one grid which has more than 20 columns to export. but the pdf is overlapped. is there any suggestion for this issue? thanks.

**Comment by PaulL1** [comment]
PDFMake doesn't span multiple pages.  Realistically I wouldn't attempt to put 20 columns on a single page, it'll always look poor.  I'd either export only visible columns, or make your font very small.
