### ISSUE TITLE
DSSqlAdapter and query 'contains'

### ISSUE THREAD

**Issue by andrejkaurin** [angular-ui/ui-grid#4770]
Why this does not work for DSSqlAdapter (PostgreSQL)

{ where: { 'name': { 'contains': 'J' } }, limit: 1000, offset: 0 }

ERROR: [Error: Operator not found]

To compare - this works fine

{ where: { 'name': { 'in': ['John'] } }, limit: 1000, offset: 0 }

**Comment by andrejkaurin** [comment]
OK, this will work

{ where: { 'name': { 'like': 'J%' } }, limit: 1000, offset: 0 }

**Comment by imbalind** [comment]
I'm afraid you are posting this in the wrong place, this repo is for angular-ui's UI-grid. I'm closing this.
