### ISSUE TITLE
A number shows up right next to the sort direction arrow

### ISSUE THREAD

**Issue by lkkadiri** [angular-ui/ui-grid#4771]
There is a weird annoying number that shows up with the latest 3.0.7 release, right next to the sort direction arrow. We only noticed that not too long ago so figured its a new issue and seems like its a new visual bug that crept on 3.0.7. Dont know whether its a new feature or a bug and if its a feature it somehow needs to be turned off as it looks out of style and kinda buggy.
![screen shot 2015-11-24 at 2 08 44 pm](https://cloud.githubusercontent.com/assets/539311/11380727/12f69064-92b5-11e5-8682-92c33c35ebd2.png)

**Comment by imbalind** [comment]
That number represents the sorting priority of that column where 1 means the highest priority. You can add less priority sorting by clicking on the column header while pressing SHIFT (I'm not 100% sure about that, it could also be CTRL or ALT, anyway a modifier key).

So it's a new feature, definitely not a bug.
