### ISSUE TITLE
RTL scrollbar in wrong position on the left in Safari and iPad

### ISSUE THREAD

**Issue by sleepydisaster** [angular-ui/ui-grid#4773]
Steps to reproduce:
1) Open tutorial for RTL Support http://ui-grid.info/docs/#/tutorial/120_RTL in Safari.
2) Look at the table's scrollbar.
3) It is located on the right side.
4) Expected behaviour: As in Chrome browser in RTL layout scrollbar should appear on the left side.
5) Such behaviour also reproduces in mobile applications on iPad
5) Safari: Version 9.0.1 (10601.2.7.2)
    Chrome: Version 46.0.2490.86 (64-bit)
Chrome
![chrome](https://cloud.githubusercontent.com/assets/7901719/11403006/955e8f9c-93ab-11e5-8973-f4e147d1df28.png)

Safari
![safari](https://cloud.githubusercontent.com/assets/7901719/11403008/9674d2e2-93ab-11e5-90b1-ea99426c169f.png)

**Comment by sleepydisaster** [comment]
any ideas on this issue?

**Comment by dlgski** [comment]
scrollbar is on right for me, tested in Safari & iPad
