### ISSUE TITLE
Set One-Time-Binding on UIGrid

### ISSUE THREAD

**Issue by Havock94** [angular-ui/ui-grid#4774]
Hi,
I'm trying to set one-time-binding to the grid on the pages I'm sure the data will be static and won't be updated (I will eventually manually refresh the page).

I added to the cellTemplate the directive
<div ui-grid-one-bind-text="productname"></div>

But what I get is that all the columns are white.

Does anyone have any hint to achieve a one-time-binding? Thank you!

**Comment by PaulL1** [comment]
One time binding is not supported.  We refresh the bindings during scroll, so unless your grid never scrolls then one-time binding will result in breakage.
