### ISSUE TITLE
Shouldn't the "filterChanged" event at least return the column for which the filter has changed?

### ISSUE THREAD

**Issue by Rumeth** [angular-ui/ui-grid#4775]
UI Grid 3.0.6

The "filterChanged" event does not currently return anything as an argument.

The document specifies the following.

> **filterChanged**
> 
> is raised after the filter is changed. The nature of the watch expression doesn't allow notification of what changed, so the receiver of this event will need to re-extract the filter conditions from the columns.

This should mean that due to the watch expression, the old & new filter terms cannot be returned.

There seems to be only 2 instances in which the "filterChanged" event is raised.

Both of them have access to the column for which they are being raised & can be changed to the following.

> **restoreColumns**
> 
> ``` javascript
> grid.api.core.raise.filterChanged ( currentCol );
> ```
> 
> **onDownEvents**
> 
> ``` javascript
> uiGridCtrl.grid.api.core.raise.filterChanged ( $scope.col );
> ```

Is there any problem returning the column for for which the filter has changed?

**Comment by imbalind** [comment]
I cannot understand the issue. Is there a problem? Or are you suggesting an enhancement?

**Comment by Rumeth** [comment]
This can be taken as an Enhancement request.

The column argument will allow access to the changed column and also provide a way to access the grid without using "this" in strict mode.

**Comment by imbalind** [comment]
Ok, I see.

Do you have a use case where this would advantage you?

**Comment by Rumeth** [comment]
Yes.

There is no other way to access the grid from the handler except for "this" which is given in the tutorial. 

>```javascript
>$scope.gridApi.core.on.filterChanged( $scope, function() {
>          var grid = this.grid;
>          if( grid.columns[1].filters[0].term === 'male' ) {
>          } else if ( grid.columns[1].filters[0].term === 'female' ) {
>          } else {
>          }
>        });
>```

Or is there?

Using "this" in "strict" mode is not allowed.

Also, the specific column for which the filter has changed will be useful in updating the filter criteria.

>```javascript
>$scope.gridApi.core.on.filterChanged( $scope, function(column) {
>          var grid = column.grid;
>          if( column.filters[0].term === 'male' ) {
>          } else if ( column.filters[0].term === 'female' ) {
>          } else {
>          }
>        });
>```

**Comment by yesarpit** [comment]
Can someone provide workaround to find which column filter  has changed on filterChanged?
I see no other way but to reset all filters before new search is performed on external filters. My backend canot filter on multiple columns and hence I need to know only the column that has changed.

**Comment by Rumeth** [comment]
@yesarpit You will have to change the following lines in the "ui-grid.js" file.

>__restoreColumns__
>```javascript
> grid.api.core.raise.filterChanged ( currentCol );
>```

>__onDownEvents__
>```javascript
> uiGridCtrl.grid.api.core.raise.filterChanged ( $scope.col );
>```

This will return the current column for which the filter change event is being triggered.

**Comment by yesarpit** [comment]
Thank you Rumeth for quick response, let me give it a try.Though you mentioned this solution a few months back, i thought its already patched with latest version.

**Comment by PresidentCamacho** [comment]
Hi, Is there a way you can make this change in the official tree?

**Comment by jasonbrandt42** [comment]
i second this for main code branch.  And it cleans up error when multi-filters are used.  Error is when last multi-filter is 'x' ed out and the grid does not return properly to a no-filter state (it filters on "" ) incorrectly.
