### ISSUE TITLE
Field Safari Problem 

### ISSUE THREAD

**Issue by Fr4ncx** [angular-ui/ui-grid#4780]
![calendar](https://cloud.githubusercontent.com/assets/13225406/11444648/1538ae3e-9526-11e5-972e-2876835c3f9e.png)
On Chrome(I.E,Firefox) my ui-grid works well but in Safari i have some problem in displaying array of data
![calendar2](https://cloud.githubusercontent.com/assets/13225406/11444667/3ded3d90-9526-11e5-9dba-3c0f3519fa01.png)

I have this field stucture
```
{ name: 'data',cellEditableCondition: false,
            displayName:'',headerCellTemplate: $scope.headerToday,
            width: '10%', cellTemplate:'<div class="ERdateElemnet" style="text-align:center;" ng-repeat="item in row.entity[col.field]">{{item}}</div>',
            cellClass: function(grid, row, col, rowRenderIndex, colRenderIndex) {
              if (grid.getCellValue(row,col)[0] == "Sab" || grid.getCellValue(row,col)[0] == "Dom") {
                return 'blue';
              }
            }
          },
```
Any suggestion?

**Comment by imbalind** [comment]
Could you please build a plunker with your issue?

**Comment by Fr4ncx** [comment]
was a problem with dates on safari, sorry!
