### ISSUE TITLE
Grouping header row customize?

### ISSUE THREAD

**Issue by BaoyunChen** [angular-ui/ui-grid#4787]
When we grouping by a column the grid will display like:

        group  |subgroup|value
        IT     |        | 
               | IT1    |1
               | IT2    |34
        ACC    |        | 
               | ACC1   |43
But I would like it to display like below:

        group  |subgroup|value
        IT     |        | total:35
               | IT1    |1
               | IT2    |34
        ACC    |        | total:43
               | ACC1   |43
Is there anyway to do it?

**Comment by PaulL1** [comment]
Yes, that is standard behaviour if you use aggregations.  Check the tutorial.
