### ISSUE TITLE
After using i18nService.setCurrentLang so that menu options appear in the correct language, ui-grid-grouping errors 

### ISSUE THREAD

**Issue by dmGentil** [angular-ui/ui-grid#4789]
in the ui-grid code, i18nService.get() no longer has the grouping object property.  page then blows up with the error: Cannot read property 'group' of undefined
on the line for: var groupColumn =... title: i18nService.get().grouping.group

**Comment by mportuga** [comment]
I believe this was fixed by the following pull request: https://github.com/angular-ui/ui-grid/pull/6710
Test it in 4.4.9
