### ISSUE TITLE
enableFullRowSelection breaks Group Expansion

### ISSUE THREAD

**Issue by jarsnid** [angular-ui/ui-grid#4794]
When the gridOption enableFullRowSelection is true and the grid is grouped on a specific column, clicking on the [+] to expand a group will not work.  Here is a plunker (taken from the docs on selection and modified to include grouping) to demonstrate this:  http://plnkr.co/edit/nAJ6h07ksn1MIYcHpQ0Q?p=preview  (once inside this plunker, group on a column like age and then expand a group.  Then, toggle full row selection and attempt to either collapse the expanded group or expand a new group.)

**Comment by jarsnid** [comment]
To fix this, I commented out line 24599:  $elm.addClass('ui-grid-disable-selection'); which allowed group expansion even with enableFullRowSelection being on.

**Comment by lertoo** [comment]
This issue only affects IE11 and Chrome (v46-v47), but not IE10.

**Comment by MartijnWelker** [comment]
@lertoo this doesn't affect IE10 because IE10 [doesn't have support for pointer-events](http://caniuse.com/#search=pointer-events)

**Comment by tarzasai** [comment]
thank you @MartijnWelker (I've set it "auto" BTW)

**Comment by qichangjun** [comment]
it works , thanks @MartijnWelker
