### ISSUE TITLE
Cannot change i18nService gridMenu.columns default translation

### ISSUE THREAD

**Issue by kresic-ivan-nsoft** [angular-ui/ui-grid#4805]
Hi guys,

I cannot find a way to change the default translation for gridMenu.columns (saying "Columns:"). I found the getter method, getSafeText, but there is no setter to change it, or I cannot seem to find one. Something like i18nService.setText('gridMenu.columns', 'New text') would be great.

Any help?

**Comment by kresic-ivan-nsoft** [comment]
I made this, hope this [gist](https://gist.github.com/kresic-ivan-nsoft/67428699910bffa6d2e1) helps someone. Works like this:  
i18nService.setText('gridMenu.aria.buttonLabel', 'My new text');

**Comment by PaulL1** [comment]
You do that by altering the translation files.

**Comment by kresic-ivan-nsoft** [comment]
Well, I needed to dynamically insert a translated value from a controller :)

**Comment by gautamvbaindur** [comment]
Hi, I am also facing the same issue. I manage my own translations and I need a way to control the "Columns" text that appears in the grid menu? Is there a solution for this? I have also raised an issue about this - https://github.com/angular-ui/ui-grid/issues/5309

**Comment by luileito** [comment]
Hi, I also noticed that `i18nService.add()` has no effect either. The only way I found to make it working is by overriding the default English translations with the desired ones:
```
i18nService.add('en', {
  column: {
    hide: '¯\_(ツ)_/¯'
  }
});
```

**Comment by mportuga** [comment]
@luileito @kresic-ivan-nsoft @gautamvbaindur Here is a solution for this issue:
http://plnkr.co/edit/YQTm8dqRPVfTcrHNc0hy?p=preview
