### ISSUE TITLE
Date Formatting for CellFilter

### ISSUE THREAD

**Issue by jmuharsky** [angular-ui/ui-grid#4806]
I am trying to add a grid with a cellfilter for a date/time property.  I'm able to use the cellFilter property on the column to format the date in a variety of methods, but the text box for end-user filtering only seems to accept dates in the form "MMM dd yyyy".  Is there a way to customize the filter text parsing for dates?  It's important to have the display format be the same as the filter entry format, and I'd rather not have to display my dates in "MMM dd yyyy" form.

Thanks in advance.

**Comment by imbalind** [comment]
I can see two options here:

- create a custom headerCellTemplate with a custom filter.
- define a custom filter function as explained [here](http://ui-grid.info/docs/#/api/ui.grid.class:GridOptions.columnDef#properties_filter) <br/>
  condition defines how rows are chosen as matching the filter term. 
  This can be set to one of the constants in uiGridConstants.filter, or you can supply a custom filter function that gets passed the following arguments: [searchTerm, cellValue, row, column]

I'm closing this, feel free to reopen it if needed.

**Comment by ruhaise** [comment]
hey imbalind can you elaborate how i can implement this, i'm experirncing the same issue
