### ISSUE TITLE
Internationalization incorrect

### ISSUE THREAD

**Issue by adrien-be** [angular-ui/ui-grid#4811]
Hi guys,
I noticed that the column sorting is incorrect if I add an item with a diacritic, for instance "élodie".
Then add another item without diacritic and starting with the same letter but without diacritic, for instance "elsa".
One would expect these two to consistently be one after another. But whenever I reorder the column, their positions keep changing quite illogically.

I stumbled upon this string sorting in the past & it's a much harder task if internationalized.
You can read a simple solution on http://stackoverflow.com/questions/51165/how-do-you-do-string-comparison-in-javascript/26295229#26295229
Cheers,
Adrien

**Comment by imbalind** [comment]
Could you please edit one of the plunker in the tutorials so to show this behaviour?

**Comment by adrien-be** [comment]
Just tried it on Plunker, it actually looks fine: all the characters with a diacritic are consistently added in the same sort order. The sorting chosen can be considered awkward but that's another topic.

http://plnkr.co/edit/hOTVATmXHGMlViscMWDB?p=preview

I believe I missed the fact that the 3rd click puts the data back to the order in which it initially was.

**Comment by imbalind** [comment]
I guess your suggestion still holds about the sorting order and the use of `localeCompare()`.

I'm closing this, feel free to open another issue for the sorting order.

**Comment by adrien-be** [comment]
Not sure what sort order are implemented in each browser though. So I won't mention that, but `localeCompare()` definitely is the way forward.
