### ISSUE TITLE
i18nService.setCurrentLang('fr'); override

### ISSUE THREAD

**Issue by Kitcat711** [angular-ui/ui-grid#4813]
Hi,

i18nService.setCurrentLang('fr'); works fine.
with Html 
div   id="grid" ui-grid="gridOptions" class="grid"  ui-grid-resize-columns></div

but adding a height in my html just remove the translation:
div   id="grid" ui-grid="gridOptions" class="grid" ng-style="{height: {{tableHeight}}+'px'}"  ui-grid-resize-columns></div
The height style is ok.
Been reading docs and trying to change almast everything, I think that is an issue then.
Kitcat

**Comment by Kitcat711** [comment]
I can improve thins by adding ui-i18n="fr" but then I got an angular parse error:
https://code.angularjs.org/1.4.8/docs/error/$parse/syntax?p0=en&p1=is%20an%20unexpected%20token&p2=4&p3=fr%20en&p4=en

which appears to be weird for "fr" is my local language every where.

**Comment by imbalind** [comment]
Could you please provide a plunkr showing the issue?

**Comment by Kitcat711** [comment]
Here it is:
http://plnkr.co/edit/Z08PId?p=preview

**Comment by imbalind** [comment]
I'm not an ui-i18n expert but I tried moving the directive up a bit and it looks like it's working: http://plnkr.co/edit/DUJpD6?p=preview anyhow maybe you don't know it but ui-i18n is a different project then ui-grid, you can find its repo [here](http://plnkr.co/edit/DUJpD6?p=preview) in case you have further problems with it.

If this solved your problem, please close this issue.

**Comment by Kitcat711** [comment]
Hello,
I did the same:
Moving the ui-i18n="fr" up when declaring the module and it solved the problem.
Thanks a lot.

**Comment by Kitcat711** [comment]
The workaround does not work anymore. What has changed? 
Getting lost.

**Comment by cosmarvv** [comment]
For me it works: ui-i18n="'fr'"

**Comment by Kitcat711** [comment]
Tried. but same result. Thanks for your answer anyway
