### ISSUE TITLE
editDropdownOptionsFunction not working or being invoked

### ISSUE THREAD

**Issue by Hubbee** [angular-ui/ui-grid#4816]
I'm trying to dynamically populate a drop down using editDropdownOptionsFunction but can't get it working. 

In fact, not even the example at http://ui-grid.info/docs/#/tutorial/201_editable doesn't work regarding this feature, column Status. It seems that the function is never invoked. 

Or am I missing something here...?

**Comment by lsmaple** [comment]
I ran into the same problem. I have a column that needs a different subset of the available options based on a value in the entity and the function I assigned to editDropdownOptionsFunction is never getting called. I verified that the 'Status' field on the example page you showed doesn't work for me either.

**Comment by lsmaple** [comment]
I did a search of "editDropdownOptionsFunction" on the ui-grid.js file (version v3.0.7 - 2015-10-06) and it doesn't exist. There is no reference to the property.

**Comment by imbalind** [comment]
editDropdownOptionsFunction is a feature added after v3.0.7 was published, so you can find it in the master but not in the last stable version, I don't know why it got through in the stable docs section.
I'm gonna look into it.

Anyhow, it will be released in v3.0.8 but we still have no guess on when it will be released.
