### ISSUE TITLE
 Tutorial: 312 Exporting Data With Custom UI

### ISSUE THREAD

**Issue by mbellotto** [angular-ui/ui-grid#4817]
Hi,

HTML code of this tutorial has some errors. SELECT end tag is duplicated at lines 118, 123 & 129.

A semicolon also missing at line 136, after &nbsp.

Regards

**Comment by imbalind** [comment]
@mbellotto do you think you could provide a pull request?

**Comment by mbellotto** [comment]
Hi Matteo,

I tried to make a PR but it has been closed it and they suggest me to open it in a different place. To be honest I don't know how to used this tool.

I hope you can fix the code.

Regards.
