### ISSUE TITLE
filter:condition: uiGridConstants.filter.GREATER_THAN ERROR

### ISSUE THREAD

**Issue by EternalHunters** [angular-ui/ui-grid#4821]
when input number ,the filter has some error,example:'age' has 31.32.35.34.49..,when greater is 30 ,it have nothing

**Comment by imbalind** [comment]
The issue is not clear enough.

Please provide the steps needed to reproduce it or, even better, a plunker showing the issue.

I'm closing this for now, open it again if you have something clearer.
