### ISSUE TITLE
UI Grid menu does not hide when using Mozilla Firefox

### ISSUE THREAD

**Issue by Mortega92** [angular-ui/ui-grid#4823]
UI Grid menu does not hide when using Mozilla Firefox, but when using Google Chome, it works perfectly fine. Please advise
![ui-grid-menu-error](https://cloud.githubusercontent.com/assets/16202699/11676666/9f0a3acc-9e6f-11e5-9067-21e557a5a6e1.png)

**Comment by zalayeto** [comment]
It is happening to me as well.

**Comment by for-sagacity** [comment]
![ng-grid--issue](https://cloud.githubusercontent.com/assets/17128404/13462119/0b67d364-e0c9-11e5-9381-b0c069178ec5.png)

My firefox version is 44.0.2
ui-grid - v3.0.7
It's still dose not work properly until using below link's some code. 
https://github.com/angular-ui/ui-grid/issues/3978

**Comment by zalayeto** [comment]
Yes, this workaround works for me. Thanks @for-sagacity .
