### ISSUE TITLE
URGENT: No main files found

### ISSUE THREAD

**Issue by iredjee** [angular-ui/ui-grid#4827]
Bower installation
```
bower install angular-ui-grid
```
Add scripts to html file
```
<link rel="stylesheet" type="text/css" href="bower_components/angular-ui-grid/ui-grid.min.css">
<script src="bower_components/angular-ui-grid/ui-grid.min.js">
```
Bower `main` option also indicates these files
```
"main": ["./ui-grid.css", "./ui-grid.js"]
```
**Sorry, but I can't find these files in the root directory.**

In addition, there are no `ui-grid.woff` and `ui-grid.ttf` files within `css` directory.

**Comment by molecular** [comment]
same here

I'm also confused as to why I have to add <script/> and <link/> manually. For other stuff bower does this automagically.

**Comment by molecular** [comment]
solved for me:

https://github.com/angular-ui/ui-grid/issues/4947#issuecomment-219015652
