### ISSUE TITLE
IE11 font rendering issues.

### ISSUE THREAD

**Issue by skarnati** [angular-ui/ui-grid#4834]
The issue is specific to IE11. I have gone through the suggested ways of checking the installed fonts and have failed to solve this.
![ui-grid-ie11](https://cloud.githubusercontent.com/assets/4125675/11692503/c29146b8-9e6d-11e5-964b-3abea5a54212.png)

This also happens with the tutorials in ui-grid.info
IE version info
Version: 11.0.9600.18098
Update Versions: 11.0.25

**Comment by swalters** [comment]
Cannot recreate using IE11 and I don't see other reports about the same issue.
