### ISSUE TITLE
Unable to minify because of a wrong relative path. 

### ISSUE THREAD

**Issue by andCoffeeCode** [angular-ui/ui-grid#4844]
Hi,

When using bower to get ui-grid, it will generate the file 'ui-grid.css' in the root folder of 'ui-grid' and in this file has this wrong relative url '../font/ui-grid.svg?12312827#ui-grid' (which the parent folder is 'bower_components').

We are also using django-pipeline which verifies that the path is invalid.

PR #4840 should fix this problem.

Thx.

**Comment by victor-torres** [comment]
:+1:

**Comment by imbalind** [comment]
Merged in commit acce707
