### ISSUE TITLE
celltemplate ng-click event has no $event object

### ISSUE THREAD

**Issue by hxlniada** [angular-ui/ui-grid#4848]
cellTemplate:
```html
<button ng-click="someFunction($event)"></button>
```
controller:
```javascript
$scope.someFunction = function (event) {
    console.log(event);
}
```
the output is 'click' string. %>_<%

**Comment by imbalind** [comment]
We don't alter ng-click default behaviour and I used it myself on many occasions, so I guess this has nothing to do with ui-grid.

In orded to check that we need you to provide a way to replicate this. Could you please make a plunkr?

**Comment by hxlniada** [comment]
sorry, I use ng-autodisbale, It rewrite the the $event object.
%>_<%
