### ISSUE TITLE
RowTemplateFn per row with row as argument

### ISSUE THREAD

**Issue by MartijnWelker** [angular-ui/ui-grid#4853]
Hello,

Is there a reason the rowTemplate function isn't called once per row with the row as argument ? This way you don't have to do the logic in your template, you can just return a html string/element which can be compiled.

If necessary I can make a pull request with this functionality. 

Kind regards,
Martijn W

**Comment by PaulL1** [comment]
That sounds like it would seriously impact performance I think.  Although arguably we'd only do it on row load....but many of these things end up getting called on every digest cycle.

**Comment by MartijnWelker** [comment]
If you keep the function small with just 1 or 2 if's I don't see why this would be worse then inline ng-if's, I've implemented a simple version of this in my own code and I haven't noticed any difference yet, I'll try to run some benchmarks to see the actual difference

**Comment by MartijnWelker** [comment]
Coming back to this, I noticed that the performance is affected on larger datasets, seeming this is impossible for now.
