### ISSUE TITLE
UI grid refresh

### ISSUE THREAD

**Issue by Abhik-c** [angular-ui/ui-grid#4873]
Hi, I have a search form and on click of search button I am loading the grid. After I sort or filter, am again searching and clicking on the search button. This time it doesn't removes the sort or filter which I applied earlier. I need to refresh the grid. Please help me.

Thanks

**Comment by mgrivera** [comment]
Hi, could you try this: 
```javascript
ui_grid.ui_grid_Api.core.notifyDataChange(uiGridConstants.dataChange.ALL);
```
I've used it when, for example, I update some data in the grid **but** the the totals don't refresh themselves. 

Bye ...
