### ISSUE TITLE
Number of watchers created by ui-grid

### ISSUE THREAD

**Issue by patrickrioux** [angular-ui/ui-grid#4881]
Hi,

I have noticed that ui-grid create a high volume of watchers. 

As an example, I have 2 grids on the page and it add +164 watchers and I have just a single row and 4 columns in the first grid. The second gird is empty. I'm a bit worried about the number of watchers created by ui-grid and how it will behaves when I'll have more records created within the grid. 

I saw the documentation page where it talk about the performance but unfortunately it is unclear to me if there will be an initiative to enhance performance. Is there any alternative?  Do you have any suggestion?  Thank you.

**Comment by PaulL1** [comment]
The grid does create a lot of watchers, 164 is quite small considering.  At a minimum you get one per visible cell, plus one per row plus a couple per column header.

**Comment by patrickrioux** [comment]
Thank you for your answer. Will see how it goes when I will have more data.

**Comment by binal24** [comment]
I having same issue. I am having 850 records, it generates 3000 watchers in page.
If I am having more than 10,000 records, my app is crashing.
