### ISSUE TITLE
How to get page number and page size in angularjs ui grid

### ISSUE THREAD

**Issue by vickykrbu** [angular-ui/ui-grid#4883]
Hi All,

I am using angularjs ui grid. here i want to know if user has clicked on which page (page number) and if he has changed page size so the selected page size i can parse it to my business tier and get the data based on that.
is there any event to get the currently selected page number and page size?

**Comment by PaulL1** [comment]
There isn't an event, but you can read it directly out of the gridOptions I believe.  Check the pagination code, it's not very complicated.

**Comment by vickykrbu** [comment]
Hi Paul,
Thanks for your reply,
I checked pagination code, are you telling about this code which is below:
 $scope.gridOptions2.onRegisterApi = function (gridApi) {
    $scope.gridApi2 = gridApi;
  }
if yes, i tried this but when page loads ajax call is still continuing and not able to see the grid data.

**Comment by vickykrbu** [comment]
Hi All,

I need your help this is urgent for me.

**Comment by PaulL1** [comment]
No, I mean look at the pagination code in github, or the tutorial for pagination that I think reads the page numbers.  I think you can get it directly out of gridOptions the same way you set it - you can read it.

**Comment by DattatreyaDash** [comment]
//Let's assume that this is the way you declared the options for grid in your js page
$scope.gridCompleteOptions = {
            paginationPageSizes: [5, 10, 15],
            //multiSelect: false,
            //enableRowSelection: true,
            //enableRowHeaderSelection: false
        };

$scope.gridCompleteOptions.onRegisterApi = function (gridApi) {
            $scope.gridApiUsed = gridApi;

            $scope.gridApiUsed.pagination.on.paginationChanged($scope, function (pageNumber, pageSize)
            {                             
                pageNumberOrPageSizeChanged(pageNumber, pageSize);
            });    
        }

//This will help to get both when page size changes or page number changes
function pageNumberOrPageSizeChanged(pageNumber, pageSize)
{
          console.log("Received: pageNumber=" + pageNumber + ", pageSize= " + pageSize);
}

//If you want it in other way, write this anywhere you want
           console.log("Current page: " + $scope.gridApiUsed.pagination.getPage());
           console.log("Page size: " + $scope.gridCompletOptions.paginationPageSize);

**Comment by vickykrbu** [comment]
Thanks Dattatreya it's working for me.

**Comment by vamar797** [comment]
I am using angularjs ui grid, i have integrated external pagination, Sorting of the Columns are not working. How can I have sorting on the grid for multiple columns using pagination. Is there any solution to fix this?

**Comment by OnlyBelter** [comment]
see http://plnkr.co/edit/np6y6rgN1ThnT0ZqyJeo?p=preview, a whole version in Plnkr.
