### ISSUE TITLE
grid.appScope and ControllerAs

### ISSUE THREAD

**Issue by jweinstein92** [angular-ui/ui-grid#4886]
I'm having issues with accessing the scope from a cellTemplate on version 3.0.7. I have tried what was posted in the documentation and other places with no luck. I am trying to add a RowHeaderColumn to the grid and have a callback method triggered on click.

```
var vm = this;
vm.delete = function(row) {
    var foo = 1;
};
vm.gridOptions.appScopeProvider = vm;
vm.gridOptions.onRegisterApi = function(gridApi){
    //set gridApi on scope
    vm.gridApi = gridApi;
    var cellEditTemplate = 'grid-header-delete.tmpl.html';
    vm.gridApi.core.addRowHeaderColumn( { name: 'rowHeaderCol', displayName: '', width: 30, cellTemplate: cellEditTemplate} );
};
```

In cell template I have tried the following with no luck. Any ideas? I also tried setting appScopeProvider = this.
```
<div ng-click="grid.appScope.delete(row)">
    <i class="zmdi zmdi-delete"></i>
</div>

<div ng-click="vm.grid.appScope.delete(row)">
    <i class="zmdi zmdi-delete"></i>
</div>

<div ng-click="grid.appScope.vm.delete(row)">
    <i class="zmdi zmdi-delete"></i>
</div>
```

**Comment by j2L4e** [comment]
I've never set appScopeProvider when using controllerAs. Leave appScopeProvider alone and
`ng-click="grid.appScope.vm.delete(row)"`
should work

**Comment by rahulbhadhoriya** [comment]
@j2L4e thanks
