### ISSUE TITLE
How to detect ui-grid (value) - on a click - within Angular UI-Grid maybe from a cellTemplate ?

### ISSUE THREAD

**Issue by webia1** [angular-ui/ui-grid#4888]
Supposed, that is my grid:
```html
<div
    ui-grid="myAPI.myGrid"
    ui-grid-pinning
    ui-grid-pagination
    ui-grid-resize-columns
    class="gridMid">
</div>
```
I would like to detect/alert the name of the grid (in the case above `myApi.myGrid`) if I klick on a button, which is placed in the grid (e.g. in a cellTemplate).  How can I do that? 

Thank you, for your answer..

**Comment by AgDude** [comment]
I don't think that is possible. That really isn't a "grid name" it is a reference to a scope property. You could add a "name" to your gridOptions object, which you could then access with the public api.
