### ISSUE TITLE
cellTemplate: 'url' leads to empty grid

### ISSUE THREAD

**Issue by FrancescoRizzi** [angular-ui/ui-grid#4889]
Hi.
I took the plunkr from [305 - Accessing scope in templates](http://ui-grid.info/docs/#/tutorial/305_appScope) and tried to push the cell template into a separate template file.

[The resulting plunkr](http://plnkr.co/edit/Wj81epkthXG8MSG4M7Se?p=preview), as you can see, shows a blank/empty grid. If you have the browser Console open, you'll also see a message from angular indicating it is `fetching url button-column.html` (and the Network tab should show you the template file was received correctly).

From what I read around the tutorial (and other issues, such as [#611](https://github.com/angular-ui/ui-grid/issues/611) I should be able to use a url reference anywhere we can set a cell/header/footer template, but I'm clearly doing something wrong?

Thanks in advance

**Comment by jernejcic** [comment]
Your grid has to have data to display anything. You commented it the data out.

Here's a working plunkr: http://plnkr.co/edit/3SgaCU7NXt5gKa3ABgi9?p=preview

Also suggested to wrap your template with the ui-grid cell class.

**Comment by FrancescoRizzi** [comment]
Oh... My... sorry for making you do the work my eyes and brains should have done...
I promise I encountered this in a much more complicated example first, and eventually reduced it down to the plunkr above... I'll go back and figure out what else must be wrong in my actual case - at least your plunkr shows me the problem is not the url reference in templateCell!

Thanks again!

**Comment by jernejcic** [comment]
No worries. We've all been there. In fact I only stumbled on your issue
because I'm new to ui-grid and trying to figure out my own. Figured I could
help you with that one since I only figured it out a few hours earlier ;-).
