### ISSUE TITLE
how to sort numeric column in ui-grid.

### ISSUE THREAD

**Issue by sinntar** [angular-ui/ui-grid#4893]
hi.

i need to sort the numeric column, but now i am getting like 1, 15, 2 , 3... is there any suggestion or sample i can refer to implement 1 , 2, 3, 15 ... thanks,

**Comment by PaulL1** [comment]
You need to change the column type to (I think) numeric on the colDef.  Might be number.  Check the doco for type.

**Comment by sinntar** [comment]
Hi PaulL,

if in same column, i have both number and string..is there any way i can sort properly, just like i can get the number value first then show the string values? thanks.

**Comment by PaulL1** [comment]
Only with a custom sort function

**Comment by rappol** [comment]
Hi there, im using  type= 'number' for a column with decimal numbers ex: 10.2 but its not sorting properly. Is there another option?
