### ISSUE TITLE
Automatic CRUD generation via ngResource 

### ISSUE THREAD

**Issue by webia1** [angular-ui/ui-grid#4896]
I would like to achieve a CRUD-generation without repeating my code. I only want to tell (via parameter) which service should get CRUD masks. My grid should update both the model (e.g. $scope.customers) and via ngResource the connected service (e.g. rest-api/customers). I would only change ColumDefs for every grid, the rest of code would be the same.

There is  (http://brianhann.com/create-a-modal-row-editor-for-ui-grid-in-minutes/) a beautiful recipe for a modal editor but it can not be automated this way.

Is that possible with Angular-UI-Grid, if yes, dou have a recipe for me?

Many thanks for your feedback
kind greetings from Austria

**Comment by AgDude** [comment]
this does not appear to be a defect report, and outside the scope of ui-grid.

**Comment by webia1** [comment]
I've already a solution for your ui-grid on this purpose, but thank you for a reply..
