### ISSUE TITLE
Cancel navigation event

### ISSUE THREAD

**Issue by feralanPaladin** [angular-ui/ui-grid#4899]
Hi,

I am using "editableCellTemplate: 'ui-grid/dropdownEditor'" with cellNav function. That's why the down and up arrow events are catched by the cellNav logic and taken as navigation commands. So I can not navigate through dropdown list using the down and up arrow keys. This situation can be generated based on your tutorial (Tutorial: 201 Edit Feature). If you insert cellNav logic to the ui-grid, you will loose the navigation ability of the dropdown elements.

So I wander if you have any suggestion for me to catch the arrow events and cancel their propagation to the cellNav logic?

Thank you in advance

**Comment by imbalind** [comment]
I guess that's a design choice but I also think that up/down arrows should let you scroll the options in your dropdown instead of triggering navigation.

Inside tutorial 201 I found:

> Custom edit templates should be used for any editor other than the default editors, but be aware that you will likely also need to provide a custom directive similar to the uiGridEditor directive so as to provide BEGIN_CELL_EDIT, CANCEL_CELL_EDIT and END_CELL_EDIT events.

So maybe you can provide a custom uiGridEditor directive that could prevent cellNav logic.

**Comment by feralanPaladin** [comment]
In Tutorial 309, ui-grid team did use the cellNav and edit options together. In the tutorial the same issue also exist and dropdown is closed when you hit the down array button.
I will try the custom template solution, but this issue should be solved at least in the Tutorial 309.

**Comment by feralanPaladin** [comment]
Also in the ui-grid.js code uiGridEditDropdown directive has a comment as follows:
   *  Events that end editing:
   *     blur and enter keydown, and any left/right nav
So I think it is a simple bug for the uiGridEditDropdown  directive when using cellNav

**Comment by feralanPaladin** [comment]
I fix the issue with a little modification on the uiGridEditDropdown directive.
I just change the keydown event listener and and stast to listen for UP and DOWN button events.
A custom template can also solve the issue, but I am too lazy for that.
Thank you anyway :)
