### ISSUE TITLE
Incompatibility with grouping and enableFullRowSelection=true

### ISSUE THREAD

**Issue by patrickrioux** [angular-ui/ui-grid#4900]
Hi,

I'm using enableFullRowSelection/enableRowSelection=true.

When grouping on a specific column, I noticed the +- at the top grid level works good.
But the +- control at the group level (row level) is disabled by the class ui-grid-disable-selection.

When setting enableFullRowSelection=false, the +- at row level is working but I'm losing the row selection feature.

Is this is consider a bug?  

I wonder why we can't have the row selection and accessing the +- grouping button at the same time?

I think something is missing to the condition below:

            function registerRowSelectionEvents() {
              if ($scope.grid.options.enableRowSelection && $scope.grid.options.enableFullRowSelection) {
                $elm.addClass('ui-grid-disable-selection');

Thank you.

**Comment by rappol** [comment]
I had the same problem yesterday and in some issue..(i dont remember which one) someone told this would fix it (and for me was worked)

```
.ui-grid-cell.ui-grid-disable-selection.ui-grid-row-header-cell {
    pointer-events: all !important;
}
```

**Comment by patrickrioux** [comment]
Indeed, this fixed the issue. Thank you.
