### ISSUE TITLE
[ui-grid-selection] different rowHeight not evaluated

### ISSUE THREAD

**Issue by Irthen** [angular-ui/ui-grid#4901]
I just used a different rowHeight (e.g. 62) and the selection feature, see:
![ui-grid-selection](https://cloud.githubusercontent.com/assets/8327427/11973047/0ce88086-a955-11e5-9bea-e6e2f3e739a0.png)

In my opinion the "checkbox" should be vertically centered; it does not look fancy right now. Furthermore the whole cell should be clickable.

Please let me know if it's possible to do that in some way.

**Comment by imbalind** [comment]
You could theoretically override the default CSS style for the "checkbox" and customize it as you like. Did you try that?

**Comment by Irthen** [comment]
I did try that of course: height 100% for the checkbox cell and some css for vertical align; but that doesn't work.
