### ISSUE TITLE
treeview issues

### ISSUE THREAD

**Issue by HeavenlyHost** [angular-ui/ui-grid#4903]
When using ui-grid 3.0.6 there sometimes appears to be a render problem with the grid rendering of both the treeview node icons (the plus and minus symbols) and the tick selection icon, they are simply not drawn and remain invisible. I am trying to use this control as both a treeview and a standard grid (obviously not at the same time) but sometimes, not always, these icons are not displayed, the user can still click in and around the area and the correct functionality is fired but the icons in both cases remain invisible. This problem comes and goes but is now seen as a bug. Any ideas ?

**Comment by imbalind** [comment]
Never happened to me, can you build a plunkr to replicate it or is just random?
