### ISSUE TITLE
UI Grid, hide column option

### ISSUE THREAD

**Issue by Hasnaa-Ibraheem** [angular-ui/ui-grid#4905]
Would you please add this option: "enableHiding = false" on grid level, not only columnDef level?
Also I'd appreciate that you remove the reserved empty space for "Hide Column" option if the option is disabled.
Thanks in advance.

**Comment by AgDude** [comment]
I do not see an empty space. Provide a plunker please.

**Comment by Hasnaa-Ibraheem** [comment]
Thank you so much AgDude for following up, we resolved the issue of empty spaces from our side couple of days ago, it was an issue in our CSS.
However, I'd so much appreciate if you make the "enableHiding = false" option on the grid level and also gave us a shortcut API to reset sort in all columns at once
Thanks again

**Comment by AgDude** [comment]
We might consider a good quality pull request to add those options, as long as the api was similar to other options.
