### ISSUE TITLE
UIGRID Service call for each "+" button for treeview

### ISSUE THREAD

**Issue by phani2015** [angular-ui/ui-grid#4906]
Hi,

I want implement Rest full web service call for each treeview level (means each "+" button) in my grid, can you help me how to implement.

It is very urgent, can any one help me.

**Comment by rajan-hl** [comment]
looks like an interesting feature. if you are planing to write this feature, i can help

**Comment by phani2015** [comment]
Do you have any idea how to implement.

**Comment by phani2015** [comment]
Hi Rajan or any one, do you have anysolution for my requirement. I need to implement Category view in my uigrid, for clicking each + button.

**Comment by AgDude** [comment]
See the events in `treeBase` [api docs](http://ui-grid.info/docs/#/api/ui.grid.treeBase.api:PublicApi). You should be able to implement what you want using the public api.
