### ISSUE TITLE
Dynamically disable sorting on angular UI grid

### ISSUE THREAD

**Issue by maruthi1255** [angular-ui/ui-grid#4908]
I am trying to disable sorting on angular UI grid dynamically using the following code.(on some user UI action)
gridOptions.enableSorting = false
This is not working , can any one suggest how can we make it.

**Comment by maruthi1255** [comment]
How to disable column / table sorting (initially enabled)? What is an API for that? #4127
got the answer from this post, but we can still sort by clicking on the column header and you still see the up/down triangles.

**Comment by rajan-hl** [comment]
see this line of code, you might want to assign none as value to sort.direction
https://github.com/angular-ui/ui-grid/blob/master/src/templates/ui-grid/uiGridHeaderCell.html#L5

**Comment by AgDude** [comment]
Makes sure you are calling the notify data change api, documented here:
http://ui-grid.info/docs/#/api/ui.grid.core.api:PublicApi

If it still isn't working, please include a plunker exmple.
