### ISSUE TITLE
Dynamic Column

### ISSUE THREAD

**Issue by ganku007** [angular-ui/ui-grid#4910]
Hi,

I have used UI Grid.  I haven't defined column names in the GridOptions. I have just set the Json object as datasource and The UI grid is generated without any issues.

I want to change the style of the column.  I have tried by accessing the GridOptions in the scope but I could not find ColumnDef propery in GridOptions since I didn't defined column names in GridOptions.

How can i access the columns for the UI grid by code if the columns are automatically generated.

Regards,
Ganesh.

**Comment by twh1808** [comment]
This is something better suited for their [Gitter](https://gitter.im/angular-ui/ui-grid) page than an issue on Github.

That being said, there is a large documentation of their API found [here](http://ui-grid.info/docs/#/api). I'm having a hard time understanding what you want to do, besides "change the style". Do you mean you want to change `width`, `css`, `displayName`?

What I believe you're doing is following the [101 Tutorial](http://ui-grid.info/docs/#/tutorial/101_intro) which doesn't bind all options, it simply binds some data.

Instead try putting your data onto `gridOptions` then you should have access to everything on `gridOptions`, such as `gridOptions.columnDefs`, at any point after the grid is instantiated.
```
// Your data, whatever that may be
var data = [...];

// The grid options
$scope.gridOptions = {
    data: data
};

// Print out the grid options to show what I have access to
console.log($scope.gridOptions);
```
What will likely happen is you'll see a flash of the original grid, then whatever updates you make from there on out. It might not look pretty, but without defining `columnDefs` up front I'm not sure you can prevent it. However there are ways to show/hide until after you're done updating in order for the "flash" to be hidden from the end user.
