### ISSUE TITLE
Multi-line Headers with formatting in PDF export

### ISSUE THREAD

**Issue by dlgski** [angular-ui/ui-grid#4914]
I am trying to export my grid with a custom header.  My header is multi-line.  If I have no formatting, I can see all 3 lines.  But if I add the headerStyle, only 1 line shows, and it's formatted properly.  How can I get all 3 lines to show?

Here is a plunker to show the issue I'm having:
http://plnkr.co/edit/Bzn2a5w63ObOodR5BQZZ?p=preview

Also, is there a way to add a header to export by CSV?

**Comment by snkhan** [comment]
Did you find solution for multi line header?

**Comment by vishaloban** [comment]
used '\n' for break line

{text:['hello','\n','world']},
