### ISSUE TITLE
Can't reset the sorting info for the grid

### ISSUE THREAD

**Issue by rihamsamy** [angular-ui/ui-grid#4917]
Hi All,

Would you please let me know is it feasible to reset all the sorting info for the grid?
If I clicked on many of the headers to sort the data, so I need a way to reset all these sorting info at once instead of clicking on each header to remove the sorting.

FYI, I'm using (ui-grid - v3.0.7)
Would you please help ASAP?

Thanks in advace.

**Comment by benjaminmbrown** [comment]
Hi, check this out: http://ui-grid.info/docs/#/tutorial/102_sorting.

Maybe try something like:
    $scope.resetSorts= function() {
          angular.forEach($scope.YOURGRIDOPTIONS.columnDef, function(columnDef) {
                 columnDef.sort.direction = uiGridConstants.ASC;
            });
        }

**Comment by jainrahulkumar** [comment]
this solution did not work since columnDef.sort is undefined

**Comment by VelsP** [comment]
$scope.clearSort = function() {
    angular.forEach($scope.gridApi.grid.columns, function(col){
      col.unsort();
    });
 };
