### ISSUE TITLE
Feature Request: Column Menu Templates and Nested Menu

### ISSUE THREAD

**Issue by vdiazrj** [angular-ui/ui-grid#4919]
Support for a hierarchical column menu with the ability to specify a template or template URL for each menu item.

For instance, there could be a column menu called "Show/Hide Columns" that reveals a sub menu containing an input field and a list of columns with a checkbox next to the name of each column. The input field would be used to filter the list of columns and the checkbox is to toggle the visibility of each column.

![image](https://cloud.githubusercontent.com/assets/15878004/12066810/76a870d0-afb3-11e5-9336-5550b2429e67.png)

Or a sub-menu on a column to filter the column via user input.

![image](https://cloud.githubusercontent.com/assets/15878004/12066814/9b6ca616-afb3-11e5-9af4-837ebe5a1559.png)

Another example would be to simply categorize menu options so that you wouldn't be left with 15 top level option. Instead maybe, you would have 3 categories each with 5 options.

![image](https://cloud.githubusercontent.com/assets/15878004/12066828/d0ce4620-afb3-11e5-8279-3b97a319031c.png)

**Comment by anusha547** [comment]
Hi could you please provide the snippet for filters in column Menu,i am checking the feature same as above ,but i didn`t get any snippets.Could you please help on this?

**Comment by ajentering** [comment]
Hi @vdiazrj @anusha547 i am trying to achive the same but till now no luck, can you please provide any help on the same.
Thank you..
