### ISSUE TITLE
prevent scroll to top when clicking on show/hide columns menu icon

### ISSUE THREAD

**Issue by bostondevin** [angular-ui/ui-grid#4921]
If the table is half way down the page, when I click on the icon which allows me to control the columns that are displayed, the menu opens, but it's forcing the page to scroll to the top. 

When I have a bunch of columns and the menu itself scrolls, when I click on an individual option in the menu, it forces the menu to scroll to the top as well.

**Comment by swalters** [comment]
@JLLeitschuh is this caused by aria implementation?

**Comment by bostondevin** [comment]
Nah - not that. It's a combo of the two switches which are negating the behavior of that checkbox

**Comment by SMauser** [comment]
We have the same issue in our application. Are there any update or workaround here?

**Comment by SuprasannaBhaumik** [comment]
Check the fix provided by @ChrisWiGit 
 https://github.com/angular-ui/ui-grid/issues/4623
