### ISSUE TITLE
No way to programmatically unfocus cell

### ISSUE THREAD

**Issue by JZehet** [angular-ui/ui-grid#4924]
After reading https://github.com/angular-ui/ui-grid/issues/3815 i found no clean solution to unfocus a cell after setting new data. The class .ui-grid-cell-focus is still attached. Is it possible to have clearfocus() as a part of the public api ?

  http://plnkr.co/edit/MJGJzz?p=preview

**Comment by pjwalmsley** [comment]
+1

**Comment by mborca** [comment]
+1

**Comment by zamb3zi** [comment]
+1

**Comment by cvanes** [comment]
+1

**Comment by binaworks** [comment]
+1

**Comment by jamadagniVijay** [comment]
+1
