### ISSUE TITLE
rowSelectionChanged event not fired on shift+click

### ISSUE THREAD

**Issue by jdfwarrior** [angular-ui/ui-grid#4926]
I'm currently using version 3.0.0-rc22-42412c and have noticed that when the modifierKeysToMultiSelect option is enabled, the api.selection.on.rowSelectionChanged event isn't fired when the user shift+click's to select a span of rows. It fires normally on ctrl+click, but not shift+click. I checked updated versions but didn't see the fix posted in the change log.

**Comment by tjamin** [comment]
I can confirm this bug. Here is a plunker to demonstrate the behavior:
http://plnkr.co/edit/u5pzISURTnvPBm9FyiLr?p=preview
Any plans to fix it?

**Comment by sssalib42** [comment]
Yes! Same here... Do you guys know of a workaround until the bug is fixed?

**Comment by binaworks** [comment]
Found the solution [here](http://stackoverflow.com/questions/29247032/angular-ui-grid-event-row-selected).
Use rowSelectionChangedBatch
