### ISSUE TITLE
Doesn't Export to CSV when used with IONIC

### ISSUE THREAD

**Issue by bpasham** [angular-ui/ui-grid#4930]
I am trying to use UI-GRID with IONIC framework, and export to CSV doesn't work. Export to pdf is working is working fine though. I am using Ionic 1.1.1 and uiGrid 3.0.7 with Angular 1.4.3

**Comment by AgDude** [comment]
My guess is that cordova won't let you download a file. I suspect you will need to use a plugin for that. Please provide a plunker/codepen that demonstrates the issue.

**Comment by bpasham** [comment]
It is working to download the pdf export. Just not CSV.

On Tuesday, January 12, 2016, Nate Dudenhoeffer <notifications@github.com>
wrote:

> My guess is that cordova won't let you download a file. I suspect you will
> need to use a plugin for that. Please provide a plunker/codepen that
> demonstrates the issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui/ui-grid/issues/4930#issuecomment-171023591>
> .
>


-- 
Bhuvan Pasham
+1 (516) 777-0884

**Comment by AgDude** [comment]
CSV and PDF exports work very differently internally.

The core team on this project has very limited time, if you can provide a reproducible example, this might get some attention. We do no officially support cordova, and will not be testing in cordova.

**Comment by PaulL1** [comment]
The code for exporter, and in particular csv export download, is very simple.  It should be reasonable easy for you to debug this yourself.

**Comment by gine** [comment]
My application work with ionic too and i was stucked on this problem for 3 hours.

yep CSV and PDF exports work very differently internally. Pdf use pdfmaker the FileSaver function SaveAs(blob, filename). 

```
downloadPDF: function (fileName, docDefinition) {
  var D = document;
  var a = D.createElement('a');
  var strMimeType = 'application/octet-stream;charset=utf-8';
  var rawFile;
  var ieVersion;

  ieVersion = this.isIE(); // This is now a boolean value
  var doc = pdfMake.createPdf(docDefinition);
  var blob;

  doc.getBuffer( function (buffer) {
    blob = new Blob([buffer]);

    // IE10+
    if (navigator.msSaveBlob) {
      return navigator.msSaveBlob(
        blob, fileName
      );
    }

    // Previously:  && ieVersion < 10
    // ieVersion now returns a boolean for the
    // sake of sanity. We just check `msSaveBlob` first.
    if (ieVersion) {
      var frame = D.createElement('iframe');
      document.body.appendChild(frame);

      frame.contentWindow.document.open("text/html", "replace");
      frame.contentWindow.document.write(blob);
      frame.contentWindow.document.close();
      frame.contentWindow.focus();
      frame.contentWindow.document.execCommand('SaveAs', true, fileName);

      document.body.removeChild(frame);
      return true;
    }
  });
},
```

The csv set an hidden link and then trigger a click on it with a timeout:

```
downloadFile: function (fileName, csvContent, columnSeparator, exporterOlderExcelCompatibility) {
  var D = document;
  var a = D.createElement('a');
  var strMimeType = 'application/octet-stream;charset=utf-8';
  var rawFile;
  var ieVersion = this.isIE();

  // IE10+
  if (navigator.msSaveBlob) {
    return navigator.msSaveOrOpenBlob(
      new Blob(
        [exporterOlderExcelCompatibility ? "\uFEFF" : '', csvContent],
        { type: strMimeType } ),
      fileName
    );
  }

  if (ieVersion) {
    var frame = D.createElement('iframe');
    document.body.appendChild(frame);

    frame.contentWindow.document.open('text/html', 'replace');
    frame.contentWindow.document.write('sep=' + columnSeparator + '\r\n' + csvContent);
    frame.contentWindow.document.close();
    frame.contentWindow.focus();
    frame.contentWindow.document.execCommand('SaveAs', true, fileName);

    document.body.removeChild(frame);
    return true;
  }

  //html5 A[download]
  if ('download' in a) {
    var blob = new Blob(
      [exporterOlderExcelCompatibility ? "\uFEFF" : '', csvContent],
      { type: strMimeType }
    );
    rawFile = URL.createObjectURL(blob);
    a.setAttribute('download', fileName);
  } else {
    rawFile = 'data:' + strMimeType + ',' + encodeURIComponent(csvContent);
    a.setAttribute('target', '_blank');
  }

  a.href = rawFile;
  a.setAttribute('style', 'display:none;');
  D.body.appendChild(a);
  setTimeout(function() {
    if (a.click) {
      a.click();
      // Workaround for Safari 5
    } else if (document.createEvent) {
      var eventObj = document.createEvent('MouseEvents');
      eventObj.initEvent('click', true, true);
      a.dispatchEvent(eventObj);
    }
    D.body.removeChild(a);

  }, this.delay);
},
```

You can fix it with:

```
..
if(window.ionic && window.saveAs){
  saveAs(blob, fileName);
} else if (a.click) {
  a.click();
}
...
```
Here the plunker to reproduce the problem: http://plnkr.co/edit/rb0JFHYr1LGPzscFYAmm?p=preview
Builded from the example on this page: http://ui-grid.info/docs/#/tutorial/206_exporting_data

I hope that this problem will be fixed on next release.
