### ISSUE TITLE
First item in grid not editable when using dropdownEditor and rowheight < 30

### ISSUE THREAD

**Issue by dietergoetelen** [angular-ui/ui-grid#4933]
The column where you use dropdownEditor is not editable when you change the rowheight from the default to i.e. 25.

In the plunkr below I reproduced this bug, try to change the gender on the first row:
http://plnkr.co/edit/EOPDWo5fxFonhgxkdYLg?p=preview

**Comment by mgrivera** [comment]
Hi, I'm facing this issue too. I upgraded ui-grid from 3.0.5 to 3.0.7, but the issue remains. Worked fine with previous versions of ui-grid. I suppose this issue is related to a very recent version. 
Thanks and bye ...

**Comment by B8li** [comment]
Hi @dietergoetelen , 
Issue has been fixed with latest release 3.1.0. You can test the same plunkr and close the issue if everything is fine with latest version 3.1.0.

**Comment by dietergoetelen** [comment]
@B8li indeed it's all working as expected, thanks!
