### ISSUE TITLE
Changing the columns order in export 

### ISSUE THREAD

**Issue by vattipalli** [angular-ui/ui-grid#4934]
I was wondering if there is a flexibility to change the order of columns appearing in a pdf and excel sheet in grid options. (columndefs).
I need to reorder the columns in my downloaded pdf file. Is it possible?

**Comment by AgDude** [comment]
Yes, use the move columns feature. If you mean a different order than displayed, no. In that case you would need to use the publicApi to change to the order, then change it back after the export.
