### ISSUE TITLE
cellTemplate IE not working

### ISSUE THREAD

**Issue by OpsRJ** [angular-ui/ui-grid#4935]
If u put a variable inside any attribute of the the div:.

` { name: 'cores', field: 'widgets', cellTemplate: '<div style="background-color:{{ANY_VAR}}"></div>' }`

It doesnt work on IE. the angular var is not complied and ie ignores it. But if u out the variable inside the div it works. 

` { name: 'cores', field: 'widgets', cellTemplate: '<div style="background-color:#CECECE">{{ANY_VAR}}</div>' }` -> It works!

**Comment by pinkgom** [comment]
I had a same problem, too. Chrome works well, but IE11 doesn't.

**Comment by OpsRJ** [comment]
I managed to get it working in IE11 with a directive and inside it, i´m observing the attribute changes and applaying it.

**Comment by swalters** [comment]
This is a known issue with IE and angular.  you should use ng-style

**Comment by arwindraj** [comment]
use ng-attr-style instead of style and it will work with IE
