### ISSUE TITLE
enableFullRowSelection + enableRowHeaderSelection causes checkbox to become uncheckable

### ISSUE THREAD

**Issue by bostondevin** [angular-ui/ui-grid#4938]
I have both these options enabled in the grid, and when I do this, the row is selectable, but the checkbox on the left stops working. If I turn off enableFullRowSelection the checkbox becomes selectable again. 

enableFullRowSelection: true, enableRowHeaderSelection: true,

**Comment by PatrickMennen** [comment]
Seems like a bug in the implementation and it has been reported since the commit was made in May 2015. I can confirm that this issue is still in the most active release.

**Comment by gzinger** [comment]
Is there a workaround?

**Comment by mabi** [comment]
@gzinger see #4548 for a workaround
