### ISSUE TITLE
Replacement for width:"*" in angular ui-grid 3.x

### ISSUE THREAD

**Issue by uday-sharma** [angular-ui/ui-grid#4942]
Do we have a replacement for width:"*" for setting automatic column width  in angular ui-grid 3.x? If not are there any other ways to do this without affecting the performance(like columnApi or overriding css in ui-grid.css)?

**Comment by AgDude** [comment]
`*` is a valid width. Please search the api docs before opening feature request tickets.
http://ui-grid.info/docs/#/api/ui.grid.class:GridOptions.columnDef
