### ISSUE TITLE
allRowsVisible rows processor function is registered with undefined priority

### ISSUE THREAD

**Issue by czyzm** [angular-ui/ui-grid#4945]
There is a simple mistake made when registering rows processor function allRowsVisibile. The priority 50 that should be used for this processor is passed to forEach function instead of the registerRowsProcessor function:

```
      // Reset all rows to visible initially
      grid.registerRowsProcessor(function allRowsVisible(rows) {
        rows.forEach(function (row) {
          row.evaluateRowVisibility( true );
        }, 50);

        return rows;
      });
```

As a result the allRowsVisible processor is registered with undefined priority.

**Comment by mportuga** [comment]
https://github.com/angular-ui/ui-grid/pull/6456/commits/b223f012ec419812434469cd3660df066933943b
