### ISSUE TITLE
help! ui-grid.min.js and CSS MISSING ... ???

### ISSUE THREAD

**Issue by DaveBGld** [angular-ui/ui-grid#4947]
After intalling with bower install angular-ui-grid

these module files are not installed 

   bower_components/angular-ui-grid/ui-grid.min.css
   bower_components/angular-ui-grid/ui-grid.min.js

I downloaded the zip file and they are not there either... 

They dont seem to be on the git page either  at https://github.com/angular-ui/ui-grid 

Many thanks!

**Comment by AgDude** [comment]
I just tried a bower install, and it appears to be working fine. The dist files are not in git, but they are available for download at www.ui-grid.info

**Comment by DaveBGld** [comment]
When I do a bower install ui-grid, I get the exact copy of what's on Git.What bower install do you do? Why would I get the wrong repository?David


-------- Original Message --------
Subject: Re: [ui-grid] help! ui-grid.min.js and CSS MISSING ... ???
(#4947)

**Comment by pete-otaqui** [comment]
I found the same issue.  I'm using `node v5.4.1`, `npm 3.5.3` and `bower 1.7.2`.

I ran `bower install angular-ui-grid`, the project was installed in `bower_components/angular-ui-grid/`, but there were no `ui-grid.min.css` or 'ui-grid.min.js`files.

The [Bower section of the README](https://github.com/angular-ui/ui-grid/blob/3663aa/README.md#bower) states that there should be these files after a bower install.

**Comment by pete-otaqui** [comment]
I also tried running `npm install` and the `grunt -h` from the `bower_components/angular-ui-grid` directory, but it returns an error about both "Loading Grunt tasks" and being unable to find `lib/test/angular/files.json`, so clearly this isn't an exact replica of the source git repository either.

**Comment by molecular** [comment]
> I upgraded bower to 1.7.7 and now it seems to work fine, with the latest angular-ui-grid 3.1.0 - back to the proper distribution files installed by bower (and not the source git repo).

I have the same problem, even with bower 1.7.7 (which I already had).

What's the deal, how to solve this? Any hints?

**Comment by molecular** [comment]
seems bower is pulling the wrong repo `https://github.com/angular-ui/ui-grid` instead of `https://github.com/angular-ui/bower-ui-grid`

**Comment by molecular** [comment]
Strange: it seems bower is pulling the correct repo:

```
(venv) nick@dose  (master) ~/daisy/rs/site4\> bower -V install angular-ui-grid
bower cached        https://github.com/angular-ui/bower-ui-grid.git#3.1.1
bower validate      3.1.1 against https://github.com/angular-ui/bower-ui-grid.git#*
bower install       angular-ui-grid#3.1.1
```

but the files are not there

```
(venv) nick@dose  (master) ~/daisy/rs/site4\> ls bower_components/angular-ui-grid
bower.json  less  README.md
```

whereas a manual git clone of the same repo `https://github.com/angular-ui/bower-ui-grid.git` actuall *has* the files:

```
nick@dose  /tmp\> git clone https://github.com/angular-ui/bower-ui-grid.git
Cloning into 'bower-ui-grid'...
remote: Counting objects: 302, done.
remote: Total 302 (delta 0), reused 0 (delta 0), pack-reused 302
Receiving objects: 100% (302/302), 2.14 MiB | 923.00 KiB/s, done.
Resolving deltas: 100% (159/159), done.
Checking connectivity... done.
nick@dose  /tmp\> cd bower-ui-grid/
nick@dose  (master) /tmp/bower-ui-grid\> ls
bower.json  package.json  ui-grid.css  ui-grid.js       ui-grid.min.js  ui-grid.ttf
less        README.md     ui-grid.eot  ui-grid.min.css  ui-grid.svg     ui-grid.woff
```

**Comment by molecular** [comment]
I solved the issue by:

```
#> bower cache clean
#> rm -rf bower_components
#> bower install
```
