### ISSUE TITLE
ui-grid gridFooter filter feature request

### ISSUE THREAD

**Issue by kenwilcox** [angular-ui/ui-grid#4954]
First off I'd like to thanks the folks involved for making ui-grid. I've enjoyed using it in my projects.

I'm currently using the grid footer to display the number of rows, the filtered rows and the selected rows. However the amount of data that's displayed can be in the thousands of records. Since it's usually over a thousand rows I'd like to filter the results as a number - the users like to see the thousands separator.

So I've hacked something together like so for my gridFooterTemplate

``` html
<div class="ui-grid-footer-info ui-grid-grid-footer">
    <span>{{'search.totalItems' | t}} {{grid.rows.length | number}}</span>
    <span ng-if="grid.renderContainers.body.visibleRowCache.length !== grid.rows.length" class="ngLabel">
        ({{"search.showingItems" | t}} {{grid.renderContainers.body.visibleRowCache.length | number}})
    </span>
    <span ng-if="grid.selection.selectedCount !== 0 && grid.options.enableMyFooterTotalSelected" class="ng-binding ng-scope">
        ({{"search.selectedItems" | t}} {{grid.selection.selectedCount | number}})
    </span>
</div>
```

All that I'm doing is combining the ui-grid-grid-footer.html and gridFooterSelectedItems.html templates and adding a number filter to the values. I've also added a enableMyFooterTotalSelected grid option so I can enable that and disable the enableFooterTotalSelected so the default, unfiltered value, isn't shown.

This is an ugly hack and I'd like to fix it. 

I see that the uiGridFooterCell.html uses CUSTOM_FILTERS, and that would be great to add something like that to the grid footer. Would this be the direction to go, or would it just be easier to create a PR with the number filter applied like above? Doing something like CUSTOM_FILTERS it seems like one would have to add gridFooterTotalFilter, gridFilterVisibleFilter and gridFooterSelectedFilter or just a gridFooterFilter and apply it to all three. Honestly I'm kinda lost going this route, but I'm willing to try.

I can't see why anyone would not want the values filtered as a number, and that would be an easier patch.

Thoughts/Direction?
Thanks

**Comment by PaulL1** [comment]
I think the problem is that we can never do 100% of what everyone might want, so we try to cover the most common use cases, and people can tailor the templates if they want something more obscure.

On that basis, I think it is reasonable to create a single filter (CUSTOM_FILTERS) and apply to all three numbers similar to what we do in the other areas of the grid.  If people happened to want different filters for the different numbers then that's when they'd need to directly tailor the template.

Does that make sense?

**Comment by kenwilcox** [comment]
Yes it does - I'll see if I can figure it out - thanks

**Comment by kenwilcox** [comment]
Bummer - PhantomJS Failed on the default grunt task - tail of the log - master branch (cad146b)

```
PhantomJS 1.9.8 (Windows 7 0.0.0): Executed 671 of 676 DISCONNECTED (1 min 28.52
 secs / 42.753 secs)
INFO [karma]: Restarting PhantomJS 1.9.8 (Windows 7 0.0.0) (2 of 2 attempts)
INFO [PhantomJS 1.9.8 (Windows 7 0.0.0)]: Connected on socket z199iD3EnNUvJA2b6i
Un with id 99952903
................................................................................

................................................................................

................................................................................

................................................................................

................................................................................

................................................................................

................................................................................

................................................................................

................................ERROR [launcher]: PhantomJS crashed.

ERROR [launcher]: PhantomJS failed 2 times (crashed). Giving up.
Warning: Task "karma:angular-1.3.0" failed. Use --force to continue.

Aborted due to warnings.


Execution Time (2016-01-12 22:14:49 UTC)
jshint:src_test         4.1s  █ 1%
karma:angular-1.2.14   47.7s  ██████ 13%
karma:angular-1.2.26   43.4s  █████ 12%
karma:angular-1.2.8    45.2s  █████ 12%
karma:angular-1.3.0   3m 42s  ████████████████████████ 60%
Total 6m 10.2s
```

I'll try it on a different machine.
