### ISSUE TITLE
No way to change header row height in 3.0?

### ISSUE THREAD

**Issue by tapresle** [angular-ui/ui-grid#4956]
I was looking at the configuration options: https://github.com/angular-ui/ui-grid/wiki/configuration-options and saw `//The height of the header row in pixels.
        headerRowHeight: 30,` but that doesn't seem to work anymore. Anyone else have a workaround?

**Comment by ChrisHuston** [comment]
You can do this with CSS:

.grid .ui-grid-header-cell {
    height: 30px;
}

Where "grid" is your class defined for your grid.

**Comment by tapresle** [comment]
Unfortunately that can have side effects. Also don't see a reason as to why there is a rowHeight attribute but not headerRowHeight anymore.

**Comment by ctysingh** [comment]
I am also facing this issue with version 3.1 . Is there anyone who is able to fix this with CSS settings?

**Comment by tapresle** [comment]
@ctysingh I followed @ChrisHuston's suggestion but needed to use

.grid .ui-grid-header-cell {
height: 30px !important;
}

because my grid was initially hidden and I had some weird issues with UI-Grid's CSS overriding mine. I also had another requirement to change the height based on certain criteria so I had to do that using Javascript.

**Comment by murarivarma** [comment]
# Use this in your CSS.

    .ui-grid-header-cell-primary-focus {

      line-height: 2.428571;

    }
