### ISSUE TITLE
suggestion: uiGridAutoResize can use a uiGridAutoResizeContainer directive

### ISSUE THREAD

**Issue by gpalmer1984** [angular-ui/ui-grid#4957]
Make a directive for an attribute to declare the grid container (ui-grid-auto-resize-container) which will then store the dimensions into the gridUtil service.  I then use ng-style and access the dimensions in the service to set the desired dimensions.

    app.directive('uiGridAutoResizeContainer', function(gridUtil){
        return {
            controller : function($element, $timeout){
                var resizeHandle = null;
                function getDimensions(){
                    if (resizeHandle){$timeout.cancel(resizeHandle);}
                    resizeHandle = $timeout(function(){
                        gridUtils.autoResizeHeight = $element[0].clientHeight;    
                        getDimensions();
                    }, 250);
                }
                getDimensions();
            }
        };
    });

**Comment by AgDude** [comment]
This looks like a PR not an issue. What problem is it solving?
