### ISSUE TITLE
No empty message capability

### ISSUE THREAD

**Issue by jadrake75** [angular-ui/ui-grid#496]
The grid should be able to display a message / row of text in the grid if there is no content in the data array. Something like "No xxx found" etc.  This is consistent with other grids available.  I could swing this with a directive and showing/hiding a div in ngViewport but it would be better if this was provided as part of the component.

**Comment by sryzycki** [comment]
Hey guys. I'd like to upvote this feature but this time for ui-grid 4.x.

The ng-transclude method is great but to display a "no results" text below the table header you'd need to know its height in pixels which vary depending on filters that are displayed.

It would be nice to have an "input" property available e.g on the `<div ui-grid ui-grid-message="$ctrl.emptyListMessage"></div>`. If it's set, it's shown.

I could create a PR if you guys point me at the right direction.
