### ISSUE TITLE
[Feature Request] Grouping of value ranges

### ISSUE THREAD

**Issue by andreaswegge** [angular-ui/ui-grid#4966]
Hi! 

I think the grouping feature is missing something important: some sort of quantitative Grouping for numeric values.

For example take your standard example (http://ui-grid.info/docs/#/tutorial/209_grouping):
 
Now you want to analyse your data by age range: What's the balance of 20-25 year olds?

Or by balance range: What do people with a balance <2000$ have in common?

That's something you can't easily do right now with grouping (maybe write your own groupingColumnProcessor?) and I feel like it is a core feature for a grouping functionality.

Best,
Andreas

**Comment by AgDude** [comment]
http://ui-grid.info/docs/#/tutorial/320_complex_grouping shows some examples of how to write grouping functions. It is not very difficult. This isn't something likely to land in the core, since it would require a new UI, which would be difficult to make flexible enough to cover most cases.
