### ISSUE TITLE
If I disable hide in all columns, exporter menu still has an entry for "Columns:" 

### ISSUE THREAD

**Issue by billyaraujo** [angular-ui/ui-grid#4971]
If I disable hide in all columns, exporter menu has an unnecessary entry for "Columns:" with nothing underneath.

![image](https://cloud.githubusercontent.com/assets/5067963/12356194/1f552eee-bb99-11e5-915f-3f28170d6949.png)

http://plnkr.co/edit/0Y1tI2wKJXzAr5r4eUrZ?p=preview

**Comment by murtazajafferji** [comment]
Set `gridMenuShowHideColumns` in your `gridOptions` to `false`.
http://plnkr.co/edit/bjKnWQN8B8DRrdtwf0Bs?p=preview

**Comment by billyaraujo** [comment]
Thanks @murtazajafferji
