### ISSUE TITLE
Unpinned columns got automatically pinned again after column moving

### ISSUE THREAD

**Issue by nighantom** [angular-ui/ui-grid#4972]
http://plnkr.co/edit/N3AYS5PdbZsuYFFSYdws?p=preview

Steps to reproduce:
1. Unpin "Name" column
2. Move "Age" column forward or backward

Result:
"Name" column got pinned again

Expected:
"Name" column should NOT be automatically pinned after other column moving

**Comment by yccteam** [comment]
#5015
