### ISSUE TITLE
iPad scrolling shows empty unrendered lines until scroll stops (a lot of time) 

### ISSUE THREAD

**Issue by ekiran** [angular-ui/ui-grid#4979]
iPad scrolling shows empty unrendered lines until scroll stops (a lot of time).
when scrolling in iPad up and down and giving it a momentum of scroll it takes a lot of time for it to stop and meanwhile (can be 5+ sec of slowing down animation) you only see an empty white grid.
tested on iPad.
Please suggest !!!

**Comment by dlgski** [comment]
this may be resolved in next release 3.2.7

If it is still an issue, please open an issue with a plunker so it can be reproduced
