### ISSUE TITLE
grouping and selection, selectAll use case

### ISSUE THREAD

**Issue by gpalmer1984** [angular-ui/ui-grid#4983]
When I select all on the [complex grouping tutorial](http://ui-grid.info/docs/#/tutorial/320_complex_grouping) the group header rows are not selected.  This can result in a confusing user experience.  This seems like a simple problem which I am willing to fix in my controller within the api.selection.on.rowSelectionChangedBatch function by setting all of the internal group checkboxes based upon the selectAllState.

The second more advanced use case which might fit into addressing the first use case is that selecting rows within a group individually could reflect in the group check state.  I suggest a tri-state checkbox for these situations.

Thank you for your help.

**Comment by gpalmer1984** [comment]
I found how to change the checkbox programmatically:
```
    api.grid.treeBase.tree.forEach(function(branch){
        branch.row.isSelected = false;
    });
```

**Comment by yccteam** [comment]
I've actually implemented this for my own grid in my app.  Unfortunately it is an offline app.  I'll try to reproduce the code here ASAP.
