### ISSUE TITLE
[sortChanged Event] Doc and Implementation Mismatch - What Should We Do?

### ISSUE THREAD

**Issue by lpand** [angular-ui/ui-grid#4984]
Documentation and implementation of the `sortChanged` event don't match. The [documentation](https://github.com/angular-ui/ui-grid/blob/master/src/js/core/factories/Grid.js#L392) says the callback is invoked with just the sorted columns array, whereas in at least two different places ([Core](https://github.com/angular-ui/ui-grid/blob/master/src/js/core/factories/Grid.js#L1992) and [Save State](https://github.com/angular-ui/ui-grid/blob/master/src/features/saveState/js/saveState.js#L584)) the event is raised with the grid and list of columns.
If this behavior is coherent across event callback signatures, that is the first argument is always the grid, i'd say let's change the doc, otherwise the code (and i could make a pull request). What do you think about it?

**Comment by swalters** [comment]
I haven't dug into it, but for a lot of API's, sending the grid is redundant.  The api has a reference to the grid, so it doesn't need it as an argument.  But that would be a breaking change so it's best for now to fix the doc.

**Comment by lpand** [comment]
Ok, i'll make a pull request with the edited documentation.
