### ISSUE TITLE
Header menu not working with firefox

### ISSUE THREAD

**Issue by dipakbhimani** [angular-ui/ui-grid#4992]
Hi, 

ui-grid - v3.0.7 - header menu is not working with Firebox 43.0.4 build. 

When I close the header menu, part of it hidden behinds the grid. It seems there was similar issue fixed specifically for IE9. Looks like some css issue. However this working fine in IE and Chrome.

**Comment by Prakash2024** [comment]
I have the same issue. When I click on the 'Sort Asecnding' for example on the header menu, the popup menu goes behind the grid, in Firefox.
Version: 3.0.7
