### ISSUE TITLE
impossible to increase header height and a sole line in the grid has no bottom border

### ISSUE THREAD

**Issue by flamant** [angular-ui/ui-grid#4997]
Hello,

I use ui-grid for angularjs. I display a unique row in my grid and I have the two following problems : 

1) I cannot increase the height of the header of my grid so when I have a header text that is long, i cannot see it completely. I cannot modify the css because I have other grids with standard height. 

2) My unique row of data doesn't display the bottom border (border of cell I suppose). I specified a paginationSize of 10. 

I tried to reproduce my two problems on plunker but without sucess(I can't even see the grid). I give you the link :  http://plnkr.co/edit/ETQz1j46KVdapwiTIDNy?p=preview

Thank you in advance for your answers

**Comment by murarivarma** [comment]
# Use this in your CSS to increase header height.

    .ui-grid-header-cell-primary-focus {
      line-height: 2.428571;
    }
