### ISSUE TITLE
Hide pinning/static row header when adding ui-grid-grouping

### ISSUE THREAD

**Issue by bitflower** [angular-ui/ui-grid#4999]
When adding the ui-grid-grouping directive the "row header area" left to the grid is added. It has the class "ui-grid-pinned-container":
![unbenannt](https://cloud.githubusercontent.com/assets/6666636/12454493/0682cb6c-bf98-11e5-91c6-f13220c9644b.PNG)

I want to add the grouping directive for aggregation effects on columns but without any visual effects like this added row header bar.

I didn't find an options value for this. How can I achieve this?

**Comment by yccteam** [comment]
Have you tried: `showTreeRowHeader`?
In: http://ui-grid.info/docs/#/api/ui.grid.treeBase.api:GridOptions

**Comment by bitflower** [comment]
@yccteam Worked, thanks. Wasn't looking for the context of "tree".

**Comment by bitflower** [comment]
Still, in my opinion simply adding the directive should not change to look of that grid that much in the way that it adds the fixed column.

**Comment by gethinoakes** [comment]
`showTreeRowHeader: false` only seems to work when there is data loaded in the grid, if there is no data the column still takes up space. Is there anyway to prevent this? 

Thanks.

**Comment by gethinoakes** [comment]
Sorry, I found out that `treeRowHeaderAlwaysVisible: false` what I needed. Thanks!
