### ISSUE TITLE
Grid does not render properly when it is hidden (such as in a tab)

### ISSUE THREAD

**Issue by c0bra** [angular-ui/ui-grid#50]
I'm trying to use ng-grid in a tab pane that's hidden on initial load.

I've found that the rows do not draw at all and the header/footer draw improperly on data instantiation. The header shows the right number of records and the columns are there in the column menu, but they're off to the left of the grid div.

If I activate the pane and resize the viewable area (either by opening firebug or resizing the browser window), the rows and other content will draw.

I'm not sure if I can demonstrate this in jsFiddle/plunkr, but I could try.

**Comment by muldon** [comment]
@karlr42 thanks for the solution, it solved for me. It is complicated for us to just replace the ui version after the system is already working and starts to bug in this things. The replacement could issues another bugs. This solution came in handy !

**Comment by ali-khan-confiz** [comment]
@karlr42  thanks for the solution came in handy my problem happens when i revisit the page and it only shows grid of already selected tab because i have applied $(window).resize(); without timeout and returning of service call not it is working perfectly

**Comment by sukhoi1** [comment]
On modal display UI Grid v3.1.0 wrong auto-width.

**Comment by sukhoi1** [comment]
I have found two auto-size bugs in the v0.3.1 plugin.

**Comment by sukhoi1** [comment]
http://stackoverflow.com/questions/35246402/ui-grid-v0-3-1-column-auto-width-issue-detected/35246460#35246460

**Comment by rover10** [comment]
Finally calling the below code when clicking on tab to resize the window worked for me.

$interval(function() {
					var fireRefreshEventOnWindow = function () {
					 var evt = document.createEvent("HTMLEvents");
					 evt.initEvent('resize', true, false);
					 window.dispatchEvent(evt);
					};
					fireRefreshEventOnWindow();
				}, 100, 1);
