### ISSUE TITLE
double vertical scrollbar

### ISSUE THREAD

**Issue by irshadmalek11** [angular-ui/ui-grid#5003]
I am getting two vertical scrollbar in IE 11. It's working fine in chrome.

![capture](https://cloud.githubusercontent.com/assets/16242862/12466149/0341ef1e-bf98-11e5-91ed-8b7f5cc46b7e.PNG)

any idea ?

**Comment by swalters** [comment]
Do you get the same on http://ui-grid.info/docs/#/tutorial/401_AllFeatures?

**Comment by irshadmalek11** [comment]
no, this one looks good on my IE

**Comment by mportuga** [comment]
Cannot reproduce
