### ISSUE TITLE
Increasing digests with grid toggling

### ISSUE THREAD

**Issue by yccteam** [angular-ui/ui-grid#5006]
I'm moving the grids around quite a lot in my app.   While creating a plnkr, I've noticed that each time I re-show my grid (either by using ng-if or by doing it manually with `$compile` and `scope.destroy/element.remove`), I get roughly double the amount of $rootScope digests.
Here's the plnkr:
http://plnkr.co/edit/uOYKeJvANJu1b9zk8Ac1?p=catalogue
Take a look at the console log when clicking the toggle button.  See that each time the grid appears, you get more digest cycles. This might hint on a memory leak. Then again, it might be plnkr (since I could not see this effect in my app).

**Comment by AgDude** [comment]
@yccteam I think this was a problem in your logging. Here is an updated plunker where I reset the counter after console.log: http://plnkr.co/edit/sxcDVQyIGCURyWutrZrY?p=preview

If I am incorrect, feel free to re-open.

**Comment by yccteam** [comment]
@AgDude thanks. That must have been the reason why this effect didn't show up in my app as well :)
