### ISSUE TITLE
Clear all filter menu item configuration option

### ISSUE THREAD

**Issue by Mr-SubhadipGhosh** [angular-ui/ui-grid#5012]
Hi , Is there any option to hide "clear all filter" grid menu item by option configuration in grid options just like export pdf and xls? If not what is the best way to do it(but filter need to be there)? Is there any plan to add this option in ui-grid param?

**Comment by yccteam** [comment]
Clear the `filter.term` of every column to make sure no filter is active.
You could use this in an ng-click or something:
```
angular.forEach($scope.gridApi.grid.columns, function(col){
col.filter.term = '';
});
```
