### ISSUE TITLE
UI-Grid with Just Images

### ISSUE THREAD

**Issue by myGitHubForum** [angular-ui/ui-grid#5026]
I want to create a grid with images of 5 per row and it should be lazy loading. Is it possible? Any example would be appreciated.

IMG1	IMG2	IMG3	IMG4	IMG5
IMG6	IMG7	IMG8	IMG9	IMG10
..	..	..	..	..

**Comment by swalters** [comment]
https://github.com/angular-ui/ui-grid/blob/master/CONTRIBUTING.md

**Comment by swalters** [comment]
sorry to be so blunt, but no one is reading that link which is clearly visible in the new issue.
