### ISSUE TITLE
Grid does not draw properly when initially hidden

### ISSUE THREAD

**Issue by evilandroid** [angular-ui/ui-grid#5032]
This is one of those issues that keeps coming back.  it was fixed in a previous version (I'm not sure which), but now it's back.

I'm currently using 3.1.0 (https://github.com/angular-ui/ui-grid.info/tree/gh-pages/release/3.1.0).  I'm going to try and step it back until it works again.

**Comment by yccteam** [comment]
Could you please share a plnkr of this bug?

**Comment by ericlabra** [comment]
I have the same issue. I made a single page application, and the ui-grid is initially hidden. when I load the module of the grid , this load exactly like the photo on top... in the 3.0.0 versions and in the 3.1.0 I have the same issue.

**Comment by ericlabra** [comment]
evilandroid.. which version has fixed the issue?

**Comment by evilandroid** [comment]
I was mistaken, it was never fixed.  If you view the grid once in a situation where it works before you view it from a hidden div, it works fine in the hidden div for the duration of the session.  I thought this was fixed in a previous version, but I used to display a grid on the home page so I didn't catch it until recently when I removed the grid from my home page.

**Comment by evilandroid** [comment]
FYI - you can temporarily fix it by creating a ridiculous number of CSS media width adjustments (to the grid) based on the width of the browser.  That has issues too, but it mostly works.

**Comment by swalters** [comment]
this is an edge case that we can't seem to recreate.  Any plunkr you could give us to demonstrate it would be great

**Comment by mportuga** [comment]
Mark help wanted

**Comment by mportuga** [comment]
Mark as needs help
