### ISSUE TITLE
Rendered rows out of sync with current scroll position after resize

### ISSUE THREAD

**Issue by MarkKerby** [angular-ui/ui-grid#5037]
We see an issue where the grid appears empty when refreshed after resizing vertically.

After a resize prevScrolltopPercentage is no longer valid because the scroll height has now changed. It does not get recalculated. It is passed to adjustRows from redrawInPlace causing the render row range to be calculated incorrectly.

We have the following workaround:

After vertically resizing the element containing our grid we call:
grid.api.core.handleWindowResize();

The next call to uiGridCtrl.grid.refresh() can cause the grid to calculate the wrong scroll range and display empty cells. To resolve this we:

1] In handleWindowResize() reset all render containers prevScrolltopPercentage to undefined

```
for (var i in self.renderContainers) {
  self.renderContainers[i].prevScrolltopPercentage = undefined;
}
```

2] In redrawInPlace when rowsAdded is not true, pass prevScrollTop to adjustRows

```
container.adjustRows(container.prevScrollTop, container.prevScrolltopPercentage);
```

I think this is because after resizing the prevScrolltopPercentage is no longer valid, clearing it causes a new scrollPercentage to be recalculated based on the pixel based scroll top within adjust rows.

**Comment by swalters** [comment]
Do you have a plunkr to demonstrate?  I tried to recreate using http://ui-grid.info/docs/#/tutorial/213_auto_resizing.
