### ISSUE TITLE
Sorting doesn't work

### ISSUE THREAD

**Issue by shash8787** [angular-ui/ui-grid#5042]
![sort_prob](https://cloud.githubusercontent.com/assets/1330967/12656734/b87b36f2-c5cd-11e5-9922-fddfce367183.PNG)

If you check image file attached, after sorting in ascending order, somehow those rule names starting with 'I' shows up before rule names with 'A'. My columnDef for that is as follows. I've tried type: 'string', and 'numberStr' but obviously it doesn't work. Please help.

{ field: 'RuleName', displayName: 'Rule Name', enableHiding: false, groupingShowAggregationMenu: false}

**Comment by JLLeitschuh** [comment]
Are you loading old data?
Are you manually setting the sort order?
We recently changed how sorting works. What version of UI Grid are you using?

**Comment by shash8787** [comment]
What do you mean by this?
yeah, I'm manually setting the sort order by clicking the column order. 
v3.0.7
