### ISSUE TITLE
grid body overflows on column resizing

### ISSUE THREAD

**Issue by arvindsemwal716** [angular-ui/ui-grid#5048]
Hi, I am using ui-grid in my application. Currently, I am having a strange issue. Whenever I resize the column too much the grid data body overflows. As you can see in the attached image. Is there any solution for this issue? Thanks in advance.
![Uploading uigridissue.jpg…]()

**Comment by yccteam** [comment]
The image was not uploaded. What should I do in order to see this error? I tried to play with the columns width, but could not see the issue.
