### ISSUE TITLE
Filters Text-box ( ui-grid-filter-input ) Overlaps "X" Button ( ui-grid-icon-cancel )

### ISSUE THREAD

**Issue by Yashkochar20** [angular-ui/ui-grid#5051]
Actual: Attached is a screenshot of the issue. When input text length is longer than the size of the search box, the text and the "X" button overlap.

I would expect 'X' to stay locked and when user enters a long name bigger than length of search field, the field scrolls to the right and the text at the beginning of the input text box starts to get hidden as it moves to the left (which is actual now just that the 'X' button is not locked and overlaps the characters)

<img width="161" alt="screen shot 2016-02-01 at 1 51 19 pm" src="https://cloud.githubusercontent.com/assets/7841033/12727399/e6ee6764-c8ea-11e5-87ac-47b80a1e89c8.png">

**Comment by islamgamal** [comment]
+1 
![image](https://cloud.githubusercontent.com/assets/14905288/14282596/694887b8-fb3f-11e5-84ea-93d1e3668515.png)

**Comment by tentuxAtWork** [comment]
Issue still present in v4.0.4. @Yashkochar20 has suggested the text within the input field should simply stop short of the cancel button (small X) to prevent the text from overlapping. This can be achieved by adding some padding-right to the input field within Chrome. 

However, I feel the cancel button / small cross should be next to the input field (on the right) and not within the bounds of the input field / textbox - this would be consistent with how dropdown lists (select) appear within the filter, as here the cancel button is next to the select element on the right hand side.
