### ISSUE TITLE
Disable Multi Column Sort

### ISSUE THREAD

**Issue by dollynishit** [angular-ui/ui-grid#5062]
Hi,

I want to know is there a way I can disable multiple column sort by shift and click? I need this for my project urgently.

Thanks in advance!!!

**Comment by yccteam** [comment]
That is a nice feature. What you could do in the meantime is listen to a
click event over the `headerRow` and check if the `shift` key was held and
do your logic then (remove all sorting from your grid...).

**Comment by dollynishit** [comment]
Why do i need to remove sorting from all columns. I can listen to shift and
clicj event on header row and then disable sort property true for that
specific column.

**Comment by yccteam** [comment]
@dollynishit you might not need it, but some of us do :)
It is quite easy to implement both solutions.
