### ISSUE TITLE
Grid does not work well with Bootstrap Nav Tabs

### ISSUE THREAD

**Issue by jakednoh** [angular-ui/ui-grid#5066]
Hi guys,
I tried to use multiple grids in Bootstrap nav tabs and found a little weird issue.
When the page initially loaded  and wait(NOT CHANGE TABS) for like 3 to 5 seconds, the grids in other tabs are not showing up, just empty.
But when right after the page is loaded and click the other tabs, the grids does show up.
I really like both Bootstrap and ui-grid.
So is there any suggestion?
Thanks

Here is Plunker
http://plnkr.co/edit/2dVDfSnqfFxvyg2KFuVw?p=info

**Comment by sercangurbuz** [comment]
i think autoresize option will be the fix
[check out this ](http://ui-grid.info/docs/#/tutorial/108_hidden_grids)
[working plunkr ](http://plnkr.co/edit/fwdXMamTBrR1yKVwcohZ?p=preview)

**Comment by jakednoh** [comment]
Oh, I should have checked the tutorial first.
It no longer bothers me.
Thanks for the help!
