### ISSUE TITLE
Grouping panel

### ISSUE THREAD

**Issue by ColcerP** [angular-ui/ui-grid#5077]
Hello guys. I'm having a hard time to accomplish a grouping functionality which consists in a panel above the grid and the user could drag and drop the columns in that panel. It is that possible with the v3.0.7 of the ui grid?
![grid](https://cloud.githubusercontent.com/assets/6659895/12894845/f978c6ec-cea1-11e5-8e39-e6424baa90de.PNG)

**Comment by shadkhan** [comment]
This feature has been removed from ui-grid v-3 . I don't know why it has been removed 
One of my project required drag n drop for groupable column so I ended up using ng-grid old version.

**Comment by mportuga** [comment]
This functionality has been removed
