### ISSUE TITLE
Wierd Issue: $scope.gridApi Undefined

### ISSUE THREAD

**Issue by sbassgm** [angular-ui/ui-grid#5079]
in  `$scope.gridOptions.onRegisterApi = function (gridApi)` I set `$scope.gridApi = gridApi` however when I try to use `$scope.gridApi` out side `$scope.gridOptions.onRegisterApi` it says its undefined. I tried to follow some of this tutoria logic: http://ui-grid.info/docs/#/tutorial/210_selection
However no success. I have tried many things but still don't work. Ultimatly I want my "Select All"  and "ClearAll" to work but dont work because I can't access  `$scope.gridApi` 

**_in my JS file:_**

```
angular.module('sccApp.workqueue', ['ngRoute', 'ngResource', 'angularBootstrapNavTree', 'ui.grid', 'ui.grid.selection', 'ui.grid.pinning', 'ui.grid.resizeColumns', 'ui.grid.autoResize', 'ui.bootstrap', 'ui.grid.saveState'])


.controller('WorkqueueCtrl', ['$scope', '$location', 'FetchService', 'PostService', 'Preferences', 'UserInfo', 'DisplayDate', 'Root', '$http', 'uiGridConstants', '$window', '$log', '$modal', '$timeout', function ($scope, $location, fetchService, PostService, Preferences, UserInfo, DisplayDate, Root, $http, uiGridConstants, $window, $log, $modal, $timeout) {


    $scope.gridOptions = {
        minRowsToShow: 8,
        rowHeight: 35,
        enableHorizontalScrollbar: 1,
        enableVerticalScrollbar: 1,
        multiSelect: true,
        enableRowSelection: true, 
        enableSelectAll: true,
        enableFiltering: true,
        enableRowHeaderSelection: false
    };

    $scope.gridOptions.columnDefs =  [
            {
                displayName: "WORKQUEUE_GRID_1_COLUMN_1",
                field: 'type',
                headerCellFilter:'translate',
                headerTooltip: true,
                width: '11%',
                enableFiltering: true,
                filter: {
                    condition: uiGridConstants.filter.EXACT,
                    type: uiGridConstants.filter.SELECT,
                    selectOptions: []
                },
                pinnedLeft:true
            }, {
                displayName: 'WORKQUEUE_GRID_1_COLUMN_2',
                field: 'partNumber',
                headerTooltip: true,
                headerCellFilter:'translate',
                rowTemplate: 'workqueue/table-click-row.html',
                filter: {
                    condition: uiGridConstants.filter.CONTAINS
                },
                pinnedLeft:true
            }
        ];

    $scope.gridOptions.onRegisterApi = function (gridApi) {
        $scope.gridApi= gridApi
            gridApi.selection.on.rowSelectionChanged($scope,function(row){
                var msg = 'row selected ' + row.isSelected;
                console.log(msg);
              });

            gridApi.selection.on.rowSelectionChangedBatch($scope,function(rows){
                var msg = 'rows changed ' + rows.length;
                console.log(msg);
              });
    };

    $scope.selectAll = function() {
        $scope.gridApi.selection.selectAllRows();
        console.log($scope.gridApi + "<<<grid Api Select All")
    }


    $scope.clearAll = function() {
       $scope.gridApi.selection.clearSelectedRows();
       console.log("CLEARED DATA")
    };

```

_**in my html file:**_

```
<div class="row space" ng-controller="WorkqueueCtrl">
    <div class="col-sm-12">                            
        <div class="btn-toolbar pull-left" >
            <button ng-disabled="loading" ng-click="selectAll()"
                class="btn btn-default">SELECT ALL</button>
            <button ng-disabled="loading" ng-click="clearAll()"
                class="btn btn-default">Clear All</button>
        </div>
    </div>
</div>


<div class="row space">
    <div class="col-sm-12" ng-controller="WorkqueueCtrl">
        <div ui-grid-selection  class="grid" ui-grid="gridOptions" ui-grid-resize-columns></div>
    </div>
</div> 
```

**Comment by KevinTCoughlin** [comment]
@sbassgm are you trying to access `gridApi` before the register callback has been called and the object is assigned?

**Comment by YamilBracho** [comment]
Hi
I have the same issue.
I created my grid.options as 
`        $scope.gridOptions = {
            enableFiltering: true,
            enableRowSelection: false,
            enableCellSelection: true,
            enableSelectAll: false,
            showGridFooter: true,
            enableRowHashing: true,
            paginationPageSizes: [9, 18, 27],
            paginationPageSize: 9,
            columnDefs: [
                {name: 'fe_registro',
                    enableFiltering: false,
                    enableColumnMenu: false,
                    displayName: 'Edit',
                    cellTemplate: './registro_viaje/CellEditRegistroViajeTemplate.html',
                    width: '5%'
                },
                {name: 'tx_tipo_documento', displayName: 'T', width: '5%', enableFiltering: false},
                {name: 'tx_documento_id', displayName: 'Numero', width: '10%', enableFiltering: false},
                {name: 'tx_nombre', displayName: 'Nombre', width: '25%', enableFiltering: false},
                {name: 'tx_apellido', displayName: 'Apellido', width: '25%', enableFiltering: false},
                {name: 'edad', displayName: 'Edad', width: '8%', enableFiltering: false},
                {name: 'mt_total', displayName: 'Total', cellClass: 'text-right', enableFiltering: false}
            ],
            onRegisterApi: function(gridApi) {
                $scope.gridApi = gridApi;
            }
        };
`

I show a modal when I got the data that I will put in the grid, this way:
` $scope.gridOptions.data.push(oPasajero);`

And then refresh the grid:
`$scope.gridApi.core.refresh();`

But i got Error: $scope.gridApi is undefined

Also I noted that this problem happened, the column header does not be shown...

Any hint, please

TIA,
Yamil

**Comment by liFeixiang** [comment]
different scopes.

**Comment by cookatrice** [comment]
in my case, 
after added onRegisterApi() to gridOption, cleared this issue.
<img width="385" alt="2017-06-19 5 09 27" src="https://user-images.githubusercontent.com/3710604/27275386-22c20cfa-5512-11e7-9b15-65d694ea4194.png">

**Comment by SkylarLK9998** [comment]
I have the same issue. I tried the fix @cookatrice recommended but it still didn't work.

**Comment by SkylarLK9998** [comment]
Update: I found a Fix. in $scope.gridOptions{...} put
onRegisterApi: function(gridApi){
                    $scope.gridApi = gridApi;
                }
first before you put/declare/assign anything else in $scope.gridOptions{...}

**Comment by gustavomassa** [comment]
@SkylarLK9998 

Declaring the onRegisterApi as the first parameter of the griOptions did not resolve the issue.
```
      $scope.gridOptions = {
        onRegisterApi: function (gridApi) {
          $scope.gridApi = gridApi;
          console.log('gridApi: ', gridApi);
          console.log('type: ', typeof (gridApi));
        },
        showGridFooter: true,
        showColumnFooter: true,
        enableFiltering: true,
        columnDefs: columnDefs,
        data: options.data,
      };
```

**Comment by SkylarLK9998** [comment]
Yeah, after I posted that "fix" I learned that gridApi needs to be set up before you can use it. If you need to use it immediately after the grid is created, try adding a $timeout with a delay of 0.
Your code should look something like this:
$scope.girdOptions = {
onRegisterApi: function(gridApi){
    $scope.gridApi = gridAPi;
        $timeout(
            /*your code here*/
        )
    },
    /* other stuff */
}

**Comment by codemonkeyneo** [comment]
I know this issue is closed but I was battling with this problem also and found that if I set the column definition after the data had been received everything works as expected. I was bascailly wanted to change the data from calling different API services.

    yoursever.CallSomething(optional params).then ( function ( data ) {
       $scope.gridOptions.data = data;
        $scope.gridOptions.columnDefs = [ YOUR DEF HERE ] ; // calling this after resolved my issues
    });

Maybe that will help someone else facing same issue, if not nothing lost :) Thanks all.
