### ISSUE TITLE
No compatible version found: ui-grid@3.1.0

### ISSUE THREAD

**Issue by chinachuner** [angular-ui/ui-grid#5081]
package.json:  dependencies "ui-grid": "3.1.0"
npm install

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12

npm ERR! No compatible version found: ui-grid@3.1.0
npm ERR! Valid install targets:
npm ERR! 0.0.0

**Comment by lpand** [comment]
`npm install angular-ui-grid`
