### ISSUE TITLE
Not fire 'rowSelectionChanged' or 'rowSelectionChangedBatch' event on unselect row

### ISSUE THREAD

**Issue by norf33rus** [angular-ui/ui-grid#5088]
Hi, im confront a question about multiselect rows. I'm use ui-grid-rownav and multiSelect: true. When im chose a row and select next row with a (Shift key and arrow), event 'rowSelectionChangedBatch' was fired, but if im unselect this rows back, nothing happend. And i'm not sure how many row's user selected.

**Comment by jmalkan** [comment]
I don't see ui-grid-rownav. Did you mean ui-grid-cellNav?

Please provide plunkr
