### ISSUE TITLE
When using ng-show, grid will not load data until window is resized

### ISSUE THREAD

**Issue by codyhazelwood** [angular-ui/ui-grid#5096]
I build a custom tab directive, and I have a UI-Grid instance inside one of those tabs.  If the tab is not visible, then `ng-show` will hide the tab.  Once the tab becomes visible, no data is shown until the window is resized.  Once resizing the window, everything works as expected (including reloading data).

If I switch to `ng-if`, there are no issues.

Using angular 1.4.8 and UI-Grid 3.1.0.

Similar to:
#855 #4352

**Comment by swalters** [comment]
known issue.  ng-show leaves the grid with now width and height so it can't properly size.  ng-if is the proper workaround

**Comment by ddehghan** [comment]
Hi - I am sorry but how does closing this bug as a known issue helps.  Showing and hiding is pretty basic requirements of any components. The other bugs where old and maybe could be justified as closed. One of the bugs has been idle for 6 months with waiting flag for an answer that is clearly provided. 

How many more people have to waist their time discovering the wheel on their own and get to this point. 

We should reopen this. It as clear statement of the bug and shows that is happens on the most recent code.

**Comment by gsalisbury-advera** [comment]
For anyone still having this issue, adding a width to the div solved the problem for me. https://github.com/angular-ui/ui-grid/issues/4352

**Comment by Alagappapandian** [comment]
Add `ui-grid-auto-resize` directive also solve this problem.
