### ISSUE TITLE
Column Re-Sizing not Firing Unitl Column is Moved

### ISSUE THREAD

**Issue by tuckerjt07** [angular-ui/ui-grid#5105]
On the example page for enableColumnResizing, and in my application, re-sizing and reordering are both enabled. However, the column remains locked to its initialized width until it has been moved, ie reordered.

**Comment by mportuga** [comment]
Check in version 4.0.3 and see if the issue is still there. If it is, please provide a plunker and mention your browser and OS so that I can best look into this issue.
