### ISSUE TITLE
Best way to add an input element to a column menu?

### ISSUE THREAD

**Issue by achowdhury91** [angular-ui/ui-grid#5108]
Hi everyone,

I'm wondering if there is a way to get an input element in the column menu, like in the following design:

I would like to add an input text box as well as checkboxes. I looked through the documentation and API and I found the property "menuItems" but it doesn't seem to allow for much customizability outside of an icon and a click-action.

Any help would be really appreciated.

Thanks. 

<img width="1147" alt="screen shot 2016-02-11 at 3 04 53 pm" src="https://cloud.githubusercontent.com/assets/4889882/12995485/a2d7819c-d0dc-11e5-96c1-802266c69f91.png">

**Comment by georgiabarnes** [comment]
I have the same issue, were you able to figure this out?
