### ISSUE TITLE
Bug: Scrolling Regression in v3.1.0+

### ISSUE THREAD

**Issue by KegDemon** [angular-ui/ui-grid#5118]
Hi All,

I've noticed that there appears to be a scrolling regression that occurred after upgrading from version 3.0.7 which causes large grids that are set to full height (upped virtualizationThreshold to permit the rendering of this) to not allow scrolling down the page, only up.

This can be seen here: http://plnkr.co/edit/i2horUuRWwEpf37tTc2j?p=preview

Note that this has been tried in all browsers on OS X and Windows (Chrome, Safari, FireFox, IE).

Thanks for taking a look.

**Comment by zhenyi2697** [comment]
+1
This is an annoying bug for me too.
Hope that it get fixed in next version.
