### ISSUE TITLE
Feature request: defaults for column min-width and max-width

### ISSUE THREAD

**Issue by betsydupuis** [angular-ui/ui-grid#5119]
It looks like this feature once existed, but has been deprecated.
https://github.com/angular-ui/ui-grid/issues/3941

I would like to be able to define a default min-width and max-width. I'm working with a very large data set and this would be useful rather than looping through each columnDef and setting the width settings.

Here is the suggested solution from  [horizontal scrolling](http://ui-grid.info/docs/#/tutorial/191_horizontal_scrolling):

```
  $scope.gridOptions.columnDefs = [];
  $timeout( function() {
    for (var colIndex = 0; colIndex < colCount; colIndex++) {
      $scope.gridOptions.columnDefs.push({
        name: 'col' + colIndex,
        width: Math.floor(Math.random() * (120 - 50 + 1)) + 50
      });
    }
  });
```

**Comment by mportuga** [comment]
This feature already exists:
http://ui-grid.info/docs/#!/tutorial/204_column_resizing
