### ISSUE TITLE
Feature Request: Infinite Scrolling for columns.

### ISSUE THREAD

**Issue by betsydupuis** [angular-ui/ui-grid#5124]
I'm creating a grid with a large number of columns. I would like to be able to use infinite scrolling for columns.

**Comment by blowsie** [comment]
Just out of curiosity, do you have an API to handle this? If so how was it approached.

**Comment by betsydupuis** [comment]
Right now we're able to request a data set based on an array of columns, but we're considering adding true column 'pages'  with possibly giving them subsection names.

**Comment by faris-git** [comment]
I'm new to angularjs and ui-grid.
Is there any properties or function that I can control the horizontal scroll for concating columns. I've data set of 100K rows and 2K columns which is worst for rendering. I'm using infinite scroll features from ui-grid.
It'll be great if there is any code that I can extend or use.
