### ISSUE TITLE
Unable to Bind array object to the UI-Grid 

### ISSUE THREAD

**Issue by Shreeshag** [angular-ui/ui-grid#5128]
I have data as bellow :
```
$scope.gridOptions = {
columnDefs: [
                         { name: 'users', displayName:'Users'}
                     ]
};

$scope.gridOptions.data = ["users": [{"ABC","ADF","PQR"}]];

```
I am unable to display "users" data in single cell. 

Any ides, how to solve this?

**Comment by Vinodang** [comment]
your code has some error, change the name to field like this:
$scope.gridOptions = {
columnDefs: [
                         { filed: 'users', displayName:'Users'}
                     ]
};

**Comment by shadkhan** [comment]
Hi please try this code I just checked it in grid it will work fine

```
$scope.gridOptions = {
columnDefs: [
                         { field: 'Name', displayName:'Users'}
                     ],
					 
					 onRegisterApi: function(gridApi){
                                        $scope.gridApi = gridApi;
    }
  
};

$scope.gridOptions.data = [{"Name": "ABC"}, {"Name": "ADF"}, {"Name": "PQR"}];
```

**Comment by Shreeshag** [comment]
@Vinodang 

I think there is no error in my code, its work me for other data, but i am unable to bind Array in single cell.

**Comment by Shreeshag** [comment]
@shadkhan 

yup, let me try :-)

**Comment by Shreeshag** [comment]
@shadkhan 

If i use $scope.gridOptions.data = [{"Name": "ABC"}, {"Name": "ADF"}, {"Name": "PQR"}];

It will create new row for each name, but i am looking all 3 values in single cell like: 'ABC,ADF,PQR'

**Comment by Shreeshag** [comment]
Some how i done with "cellFilter: "
Thank you

**Comment by Vinodang** [comment]
@Shreeshag  could you please show your fixed code?

**Comment by Shreeshag** [comment]
I have done with 
```
.filter('users', function() { 
                     ....
                     ....
                     ....
                     ....
})
```
