### ISSUE TITLE
I am using ui-grid in my app, how can I select a row in the grid?

### ISSUE THREAD

**Issue by firecentaur** [angular-ui/ui-grid#5133]
Hi there,

I am using ui-grid in my app, and I would like to select row in the grid - ie: programmaticly  checkbox a row.

I saw that there are is the file gridTestUtils.spec.js in github,

I have copied it into my tests/lib folder.

Now how can I use it to select a row in my grid?

I hope you can help

**Comment by PaulL1** [comment]
Check the tutorials.  Many of the 100 and 200 series have test cases inside the tutorial, I think I recall writing one for selection.
