### ISSUE TITLE
ReOpen issue #2254

### ISSUE THREAD

**Issue by vknvnn** [angular-ui/ui-grid#5134]
[#2254](https://github.com/angular-ui/ui-grid/issues/2254)
current version, I see it not work? 

http://plnkr.co/edit/7BRy6F?p=preview

and it work when i implement same example below:

http://plnkr.co/edit/44SYdj19pDDaJWiSaPBt?p=preview

**Comment by Atmos206** [comment]
There is a simple css workaround I have noted in Issue #5474 
No need to implement a custom selection directive for uiGridCell
