### ISSUE TITLE
cellFilter is used on function and string cellTooltip

### ISSUE THREAD

**Issue by MattiJarvinen** [angular-ui/ui-grid#5152]
On column with cellFilter and cellTooltip defined as string or a function tooltip value is passed to cellFilter.

Tutorial states: Tooltips respect the cellFilter, so if you define a cellFilter it will also be used in the tooltip.
API states: cellFilter is a filter to apply to the content of each cell

Maybe the tutorial's description should be extended to cellFilter documentation or cellFilter should be used only if cellTooltip value from a function is true or the cellTooltip property is true.
http://plnkr.co/edit/ViUVjaY4qTVK4oPp0aRo

**Comment by zuzusik** [comment]
I don't think this one should be closed. As for me it is valid.

**Comment by zuzusik** [comment]
Still a valid issue

**Comment by zuzusik** [comment]
Still a valid issue

**Comment by zuzusik** [comment]
Still the issue

**Comment by zuzusik** [comment]
Still an issue

**Comment by zuzusik** [comment]
I should probably already give up on this, but I will not :)

**Comment by zuzusik** [comment]
Ping-pong with stale bot! Your turn! Boom!

**Comment by wesfincher** [comment]
I'll join this fight!  I'm currently showing a percentage in the cell value and formatted using a cellFilter.  I need the tooltip to be the string representation of the fraction ("6/7") to be displayed.  Using the cellFilter on what's returned from the tooltip function gives me 0%....Sure I can overload my filter, but I'm sure others have run upon this same problem

**Comment by zuzusik** [comment]
Looks like stale bot won 😃

**Comment by wesfincher** [comment]
Boo stalebot!
