### ISSUE TITLE
Exporting CSV with cell display value rather than the source value (with cellFilter from custom factory)

### ISSUE THREAD

**Issue by ComeOutToPlay** [angular-ui/ui-grid#5159]
I tried to use the solution from 

https://github.com/angular-ui/ui-grid/pull/4948

and I built this Plnkr, where the table display and export work really good!

http://plnkr.co/edit/iunzUmHe0DYFH7EFSTGQ?p=preview

But, I have a custom factory (uiGridFactory) that provides me the cellFilter that I built to reuse it. The table is rendered really good, but I cannot export the CSV values for the Company column. 

```
  { field: 'name' },
  { field: 'gender', visible: false},
  { field: 'company', cellFilter: 'mapCompany:row.grid.appScope.companyCatalog' }
```

(*) I load companyCatalog from a REST service. 

Here is my Plnkr.

http://plnkr.co/edit/LNj7TImWQg8G7mmXIyAz?p=preview

Any suggestion will be really appretiated

Thanks!

**Comment by dereklin** [comment]
Facing the same issue.  Is there a way to specify if the raw data or formatted data will be exported by column?

**Comment by rloisel-forcity** [comment]
Same issue
