### ISSUE TITLE
Error while building columns

### ISSUE THREAD

**Issue by angular-git-user** [angular-ui/ui-grid#5162]
Hello!!! I don't know exactly why I'm getting this error and on what line of my code...
I'm just adding columns dynamically even before the data is populated..
I'm using,  "version": "3.0.7"
It says,
`TypeError: Cannot read property 'name' of undefined`
`    at p.buildColumns (ui-grid.min.js:7)`
 `   at l (ui-grid.min.js:7)`
`    at Object.fn (angular.js:15763)`
`    at r.$digest (angular.js:15896)`
 `   at r.$apply (angular.js:16160)`
`    at g (angular.js:10589)`
 `   at T (angular.js:10787)`
`    at XMLHttpRequest.w.onload (angular.js:10728)`

**Comment by umdstu** [comment]
I am getting this same error. Did you resolve it or give up?
