### ISSUE TITLE
Console error from WheelEvent trying to set readonly property

### ISSUE THREAD

**Issue by IvanJoukov** [angular-ui/ui-grid#5164]
WheelEvent.deltaMode is a READONLY property, as explained https://developer.mozilla.org/en-US/docs/Web/API/WheelEvent/deltaMode.

The code currently tries to set it to 0 at the bottom of a method, causing harmless but annoying JS errors in the console.  

I've submitted a pull request to fix it here https://github.com/angular-ui/ui-grid/pull/5155

**Comment by swalters** [comment]
I can not recreate with Firefox 44.0.2 on Windows 10.

**Comment by IvanJoukov** [comment]
@swalters I set about to create a plunkr to reproduce the issue, and discovered that it only happens in a global strict mode on the ui-grid.js file, which is a bit hard to reproduce in a plunkr.  In my case it happens because I am concatenating/minifying my scripts and some other third party script seems to have this issue.   To reproduce it, if you have a local set up, just add "use strict"; at the very top of your ui-grid.js file.  So, trying to set a property that only has a getter is only an error in strict mode, but still, given that this may occur and it serves no purpose I think my pull request is appropriate. 

Uncaught TypeError: Cannot set property deltaMode of #<WheelEvent> which has only a gettermousewheelHandler @ ui-grid.js:11690jQuery.event.dispatch @ jquery.js:4430elemData.handle @ jquery.js:4116

**Comment by caseyjhol** [comment]
Just reproduced this issue with Chrome 48 on Windows 10. This is only happening when the ui-grid JS is included in another file with "use strict." As concatenating JS files should be common practice in any production site, this seems like a good pull request to merge.

**Comment by IvanJoukov** [comment]
Hi @swalters, any particular reason you don't want to accept this?

**Comment by fyyyyy** [comment]
Same happens here, when using ES6 / babel
