### ISSUE TITLE
Dynamically unpin the columns

### ISSUE THREAD

**Issue by angular-git-user** [angular-ui/ui-grid#5166]
Hello, I've added a feature in my grid's column menu called 'Freeze Panes'.
So if i have 5 columns and the user says on the third column as freeze panes then column 1, 2, 3 would be pinned to left at once... I'm able to achieve this successfully..
But what I'm unable to do is Unfreeze them.. ie if he clicks on unfreeze then these columns should be unpinned... 
`some code....called from action..`
  `if(col_index != null){`
`_.each(colDefs, function(colDef, index){`
`if(index <= col_index){`
 `if(pinleftboolean){`
`colDefs[index].pinnedLeft = pinleftboolean;`
`}else{`
`colDefs[index].pinnedLeft = pinleftboolean;`
`}`
`}`
`});`
`grid.api.core.notifyDataChange(uiGridConstants.dataChange.COLUMN);`
`}`
This is what Im trying to do.. during FreezePanes.. `pinleftboolean = true` and for Unfreeze  `pinleftboolean = false`

Is there a method to unpin a column.. not able to locate one in UI Grid's source

**Comment by dsouza-ansel** [comment]
This is what I've tried after doing a deep search in the source code.. the default unpin column option available makes the same service call what I'm trying to do explicitly..
I do not see any errors on the console.

`if(pinleftboolean){`
`                        colDefs[index].pinnedLeft = pinleftboolean;`
       `             }else{`
           `             grid.api.pinning.pinColumn(context.col, undefined)`
   `                 }`

This makes call at line 21473
`pinColumn: function(col, container) {`
           `     service.pinColumn(grid, col, container);`
`              }`

**Comment by dsouza-ansel** [comment]
I have also tried property..
colDefs[index].unpin = true;

**Comment by amex132** [comment]
I have a similar issue, I'm unable to dynamically unpin a column. Were you able to implement a solution or workaround for this? Thanks!
