### ISSUE TITLE
Data does not display when parentheses in column name

### ISSUE THREAD

**Issue by saaqibz** [angular-ui/ui-grid#5169]
Hello, I was trying to use UI grid and stumbled into a bug.

To reproduce, Create a data object with parentheses in their name. The one I used was:

"Style Description (Long)" and "Style Description (Short)". Associate them with a string value and see if they show up in a basic grid (the header shows up but the data does not).

I believe it is the parentheses because I can fix it by replacing the parentheses with dashes:

Let me know if you have trouble reproducing it and I'll provide more details

**Comment by angular-git-user** [comment]
what you can do is use display name if you only want paranthesis for display purpose..
eg.
`{displayName:'Style Description (Long)', name:'styledesc_long'},`
`{displayName:'Style Description (Short)', name:'styledesc_short'}`

**Comment by yellowiscool** [comment]
If the columns names are dynamic, you can encode them in base64 (`window.btoa`) as a workaround.

**Comment by zheng-wang** [comment]
I encountered the same problem. I ended up using yellowiscool's solution, because the column names are retrieved dynamically from the server side.

Hope it can be fixed so that we can avoid using the trick.

**Comment by prashasti4** [comment]
Any updates on this issue?

**Comment by vishalkrv** [comment]
Any updates on this ?

**Comment by mportuga** [comment]
As @angular-git-user stated: "you can do is use display name if you only want parenthesis for display purpose"
