### ISSUE TITLE
i18nService Translate

### ISSUE THREAD

**Issue by gilsonjoanelo** [angular-ui/ui-grid#5180]
The several days, I was facing a problem regarding the translation of a column displayed in gridMenu. The grid showed only [MISSING]. I knew I was missing some item in my translation.
After several tests could identify the component that performs the translation point "ui-grid.js | line 13894" and at this point, it does not display the name of the column that does not have the translation.

The current code is as the model below

for (var i = 0; i < paths.length; ++i) {
            if (current[paths[i]] === undefined || current[paths[i]] === null) {
              return i18nConstants.MISSING;
            } else {
              current = current[paths[i]];
            }
          }

It would be interesting to add that column is the problem. I made the adjustment to the model below and could identify other points that also were with the same problem.

for (var i = 0; i < paths.length; ++i) {
            if (current[paths[i]] === undefined || current[paths[i]] === null) {
                return i18nConstants.MISSING + " " + paths[i];
            } else {
              current = current[paths[i]];
            }
          }

It would be interesting to integrate this change in the component.

**Comment by screamsyk** [comment]
It's more like that there is no configuration for the target language in ui-grid.js. For example:
（1）I set the language to Chinese:`i18nService.setCurrentLang('zh-cn');`
（2）And I want to export data as excel, so the excel export menu items will be added to the ui-grid grid menu.
（3）But the excel export menu name is [MISSING]
（4）I check the source code and I find this:
![1](https://user-images.githubusercontent.com/25660357/34980930-f0c3794e-fae0-11e7-8a50-27971cd4ed1a.png)
（5）As shown above, there is no configuration for the excel export menu, so it shows [MISSING]. Now, we can solve the problem of 'i18nService Translate' by adding our configuration to ui-grid.js. This is one way to do it.

**Comment by mportuga** [comment]
This issue was address by pull request #6762
