### ISSUE TITLE
Vertical nggrid

### ISSUE THREAD

**Issue by toonsii123** [angular-ui/ui-grid#5219]
Hi Everybody,
I am trying to set a vertical nggrid with no "ColumnsDef" but "RowsDef"  (which does not exist) and my header set in the first column. Is this possible ?
Thanks in advance

**Comment by stevenlius** [comment]
I guess you can hack it around. You could have the columnsDef to have only one property. 
columnsDef{
       RowTitlte: "" ,
       data : ""
}
By doing this, you can only create 2 column data grid.
