### ISSUE TITLE
Issue with require js

### ISSUE THREAD

**Issue by chiragwizni** [angular-ui/ui-grid#5221]
hi there

I am using ui grid with require js, it throws following error irrespective of actual path provided in require config, I am clueless about this error let me know what should I do
`GET http://localhost:3001/ui-grid/ui-grid

404 Not Found
        1ms 
angular.js?v=1.0 (line 8380)
Error: [$compile:tpload] Failed to load template: ui-grid/ui-grid
http://errors.angularjs.org/1.2.16/$compile/tpload?p0=ui-grid%2Fui-grid
minErr/<@http://localhost:3001/assets/libs/angular/angular.js?v=1.0:78:12
compileTemplateUrl/<@http://localhost:3001/assets/libs/angular/angular.js?v=1.0:6788:17
$http/promise.error/<@http://localhost:3001/assets/libs/angular/angular.js?v=1.0:7953:11
qFactory/defer/deferred.promise.then/wrappedErrback@http://localhost:3001/assets/libs/angular/angular.js?v=1.0:11328:31
qFactory/defer/deferred.promise.then/wrappedErrback@http://localhost:3001/assets/libs/angular/angular.js?v=1.0:11328:31
qFactory/createInternalRejectedPromise/<.then/<@http://localhost:3001/assets/libs/angular/angular.js?v=1.0:11461:29
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://localhost:3001/assets/libs/angular/angular.js?v=1.0:12412:16
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://localhost:3001/assets/libs/angular/angular.js?v=1.0:12224:15
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:3001/assets/libs/angular/angular.js?v=1.0:12516:13
done@http://localhost:3001/assets/libs/angular/angular.js?v=1.0:8204:34
completeRequest@http://localhost:3001/assets/libs/angular/angular.js?v=1.0:8412:7
createHttpBackend/</xhr.onreadystatechange@http://localhost:3001/assets/libs/angular/angular.js?v=1.0:8351:1
`

**Comment by ashwin-sureshkumar** [comment]
I am using ui-grid with require js as well it works well. Please provide more information, 

1. folder where your ui-grid is located, looks like you angular loads from assets/libs 
2. require js config 
3. app initialization

**Comment by chiragwizni** [comment]
Hi thanks for your prompt reply, I injected the library at a wrong place, sorry for the inconvenience caused. Though I am 3 questions for you:
1) Is this library compatible with angular 2.0
2) How to do server side grouping
3) I need to rebind the data, but the scroll retains it position hence fires data binding event retaining its page number.

**Comment by lepkifke** [comment]
Can you please tell me how did you resolve it i have the same issue?

**Comment by pforprasad** [comment]
I'm getting this issue with angular 1.5.5 and ui-grid 3.0 not able to guess what is going wrong please reply if you know the fix

**Comment by guntercn** [comment]
hi. i have the same error 
/ui-grid/ui-grid 404 (Not Found)

angular 1.5.5 ui-grid 4.0.4

**Comment by JGSolutions** [comment]
@chiragwizni 
Did anyone resolve this issue using requirejs. If yes can you post a quick example.
