### ISSUE TITLE
npm install from FIRST_TIMER.md

### ISSUE THREAD

**Issue by jesussaad** [angular-ui/ui-grid#5223]
In "Setup the toolset" chap from FIRST_TIMER.md guide says this: "Then install the npm dependencies: npm install". I run this and got any errors followed attached.
[ui-grid-FIRST_TIMER.txt](https://github.com/angular-ui/ui-grid/files/172013/ui-grid-FIRST_TIMER.txt)

Previously I follow the guide and Install Node.js v5.8.0 Stable.

In this guide says: "if you get errors then something has gone wrong. Tell us about it, and help to improve this guide by adding common errors and resolutions here", but I don't know where and how can I tell you and I want to contribute with this guide too.

Thanks for attention and if I open this issue in wrong place, I'm sorry, I'm new here and I want to know the best practices.

**Comment by arjshiv** [comment]
Looks like ```node-gyp``` is failing. There seems to be some discussion on this issue at https://github.com/nodejs/node-gyp/issues/341 . 


For now, can you try the solution suggested at http://stackoverflow.com/a/12825911/1614987 ?
