### ISSUE TITLE
ScrollEvent through wheelScrollThrottle not defined

### ISSUE THREAD

**Issue by stevenlius** [angular-ui/ui-grid#5225]
I am using ui-grid 3. 
The bug that the scrollEvent factory can not found wheelScrollThrottle, which apparently the factory works like 
`self.grid.options.wheelScrollThrottle, {trailing: true});`

I try to create the scrollEvent by passing $scope or $scope.gridOptionsView ->(a name that I create to bind to ui-grid)

```
 var scrollObj = new ScrollEvent($scope, null, null, uiGridConstants.scrollEventSources);
 var scrollObj = new ScrollEvent($scope.gridOptionsView , null, null, uiGridConstants.scrollEventSources);
```

Get rid of options in `self.grid.options.wheelScrollThrottle, {trailing: true});` make it working. I guess we should ask user to pass in the `$scope.gridOption`, and get rid of the `grid.options` in scrollEvent factory, as people might name their gridoption differently. 

Furthermore, we are lacking of documentation of how to use scrollEvent. I am still trying to figure out what is rowContainer, so I can use getNewScrollTop to get the scroll position.

**Comment by mportuga** [comment]
Note: Add help wanted label
