### ISSUE TITLE
autoAdjustHeight on windows and firefox

### ISSUE THREAD

**Issue by ivanvoznyakovsky** [angular-ui/ui-grid#5231]
after https://github.com/angular-ui/ui-grid/commit/48fd5021a19e3792dbc04de55770bfc26a95ce53 the following bug appeared in FF on windows: autoAdjustHeight is not reachable

`ui-grid-viewport`'s min-height is 20px
`overflow-y: scroll;` forces browser to render scroll bar even when there's nothin to scroll
this adds to `ui-grid-viewport` extra 14px. so now it's 34px.
default `rowHeight` is 30px.
`autoAdjustHeight` is called only when the following condition is `true`

``` js
if (grid.gridHeight <= grid.options.rowHeight && grid.options.enableMinHeightCheck) {
  autoAdjustHeight();
}
```

thus we'll never get to it.

**Comment by markwilk** [comment]
Wow, thanks for your comment @ivanvoznyakovsky !  I've been struggling with a grid all day long that exhibited this same behavior (FF/Win).  Ultimately ended up setting the row height to 34px.

**Comment by zackurben** [comment]
Great find @ivanvoznyakovsky! I think this is also the primary issue with some other tickets related to `ui-grid-auto-resize`, like https://github.com/angular-ui/ui-grid/issues/2930.

@mportuga any reason why the `autoAdjustHeight()` can't be invoked on all new grid inits? https://github.com/angular-ui/ui-grid/blob/154ced2b2717a5e5cd4899b64aab0a2b865c4e74/src/js/core/directives/ui-grid.js#L273-L289
