### ISSUE TITLE
Nuget does not contain latest version

### ISSUE THREAD

**Issue by MichalJakubeczy** [angular-ui/ui-grid#5232]
It seems that latest nuget package available still uses version 3.1.0.1 but according to your site there is 3.1.1 already.

We use your grid and also use nuget to periodically update it.

Could you please update nuget to latest version.

Thanks.

**Comment by dsaf** [comment]
Yes, please.

**Comment by MichalJakubeczy** [comment]
Newest stuff missing on nuget. Current newest is 3.2.1 but on nuget is 3.1.1.

We like your grid, but are limited to nuget to upgrade our tools. 

Could you please update nuget to latest version.

Thanks.

**Comment by MatejQ** [comment]
Currently nuget is again 2 versions behind. It contains version 4.0.2 which was released 3 months ago. Please don't neglect nuget when releasing latest version.

**Comment by mportuga** [comment]
I will say that I am not sure who is maintaining the nuget version. When I took over ui-grid there was already no task build in to release a new nuget version and I have not been doing it. In order words, we no longer officially release to it or have access to it, someone else is handling that.
