### ISSUE TITLE
Apply 'OR' option for multiple filters

### ISSUE THREAD

**Issue by sannitesh** [angular-ui/ui-grid#5234]
We are using ui-grid in one of our project and currently we can apply two filters for each column which is supported by UI-grid. We have filters arrays something like mentioned below:

```
{ field: 'age', filters: [
    {
      condition: uiGridConstants.filter.GREATER_THAN,
      placeholder: 'greater than'
    },
    {
      condition: uiGridConstants.filter.LESS_THAN,
      placeholder: 'less than'
    }
  ]
}
```

This will return rows which are matches both the criteria. This is perfect.

Now we would like to add "OR" condition in between these filters so that both filters can be applied or one of them can be applied. I don't see any support in UI-grid for this feature. Can we add this functionality in upcoming version?

**Comment by johncja** [comment]
Is that what you asking about? http://stackoverflow.com/questions/36153851/

**Comment by timc13** [comment]
+1

**Comment by mportuga** [comment]
We unfortunately won't have a chance to add this in the upcoming version, but we are accepting pull requests if you can implement it.

**Comment by georgiabarnes** [comment]
Any progress on this?

**Comment by mportuga** [comment]
Nope, this was closed due to inactivity for so long. I can reopen it and reprioritize
