### ISSUE TITLE
enableFiltering option is not working for some turkish characters ı, i, I, İ

### ISSUE THREAD

**Issue by fatihturgut** [angular-ui/ui-grid#5235]
Hi,

This repository is working great. 

But i have small problem with it. 

All turkish characters are working except two characters: ı, i ( I, İ ).
We have two different characters on our turkish keyboards like in this picture:

![img_4207](https://cloud.githubusercontent.com/assets/12934059/13881467/b3d934fe-ed29-11e5-94c2-5d78c52248fe.JPG)

However, enableFiltering option is not filtering words properly. 

*When i write "i" on filter box, it brings me all "i" and "I" letters. It should bring "i" and "İ".
*When i write "ı" on filter box, it brings me only "ı". It should bring "ı" and "I".
Picture:
![adsiz](https://cloud.githubusercontent.com/assets/12934059/13881774/fb0458ee-ed2a-11e5-9e44-239ae19d1091.png)

How can i solve this problem?

Thank you.

**Comment by kunthar** [comment]
There should be no problem at all with ui-grid. Please see [here](http://ui-grid.info/docs/#/tutorial/401_AllFeatures) . Insert Turkish chars and try to sort it. Also good [resource](https://docs.python.org/2/howto/unicode.html) to understand encodings would be useful.
