### ISSUE TITLE
Vertical scrollbar jumps back to previous row

### ISSUE THREAD

**Issue by adnirjhar** [angular-ui/ui-grid#5236]
Hello, 
I am using 3.0.7. I customized the basic css of ui-grid to give a look like the following. As you can see below, I have added some margins on top and bottom for each row, and some border stuff. When I am using the scrollTo function to get to the last row, the vertical scrollbar jumps to the end, and jumps back again to the previous row. 
- I have set the rowHeight,
- scrollTo not taking me to last row, even clicking repeatedly. 
  ![223](https://cloud.githubusercontent.com/assets/2383909/13889776/a0bd5f5a-ed72-11e5-9e9a-129326713691.png)

In the picture below, everything is the same just except there are no custom margins for each row. scrollTo is behaving perfectly here.
![gghj](https://cloud.githubusercontent.com/assets/2383909/13889800/c0013ef4-ed72-11e5-93d1-a1d5fb26c94c.png)

Help a noob. :)
Thanks in advance.

**Comment by mportuga** [comment]
Will be resolved in 4.4.5
