### ISSUE TITLE
User can't select the row by clicking the select checkbox  available in the respective row when  enableFullRowSelection : true"

### ISSUE THREAD

**Issue by yogeshsonawane** [angular-ui/ui-grid#5239]
ui-grid version : 3.1.0 and 3.1.1 

Description of the issue:  
User can't select the row by clicking the select checkbox  available in the respective row. This issue is reproduced only when the "enableFullRowSelection : true" in the grid configuration. In case of false the check-box selection works fine.

Steps
1. Create the grid having "ui-grid-selection" feature enable
2. make the enableFullRowSelection : true,
3. click on the check-box against the any row.
4. User can't select the row.

**Comment by yogeshsonawane** [comment]
http://plnkr.co/edit/xoPiwLZYt32CR8ZBTA09?p=preview

**Comment by angular-git-user** [comment]
You can do something like this..
1) Create a singleclick even on row template
`self.rowTemplate = function(){
            return '<div ng-dblclick="grid.appScope.rowDblClick(row)" ng-click="grid.appScope.rowSingleClick(row)" >' +
                '  <div ng-repeat="(colRenderIndex, col) in colContainer.renderedColumns track by col.colDef.name" class="ui-grid-cell" ng-class="{ \'ui-grid-row-header-cell\': col.isRowHeader }"  ui-grid-cell></div>' +
                '</div>'
        };`

2) write a function on its appscope
`$scope.rowSingleClick = function(row){
			if(row.isSelected != undefined) {
				if(row.isSelected === true){
					self.gridApi1.selection.unSelectRow(row.entity);
				}else{
					self.gridApi1.selection.selectRow(row.entity);
				}
			}else{
				self.gridApi1.selection.selectRow(row.entity);
			}
		};`

I'm using this for my project it should work..

**Comment by antonio91kim** [comment]
+1

**Comment by thorvx** [comment]
Try this style to enable checkbox selection:

```
.ui-grid-cell.ui-grid-disable-selection.ui-grid-row-header-cell {
    pointer-events: all;
}
```

**Comment by gBe1983** [comment]
https://stackoverflow.com/questions/29469778/angular-ui-grid-row-selection
