### ISSUE TITLE
ui-grid-api or ui.grid.core not working for $scope.gridApi.core.notifydatachange()

### ISSUE THREAD

**Issue by babukota** [angular-ui/ui-grid#5242]
property 'core' is bound to a null reference or propery can't be found. I tried all ways of getting ui-grid-core references as module, factoreiss..but no use.

Basically I am trying to update a row in a grid and want to show the updated information on the same page.
a) Inital load is done using ASP MVC data model structure
b) Date update in grid is done through ajax call using Jquery Dialog popup.
c) Grid Data reload from server using ajax call from call back of DialogClose event function.
d) I can updated information on server and in call back function using alert/console.
e) but UI-Grid is not updated..having old data. Temp fix, i had to use window.location.reload(), which I don't want because I want only UI-GRID to get updated and want to be on the same page, where updates are done.

See below code I used.

@model IList<TSMISWebApp_2016.Areas.Statements.Models.VALIDATION_JOBS_SENT_FD>

@{
    ViewBag.Title = "Validate_Jobs";
    Layout = "~/Areas/Statements/Views/Shared/_Layout.cshtml";
}

<!doctype html>
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="stylesheet" href="/docs/css/bootstrap-flatly.min.css" />
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" />
    <link rel="stylesheet" href="/css/site.css" />
    <link rel="stylesheet" href="//ui-grid.info/release/ui-grid-unstable.min.css" />
    
    
    <script src="https://sidecar.gitter.im/dist/sidecar.v1.js" async defer></script>
    <style>
   
  .full button span {
    background-color: limegreen;
    border-radius: 32px;
    color: black;
  }
  .partially button span {
    background-color: orange;
    border-radius: 32px;
    color: black;
  }
        .grid {
         width: 1700px;
           height: 610px;
            }
.cellToolTip {
    overflow: visible;
}

.tooltip {
  top: 0 !important;
}
    </style>
</head>
<body>

    <nav class="navbar navbar-default navbar-fixed-top">
    </nav>
    <div class="main-content">

        <div class="container-fluid" ng-app="demo">            
            <div class="row">
                <div >
                    <div class="feature" ng-controller="MainCtrl">
                        <script type="text/ng-template" id="cellWithTooltip.html">
                            <div class="ui-grid-cell-contents" tooltip="{{COL_FIELD}}">{{ COL_FIELD }}</div>
                        </script>
                        <h4 class="feature-heading">Validate Jobs</h4>
                        <label>Start Date: </label>&nbsp;&nbsp;
                        <input id="startDate" type="text" class="addDatePicker">
                        
                        <div class="grid" ui-grid="gridOptions" ui-grid-edit ui-grid-pagination ui-grid-selection></div>
                        <div id="dialog" class="dialog" title="Edit MMS Job" style="display:none">
                            <br />
                            <table>
                                <tr>
                                    <td>
                                        <label>INSERTDATE:</label>
                                        <input type="text" name="insertDate" ng-model="insertDate" id="insertDate" readonly />
                                    </td>
                                    <td>
                                        <label>DD:</label>
                                        <input type="text" name="DD" id="DD" size="20" ng-model="dd" readonly />
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <label>JOBNAME:</label>
                                        <input type="text" name="jobName" id="jobName" size="20" ng-model="jobName" readonly />
                                    </td>
                                    <td>
                                        <label>JOBNO:</label>
                                        <input type="text" name="jobNo" id="jobNo" size="20" ng-model="jobNo" readonly />
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <label>Notes:</label>
                                        <input type="text" name="Notes" id="Notes" ng-model="notes" />
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <input id="site" type="text" style="display:none" />
                                        <input id="tableId" type="text" style="display:none" />
                                    </td>
                                </tr>
                                @*<tr>
                        <td>
                            <button id="editMMS" name="editMMS" ng-click="editMMS()">Edit MMS</button>
                        </td>
                    </tr>*@
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div>

        <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
        <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js"></script>
        <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular-animate.js"></script>
        <script src="//ui-grid.info/release/ui-grid-unstable.min.js"></script>
        <script src="https://github.com/angular-ui/ui-grid.info/tree/gh-pages/release/3.0.1"></script>
        
        <script src="http://ui-grid.info/release/ui-grid-unstable.js"></script>
        <script src="//angular-ui.github.io/bootstrap/ui-bootstrap-tpls-1.2.5.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js" type="text/javascript"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.1/jquery-ui.min.js" type="text/javascript"></script>

        @*@Scripts.Render("~/bundles/datepicker")*@
        
        <script type="text/javascript">
    ShowModelPopUp = function () {
        window.showModalDialog('/Validate_FD_Jobs/OpenModelPopup', "WindowPopup", 'width=600px,height=400px');

    }
        </script>

        <script>                          
            var dataList1 = [];
            angular.module('demo', ['ui.grid', 'ui.grid.edit', 'ui.grid.resizeColumns', 'ui.grid.pagination']).
            controller('MainCtrl', ['$scope', '$http', '$log', '$timeout', 'uiGridConstants', function ($scope, $http, $log, $timeout, uiGridConstants) {
                
                $scope.initialLoad = function(page)
                {
                    var myModel1 = @{@Html.Raw(Json.Encode(Model));}; 
                    
                for (var i = 0; i < myModel1.length; i++) {
                    dataList1[i] =
                        {
                            "tableid":myModel1[i].tableid,
                            "site":myModel1[i].site,
                            "Insert_Date":myModel1[i].Insert_Date,
                            "Jobname": myModel1[i].Jobname,
                            "Jobno": myModel1[i].Jobno,
                            "dd": myModel1[i].dd,
                            "MMSPieces":myModel1[i].MMSPieces,
                            "FD_MMSPieces":myModel1[i].FD_MMSPieces,
                            "FDpiecesReceived":myModel1[i].FDpiecesReceived,
                            "FDReceivedDatetime":myModel1[i].FDReceivedDatetime,
                            "Time_Elapsed":myModel1[i].Time_Elapsed,
                            "Notes":myModel1[i].Notes,
                            "Entered_by":myModel1[i].Entered_by,
                            "Date_Time":myModel1[i].Date_Time
                        }
                };                
                $scope.gridOptions = {                             
                    paginationPageSizes: [15, 30, 45],
                    paginationPageSize: 15,
                    enablePaginationControls: true,
                    paginationCurrentPage: 1,
                    enableFiltering: true,
                    enableHorizontalScrollbar:false,
                    showGridFooter: true,
                    enableSorting: true,
                    columnDefs: [
                    {name: 'tableid', width: 75,  visible:false, },
                    {name: 'site', width: 75},
                    {name: 'Insert_Date', displayName:'MMS_Sent_Date',width: 150},
                    {name: 'Jobname', displayName:'Job_Name', width: 100, enableFiltering: false},
                    {name: 'Jobno', displayName:'Job_no', width: 100, enableFiltering: false},
                    {name: 'dd',displayName:'DD', width: 75, enableFiltering: false},
                    {name: 'MMSPieces', displayName:'MMSPieces' ,width: 100, enableFiltering: false},
                    {name: 'FD_MMSPieces',displayName:'FD_Ack_Pieces',width: 130, enableFiltering: false},
                    {name:'FDpiecesReceived', displayName:'FD_Pieces_Received', width: 153,enableFiltering: false},
                    {name:'FDReceivedDatetime',displayName:'FDReceivedDatetime', width: 160},
                    {name:'Time_Elapsed',width: 120, enableFiltering: false},
                    {name:'Notes',width: "*", enableFiltering: false, cellToolTip: function(row,col){return 'Notes: '+row.entity.Notes +'Desc:' + row.entity.Description;}},
                    {name: 'Entered_by',width: 100, enableFiltering: false},
                    {name:'Date_Time',displayName:'Date_Time', width:150, enableFiltering: false},
                    {name:'Action', enableFiltering: false, cellTemplate:'<a href="#" onclick="ShowModelPopUp();">Edit</a>', width:75},
                    {name:' ', enableFiltering: false, cellTemplate:'<b><button type="button" class="btn btn-xs btn-primary" ng-click="grid.appScope.editRow1(grid, row);">Edit</button></b>', width:65}
                    ] 
                    ,
                    data: dataList1
                };                          
                };

                $scope.dataReload = function(){
                   // $scope.gridApi.core.notifyDataChange(uiGridConstants.dataChange.ALL); 
                };

                $scope.initialLoad(1);

                var dialogFunc =  $("#dialog").show().dialog({
                    autoOpen: false,
                    closeOnEscape: true,
                   draggable: true,
                    height: 300,
                    width: 500,
                    dialogClass: "alert",
                    buttons: [
                                {
                                    text: "Save",
                                    icons: {
                                        primary: "ui-icon-heart"
                                    },
                                    click: function() {                                                
                                        var Validations_jobs_Notes_Update_Model =
                                        {
                                            "notes":$("#Notes").val(),
                                            "tableId": $("#tableId").val(),
                                            "Jobno": $("#jobNo").val(),
                                            "Jobname": $("#jobName").val(),
                                            "dd": $("#DD").val(),
                                            "site": $("#site").val(),
                                            "Entered_by": "VB96073",
                                            //"Date_Time":DateTime.Now
                                        };

                                        $.ajax({
                                            url: '/Validate_FD_Jobs/UpdateNotes',
                                            data: JSON.stringify(Validations_jobs_Notes_Update_Model),
                                            type: 'POST',
                                            dataType: "json",
                                            traditional: true,
                                            contentType: 'application/json; charset=utf-8',
                                            success: function (data) {
                                                $scope.initialLoad(0);
                                            },
                                            error: function (data) {
                                                alert("ERROR  from AJAX call ");
                                            }
                                        });
                                        $( this ).dialog( "close" );
                                    }
                                },
                                {
                                    text: "Close",
                                    icons: {
                                        primary: "ui-icon-heart"
                                    },
                                    click: function() {
                                        $( this ).dialog( "close" );
                                    }
                                }
                    ]
                });

                $scope.editRow1 = function (grid, row){
                    $("#insertDate").val(row.entity.Insert_Date);
                    $("#jobName").val(row.entity.Jobname);
                    $("#jobNo").val(row.entity.Jobno);
                    $("#DD").val(row.entity.dd);
                    $("#Notes").val(row.entity.Notes);       
                    $("#site").val(row.entity.site);
                    $("#tableId").val(row.entity.tableid);
                    dialogFunc.dialog("open","closeOnEscape", true);     
                    dialogFunc.on('dialogclose',function(event){
                          $scope.dataload($scope.gridOptions.paginationCurrentPage);                                                
                    });
                };

                $scope.dataload = function(page){
                    $.ajax({
                        type: 'GET',
                        contentType: 'application/json; charset=utf-8',
                        url: '/Validate_FD_Jobs/getValidateJobs',
                        success: function (data) {
                            var myModel1 =data;
                            var dataList2 =[];
                            for (var i = 0; i < myModel1.length; i++) {
                                dataList2[i] =
                                    {
                                        "tableid":myModel1[i].tableid,
                                        "site":myModel1[i].site,
                                        "Insert_Date":myModel1[i].Insert_Date,
                                        "Jobname": myModel1[i].Jobname,
                                        "Jobno": myModel1[i].Jobno,
                                        "dd": myModel1[i].dd,
                                        "MMSPieces":myModel1[i].MMSPieces,
                                        "FD_MMSPieces":myModel1[i].FD_MMSPieces,
                                        "FDpiecesReceived":myModel1[i].FDpiecesReceived,
                                        "FDReceivedDatetime":myModel1[i].FDReceivedDatetime,
                                        "Time_Elapsed":myModel1[i].Time_Elapsed,
                                        "Notes":myModel1[i].Notes,
                                        "Entered_by":myModel1[i].Entered_by,
                                        "Date_Time":myModel1[i].Date_Time
                                    }
                            };
                            //alert ("from rootscope: " + dataList2[0].Jobname);
                            $scope.gridOptions.data = dataList2;
                            $scope.dataReload();
                            //$scope.gridApi.core.notifyDataChange(uiGridConstants.dataChange.ALL); 
                            //$scope.gridOptions.paginationCurrentPage = $scope.gridOptions.paginationCurrentPage
                          window.location.reload();
                        },
                        error: function (data) {
                            alert("Error message");
                        }
                    });
                };

             }])                    
        </script>
        </div>
</body>
</html>

**Comment by babukota** [comment]
@model IList<TSMISWebApp_2016.Areas.Statements.Models.VALIDATION_JOBS_SENT_FD>

@{
    ViewBag.Title = "Validate_Jobs";
    Layout = "~/Areas/Statements/Views/Shared/_Layout.cshtml";
}




<!doctype html>
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="stylesheet" href="/docs/css/bootstrap-flatly.min.css" />
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" />
    <link rel="stylesheet" href="/css/site.css" />
    <link rel="stylesheet" href="//ui-grid.info/release/ui-grid-unstable.min.css" />
    
    
    <script src="https://sidecar.gitter.im/dist/sidecar.v1.js" async defer></script>
    <style>
   
  .full button span {
    background-color: limegreen;
    border-radius: 32px;
    color: black;
  }
  .partially button span {
    background-color: orange;
    border-radius: 32px;
    color: black;
  }
        .grid {
         width: 1700px;
           height: 610px;
            }
.cellToolTip {
    overflow: visible;
}


.tooltip {
  top: 0 !important;
}
    </style>
</head>
<body>

    <nav class="navbar navbar-default navbar-fixed-top">
    </nav>
    <div class="main-content">

        <div class="container-fluid" ng-app="demo">            
            <div class="row">
                <div >
                    <div class="feature" ng-controller="MainCtrl">
                        <script type="text/ng-template" id="cellWithTooltip.html">
                            <div class="ui-grid-cell-contents" tooltip="{{COL_FIELD}}">{{ COL_FIELD }}</div>
                        </script>
                        <h4 class="feature-heading">Validate Jobs</h4>
                        <label>Start Date: </label>&nbsp;&nbsp;
                        <input id="startDate" type="text" class="addDatePicker">
                        
                        <div class="grid" ui-grid="gridOptions" ui-grid-edit ui-grid-pagination ui-grid-selection></div>
                        <div id="dialog" class="dialog" title="Edit MMS Job" style="display:none">
                            <br />
                            <table>
                                <tr>
                                    <td>
                                        <label>INSERTDATE:</label>
                                        <input type="text" name="insertDate" ng-model="insertDate" id="insertDate" readonly />
                                    </td>
                                    <td>
                                        <label>DD:</label>
                                        <input type="text" name="DD" id="DD" size="20" ng-model="dd" readonly />
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <label>JOBNAME:</label>
                                        <input type="text" name="jobName" id="jobName" size="20" ng-model="jobName" readonly />
                                    </td>
                                    <td>
                                        <label>JOBNO:</label>
                                        <input type="text" name="jobNo" id="jobNo" size="20" ng-model="jobNo" readonly />
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <label>Notes:</label>
                                        <input type="text" name="Notes" id="Notes" ng-model="notes" />
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <input id="site" type="text" style="display:none" />
                                        <input id="tableId" type="text" style="display:none" />
                                    </td>
                                </tr>
                                @*<tr>
                        <td>
                            <button id="editMMS" name="editMMS" ng-click="editMMS()">Edit MMS</button>
                        </td>
                    </tr>*@
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div>


        <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
        <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js"></script>
        <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular-animate.js"></script>
        <script src="//ui-grid.info/release/ui-grid-unstable.min.js"></script>
        <script src="https://github.com/angular-ui/ui-grid.info/tree/gh-pages/release/3.0.1"></script>
        
        <script src="http://ui-grid.info/release/ui-grid-unstable.js"></script>
        <script src="//angular-ui.github.io/bootstrap/ui-bootstrap-tpls-1.2.5.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js" type="text/javascript"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.1/jquery-ui.min.js" type="text/javascript"></script>

        @*@Scripts.Render("~/bundles/datepicker")*@
        
        <script type="text/javascript">
    ShowModelPopUp = function () {
        window.showModalDialog('/Validate_FD_Jobs/OpenModelPopup', "WindowPopup", 'width=600px,height=400px');


    }
        </script>

        <script>                          
            var dataList1 = [];
            angular.module('demo', ['ui.grid', 'ui.grid.edit', 'ui.grid.resizeColumns', 'ui.grid.pagination']).
            controller('MainCtrl', ['$scope', '$http', '$log', '$timeout', 'uiGridConstants', function ($scope, $http, $log, $timeout, uiGridConstants) {
                
                $scope.initialLoad = function(page)
                {
                    var myModel1 = @{@Html.Raw(Json.Encode(Model));}; 
                    
                for (var i = 0; i < myModel1.length; i++) {
                    dataList1[i] =
                        {
                            "tableid":myModel1[i].tableid,
                            "site":myModel1[i].site,
                            "Insert_Date":myModel1[i].Insert_Date,
                            "Jobname": myModel1[i].Jobname,
                            "Jobno": myModel1[i].Jobno,
                            "dd": myModel1[i].dd,
                            "MMSPieces":myModel1[i].MMSPieces,
                            "FD_MMSPieces":myModel1[i].FD_MMSPieces,
                            "FDpiecesReceived":myModel1[i].FDpiecesReceived,
                            "FDReceivedDatetime":myModel1[i].FDReceivedDatetime,
                            "Time_Elapsed":myModel1[i].Time_Elapsed,
                            "Notes":myModel1[i].Notes,
                            "Entered_by":myModel1[i].Entered_by,
                            "Date_Time":myModel1[i].Date_Time
                        }
                };                
                $scope.gridOptions = {                             
                    paginationPageSizes: [15, 30, 45],
                    paginationPageSize: 15,
                    enablePaginationControls: true,
                    paginationCurrentPage: 1,
                    enableFiltering: true,
                    enableHorizontalScrollbar:false,
                    showGridFooter: true,
                    enableSorting: true,
                    columnDefs: [
                    {name: 'tableid', width: 75,  visible:false, },
                    {name: 'site', width: 75},
                    {name: 'Insert_Date', displayName:'MMS_Sent_Date',width: 150},
                    {name: 'Jobname', displayName:'Job_Name', width: 100, enableFiltering: false},
                    {name: 'Jobno', displayName:'Job_no', width: 100, enableFiltering: false},
                    {name: 'dd',displayName:'DD', width: 75, enableFiltering: false},
                    {name: 'MMSPieces', displayName:'MMSPieces' ,width: 100, enableFiltering: false},
                    {name: 'FD_MMSPieces',displayName:'FD_Ack_Pieces',width: 130, enableFiltering: false},
                    {name:'FDpiecesReceived', displayName:'FD_Pieces_Received', width: 153,enableFiltering: false},
                    {name:'FDReceivedDatetime',displayName:'FDReceivedDatetime', width: 160},
                    {name:'Time_Elapsed',width: 120, enableFiltering: false},
                    {name:'Notes',width: "*", enableFiltering: false, cellToolTip: function(row,col){return 'Notes: '+row.entity.Notes +'Desc:' + row.entity.Description;}},
                    {name: 'Entered_by',width: 100, enableFiltering: false},
                    {name:'Date_Time',displayName:'Date_Time', width:150, enableFiltering: false},
                    {name:'Action', enableFiltering: false, cellTemplate:'<a href="#" onclick="ShowModelPopUp();">Edit</a>', width:75},
                    {name:' ', enableFiltering: false, cellTemplate:'<b><button type="button" class="btn btn-xs btn-primary" ng-click="grid.appScope.editRow1(grid, row);">Edit</button></b>', width:65}
                    ] 
                    ,
                    data: dataList1
                };                          
                };

                $scope.dataReload = function(){
                   // $scope.gridApi.core.notifyDataChange(uiGridConstants.dataChange.ALL); 
                };

                $scope.initialLoad(1);

                var dialogFunc =  $("#dialog").show().dialog({
                    autoOpen: false,
                    closeOnEscape: true,
                   draggable: true,
                    height: 300,
                    width: 500,
                    dialogClass: "alert",
                    buttons: [
                                {
                                    text: "Save",
                                    icons: {
                                        primary: "ui-icon-heart"
                                    },
                                    click: function() {                                                
                                        var Validations_jobs_Notes_Update_Model =
                                        {
                                            "notes":$("#Notes").val(),
                                            "tableId": $("#tableId").val(),
                                            "Jobno": $("#jobNo").val(),
                                            "Jobname": $("#jobName").val(),
                                            "dd": $("#DD").val(),
                                            "site": $("#site").val(),
                                            "Entered_by": "VB96073",
                                            //"Date_Time":DateTime.Now
                                        };

                                        $.ajax({
                                            url: '/Validate_FD_Jobs/UpdateNotes',
                                            data: JSON.stringify(Validations_jobs_Notes_Update_Model),
                                            type: 'POST',
                                            dataType: "json",
                                            traditional: true,
                                            contentType: 'application/json; charset=utf-8',
                                            success: function (data) {
                                                $scope.initialLoad(0);
                                            },
                                            error: function (data) {
                                                alert("ERROR  from AJAX call ");
                                            }
                                        });
                                        $( this ).dialog( "close" );
                                    }
                                },
                                {
                                    text: "Close",
                                    icons: {
                                        primary: "ui-icon-heart"
                                    },
                                    click: function() {
                                        $( this ).dialog( "close" );
                                    }
                                }
                    ]
                });

                $scope.editRow1 = function (grid, row){
                    $("#insertDate").val(row.entity.Insert_Date);
                    $("#jobName").val(row.entity.Jobname);
                    $("#jobNo").val(row.entity.Jobno);
                    $("#DD").val(row.entity.dd);
                    $("#Notes").val(row.entity.Notes);       
                    $("#site").val(row.entity.site);
                    $("#tableId").val(row.entity.tableid);
                    dialogFunc.dialog("open","closeOnEscape", true);     
                    dialogFunc.on('dialogclose',function(event){
                          $scope.dataload($scope.gridOptions.paginationCurrentPage);                                                
                    });
                };

                $scope.dataload = function(page){
                    $.ajax({
                        type: 'GET',
                        contentType: 'application/json; charset=utf-8',
                        url: '/Validate_FD_Jobs/getValidateJobs',
                        success: function (data) {
                            var myModel1 =data;
                            var dataList2 =[];
                            for (var i = 0; i < myModel1.length; i++) {
                                dataList2[i] =
                                    {
                                        "tableid":myModel1[i].tableid,
                                        "site":myModel1[i].site,
                                        "Insert_Date":myModel1[i].Insert_Date,
                                        "Jobname": myModel1[i].Jobname,
                                        "Jobno": myModel1[i].Jobno,
                                        "dd": myModel1[i].dd,
                                        "MMSPieces":myModel1[i].MMSPieces,
                                        "FD_MMSPieces":myModel1[i].FD_MMSPieces,
                                        "FDpiecesReceived":myModel1[i].FDpiecesReceived,
                                        "FDReceivedDatetime":myModel1[i].FDReceivedDatetime,
                                        "Time_Elapsed":myModel1[i].Time_Elapsed,
                                        "Notes":myModel1[i].Notes,
                                        "Entered_by":myModel1[i].Entered_by,
                                        "Date_Time":myModel1[i].Date_Time
                                    }
                            };
                            //alert ("from rootscope: " + dataList2[0].Jobname);
                            $scope.gridOptions.data = dataList2;
                            $scope.dataReload();
                            //$scope.gridApi.core.notifyDataChange(uiGridConstants.dataChange.ALL); 
                            //$scope.gridOptions.paginationCurrentPage = $scope.gridOptions.paginationCurrentPage
                          window.location.reload();
                        },
                        error: function (data) {
                            alert("Error message");
                        }
                    });
                };


             }])                    
        </script>
        </div>
</body>
</html>

**Comment by PaulL1** [comment]
I don't see you calling onRegisterApi anywhere, this is usually required to get a reference to the gridApi.

**Comment by vishnusreek** [comment]
Now I added onRegisterApi in $scope.gridOptions ={..data:myData,onRegisterApi: function(gridApi){
$scope.gridApi = gridApi}. Now it is working fine. 

None of the updateGrid example they proivded onRegisterApi as mandatory, so didn't had idea.

Thanks a lot!!!

**Comment by babukota** [comment]
The above comment was from me (babukota). I want to close this issue

**Comment by babukota** [comment]
Paul,

Can you please help me out on how to get CellToolTip: on mouseover/hover on
a column when i move mouse over the cell the data should be displayed. See
below code which is extension to earlier. I tried different ways but
couldn't get succeed.


<!doctype html>
<html class="no-js" lang="en">
<head>
    <title></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <link rel="stylesheet" href="//
ui-grid.info/release/ui-grid-unstable.min.css" />
    @*<link href="~/public/css/ui-grid-unstable.min.css" rel="stylesheet"
/>*@
    <script src="~/public/js/jquery-2.1.4.min.js"></script>
    <script src="~/public/js/bootstrap.min.js"></script>
    <script src="~/public/js/AngularJS/angular.js"></script>
    <script src="~/public/js/AngularJS/angular-animate.js"></script>
    <script src="~/public/js/ui-grid-unstable.min.js"></script>
    <script src="~/public/js/ui-bootstrap-tpls-1.2.5.js"></script>
    <script src="~/public/js/jquery-1.10.2.js"></script>
    <script src="~/public/js/jquery-ui.min.js"></script>
    <script src="~/public/js/bootstrap-datepicker.js"></script>
    <script src="~/public/js/validateFDAngular.js"></script>
    <link href="~/public/css/validateFD.css" rel="stylesheet" />

    <style>

    </style>
</head>
<body>

    <nav class="navbar navbar-default navbar-fixed-top">
    </nav>
    <div class="main-content">

        <div class="container-fluid" ng-app="demo">
            <div class="row">
                <div>
                    <div class="feature" ng-controller="MainCtrl">
                        <h4 class="feature-heading">Validate Jobs</h4>
                        <br />

                        <br />
                        <div class="grid" ui-grid="gridOptions"
ui-grid-pagination ></div>

                        <br />
</div>
</div>
</div>
</div>
</body>


var app = angular.module('demo', ['ui.grid', 'ui.bootstrap',
'ui.grid.resizeColumns', 'ui.grid.pagination']);
app.factory('validateFDService', function () {

});
app.controller('MainCtrl', ['$scope', '$http', '$log', '$timeout',
'uiGridConstants', function ($scope, $http, $log, $timeout,
uiGridConstants) {
    $scope.modelData = [];
    $scope.filterValidation = "*Select either Site or Start/end date for
data filter";
    $scope.endDateValidation = "*endDate can not be empty or less than
startDate";
    $scope.noSearchResults = "*No Search Results";
    $scope.filterNotSelected = true;
    $scope.endDateValidationHide = true;
    $scope.noSearchResultsHide = true;
    $scope.dataload = function (page) {
        $.ajax({
            cache: false,
            type: 'GET',
            contentType: 'application/json; charset=utf-8',
            url: '/Validate_FD_Jobs/FilterValidateJobs',
            data: { siteSelected: $scope.siteFilter, startDate:
$scope.filterStartDate, endDate: $scope.filterEndDate },
            success: function (data) {
                // alert ("from rootscope: " + dataList2[0].Notes + " " +
$scope.counter);
                if (data == null || data.length === 0) {
                    $scope.noSearchResultsHide = false;
                };
                $scope.gridOptions.data = data;

$scope.gridApi.core.notifyDataChange(uiGridConstants.dataChange.ALL);
                $scope.gridOptions.paginationCurrentPage =
$scope.gridOptions.paginationCurrentPage
            },
            error: function (data) {
                alert("Error message");
            }
        });
    };

    $scope.initialLoad = function (page) {
        $scope.gridOptions = {
            paginationPageSizes: [15, 30, 45],
            paginationPageSize: 15,
            enablePaginationControls: true,
            paginationCurrentPage: 1,
            enableFiltering: true,
            enableHorizontalScrollbar: false,
            showGridFooter: true,
            enableSorting: true,
            columnDefs: [

            { name: 'tableid', width: 75, visible: false, },
            { name: 'Action', enableFiltering: false, cellTemplate: '<a
href="#ex1" rel="modal:open" ng-click="grid.appScope.editRow1(grid,
row);"">Edit</a>', width: 75},
            { name: 'site', width: 75},
            { name: 'Insert_Date', displayName: 'MMS_Sent_Date', width:
150, enableFiltering: false},
            { name: 'Jobname', displayName: 'Job_Name', width: 100},
            { name: 'Jobno', displayName: 'Job_no', width: 100},
            { name: 'dd', displayName: 'DD', width: 75, enableFiltering:
false},
            { name: 'MMSPieces', displayName: 'MMSPieces', width: 100,
enableFiltering: false},
            { name: 'FD_MMSPieces', displayName: 'FD_Ack_Pieces', width:
130, enableFiltering: false},
            { name: 'FDpiecesReceived', displayName: 'FD_Pieces_Received',
width: 153, enableFiltering: false},
            { name: 'FDReceivedDatetime', displayName:
'FDReceivedDatetime', width: 160, enableFiltering: false},
            { name: 'Time_Elapsed', width: 120, enableFiltering: false},
            { name: 'Notes', width: "*", enableFiltering: false, *cellToolTip:
true*},
            { name: 'Entered_by', width: 100, enableFiltering: false},
            { name: 'Date_Time', displayName: 'Date_Time', width: 150,
enableFiltering: false}
            ]
            ,
            onRegisterApi: function (gridApi) {
                $scope.gridApi = gridApi;
            }
        };
    };

    $scope.initialLoad(1);
    $scope.dataload(0);
}]);

**Comment by angular-git-user** [comment]
you just need to add `cellTooltip: true, headerTooltip: true` in each of youre column defs where ever you need them

**Comment by angular-git-user** [comment]
` { name: 'Notes', width: "*", enableFiltering: false, cellTooltip: true},`
         `   { name: 'Entered_by', width: 100, enableFiltering: false}`

**Comment by babukota** [comment]
Thanks you everyone, it worked. My bad I was using CellToolTip all the time
and it didn't worked. After changing to CelTooltip:true it worked. Thank
you!!!
