### ISSUE TITLE
Contents of a pinned column are not scrollable with long text in the cell

### ISSUE THREAD

**Issue by wbrycki** [angular-ui/ui-grid#5247]
I have a pinned column to the right and when I place a long text inside a cell, the contents of this cell (or a column) are not scrollable.

I would expect, that when I insert a longer text I'm able to see it without editing the cell (like a column width auto-adjust option).

Plunker:
http://plnkr.co/edit/XV8KSwqYuUQwz17Qomg4?p=preview

**Comment by mportuga** [comment]
I don't believe making the column scrollable is the right solution, at most we could rely on a tooltip and ellipsis for that
