### ISSUE TITLE
grids initial rows not visible if scrolled when it becomed visible 

### ISSUE THREAD

**Issue by bhantol** [angular-ui/ui-grid#5249]
I have grid that I enable or disable using ng-show.

Go to the [top rows invisible plnkr](http://plnkr.co/edit/vfD0izav1jH0tPy1s6HY?p=preview) and follow these steps:
1. Click on `Click Me` button. A grid will be displayed.
2. Scroll to about 6 rows.
3. Now `Click Me`
4. You will see first few rows not visible. There is a blank space. If you scrolled all the more than the page none of the rows are visible.

**Comment by yogeshgadge** [comment]
No issues with ng-if
But that is basically destroying and recreating the grid itself.
http://plnkr.co/edit/KlLhbAIgbCRpvpH3vJhP?p=preview
