### ISSUE TITLE
Right Click event in Context Menu

### ISSUE THREAD

**Issue by samit2015** [angular-ui/ui-grid#5261]
Hi,

I have added Context Menu by using ngContextMenu on ui grid where one menu says display row id. I am doing this under context menu

['Display Document ID', function ($itemScope) {
                alert($itemScope.id);//Its coming blank/undefined
            }]

Can u plz help me how can i get it?

**Comment by samit2015** [comment]
got it

$itemScope.gridOptions.data[0].id

**Comment by samit2015** [comment]
This will fail if I sort data... :-( 

Does any know on right click >> Context menu>> How to get row data

**Comment by stduolc** [comment]
hi, did you implement the function at last?

**Comment by stduolc** [comment]
@samit2015 hi, did you implement the function at last?

**Comment by samit2015** [comment]
Yes ...I was able to do it
