### ISSUE TITLE
Feature Request: Sort column by a value that isn't what is displayed in the grid

### ISSUE THREAD

**Issue by fergusonna** [angular-ui/ui-grid#5265]
The ability to have a hidden value in the row.entity that is used to sort the column instead of the value shown in the column. 

Say I have a list of users, with a hidden ID for each user on the list. It would be a great feature to simply have to set a sortByField value in the columnDef instead of defining a custom sortingAlgorithm.

**Comment by juunp** [comment]
You can add a column with ID as field, set visible to false and add the sort you want on the column to sort the grid.
