### ISSUE TITLE
I want New row to be the first row of the grid even after sorting

### ISSUE THREAD

**Issue by dhawkKD** [angular-ui/ui-grid#5268]
Currently I am facing an issue, when I am adding a new row it comes on the first row of the grid, which is what I am expecting but when I am clicking on sorting, it went to last row. Is there any way through which my new row will always be the first row in the grid even after sorting or filtering.

**Comment by juunp** [comment]
I think you can add a column with 'isNew' as field (adding isNew to all new objects), set a sort with priority: 0
