### ISSUE TITLE
[bug]error occur when custom a editableCellTemplate

### ISSUE THREAD

**Issue by buaasun** [angular-ui/ui-grid#5271]
I add a select element in a `editableCellTemplate` , but when I double click the company cell to edit it, an error occured like this

``` error
angular.js:12330 TypeError: $elm[0].select is not a function
    at ui-grid.js:16365
    at angular.js:17709
    at completeOutstandingRequest (angular.js:5394)
    at angular.js:5666
```

[plnkr](http://plnkr.co/edit/FefZzxxOkr2tjc13eq3b) is here. Is this a bug of ui-grid?

**Comment by SergeyCherman** [comment]
uiGrid custom editable templates require that you handle the closing of the cell yourself. See an explaination/example for ui-select in http://brianhann.com/ui-grid-and-dropdowns/

UI-Grid does support regular dropdowns via a definition in the grid options as shown in http://ui-grid.info/docs/#/tutorial/201_editable

If you want to use a custom template with an HTML select in it you can do something like this:

    .directive("uiGridSelect", uiGridSelect)
    uiGridSelect.$inject = ['$document', 'uiGridEditConstants'];
```

   function uiGridSelect($document, uiGridEditConstants) {
    return function link($scope, $elm, $attr) {
      $document.on('click', docClick);
      $document.on('change', function(){
        $scope.$emit(uiGridEditConstants.events.END_CELL_EDIT)
      });

      function docClick(evt) {
        if ($(evt.target).closest('select').size() === 0) {
          $scope.$emit(uiGridEditConstants.events.END_CELL_EDIT);
          $document.off('click', docClick);
        }
      }
    };
  }

```
` editableCellTemplate: "<select ui-grid-select ng-class=\"\'colt\' + col.uid\" data-ng-options=\"field for field in grid.appScope.sampleData\" ng-model=\"MODEL_COL_FIELD\"><option value=\"\" ng-if=\"false\"></option></select>"`
