### ISSUE TITLE
in angularjs gridApi.selection.on issue

### ISSUE THREAD

**Issue by PraveenBaltha** [angular-ui/ui-grid#5284]
Hi Friends,
I am new to the ui-grid. I am facing one issue , after populating ui-grid trying to get the selected row of grid. 

in module i have added the ['ui-grid,'ui.grid.selection'].please add the attachment .
After running the grunt , requirejs not able to find the 'ui.grid.selection' is there any downloadable file  to set the path in ui.gird.selection.

![image](https://cloud.githubusercontent.com/assets/9865404/14274618/057b62d2-fb30-11e5-8b03-7ffbea3a4480.png)

![image](https://cloud.githubusercontent.com/assets/9865404/14274711/9dbe1e0e-fb30-11e5-8120-f1b04757aeb0.png)

if i remove the ui.grid.selection getting the below issue;
![image](https://cloud.githubusercontent.com/assets/9865404/14275104/f410c7fa-fb32-11e5-83eb-1e9b08deac70.png)

**Comment by stevenlius** [comment]
Did you specify ui-grid-selection as attribute in the div tag?

**Comment by PraveenBaltha** [comment]
Thanks for response .
yes i have given in div tag. It bugging me like anything . 
![image](https://cloud.githubusercontent.com/assets/9865404/14288085/e6c2af2e-fb72-11e5-9f3e-f92c4a3a7d72.png)

**Comment by PraveenBaltha** [comment]
Hi Stevenlius,

please find the screen shot . I have added the ui-grid-selection in div tag also;

![image](https://cloud.githubusercontent.com/assets/9865404/14291964/8929f49c-fb83-11e5-8a71-5745adfd099b.png)

**Comment by stevenlius** [comment]
Did you miss 'ui.grid' in the module?

**Comment by PraveenBaltha** [comment]
Hi 
No I mentioned in the dashboard module..

![image](https://cloud.githubusercontent.com/assets/9865404/14321675/d54d5c24-fc37-11e5-9f97-f915af4296ea.png)
