### ISSUE TITLE
is posible undo edits cells?

### ISSUE THREAD

**Issue by eduard10000** [angular-ui/ui-grid#5287]
i don't find anything fot this.  can this a new features?

**Comment by stevenlius** [comment]
Currently, I guess such feature is not existed. But you can work around it by having a cache-ish object array to store pre-changed values. 

`[{column: x, row: y, data: data:soemthing}, {column: x: row: y: data:soemthing}]. `

When data is about to change, put it property to this array, if undo is clicked, revert the data grid cell with the last item from the array.

**Comment by ladislaogarcia** [comment]
It works. Just one codeline.
$scope.gridApi.edit.on.afterCellEdit( $scope , function (rowEntity , colDef , newValue , oldValue ) {
    rowEntity[colDef.name] = oldValue;
});

It takes the column name and take that cell on the selected row. Then, it just left to assign old value to that cell.
