### ISSUE TITLE
Is there any way to enable External Pagination with Scrolling?

### ISSUE THREAD

**Issue by cheahkhing** [angular-ui/ui-grid#5291]
Hi, 

I am trying to figure out how to enable this kind of behaviour:

The grid will be using External Pagination, which would probably be a REST service that supports Page Size, and start at which page, etc.

On the initial load, the REST service will return the data for first page, and also the total numbers of rows available.

So, let say now the total is 1000, and first page is 100. 
The grid will show a scrollbar for the grid with length of 1000 items in it. But in fact, it only has 100 rows of data.

Whenever user scrolls down reaching row number 100, it will knows to fetch more data from the service by passing the current page, and get the data back to display.

Is this behaviour achievable with ui-grid?

**Comment by stevenlius** [comment]
What you are looking for is called lazy loading or infinite loading, the exact behavior is not achievable with UI grid. But you can work around this by implementing your own behavior. 

1. Render scroll bar length according to data length. (I couldn't find a way to set the scrollbar size without given the initialized array)
2. Register scrollEnd on GridApi to listen scroll event. 
         `if in the viewport do not data
              retrieve from backed`
            3. Async call to server to retrieve data 
            4. Append the result to the data array 
            5. Refresh the data grid.

**Comment by cheahkhing** [comment]
@stevenlius Thanks for your pointer. However, for (1), if the scrollbar need to have full length of array then only works, seems to be defeating the purpose? 
The idea is to lazy load the data, if we already fully load everything, that's no longer lazy load.
I'll try out with your idea and see if the scrollbar can be override.

**Comment by stevenlius** [comment]
You are correctly, we found out that it have performance issues when loading large set of data. As you have to do angular.copy to do data swap. Which it is deep copy operation. 

We have recently changed our implementing, and this might be the better solution, so
1. Instead of using their native scrollbar, we disabled it and we created our own scrollbar next to the grid. (Responsive, full control) 
2.  We set the grid to view only render 12 rows in total, and we just keep replacing rows when user scroll ends. 
3. It is still smooth and you won't notice the difference. We pre-cached 500 items before the selected item point and the next 500 items as well. 
4. We have a table with 4million rows, server retrieve only 1000items at a time take under 250ms, rendering cells takes less than 50ms, so within 300ms, we complete the operation.

**Comment by lukaszbachman** [comment]
@stevenlius any chance you could prepare a demo showing that in a jsfiddle or plunker? I'd love to see that in action before I invest the time in developing something similar for my project. Thanks.

**Comment by PaulL1** [comment]
Can you not use the infinite scroll feature?  That's exactly what it's for.

**Comment by cheahkhing** [comment]
@PaulL1 If you read through the details, you'll see that infinite scroll doesn't fit our requirements.
Infinite scroll feature will only show you the scrollbar of what's currently available.
In our case, we need to show user the "fake" scrollbar height that tells how much exactly the data is.
For eg: our pagination server will return total records is 5000, so the length of the scrollbar will be very long for user to scroll through / jump to a specific page.

As for infinite scrolling, you can't do this at all. The user will lose the capability of quickly "jumping" to a specific page. You always need to scroll down, wait for it to load, page by page, which is slow.

Hope you got what I am trying to say.

**Comment by stevenlius** [comment]
@cheahking The final implementation that we completed is something looks like this. http://www.jeasyui.com/demo/main/index.php?plugin=DataGrid&theme=default&dir=ltr&pitem=

**Comment by stevenlius** [comment]
@cheahkhing check the thing that is called virtual scrolling.

**Comment by PaulL1** [comment]
I do see what you're saying, but that wouldn't be overly hard to add to infinite scroll (infinite scroll itself has very little code in it).  Perhaps you could submit a PR with those extensions?

**Comment by stevenlius** [comment]
@PaulL1   I would not put this extension in infinite scroll, as it complicate its natural purpose of infinite scroll. I would create a separate feature as virtual scroll as it behaves quite differently. 

Use case: 
1. user knows the length of total data set and want to go through partial of data easily. 
2. user will be able to scroll to the any point to retrieve the set of data through their own REST api.

**Comment by lukaszbachman** [comment]
@stevenlius that's exactly what we are looking for. I was hoping you could show off  your own implementation in ui-grid, but if that's not feasible then OK.

@PaulL1, I'll have a look if I could patch this up. Infinity scroll is indeed very close to what we want. It's just the scrollbar what needs to be adjusted.
