### ISSUE TITLE
Dynamically added grid

### ISSUE THREAD

**Issue by BirdDog69** [angular-ui/ui-grid#5293]
Hey all,

I'm trying to use the uiGrid in an MVC Application, which also uses Angular tabs that are dynamically added based on what the user selects in a menu. Out initial tab (which is always there) comes up fine with the grid there and populated. Unfortunately that's the end of the happy story.  Thereafter whenever the user clicks a menu item, a new tab appears, but the grid isn't there. I'm brand spanking new to Angular, so I'm sure it's something I'm doing wrong. Does anybody have an example of this type of scenario, or are able to resources that could get me on the right track?

Many thanks in advance

**Comment by Grandizer** [comment]
@BirdDog69 did you ever get this working.  This is nearly 100% exactly what I am trying to do.  This link http://stackoverflow.com/questions/32470817/i-want-to-write-a-custom-directive-for-ui-grid-with-different-input-columndefs got the ball rolling but does not seem to work for me.  I have posted a question here http://stackoverflow.com/questions/37031864/how-to-dynamically-create-multiple-ui-grids-with-angular but do not have a response yet.

**Comment by BirdDog69** [comment]
Sorry for the delayed response Grandizer. Sadly, no so we moved on to another tool. Does look like you got an answer to your question on stackoverflow though, so might need to revisit it if our other path fails.
