### ISSUE TITLE
UI Grid Dropdown not working as expected

### ISSUE THREAD

**Issue by muralidharan-mohan** [angular-ui/ui-grid#5294]
Hello Ui Grid Team,
First i need to say thanks for providing wonderful UI grid Component.
I found one issue in Ui grid,  
changed Dropdwon value is not updating in UI Grid. 
I created Plunker http://plnkr.co/edit/PfhT9P8CPIa54iAMvw4N?p=preview
Please check issue.
Thanks in advance.

**Comment by The3ngineer** [comment]
I think this is the same issue we are experiencing. In our testing with version grid 3.1.1 on iOS 9.3.2 on (at least) iPad Pro 9 inch and iPhone 5 the dropdown is only saving results when going through the options in one direction. For example, we have  a male/female selection and if male is selected we can edit it and select/save female but not the other way around.
It is also happening on the ui-grid.info Tutorials section 201 Edit Feature. We are currently taking a look in more detail and will post anything we find.

**Comment by AndriyTG** [comment]
Hello,

I ran into this same issue and found a work around. Ui.Grid has an example where one column is selected via mobile device and allows selected value to be retained.

Please see column status column in http://ui-grid.info/docs/#/tutorial/201_editable grid.

**Comment by dlgski** [comment]
Thank you @AndriyTG closing this issue.
