### ISSUE TITLE
Grid header height is off, filter input not showing (reopening #1796)

### ISSUE THREAD

**Issue by MartijnWelker** [angular-ui/ui-grid#5302]
I have the same issue as in #1796, the headers don't have the right heights and therefore the input fields are hidden, however, after switching between 2 bootstrap tabs the headers render correctly.

I couldn't get this reproduced reliably in a plunkr, but it happens every time in my app.

[example screenshots](http://imgur.com/a/yiohY)

**Comment by shashankGopannagari** [comment]
I have also same problem can any one help me on this

**Comment by vhexedv** [comment]
Eu tive o mesmo problema no meu caso era que eu estou usando CellTemplate para adicionar uma coluna de ação fixa e trazendo dados dinamicamente.
Como eu sempre vou usar filtro, coloquei no meu css o seguinte.
.grid .ui - célula cabeçalho da grelha {
  height: 60px ;
}
Desta forma eu forço a altura ideal para que as colunas de header exibam meus campos de filtro.

**Comment by vhexedv** [comment]
I had the same problem in my case was that I am using CellTemplate to add a fixed action column and bringing data dynamically.
How will I always use filter, put on my css the following.

.grid .ui - grid cell header {
height: 60px ;
}

In this way I force the ideal height for the header columns display my filter fields .

**Comment by mportuga** [comment]
Without a plunker, I cannot fix this issue. As of now I am left to think this must be an issue with customizations applied on your side. Feel free to reopen if you find a way to reproduce it via plunker.
