### ISSUE TITLE
Filtering doesn't work when fields are object properties

### ISSUE THREAD

**Issue by esheffield-ivantage** [angular-ui/ui-grid#531]
Filtering doesn't seem to work when the data in the grid consists of nested objects. For example, suppose you have data that looks like this:

```
$scope.myData = [{fields: {name: "Moroni", age: 50}},
                 {fields: {name: "Tiancum", age: 43}},
                 ...];
```

You can configure the column definitions so that the data displays properly in the grid:

```
columnDefs:[
  {
    field: "fields['name']",
    displayName: "Name"
  },
  ...
]
```

... but any attempts at filtering with the search box will result in no items showing in the grid. Presumably this is because ng-grid filters strings, not objects. Is there a way to get filtering to work in such a case? Here's a Plunker demonstrating this example: http://plnkr.co/edit/l2J1S9

**Comment by shanimal** [comment]
fwiw, I got around this issue by adding the nested field values onto the object root instead of using dot syntax for field. something like this...

    $scope.invoices = _(data.content.orderList).map(function(v){
        v.adTitle = v.oDetails.adTitle;
        return v;
    })
    ....
    // set the field
    field: 'adTitle',

vs.

    $scope.invoices = data.content.orderList
    ....
    // set the field
    field: 'oDetails.adTitle',

**Comment by agriboss** [comment]
I have not tried what the others above have suggested as I do not want to modify the source.  Here is a workaround that gets around it... 

I believe the problem occurs here (nested data causes dot notation to be returned in "field"):
```

          if ( row.entity[field].match(matcher) ){
                 match = true;
          }

```

You can do something like this in your search function:

```
                var j = field.split(".");
                //j is now array of prop names to drill into data
                var rowEntity = row.entity;
                
                //descend into object using array of prop names
                angular.forEach(j, function(prop){
                    rowEntity = rowEntity[prop];
                }); `

                if ( rowEntity.match(matcher) ){
                     match = true;
                }

```
