### ISSUE TITLE
Fix (Stick) UI Grid column headers and horizontal scroll when grid's vertical scollbar is disabled

### ISSUE THREAD

**Issue by angular-git-user** [angular-ui/ui-grid#5310]
I have disabled UI Grid vertical scroll bar and have just page scroll bar with more than 200 records displayed at a time.
But when the page is scrolled the grid headers are not visible on the screen.
Also the horizontal scroll bar is present right at the bottom of the screen making it inconvenient as the user would have to scroll right till the bottom to access it making the grid column headers invisible.

**Comment by angular-git-user** [comment]
http://plnkr.co/edit/yjV6ytBNtu1R0KskqyCD?p=preview

**Comment by mportuga** [comment]
Not an issue that can be solved within ui-grid since you are disabling ui-grid scrolling.

**Comment by NitendraTripathi** [comment]
how to enable scrolling

**Comment by debovis** [comment]
@mportuga Deflecting answer and closing the issue leaves the question unanswered.
