### ISSUE TITLE
Scrolling on Tablets not working when a column is pinned right. 

### ISSUE THREAD

**Issue by siminaN** [angular-ui/ui-grid#5324]
Hi Guys, 

The problem is about tablets. Tested on Samsung Tab 2 and IPad Air 2. 

If you have a column pinned to the right, you can only scroll in that grid if you touch that pinned column. Also, when you manage to scroll you can see a delay between the pinned columns moving and the rest of the row.

This can be easy seen with the example from the pinning tutorial. 
http://ui-grid.info/docs/#/tutorial/203_pinning

Is there anything we can do to fix this? 
Thanks!

**Comment by laloutre87** [comment]
I confirm this bug, and it can also be reproduced using the ipad mode in chrome dev' tools.

**Comment by laloutre87** [comment]
Possible workaround : .ui-grid-viewport { overflow : auto } ,  puis styler les scrollbars ajoutées pour les rendre invisibles.

**Comment by Ruud-cb** [comment]
+1, couldn't really find where to put those classes, tried using the header template in an `ngclass` depending on the `col.colDef.pinnedRight` or left property. Didn't work.

**Comment by dlgski** [comment]
assuming you are all set with @laloutre87 's solution.  We cannot put overflow: auto into the product do to how IE handles scrollbars.  If you have a different solution that may work across all browsers and devices, please provide a plunker.  Thank you!

**Comment by laloutre87** [comment]
My "solution" is not acceptable ! It's a quick workaround.  You can't possibly close this bug just like that. What's wrong with leaving a ticket open until it's actually resolved ???

**Comment by jpadre** [comment]
Hi all,

I just tried @laloutre87 's workaround, and I can confirm it doesn't solve the issue completely
- Yes, it work on tablets
- However, on Chrome, you loose both the horizontal scrollbar and the vertical one is transparent for me (if I can manage to find it)
- In IE and Firefox, it causes two vertical scrollbars to appear, one for the body container and the other for the right pinned container

Try as I might, I couldn't get the CSS to work for all these browsers (and haven't tested safari), especially without loosing the horizontal scroll

Voting to reopen this issue

**Comment by boris-meerovich-sp** [comment]
same in 4.0.1...

**Comment by dlgski** [comment]
Have you tried the new custom scrolling feature?  http://ui-grid.info/docs/#/tutorial/407_custom_scrolling 

Just released in 4.0
