### ISSUE TITLE
Sorting is wrong when flatEntityAccess and sortCellFiltered are enabled

### ISSUE THREAD

**Issue by lebolo** [angular-ui/ui-grid#5326]
If `flatEntityAccess: true` and `sortCellFiltered: true` are set for a column definition, the grid doesn't sort.

In this case, [`rowSorter`](https://github.com/angular-ui/ui-grid/blob/v3.1.1/src/js/core/services/rowSorter.js#L450) uses `grid.getCellDisplayValue` instead of `grid.getCellValue` and the first cell value encountered gets cached*. Meaning all subsequent cell values get returned as the first cell value (so the grid ultimately fails to sort since it thinks all cell values are the same).

Here is a [plunkr](http://plnkr.co/edit/8LWQTs?p=preview) - try to sort the _gender_ column to see the problem.

I can disable `flatEntityAccess` as a workaround, but am not sure how to properly fix this. If anyone has some guidance, I can try creating a pull request.

*This happens because [`getCellDisplayValue`](https://github.com/angular-ui/ui-grid/blob/v3.1.1/src/js/core/factories/Grid.js#L1857) uses `$parse(row.entity[col.field] + custom_filter)`, which becomes `$parse("first_cell_value_encountered | some_filter")` when `flatEntityAccess` is enabled, instead of `$parse(row.getEntityQualifiedColField(col) + custom_filter)`, which becomes `$parse("entity['some_field'] | some_filter")`

**Comment by lebolo** [comment]
I originally thought this only happened when `cellFilter` was not set, but that's not the case. I edited the title and original issue.

**Comment by lebolo** [comment]
Obviously, this also affects situations where `flatEntityAccess` and `filterCellFiltered`are both enabled.

**Comment by jasonlikescats** [comment]
Here's a somewhat more direct [reproduction plunkr](http://plnkr.co/edit/TPoyO0ktcwFYfDoNlH7Z?p=preview) that just calls getCellDisplayValue directly. Click the button to trigger the error.
