### ISSUE TITLE
UI-Grid text does not retain formatting

### ISSUE THREAD

**Issue by nareshurs** [angular-ui/ui-grid#5327]
If I configure UI grid with columns which display strings, are loosing formatting.
Ex: Text from database comes with spaces in between words but when displayed in Grid looses the spaces. I know workaround of displaying with a class pre as celltemplate, however I dont want to give for all columns and all grids though out the application.

(Ignore my previous description which is no way related to UI grid .)

**Comment by stevenlius** [comment]
Please specify versions. 
I have tested with v3.1.1, and I didnt see that problem. 
http://plnkr.co/edit/z46CCLDNZhXg0axqkiEo?p=preview

**Comment by nareshurs** [comment]
Very sorry for the late reply. I am using 3.0.7. I still see problem in the plunker you have mentioned. 

I have added some spaces to first name . Still it is not working.
http://plnkr.co/edit/l72G2VzHtiSnyaUpxNLl?p=preview

We need a generic way to retain formatting while displaying data in grid instead of applying pre to every column

**Comment by BizH** [comment]
Also, leading and training spaces are deleted (when the user changes when editing a cell). So, "  abc" is changed to "abc" and "abc  " is changed to "abc". In some case, spaces need to be preserved (especially leading spaces).

**Comment by hemolack** [comment]
This can be worked around by adding an additional class to the cell template and specifying `white-space: pre` in the CSS for that class.
