### ISSUE TITLE
aggregationType sum with footerCellFilter 'time'

### ISSUE THREAD

**Issue by avihaym** [angular-ui/ui-grid#5329]
Hii ,
I have time column that his format is  : 00:00:00  and i try to make sum to all this column but i can`t figure out how.

plz help.

**Comment by billyaraujo** [comment]
Would be easier with  a plunker but maybe you can store time an integer 

type: 'number',

and then have a custom cellFilter for display purposes.

**Comment by avihaym** [comment]
Sound good , i will try it .
Thanks.
