### ISSUE TITLE
row selected style(.ui-grid-row-selected) is not working on Ipad

### ISSUE THREAD

**Issue by pshivareddy** [angular-ui/ui-grid#5330]
Hi,

I am loading students records in angular grid. when a student row is selected, multiple tasks are executed. But selected row UI style is disappearing even though i selected a row in iPad but it is working in desktop and laptop browser. Any help?

**Comment by dlgski** [comment]
Please re-submit as an issue with a plunker if this is still a problem.   I have selected a row on an iPad and am unable to reproduce as you have described here.
