### ISSUE TITLE
ui-grid does not adjust height when horizontal scroll bar is enabled

### ISSUE THREAD

**Issue by Yashkochar20** [angular-ui/ui-grid#5334]
As WHEN_NEEDED option is no longer supported for horizontal scrolling, 
A workaround for this is to set enableHorizontalScrollbar: 0 on gridOptions and then in stylesheet have the following code:

``` javascript
.ui-grid-viewport {
    overflow-x: auto !important;
}
```

This gives us scroll bar when needed on both windows and OSX platform.
But in windows when the scroll appears it overlaps the last row and hence last row contents gets clipped off.  
![capture](https://cloud.githubusercontent.com/assets/7841033/14658092/87a105c0-065f-11e6-8f16-306c373999a3.PNG)

Also check: https://github.com/angular-ui/ui-grid/issues/2635

Success Criteria: ui-grid should resize itself when the scroll bar appears with this workaround.

**Comment by mportuga** [comment]
WHEN_NEEDED option is back as part of version 4.4.2
