### ISSUE TITLE
how to give cell by cell Validation in Angular UI-Gird

### ISSUE THREAD

**Issue by himanshumalviya2016** [angular-ui/ui-grid#5335]
Hello guys,
      I am searching for some idea for#  annular grid cell by cell validation.
If i have some input fields which only require 300 characters and if it exceed from 300 character one Message should display for maximum characters.

@please suggest any idea or implementation which is exist or new can apply.

**Comment by billyaraujo** [comment]
You can use gridApi.edit.on.afterCellEdit:

```
gridApi.edit.on.afterCellEdit($scope,function(rowEntity, colDef, newValue, oldValue){
            $scope.msg.lastCellEdited = 'edited row id:' + rowEntity.id + ' Column:' + colDef.name + ' newValue:' + newValue + ' oldValue:' + oldValue ;
            $scope.$apply();
          });
```

http://plnkr.co/edit/HR75P0VUjtlA3OKZZ3aj?p=preview

But this will only validate after you press edit. To check during edit not sure.
