### ISSUE TITLE
Problem with toggle filtering

### ISSUE THREAD

**Issue by roscheld** [angular-ui/ui-grid#5347]
Hi,

First of all thanks for the great grid, but I'm having some issues with the toggle filtering feature. I have found some issues that relate to mine but they never gave a clear fix and for me it's still not working as it should. I added some screenshots where you can see when I press the toggle filter the fields appear but they aren't visible. I've already tried playing with CSS but I can't figure it out and I don't even know if it's possible to do. I hope someone can help me! I'm currently on version ui-grid - v3.1.0 - 2016-01-19.

Many thanks in advance! 

Screenshot before clicking toggle filter
![filternotvisible](https://cloud.githubusercontent.com/assets/7072451/14744614/c4da869c-08a7-11e6-9926-59145d097dc5.png)

Screenshot after clicking toggle filter, they are there but just not visible.
![filternotvisible_2](https://cloud.githubusercontent.com/assets/7072451/14744624/cef61d76-08a7-11e6-8e8d-1258eec5b699.png)

![filternotvisible_3](https://cloud.githubusercontent.com/assets/7072451/14744633/d6df1376-08a7-11e6-80bb-c95d25e69a19.png)

**Comment by mportuga** [comment]
I don't believe this issue still exists as the All features demo has a toggle filter button which is working as expected.
