### ISSUE TITLE
Multiple table selection problem?

### ISSUE THREAD

**Issue by htve** [angular-ui/ui-grid#5352]
I have a page with two tables on it,
html:

```
<input type="file" accept=".csv" custom-on-change="uploadFile" id="id1"/>
<div id="waybillsGrid" ui-grid="waybillsOptions" ui-grid-importer ui-grid-resize-columns></div>

<input type="file" accept=".csv" custom-on-change="uploadFile" id="id2" />
<div id="goodesGrid" ui-grid="goodesOptions" ui-grid-importer ui-grid-resize-columns></div>
```

app.js
`$scope.uploadFile = function (files) {
                if (files && files.length === 1) {
                    $scope.gridApi.importer.importFile(files[0]);
                }
            };`

When you click on the Id1 for data import, it will always be the data into the Id2 table. This need how to solve it?

**Comment by billyaraujo** [comment]
Do you have a $scope.gridApi for each grid?

Such as $scope.gridApi1, $scope.gridApi2.

**Comment by htve** [comment]
Hi，@billyaraujo
The first table is $scope.gridApi1? The second table is $scope.gridApi2?

**Comment by htve** [comment]
I need is: 
click on the ID=id1 button, import the CSV file into the ID=waybillsGrid grid;

click on the ID=id2 button, import the CSV file into the ID=goodesGrid grid;

**Comment by billyaraujo** [comment]
Depends. Just assign different api. When you do:

        onRegisterApi: function(gridApi) {

          $scope.gridApi1 = gridApi;

      }

**Comment by htve** [comment]
Thank you very much for your help, my problem has been solved.
