### ISSUE TITLE
On pagination the page textbox does not allows to delete its current number and set other option.

### ISSUE THREAD

**Issue by tecsined** [angular-ui/ui-grid#5355]
On pagination the page textbox does not allows users delete the current selected page number to set other page number. When a user uses the backspace  to delete the number it automatically default it to 1. Thus, users only have the option of selecting the whole number and start changing it. As side effect for this behavior when users are setting their number the control start resolving the pages results dynamically.

Solution proposal:   To have a setting that allows a users to delete selection and pagination does not seek for results with and empty page number. Also has an option to enable manual paging for instance user write a number and it does not seek data until the user hot enter or the control lose focus.

**Comment by vibhayadaw** [comment]
+1. I am also looking for the solution for same. Any clues by when this will be fixed.

**Comment by aravinthlr** [comment]
Friends, have you got any solution or suggestion on this?
