### ISSUE TITLE
Cancel event not firing when editing

### ISSUE THREAD

**Issue by andres-pipicello** [angular-ui/ui-grid#5357]
Hello

Following the tutorial for editable tables (http://ui-grid.info/docs/#/tutorial/201_editable), I have modified the example a little to test the PublicApi events. I have found that the cancel event is never fired, and the edit is always accepted, even when the Esc key is pressed. This happens also happens in the tutorial.
You can see this behaviour at http://plnkr.co/edit/Bdzoj0oeMy3n4sm4I8s0?p=preview

Regards

**Comment by billyaraujo** [comment]
@andres-pipicello 

Hi,

I tested your plunker and when I press the ESC key I get the cancelled message.

**Comment by andres-pipicello** [comment]
Originally I only tested the script on Chromium(50.0.2661.86) in two different machines. Instead of firing a cancel event, an after edit event gets fired, and the changes get accepted no matter what.

Now I tested it on Firefox and Chrome and it works fine, so it is seems to be a Chromium-only issue.

Sorry for the noise
