### ISSUE TITLE
When resized by double click, colResizable.on.columnSizeChanged passes deltaChange = 0 to the callback function

### ISSUE THREAD

**Issue by lyubenblagoev** [angular-ui/ui-grid#5362]
When column is resized by double clicking instead of drag & drop, colResizable.on.columnSizeChanged passes 0 to the deltaChange argument.

**Comment by mobichel** [comment]
It's a bug because xDiff variable passed to callback is always 0. 
There is code:
`maxWidth = width;'
'xDiff = maxWidth - width;`
