### ISSUE TITLE
Screen show behinde the ui-grid. headercell button

### ISSUE THREAD

**Issue by lecoleco** [angular-ui/ui-grid#5366]
Hi,

I put a button on headercell. 
The button show ok, but when i click on button, the screen show behinde the grid.

http://plnkr.co/edit/1ZRXhI60RWJHUd9ZXzSZ?p=preview

Thanks

**Comment by billyaraujo** [comment]
Mine is showing in front. Which browser?

**Comment by lecoleco** [comment]
Chrome
