### ISSUE TITLE
rowIdentity() function if returns non - unique value, first row is repeated  n -times where n is the total number of records in data object

### ISSUE THREAD

**Issue by brijeshguptakol** [angular-ui/ui-grid#5368]
If we have a rowIdentity function defined for a grid, and the value returned does not happen to be unique across all rows, then on changing (adding another record using push()) the data object of the grid keeps replicating the first record. It seems it is trying to fetch the records while iterating using the RowId returned by the rowIdentity() while is same for the all the rows in this case.

I think, grid should not depend on the uniqueness of the row for populating the records.

Please check if this is bug or it is intentionally done this way?

**Comment by PaulL1** [comment]
This isn't a bug. The rowidentity function, if provided, must give unique values to each row. When given this function ui-grid uses it to find the rows.

Sent from my iPhone

On 29 Apr 2016, at 11:26 PM, brijeshguptakol <notifications@github.com<mailto:notifications@github.com>> wrote:


If we have a rowIdentity function defined for a grid, and the value returned does not happen to be unique across all rows, then on changing (adding another record using push()) the data object of the grid keeps replicating the first record. It seems it is trying to fetch the records while iterating using the RowId returned by the rowIdentity() while is same for the all the rows in this case.

I think, grid should not depend on the uniqueness of the row for populating the records.

Please check if this is bug or it is intentionally done this way?

-
