### ISSUE TITLE
Horizontal scroll not working

### ISSUE THREAD

**Issue by jaymoore** [angular-ui/ui-grid#5376]
For large sets of data that are wider than the screen width, ui grid is not scrolling automatically?

http://plnkr.co/edit/WcdQyUNm4UNxjdyX6UDh?p=preview

**Comment by mportuga** [comment]
Cannot reproduce

**Comment by luigiruocco** [comment]
The problem is still present in version 4.8.3 and occurs only on Microsoft Windows operating system on all browsers.
