### ISSUE TITLE
Exportfieldcallback dont´export date as I´ve formated... 

### ISSUE THREAD

**Issue by xxnull** [angular-ui/ui-grid#5377]
My date have this format : 'YYYY-MM-DD'
when I export it as csv in the excel file i see the date as 'DD/MM/YYYY'

why the format change on export?

exporterFieldCallback: function ( grid, row, col, value ){
            if(_.includes(['CreatedDate'], col.name)){
                return moment.unix(value).format("YYYY-MM-DD");
            }
            return value;
    }

**Comment by angular-git-user** [comment]
it should have... try to print it in the console `console.log(moment.unix(value).format("YYYY-MM-DD"))` just to make sure if is fine.. I too had used moment api to translate my date for export and it worked

**Comment by gine** [comment]
I have this issue too.  

How i set che column:

`{ field: 'mixedDate', displayName: "Long Date", cellFilter: 'date:\'dd/MM/yy\'', filterCellFiltered:true}`

How i see the date on the table:

`25/09/2016`

How i see date on csv/pdf:

`"2016-09-25T13:53:45.819Z"`

To be more precise any cellFilter doesn't work, how you can see with gender column.

Here the example with [plunkr](http://plnkr.co/edit/aTYXYd6puFZoVQEcSZ8w?p=preview)

You must click on gridMenù then click on export.
