### ISSUE TITLE
Wrong grid height when setting less than "10" in paginationPageSize

### ISSUE THREAD

**Issue by NoelBroda** [angular-ui/ui-grid#5382]
Step to reproduce it:
- Open `misc/demo/grid-accessiblility.html`
- Change those two values: `paginationPageSizes: [5]`, `paginationPageSize: 5` in `gridOptions`
- Go to your browser and see the new `look and feel`. You should see something like the screenshot (tested in Firefox and Chrome over a Mac)

<img width="1314" alt="screen shot 2016-05-05 at 4 26 51 pm" src="https://cloud.githubusercontent.com/assets/16190546/15054563/80ee6138-12de-11e6-8b18-d5a6b0708586.png">

**Comment by angular-git-user** [comment]
They havent designed the grid to change the grid size dynamically, you may have to apply youre own logic like
`height = (rowLength*30)+80;`
`$('#grid1').css('height', height + 'px');`

where `rowLength` is number of visible rows and `80` is approx calculated height with `filters + headers`
