### ISSUE TITLE
how to hide the "Clear all filters"

### ISSUE THREAD

**Issue by jackyhaoli** [angular-ui/ui-grid#5384]
Hi guys, 

I want to customise the gridMenu, how to hide the "Clear all filters"?

**Comment by angular-git-user** [comment]
you cant... only export features can be hidden... if you still want to then may be you need to use some jquery around.. hide the div or something of that sort

**Comment by srinivasyl** [comment]
make enableFiltering option to false
```
$scope.gridOptions = {
        showGridFooter: true,
        showColumnFooter: true,
        enableFiltering: false,
        onRegisterApi: function (gridApi) {
          $scope.gridApi = gridApi;
        }
      };
```

**Comment by srinivasyl** [comment]
make enableFiltering option to false

```
$scope.gridOptions = {
        showGridFooter: true,
        showColumnFooter: true,
        enableFiltering: false,
        onRegisterApi: function (gridApi) {
          $scope.gridApi = gridApi;
        }
      };
```

**Comment by drai05** [comment]
You can use the following code:

![image](https://user-images.githubusercontent.com/18260749/50902815-f2c5f480-1441-11e9-8bd4-e49d019fe8a0.png)

here on click of menu button "$(".ui-grid-menu-button")", i am hidding the all options after 2nd options. you can change the code at line $("button.ui-grid-menu-item:gt(1)").hide(); to hide option which you want.
