### ISSUE TITLE
I use angular-translate to translate the ui-grid but sometimes it doesn't work

### ISSUE THREAD

**Issue by qichangjun** [angular-ui/ui-grid#5391]
thi is my code 
`angular.module "myApp"
.factory 'hsTranslateService',
['$translate',
   ($translate) ->
     translate:(key) ->
       if key
        console.log 'trannn',$translate.instant(key)
        return $translate.instant(key)
      else
        return key
]`

`
          name: 'object_name'
          displayName: hsTranslateService.translate 'OPS_PURCHASE_UIGRID_TITLE_OBJECT_NAME'
          minWidth:300
          cellTemplate:'webComponents/common/hsTemplates/doc/list-docContent.html'
          editableCellTemplate:hsTpl.hsEditableCellTemplate`

somtimes after I refresh my web it doesn't translate the header like this 

![image](https://cloud.githubusercontent.com/assets/15797310/15103743/b3d4c50a-15e1-11e6-98ba-0209d0b4a102.png)

**Comment by loopmocker** [comment]
how did you fix this problem?
