### ISSUE TITLE
Enahancement: provide base operators (=, !=, <=, <, etc.) for filtering data by underlying data type.

### ISSUE THREAD

**Issue by kentonbmax** [angular-ui/ui-grid#5398]
Enable in similar fashion to selection and paging. Could be called advanced filtering. 
- Ability to filter by not equal to string
- Ability to filter int by > or < or !=, or <=, or >= n

option extra credit
- ability to filter by array (n, n1, n^n), not in {n, n1, n^n}

**Comment by angular-git-user** [comment]
well you can still write you're own filter template and filtering logic... or dynamically apply filters as per user selection
