### ISSUE TITLE
Feature request: Ability to plug-in almost anything inside the ui-grid expanded row. How much feasible it will be?

### ISSUE THREAD

**Issue by saurabh-sp-tripathi** [angular-ui/ui-grid#5400]
We have this requirement where the grid row may be expanded and in that expanded row we need ability to plug in almost anything. 

How much feasible this could be with ui-grid? Me and my team will be very much happy to contribute if possible.

**Comment by angular-git-user** [comment]
Almost anything means what exactly? isn't it possible now? you can nest in any json data...
