### ISSUE TITLE
ui-grid docs are not working too many times

### ISSUE THREAD

**Issue by piyush-dholariya** [angular-ui/ui-grid#5410]
Since many days in between docs are not working, it shows site can not be reached. is your domain expired?

**Comment by hohwille** [comment]
ui-grid.info is entirely gone :(

**Comment by prashanth000mj** [comment]
we can follow this http://angular-ui.github.io/ui-grid/

**Comment by lolobosse** [comment]
@prashanth000mj It is only for basic stuff, I'm missing the advanced tutorials for instance... But cool though 😄

**Comment by yorikcv** [comment]
Hello. you can download source of website here https://github.com/angular-ui/ui-grid.info/tree/gh-pages
and open with grunt or gulp (create serve localhost)

**Comment by pccjamie** [comment]
Any news on the doc site?

**Comment by piyush-dholariya** [comment]
yes  site is up now, but can anyone give steps how to setup locally ui site. they have given some steps in github but they are not useful for me.
