### ISSUE TITLE
Feature to Limit Multiselect in Ui Grid

### ISSUE THREAD

**Issue by sagarwasule** [angular-ui/ui-grid#5419]
In UI Grid we have a feature where rows can be multi selected. There should be a feature where developer can specify how many rows can be selected at max in UI Grid

**Comment by shamoh19** [comment]
+1

**Comment by sagarwasule** [comment]
@shamoh19 I have achived this by maintaining a scope where I have count of rows selected, in case the max desired count  is achieved then no further selection will happen
