### ISSUE TITLE
UI-Select: Clear option leaves last activeIndex

### ISSUE THREAD

**Issue by joaoferreira89** [angular-ui/ui-grid#5425]
Hi,
I'm using the ui-select 0.17.1 plugin, and i have it configured with allowClear = true.

Steps to reproduce issue:
- when the select opens, it shows the first element selected (index 0) by default;
- open the ui-select and select the third option (index 2)
- close the ui-select
- click on the clear icon to clear the selection
- open the ui-select again: the active option is still the third option.

This is caused because the clear method does not set the default variable at: 'activeIndex'.
It is a quick fix, just add:
 ctrl.activeIndex = 0;
at the controller clear() function.

Best regards,
João Ferreira

**Comment by mportuga** [comment]
This is ui-grid, not ui-select
