### ISSUE TITLE
Special characters in displayName not working properly

### ISSUE THREAD

**Issue by dereklin** [angular-ui/ui-grid#5434]
Hi,

I want to put a delta special character in my headers.  When I use 

```
&Delta;
```

It shows the code.

When I use the symbol, the export doesn't look right.

Here is the plunker.

http://plnkr.co/edit/YmjOKvByOAT3KnYKu4am?p=preview

How to do this properly?

**Comment by bjaraujo** [comment]
You probably have provide your own headerTemplate. Not sure.
