### ISSUE TITLE
group by string column results in duplicate groups with duplicate rows

### ISSUE THREAD

**Issue by arnorhaux** [angular-ui/ui-grid#5437]
Hi

I have reviewed the guidelines and created a Plunkr to replicate this issue

When I have array in json data, that holds 21 rows with 3 diffrent types of "AssetTypeName" (column) which is the column that the grid is groupped by, it will result in a grid that shows the same group multiple times. The only group that appears one time is a group that has only one row in that particular AssetTypeName category.

For example AssetTypeName = "Domestic bonds" should have 5 rows but the grid shows the groups three times which all contains the same 2 first rows in that category.

When I expand some group-row, all the duplicated groups will expand.

http://plnkr.co/edit/fBqNq33XmQTYS4Ga9wrW?p=preview

Sincerly - arnorhaux

**Comment by arnorhaux** [comment]
well solved it myself

apperantly if you skip the sort definition for the groupped column, it will result in this strange behavior.

`{
                      field: 'AssetTypeName', name: 'AssetTypeName', visible: true,
                      grouping: { groupPriority: 0 },
                      sort: { priority: 0, direction: 'desc' },  <-- Don't skip this although sorting is not required
                      width: '10%',
                      enableColumnMenu: false,
                      cellTemplate: '<div><div ng-if="!col.grouping || col.grouping.groupPriority === undefined || col.grouping.groupPriority === null || ( row.groupHeader && col.grouping.groupPriority === row.treeLevel )" class="ui-grid-cell-contents" title="TOOLTIP">{{COL_FIELD CUSTOM_FILTERS}}</div></div>'
                  }`

Is this a bug?

**Comment by arunkumarsp** [comment]
This worked !!! thanks :+1:

**Comment by thiagodebona** [comment]
Same problem here, what do i have to solve it?

**Comment by thiagodebona** [comment]
I found the real solution [HERE....](https://github.com/angular-ui/ui-grid/issues/5270?_pjax=%23js-repo-pjax-container)

**Comment by cyrilchapon** [comment]
For anyone wondering, it seems that messing with sort priorities creates same issue.

I found that :

- Every group-aware collumns must have same sort priority
- Every additional collumn can mess with priorities
