### ISSUE TITLE
Vertical scrollbar when using height 100% on grid

### ISSUE THREAD

**Issue by ValYouW** [angular-ui/ui-grid#5442]
Hi,

I am trying to let the grid take 100% height of its parent by setting its dev (and all parent elements up to `html`) to have `height: 100%`.
Doing so indeed makes the grid take the entire screen, BUT with a scrollbar on the page, I can solve this if I disable the grid border (`border: none` on the grid's div).
Here is an example in [codepen](http://codepen.io/ValYouW/pen/NrKRQp)
Any ideas? should `getViewportHeight` adjust for the grid's border?

![uigridborderscroll](https://cloud.githubusercontent.com/assets/4539636/15632761/91cd3820-25a4-11e6-93d2-958ff3a7f2b1.png)

![uigridnobordernoscroll](https://cloud.githubusercontent.com/assets/4539636/15632762/963b442e-25a4-11e6-92d5-af981ec01c1f.png)

**Comment by nkoterba** [comment]
Somewhat related question.  We are using `flexbox` with ui-grid and in some cases, it appears the vertical scrollbar is creating a horizontal scrollbar unnecessarily but b/c elements are being "pushed" when the vertical scrollbar appears.

Where in the codebase would be the best place to start looking at how to "handle" when scrollbars appear?

**Comment by mportuga** [comment]
enableHorizontalScrollbar
http://ui-grid.info/docs/#!/api/ui.grid.class:GridOptions
