### ISSUE TITLE
Sorting doesn't work correctly on Chrome when the grid uses grouping on a column with type 'number'

### ISSUE THREAD

**Issue by jabas06** [angular-ui/ui-grid#5453]
Hi,

I'm retrieving an integer column from an ajax request, and I want to use 'number' sorting on that column, so I define the column explicitly as 'number' type. The sorting works until I add grouping on the same column. The issue is only present on Chrome. IE has no problem.

I provide a plnkr to show the issue.
http://plnkr.co/edit/E12WguUoTmWvlJ1kA4db?p=preview

IE - working
![image](https://cloud.githubusercontent.com/assets/3453385/15797629/b071c766-29e4-11e6-84d0-0c83e240614e.png)

Chrome - not working

![image](https://cloud.githubusercontent.com/assets/3453385/15797641/f4140614-29e4-11e6-93bc-495dcb0811f1.png)

**Comment by nickxbs** [comment]
The grid tries to sort the render value (string) with the sortNumber alghoritm

**Comment by billyaraujo** [comment]
very strange because sorting seems to affected by the grouping.

**Comment by nickxbs** [comment]
Yes 
https://github.com/angular-ui/ui-grid/issues/4778
