### ISSUE TITLE
setCurrentLang not working

### ISSUE THREAD

**Issue by patrickrioux** [angular-ui/ui-grid#5457]
Hi,

I'm using version 3.1.1

Not clear to me if this is an issue or not. I'm unable to find any solution.
I'm calling  i18nService.setCurrentLang('fr') to switch the language. 
When calling getCurrentLang() it return the 'fr' code as expect. 

The problem is none of the grid menu dropdrop down, pagination are translated. Looking into ui-grid code, I noticed that html is integrated to $cachetemplate. I wonder if this could not be the problem?

**Comment by ghiscoding** [comment]
I also have the same problem and I search through the core code and found out that it won't apply the translation unless you do a `$state.reload()` (UI Router) or `$route.reload()` (ngRouter) to see the translations applied. You can try it manually to, just change route and come back to your original page, you will see the translation applied (at least I do see it on my side).

I was looking in the code thinking that it was maybe a timing issue but it's not that at all. To see the translations applied, you really need to recreate the grid completely again (hence calling a `$state.reload()` does work). Calling a state reload is really annoying though, since we need to make another call to the backend for data refresh as well :(

Not sure if there's a way to recreate the grid and gridOptions without leaving the controller or calling backend (or state reload)?

**Comment by patrickrioux** [comment]
Unfortunatly it doesn't fix my issue. I doudt that ui-grid is fully tested with other languages?

**Comment by patrickrioux** [comment]
After investigating the issue in the ui-grid.js, I have resolved the issue (I hope this can be apply officially soon).

`var localeDirective = function (i18nService, i18nConstants) {
    return {
      compile: function () {
        return {
          pre: function ($scope, $elm, $attrs) {
            var alias = i18nConstants.LOCALE_DIRECTIVE_ALIAS;
            // check for watchable property
            var lang = $scope.$eval($attrs[alias]);
            if (lang) {
              $scope.$watch($attrs[alias], function () {
                i18nService.setCurrentLang(lang);
              });
            } else if ($attrs.$$observers) {
              $attrs.$observe(alias, function () {
                //i18nService.setCurrentLang($attrs[alias] || i18nConstants.DEFAULT_LANG);
				i18nService.setCurrentLang(i18nService.getCurrentLang() || i18nConstants.DEFAULT_LANG);  // PRIOUX
              });
            }
          }
        };
      }
    };
  };`

**Comment by ghiscoding** [comment]
Did you modify the `ui-grid.js` core module for that to work? Your code is quite hard to read, have you tried to put your code inside a `javascript` markdown? You can see the `javascript` markdown [here](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting) . Also, if you could tell the line number, that would be easier to find.

I'm very interested to use your code if it means that I don't need to refresh my page to get the translation applied.

**Comment by patrickrioux** [comment]
Sorry for the javascript code, should be ok now.

Yes I have modified the ui-grid.js and used the overwritten version in my application as a work around.
It is not the best but until this is fix in the core code this is the only option I have found.

I don't have the line number but you should not have any trouble finding it.
Basically, I changed the first argument...
Instead of: //i18nService.setCurrentLang($attrs[alias]...
Replaced by: i18nService.setCurrentLang(i18nService.getCurrentLang()...

Not sure what was the intention of using $attrs[alias]. This might need to be fixed differently but my changes fixes the behavior and all the grid translations are now good (grid menu, column drop down and paging).

**Comment by ghiscoding** [comment]
Is that fix suppose to apply the new language on the header menu of each column? I tried it and this line doesn't seem to get triggered in my case. 

On my side, I have a `watch` for a language change and I apply the `setCurrentLang()`:
```javascript
$scope.$on("LanguageChange", function (events, languageKey) {
    i18nService.setCurrentLang(languageKey);
  });
```

Then I did modify the `ui-grid.js` core file and I also added some `console.log()` but it doesn't go inside

```javascript
var localeDirective = function (i18nService, i18nConstants) {
    return {
      compile: function () {
        return {
          pre: function ($scope, $elm, $attrs) {
            var alias = i18nConstants.LOCALE_DIRECTIVE_ALIAS;
            // check for watchable property
            var lang = $scope.$eval($attrs[alias]);
            if (lang) {
              $scope.$watch($attrs[alias], function () {
                console.log(lang); // <-- console log
                i18nService.setCurrentLang(lang);
              });
            } else if ($attrs.$$observers) {
              $attrs.$observe(alias, function () {
                console.log(i18nService.getCurrentLang()); // <-- console log
                //i18nService.setCurrentLang($attrs[alias] || i18nConstants.DEFAULT_LANG);
                i18nService.setCurrentLang(i18nService.getCurrentLang() || i18nConstants.DEFAULT_LANG);
              });
            }
          }
        };
      }
    };
  };
```

Would you mind sharing your code for the language change? You said that you aren't reloading the page, is that correct?

**Comment by patrickrioux** [comment]
Correct, I'm not reloading the page. I'm using ui-grid - v3.2.1 - 2016-06-28
This is maybe why this is not called in your case?

The language in my application is set in a LanguageService but it does this...

```javascript
var setGridLanguage = function () {
          var languageObj = LocalCacheService.get(APP_CONSTANTS.localCacheKey.language);
          var preferredLanguage = languageObj ? languageObj : APP_CONSTANTS.language;
          i18nService.setCurrentLang(preferredLanguage.split('-')[0]);
        };
```
The current language is set in the localStorage and obtain from a LocalCacheService (this is to make sure to keep the language on browser refresh F5). If not found in localStorage, I'm using a default from APP_CONTANTS (en-US). Then ultimatly, I'm just calling the i18nService.setCurrentLang()
Need to alter the language for the grid to end up with just en, fr, es, etc (to match supported language codes).

This needs to occurs before your grid instance gets created otherwise you might end up with 'en'.

Hope that help.

**Comment by ghiscoding** [comment]
So I found out why it wasn't getting triggered. Your datagrid is probably wrapped with a `<div ui-i18n="{{vm.lang}}">` to get the line that you changed triggered. But even though, it still doesn't make it to work on my side. Any special directives that you use apart from the `ui-i18n` wrapper? 

Side note.
Have you tried with the GridMenu as well? I mean do you get the new translation in both the Header menus and the GridMenu?

**Comment by ghostfreeman** [comment]
I'm seeing a similar issue with ui-grid and Ionic, where it will occasionally pass a malformed i18n string to an overloaded instance of `i18nService.getCurrentLang()`. I'm not entirely clear on why this only occurs within Ionic projects, but the addition of a preceding white space throws all the strings in memory off. I was able to correct it by trimming the contents inside `localeDirective` before assigning the results to any `i18Service.setCurrentLang` method call. I will make a pull request for this fix later today.

**Comment by ghostfreeman** [comment]
I haven't had the time to create a pull request, so I pulled a patch of my changes and attached it. I hope this helps out anyone encountering this issue.

`diff --git a/www/app/lib/angular-ui-grid/ui-grid.js b/www/app/lib/angular-ui-grid/ui-grid.js
index de0177b..d054b68 100644
--- a/www/app/lib/angular-ui-grid/ui-grid.js
+++ b/www/app/lib/angular-ui-grid/ui-grid.js
@@ -14705,7 +14705,7 @@ module.filter('px', function() {
          * @description returns the current language used in the application
          */
         getCurrentLang: function () {
-          var lang = langCache.getCurrentLang();
+          var lang = langCache.getCurrentLang(); //trim()
           if (!lang) {
             lang = i18nConstants.DEFAULT_LANG;
             langCache.setCurrent(lang);
@@ -14733,7 +14733,9 @@ module.filter('px', function() {
               });
             } else if ($attrs.$$observers) {
               $attrs.$observe(alias, function () {
-                i18nService.setCurrentLang($attrs[alias] || i18nConstants.DEFAULT_LANG);
+		var setLang = $attrs[alias] || i18nConstants.DEFAULT_LANG;
+		setLang = setLang.trim();
+                i18nService.setCurrentLang(setLang);
               });
             }
           }`

**Comment by ghiscoding** [comment]
hello @ghostfreeman would it be possible to just put the end result code or use ` ```diff ` to wrap the code you've put, the `diff` will also highlight like regular git commit.

**Comment by ghostfreeman** [comment]
Sure. Hope this helps.

**Comment by ghiscoding** [comment]
ah yes much better thanks :D
