### ISSUE TITLE
Headers not displaying in ui-grid when I am using html templates

### ISSUE THREAD

**Issue by kiran11990** [angular-ui/ui-grid#5458]
Headers are not displaying when I am using the html templates for columnDefs

![headers not displaying](https://cloud.githubusercontent.com/assets/18546424/15854372/17822da8-2cc7-11e6-9bc2-8b6a8bc5dc22.png)

**Comment by jgunderson-IAS** [comment]
+1 Experiencing the same issue. Nothing fancy just using URL string to fetch the header cell templates. Verified that the template is loaded in chrome dev tools network tab.

**Comment by ishoukry** [comment]
Same here. Though headers are then shown fine if ui-grid-callnav is added (but adding cellnav causes other issues)
