### ISSUE TITLE
Height is calculated incorrectly with footers and pinned columns and editing cells...

### ISSUE THREAD

**Issue by cleon26** [angular-ui/ui-grid#5459]
Take a look at this plunker:
http://plnkr.co/edit/i8GRAFEOJoQdhSHNMKPp?p=preview

Try these steps (ensure your browse is about wide enough that the grid has a horizontal scrollbar)
1. Pick a cell and put it into edit mode, for example the "aaaaa" cell.
2. Notice that when you entered edit mode, the input text was highlighted.
3. Using your mouse click in the input to remove the highlighting and place your cursor somewhere in the text.  For example, imagine you were about to change the text to "aaaXaaa".

Notice what happened when you did that?

When the input selection was cleared, the grid scrollbars dissappear, and the column footers shift around by exactly the height of the scrollbar.  Once you enter this state, you can continually edit and focus cells and the footers jumps all over the place.

![gridbug](https://cloud.githubusercontent.com/assets/7850944/15871314/e27c86d0-2cc1-11e6-9863-d47e580aa8d6.png)

**Comment by bjaraujo** [comment]
seems like a bug to me.

**Comment by benripley** [comment]
I am seeing this as well.
