### ISSUE TITLE
Column resize after programatic changes to columnDefs results in an empty grid if columnDefs are changed again

### ISSUE THREAD

**Issue by bbradbury** [angular-ui/ui-grid#546]
Go here: http://embed.plnkr.co/99GO3k/preview

Working case:
1. Choose Grid 1 -> Display (note data)
2. Choose Grid 2 -> Display (note data; # of cols has changed)

Broken case:
1. Choose Grid 1 -> Display (note grid data)
    \* **This time, adjust the width of a column**
2. Choose Grid 2 -> Display
    \* **!!Grid disappears!!**

Chrome 27.0.1453.93 / OS X

**Comment by sugir93** [comment]
hi am using ui-grid, but the colum data are over laping.

how to show all the data without hiding the data.
