### ISSUE TITLE
Disabling enableFiltering on column dynamically still filters

### ISSUE THREAD

**Issue by Atmos206** [angular-ui/ui-grid#5465]
After changing a columns **enableFiltering** property from **TRUE** to **FALSE** (**GridColumn** object, as well as  it's **columnDef**), the column is still included in filtering that occurs in the **rowSearcher.search** method.

 It seems that, even if a filter object property exist or filters object array exists, the column should not be considered in the filtering that occurs in the search method if it has **enableFiltering** set to false.

**Comment by mportuga** [comment]
Could you clarify?
