### ISSUE TITLE
110 grid in modal - column name overlapping with ordering arrow

### ISSUE THREAD

**Issue by rlrosa** [angular-ui/ui-grid#5470]
hi, i'm having a small problem with the tutorial: the 3rd column name overlaps the ordering arrow.

plunkr (copied from tutorial): http://plnkr.co/edit/cN5SaAYJKKYzleNdagCh

not sure what's going on, but i guess tutorial should work nicely.

happens on both chrome (Version 50.0.2661.102 (64-bit)) and firefox (46.0.1). i'm on ubuntu 14.04 16 bits.

tips? thanks!
salú

screenshot:
![overlap](https://cloud.githubusercontent.com/assets/889811/16031025/440f4c38-31cd-11e6-820a-752fbc65f332.png)

**Comment by bjaraujo** [comment]
Because you have a fixed width on the grid. You might need to fix the width of the container instead.

http://plnkr.co/edit/cN5SaAYJKKYzleNdagCh?p=preview

**Comment by rlrosa** [comment]
@bjaraujo i'm no expert here, but i don't think that's the issue (or i don't understand it)

i think the div holding the column menu button overlaps the one holding the header text, they don't seem to care about each other.
that, combined with ui-grid.css:174 setting an extra margin for the last column:

    .ui-grid-column-menu-button-last-col {
       margin-right: 25px;
    }

which i believe is for the grids that have a dropdown button on the upper right corner, makes things overlap.
this is not my code, i'm reporting this on the examples from the documentation. i attached a screenshot, the documentation link is:

http://ui-grid.info/docs/#/tutorial/110_grid_in_modal
