### ISSUE TITLE
headerFilter not working

### ISSUE THREAD

**Issue by dereklin** [angular-ui/ui-grid#5472]
I was looking a way to format the header with an angular filter and found headerFilter mentioned here:
https://github.com/angular-ui/ui-grid/issues/2526

So I have a headerFilter here https://plnkr.co/edit/koqpTblLxNrWYD9dgddB?p=preview

But it's not working. I expect to see the column header Number changed to TEST.

**Comment by Atmos206** [comment]
The only mention of **headerFilter** in the API documentation is **exporterHeaderFilter** and **importerHeaderFilter**. Searching the latest code base (3.1.1) **headerFilter** is never referenced. Perhaps it existed in an earlier version.

Another route you could take is using **$filter** for the **displayName** property, referencing your custom filter. I've modified your plnkr to show this:

https://plnkr.co/edit/trAdyI6T8UIkDgZPJDdi?p=preview

**Comment by dereklin** [comment]
@Atmos206 Thanks!  It's working as expected: https://plnkr.co/edit/koqpTblLxNrWYD9dgddB?p=preview

**Comment by Atmos206** [comment]
@derklin Awesome! You can close this issue now =)
