### ISSUE TITLE
grid doesn't refresh

### ISSUE THREAD

**Issue by antonyboom** [angular-ui/ui-grid#5484]
After mutiple searches on stackoveflow and here, I didn't find solution, and it looks like issue for me. This is topic on [stackoverflow](http://stackoverflow.com/questions/37931695/refresh-angular-ui-grid)

I believe that I've tried every way defined in API  but my grid still doesn't want refresh.

Nothing of this:

```
$scope.gridApi.core.notifyDataChange(uiGridConstants.dataChange.OPTIONS);
$scope.gridApi.core.notifyDataChange( uiGridConstants.dataChange.ALL);
$scope.gridApi.core.notifyDataChange(uiGridConstants.dataChange.EDIT);
$scope.gridApi.core.queueGridRefresh();
$scope.gridApi.core.refresh();
$scope.gridApi.grid.refreshCanvas();
$scope.gridApi.grid.refreshRows();
```

can't impact on grid

**Comment by conan-z** [comment]
Your link leads to a 404 page.
