### ISSUE TITLE
angular.js:13708 Error: [$parse:syntax] Syntax Error: Token 'en' is an unexpected token at column 4 of the expression [ru en] starting at [en].

### ISSUE THREAD

**Issue by cybermerlin** [angular-ui/ui-grid#5487]
write in template
```html
<div class="grid" ui-i18n="ru" ui-grid="gridOptions"
```
after render
```html
<div class="grid" ui-i18n="ru en" ui-grid="gridOptions"
```
check it out
```
 ui-i18n="ru en"
```

**Comment by buhichan** [comment]
+1.
uiI18n directive is so broken.

**Comment by cybermerlin** [comment]
https://github.com/cybermerlin/ui-grid/tree/bugfix/i18n

**Comment by Andyvec** [comment]
Hi,
In 4.0.2 is still broken. I can reproduce cybermerlin issue.
But I could change the language with the i18nService as http://ui-grid.info/docs/#/tutorial/104_i18n.

**Comment by cybermerlin** [comment]
fix based into
https://github.com/cybermerlin/ui-grid/tree/develop

**Comment by najafsen** [comment]
4.0.10 is still broken.
