### ISSUE TITLE
UI-grid grouping Pagination Issue

### ISSUE THREAD

**Issue by Mohana-Lakshmi** [angular-ui/ui-grid#5489]
- [ true] This is a bug report, not a question on how to use the grid.  
I have grid with grouping columns and it shows the group header row. When i added pagination , it is counting number of visible rows along with group header row. 

Suppose my data is having is 4 items  in one page. Pagination is displaying 5 items in one page because it is including group header row as well. please let us know the solution for this.

**Comment by sivaswamy** [comment]
I'm also facing the same issue, group headers row  are also  included in Pagination count.

Any update on this?

**Comment by SumeetKhandre** [comment]
I am also facing the same issue. I do not want to count the grouping header. 

Please can somebody help to find solution on this.

**Comment by Mohana-Lakshmi** [comment]
@sivaswamy - Here is the sample plunker - which has ui-grouping and pagination . http://plnkr.co/edit/myDUiu7cdrGopQgn7t2p?p=preview

**Comment by Mohana-Lakshmi** [comment]
@SumeetKhandre : please refer to this plunker , there is solution for it. 
http://plnkr.co/edit/myDUiu7cdrGopQgn7t2p?p=preview
