### ISSUE TITLE
angular ui grid grouping won´t work when groupPriority is set

### ISSUE THREAD

**Issue by theremin** [angular-ui/ui-grid#5495]
i have create a little plunker example to demonstrate the issue.
when i use the ui grid with enableGrouping = true and add a groupingPriority to the column the groups are distributed in more items on the grid. By opening one group all other groups with the same name opens too.

not working when activate this columns:

```
    this.bugColumns = [
    { 
      'field': 'device_name',
      'enableGrouping': true,
      'grouping': {
        'groupPriority': 1
      }
    },
    { 
      'field': 'device_type_name', 
      'enableGrouping': true,
      'grouping': {
        'groupPriority': 0
      }
    }
   ];
```

working with this ..:

```
this.columns = [
    { 
      'field': 'device_name',
      'enableGrouping': true
    },
    { 
      'field': 'device_type_name', 
      'enableGrouping': true
    }
  ];
```

http://plnkr.co/edit/3acARmRVoX27HCd9PtQx?p=info

Activating the example with 'bugColumns' demonstrates that there are same groupenames repeated, and clicking on each of them not one group will be open but all groups will be open.

**Comment by robshep** [comment]
I've just found this behaviour too.  

If you manually ungroup via the column menu, then group via the column menu, it groups fine. 

Have you found a fix/workaround?

**Comment by theremin** [comment]
not at all. we have deactivate the feature for the moment.

**Comment by robshep** [comment]
I can confirm the error and have a workaround for now. 

During the column construction phase, I determine if I want to group a column.  
(In my case I only have one column that I care about grouping, so I just use the name directly)

Then do the following....

```
theGrid.core.notifyDataChange(uiGridConstants.dataChange.ALL);

if(_group){
	$timeout(function(){
		theGrid.grouping.clearGrouping();
		theGrid.grouping.groupColumn('Member Type')
	},500)
}
```

The 500ms may be a little conservative, ( or even unnecessary if there is a better way) but it works good enough for me at present.

I can't work out how it is failing.

**Comment by Nisk** [comment]
I have the same issue. Three rows that should be grouped just appear individually - and their "aggregated" (in quotes because aggregation is not happening really) values are scrambled up - the values from row No3 appear in row No1 & row No2 etc.

Bump.

**Comment by MatejQ** [comment]
+1
it's currently not possible to group by column which is hidden by visible: false. We had to set width: 0 and maxWidth: 0, but even then, a few px of column cells were visible, including sorting indicator. We hid the sorting indicator by headerCellClass: "hidden-xs hidden-sm hidden-md hidden-lg" (those are bootstrap classes) and hidden the few px of each row via custom cellTemplate that contans ng-if="col.grouping && row.groupHeader" (we are using angular).
Also the grouping must not be set on column when creating column definitions, but it must be set when api was registered (typescript code follows):
```
            this._timeout(() => {
                gridApi.grouping.clearGrouping();
                gridApi.grouping.groupColumn(GroupColumnName);
            }, null, false);
```
Hope this helps someone else. And it would be nice to have this bug fixed for good after all these years.

**Comment by kostetskyroma** [comment]
Helps for me: 

`this.bugColumns = [
    { 
      'field': 'device_name',
      'enableGrouping': true,
      'grouping': {
        'groupPriority': 1
      },
      sort: { priority: 1, direction: 'asc' }
    },
    { 
      'field': 'device_type_name', 
      'enableGrouping': true,
      'grouping': {
        'groupPriority': 0
      },
      sort: { priority: 0, direction: 'asc' }
    }
   ];
`
