### ISSUE TITLE
CellTemplate does not work properly

### ISSUE THREAD

**Issue by demoalbe** [angular-ui/ui-grid#5496]
Hi,
i try to explain the problem with some steps:
**GOAL:**
i would show a glyphicon-ok or a glyphicon-remove wheter the value of a column is true or false. For doing it i put this cellTemplate:
`<div class=\"glyphicon glyphicon-ok ui-grid-cell-contents \" ng-show=\"{{row.entity.isActive}}\"></div><div class=\"glyphicon glyphicon-remove ui-grid-cell-contents \" ng-hide=\"{{row.entity.isActive}}\"></div>`

**OBSERVED BEHAVIOUR:**
Sometimes, seemingly not in systematic way, it does not works properly. I mean: sometimes works good, sometimes when the value is true it shows the remove glyph, sometimes when is false it shows the ok glyph.

**HOW TO REPRO:**
I reproduced the problem from a your plunker, but not the exactly the same example i described before. In this case i show the value bold when the value is true, and don't show anything when the value is false. As you can see, there are some false bold and some true not shown.

![example](https://cloud.githubusercontent.com/assets/20185520/16415592/57c99b4e-3d3e-11e6-99c2-7e954eb37abf.png)
[http://plnkr.co/edit/3dmfkfHCmPx71dchy0cC?p=preview](url)

Thank you for helping me!
Alberto

**Comment by bjaraujo** [comment]
http://plnkr.co/edit/WX77YYAmn20qLX2cTO2N?p=preview

**Comment by demoalbe** [comment]
Thank you very much!
