### ISSUE TITLE
files missing in npm package

### ISSUE THREAD

**Issue by DaniVarga** [angular-ui/ui-grid#5499]
Since Version 3.2.x some files are missing in the npm package its breaking my buildscripts.
### v3.2.1

```
$ npm i angular-ui-grid 
/home/test
└─┬ angular-ui-grid@3.2.1 
  └── angular@1.4.12 

$ ls node_modules/angular-ui-grid 
package.json  README.md  ui-grid.js
```
### v3.1.1

```
$ npm install angular-ui-grid@3.1.x
/home/test
└── angular-ui-grid@3.1.1 

$ ls node_modules/angular-ui-grid 
bower.json  package.json  ui-grid.css  ui-grid.js       ui-grid.min.js  ui-grid.ttf
less        README.md     ui-grid.eot  ui-grid.min.css  ui-grid.svg     ui-grid.woff
```

**Comment by paulreeve** [comment]
I am on 3.2.1 and am missing `ui-grid.css`. I ran an `npm cache clean` and the problem still persists.

**Comment by sparty02** [comment]
Same problem here.... was release 3.2.1 published via Node 6?  I've heard that people have had issues with missing files when using Node 6 to publish.

**Comment by paulreeve** [comment]
Reverting to `3.1.1` worked on for me.

**Comment by mportuga** [comment]
This is no longer reproducible in the latest version.
