### ISSUE TITLE
ng-grid doesn't resize with containing <div>

### ISSUE THREAD

**Issue by HiloCoder** [angular-ui/ui-grid#550]
If the div that contains an ng-grid changes size via a transition, ng-grid doesn't resize with the div.   

Here's a Plunker:  http://plnkr.co/edit/wlbbf5

Hit the "Bigger" button and notice the grid doesn't resize with the div.  If you then click on a column header to sort the data, it will resize.   Same problem with hitting the "Smaller" button.

**Comment by sabi02** [comment]
xD Hola, curiosamente yo estoy en pleno 2016 con el problema de que el grid no se ajusta a su contenedor. Curiosamente en mi proyecto estoy usando jquery flot y en mi include de javaScript tengo un js llamado < jquery.flot.resize.js > lei y busqué mucho sobre como solucionar el problema y e aquí la solución. Espero pueda servirles de algo a las personas que pasen por este problema.
