### ISSUE TITLE
grid.options are undefined

### ISSUE THREAD

**Issue by Olegarius** [angular-ui/ui-grid#5500]
Hi. I trying to use ui-grid by Your documentation.
For some reason I always have the error: "Cannot read property 'rowTemplate' of undefined"
Looks like in ui-grid.js on line 9227 grid.options are undefined for some reason.
Note. On Your examples grid controller writed on the main page.
But on My project I load template via $routeProvider:
```
var app = angular.module('app', [ 'ui.grid' , 'ui.grid.selection' ]).config(['$routeProvider', function($routeProvider) {
        $routeProvider.when('/grid', {
                controller: 'GridController',
                templateUrl: 'angular/view/examples/grid.html',
                controllerAs: 'vm'
            });
}]);
```
In this case ui-grid can-not be load as described on Docs.
My full example of code:
**index.html**
```
<!DOCTYPE html>
<html lang="en">

<head>
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" />
</head>

<body>

  <div class="col-lg-12" ng-view>
    <!-- dynamic content -->
  </div>

  <!-- jQuery, angular, bootstrap -->
  <script src="//code.jquery.com/jquery-2.0.3.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.3/angular.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.3/angular-route.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.3/angular-resource.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.3/angular-animate.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.3/angular-touch.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.3/angular-cookies.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/1.3.3/ui-bootstrap-tpls.min.js"></script>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

  <script src="http://ui-grid.info/release/ui-grid.js"></script>
  <link rel="stylesheet" href="http://ui-grid.info/release/ui-grid.css" type="text/css">

  <!-- main module and router-->
  <script src="app.js"></script>

  <!-- examples -->
  <script src="grid.js"></script>

</body>

</html>
```
**app.js**
```
(function() {
  'use strict';

  angular.element(document).ready(function() {
    //initialize app
    angular.bootstrap(document, ['app']);
  });

  var app = angular
    .module('app', [
      'ngRoute', 'ngResource', 'ngAnimate', 'ngCookies', 'ui.bootstrap', 'ui.grid', 'ui.grid.selection'
    ])
    .config(['$routeProvider', function($routeProvider) {
      $routeProvider
        .when('/grid', {
          controller: 'GridController',
          templateUrl: 'angular/view/examples/grid.html',
          controllerAs: 'vm'
        })
        .otherwise({
          redirectTo: '/'
        });
    }]);

})();
```
**grid.js**
```
(function() {
  'use strict';
  angular
    .module('app')
    .controller('GridController', function() {
      //empty controller
    })
    .controller('GridTpl', ['$scope', function($scope) {
      $scope.gridOptions = {};
      $scope.gridOptions.columnDefs = [{
        name: 'name'
      }, {
        name: 'age'
      }];

      $scope.myData = [{
        name: "Moroni",
        age: 50
      }, {
        name: "Tiancum",
        age: 43
      }, {
        name: "Jacob",
        age: 27
      }, {
        name: "Nephi",
        age: 29
      }, {
        name: "Enos",
        age: 34
      }];
      $scope.gridOptions.data = $scope.myData;
    }]);

})();
```
**grid.html**
```
<div class="col-md-6 col-md-offset-3" ng-controller="GridTpl">
  <div ui-grid="gridOptions" class="myGrid"></div>
</div>
```

**Comment by msrikanth508** [comment]
@Olegarius, After defining gridOptions with column definitions again you are defining with data as a new object. 
Instead of doing this $scope.gridOptions = { data: 'myData' };
do this one $scope.gridOptions.data = $scope.myData;

**Comment by Olegarius** [comment]
It does not helps.
I edited the code with fixed errors.
Also I added it to the plunker: http://plnkr.co/edit/JYOffrlUZ2OVsb2rBTBR?p=preview for the better code organization.
Thanks for any help.

**Comment by msrikanth508** [comment]
@Olegarius I have updated plunker http://plnkr.co/edit/PHmFfi3LX0To3KB0H6NA?p=preview here it is
![image](https://cloud.githubusercontent.com/assets/8520311/16447748/acf4ec04-3e0b-11e6-80d1-a1bf299a18a1.png)

**Comment by Olegarius** [comment]
Yes. My faul. Template path.
Could be some module on My real project have conflict with ui-grid.
I will write again when I find the reason.

Thanks for the help.

**Comment by Olegarius** [comment]
I found the real reason of the bug. I was updated the plunker http://plnkr.co/edit/JYOffrlUZ2OVsb2rBTBR?p=preview
The reason of the bug with adding facrory 'configService' in services.js file.
It uses for service provider mechanism.

Any suggestions?

**Comment by Olegarius** [comment]
I solved the problem.
Guys, I little confuzed with this ui-grid.
It is very cool lib, but code realization is sucs:
[] first, You can't use ui-grid if You try use it from controller without $scope (for example I usually used this). For fix this I need to write empty controller and after that another controller with $scope, that calls from html
[] If I want to create Grid service, factory or something like that - ui-grid will give us error "Cannot read property 'rowTemplate' of undefined". For fix that we don't have to use service or factory with name "Grid".

Anyway thanks for this beautiful ui.
But You have mutch work for fixing this bugs.
Good luck!

**Comment by jamespsterling** [comment]
@Olegarius this did the trick for me too, thanks for the solution.
