### ISSUE TITLE
Column filters treat NULL as a string, so the characters "n," "u," and "l" don't filter out rows with null values

### ISSUE THREAD

**Issue by sequentialscott** [angular-ui/ui-grid#5502]
I've found this issue in version 3.1.0, but have reproduced it in a [Codepen using 3.2.1](http://codepen.io/scottmcd/pen/xOqewO).

When using the column filter, entering the characters "n," "u," or "l" initially does not remove rows with null values for that column.  It seems to be treating "null" as a string rather than a value.

In looking at the source, it looks like the rowSearcher.runColumnFilter() function returns true when the value is null:

```
if (filter.containsRE) {
    return filter.containsRE.test(value);
}
```

I'll post any workarounds or fixes here.  Please let me know if I'm doing something wrong in the config, as well.  Thanks!

UPDATE: According to [this SO](http://stackoverflow.com/questions/2430578/is-it-a-bug-in-ecmascript-s-testnull-returns-true), it appears that the .test() function does result in null being coerced to 'null', so it looks like the solution is to check value for null before doing the regex test.

**Comment by sequentialscott** [comment]
The least intrusive update that I see is adding the line at the bottom of the snippet below:

```
  rowSearcher.runColumnFilter = function runColumnFilter(grid, row, column, filter) {
    // Cache typeof condition
    var conditionType = typeof(filter.condition);

    // Term to search for.
    var term = filter.term;

    // Get the column value for this row
    var value;
    if ( column.filterCellFiltered ){
      value = grid.getCellDisplayValue(row, column);
    } else {
      value = grid.getCellValue(row, column);
    }

      if (value === null) value = '';
```

Would it be helpful to submit this as a pull request?

**Comment by aih** [comment]
This is also true for 'undefined', if any cell values are undefined. See a variation on @sequentialscott's Codepen: http://codepen.io/anon/pen/ZpZyrZ
