### ISSUE TITLE
Is this possible in UI-Grid

### ISSUE THREAD

**Issue by VenkatRamNDD** [angular-ui/ui-grid#5513]
Can any one suggest me how to implement this in **ui-grid** 

![griddata](https://cloud.githubusercontent.com/assets/10338765/16521729/7603d7a8-3fb6-11e6-81f8-cd09368fe427.png)

**Comment by hexaclock** [comment]
Try using expandable rows, complex trees, or complex groups. The last one is probably what is best. See the tutorial: http://ui-grid.info/docs/#/tutorial/320_complex_grouping

**Comment by csvan** [comment]
This is not a discussion forum, kindly use StackOverflow.

**Comment by mportuga** [comment]
Moving this to our new support page as this is not a bug.
https://groups.google.com/forum/#!topic/ui-grid-support/tIdcXMCbouo
