### ISSUE TITLE
No option is available to write or not separator header

### ISSUE THREAD

**Issue by SoyElHomerMalo** [angular-ui/ui-grid#5517]
The separator header is written depending on web browser user is using.

```
if (ieVersion) {
    (...)
    frame.contentWindow.document.write('sep=' + columnSeparator + '\r\n' + csvContent);
    (...)
}
```

If a user is working on different browser than IE and wants to use a custom separator, it won't display properly on MS Excel. Similar problem appears if user working on IE try to open a CSV with other program than MS Excel.

We should add a new option on gridOptions that let user decide to use or not this header.

**Comment by EruantalonJS** [comment]
+1

The separator ("sep=") is specific of MS Excel and has nothing to do with the browser used. 

We should let the dev decide if they want to include it or not.
