### ISSUE TITLE
rowedit setRowsDirty() does not set rows as dirty

### ISSUE THREAD

**Issue by cscott-stc** [angular-ui/ui-grid#5518]
Calling setDirtyRows with an array of rows to be set dirty does not result in rows being marked as dirty. 

Issue appears to be caused by the call to "grid.getRow( value );" which returns null. getRow apperas to be expecting a row.entity **not** a row.

Changing "grid.getRow( value );" to "grid.getRow( value.entity );" on line 586 of gridRowEdit.js appears to fix this problem.

**Comment by phillipspc** [comment]
try `setRowsDirty()` instead of `setDirtyRows()`
http://ui-grid.info/docs/#/api/ui.grid.rowEdit.api:PublicApi

**Comment by cscott-stc** [comment]
OK - that's a typo in my logging of incident - in my code I was calling setRowsDirty() 

If i'd been calling a non-existent method I wouldn't have been able to trace the problem back to the call to grid.getRow and implement a fix

**Comment by phillipspc** [comment]
very true... anyways just trying to help.
In my usage of this I've been passing in the row.entity, rather than row, so I think its just a question of documentation. Although it does describe the argument `dataRows` as `the data entities for which the gridRows should be set dirty.`
