### ISSUE TITLE
Check box is not persistent when pagination

### ISSUE THREAD

**Issue by 1112403** [angular-ui/ui-grid#5521]
Hi there,
I use cellTemplate to add an checkbox column to the grid. But there is an issue when I enable pagination feature.

Step to reproduce bug:
- Check the check box on the first row of page 1
- Go to page 2, the check box on the first row is already checked

Here is the [plunker](https://plnkr.co/edit/dI8ykN7Y9omCjZ9byemv?p=preview)

Could anyone tell me what did I do wrong ?
Thanks in advance.

**Comment by joydeeproy** [comment]
Hi,

  I guess you are handling properly after landing to the next page. Please
check this example.



http://ui-grid.info/docs/#/tutorial/314_external_pagination


On Tue, Jul 5, 2016 at 4:54 PM, Nguyễn Tuấn Vương <notifications@github.com>
wrote:

> Hi there,
> I use cellTemplate to add an checkbox column to the grid. But there is an
> issue when I enable pagination feature.
>
> Step to reproduce bug:
>
>    - Check the check box on the first row of page 1
>    - Go to page 2, the check box on the first row is already checked
>
> Here is the plunker <https://plnkr.co/edit/dI8ykN7Y9omCjZ9byemv?p=preview>
>
> Could anyone tell me what did I do wrong ?
> Thanks in advance.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/angular-ui/ui-grid/issues/5521>, or mute the thread
> <https://github.com/notifications/unsubscribe/AOSAdufAZvXnt9FwUBge2RvIOdI75YSWks5qSj7cgaJpZM4JFBU7>
> .
>



-- 
With Regards

Joydeep Roy

**Comment by joydeeproy** [comment]
Please check your js file where you are handling the event.



http://ui-grid.info/docs/#/tutorial/405_exporting_all_data_complex

On Tue, Jul 5, 2016 at 6:35 PM, Joydeep <joydeeproyin@gmail.com> wrote:

> Hi,
>
>   I guess you are handling properly after landing to the next page. Please
> check this example.
>
>
>
> http://ui-grid.info/docs/#/tutorial/314_external_pagination
>
>
> On Tue, Jul 5, 2016 at 4:54 PM, Nguyễn Tuấn Vương <
> notifications@github.com> wrote:
>
>> Hi there,
>> I use cellTemplate to add an checkbox column to the grid. But there is an
>> issue when I enable pagination feature.
>>
>> Step to reproduce bug:
>>
>>    - Check the check box on the first row of page 1
>>    - Go to page 2, the check box on the first row is already checked
>>
>> Here is the plunker
>> <https://plnkr.co/edit/dI8ykN7Y9omCjZ9byemv?p=preview>
>>
>> Could anyone tell me what did I do wrong ?
>> Thanks in advance.
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/angular-ui/ui-grid/issues/5521>, or mute the thread
>> <https://github.com/notifications/unsubscribe/AOSAdufAZvXnt9FwUBge2RvIOdI75YSWks5qSj7cgaJpZM4JFBU7>
>> .
>>
>
>
>
> --
> With Regards
>
> Joydeep Roy
>
>


-- 
With Regards

Joydeep Roy

**Comment by 1112403** [comment]
hi @joydeeproy, thanks for reply
I've tried getPage function in gridApi.pagination.on.paginationChanged but it seems does not work!
Any idea ?

**Comment by miguelotemagno** [comment]
Try change

**data-ng-model="chkCell"**   to   **data-ng-model="row.entity.checkbox"**
