### ISSUE TITLE
cell with value "0" not shown

### ISSUE THREAD

**Issue by thorvx** [angular-ui/ui-grid#5523]
Cell with value "0" not shown when have cellFilter configured, like ui.grid tutorial.

Here the example for (check the column Gender):

http://plnkr.co/edit/J27VGAj3q5AzmKL0Anc4?p=preview

**Comment by DimitarChristoff** [comment]
so 

```js
filter('mapGender', function() {
  var genderHash = {
    0: 'male',
    1: 'female'
  };

```

you actually get values of '1' or '2' passed, which is not in your map. 
also, you do `if (!input) {` which will be falsy for 0 and incorrect. 

**not a bug.**

**Comment by mportuga** [comment]
As @DimitarChristoff pointed out, this is not a bug.
