### ISSUE TITLE
Pinned column headers not clickable/sortable

### ISSUE THREAD

**Issue by csvan** [angular-ui/ui-grid#5532]
To reproduce:
1. Add the ui-grid-pinning plugin for an existing grid
2. Add at least two columns to the grid, one of them having the `pinnedLeft: true` property set
3. Make sure both columns are sortable
4. Render the grid.
5. Click on the non-pinned header - sorting works.
6. Click on the pinned header - nothing happens.

I did some digging on this - the problem seems to happen in the following code:

```
$scope.onDownEvents = function(type) {
  // If there is a previous event, then wait a while before
  // activating the other mode - i.e. if the last event was a touch event then
  // don't enable mouse events for a wee while (500ms or so)
  // Avoids problems with devices that emulate mouse events when you have touch events

  switch (type) {
    case 'touchmove':
    case 'touchend':
      $contentsElm.on('click', $scope.clickFn);
      $contentsElm.on('touchstart', $scope.downFn);
      $timeout(function() {
        $contentsElm.on('mousedown', $scope.downFn);
      }, changeModeTimeout);
      break;
    case 'mousemove':
    case 'mouseup':
      $contentsElm.on('click', $scope.clickFn);
      $contentsElm.on('mousedown', $scope.downFn);
      $timeout(function() {
        $contentsElm.on('touchstart', $scope.downFn);
      }, changeModeTimeout);
      break;
    default:
      $contentsElm.on('click', $scope.clickFn);
      $contentsElm.on('touchstart', $scope.downFn);
      $contentsElm.on('mousedown', $scope.downFn);
  }
};
```

When the `default` block is entered for the pinned column, it appears that, somehow, no listeners are bound at all for the $contentsElm. However, they are indeed bound in the non-pinned column.

**Comment by csvan** [comment]
For anyone interested, I eventually resolved this by setting:

```
  .ui-grid-render-container {
    pointer-events: none;
  }
```

This was necessary since click events to the pinned column were being blocked by a container instance which effectively covered both it and the non-pinned columns. 

This is a hack, and probably not ideal. I have no idea if it breaks any other functions in the grid.

**Comment by mportuga** [comment]
No longer reproducible
