### ISSUE TITLE
Can't update footerCellTemplate

### ISSUE THREAD

**Issue by kimkaid** [angular-ui/ui-grid#5533]
Hello,

I have a grid with its columnDefs containing footerCellTemplate which has a value.
I want to be able to change this value in the footerCellTemplate but while I'm changing it , it's updated in the columnDefs but not rendered again.

I have tried everything I knew to force the refresh of the footer but nothing worked.
        gridApi.core.notifyDataChange(uiGridConstants.dataChange.COLUMN);
        gridApi.core.queueGridRefresh();
        gridApi.core.queueRefresh();   

http://plnkr.co/edit/SnPIocr9rUdIY82Pitzv?p=preview

**Comment by mportuga** [comment]
Moving this to our new support page as it doesn't appear to be a bug with UI-Grid. I also answered your question there.
https://groups.google.com/forum/#!topic/ui-grid-support/gBion1VecNs
