### ISSUE TITLE
Catalan Translation

### ISSUE THREAD

**Issue by polamatvalls91** [angular-ui/ui-grid#5536]
Hi, I find that the grid is not translated into catalan. I have implemented for me and I already have the changes adding a new delegate through the i18n service. May I do a branch and do the pull request?

**Comment by Totemika** [comment]
@pereperot in which fork did you implement it? I wanna add translation for Norwegian

**Comment by pereperot** [comment]
I hadn't pushed it, I've done it because I need it, but no one has answered....

**Comment by Totemika** [comment]
@pereperot you just have to fork the repo, translate it in your fork, and then Pull request. We just did it for Norwegian an hour ago (https://github.com/angular-ui/ui-grid/pull/6062)

**Comment by mportuga** [comment]
@pereperot I know it has been a long time, but a PR from you would be appreciated, or even a pluker that I can copy from.
