### ISSUE TITLE
blank header is not sortable

### ISSUE THREAD

**Issue by jadrake75** [angular-ui/ui-grid#554]
If you define a header with the following object:

{
  field: 'wantList',
  displayName: '',
  resizeable: false,
  width: 28,
  cellTemplate: <some template>
},

This is an icon column where the column either has a value or not (so it would be nice to sort on it).  Using '' for the displayName does not enable sorting.  If I change this to add a '-' or something it is sortable, but the look and feel is less than satisfactory.

**Comment by soyiatgit** [comment]
I have columns with varying text and hence few columns overall height is greater than the area of text within it. The column is sortable only while clicking on headerText. While clicking on empty space below text, the sorting doesn't work. 

Using the above approach by @jadrake75 , one can create a small empty div, but it still do not go well with UX. Any plans to incorporate sorting on header div as such?? Infact are there any reasons for current implementation.??
