### ISSUE TITLE
On Field blur , same value set to other field

### ISSUE THREAD

**Issue by prasannapethe** [angular-ui/ui-grid#5540]
Hi ,
I am using celltemplate as 

![image](https://cloud.githubusercontent.com/assets/12293093/16732285/050d97fa-479a-11e6-99e8-d16eb84e60c0.png)

On wrong entry Entry the Same value set to other field 

![shot](https://cloud.githubusercontent.com/assets/12293093/16732051/df6ed514-4798-11e6-879e-6d670d194014.png)

**Comment by mportuga** [comment]
Our team is currently too small to look into custom behavior issues.
