### ISSUE TITLE
Allow setting $$treeLevel to undefined

### ISSUE THREAD

**Issue by MartijnWelker** [angular-ui/ui-grid#5548]
On line 26630 (v3.2.1) there's a check whether to copy the entity's `$$treeLevel` attribute:
`if ( typeof(row.entity.$$treeLevel) !== 'undefined' && row.treeLevel !== row.entity.$$treeLevel ){`

It would be nice if you could set the `$$treeLevel` to undefined to indicate that the row has become a leaf node.

**Comment by mjvdwater** [comment]
This is still an issue in v4.0.6. It is currently impossible to turn a header row into a non-header row by setting the $$treeLevel property of the row entity to undefined, while it *is* possible to turn a non-header row into a header row this way.
