### ISSUE TITLE
Possible to use different plug in for Pdf export

### ISSUE THREAD

**Issue by PrakashThiru14** [angular-ui/ui-grid#5549]
I know, Pdfmake will not work in IE . But I need to use IE 10 browser only.. is there any other possibility to export ui-grid data to PDF, like any other  plug-in supports?

**Comment by mportuga** [comment]
Moving this to our new support page as it is not a bug with UI-Grid:
https://groups.google.com/forum/#!topic/ui-grid-support/0FKtqwUGTUM
