### ISSUE TITLE
3.2.1 => condition fn no longer triggered

### ISSUE THREAD

**Issue by fyyyyy** [angular-ui/ui-grid#5550]
Previously we were using ui-grid =< 3.1.1

Since 3.2.1, the filter.condition fn is no longer triggered ( in columnDefs )

Our columnDefs are 

```js
_.forEach col... 
  col.noTerm = true;
  col.filter = { condition: fn.... };
  col.filterHeaderTemplate = null;

```

**Comment by conan-z** [comment]
This might be the same issue as @ #5551.
