### ISSUE TITLE
Update Event Documentation from ngGrid to uiGrid

### ISSUE THREAD

**Issue by mariohmol** [angular-ui/ui-grid#5552]
Hi,
the wiki is showing the old style for cpaturing events

https://github.com/angular-ui/ui-grid/wiki/Grid-Events

Correct now is changing to ui like `uiGridEventEndCellEdit` , instead of ng

Just to reminder to update (took one hour to find the correct)

**Comment by mportuga** [comment]
I will be working on this soon, but in the mean time, I am tagging it as a docs change.

**Comment by mportuga** [comment]
The Wiki page is deprecated as it only pertains to the legacy ng-grid.
