### ISSUE TITLE
column resizing issue. 

### ISSUE THREAD

**Issue by elsuenog** [angular-ui/ui-grid#5554]
I have multiple grids being shown on tabs. One grid per tab, the grid has something around 30 or so  columns. When I have click on a new tab the grid only shows first four columns before expanding to show the rest of the columns. Is there a way avoid having this little animation/bug happen and show all columns when changing between tabs?

I have tried to remove ui-grid-auto-resize and that works for only the first tab(which is the one initially active) but when I change to another tab it will only display the first four columns only and shows rest when I scroll horizontally.

**Comment by tempaa2** [comment]
Hi

In gridOptions, the default value for excessRows , excessColumns is 4. But you can update it to whichever number you want. You can try updating $scope.gridOptions.excessColumns value.
Below is Ui grid API information URL.

http://ui-grid.info/docs/#/api/ui.grid.class:GridOptions
