### ISSUE TITLE
Resizing the last column does not work when grid menu is on

### ISSUE THREAD

**Issue by seshma** [angular-ui/ui-grid#5557]
The Grid/Setting Icon Menu overlaps over the right column column divider  and hence cannot resize  the rightmost column 

Refer to plunker: http://plnkr.co/edit/THN0LXEkDEih2e4Efl3b?p=preview

**Comment by eskutti** [comment]
Add the below css style  to resolve the issue : 

.ui-grid-header-cell-last-col + .ui-grid-column-resizer.right {
    margin-right: 23px;
}
