### ISSUE TITLE
es6 module import for ui.grid

### ISSUE THREAD

**Issue by chyzwar** [angular-ui/ui-grid#5558]
Hi, 

I am using es6 modules in webpack. When importing uiGrid I get empty object insted name that can be used in module definition. uiRouter and others in this example properly give string name for module.

``` js
import 'angular-material/angular-material.css';
import 'angular-ui-grid/ui-grid.css';

import angular from 'angular';
import ngAnimate from 'angular-animate';
import ngAria from 'angular-aria';
import ngMaterial from 'angular-material';

import uiRouter from 'angular-ui-router';
import uiGrid from 'angular-ui-grid';

import AppComponent from './app.component';
import Common from './common/common';
import Components from './components/components';

angular.module('ng-app', [
  ngAnimate,
  ngAria,
  ngMaterial,

  uiRouter,
  //uiGrid -> This gives empty object

  Common.name,
  Components.name
])
.directive('app', AppComponent)
```

**Comment by Chyzwar** [comment]
after checking what others do, It might be needed to add index.js with content simmilar to:

```js
require('./angular-aria');
module.exports = 'ngAria';
```

This would solve problem for most modules lie clj, es, browserity...

**Comment by d-amit** [comment]
+1

**Comment by GregePorter** [comment]
And for a quick solution, you can just use 'ui.grid' instead of uiGrid in your module statement

**Comment by Chyzwar** [comment]
Yeah I know that this is solution, but it would be nice to have consistent usage with ES6.

**Comment by GregePorter** [comment]
@Chyzwar , sure sure. I wanted to make a note here just in case someone else came across this page looking for a solution.

**Comment by csvan** [comment]
+1
