### ISSUE TITLE
Graphical chart or JAVAScript chart ?

### ISSUE THREAD

**Issue by himanshumalviya2016** [angular-ui/ui-grid#5571]
hello guys,
       Can you help me to get this chart name and in which plugin this chart is available 
it's kind of Y and X axis based chart the line will be show the currency for particulate points and X-will be Dates  
![capture](https://cloud.githubusercontent.com/assets/18567321/16985013/60a4e6c4-4e9b-11e6-973a-2e6f0b380429.JPG)

**Comment by mportuga** [comment]
How is this a UI-Grid Issue?
