### ISSUE TITLE
clickable buttons instead of checkboxes... inconsistent behavior

### ISSUE THREAD

**Issue by phillipspc** [angular-ui/ui-grid#5576]
For the project I'm working on, I wanted to have some boolean fields be clickable buttons rather than the standard checkboxes. The main bonus of this is not having to enter into edit mode on these fields to make the change (single click rather than one click to enter edit mode and another to check/uncheck).
This allllmost works, but I've noticed some inconsistent behavior, which I've been able to reproduce in this plunker: http://plnkr.co/edit/WfPyG1BMWioi3iWq8QCr?p=preview

Everything works great, except when you immediately (before doing anything else) click the active field for the first row... You'll notice this does not properly trigger the save flow. A second click on the same field seems to get things going, and the problem doesnt occur on other rows.

This is the problem I'm seeing in my project. I can't seem to manually trigger the save flow for rowEdit consistently, and sometimes end up with "dirty" rows that stay dirty until another change occurs. And this happens for all rows, not just the first as in the plunker. Any thoughts or suggestions are appreciated!

**Comment by mportuga** [comment]
Moving this to our newly created support page. Some from the dev team should answer this as soon as possible.

https://groups.google.com/forum/#!topic/ui-grid-support/D4s8VT4QbFI
