### ISSUE TITLE
Disabling of the pinning doesn't work

### ISSUE THREAD

**Issue by angular-user** [angular-ui/ui-grid#5584]
UI-Grid seems to have a bug that it wouldn't remove the pinning when the column config is changed.
I have a plunker below showing a grid pinned and I wanted the columns to be unpinned when a button is clicked. 
http://plnkr.co/edit/ulv21TxdjpO4ZP5YjSHe?p=preview

**Comment by bjaraujo** [comment]
Can't see any issue. Seems to be working fine in Chrome.

**Comment by shivam25** [comment]
Facing similar issue.. where I am not able to unpin a column in my project.
After updating the columnDef, I am also calling gridApi.core.notifyDataChange(uiGridConstants.dataChange.ALL);

But still the problem exists.

Please help @mportuga , @bjaraujo
