### ISSUE TITLE
How to (doc) cellTemplate with ui-sref and item id

### ISSUE THREAD

**Issue by vorburger** [angular-ui/ui-grid#559]
I would appreciate an example on https://github.com/angular-ui/ng-grid/wiki/Templating illustrating how to use cellTemplate with some AngularJS directive (such as e.g. https://github.com/angular-ui/ui-router/wiki/Quick-Reference#ui-sref, which should be a fairly common use case) and access to a row property such as (common again) the ID property of some data.

I've tried things like a ui-sref="main.acontact({id: {{row.getProperty('id')}} })" or a ui-sref="main.acontact({id: $row.getProperty('id') })", but these don't work.. I haven't quite gotten my head around how to do this right..

Thank you!

**Comment by RoyLING** [comment]
I found this issue as well (a very common use case though). I wonder whether this would be addressed in ui-grid (3.x).

**Comment by hannupekka** [comment]
```cellTemplate: '<div class="ui-grid-cell-contents"><a ui-sref="stateName({param1: row.entity.param1, param2: row.entity.param2})">View</a></div>'```
This seem to be working with 3.0.1

**Comment by PraveenGuda** [comment]
@vorburger Can you attach example of $state.href it is not working Thankyou

**Comment by vorburger** [comment]
Hi, sorry no, this was too long ago... Please feel free to ignore this very
old comment from me on this, I've moved on to other things since.

**Comment by kathiravan07** [comment]
columns:
name: 'Start',
            cellTemplate:'<input type="text" id="datepicker"/>',
            width:150,
kendodatepicker:
  $("#datepicker").kendoDatePicker();
i'm access the id to view the date picker but it's not working in the inside the grid
help me
