### ISSUE TITLE
Click event propagation stopped on click with cellNav

### ISSUE THREAD

**Issue by MichalJakubeczy** [angular-ui/ui-grid#5595]
Steps to reporoduce:
1) Make sure you have a grid with cellNav enabled
2) Attach a click handler to document
3) Click on a cell and observe that document click event handler is not triggered.

It is because of this line of code:

```
// When a cell is clicked, broadcast a cellNav event saying that this row+col combo is now focused
$elm.find('div').on('click', function (evt) {
  uiGridCtrl.cellNav.broadcastCellNav(new GridRowColumn($scope.row, $scope.col), evt.ctrlKey || evt.metaKey, evt);

  evt.stopPropagation();
  $scope.$apply();
});
```

Is it necessary to stopPropagation of this click event?

**Comment by mportuga** [comment]
@JLLeitschuh Do you know if that stopPropagation call is necessary?

**Comment by JLLeitschuh** [comment]
Something to do with focus management and the screen reader. I don't really remember.
