### ISSUE TITLE
Remove Angular dependency from npm

### ISSUE THREAD

**Issue by FabioAntunes** [angular-ui/ui-grid#5596]
Please remove angular dependency from the npm package.

```
{
  "name": "angular-ui-grid",
  "description": "A data grid for Angular",
  "main": "ui-grid.js",
  "ignore": [],
  "dependencies": {
    "angular": ">=1.2.16 1.4.x"
  },
 ...
}
```

 I'm using angular 1.5 and because of that I get an unnecessary angular 1.4 version inside of ui-router

```
node_modules/
|__angular-1.5
|__ui-grid/
    |__node_modules/
         |__angular-1.4
```

**Comment by cybermerlin** [comment]
не беспокойтесь
все у Вас будет работать как надо.

**Comment by mportuga** [comment]
With the latest release, we are officially supporting angular 1.5
