### ISSUE TITLE
Disable cell focus for row selection checkboxes

### ISSUE THREAD

**Issue by vijaygkd** [angular-ui/ui-grid#5597]
I have a ui-grid with several columns. Two of those columns are editable. I have also enabled row selection which makes the checkboxes appear in the left most column of the row.

I have disabled cell focus for non-editable columns. What I want to achieve is when I edit one of the editable column cell and hit tab, it should navigate only between the editable columns. The problem with the current setup is that the focus shifts from the editable cells in a row to the selection checkbox in the next row instead of going to next editable cell. I want to disable focus for the selection checkboxes. Is there an api to do it?

Here is my stackoverflow post regarding this.
[Angular ui-grid disable cell focus for row selection checkboxes](http://stackoverflow.com/questions/38532519/angular-ui-grid-disable-cell-focus-for-row-selection-checkboxes)

**Comment by vijaygkd** [comment]
Any comments about this?

**Comment by mportuga** [comment]
Moving this to our new support forum.
https://groups.google.com/forum/#!topic/ui-grid-support/h2ZLeubcxpM
