### ISSUE TITLE
Writing ui Grid in Modular way in angular service not working

### ISSUE THREAD

**Issue by smrutiranjan727** [angular-ui/ui-grid#5598]
Previously my ui grid configuration settings was in controller, which was working fine - something like this http://plnkr.co/edit/C64KvvmoLHMDO2BdMW7i?p=preview. Now, I want to write my code in modular way in which I'm creating a service method and passing the column definition and the required properties (http://plnkr.co/edit/gyCK3rJRQEOewO2Sq9T4?p=preview) and trying to build the ui grid in one place rather than writing it in every controller. Can anyone plz solve my problem??

**Comment by psmyrdek** [comment]
Check this out:

http://plnkr.co/edit/PXUBOH6LiYXfMHSahB4x?p=preview

You should just update properties in existing $scope.gridOptions object instead of creating a new one.
