### ISSUE TITLE
How to use the save selection for the angular UI grid with saveRowIdentity callback for showing the correct selected rows after restoring the saved state? 

### ISSUE THREAD

**Issue by jainrocks** [angular-ui/ui-grid#5609]
How to use the save selection for the angular UI grid with **saveRowIdentity** callback for showing the correct selected rows after restoring the saved state? 

As mentioned in the tutorial :
Save the currently selected rows. If the saveRowIdentity callback is defined, then it will save the id of the row and select that. If not, then it will attempt to select the rows by row number, which will give the wrong results if the data set has changed in the mean-time.

But I don't know how to write the saveRowIdentity callback and use for this purpose. Please help...

**Comment by jainrocks** [comment]
Okay got it:

Defining this property with columnDefs and other as:
saveRowIdentity: $scope.fun

`$scope.fun = function(rowEntity) {
      return rowEntity.fieldName;
}`

This is giving the desired result.

**Comment by vpetrovic** [comment]
Is there any way that this system can work with external pagination?
