### ISSUE TITLE
Default Column Sort Direction

### ISSUE THREAD

**Issue by strider820** [angular-ui/ui-grid#561]
Is there any way to give a column a default sort direction? The problem I'm having is that I have a few number columns, and they default to sort low-to-high when they're sorted initially, but I need them to default to high-to-low first.

I've been looking through the api and code, and I'm not seeing anything. Am I missing something, or is this not currently possible?

**Comment by kmittal** [comment]
@elirankon: Was the PR by you, ever merged in? I am also looking for a way to set the 'first' sort order (on column header click)  to descending instead of ascending....
Thank you.

**Comment by elirankon** [comment]
Hi Kushagra,

Yes, it was merged into the 2.x branch.

On Mon, Apr 27, 2015 at 7:54 PM, Kushagra Mittal <notifications@github.com>
wrote:

> @elirankon <https://github.com/elirankon>: Was the PR by you, ever merged
> in? I am also looking for a way to set the 'first' sort order (on column
> header click) to descending instead of ascending....
> Thank you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui/ng-grid/issues/561#issuecomment-96738651>.
>



-- 
-------------------------------------
Eliran Kononowicz
+972-545-442913

**Comment by kmittal** [comment]
@elirankon : Thanks for responding. Can you please tell me what's the solution or where can I look for the fix... Its hard for me to track it down in the pull requests log.

**Comment by SteGriff** [comment]
@kmittal PR link: https://github.com/angular-ui/ng-grid/pull/1864

**Comment by fretman92** [comment]
Update: use the **sort** property of a columnDef to specify a default sort direction at init.

Doc: http://ui-grid.info/docs/#/api/ui.grid.class:GridOptions.columnDef

```
{ field: 'DateCreation', sort: { direction: uiGridConstants.DESC }, }
```

**Comment by cstephe** [comment]
Can't you just write a custom sort?

**Comment by edlahoz** [comment]
If you are sorting after init and have externalSorting: true, how would you manually tell ui-grid to set a particular column to sorted (either asc or desc). Is there like a setter method for this?
