### ISSUE TITLE
Row expand on click of celltemplate, UI-Grid in Angular JS

### ISSUE THREAD

**Issue by kaavya07** [angular-ui/ui-grid#5613]
Hi All,

I would like to expand the row on click of celltemplate data instead of Plus Sign.

Please help.

Please see image below.
Its expanding on click of Plus Sign but wanted it to be from click of Jobname.
![image](https://cloud.githubusercontent.com/assets/18394370/17512483/a9b65078-5e45-11e6-869e-d6443bdf00b6.png)

**Comment by angular-git-user** [comment]
write a row template with a callback function into your controller/directive which would take the row and use row expansion api to do the rest..

**Comment by AdrianToman1** [comment]
Below is the cell template I used to done the same thing:

`var cellTemplate = '<div ng-click="grid.api.expandable.toggleRowExpansion(row.entity)" class="ui-grid-cell-contents" title="TOOLTIP">{{COL_FIELD CUSTOM_FILTERS}}</div>';`

**Comment by manjunathmofs** [comment]
Can have a look so it might help u for your question asked
http://plnkr.co/edit/YnLVEUS4gmZWXjgsNXdU?p=preview

**Comment by vcollado** [comment]
@magnusakselvoll using v4.0.7 the event is fired too in the [+] icon
solved like this
```
if (event.target.localName === 'div')
```
if someone is using typescript, the event param is `(parameter) event: angular.IAngularEvent`  you can access with
```
// plain js
event['target']['localName']
// or lodash
_.at(event as any, 'target.localName');
// or change event type declaration
event:any
```
