### ISSUE TITLE
Custom Viewport Template failing to load

### ISSUE THREAD

**Issue by AndyCadney** [angular-ui/ui-grid#5617]
I’ve successfully added several custom templates to ui-grid in the past. Header template, cell template, header cell template have been no problem.

However I’ve been trying to add a custom viewport template to ui-grid with no success. 

I tried adding the template:

- Exactly as the tutorial
- Using the method that has worked successfully with other templates.

I’ve also searched for issues covering this with no success.

Here’s a custom header template successfully added:

[https://plnkr.co/edit/Vh4uEX5Gksk0kHkVV7Yk?p=preview](https://plnkr.co/edit/Vh4uEX5Gksk0kHkVV7Yk?p=preview)

Then here’s a custom viewport template failing to load using the same method:

[https://plnkr.co/edit/50dmzHwdhZNWj0tzR7ux?p=preview ](https://plnkr.co/edit/50dmzHwdhZNWj0tzR7ux?p=preview )

I’m using ui-grid 3.1.1

- Is it possible to add a custom viewport template?
- If so, what am I doing wrong?

**Comment by mportuga** [comment]
I have moved this question to our new support forum and answered it there.
https://groups.google.com/forum/#!topic/ui-grid-support/pZbMZZHsctI
