### ISSUE TITLE
Delay in rendering data in UI-Grid

### ISSUE THREAD

**Issue by SushantVarshney** [angular-ui/ui-grid#5618]
When I render my data for the first time through UI-Grid it takes a noticeable delay in showing it and the data is not so much of size also when I show my UI-Grid on javascript modal it doesn't show data but UI-Grid appears I have to press F12 or any other key on the browser so that data becomes possible.

**Comment by angular-git-user** [comment]
http://ui-grid.info/docs/#/tutorial/110_grid_in_modal
try calling this api.. handleWindowResize for the latter part of your problem.
