### ISSUE TITLE
Public Api Events need improved documentation

### ISSUE THREAD

**Issue by rwtaggart** [angular-ui/ui-grid#5621]
Hi! 

Your tutorials documentation is great. My team has been able to quickly get started using your components. However, the API documentation could use some work. It is not trivial to find events and examples of how they can be implemented. 

For example, it took us a long time to figure out how to use the _filtersChanged_ Event. The events are not searchable in the _search box_ for the API. One of my team members happened to stumble on this:  http://ui-grid.info/docs/#/api/ui.grid.core.api:PublicApi which lists the event near the bottom of the page, while he was looking for something else. Although he found it, there was not an example of how to use this within the code. We had to go somewhere else to find an example (one of your issue requests had a code snippet). 

It would be great if there exists a list of all Events which are supported for use by ui.grid, and that these events are searchable in the API/Tutorial search box:  http://ui-grid.info/docs/#/api

Thanks!

**Comment by mportuga** [comment]
Thank you for this information! I am moving this to our new support page as it is not an actual issue with UI-Grid, but a request. Someone from the Dev team should reply to your request there.
https://groups.google.com/forum/#!topic/ui-grid-support/Ehjgch4pP1A

Regards,

Marcelo
