### ISSUE TITLE
User shold not allow to hide all columns[add restriction to do that]

### ISSUE THREAD

**Issue by kite57** [angular-ui/ui-grid#5625]
Hello,

User shold not able to hide last column, There should be restriction for user that last column can not be hidden.

currently user can hide all column.

Issue: due to this, Grid will be hidden and we can not rollback or enable grid/column to user. user need to refresh page.

for help :   http://plnkr.co/edit/k2SEUyHuyyLOexjWNy4U?p=preview

Try to hide column one by one. you can hide all all column and when you hide last column of grid then grid disappear

**Comment by angular-git-user** [comment]
use this propery in columnDefs object `enableHiding: false`

**Comment by zestime** [comment]
Following [Tutorial: 303 Customizing Column Menu](http://ui-grid.info/docs/#/tutorial/303_customizing_column_menu)
You can use the 'shown' function for visibility of the hide menu.

But, 'hide column' is one of default menu items.
We can't change the 'shown' function.
I just added new custom menu for 'hide column'.
http://plnkr.co/edit/T8Srk79KMr03cItTVeUc?p=preview

**Comment by kite57** [comment]
Thank you both of you for this help.
