### ISSUE TITLE
Hiding columns with pre-set width leave blank space in the grid

### ISSUE THREAD

**Issue by Uma19** [angular-ui/ui-grid#5628]
Hi Team, 
I would like to raise one issue related with ui-grid which is as follows. Suppose I have 5 columns and for all width is defined. Now when you try to hide the column one by one then in the end it will leave blank space. But if we don't give any width then it takes is very fine ? Is there any solution for the same?

**Comment by Uma19** [comment]
![grid](https://cloud.githubusercontent.com/assets/10219453/17724664/7dfab72c-6461-11e6-814f-66bc38200250.png)

This is the sample file uploaded related with grid

**Comment by mportuga** [comment]
Working as intended since we do not want to change user's pre-set column widths.
