### ISSUE TITLE
Bower in VS doesn't find the latest version of ui-grid

### ISSUE THREAD

**Issue by CosminCraciun** [angular-ui/ui-grid#5631]
Bower in VS 2015 update 3 finds only version 3.2.1 of ui-grid. I've found a workaround by setting angular-ui/ui-grid.info as download link, but this downloads all versions of the grid.
I believe that the tags are not up-to-date (the last one is 3.2.1).

**Comment by mportuga** [comment]
This is no longer reproducible to me.
