### ISSUE TITLE
filtering with a multi-select drop down list

### ISSUE THREAD

**Issue by jmsunseri** [angular-ui/ui-grid#5638]
This isn't so much an issue as much as it is that I implemented a feature and I wanted to see if you are interested in this functionality.

`if (newFilter.condition === uiGridConstants.filter.EXACT) {
              if (newFilter.term.length !== undefined) {
                var expression = '';
                if (newFilter.term.length > 0) {
                      for (var i = 0; i < newFilter.term.length; i++) {
                          expression += '^' + newFilter.term[i] + '$|';
                      }
                      expression = expression.substring(0, expression.length - 1);
                  }
                newFilter.exactRE = new RegExp(expression, regexpFlags);
             } else {
                  newFilter.exactRE = new RegExp('^' + newFilter.term + '$', regexpFlags);
             }
        }`

I've also implemented created new templates for the filter text boxes and drop downs to use the ui-select controls though I'm not sure you would be interested in that dependency though.

**Comment by christig** [comment]
I was working on some customer filters and would be interested in seeing this. Do you have a plnkr demo? Thanks!

**Comment by jmsunseri** [comment]
I was working on a plunk but I couldn't get past this "Bad Request" message on plnkr

http://plnkr.co/edit/ESxWz3H2cMiGKveZ7SK9?p=preview

**Comment by christig** [comment]
I think it was because of the ui-bootstrap files. They had paths to files that weren't included in the plunk. I updated a few of the dependencies to use CDN's and it resolved the bad request issue. http://plnkr.co/edit/nuldgAtBeHF6RTdlIwko?p=preview

**Comment by jmsunseri** [comment]
Thanks so much!  Let me get some of my "real work" out the door and i'll
update the plunk so that it works like my app does.


Sincerely

Justin Sunseri
Please don't print this e-mail unless you really need to.
