### ISSUE TITLE
Grouping fails while implementing auto row height in angular ui-grid

### ISSUE THREAD

**Issue by arya220** [angular-ui/ui-grid#5641]
I have been trying to create an angular ui-grid with auto row height.

Meaning height of a particular row should increase automatically when the contents of the cell does not fit in. I am using ng-input-tags library for one of the columns where the contents of the cell is supposed to increase.

However I was able to achieve the same with following CSS code.

```
.ui-grid-row {
  height: auto!important;
}

.ui-grid-row > div {
  display: table-row;
}

.ui-grid-row > div .ui-grid-cell {
  display: table-cell;
  float: none;
  vertical-align: middle;
  height: auto!important;
}

.ui-grid-cell-contents {
  white-space: normal;
  text-overflow: inherit;
  word-break: break-word;
}
```

But when I applied grouping and selection, the alignment breaks completely.
Here is a [plnkr](http://plnkr.co/edit/Cs4zpp?p=preview) which I have created to demonstrate the issue.

I am expecting the grid to support auto row height, at the same time it should not loose grouping and selection functionality.

**Comment by shamimafridi** [comment]
I have the same issue.
