### ISSUE TITLE
UI-Grid responsive

### ISSUE THREAD

**Issue by SyedImranAhmed** [angular-ui/ui-grid#5642]
Hi everyone. I am new to ui-grid. I am implementing ui-gird for my project, previously we used footable for smaller device. Is this possible have similar to footable in ui-grid ?

**Comment by mportuga** [comment]
I took a look at foo table and I do think that is a pretty clever solution for responsiveness. The tricky would be to figure out which columns to hide.
https://fooplugins.github.io/FooTable/
