### ISSUE TITLE
Ui-grid blanks out on latest Chrome

### ISSUE THREAD

**Issue by jj-12** [angular-ui/ui-grid#5645]
Hey guys,

First, thanks for all your hard work.  We have been using UI-grid across different solutions in our company (Adobe) for about a year and a half now, and we love it.  It is far and away the best open source grid solution out there.  Thanks!

We have noticed that there is a very large delay on updating the cells in the newest version of Chrome ( 52.0.2743.116) that was not present beforehand.  I have created a plunkr and a gif that are attached at the end to help illustrate the problem, but the main issue is that when scrolling down through data in Chrome 52, the grid blanks out for nearly a second, which makes the grid nearly unusable now.  

Please let me know if there is more information that I could provide to help.  Thanks again!

http://plnkr.co/edit/WHW3y8VJiUZUVjzdunPf?p=preview (resize the `preview` frame to take up about 1400px, or show about 9 columns, and then start scrolling downwards with long, evenly spaced swipes)

**OS:** OSX Mavericks- El Capitan (haven't tested on a PC, but it could be present there as well)
**Browser:** Chrome ( 52.0.2743.116)

![ui-grid-blank](https://cloud.githubusercontent.com/assets/14099258/17937622/fa26f9b8-69df-11e6-9df2-f0db32623aaf.gif)

**Comment by w8kbrdr22** [comment]
I'm seeing the same problem.  @jj-12 , in the future you may want to directly reference a member of the team like @c0bra , since they are very busy and may not have seen the issue.

**Comment by jj-12** [comment]
Thanks for the suggestion, @w8kbrdr22.  So, looking at the latest commits to the repo, would it be @swalters, @JLLeitschuh , or maybe @PaulL1 that would be able to respond to this?  Are you guys still actively maintaining this?

Thanks, in advance, for your response!

**Comment by paragraff** [comment]
Try set property "Use hardware acceleration when available" in Chrome Settings. It's helped for me. 
In my case, this setting has been unchecked. I learned this by accident, when discovered that WebGL is not working: https://productforums.google.com/forum/#!msg/chrome/8pe3gOapNS0/ihwZDu9IAAAJ

**Comment by jj-12** [comment]
Hey, thanks for the response @paragraff .  I actually do have the property already checked in my Chrome Settings.  I'm seeing this error with or without the "hardware acceleration" option checked.  But you aren't seeing this problem with it checked?  Do you have at least 9 columns showing on that plunkr?  I'm seeing it consistently across 7 different computers.

Thanks,

**Comment by paragraff** [comment]
Hi, @jj-12!
Yes, after reload my browser, state of acceleration doesn't mater. But i had this problem before property state change and reload. And do not see after. I checked view from 2 to 12 columns. Browser 52.0.2743.116 (64-bit), OS OSX Yosemite.

Aaaaaand! I update browser to 53.0.2785.101 (64-bit) and see again this bug! %) WebGl don't work too. Again. State of "hardware acceleration" doesn't mater. 

Statistics for @swalters, @JLLeitschuh:
**Browser**: 53.0.2785.101 (64-bit), **OS**: OS X 10.11.6 (15G1004) - bug exist
**Browser**:  53.0.2785.101 (64-bit), **OS**: OS X 10.10.5 - bug exist
**Browser**:  52.0.2743.116 (64-bit), **OS**: OS X 10.11.4 (15E65) - work fine
**Browser**:  52.0.2743.116 (64-bit), **OS**: OS X 10.10.5 - work fine
**Browser**: 52.0.2743.116 m (64-bit), **OS**: OS Windows 7 - work fine with acceleration, bug without acceleration

**Comment by jj-12** [comment]
Hi @swalters, @JLLeitschuh & @paragraff 

Could you provide me with any update on this issue?  I'm still seeing this on Chrome Version 54.0.2840.87 (64-bit)

Thanks!

**Comment by paragraff** [comment]
@jj-12 i didn't find anything  :(

**Comment by csvan** [comment]
This almost certainly has to do with how Chrome handles mousewheel events. There seems to be some kind of throttling going on which causes the actual content box to visually scroll, but the event being delayed so that ui-grid does not update.

**Comment by paragraff** [comment]
@jj-12, @csvan  it was fixed on Chrome 55

**Comment by csvan** [comment]
Confirming that Chrome 55 resolves this issue, I think you can close it @jj-12

**Comment by jj-12** [comment]
Yes, it works!  Thanks for tracking this guys, I really appreciate it.  Closing.
