### ISSUE TITLE
Add two icons in cellTemplate

### ISSUE THREAD

**Issue by cibi246** [angular-ui/ui-grid#5647]
Hi,

Is it possible to display two glyphicons inside a cell template.

Example:
cellTemplate:'<div ng-class="[{'\glyphicon glphicon-arrow-up\':{{row.rowIndex === 0}}},{'\glyphicon glyphicon-arrow-up glyhicon glyphicon-arrow-down\':{{row.rowIndex >== 0}}}]"'

I tried it. But didnt not get two glyhicon icons. Is there any other ways to have two glyphicons icons in a cellTemplate?

Thanks in advance.

**Comment by mportuga** [comment]
Yes, see plunker: http://plnkr.co/edit/WXxYSELrcaol7tBXY5Qj?p=preview
