### ISSUE TITLE
'auto' column widths do not work

### ISSUE THREAD

**Issue by wattsbn** [angular-ui/ui-grid#565]
Unless I am missing something, setting a column width to 'auto' does not work any longer. Based on the documentation I found for this feature (https://github.com/angular-ui/ng-grid/wiki/Defining-columns), I assumed it would size the column to the size of its cells' contents. However, it seems to be always be set to the same really small width.

Here is a simple example of what I am seeing:
http://plnkr.co/edit/1l2dwY?p=preview

**Comment by chfw** [comment]
@charliehavak, your solution works for me. For everyone, I had ng-grid 2.0.11 and angular 1.3.10.

**Comment by a002194** [comment]
What is final solution for latest UI grid (3.0 and above) to make auto column width based on data? 

1) I tried above given custom logic [](http://plnkr.co/edit/96o8ZemeM1IG8CpaXwV2?p=preview) but this is also displaying unwanted empty space when increase the character size. 
2) Width='auto' doesn't support latest version. So, i tried Width="*" and Width="**" these are also not working.

now do we have any fix for this?

**Comment by derekm** [comment]
@a002194 -- Issue #5839 intersects your request for fixes.
