### ISSUE TITLE
change cell value if cell value is negative

### ISSUE THREAD

**Issue by avuthubhargavreddy** [angular-ui/ui-grid#5654]
hi,
i want to change the cell value if cell value is negative number

if cell value is **-2224.33** i wanted it as **(2224.33)**
please help me out.

**Comment by zestime** [comment]
That is quite simple. You can set a property of _cellFilter_. The _cellFilter_ accepts Angular's filter. 
Look at this, http://plnkr.co/edit/8iMxlRJctiTmxlVPg6rv?p=preview
I just created **negative** filter on Angular module. And I put it on 'age' column using _cellFilter_.

**Comment by avuthubhargavreddy** [comment]
yes worked perfectly thanx
