### ISSUE TITLE
Renaming Column Bug

### ISSUE THREAD

**Issue by gf-atebbe** [angular-ui/ui-grid#5656]
It seems that whenever a column is renamed (by adding a new field and removing the old one in the bound data as well as updating the field, name and displayName attributes of the column definition) the data disappears from view in the renamed column.

I have posted an example reproducing the issue here:
https://plnkr.co/edit/EziHHhEr2694W6lmBsip?p=info

If I do not delete the original element from the bound data then the data is still displayed in the ui-grid, so it seems like even though I change the column definition the grid does not update to reflect the new definition.

# Reproducing The Issue

1. Click on the column menu arrow in the "Removable" column
2. Select "Rename Column" from the context menu
3. In the popup box enter any string of characters (ex. Blah)
4. The column is renamed but no data is displayed in the column

If inspecting the bound data and grid options, both have been updated to reflect the new name yet the column has empty values in every row

**Comment by zestime** [comment]
I'm not sure that is a bug. In my thought, you should re-assign a columnDef property when you change column options. The property is not compared deeply. I just modified a little bit on your code. 

https://plnkr.co/edit/r4IQBFVndypKaCYW6TiZ?p=preview

**Comment by gf-atebbe** [comment]
Thank you for the quick response this solved my issue!
