### ISSUE TITLE
select a row with e2e test api

### ISSUE THREAD

**Issue by rafakwolf** [angular-ui/ui-grid#5675]
I'm trying to use "test/e2e/gridTestUtils.spec.js" on my e2e tests but, seems not working...

html 
`<div id="searchGrid" ui-grid="ctrl.gridOptions" ui-grid-exporter ui-grid-selection ui-grid-pagination class="grid"></div>`

test

```
var gridTestUtils = require(' ....  /test/e2e/gridTestUtils.spec');

// after the data loaded
 gridTestUtils.selectRow('searchGrid',0);   
```

something is wrong?  Thanks

**Comment by piyush-dholariya** [comment]
how can I highlight ui-grid row on selection/click, which has 6 pinned columns?

**Comment by rafakwolf** [comment]
@piyush-dholariya make your questions in other issue please.
