### ISSUE TITLE
CellTemplate checkbox First Row Alone Not Checked By Default

### ISSUE THREAD

**Issue by BhuvanaSanthoshkumar** [angular-ui/ui-grid#5681]
Please see the plunker,
 http://plnkr.co/edit/5hm1azyeSrWBwCNa8hKi?p=preview 

the first checkbox in grouped header is never selected.

**Comment by bjaraujo** [comment]
I had similar problem. I solved it by using ui-grid-tree-view and calculating the grouping values myself. Also added a flag in the treelevel = 0 to hide checkbox and rowTemplate.
