### ISSUE TITLE
 UI Grid Bug- Agg:remove is not working

### ISSUE THREAD

**Issue by rKS2827** [angular-ui/ui-grid#5682]
In Ui-Grid table I am using aggregate function ,but on agg:remove getting error in console "TypeError: aggregation.col.treeAggregationFn is not a function" .After click on agg:remove not able to apply aggregate function on other columns.

check this image for error http://i.stack.imgur.com/6Ja7t.png
 Here is plnkr https://plnkr.co/edit/lTkddSNhfLPHQfuldWfs?p=preview

please review it asap

**Comment by mportuga** [comment]
I believe that adding a angular noop for a default function or checking if treeAggregationFn is a function.
