### ISSUE TITLE
Scrollbars disappears when user clicks/doubleclicks in an input field (in edit mode) 

### ISSUE THREAD

**Issue by louwie17** [angular-ui/ui-grid#5685]
When I use the edit feature on the ui-grid, and either click or double click inside the input field both the scrollbars disappear. This makes the ui-grid jump a little bit, and doesn't look that great.
It can be simulated in any of the edit grid examples.
It seems to happen here:
https://github.com/angular-ui/ui-grid/blob/master/src/features/edit/js/gridEdit.js#L993

Is there a specific reason for setting disableScrolling to true here? or could this be removed?

**Comment by swalters** [comment]
It's by design.  If I remember correctly, the grid will scroll even more as it brings an editable cell into focus.  In short, it's a hack but it's a worse UI experience without it.
