### ISSUE TITLE
No way to differentiate columns from a custom sorting algorithm

### ISSUE THREAD

**Issue by chmirenko** [angular-ui/ui-grid#5692]
Custom sorting algorithms are unaware of the invoking column.
Adding it will allow, for instance, grouped sorting that may require lockup without having to define a custom sorting function per column just to identify the caller and run the same logic.

Row awareness was addressed here: https://github.com/angular-ui/ui-grid/pull/4455

Could it be possible to expose the column also on this line: [Code](https://github.com/angular-ui/ui-grid/blob/0da5cd4b6c31390ba97a1ab3cb20992de75e89ec/src/js/core/services/rowSorter.js#L458)

`tem = sortFn(propA, propB, rowA, rowB, direction, col);`

**Comment by dlgski** [comment]
Would you mind adding a plunker here and creating a PR with your proposed fix?  Thanks!

**Comment by chmirenko** [comment]
I don't think I can represent this in a plunker since it's about including a parameter that was not there.

Please review the PR. 
I see a build issue but from the log seems its the web-runner, mine was travis-linux-5 instead of travis-linux-7...?

I also updated the current documentation: [https://github.com/angular-ui/ui-grid/wiki/Sorting]
It now includes the rows and direction. (from the mentioned [#4455](https://github.com/angular-ui/ui-grid/pull/4455) )
