### ISSUE TITLE
Unpinned columns are not visible in lower width screens(mobiles), when some columns are pinned left and right.

### ISSUE THREAD

**Issue by PhanindraNath** [angular-ui/ui-grid#5695]
When nothing is pinned and the browser is resized to very small, The columns are scrolling horizontally. This is also working very fine.

When few columns are pinned right and/or left, unpinned columns will scroll horizontally in between them. This is working very fine.

Now, when I resize the browser, approximately to a width of "total width of pinned columns". It's breaking. I mean, one can not view the unpinned columns.

For example:
http://plnkr.co/edit/XFAXNbS1uahXaSM8qz4P?p=preview

Steps: resize the preview panel width to the total size of pinned columns.

![screenshot 4](https://cloud.githubusercontent.com/assets/19472549/18836712/d3cd01fa-841e-11e6-8310-dbedea2f2559.png)
Image - 1: Grid without issues.

![screenshot 5](https://cloud.githubusercontent.com/assets/19472549/18836754/fc8daca2-841e-11e6-984a-714f1a208188.png)
Image - 2: Grid with issue is showing

Expected solution:
Unpin the pinned columns when the screen width is below some margin from the total width of pinned columns.

**Comment by mportuga** [comment]
Unfortunately, I don't believe it is a good idea for the grid to unpin columns by default with this. I guess this relates to the responsiveness headline that many have been asking about, but we need to come up with a solution that respects user settings. This might be doable on your own code though.

**Comment by PhanindraNath** [comment]
> we need to come up with a solution that respects user settings

Yes, definitely. 

I would like to have a config property in the ui-grid options, which specifies to unpin all columns if the screen width is less than a specified width. This can be checked while initializing and on window resize.

For Example,
`unpinAtWidth: 500;`

If window width or grid width is below the specified width in pixel, columns can be unpinned.
If the property is not specified or assigned no value, it should work as it is working currently.
