### ISSUE TITLE
afterCellEdit event with expandable grid not working

### ISSUE THREAD

**Issue by moustafa20** [angular-ui/ui-grid#5696]
Hello 
i'm trying to use afterCellEdit event with expandable grid but unfortunately it doesn't work with sub-grid but it work just fine with parent grid  
i also reviewed this questions posted on stackoverflow two months ago but no one give an answer  
[http://stackoverflow.com/questions/38125120/aftercelledit-for-subgrid-ui-grid/39709429#39709429](url)

thank you

**Comment by moustafa20** [comment]
any ideas ?

**Comment by moustafa20** [comment]
why it takes so long from anyone to answer me?

**Comment by mportuga** [comment]
Please use stackoverflow or gitter for questions. Unfortunately, I don't have a quick answer for you and am not familiar enough with that behavior to help at the moment.
