### ISSUE TITLE
grunt build task fails due to PhantomJS timeout

### ISSUE THREAD

**Issue by dKab** [angular-ui/ui-grid#5699]
After successful installation of npm and bower dependencies I run grunt default task (build) and it fails:Running "karmangular" task

Running "karma:angular-1.2.14" (karma) task
WARN [plugin]: Error during loading "C:\ui-grid\node_modules/karma-requirejs" plugin:
  Cannot find module 'requirejs'
(node:8472) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.
INFO [karma]: Karma v0.12.37 server started at http://localhost:19876/
INFO [launcher]: Starting browser PhantomJS
WARN [launcher]: PhantomJS have not captured in 60000 ms, killing.
INFO [launcher]: Trying to start PhantomJS again (1/2).
WARN [launcher]: PhantomJS have not captured in 60000 ms, killing.
INFO [launcher]: Trying to start PhantomJS again (2/2).
WARN [launcher]: PhantomJS have not captured in 60000 ms, killing.
ERROR [launcher]: PhantomJS failed 2 times (timeout). Giving up.
Warning: Task "karma:angular-1.2.14" failed. Use --force to continue.

Aborted due to warnings.

I tried to change PORT in karma.conf from 9876 to 19876 but it didn't help.
The same happend on Ubuntu and Windows machines. 
I tried several solutions from this thread https://github.com/karma-runner/karma-phantomjs-launcher/issues/84 neither of them worked. 
node -v
v6.4.0
npm -v
3.5.3

Any thoughts?

**Comment by mportuga** [comment]
I recently added requirejs to package.json, try again if you are still interested.
