### ISSUE TITLE
adding new row and nextPage doesn't work properly

### ISSUE THREAD

**Issue by wallyjava** [angular-ui/ui-grid#5707]
I am adding a row to a grid and want to go to the next page when the grid data length is greater than the page size.  It doesn't work when the grid data length is 1 greater than the page size, but does work when it is 2 greater.

Here is my plunker:  http://plnkr.co/edit/GgtZ9AkXnSq4tK6eauEl?p=preview 

When first run there are 7 items and page size is 7.  When I click add row the first time the page count increase to 2, but does not go to the next page.  When I click add row again it does advance.

I've posted in in angular ui grid gitter and did not get an answer.

Thanks

**Comment by panxq5** [comment]
try this
`                $timeout(function() {
                    $scope.gridApi.pagination.nextPage();
                }, 100);`

**Comment by wallyjava** [comment]
that worked thanks.
