### ISSUE TITLE
Select all vs individual selection is not consistent when using filters

### ISSUE THREAD

**Issue by twisted8** [angular-ui/ui-grid#5708]
plnkr:  http://plnkr.co/edit/SwbI5j02qAG4aFbWXF4X?p=preview

Use case 1:  
1. select 'Ethel'
2. select 'Claudine'
   **Result:  Selected Items: 2**
3. filter by name. type: 'ber'
4. select Beryl, Dawson and Lakisha **(manual selection)**
     **Result:  Selected Items: 5** 
5. Clear filter. same 5 items are selected.

Use case 2:
 (clear all selections)
1. select 'Ethel'
2. select 'Claudine'
   **Result:  Selected Items: 2**
3. filter by name. type 'ber'
4. Click **select all** checkbox 
   **Result:  Selected Items: 3**
     Should it be 3 or 5? in this case previous selection is cleared. On previous use case the selection is not cleared.
5. Clear filter. Only 3 items are selected.

Thank you

**Comment by mportuga** [comment]
Well, i believe the reason for that is because select all will actively loop through other rows while doing its thing, while individual row selection will never look at or interfere with the selection status of other rows.
