### ISSUE TITLE
[Feature Request] - Need an option to make Selection by Checkbox & Selection by Row to behave different and to fire 2 different events based on  new option from gridOptions

### ISSUE THREAD

**Issue by syesudas** [angular-ui/ui-grid#5725]
Hi Team,
I have a requirement to do 2 different actions when we 
1. Select a record by clicking on checkbox &
2. Select a record by clicking on the row.
I need to perform 2 different actions for these 2 scenarios.
So, I need to 2 different events to fired for these 2 scenarios.
We can have an option to enable or disable this feature in gridOptions.

**Business Case Scenario to support this feature:**

We have a scenario where the parent record will be treated as selected and added to the selected records list only when one or more rows of the child grid gets selected.

We have a parent grid, when the row is selected from it, we need to load the child grid. But it should never select the checkbox.
When the rows of the child grid gets selected then the parent grid row's checkbox needs be marked as selected and it has to be added to the selected records list.

Here, selection by row is always used to load the child grid data.
However the selections made on the checkbox will be actually treated as records selected for processing.

Please reply if you need more clarity on this feature.

I can contribute to implement this feature and create a Pull Request.

**Comment by mblodorn** [comment]
+ 1

**Comment by darlandemarco** [comment]
Great Yesudas! 

It will help us a lot!
