### ISSUE TITLE
Issue with Angular UI grid - expandable all rows (Sub grids)

### ISSUE THREAD

**Issue by shettyabhishek** [angular-ui/ui-grid#5731]
I have a grid that has expandable rows and each row when expanded shows a sub grid. But the rendering of the sub grids is taking too much of time, even when there are only 50 rows and when i execute expand all rows.  The page kind of gets a hanged for  a few seconds 
Using the method  ::: **$scope.gridApi.expandable.toggleAllRows();**

My understanding is some of the sub-grid columns are having cell templates, which is causing the excess rendering time.

Any suggestion or some pseudo code would b really helpful .

**Comment by alwinjmjak** [comment]
Hi shetty need some suggestion on expandable functionality.So I'm unable to provide any grid options to my subgrid. Please refer https://github.com/angular-ui/ui-grid/issues/5735

**Comment by Mohana-Lakshmi** [comment]
@shettyabhishek : please check the below plunker : 

**use the below in your code and try . Also we need to add    enableExpandAll: true in grid options.**

 $scope.gridApi.grid.registerDataChangeCallback(function () {
                        $scope.gridApi.treeBase.expandAllRows()
 });

**Refer to this plunker** : http://plnkr.co/edit/myDUiu7cdrGopQgn7t2p?p=preview

**Comment by shettyabhishek** [comment]
Hi Lakshmi, 
   The issue was not about just expanding the rows, but when we add templates for the sub grids and try doing expand all, the screen would hang for a long time. How ever as of now we change the screen look and feel and the design. Thanks a lot for your suggestions and take care
