### ISSUE TITLE
Documentation: Incorrect href on API page

### ISSUE THREAD

**Issue by davgibbs** [angular-ui/ui-grid#5743]
Hi,

On the web page: "http://ui-grid.info/docs/#/api", clicking on the "UI grid" logo in the top left of the page leads to a localhost URL, which is not on the "ui-grid.info" site.

From viewing page source, the html is:
<a  href="http://127.0.0.1:9003"  class="navbar-brand">UI Grid</a>

I think this should be updated to direct the visitor to the home page of the UI Grid documentation web page.

**Comment by mportuga** [comment]
This issue is no longer reproducible.
