### ISSUE TITLE
Unable to use ui.grid.cellNav with custom cell template

### ISSUE THREAD

**Issue by sriramramaswami** [angular-ui/ui-grid#5751]
Hi,

I have a angular-ui-grid(3.1.2) where I have around 80 columns, most of it are custom cell templates on which we perform specific actions and load data. I have also enabled cellNav on the grid to help navigate the grid through the keyboard.

The issue here is that the cellNav does not work on the custom cell template. It works only on the default columns which do not have a cell template. I am unable to select the custom cell template as well. For specific reasons,I have to use the cell template in this grid.

Can you please fix this issue?

Thanks, 
Sriram

**Comment by csvan** [comment]
How do you load your templates? Have you tried injecting them into $templateCache?

**Comment by mportuga** [comment]
Closing due to lack of response.
