### ISSUE TITLE
Angular UI Grid Values with extra space in between not getting searched

### ISSUE THREAD

**Issue by vsinghvi09** [angular-ui/ui-grid#5753]
when a attribute value has more then one space between the words, it is not getting searched in the inline search criteria of Angular UI grid.

Eg : UI Grid is showing "ankle jeans" which I am searching in the inline search but its not giving me results. This is because when i inspect the element I found the original string to be "ankle  jeans" (2 spaces) in the UI grid as compared to the phrase shown. And If I search with "ankle  jeans" with spaces then I am getting results.

The Angular UI grid is itself converting the extra spaces in between the data to single space which is wrong. The data should be shown as it is which has been inserted in the UI grid.

Please suggest

**Comment by pawanupr16** [comment]
I am facing Same Problem  Please provide me solution.


thanks

**Comment by pawanupr16** [comment]
I have a two Solution of this Problem 
First you need to  change the component code in ui-grid.css put
.ui-grid-cell-contents {
 white-space: pre !important; //nowrap;
}
Second is you need to override this code in your css or your project default css put this code (put same code which you have in component file only change "white-space: pre !important;" )
.ui-grid-cell-contents {
 white-space: pre !important; //nowrap;
}
 its working fine

**Comment by pawanupr16** [comment]
close this issue
