### ISSUE TITLE
Text align center for header

### ISSUE THREAD

**Issue by nidhin001** [angular-ui/ui-grid#5756]
How to give text-aligin:'center' for header.
I used this code

```
exporterPdfTableHeaderStyle : {
                    fontSize : 9,
                    bold : true,
                    text-align: "center"
                },
```

But it shows error "Invalid or unexpected token" for the hyphen

**Comment by mportuga** [comment]
Use aligment: 'center'

http://plnkr.co/edit/kuROqwNKO9S7f7uk0ram?p=preview

I found this information by reading the pdfMake docs, which is the package we use for generating PDFs:
http://pdfmake.org/#/gettingstarted

We also call that out in our API documentation:
http://ui-grid.info/docs/#/api/ui.grid.exporter.api:GridOptions
