### ISSUE TITLE
ui-grid-scrollbar-placeholder blocks half the height of last ui-grid-cell

### ISSUE THREAD

**Issue by onmyway365** [angular-ui/ui-grid#5760]
Hi all, 

I have picked up this issue on multiple browsers (Chrome, IE, Firefox). I am on v3.2.9. I have scoured the web for a solution, so I truly hope this is not a duplicate issue.

In the bottom left corner of `ui-grid` there is a `ui-grid-scrollbar-placeholder` that obscures half the last tick box/cell (image below). 

![ui-grid-scrollbar-placeholder_1](https://cloud.githubusercontent.com/assets/15213279/19560359/79e55d0e-96d4-11e6-9fdc-883d8cc7ccc6.JPG)

Here is the `<div>` markup from the developer tools:

![ui-grid-scrollbar-placeholder_markup](https://cloud.githubusercontent.com/assets/15213279/19560531/3083cb5e-96d5-11e6-822f-48abf157ae6d.JPG)

I have also noticed that one can scroll an extra couple pixels on this tick box/cell column, that throws out the alignment (image below).

![ui-grid-scrollbar-placeholder_2](https://cloud.githubusercontent.com/assets/15213279/19560430/be8b0af8-96d4-11e6-83e5-afde5391845e.JPG)

I would appreciate it if you could show me how to fix this. Thank you very much.

**Comment by shamoh19** [comment]
Any update on this issue?

**Comment by tangentlin** [comment]
Still seeing this issue in 4.0.4 of the grid

**Comment by jeffantosh** [comment]
\src\js\core\factories\GridRenderContainer.js:
`  GridRenderContainer.prototype.needsHScrollbarPlaceholder = function () {
    var bodyRenderContainerWidth = this.grid.renderContainers.body ? this.grid.renderContainers.body.canvasWidth : 0;
    var leftRenderContainerWidth = this.grid.renderContainers.left ? this.grid.renderContainers.left.canvasWidth : 0;
    var rightRenderContainerWidth = this.grid.renderContainers.right ? this.grid.renderContainers.right.canvasWidth : 0;
    var fullGridWidth = bodyRenderContainerWidth + leftRenderContainerWidth + rightRenderContainerWidth;
    return this.grid.options.enableHorizontalScrollbar && !this.hasHScrollbar && !this.grid.disableScrolling && (fullGridWidth > this.grid.gridWidth);
  };`

**Comment by jeffantosh** [comment]
https://github.com/angular-ui/ui-grid/pull/6244/

**Comment by jeffantosh** [comment]
PR submitted https://github.com/angular-ui/ui-grid/pull/6244

**Comment by jeffantosh** [comment]
Upgraded to 4.4.4 and the issue still persists.

**Comment by mportuga** [comment]
hmm, what I find interesting is that in your screenshot, the scrollbar appears to take the full length of the grid, not just the "unpinned" portion. Have you customized CSS in some way?

**Comment by Taehyun-Ha** [comment]
$(".ui-grid-viewport").height($(".ui-grid-viewport").height()+17);
