### ISSUE TITLE
href tag created Usafe: in front

### ISSUE THREAD

**Issue by vijayalaya** [angular-ui/ui-grid#5763]
I have built an anchor tag dynamically in UIgrid using the cell template option. Am getting unsafe:javascript in front of the href attribute value in the anchor tag and it inhibits the redirection. when i checked online there are suggestion touse $compileProvider but when i add that to the angular.module("app") angular is not working properly in the page. Please help or guide me how i can fix this. my angular version is v1.5.8. Appreciate your help on this

My code:

  var linkCellTemplate = '<div class="ngCellText" ng-class="col.colIndex()">' +
                   '  <a class="text-blue-color text-underline" href="javascript:viewCPClaim(\'{{row.entity.TagNumber}}\')">{{row.entity.TagNumber}}</a>' +
                   '</div>';

var controllerId = 'UnitTracking';
angular.module("app").controller(controllerId, ['$scope', '$window', 'datacontext', 'config', 'spinner', UnitTracking]);
function UnitTracking($scope, $window, datacontext, config, spinner) {

```
$scope.init = function () {

}
```

Thanks
Vijay

**Comment by vijayalaya** [comment]
I have tried the onclick attribute of the anchor tag . Its triggering but the problem is the expression (\'{{row.entity.TagNumber}}\') is not rendering and giving the value.

    var linkCellTemplate = '<div class="ngCellText" ng-class="col.colIndex()">' +
                   '  <a  class="text-blue-color text-underline" onclick="javascript:viewCPClaim(\'{{row.entity.TagNumber}}\');">{{row.entity.TagNumber}}</a>' +
                   '</div>';

when i use ng-click, the click event is not triggering but the expression(\'{{row.entity.TagNumber}}\')   is givng the value. Any help is appreciated.

**Comment by vijayalaya** [comment]
I tried href and the below code, but it did have the unsafe:javascript infront of the javascript function.
  angular.module("app").config(['$compileProvider', function ($compileProvider) {
        $compileProvider.aHrefSanitizationWhitelist(/^\s*(javascript‌​):/);
    }]);

**Comment by mportuga** [comment]
Can you provide a plunker?

**Comment by mportuga** [comment]
Closing due to lack of response.
