### ISSUE TITLE
UI-GRID-PAGINATION

### ISSUE THREAD

**Issue by atatchin** [angular-ui/ui-grid#5768]
![image](https://cloud.githubusercontent.com/assets/14190788/19689272/6ee2ad6e-9a92-11e6-939b-e2ac3dfd3526.png)

I implemented the ui-grid-pagination directive, but looks like per supplied image all the pagination elements are oversized and displayed on the new line probably as a result. How do I overcome this issue and style it properly?

**Comment by leonardlabuneti** [comment]
It looks like your css page overwrite the pagination buttons's style.
In the example here 
http://ui-grid.info/docs/#/tutorial/214_pagination
the buttons look ok with the ui-grid css, maybe you should double check

**Comment by atatchin** [comment]
I was able to fix it with following styles:
   .ui-grid-pager-last{
       width: 35px;
   }
   .ui-grid-pager-next{
       width: 35px;
   }
   .ui-grid-pager-first{
       width: 35px;
   }
   .ui-grid-pager-previous{
       width: 35px;
   }
