### ISSUE TITLE
Editable row on selected item

### ISSUE THREAD

**Issue by kamalpatel125** [angular-ui/ui-grid#577]
Hi, 
Is it possible to have custom column with button "Edit" and click on "edit", whole row becomes the editable ? Currently It does on double click the cell but i would like to make whole row editable.
Thanks for any help !
Thanks 
Kamal Patel.

**Comment by poojanc** [comment]
Hi Kamal,
I am also looking for editable row on click of an "edit" button in a row. Any help is highly appreciable
Thanks,
