### ISSUE TITLE
F2 edit mode not works well in firefox, can test

### ISSUE THREAD

**Issue by calhemp** [angular-ui/ui-grid#5770]
this is my test
https://github.com/angular-ui/ui-grid/issues/5582

**Comment by DespotMagic** [comment]
Strange character on F2 (windows 10, Firefox 54.0.1)

[https://plnkr.co/edit/q85dduSXEz6OAxsxd1ea?p=preview](https://plnkr.co/edit/q85dduSXEz6OAxsxd1ea?p=preview)
![image](https://user-images.githubusercontent.com/18666511/29778847-c7a5c590-8c21-11e7-8aac-6e2be6acae5e.png)

**Reason:**
Firefox handling keypress event for function key. Then uiGridCellnav rise 'viewPortKeyPress' event with  property which=0.
In uiGridEditor directive:
`ngModel.$setViewValue(String.fromCharCode( typeof evt.which === 'number' ? evt.which : evt.keyCode), evt);`
**which = 0** and "String.fromCharCode(**0**)" returns this strange character.
