### ISSUE TITLE
Exception thrown editing a string containing a space using flatEntityAccess

### ISSUE THREAD

**Issue by MattOakley** [angular-ui/ui-grid#5773]
We get the issue if the value is set through the underlying model (rather than through the grid directly) to a string containing a space and then click in the cell to edit.

When `getCellDisplayValue` is called `col.cellDisplayGetterCache = $parse(row.entity[col.field] + custom_filter);` throws an exception if the string has a space.

This can be fixed by simply wrapping the expression in quotes:

```
 col.cellDisplayGetterCache = $parse("'" + row.entity[col.field] + "'" + custom_filter);
```

There was a [pr](https://github.com/angular-ui/ui-grid/pull/5426) raised in May for the same issue (I think) - but wasn't merged

**Comment by JZehet** [comment]
+1

**Comment by MichalJakubeczy** [comment]
+1 for fixing this

**Comment by MatejQ** [comment]
+2 :)
(we are having the same issue)
