### ISSUE TITLE
Boolean Editable Not Working on Firefox

### ISSUE THREAD

**Issue by jcq** [angular-ui/ui-grid#5780]
There appears to be an issue with the boolean type of editable control when used with Firefox (at least on versions 48.x and 49.x). You can see the issue on [the tutorial page for the edit feature](http://ui-grid.info/docs/#/tutorial/201_editable).

If one attempts to edit the "active" column, it will display the checkbox, but will lose focus and switch out of edit mode when one attempts a mouse click on the control. It does work if one toggles the checkbox with the keyboard (space bar).

**Comment by farooqu** [comment]
If this is occurring on macOS then fix #5771 should fix it.

**Comment by jcq** [comment]
That's good news — this was indeed on macOS.
