### ISSUE TITLE
gridApi.pagination Issue

### ISSUE THREAD

**Issue by McMounir** [angular-ui/ui-grid#5804]
Hey! 

I have an issue with **gridApi.pagination.seek(N)** and **gridApi.pagination.getTotalPages()** not working for me after switching from OData V3 to Odata V4 !! but i dont see any relation between OData And GridOption !!!

Insterad of that **gridApi.pagination.previousPage()** and **gridApi.pagination.nextPage()** still working very well.

Any help please, thank you.

**Comment by Gajendrasinh** [comment]
Hi

i have same issue with Grid with native pagination controls i want to pass pagination size.

can you help me for that?

**Comment by McMounir** [comment]
yes the problem was not with the nggrid! the problem was with how to get the count in ODataV4.
 
Instead of using "data["odata.count"]" use "data["@odata.count"]", i hope i can help you
