### ISSUE TITLE
ui-grid fonts not displaying properly

### ISSUE THREAD

**Issue by barttt** [angular-ui/ui-grid#5806]
This is in an angular meteor application. 
I installed using 'meteor npm install --save ui-grid'. 
The install went without errors. 
I copied the simple example into my page and get a grid display as expected, except for the often quoted '**chinese fonts in the header**' where some control font should be displayed.

It appears that the font got loaded, but is not useable by the browser. Chrome gives "Failed to decode downloaded font" and FF gives "downloadable font: rejected by sanitizer" for each of ui-grid.ttf and ui-grid.woff

I have read at least 25 different reports of others having the same issue. Not a single one addressed meteor, so no existing solution seems to apply (or at least I could not figure out how). I am reaching out here in the hope that someone has solved this issue, or can point me to more info.

I consider this a bug as it should have just worked as this has been known for some time.. 
Perhaps someone who knows the bits and pieces better than I can do a test install on a meteor app and render a fix.

**Comment by mportuga** [comment]
This should have been resolved in the latest version of UI-Grid. Please upgrade and retest. Also, our npm package is called angular-ui-grid. Perhaps that is part of the issue.

**Comment by mgrivera** [comment]
Hi, I know this is a closed and very old thread. 
I was also suffering this very same issue. My ui-grid was working until I upgraded it to latest version (4.6.6). Then this issue just appeared. 
I found that creating a _fonts_ sub directory in _public_ and coping the four font files there fixed everything. 
Maybe you have to (hard) reload your browser, though. 
Thanks and bye ...
