### ISSUE TITLE
Has 4.0.0 been released

### ISSUE THREAD

**Issue by samsfisher** [angular-ui/ui-grid#5810]
Just confused whether 4.0.0 has been released? ui-grid.info shows that it has been released??

![image](https://cloud.githubusercontent.com/assets/1946299/20268874/841d0e0e-aa46-11e6-82fc-5c4f3580c532.png)

**Comment by nvivo** [comment]
Same question here. The releases page doesn't show this version. Looks like it's missing a tag.

**Comment by jozsefr** [comment]
PR https://github.com/angular-ui/ui-grid/pull/5086 suggests v4.0.0 is ready?!
The latest tag on Github is 3.2.1, npm has 3.2.7 and 3.2.9 published, but there is no version 4.0.0.
Publishing it could close https://github.com/angular-ui/ui-grid/issues/5570 https://github.com/angular-ui/ui-grid/issues/5596

**Comment by mportuga** [comment]
Nope, it has not, there was some glitch in our grunt tasks that caused that issue. We will be launching 4.0.0 for real in the near future and resolving it.

**Comment by csvan** [comment]
It's out now, so I guess this can be closed: https://github.com/angular-ui/ui-grid/commit/8732590633ebf9af9025f9562ed2e9bbe597468f
