### ISSUE TITLE
v4 not available on npm registry

### ISSUE THREAD

**Issue by mscheker** [angular-ui/ui-grid#5819]
Hi,

Your site, http://ui-grid.info/, has a notice of v4.0.0 been released already but the npm registry downloads v3.2.9. Any ideas as to how can I get the latest version of the component?

Doing an integration with AngularJS v1.5.8.

Thank you in advance for your assistance.

**Comment by mscheker** [comment]
@dhodgin Thanks for your feedback. I used it before as well and liked it. Other options out there don't seem to be as solid as this one. Hoping they can provide an update.

**Comment by csvan** [comment]
It's out now, so I guess this can be closed: https://github.com/angular-ui/ui-grid/commit/8732590633ebf9af9025f9562ed2e9bbe597468f

**Comment by mscheker** [comment]
@csvan Thanks for the notification!

**Comment by aplocher** [comment]
Am I missing something?  This Issue was submitted 5 months ago and closed, but NPM shows version 3.2.11 as the latest for me.  Is this the right package?

https://www.npmjs.com/package/angular-ui-grid

npm install angular-ui-grid@latest --save
...
`-- angular-ui-grid@3.2.11
