### ISSUE TITLE
AngularJS - ngGrid does not allow columns name with "(" and ")" sign. Example : Column :- Name ($)

### ISSUE THREAD

**Issue by pawanupr16** [angular-ui/ui-grid#5824]
Grid UI Table has column name with "(" or ")" or "(" ")" then the column does not return data, it return with empty data but when we remove "(" ")" then the column returns original data.

http://plnkr.co/edit/DouHrm?p=preview

this table Edit column name and add ($) sign with column name like - city($) then see

-If the attribute has brackets than the data is not coming in the columns "Brand ($)"
-If we remove brackets than the data is returning like "Brand $"

Is their any solution for angular datatable to avoid the "(" and ")" or ($).

Please help us to resolve.

**Comment by cybermerlin** [comment]
use up to 3.0

n

```json
   {
      "name": "some caption column (city)",
      "field": "city"
   }
```

**Comment by mportuga** [comment]
ng-grid is no longer being supported. I recommend you update to ui-grid.
