### ISSUE TITLE
Double click on column separator to auto-fit column is not working properly  

### ISSUE THREAD

**Issue by VipRepo** [angular-ui/ui-grid#5839]
Hi,

This issue happens if text width in column is greater then minWidth of that column. if we double click on column separator then column get auto-fit to little less then largest text in column. So every time largest text is truncating in column.

Plunker: http://plnkr.co/edit/Ck1xz35XvgxVs33ZCG17?p=preview

Steps to reproduce:
Double click on column separator of 'Name' column, then you can see largest text which is 'Schroeder Mathews' is truncating.

Any work around would also be helpful.

**Comment by derekm** [comment]
I'd be interested in helping to fix this. Also ColumnDef `width="*"` appears to be broken and does not result in the same column widths as double-clicking all column separators.

**Comment by derekm** [comment]
@PaulL1 -- If you could give some tips on where to look for this one, I'd be interested in tackling it!

**Comment by mportuga** [comment]
Cannot reproduce.
