### ISSUE TITLE
how add custom html to row 

### ISSUE THREAD

**Issue by mathewsk** [angular-ui/ui-grid#587]
Hi,

Please see the picture below on what I'm trying to implement using ng-grid.....
Basically, I want an expandable html section to be shown when the "expand" button is clicked. I need the expanded html to be shown within the grid itself  (not outside the grid boundaries and not as a popup). 

![image](https://f.cloud.github.com/assets/4730582/851545/f374ea68-f49d-11e2-874e-63041f239b89.png)

I looked at rowTemplate thinking I would be able to plugin my own html in there...but don't see how that can be done.
Is  something like this possible with ng-grid..
Could you please point me to any ideas or plunkrs ?

Thanks!
Mat

**Comment by ParthasarathyK** [comment]
Is this issue closed? I have similar requirement in my project.
