### ISSUE TITLE
Issues cleanup

### ISSUE THREAD

**Issue by csvan** [angular-ui/ui-grid#5883]
There are currently 1000+ open issues, but a lot of these seem to simply be questions which either belong on SO or are already addressed in the documentation. 

While it certainly is a bit of work, I think it would clean the project scope a bit to go through the issue list and cut out the slack.

**Comment by mportuga** [comment]
We are meaning to do that as our next step in fact. For the launch of 4.0.0 we went through the PRs and either merged or closed all of them, with the exception of a couple that appear to still be active/recent. We will try to do the same with issues, but that will take a bit to go through.
