### ISSUE TITLE
nuget package for 4.0.0

### ISSUE THREAD

**Issue by MatejQ** [angular-ui/ui-grid#5888]
Hello,
as 4.0.0 is now out, it would be helpful to have it released also on nuget (there is currently 3.2.9 as latest).
Thank you.

**Comment by mportuga** [comment]
As far as I am aware, we do not officially support nuget. We are actively maintaining both [NPM](https://www.npmjs.com/package/angular-ui-grid) and [bower](https://bower.io/search/). Nuget, appears to be maintained by someone outside of the ui-grid team. As such, I will close this issue.
