### ISSUE TITLE
Angular 1.6 - Possibly unhandled rejection: canceled

### ISSUE THREAD

**Issue by achenxp** [angular-ui/ui-grid#5890]
Click on column header to sort data and it throws "Possibly unhandled rejection: canceled" error under Angular 1.6.

http://plnkr.co/edit/bXEXwcvHz1dK655nHpeT?p=preview

**Comment by mportuga** [comment]
angular 1.6 is currently not supported by UI-Grid, but thank you for the information

**Comment by vincent-ollivier-everysens** [comment]
+1 
Error throws immediatly at load with Angular 1.6

**Comment by sebastian-zarzycki-es** [comment]
This is a result of timeout.cancel (about 8 times in code). UI-Grid creates own promise with .then(), right after defining the cancel. This is the main offender, but there are others:

```
 Grid.prototype.queueRefresh = function queueRefresh() {
                    var self = this;

                    if (self.refreshCanceller) {
                        $timeout.cancel(self.refreshCanceller);
                    }

                    self.refreshCanceller = $timeout(function () {
                        self.refreshCanvas(true);
                    });

                    self.refreshCanceller.then(function () {
                        self.refreshCanceller = null;
                    });

                    return self.refreshCanceller;
                };
```
simple change to the then part to
```
self.refreshCanceller.then(function () {
                        self.refreshCanceller = null;
                    }, angular.noop)
```

**Comment by paambaati** [comment]
For anyone that wants a workaround (not recommended, though), you can globally silence unhandled promise rejections like this —

```
app.config(['$qProvider', function ($qProvider) {
    $qProvider.errorOnUnhandledRejections(false);
}]);
```

**Comment by dominusbelial** [comment]
sebastian-zarzycki-es solution prevents the "Possibly unhandled rejection: canceled" error but the offending code should be rewritten to prevent hiding possible errors.

**Comment by sebastian-zarzycki-es** [comment]
Can $timeout.cancel ever throw an error?

**Comment by Nickproger** [comment]
+1
Same problem... Waiting for it...

**Comment by ivorobkalo** [comment]
+1
the same

**Comment by dominusbelial** [comment]
not sure about that sebastian but angular 1.6.0 conforms to promises/a+ so proper handling should look like you suggested $promise.then(() => {},angular.noop) or $promise.then().catch() else we get the "Possibly unhandled rejection: canceled", notice you should prefer the latter as 1.6.0 migration suggest... more in "Note" section at [https://docs.angularjs.org/guide/migration#migrate1.5to1.6-ng-services-$http](url)

**Comment by sebastian-zarzycki-es** [comment]
Yes, I agree. All I'm saying is that the error response will probably never trigger anyway in this case, so angular.noop will do just fine. But, yeah, using proper then().catch() is better, even if catch would be empty.

**Comment by valdirviana** [comment]
+1
Same problem with ui-grid

**Comment by mkjois** [comment]
I tried using the `$qProvider.errorOnUnhandledRejections(false)` config on just the module that encapsulates my ui-grid, but it turns out that providers are singletons and this affects all of my modules that use `$q`.

Is there a way to have the one module use a sort of "separate `$q`" where I could ignore the unhandled rejections in that module only? Or any better workarounds?

**Comment by mkjois** [comment]
@sebastian-zarzycki-es Could you point out where in the code you found that block? I might have to tackle this myself

**Comment by sebastian-zarzycki-es** [comment]
Just search for $timeout.cancel and look for any .then() connected to them in near, as they create new promise, that has to handle the error part with catch.

**Comment by bostondevin** [comment]
+1 support angular 1.6

**Comment by dominusbelial** [comment]
using sebastian-zarzycki-es solution i have added ".catch(angular.noop)" to all the offending promises on the latest 4.0.2 uigrid for angular 1.6.1... all features are working for my implementation and not getting the Possibly unhandled rejection: canceled...
[ui-grid.zip](https://github.com/angular-ui/ui-grid/files/681279/ui-grid.zip)

**Comment by mkjois** [comment]
@dominusbelial Do you happen to have your fix on a GitHub repo?

**Comment by mportuga** [comment]
We are willing to accepts pull requests for this fix

**Comment by cybermerlin** [comment]
in [branch](https://github.com/cybermerlin/ui-grid/tree/develop) i fixed this trouble

**Comment by jasonwr** [comment]
@cybermerlin I just tested out the window.setTimeout from your branch and the problem still remains when I click on a column header to sort by column.

**Comment by dominusbelial** [comment]
forked and updated in [my branch](https://github.com/dominusbelial/ui-grid/)

**Comment by mattbrunetti** [comment]
@dominusbelial Put in a PR? :smile:

**Comment by dominusbelial** [comment]
@mattbrunetti will do, this is my first time!

**Comment by Sheeryada** [comment]
+1

**Comment by l8nites** [comment]
+1

**Comment by takotuesday** [comment]
+1

**Comment by DoubleDot** [comment]
+1

**Comment by mesosteros** [comment]
+1 Really need this fixed soon because it's a pain to test the grid filtering with it showing constantly as the user types.

**Comment by mattbrunetti** [comment]
@mesosteros You can have your custom `$exceptionHandler` ([see documentation](https://docs.angularjs.org/api/ng/service/$exceptionHandler)) ignore this and any other errors you know about and just want to silence...

```
export default function $exceptionHandlerFactory (errorHandler, $log) {
  'ngInject'
  // TODO: root out all of these ignored exceptions
  const ignorePatterns = [
    // For ui-router redirect while initializing - https://github.com/angular-ui/ui-router/issues/2977
    /^Possibly unhandled rejection: {"type":2,"message":"The transition has been superseded by a different transition"/,

    // For ui-grid /w angularjs 1.6 - https://github.com/angular-ui/ui-grid/issues/5890
    /^Possibly unhandled rejection: canceled$/,
    /^Possibly unhandled rejection: not-element$/,
  ]
  return function exceptionHandler (exception, cause) {
    if (ignorePatterns.some(pattern => pattern.test(exception))) {
      return
    }
    errorHandler.reportError(exception)
    $log.info('\tCause: ' + cause) // TODO: Include this in error report
  }
}
```

I'm not sure about everyone else, but aside from the errors being thrown I haven't noticed any actual defect. Has anyone? (Regardless, the errors are troubling to our developer minds and should be fixed)

**Comment by mesosteros** [comment]
@mattbrunetti Yeah I already tested with that and although it works it possibly silences other errors and that is a big no-no for me. But as long as it is updated by March (or preferably next week) its fine for now.

**Comment by mattbrunetti** [comment]
@mesosteros Good point. Maybe we could inspect `error.stack` to only silence errors with that message if it's coming from ui-grid? Of course this is an async error so it would only work if you have long stack traces ([using Bluebird](http://bluebirdjs.com/docs/api/promise.longstacktraces.html) or similar).

I know it's not relevant to the ultimate solution of this issue, but it may be a good generic design pattern for a stop-gap for errors that aren't causing issues besides the noise. I think I'll try it (and possibly uncover some errors I accidentally silenced).

**Comment by dominusbelial** [comment]
code as is would silence exceptions on angular 1.6.x anyway, there is a need for a catch section for some promises, perhaps without the angular.noop call, maybe something simple as console.log(err) ???

**Comment by Oceanswave** [comment]
+1

**Comment by akshay2685** [comment]
+1

**Comment by AnAndrey** [comment]
+1

**Comment by AnAndrey** [comment]
+1

**Comment by bmsdave** [comment]
+1

**Comment by jmbryan22** [comment]
+1

**Comment by hieudo** [comment]
+1

**Comment by homer2** [comment]
+1

**Comment by fr0wsTyl** [comment]
+1

**Comment by ridvanc** [comment]
+1

**Comment by ivorobkalo** [comment]
+1

**Comment by Nickproger** [comment]
Still waiting for it... :) It's the last think that block as to switch to Angular1.6...

**Comment by mattbrunetti** [comment]
PR #5949 has been merged to address this issue

**Comment by mesosteros** [comment]
@mattbrunetti I've updated everything and it still shows...

**Comment by ivorobkalo** [comment]
@mesosteros It seems package version was not updated so if You just used update - no updates were delivered

**Comment by ivorobkalo** [comment]
Any news when new version will be rolled out?

**Comment by valenburm** [comment]
+1

**Comment by masterOL** [comment]
+1

**Comment by hendriklammers** [comment]
+1

**Comment by YahiaDev** [comment]
+1

**Comment by YahiaDev** [comment]
Any news about the new version ?

**Comment by derekm** [comment]
The proposed fix is quite a hack. It fixes one NPE and then tacks a bunch of empty `.catch()`s onto everything. Seems like a silly thing for Angular 1.6 to impose on projects.

**Comment by mattbrunetti** [comment]
I agree with @derekm.. the proposed fix seems pretty wrong. There must be a solution that doesn't simply swallow all unhandled rejections, which is pretty reckless.

**Comment by sebastian-zarzycki-es** [comment]
Whoa, these comments. Does anyone even know how Angular works?

Angular's $timeout returns promise and all they did was just add a warning to all promises that do not have both results handled. In case of $timeout this is just redundant, because $timeout itself cannot ever result with an error and if you cancel it manually, you care even less. Take a look at Angular's $timeout.cancel implementation:

```
 timeout.cancel = function(promise) {
      if (promise && promise.$$timeoutId in deferreds) {
        // Timeout cancels should not report an unhandled promise.
        deferreds[promise.$$timeoutId].promise.catch(noop);
        deferreds[promise.$$timeoutId].reject('canceled');
        delete deferreds[promise.$$timeoutId];
        return $browser.defer.cancel(promise.$$timeoutId);
      }
      return false;
    };
```

Does that comment ring any bell?

**Comment by dgsmith2** [comment]
I fear this is going to turn into a flame war, but I personally DO agree with the changes.  

By supplying a ```.then(handleTheGood)``` you are implicitly supplying a ```.noop``` rejection callback.  Angular 1.6 now encourages developers to be explicit in handling either outcome of a promise.  In 1.6 if a promise you expected to _always_ resolve for some reason didn't you get information (i.e., error message in the console) about an unhandled rejection that you should obviously be handling.  

Also, if you are coding promises according to spec, you aren't using the ```.finally``` that ```$q``` provides and therefore already handling rejections explicitly, even if they are simply a ```.noop``` to achieve a "finally".  (```.then(handleTheGood, handleTheBad).then(handleRegardless)``` or ```.then(handleTheGood).catch(handleTheBad).then(handleRegardless```, with both assuming your ```handleTheBad``` doesn't return a rejected promise)

**Comment by Oceanswave** [comment]
> Angular now warns us when there's an unhandled rejection, we don't want to shut that off globally, but we also don't like the solution that suppresses unhandled rejections in non-handled cases that are not able to be controlled.

wut?

**Comment by niveditapatil** [comment]
Any idea about when is ui-grid planning to support Angular JS 1.6 version?

**Comment by DoubleDot** [comment]
Any update on this?

**Comment by alinleonard** [comment]
+ 1

**Comment by MatejQ** [comment]
I don't know whether ui-grid already handles these cases but if not, you can configure angular to ignore unhandled promise rejections (reverting to pre-1.6.0 behavior).
(typescript code following)

>             App.AppModule.config([
>                 "$qProvider",
>                 ($qProvider: any) => { // Q Provider is not part of .d.ts for some reason
>                     // suppress angular errors about unhandled promise rejections since 1.6.0
>                     $qProvider.errorOnUnhandledRejections(false);
>                 }
>             ]);

**Comment by adrienplg** [comment]
+1

**Comment by SensationSama** [comment]
See https://github.com/angular-ui/ui-router/issues/3246

**Comment by 7urkm3n** [comment]
+1

**Comment by GokuSSL5** [comment]
I get the same error running the ui-grid for the first time using Angular 1.6.4.
What's the recommendation to work around it? Revert to an earlier version of Angular?

**Comment by mohanrao** [comment]
+1

**Comment by jasonwr** [comment]
+1

**Comment by Vaelyr** [comment]
+1

**Comment by michelj90** [comment]
+1

**Comment by doracl** [comment]
+1

**Comment by jspencersharpe** [comment]
+1

**Comment by raphaelconstantino** [comment]
+1

**Comment by pwdl** [comment]
+1

**Comment by kyleThayerXpanxion** [comment]
+1!!

**Comment by ozairsajid** [comment]
+1

**Comment by cybermerlin** [comment]
fixed this trouble in

https://github.com/cybermerlin/ui-grid/tree/develop

**Comment by GlennHogent** [comment]
+1

**Comment by besil** [comment]
+1
