### ISSUE TITLE
Ui-grid Reports ( best solution? ) 

### ISSUE THREAD

**Issue by kabom** [angular-ui/ui-grid#5893]
Hey, 
i'm trying to get this state ( picture ) but i don't know the best way to get there. 
What is the expected result: pucture. ( or , if there is more items with same id ( there must be one item from that same group with NO lot ). that item ( if tree view need to be leed to the tree ).
and i want to calculate total for Articles with + without lots ( where withhout lot is leader of node ) 
and if there is same ArticleTypeName ( same id type ), to make sum of that also ( to add extra columns with that total values like on screen if possible. Please give me some instruction for best way to do that. in plunker  ( http://plnkr.co/edit/yh9UtgqjKATozjxNl7uQ?p=preview ) is the data i need to sort, and in picture are expected results. Thank you!! cheers
![screenshot_5](https://cloud.githubusercontent.com/assets/4138592/21224744/eb4d3136-c2cd-11e6-9936-598c2767ba66.png)

**Comment by csvan** [comment]
This issue tracker is not for asking questions, please use Gitter or a forum for that.

**Comment by mportuga** [comment]
@kabom This is the closest that I was able to get you for now:

http://plnkr.co/edit/YRxrBDqRJB827ylKeR6q?p=preview

Hope that helps a little.
