### ISSUE TITLE
Font location not configurable

### ISSUE THREAD

**Issue by derekm** [angular-ui/ui-grid#5899]
ui-grid requires its font be placed alongside its stylesheet. A build process that integrates ui-grid cannot conventionally put the ui-grid stylesheet in a `styles` folder and the ui-grid font in a `fonts` folder.

ui-grid fonts are in the "main" section of ui-grid's bower file. Bower package spec says image and font files are not "main" files: https://github.com/bower/spec/blob/master/json.md

**Comment by dlgski** [comment]
Can you assist with a PR to fix this?

**Comment by derekm** [comment]
Sorry for the late reply, @dlgski! I sure would like to!

**Comment by mportuga** [comment]
This was already done as part of this commit:
https://github.com/angular-ui/ui-grid/commit/352ea3d12d06bf760a83fbb33ecb8cb1e9e01481
