### ISSUE TITLE
Printed UI Grid

### ISSUE THREAD

**Issue by jdelgreco** [angular-ui/ui-grid#5903]
Please forgive me if this is covered elsewhere, and I'm simply not seeing it. My issue isn't with print styles, but with the markup present in the DOM. More accurately, my problem pertains to the lack of markup in the DOM. It looks like UI Grid does a very neat trick to save memory by not cluttering up the DOM with more rows than can be displayed at at time. The problem with this is that when a user tries to print the page, that rows scrolled out of view, are absent from the DOM altogether. I didn't see anything in your API documentation about printing. Can you recommend any particular course of action? Currently my solution is to build a hidden (redundant and non-interactive) table in the DOM, purely for the purpose of printing. It's mostly working, but feels like a hacky solution. Any advice would be great.

**Comment by archirex** [comment]
I would recommend exporting your grid with this: http://ui-grid.info/docs/#/tutorial/206_exporting_data
unless it needs to be seen together with something else on your page.

**Comment by jdelgreco** [comment]
Thanks for the suggestion. The problem is that our users want to be able to simply print the page, and see the same representation of the data on it. My redundant hidden table is doing the trick pretty well, except for one particular use case wherein we have nested directives rendering various bar charts of rolled up aggregate data. I'm not sure how to make my "print-table" directive do the same trick as UI-Grid rolling up those grouped rows, and displaying and compiling the child directives.

**Comment by mportuga** [comment]
I am not sure I have a good solution for you. I can look into a way to change the grid settings to expose all data at once on the print page for you, but that will certain have a horrible performance impact on your work. It is probably best for you to keep your current approach of force your users to use some other method for printing, such as exporting your grid.
