### ISSUE TITLE
Demo bug: Data outside of grid

### ISSUE THREAD

**Issue by TLKG** [angular-ui/ui-grid#5904]
Followed exactly as [demo](http://ui-grid.info/docs/#/tutorial/101_intro), using 

- Visual Studio 2015 Community w Update 1.
- Empty ASP web project.
- NuGet installed latest ui-grid - v3.2.9 - 2016-09-21.
- Combined .js and .html into a local.html
![ui-gridbug](https://cloud.githubusercontent.com/assets/22269729/21338830/9d8158a6-c62e-11e6-9338-7ae815d1333e.JPG)

Index.html:
```
<!doctype html>
<html ng-app="app">
<head>
    <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular-touch.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular-animate.js"></script>
    <script src="http://ui-grid.info/docs/grunt-scripts/csv.js"></script>
    <script src="http://ui-grid.info/docs/grunt-scripts/pdfmake.js"></script>
    <script src="http://ui-grid.info/docs/grunt-scripts/vfs_fonts.js"></script>
    <script src="/Scripts/ui-grid.js"></script>
    <script src="/Content/ui-grid.css"></script>

    <style>
        .grid {  width: 500px;  height: 250px;}
    </style>

    <script>
        var app = angular.module('app', ['ngTouch', 'ui.grid']);

        app.controller('MainCtrl', ['$scope', function ($scope) {

            $scope.myData = [
              {
                  "firstName": "Cox",
                  "lastName": "Carney",
                  "company": "Enormo",
                  "employed": true
              },
              {
                  "firstName": "Lorraine",
                  "lastName": "Wise",
                  "company": "Comveyer",
                  "employed": false
              },
              {
                  "firstName": "Nancy",
                  "lastName": "Waters",
                  "company": "Fuelton",
                  "employed": false
              }
            ];
        }]);
    </script>
</head>
<body>
    <div ng-controller="MainCtrl">
        <div id="grid1" ui-grid="{ data: myData }" class="grid"></div>
    </div>
</body>
</html>


```

**Comment by mportuga** [comment]
It looks like your CSS is not loading. What does your console show?

**Comment by TLKG** [comment]
Good point, here is what it complains about

On Dec 21, 2016, at 06:57 PM, Marcelo Sauerbrunn Portugal <notifications@github.com> wrote:

It looks like your CSS is not loading. What does your console show?

**Comment by hardeepsingh52** [comment]
Data is placed outside of grid 
![angulargrid](https://cloud.githubusercontent.com/assets/26478722/24033929/3c8c1a5a-0b15-11e7-9106-c2a931af42b9.png)

 <script src="Scripts/angular.js"></script>
    <script src="Scripts/angular-ui/ui-bootstrap.js"></script>
    <script src="Scripts/angular-ui-router.min.js"></script>
    <script src="Scripts/ui-grid.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular-touch.js"></script> 
    <script src="Scripts/angular-animate.js"></script>
    <script src="AngularScripts/appmain.js"></script>
<link href="Content/ui-grid.css" rel="stylesheet" />


Controller:
(function () {
    'use strict';

    angular
        .module('App')
        .controller('PartialCtrl', PartialCtrl);

    PartialCtrl.$inject = ['$location', '$scope'];

    function PartialCtrl($location, $scope) {
        /* jshint validthis:true */
        var vm = this;
        vm.title = 'PartialCtrl';

        activate();
        $scope.myData = [
  {
      "firstName": "Cox",
      "lastName": "Carney",
      "company": "Enormo",
      "employed": true
  },
  {
      "firstName": "Lorraine",
      "lastName": "Wise",
      "company": "Comveyer",
      "employed": false
  },
  {
      "firstName": "Nancy",
      "lastName": "Waters",
      "company": "Fuelton",
      "employed": false
  }
        ];
        function activate() { }
     
    }
})();


HTML 

<style>
    .grid {
    width: 500px;
    height: 250px;
  }
      </style>

<div >
    <div id="grid1" ui-grid="{ data: myData }" class="grid"></div>
</div>

**Comment by pacozevallos** [comment]
@hardeepsingh52 try changing `<!DOCTYPE html>` for `<!doctype html>` It may seem absurd but it worked for me.
