### ISSUE TITLE
Unable to re-display all hidden columns when clicking 'Clear All Filters' in grid menu

### ISSUE THREAD

**Issue by Sim12345** [angular-ui/ui-grid#5905]
link: http://plnkr.co/edit/kfVXK4oBuKqEfNoeqOWd?p=preview

The 'clear all filters' button appears when the user clicks the icon with the 3 horizontal lines, located in the top right corner of the last column.

Previously, when the user clicked the 'clear all filters' button, the filters would be cleared AND all hidden columns would be re-displayed (unhidden), but recently the hidden columns remain hidden, (unless the user manually un-hides the column by toggling the respective columns name icon in the grid menu)

Is this change in behavior intentional? Or should hidden columns be re-displayed when user clicks 'clear all filters'?

**Comment by mportuga** [comment]
This change in behavior was intentional. Clear all filters should not display hidden columns.
