### ISSUE TITLE
Functional cell templates for content based formatting

### ISSUE THREAD

**Issue by bingomanatee** [angular-ui/ui-grid#5908]
It seems to me that there is a middle ground between wanting a custom cell template and just wanting to format the text value of a field. I'd like to be able to pass a function as a cell template that takes in the cell value and returns a string that you put into the standard cell template. If I want to just mess with the displayed value, I shouldn't have to deal with the content wrapper with which I have no problem.

**Comment by mportuga** [comment]
You should use angular filters for just formatting the text value of a field.
