### ISSUE TITLE
add type = time?

### ISSUE THREAD

**Issue by sonicwong** [angular-ui/ui-grid#5909]
I read the doc and it only allow below input type:

http://ui-grid.info/docs/#/api/ui.grid.class:GridOptions.columnDef
'string','boolean','number','date','object','numberStr'

But in the HTML5 input type, there is a type='time':
http://www.w3schools.com/code/tryit.asp?filename=FAZKGA3Q1WPV

Is it possible to add type = "time" ?

**Comment by mattmutt** [comment]
Unless you are happy with the elementary and native time picker offered by the browser, you are better off trying out a custom filter.
http://stackoverflow.com/questions/31588622/angular-js-ui-grid-custom-date-filter

This will offer the best potential for dealing with specialized filter behavior and layout.

**Comment by sonicwong** [comment]
ok, thanks a lot.
