### ISSUE TITLE
Pagination: displayed items number

### ISSUE THREAD

**Issue by ezemoro** [angular-ui/ui-grid#5915]
Page size is 25. It is displaying 25 elements, but on the pagination footer it says 1 - 26 instead of 1 - 25

![image](https://cloud.githubusercontent.com/assets/2272820/21486772/47616d4c-cb99-11e6-8c35-fc7848461e94.png)
The image is from the tutorial

This is works fine in version 3.2.9, but not in 4.0.1

Thanks!

**Comment by Chikel** [comment]
Same issue here

**Comment by namitamalik13** [comment]
Facing same issue.

**Comment by abhishekguruvayya** [comment]
+1

**Comment by rbaras** [comment]
Same here. The issue started with version 4.0.0

**Comment by markkesty** [comment]
+1

**Comment by alanchavez88** [comment]
+1 is there any ETA? Maybe something I can help with?

**Comment by shuigupta** [comment]
+1

**Comment by harikrishnan-u01** [comment]
I am using v4.0.2 and this issue is still there. Is there any fix available for this?

**Comment by thiagodebona** [comment]
+1

**Comment by mportuga** [comment]
This issue has been resolved in v4.0.3

**Comment by thiagodebona** [comment]
No, it doesn't

Em 24 de mar de 2017 19:09, "Marcelo Sauerbrunn Portugal" <
notifications@github.com> escreveu:

**Comment by masudshrabon** [comment]
I think, "Pagination: displayed items number" - it's a severe bug of the library **ui-grid.min.js**.
I have solved this issue by changing the library code slightly as  following:

The **ui-grid.min.js** library code exists this wrong code: 
    `{{ 1 + paginationApi.getLastRowIndex() }}`

Just replace the above code as following:
`{{  paginationApi.getLastRowIndex() }}`

I hope this change will solve this issue.

**Comment by thiagodebona** [comment]
body { width: 100% !important; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; margin: 0; padding: 0; }
      img { outline: none; text-decoration: none; -ms-interpolation-mode: bicubic; }
      body { color: #65646a; font-family: 'Helvetica Neue', HelveticaNeue, helvetica, arial, sans-serif; }
      h1 a:active { color: #4a8db8 !important; }
      h2 a:active { color: #4a8db8 !important; }
      h3 a:active { color: #4a8db8 !important; }
      h4 a:active { color: #4a8db8 !important; }
      h5 a:active { color: #4a8db8 !important; }
      h6 a:active { color: #4a8db8 !important; }
      h1 a:visited { color: #4a8db8 !important; }
      h2 a:visited { color: #4a8db8 !important; }
      h3 a:visited { color: #4a8db8 !important; }
      h4 a:visited { color: #4a8db8 !important; }
      h5 a:visited { color: #4a8db8 !important; }
      h6 a:visited { color: #4a8db8 !important; }
      a:visited { color: #4a8db8; }
      a:hover { color: #2dbe60; text-decoration: underline; }
      .u-headingMobileAnchor a {text-decoration: none !important; color: #2dbe60 !important; pointer-events: none !important; cursor: default !important;}
      .u-bodyMobileAnchor a {text-decoration: none !important; color: #65646a !important; pointer-events: none !important; cursor: default !important;}
      .footer a:hover { text-decoration: none; }
      .footer-small a:hover { text-decoration: underline; }
      body { background-color: #f3f3f3; }
      .ExternalClass { width: 100%; }
      .ExternalClass { line-height: 100%; }
      table[id='inception'] .Btn-anchor:hover { color: #fff !important; }
      table[id='inception'] .Btn-anchor:visited { color: #fff !important; }
      @media screen and (min-width: 579px) {
        table[id="inception"] .l-inception-point { width: 578px !important; }
      }
      @media only screen and (min-device-width: 768px) and (max-device-width: 1024px) {
        table[id="inception"] a[href^="tel"] { text-decoration: none; color: #65646a; pointer-events: none; cursor: default; }
        table[id="inception"] a[href^="sms"] { text-decoration: none; color: #65646a; pointer-events: none; cursor: default; }
        .mobile-link table[id="inception"] a[href^="tel"] { text-decoration: default; color: #65646a !important; pointer-events: auto; cursor: default; }
        .mobile-link table[id="inception"] a[href^="sms"] { text-decoration: default; color: #65646a !important; pointer-events: auto; cursor: default; }
        table[id="inception"] .u-headingMobileAnchor a {text-decoration: none !important; color: #2dbe60 !important; pointer-events: none !important; cursor: default !important;}
        table[id="inception"] .u-bodyMobileAnchor a {text-decoration: none !important; color: #65646a !important; pointer-events: none !important; cursor: default !important;}
      }
      @media only screen and (max-device-width: 578px), only screen and (max-width: 578px) {
        table[id="inception"] .Branding_positive-container { padding: 14px 0 0 16px !important; }
        table[id='inception'] .Btn-anchor { display: block !important; }
        table[id='inception'] .Row_small { padding: 0 !important; }
        table[id='inception'] .Row_medium-top { padding-top: 16px !important; }
        table[id='inception'] .Avatar-img { width: 48px !important; height: 48px !important; }
        table[id="inception"] { width: 100% !important; }
        table[id="inception"] .l-outie { padding: 0px !important; }
        table[id="inception"] .l-inception-point { width: 100% !important; }
        table[id="inception"] .l-footer { width: 100% !important; }
        table[id="inception"] .l-wrap { width: 100% !important; }
        table[id="inception"] .l-full-bleed { width: 100% !important; }
        table[id="inception"] .media-obj { width: 100% !important; }
        table[id="inception"] .media-content { width: 100% !important; }
        table[id="inception"] .btn { width: 100% !important; }
        table[id="inception"] .btn td { width: 100% !important; }
        table[id="inception"] .l-inception-point { border-right: none !important; border-left: none !important; }
        table[id="inception"] .l-full-bleed img { width: 100% !important; height: auto !important; }
        table[id="inception"] .l-pad > tbody > tr > td { padding: 16px !important; }
        table[id="inception"] .l-split { width: 100% !important; }
        table[id="inception"] .l-split + .l-split { margin-top: 32px !important; }
        table[id="inception"] .ill-notebook { width: 100% !important; height: 96px !important; }
        table[id="inception"] .footer { padding-right: 16px !important; padding-left: 16px !important; }
        table[id="inception"] .btn span { display: block !important; }
        table[id="inception"] a[href^="tel"] { text-decoration: none; color: #65646a; pointer-events: none; cursor: default; }
        table[id="inception"] a[href^="sms"] { text-decoration: none; color: #65646a; pointer-events: none; cursor: default; }
        .mobile-link table[id="inception"] a[href^="tel"] { text-decoration: default; color: #4a8db8 !important; pointer-events: auto; cursor: default; }
        .mobile-link table[id="inception"] a[href^="sms"] { text-decoration: default; color: #4a8db8 !important; pointer-events: auto; cursor: default; }
        table[id="inception"] .u-headingMobileAnchor a {text-decoration: none !important; color: #2dbe60 !important; pointer-events: none !important; cursor: default !important;}
        table[id="inception"] .u-bodyMobileAnchor a {text-decoration: none !important; color: #65646a !important; pointer-events: none !important; cursor: default !important;}
        table[id="inception"] .Rule { display: none !important; }
        table[id="inception"] .l-pad { text-align: center !important; }
      }
    
  
  
    
      
        
          
            
              
                
                  
                    
                      
                        
                          
                          
                            
                              
                                
                                  
                                
                              
                            
                          
                        
                      
                    
                  
                  
                  
                    
                      
                        
                          
  
    
      

        
          
            
              

              
            

            
              
                
                  thiagodebona@gmail.com convidou você para uma conversa no Evernote.
                
              
            

            
              
            
              Aceitar convite
        
              
            
          
        
      
    
  



  
    
      
        O Evernote é o escritório moderno que você precisa. Colecione ideias e trabalhe em projetos em conjunto.
      
    
  


                        
                      
                    
                  
                  
                
                
              
            
          
          
          
            
              
                Para obter solicitações de suporte, entre em contato conosco ao acessar a nossa página de suporte.

                Este e-mail foi enviado a você pela Evernote Corporation (ou a sua subsidiária). Evernote Corporation, 305 Walnut Street, Redwood City, CA 94063, EUA.

                
                  
                    Cancelar inscrição

**Comment by thiagodebona** [comment]
body { width: 100% !important; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; margin: 0; padding: 0; }
      img { outline: none; text-decoration: none; -ms-interpolation-mode: bicubic; }
      body { color: #65646a; font-family: 'Helvetica Neue', HelveticaNeue, helvetica, arial, sans-serif; }
      h1 a:active { color: #4a8db8 !important; }
      h2 a:active { color: #4a8db8 !important; }
      h3 a:active { color: #4a8db8 !important; }
      h4 a:active { color: #4a8db8 !important; }
      h5 a:active { color: #4a8db8 !important; }
      h6 a:active { color: #4a8db8 !important; }
      h1 a:visited { color: #4a8db8 !important; }
      h2 a:visited { color: #4a8db8 !important; }
      h3 a:visited { color: #4a8db8 !important; }
      h4 a:visited { color: #4a8db8 !important; }
      h5 a:visited { color: #4a8db8 !important; }
      h6 a:visited { color: #4a8db8 !important; }
      a:visited { color: #4a8db8; }
      a:hover { color: #2dbe60; text-decoration: underline; }
      .u-headingMobileAnchor a {text-decoration: none !important; color: #2dbe60 !important; pointer-events: none !important; cursor: default !important;}
      .u-bodyMobileAnchor a {text-decoration: none !important; color: #65646a !important; pointer-events: none !important; cursor: default !important;}
      .footer a:hover { text-decoration: none; }
      .footer-small a:hover { text-decoration: underline; }
      body { background-color: #f3f3f3; }
      .ExternalClass { width: 100%; }
      .ExternalClass { line-height: 100%; }
      table[id='inception'] .Btn-anchor:hover { color: #fff !important; }
      table[id='inception'] .Btn-anchor:visited { color: #fff !important; }
      @media screen and (min-width: 579px) {
        table[id="inception"] .l-inception-point { width: 578px !important; }
      }
      @media only screen and (min-device-width: 768px) and (max-device-width: 1024px) {
        table[id="inception"] a[href^="tel"] { text-decoration: none; color: #65646a; pointer-events: none; cursor: default; }
        table[id="inception"] a[href^="sms"] { text-decoration: none; color: #65646a; pointer-events: none; cursor: default; }
        .mobile-link table[id="inception"] a[href^="tel"] { text-decoration: default; color: #65646a !important; pointer-events: auto; cursor: default; }
        .mobile-link table[id="inception"] a[href^="sms"] { text-decoration: default; color: #65646a !important; pointer-events: auto; cursor: default; }
        table[id="inception"] .u-headingMobileAnchor a {text-decoration: none !important; color: #2dbe60 !important; pointer-events: none !important; cursor: default !important;}
        table[id="inception"] .u-bodyMobileAnchor a {text-decoration: none !important; color: #65646a !important; pointer-events: none !important; cursor: default !important;}
      }
      @media only screen and (max-device-width: 578px), only screen and (max-width: 578px) {
        table[id="inception"] .Branding_positive-container { padding: 14px 0 0 16px !important; }
        table[id='inception'] .Btn-anchor { display: block !important; }
        table[id='inception'] .Row_small { padding: 0 !important; }
        table[id='inception'] .Row_medium-top { padding-top: 16px !important; }
        table[id='inception'] .Avatar-img { width: 48px !important; height: 48px !important; }
        table[id="inception"] { width: 100% !important; }
        table[id="inception"] .l-outie { padding: 0px !important; }
        table[id="inception"] .l-inception-point { width: 100% !important; }
        table[id="inception"] .l-footer { width: 100% !important; }
        table[id="inception"] .l-wrap { width: 100% !important; }
        table[id="inception"] .l-full-bleed { width: 100% !important; }
        table[id="inception"] .media-obj { width: 100% !important; }
        table[id="inception"] .media-content { width: 100% !important; }
        table[id="inception"] .btn { width: 100% !important; }
        table[id="inception"] .btn td { width: 100% !important; }
        table[id="inception"] .l-inception-point { border-right: none !important; border-left: none !important; }
        table[id="inception"] .l-full-bleed img { width: 100% !important; height: auto !important; }
        table[id="inception"] .l-pad > tbody > tr > td { padding: 16px !important; }
        table[id="inception"] .l-split { width: 100% !important; }
        table[id="inception"] .l-split + .l-split { margin-top: 32px !important; }
        table[id="inception"] .ill-notebook { width: 100% !important; height: 96px !important; }
        table[id="inception"] .footer { padding-right: 16px !important; padding-left: 16px !important; }
        table[id="inception"] .btn span { display: block !important; }
        table[id="inception"] a[href^="tel"] { text-decoration: none; color: #65646a; pointer-events: none; cursor: default; }
        table[id="inception"] a[href^="sms"] { text-decoration: none; color: #65646a; pointer-events: none; cursor: default; }
        .mobile-link table[id="inception"] a[href^="tel"] { text-decoration: default; color: #4a8db8 !important; pointer-events: auto; cursor: default; }
        .mobile-link table[id="inception"] a[href^="sms"] { text-decoration: default; color: #4a8db8 !important; pointer-events: auto; cursor: default; }
        table[id="inception"] .u-headingMobileAnchor a {text-decoration: none !important; color: #2dbe60 !important; pointer-events: none !important; cursor: default !important;}
        table[id="inception"] .u-bodyMobileAnchor a {text-decoration: none !important; color: #65646a !important; pointer-events: none !important; cursor: default !important;}
        table[id="inception"] .Rule { display: none !important; }
        table[id="inception"] .l-pad { text-align: center !important; }
      }
    
  
  
    
      
        
          
            
              
                
                  
                    
                      
                        
                          
                          
                            
                              
                                
                                  
                                
                              
                            
                          
                        
                      
                    
                  
                  
                  
                    
                      
                        
                          

  
    
      
        
          
            
              
                
                      Você tem 2 mensagens à sua espera no Evernote
                
              
            
            
              
                As pessoas querem conversar com você. Clique no botão verde para participar.
              
            
            
              
                
                      2 mensagens não lidas de
                
              
            
            
              
                    thiagodebona@gmail.com
              
            
            
            
              
                Responder no Evernote
              
            
          
        
      
    
  



  
    
      
        O Evernote é o escritório moderno que você precisa. Colecione ideias e trabalhe em projetos em conjunto.
      
    
  


                        
                      
                    
                  
                  
                
                
              
            
          
          
          
            
              
                Para obter solicitações de suporte, entre em contato conosco ao acessar a nossa página de suporte.

                Este e-mail foi enviado a você pela Evernote Corporation (ou a sua subsidiária). Evernote Corporation, 305 Walnut Street, Redwood City, CA 94063, EUA.

                
                  
                    Cancelar inscrição
