### ISSUE TITLE
Do ui-grid and its third-party features enable entering formulas in cells?

### ISSUE THREAD

**Issue by chengtie** [angular-ui/ui-grid#5920]
Hello,

I would like to know if ui-grid (and its third-party features) supports **formula**? I am not talking about the formulas (eg, `getTotal()`) in JavaScript files. I want to enable users enter formulas directly in the cells (like google sheets), and such formulas could be calculated.

Cheers

Tie

**Comment by mportuga** [comment]
As far as I am aware, we do not. But I would recommend reading our tutorial page or asking this question on stackoverflow
