### ISSUE TITLE
How to implement a grid that enables to copy-paste to a range of cells?

### ISSUE THREAD

**Issue by chengtie** [angular-ui/ui-grid#5921]
Hello,

At the moment, to copy-paste a value to a cell, it seems that we have to **double click** on the cell before pasting, like in [this example](http://ui-grid.info/docs/#/tutorial/301_editableOnFocus).

Does anyone know how to implement the grid such that we could paste just after **one click** (ie, selecting) the cell?

I am asking this, because I would like to finally realise such a scenario: users could select a range of data in a google sheet and copy them (by `Ctrl+C`), then they go to our grid, select a cell by **one click**, then paste them (by `Ctrl+V`), as a result values of a range of cells will be changed.

Does anyone know what API or third-party features are available to realise this?

Cheers

Tie

**Comment by mportuga** [comment]
The issue board is not meant to be used for questions. Please defer to gitter or stackoverflow for questions of this nature.
