### ISSUE TITLE
Sort Menu position issue with custom header template

### ISSUE THREAD

**Issue by pshivareddy** [angular-ui/ui-grid#5922]
Hi,

I have an issue with sort menu position when i use custom header template(mentioned below) and when cursor is scrolled to right. 

**Custom Header Template:-**

> <div role="rowgroup"
     class="ui-grid-header">
    <div class="ui-grid-top-panel">
        <div class="ui-grid-header-viewport">
            <div class="ui-grid-header-canvas">
                <div class="ui-grid-header-cell-wrapper" ng-style="colContainer.headerCellWrapperStyle()">
                     <div role="row" class="ui-grid-header-cell-row" ng-if="colContainer.renderedColumns !== undefined">
                        <div class="ui-grid-container" 
                        ng-repeat="cat in colContainer.renderedColumns | uniqueheader:'category'">
                            <div ng-repeat="col in colContainer.renderedColumns | filter:{ uid: cat.uid }" 
                            ng-if="cat.colDef.category === undefined" render-index="$index" class="ui-grid-headercell ui-grid-clearfix" 
                            ui-grid-header-cell col="cat"></div>
                            <div class="ui-grid-header-cell ui-grid-clearfix ui-grid-category" ng-if="cat.colDef.category.length > 0">                                    
                                    <div class="ui-grid-categorytext">{{cat.colDef.category}}</div>
                                    <div class="ui-grid-headercell ui-grid-clearfix" 
                                        ng-repeat="col in colContainer.renderedColumns | filter:{ colDef:{category: cat.colDef.category} }"
                                        ui-grid-header-cell col="col" render-index="$index">                      
                                    </div>
                            </div>                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

> </div>

Created unique filter to avoid duplicate header names

> app.filter('uniqueheader', function () {
  return function (input, property) {
    var uniqueList = []
    angular.forEach(input, function (obj, key) {
      if (uniqueList.length === 0 || obj.colDef[property] === undefined) {
        uniqueList.push(obj)
      } else {
        if (obj.colDef[property] !== undefined) {
          var result = $.grep(uniqueList, function (e) { return e.colDef[property] === obj.colDef[property] })
          if (result.length === 0) {
            uniqueList.push(obj)
          }
        }
      }
    })
    return uniqueList
  }
})

Source Link:- [http://plnkr.co/edit/rUsK0LfGF3ws8vhsc9sR?p=preview](http://plnkr.co/edit/rUsK0LfGF3ws8vhsc9sR?p=preview)

Steps to reproduce
1. Must have scroll bar to right side and add additional columns 
2.  Added custom header

**Issue:-**
![image](https://cloud.githubusercontent.com/assets/5755648/21624968/695c9798-d1d7-11e6-9037-677660c12352.png)

_Any solution would be appreciated. Thank you._

**Comment by mportuga** [comment]
I believe this was recently resolved in 4.4.5
