### ISSUE TITLE
Dynamic addition of column in between 2 columns using columnDef doesn't work after re-arranging columns using move feature.

### ISSUE THREAD

**Issue by rohitmitra5752** [angular-ui/ui-grid#5923]
Repro steps:

1) Rearrange columns to have new order.
2) Now try to add a new column in between already existing 2 columns by inserting it into gridOptions.ColumnDef.
Actual: Newly added column doesn't get added at the desired location rather it gets moved at the end of already existing columns.

Investigation details:

On re-arranging already existing columns, ui grid maintains moveColumns cache. Now when we perform insert new column between 2 columns (say 1st two columns) by changing columnDefs, this new column gets added to grid.columns as per columnDefs order. Then, VerifyColumnOrder() gets called which has logic to restore grid.columns to have already existing column order from moveColumns cache and moves newly added column to the last in grid.columns which then gets rendered on grid.

**Comment by mohitYo** [comment]
I am also facing same issue please suggest proper fix for this. Right now i commented VerifyColumnOrder() code to make this scenario work.
