### ISSUE TITLE
$scope.gridAPI.grid.rows not updating to match contents of $scope.gridOptions.data

### ISSUE THREAD

**Issue by JMax2012** [angular-ui/ui-grid#5925]
I have a hidden grid ("gridExport") whose purpose is only to consume large data sets and export the data to CSV.

When the user clicks the Export button, this code is executed -- I have indicated in the comments what the issue is:

```
myService.GetAllData().then(function (response) {
if (response) {

$scope.gridExport.data = response;

//debugger shows $scope.gridExport.data = Array[1000], correct amount of data

$scope.gridExportApi.exporter.csvExport('all', 'visible', myElement);

//debugger shows $scope.gridExportApi.grid.rows = Array[0]
//csv contains zero rows of data

}
});
```

Is there a way to force the grid api to "catch up" and refresh so that it is aware of the latest data set?

**Comment by JMax2012** [comment]
To clarify, this issue is not impacted by the visibility or invisibility of the grid. I tested again on a visible grid, first loading just 100 rows of data, then attempting to batch-execute a load-and-export of 1000 rows.

First execute:

myService.GetPartialData(1,100).then(function (response) {
if (response) {

$scope.gridOptions.data = response;

//debugger shows $scope.gridOptions.data = Array[100], correct amount of data

}
});

Then execute:

myService.GetAllData().then(function (response) {
if (response) {

$scope.gridOptions.data = response;

//debugger shows $scope.gridOptions.data = Array[1000], correct amount of data

$scope.gridApi.exporter.csvExport('all', 'visible', myElement);

//debugger shows $scope.gridApi.grid.rows = Array[100]
//csv contains 100 rows of data

}
});

**Comment by sergiomcalzada** [comment]
Hello, I have the same problem when using "exporterAllDataFn". When the promise resolves in the funcion "loadAllDataIfNeeded", the "grid.options.data" is a zero items array. So, "grid.modifyRows(grid.options.data)" is empty and the csv too

Any idea why?
