### ISSUE TITLE
Can't figure out how to remove the whitespace to the left subgrid

### ISSUE THREAD

**Issue by bulu11** [angular-ui/ui-grid#5941]
I'm using the Angular ui-grid and Angular (v1.4). I can display a simple table fine but when it comes to nested tables To see an example of the code - go to http://ui-grid.info/docs/#!/tutorial/216_expandable_grid, then click on the "Edit in Plunkr" link on the right about halfway down. In this example, when you click on a row you'll see the subgrid. That's fine but for this subgrid I'd like to remove the whitespace to the left subgrid's ID column and also ensure the subgrid's columns line up the the parent columns.

**Comment by csvan** [comment]
Why are you writing your ticket in the title?

**Comment by mportuga** [comment]
I am guessing this particular question has to do with the second grid in that example, the one with the pinned column. But regardless, this seems like more of a question of customization rather than a legitimate bug or enhancement/feature. Therefore, I am closing this issue.
