### ISSUE TITLE
when we use a customScroller ui-grid data is not getting updated

### ISSUE THREAD

**Issue by shardulP** [angular-ui/ui-grid#5943]
Hi 

I just found the issue. I am not sure whether it is already reported or not. When we are using the customScroller property of gridOptions. Then if data is not getting updated. 

I have attached 2 plunkers one for working without customScrolle andothe one is with customScroller. 
https://plnkr.co/edit/bsjJSsThti5e30EkibsS?p=preview
http://plnkr.co/edit/4io3nxRWROUzelKX4elb?p=preview 

Please let me know if I missed something ?

**Comment by mportuga** [comment]
That is because your scroll handler is not updating any of the viewport position. If you look at the following example, calling the standard scroll handler after yours is causing scrolling to work correctly: http://plnkr.co/edit/gJNhWDw5wywPCMVQZ7pS?p=preview
