### ISSUE TITLE
Cannot read property 'options' of undefined when clicking on GridMenu

### ISSUE THREAD

**Issue by felixn11** [angular-ui/ui-grid#5945]
When expanding the GridMenu and error is thrown saying: "Cannot read property 'options' of undefined" @ui-grid.js:18559. This happens when the module 'ui.grid.exporter' is included. 

No need for a Plunkr because the same issue is happening when clicking on the GridMenuButton in the tutorial:
http://ui-grid.info/docs/#/tutorial/206_exporting_data

Seems like grid is undefined in the "shown" event.

**Comment by npetralia** [comment]
Hi,

I have open this issue too but nobody look on it
=> https://github.com/angular-ui/ui-grid/issues/5926

**Comment by darionato** [comment]
I've this error too

**Comment by npetralia** [comment]
It's a regression between 4.0.1 and 4.0.2

**Comment by pkiranc** [comment]
This issues is occurring on all the examples that are using menu.Can someone please look into this.

**Comment by dscarfo** [comment]
I had the same issue running with version 4.0.2.  Reverting to version 4.0.1 resolved the issue for me.

**Comment by takotuesday** [comment]
What is the status of this issue?

**Comment by johnedvard** [comment]
I am having the same issue. Everything still works, but the console is overwhelmed with error messages.

**Comment by tmarkley** [comment]
Good news: this was fixed in today's release: https://github.com/angular-ui/ui-grid/blob/master/CHANGELOG.md#v403-2017-03-24

**Comment by MJ33** [comment]
great! :100:

**Comment by quiksillvr** [comment]
Thank you!!

**Comment by darionato** [comment]
it works, thanks

**Comment by Kaang** [comment]
The same issue in 4.0.11.
4.0.10 looks like works

**Comment by mportuga** [comment]
Issue is resolve of 4.2.0
