### ISSUE TITLE
cell edit behavior of last row depends on row height

### ISSUE THREAD

**Issue by JZehet** [angular-ui/ui-grid#5950]
Move to the last row of the plunker example.
Start editing a new age value. The existing value is not replaced.
Start editing a age value of another row. The existing value is replaced.
Change the row height to 30 which is the default.
Bevavior is the same for all rows.

https://plnkr.co/edit/NodN13?p=info

**Comment by Backi03** [comment]
+1

**Comment by mportuga** [comment]
Could not reproduce on the latest version: http://plnkr.co/edit/FCUnP2sUCUgiqDz8hSPI?p=preview
