### ISSUE TITLE
onRegisterApi not working

### ISSUE THREAD

**Issue by rahi-rajeev** [angular-ui/ui-grid#5963]
$scope.gridOptions = {
		columnDefs : $scope.columsSetting,
		saveFocus : false,
		enableGridMenu : true,
		paginationPageSizes : [],
		paginationPageSize : 0,
		useExternalSorting : true,
		enableRowSelection : true,
		enableSelectAll : true,
		saveScroll : true,
		enableVerticalScrollbar : false,
		enableColumnReordering : true,
		enablePaginationControls : false,
		paginationCurrentPage : 1,
		PageSize : 1,
		enableColumnMenus : false,
		
		rowTemplate : '<div grid="grid" class="ui-grid-draggable-row" draggable="true"><div ng-repeat="(colRenderIndex, col) in colContainer.renderedColumns track by col.colDef.name" class="ui-grid-cell" ng-class="{ \'ui-grid-row-header-cell\': col.isRowHeader, \'custom\': true }" ui-grid-cell></div></div>',
		onRegisterApi : function(gridApi) {
			$scope.gridApi = gridApi;
			alert('jjhjhj');
                       //not getting alert here
			// Setup events so we're notified when grid state changes.
			//$scope.gridApi.colMovable.on.columnPositionChanged($scope, saveState);
			//$scope.gridApi.colResizable.on.columnSizeChanged($scope, saveState);
			// gridApi.core.on.columnVisibilityChanged($scope, function(changedColumn) {
			// $scope.columnChanged = {
			// name : changedColumn.colDef.name,
			// visible : changedColumn.colDef.visible
			// };
			// });
		}
	};

**Comment by lobo78** [comment]
I'm not able to reproduce your issue. Could you provide a plunker that shows the problem?
