### ISSUE TITLE
First click on partially on-screen grid forces full page scroll to display entire grid

### ISSUE THREAD

**Issue by daredevil82** [angular-ui/ui-grid#5968]
Using the [CellNav tutorial ](http://ui-grid.info/docs/#/tutorial/202_cellnav) as an example, 

1. Scroll down almost to the end of the page such that the first row of the demo grid is visible.  Whether you scroll all the way down and up slightly does not matter.
1. Select the name or ID of the first row.
1. Entire page will scroll downward to display entire grid container element.

This only happens for the first click on the grid.  Subsequent clicks, even after scrolling back up to display only the first row, will not have forced scrolling.  This is occurring on latest Chrome on the UI-Grid docs.

**Comment by mportuga** [comment]
This is happening because when you click on the row, focus is being set to the ui-grid-focuser element, and the default browser behavior in that case is to scroll to show the "focused element". This will need a decision as to whether we want to redesign the callNav or close this issue.
