### ISSUE TITLE
Resetting grid column

### ISSUE THREAD

**Issue by srikantsima** [angular-ui/ui-grid#5971]
Hi All,

I am working in angular 1.3 version and ui-grid 3.0.
Currently i am facing one problem in my grid.
The issue is---User can able to move column left and right. After column movement i want to reset the column position when i click any button. But is is not happening..

Thanks in advance.

**Comment by mportuga** [comment]
You can try something like this: http://plnkr.co/edit/iPTj7wv5eVR43h0nmQRl?p=preview
