### ISSUE TITLE
How to set the max length or max limit to the editable field in UI Grid ?

### ISSUE THREAD

**Issue by rahuljain257** [angular-ui/ui-grid#5977]
Hello Everyone,

Can u please tell me how can i set the max length to the field in UI Grid ? Please see the **plunker** link : http://plnkr.co/edit/B0htl6pHCQTxBTwcowOY?p=preview

I know about setting it in **EditItemTemplate** field but want to know whether its possible in the grid directly without specifying the **EditItemTemplate**.

Thanks
Rahul Jain

**Comment by AliaksandrBortnik** [comment]
@rahuljain257 I believe there is no way besides one you have mentioned. It would be much better to ask such questions "How to" using Stackoverflow.
