### ISSUE TITLE
How to set the Date Picker in UI Grid which works in all the major browser ?

### ISSUE THREAD

**Issue by rahuljain257** [angular-ui/ui-grid#5978]
Everyone,

I am looking to implement the datepicker or masked input control in UI Grid but didn't find anything. So can you please point me to some article or piece of code which will guide me to implement the date picker or maked input control in my UI grid development.

By setting the type="date" populates the picker but it work only in chrome & I want to make it work in IE Safari & Firefox.

So waiting for your reply.

**Comment by Bodmoor** [comment]
+1 The datepicker is not displayed in Internet Explorer, so far I have only seen it work in Chrome.
