### ISSUE TITLE
pagingOptions.currentPage doesn't get set properly with Angular >1.1.1.

### ISSUE THREAD

**Issue by dnordberg** [angular-ui/ui-grid#598]
Using Ng-grid 2.0.7 pagingOptions.currentPage doesn't get set properly with Angular >=1.1.3 (The version provided by ng-grid in the lib folder).

It does work when reverting back to 1.0.2 which is the version defined in the plnkr provided on the ng-grid documentation page. The regression seems to have been introduced in 1.1.3 (1.1.1 works fine).

An example that illustrates the issue:
http://plnkr.co/edit/jxdukO?p=preview

The input field used to display the current page shows no initial value, using the paging buttons does not change the value as expected even after inputing a value manually. Also the validation doesn't seem to work as the input gets marked as invalid for valid numbers.

**Comment by vijender1256** [comment]
$scope.yourGridOptions.paginationCurrentPage = 1; --> will reset the pagenumber of angular ui-grid :)

**Comment by sudhirgoswami** [comment]
https://stackoverflow.com/questions/45453359/how-to-get-page-number-in-slickgrid-while-click-the-page-numbers
