### ISSUE TITLE
formular injection vulnerability on CSV export

### ISSUE THREAD

**Issue by hohwille** [angular-ui/ui-grid#5991]
We have received valuable input from a commercial penetration test of our angular app using ui-grid. One issue that was found is directly related to ui-grid and is about formular injection via excel (https://www.owasp.org/index.php/CSV_Excel_Macro_Injection).

Steps to reproduce:
* Insert this data ```=cmd|' /C calc'!A0``` into a grid cell somehow
* Perform a CSV export and open the result in MS excel
* Confirm any secruity warnings (this should at least prevent smart users from the attack)
* See that the injection was actually executed and the command (```calc.exe```) has been opened.

Please note that opening Calc is just a harmless example. You could also format the disc or do other harm.

Possible solution:
Escape the generated CSV output e.g. by enclosing all cell data into single quotes. This however requires also to escape single quotes in user data.

**Comment by mportuga** [comment]
Thank you for the idea!

**Comment by rswhiting** [comment]
So, after coming up with a solution and implementing it on the branch, I decided to put it into the sample data. As it turns out, the csv export already quotes strings--which should take care of it.

**Comment by mportuga** [comment]
@rswhiting, are you saying this is no longer an issue with ui-grid?

**Comment by rswhiting** [comment]
Yes, the csv export quotes all string fields, so it implements one of the recommended solutions for CSV injection mitigation.

**Comment by mportuga** [comment]
Thank you!
