### ISSUE TITLE
grid with pagination, scrollToFocus to last row: scrollbar does not reach the end

### ISSUE THREAD

**Issue by RalleSaid** [angular-ui/ui-grid#5993]
I have a grid with pagination, and when I try to scroll focus to the last row, it does not display correctly.
It is as if the height of the paging bar is not considered

[Here is a plunker](http://plnkr.co/edit/zLnfPoII23msd4HFADl1?p=preview)

html:
`<div ui-grid="gridOptions" ui-grid-cellnav ui-grid-pagination class="grid"></div>`

js
```
$scope.scrollToFocus = function() {
      rowIndex = $scope.gridApi.grid.renderContainers.body.visibleRowCache.length - 1;
      rowEntity = $scope.gridApi.grid.renderContainers.body.visibleRowCache[rowIndex].entity;
      $scope.gridApi.cellNav.scrollToFocus( rowEntity, $scope.gridOptions.columnDefs[0]);
};
```

pd: sorry for my english

**Comment by RalleSaid** [comment]
My workaround: 

ui-grid.js (v4.0.1), line 6069 aprox.
```
if(self.options.enablePaginationControls){
          bottomBound = bottomBound - 30
      }
```
if the pagination controls are enabled, I add to the calculation the pixels that has the height of the bar.

**Comment by mportuga** [comment]
This issue is no longer reproducible with the latest version of ui-grid.
