### ISSUE TITLE
.ui-grid-cell-contents events when using directive in headerCellTemplate

### ISSUE THREAD

**Issue by cooljingle** [angular-ui/ui-grid#5996]
I am specifying a custom headerCellTemplate which contains a directive. In such a situation the directive template won't render until after the parent ui-grid directive has run through its link, which contains the following
`var $contentsElm = angular.element( $elm[0].querySelectorAll('.ui-grid-cell-contents') );`
and then assigns various events to this element. 

Unfortunately my header cell will not get these events bound as the relevant DOM doesn't exist yet. This can be fixed fairly easily with [delegated events](http://api.jquery.com/on/) e.g.
    `$contentsElm.off('click', $scope.clickFn);` becomes
    `$elm.off('click', '.ui-grid-cell-contents', $scope.clickFn);`

I'll submit a PR for this shortly.

**Comment by dlgski** [comment]
I need to revert this commit.  delegated events are not supported in Angular at this point.  @cooljingle can you make sure you run through and test your code locally before submitting a PR in the future.  Thank you
