### ISSUE TITLE
Aggregate Sorting

### ISSUE THREAD

**Issue by knadeau** [angular-ui/ui-grid#600]
I have a table grouped by its first column. I'd like to reorder the groups by, for example, number of children in the group (or any function of the aggregate row and its properties). Is it possible to group by one criterion but sort by another?

**Comment by prettycode** [comment]
@bingomanatee I have a similar requirement as the original author of this issue, and your suggestion was my first thought. A second thought was that I might somehow add a column menu item for "Sort Count Ascending" and another "Sort Count Descending" that would only be a menu item for columns that are grouped. Is this second approach reasonable/feasible, in your expert opinion?
