### ISSUE TITLE
Data change not appears in grid when entire dataset/json changes along with column names

### ISSUE THREAD

**Issue by prashasti4** [angular-ui/ui-grid#6000]
Here is the plunker , Please check that data.json & data2.json have different column names , and only the column name that matches with data.json gets updated. How can I fix this?
https://plnkr.co/edit/1B7sahBs188JiOrzmCHP?p=preview

**Comment by mportuga** [comment]
This plunker is using ng-grid, not UI-grid. However, I did try to recreate the plunker using uiGrid and that issue is still reproducible.
http://plnkr.co/edit/wO4fhSL6Hbz1yFEEwFNJ?p=preview

**Comment by mportuga** [comment]
However, I am able to solve the issue by updating the column defs array during the swap data step as seen bellow:
http://plnkr.co/edit/9AsHpRhzkLCJt7BQdaKu?p=preview
