### ISSUE TITLE
Pinned Column height Does not match to body column in angular grid

### ISSUE THREAD

**Issue by jaypalkadam** [angular-ui/ui-grid#6001]
![image](https://cloud.githubusercontent.com/assets/4994840/22774886/27edc72c-eecf-11e6-9390-b7d172bed687.png)

I have make the height of the grid cell auto. but the height of the pinned column is not increasing as per the body column . The grid look like as per the above screen

**Comment by mportuga** [comment]
I believe that is due to your CSS. That issue cannot be observed on UI-Grid by default.
