### ISSUE TITLE
Customized checkbox in tree grid!!

### ISSUE THREAD

**Issue by saurabhmuthiyan** [angular-ui/ui-grid#6004]
Hi there, I am new to Angular, some how I managed to load tree grid using UI-grid and I loved it.
I have an requirement where I need checkbox on particular row.
I have added column like given below:
{  name: 'chbx', pinnedLeft: true, width: 40,
             enableFiltering: false, enableSorting: false, headerCellClass: 'grey', cellTemplate:'<div><input type="checkbox" ng-init="checkStatus=false" /></div>'}

 functionality  can you develop some feature customize checkbox on particular rows (whether row to have checkbox decided on json data like row.chbx==1 then add checkbox on row).
![capture](https://cloud.githubusercontent.com/assets/18263057/22825395/029bf2ca-efb3-11e6-83ce-ef6c0c0be591.PNG)
I look forward to have some positive feedback.

**Comment by kj-johnson** [comment]
This looks like it can all be done with custom Cell Templates.
