### ISSUE TITLE
ui-grid > pagination 

### ISSUE THREAD

**Issue by SYNCvighnesh** [angular-ui/ui-grid#6006]
when I am passing heardcoded values for 
 $scope.gridOptions1.data =[{
	"name": "Ethel Price",
	"gender": "female",
	"company": "Enersol"
}, {
	"name": "Claudine Neal",
	"gender": "female",
	"company": "Sealoud"
}, {
	"name": "Beryl Rice",
	"gender": "female",
	"company": "Velity"
}, {
	"name": "Wilder Gonzales",
	"gender": "male",
	"company": "Geekko"
}];
 for pagination i am getting  1 - 5 of 4 items at bottom of ui-grid why it is so ?
if I am passing only 4 items but why count of pagination is different
kindly look into plunker 
http://plnkr.co/edit/JzXSQwbv8xcA3UwAcWHz?p=preview

**Comment by joeltmiller** [comment]
I second this. Happened with the `4.0.0` upgrade, had to roll back to `3.2.9`.
