### ISSUE TITLE
Horizontal Scrollbar disappears when grid is empty on Chrome

### ISSUE THREAD

**Issue by kj-johnson** [angular-ui/ui-grid#6008]
I had this issue on Chrome only back in September (IE and Firefox did not exhibit the behavior). I was able to fix it by removing my custom CSS for the grid and putting it back in piece by piece until it broke again. The problem was having a margin on the top of the ui-grid canvas (between the header cells and the body cells of the ui-grid).

In particular, the offending css was the .ui-grid-canvas margin-top.

Here's a plunker showing the issue (note that you can fiddle with the css and grid options, this was how we had it set up, but even using the built-in scrollbars they are greyed out and disabled on an empty grid.
[Plunker](http://plnkr.co/edit/TE3fNmNdhLwTj6Pb7BhS?p=preview)

**Comment by mportuga** [comment]
Issue is no longer reproducible with the latest version and WHEN_NEEDED option.
