### ISSUE TITLE
Error: [$compile:ctreq] Controller 'uiGrid', required by directive 'uiGridImporterMenuItem', can't be found!

### ISSUE THREAD

**Issue by bobisch** [angular-ui/ui-grid#6009]
After upgrading to 4.0 getting:

`Error: [$compile:ctreq] Controller 'uiGrid', required by directive 'uiGridImporterMenuItem', can't be found!`

More interesting is that the plunker for [tutorial 311](http://ui-grid.info/docs/#/tutorial/311_importing_data_with_rowedit) exhibits the same problem.

As soon as you click the grid menu the error comes up in the console.  Tested in Chrome.

Update:  This actually seems to be a regression between 4.0.1 and 4.0.2.

**Comment by freefri** [comment]
Error confirmed in 4.0.2 not existing in 4.0.1
I'm also getting the error in the tutorial 311

**Comment by arjang** [comment]
Im facing the same issue in v4.06.

**Comment by alankrutha05** [comment]
Do we have a fix for this? As am seeing this issue even in the tutorial even now (4.1.3)

**Comment by mportuga** [comment]
Yes, PR #4178 resolves this issue. It will be is 4.2.1
