### ISSUE TITLE
chrome 56 scroll issue on ui-grid 3

### ISSUE THREAD

**Issue by HaroldStruwig** [angular-ui/ui-grid#6017]
issue is not on ui-grid 4 but only on ui-grid 3

## issue description
grid auto scrolls to the bottom once one starts to scroll down

## reproduce issue:
- use chrome 56
- open pen: [https://codepen.io/anon/pen/JEVYwN](https://codepen.io/anon/pen/JEVYwN)
- start scrolling

## reason for issue:
[https://www.chromestatus.com/feature/5700102471548928](https://www.chromestatus.com/feature/5700102471548928)

## fix for issue:
add CSS
```css
.ui-grid-viewport {
  overflow-anchor: none;
}
```

**Comment by mloutraris-ge** [comment]
We were seeing the same problem. Thanks for finding the fix!

**Comment by anx-ckreuzberger** [comment]
I have the same issue for a couple of days now.

Your CSS Snippet fixed it for me, thank you very much!

**Comment by prksean** [comment]
Awesome! Thanks for the solution. If I came here 6 days earlier, I would have struggled with this so much. Am I supposed to simply add overflow-anchor: none; to already existing ui-grid.css?

**Comment by sebastianchacko89** [comment]
@HaroldStruwig Awesome! Thanks for finding the fix. Im facing the same issue. 
Could you please raise a pull request with your fix, so its available in the next release?

**Comment by ravivantaku** [comment]
Awesome! Thanks for solution.

**Comment by mportuga** [comment]
I release a ui-grid version 3.2.10 with @Joel-Kornbluh's fix
