### ISSUE TITLE
Errors when opening menu with export to CSV / PDF

### ISSUE THREAD

**Issue by haywiresquid** [angular-ui/ui-grid#6019]
v4.0.2.
Minor bug when opening the grid menu with export to csv/pdf enabled you get a list of errors in the console, the export seems to still work however. 

http://ui-grid.info/docs/#/tutorial/206_exporting_data

**Comment by spatsatzis** [comment]
Try reverting temporary to v4.0.1 which solves the problem. i had the same issue!
