### ISSUE TITLE
怎么设置ui-grid 的表头的按钮模板

### ISSUE THREAD

**Issue by yangjingyu** [angular-ui/ui-grid#6020]
表头的模板设置，替换原来的

**Comment by notomorow** [comment]
有一个属性叫headerCellTemplate

**Comment by yangjingyu** [comment]
表头的排序按钮模板可以设置么？

**Comment by adrianviegas** [comment]
This seems to be a question rather than an issue
Check out http://ui-grid.info/docs/#/tutorial/115_headerCellClass
and see `displayName` in [`GridColumn`](http://ui-grid.info/docs/#/api/ui.grid.class:GridColumn)
