### ISSUE TITLE
tons of official examples not working

### ISSUE THREAD

**Issue by capz** [angular-ui/ui-grid#6025]
i am setting up a new project with ui-grid and ~half of the documentation examples dont work. Documentation is frustrating where it is available by not mentioning how to do certain things (subscribing to events), outdated/undocumented code (list of available events). Doesnt link to relevant information (macros for use with cell edit templates, how to access properties on complex objects hidden behind cell edit template macros).

Also use of $scope is rampant, something that i feel should be avoided, especially in examples.

**Comment by kylej-89** [comment]
It is pretty much a dead control in terms of support now. I'd recommend moving to AG-Grid

**Comment by jimgrimmett** [comment]
Apart from the fact AG-grid is ~£500 license and ui-grid is still actively being bug-fixed and developed... sure.

**Comment by mportuga** [comment]
We are more than willing to accept pull request with fixes for the documentation and alternatives that do not rely so much on $scope. Unfortunately, the core team is really small right now and busy with our day jobs, so we can't keep everything as up-to-date as we would like. And as @jimgrimmett said, ui-grid is still actively being bug-fixed and developed, but that is mostly done by the community nowadays. For myself, I try to keep the build green and merge pull requests from time to time, then deploy new releases for the public.
