### ISSUE TITLE
Urgent: ui-grid 4.0.2 has column header alignment issues with column data

### ISSUE THREAD

**Issue by Saransh27** [angular-ui/ui-grid#6027]
I am facing column alignment issues in ui-grid 4.0.2:
For example:

**Col Header -->  Name  |         gender  |       Address|        Ssn        |     education
row           --> saransh  |       male    |        Australia|      121212 |      B.Tech

Data in the row is shifted towards left. can anyone please help me with this solution?**
Earlier I was using the same code in grid 3.2.9 and there were no alignment issues.

**Comment by raulyrauly** [comment]
I am seeing the same issue, it hasn't happened for me in Google Chrome, but firefox is showing this behavior.

**Comment by Saransh27** [comment]
I can replicate this issue in all the browsers.

**Comment by Saransh27** [comment]
I found the solution, It is working fine when I remove my custom width in col definitions. 

I had specified width of the columns in percentage. Now I have removed them and specified custom width only for few columns that too in pixels and not in %.
