### ISSUE TITLE
Remove $$treeLevel from grid menu

### ISSUE THREAD

**Issue by TLKG** [angular-ui/ui-grid#6028]
Have a TreeView of ui-grid populated from REST API, data include column [$$treeLevel] for tree structure.
![1](https://cloud.githubusercontent.com/assets/22269729/23142533/53a93734-f771-11e6-9c9b-1cae765b1080.JPG)

Now, how to get rid of it from the grid menu?

**Comment by TLKG** [comment]
excludeProperties[ ] is not helpful because columnDefs is being used.

**Comment by mportuga** [comment]
set it to enableHiding to false on the column def for that column.
