### ISSUE TITLE
[Solved] Freakishly fast scrolling of ui-grid in latest chrome and opera web browsers

### ISSUE THREAD

**Issue by rajatjangir** [angular-ui/ui-grid#6038]
I had to try different solution to make this scrolling behaviour go. I was almost on the verge of giving up ui-grid but this little piece of code helped me solve this issue.  Hope it does help someone else with the same problem.

Paste this code in your css if you are facing same issue as me it worked for me thanks

.ui-grid-viewport {
    overflow-anchor: none;
}

thanks

**Comment by webfeat** [comment]
Can you tell me what's happens before you append the code?I had encountered a trouble .when I scroll my grid,I found that  the grid was scrolling quickly and automatically.
