### ISSUE TITLE
The Grid scrolls up while editing the cell

### ISSUE THREAD

**Issue by soyiatgit** [angular-ui/ui-grid#6053]
With 5-6 rows, the grid and the editing seems fine. While as the number of rows increase, on editing the grids scrolls up. This happens when the user tries to edit a cell on last row. As soon as user clicks the cell, the grid scrolls up, the user has to scroll down to see last row again.

**Comment by AnnTV** [comment]
I have the same issue with scrolling to center clicked cell

**Comment by mportuga** [comment]
Will be resolved in 4.4.5
