### ISSUE TITLE
Run examples from page via Plunker links on page, shows only empty div

### ISSUE THREAD

**Issue by dannychase2004** [angular-ui/ui-grid#6054]
In my environment, I was trying to get the grid examples to work, and only got an empty div with a border. Went to the main page for help, clicked the Plunker link, and those are coming up the same way. Something different about the grid that wasn't updated on the page?

**Comment by mportuga** [comment]
I don't think so, I was able to reach many of the plunkers in our page with Mac Chrome today. Could you provide me more information about your setup? Like, what OS and browsers you are using

**Comment by smohammedyasin** [comment]
Same with me, i can see only empty div, i'm using google Crome windows 10. and mac Sierria(10.12 )

**Comment by smohammedyasin** [comment]
I found the issue. because i 'm using 1.6.3 angular js version. this is very sad. i cannot down grade my version.  i must look alternate plugin.

**Comment by mportuga** [comment]
I am sorry. I will need to add support for angular 1.6 in a future release

**Comment by mportuga** [comment]
As of version 4.1.0 we now support angular 1.6
