### ISSUE TITLE
UI.Grid header/footer is displayed before the data

### ISSUE THREAD

**Issue by Dkr17** [angular-ui/ui-grid#6063]
Hi All,
I am using a ui.grid and binding service data to it. 
The problem is that the header/footer is displayed and after that the data is displayed in the grid.
i have used headercelltemplate and Cellclass in $scope.gridoptions.

Please help me so that i can bind/display the grid when the service data is available or i can use headercelltemplate in OnRegisterAPI. I have no knowledge on RegisterAPI.

 $scope.myData = [];

        var promise = AVLAlertImpactsService.getAVLAlertImpactsData($scope.resultView);

        promise.then(function (result) {

            $scope.myData = result;
            //alert(result.length);
            $scope.gridOptions.data = result;
            // $scope.gridOptions.data = result;
        });

        $scope.gridOptions = {
            //data:'myData',
            paginationPageSizes: [5, 5, 50, 75],
            enableRowSelection: true,
            paginationPageSize: 5,
            showGridFooter: true,
            onRegisterApi: function (gridApi) {
                $scope.gridApi = gridApi;
            },
            gridFooterTemplate: '<div style="padding-left:400px;"> * Potential Impacts should be verified by your engineering staff before initiating any action.</div>',
            enbaleSorting: true,
            enablePaging: true,
            enableFiltering: true,

            columnDefs: [
                {
                    name: 'IPN', displayName: 'IPN', width: 200, enableFiltering: true,
                    headerCellTemplate: "<div class='ui-grid-spilt-header-main'><div class='ui-grid-split-merge-header' style='width:900%'><table class='ui-grid-header-table'><tbody<tr><td width='67%' style='background-color:#FFE4C4'>Information from your AVL</td><td width='33%'style='background-color:	#ADD8E6' >Information from Notice</td></tr></tbody></table></div>Internal PN</div>",
                },
                 {
                     field: 'CPN', width: 400,
                     headerCellTemplate: "<div class='ui-grid-spilt-header-main'>National Semiconductor PN in your AVL</div>",
                 },
                 {
                     field: 'vendor_mfr', width: 200,
                     headerCellTemplate: "<div class='ui-grid-spilt-header-main'>MFR in your AVL</div>",

                 },
                
                {
                    field: 'ConfidenceText', width: 200,
                    headerCellTemplate: "<div class='ui-grid-split-header-main'>Match Confidence</div>",
                    cellClass:
                        function (grid, row, col, rowRenderIndex, colRenderIndex) {

                            if (row.entity.C_matchConfidence == 100) {

                                //if (grid.getCellValue(row, col) == 007) {

                                return 'perfect';
                            }
                }
            ]

        };
    }

**Comment by mportuga** [comment]
Have you considering doing an ng-if on the entire grid that waits until data is defined before trying to render it?

**Comment by Dkr17** [comment]
Thanks mportuga. I have used ng-if but have not used wait. With this new problem arises , the column headers are not displayed, where as the data is not.
