### ISSUE TITLE
v4.0.2 row number <start row number> - <end row number> is wrong

### ISSUE THREAD

**Issue by opadillaintegrify** [angular-ui/ui-grid#6064]
The bug can be seen in the first grid on this page: http://ui-grid.info/docs/#/tutorial/214_pagination

![screen shot 2017-03-07 at 10 27 17 am](https://cloud.githubusercontent.com/assets/10500171/23666443/a9ef66b2-0320-11e7-9289-c6a3d712671f.png)

The bottom right displays: 1-**26** of 100 items
It should display: 1-**25** of 100 items

Paging consistently shows end number to be +1 than it should be.

**Comment by yalnifj** [comment]
See https://github.com/angular-ui/ui-grid/issues/5944

**Comment by harikrishnan-u01** [comment]
Am also facing the same issue. Any fix available?

**Comment by mportuga** [comment]
yes, we just merged the fix recently and it will be present in the next release

**Comment by harikrishnan-u01** [comment]
Hi mportuga,

When is the next release planned? I need the fix urgently in my project.

Thanks,
Hari

**Comment by mportuga** [comment]
@harikrishnan-u01 v4.0.3 is now released and this issue is resolved.
