### ISSUE TITLE
ui-grid with external Filter dropdown columns

### ISSUE THREAD

**Issue by cristtiah** [angular-ui/ui-grid#6068]
Hi I am new to AngularJS and I am using version 1.3 and ui-grid but cant find an example of an external Filter with select dropdown of the columns and an input field for the filterValue. Can anyone help me? Thanks so much.

**Comment by mportuga** [comment]
Here is a quick example:
http://plnkr.co/edit/pnfcIn0RBnnzeU8kuosg?p=preview

By the way, the latest version of ui-grid requires that you use angular 1.4 or angular 1.5

**Comment by cristtiah** [comment]
Hi Marcelo thanks. I am new to Angular can you guide me on this? We are still using Angular 1.3 what happens if we dont use 1.4 or 1.5? Will the scripts still work? And also your example how do I use the my-custom-filter.html to index.html? Thanks so much for your help.

**Comment by mportuga** [comment]
It is brought in by the "myCustomFilter" directive on line 65 of app.js

**Comment by cristtiah** [comment]
Thanks again for your reply. I was really looking at an external filter on top of the grid putting selected field names(columns) on the dropdown and an input textbox to filter what is selected in the dropdown and a Search button

**Comment by mportuga** [comment]
Oh, so you want the filter to not be inside the grid, but outside it? I can come up with a plunker for that later tonight

**Comment by cristtiah** [comment]
thanks any luck?

**Comment by mportuga** [comment]
Sorry, I ended up not having time last night, here it is now though:
http://plnkr.co/edit/ZpIVgsaFQejG1Wa3OjCb?p=preview

I also found an example of use doing this in our website:
http://ui-grid.info/docs/#/tutorial/321_singleFilter

**Comment by cristtiah** [comment]
for some reason am getting Expected Identifier here

var match = row.entity[field].match(matcher);

**Comment by mportuga** [comment]
weird, can you attach me a screenshot of the error you are seeing?
