### ISSUE TITLE
UI grid menu throws an error when ui-grid-importer is present

### ISSUE THREAD

**Issue by prashant93** [angular-ui/ui-grid#6070]
On click of UI grid menu error is thrown, functionality working fine but still why this error.
![image](https://cloud.githubusercontent.com/assets/4151470/23858232/c581e526-0825-11e7-90ff-9ea1bc297343.png)

**Comment by mportuga** [comment]
I actually have a fix for this issue right now. It is going to be added in the next release. But I am trying to solve the build issue first.

**Comment by prashant93** [comment]
when will next release happen, I am also trying to solve this issue.

**Comment by mportuga** [comment]
v4.0.3 is now released.

**Comment by mportuga** [comment]
Turns out a less severe version this issue persists. But now it is an error about the ui-grid-importer feature.
![screen shot 2017-03-24 at 6 06 15 pm](https://cloud.githubusercontent.com/assets/6733275/24315327/ca5e305a-10bc-11e7-84d6-9ca40cb6b874.png)

**Comment by zhenz** [comment]
Do we have this solved? Still getting

Error: [$compile:ctreq] Controller 'uiGrid', required by directive 'uiGridImporterMenuItem', can't be found!

in v4.0.6.

Duplicate issue https://github.com/angular-ui/ui-grid/issues/6009

**Comment by ewahner** [comment]
This is still an issue in 4.0.11.  Are there any plans to address this?

**Comment by ewahner** [comment]
I was looking at the code and it appears there are `this.grid` references in the **addToMenu** function that are invalid and should probably just be `grid`.whatever but there is still the angular error when clicking on the menu item:

[$compile:ctreq] Controller 'uiGrid', required by directive 'uiGridImporterMenuItem', can't be found!

**Comment by alankrutha05** [comment]
Do we have a solution to this issue? Am still seeing it in 4.1.3 as well.

**Comment by mportuga** [comment]
4.2.1 has a fix for this.
