### ISSUE TITLE
Edit in Plunker are pointing back to ui-grid/info

### ISSUE THREAD

**Issue by TLKG** [angular-ui/ui-grid#6078]
Can we have them in plunker? For example, "Edit in Plunker" for [103 filter](http://ui-grid.info/docs/#/tutorial/103_filtering) and [212 Infinite Scroll](http://ui-grid.info/docs/#/tutorial/212_infinite_scroll) are pointing back to ui-grid.info/docs.

**Comment by mportuga** [comment]
Those links worked as expected for me:

103 filter: http://plnkr.co/edit/?p=preview
212 Infinite Scroll: http://plnkr.co/edit/?p=preview
