### ISSUE TITLE
Grouping with more than one column.

### ISSUE THREAD

**Issue by Vibha19gn** [angular-ui/ui-grid#6084]
On grouping of data/rows based on more than one header column, the grouped data/rows appear in different rows.Clicking on each grouped header in different rows shows the grouped data/rows.Can the grouping headers be shown in one row itself and on one click show all the grouped data/rows.The change i'm looking for is in display part only.

Example:
Can the order #, PO # and quantity grouping header (1489650598956 (2), 1578284085800 (2), 1.0 (2) in bold) appear in the same first row itself?.The problem is that i have to click thrice on plus (now minus) symbol for (1489650598956 (2), 1578284085800 (2), 1.0 (2) in bold) to see the grouped data/rows.If the grouping headers appear in same row, then on one click the grouped data can be seen.

Can the grouping headers (1489650598956 (2), 1578284085800 (2), 1.0 (2) in bold) appear in same row?

<img width="1396" alt="screen shot 2017-03-16 at 3 34 29 pm" src="https://cloud.githubusercontent.com/assets/26456510/23991190/7a0f7d98-0a5e-11e7-880a-c06ea3b6d4e8.png">

**Comment by mportuga** [comment]
That is working as intended. It works the same in other grids too: 
https://www.ag-grid.com/example.php
https://www.jqwidgets.com/jquery-widgets-demo/demos/jqxgrid/index.htm#demos/jqxgrid/grouping.htm

This is more of a feature request rather than a bug. We would certainly accept a PR making this change, but it is not a priority.

**Comment by Vibha19gn** [comment]
Thanks for the response.I wanted to know if a feature like this existed in UI grid.I didn't intend it to be a bug.
