### ISSUE TITLE
Cell data bound event

### ISSUE THREAD

**Issue by rtprakash** [angular-ui/ui-grid#6087]
This is not an issue, just want to know whether any event available on cell data bound. Need to disable/enable cell edit based on the data. For example based on the data i want to enable edit on Row1 - Column1 and disable edit on Row2 - Column1.

**Comment by jniles** [comment]
Will the [cellEditableCondition](http://ui-grid.info/docs/#/api/ui.grid.edit.api:GridOptions)  work?  You have access to both the rows and columns, so that should give you all the information you require.
