### ISSUE TITLE
japanese i18nService not have grouping and validate values 

### ISSUE THREAD

**Issue by kawatanabe** [angular-ui/ui-grid#6089]
I tried to use grid grouping by 'ja' locale ,but not worked.
So, i18nService  does not have grouping and validate values.
(other language has each values)

**Comment by mportuga** [comment]
If you know the proper translations for Japanese, we will gladly accept a PR with those translations.

**Comment by mportuga** [comment]
This issue was fixed on version 4.0.4 with the following commit:
https://github.com/angular-ui/ui-grid/commit/47e78d16710a96033c692f800c5bb4874f694fc8
