### ISSUE TITLE
Rendering issue in IE11 with column percentage width 

### ISSUE THREAD

**Issue by fredrik01234** [angular-ui/ui-grid#6095]
Defining multiple columns with percentage as width casues IE11 and FF to render the last column on next row when resizing.

Example on plunker....
http://plnkr.co/edit/EDy3hmRHkLMosYyn5XB4?p=preview

Start in IE11 and just resize the grid window to different sizes and on some sizes it fails to render grid propperly like belop picture.

![ie11](https://cloud.githubusercontent.com/assets/26548409/24106933/b7a6e82a-0d89-11e7-8722-b967072eee69.PNG)

Tested with latest ui-grid 402
/Fredrik

**Comment by madhurshome** [comment]
I'm also facing the same issue. Does anyone know the fix?
