### ISSUE TITLE
Duplicate IDs when using "ui-grid-selection"

### ISSUE THREAD

**Issue by dburgener-ipayables** [angular-ui/ui-grid#6096]
When I use "ui-grid-selection", the div that holds the column for the checkboxes, has the same ID as the div that holds the rest of the columns. This fails ADA compliance. I am using v3.1.1

![image](https://cloud.githubusercontent.com/assets/16689900/24108754/2e7a0d50-0d54-11e7-9da5-bc54495bf460.png)

**Comment by mportuga** [comment]
Is this issue still reproducible in v4.0.3?

**Comment by dburgener-ipayables** [comment]
@mportuga I just upgraded to 4.0.4, and the issue is still there.

**Comment by mportuga** [comment]
The issue still exists for rows.
