### ISSUE TITLE
UI-Grid Customizer Page Error when I don't add a / at the end of the URL

### ISSUE THREAD

**Issue by aguirre1017** [angular-ui/ui-grid#6100]
The [customizer page](http://ui-grid.info/customizer) is having an error while accessing.

**Comment by mportuga** [comment]
That is interesting. So, if you go to http://ui-grid.info/customizer/, the page loads as expected, however, if you go to http://ui-grid.info/customizer, the page gets an error. The only difference is the presence of a / at the end. I am not sure why that is the case.

**Comment by aguirre1017** [comment]
Might be a server issue. As per my check now, they already change the customize link with / at the menu.
