### ISSUE TITLE
Page Footer Row Count Not Correct

### ISSUE THREAD

**Issue by ckelley7** [angular-ui/ui-grid#6104]
In v4.0.2 when pagination is enabled, the default page footer displays on the far right "**i** - **j** of **N** items" where **i** is ordinal of the first item displayed on the page, **j** is the ordinal of the last item displayed on the page and **N** is the total items on all pages.  The defect is that **j** is always off by one on the high side.  You can see this behavior at http://ui-grid.info/docs/#/api/ui.grid.pagination.directive:uiGridPagination.  For example, on the last page of this grid, it should say "11 - 12 of 12 items".  Instead, it displays "11 - 13 of 12 items".

**Comment by mportuga** [comment]
This issue was resolved in v4.0.3
