### ISSUE TITLE
Long tooltips get truncated in Internet Explorer

### ISSUE THREAD

**Issue by soyiatgit** [angular-ui/ui-grid#6115]
The large tooltip in IE gets truncated after a certain amount of text. Not pretty sure if the word limit is fixed ( as I got two different limits). However, I confirmed this issue on ui-grid docs site by editing the columns.

Is it a known issue. Is any work around available ?

**Comment by mportuga** [comment]
We are not using custom tooltips in ui-grid, just standard HTML ones. So my guess is that this is just default IE behavior.
