### ISSUE TITLE
Change Columns Data

### ISSUE THREAD

**Issue by rahi-rajeev** [angular-ui/ui-grid#6121]
Hello Team,
I have a problem 
let me explain in table cell i am displaying value like enable/disable when user in select this row then ajax will call after response i want to change this row particular cell data like 
$scope.gridOptions.data["status"] ="Enabled";
$scope.gridOptions.data.status ="Enabled";
i mean i want to change particular column value 
its not working

**Comment by mportuga** [comment]
Can you provide a plunker of your issue? I tried reproducing it and couldn't.

See my plunker: http://plnkr.co/edit/cRPtNoQFBAABh3t1Fy77?p=preview

**Comment by mportuga** [comment]
Actually, I just found an example that is closer to what you described. Try using the notifyGridChange API, similar to this PR.
http://plnkr.co/edit/l5j1ECD99QHhSImtRn5F?p=preview

**Comment by rahi-rajeev** [comment]
Hi,
Let me explain supposed I have select 3 row then I have button like enable
which is used to enable status when I click on this button then I got
selected rows I just to change text of status of these rows

**Comment by mportuga** [comment]
@rahi-rajeev Could you make a plunker with your example? It is hard to help out of the description alone. But notifyDataChange still seems like the solution to me

**Comment by rahi-rajeev** [comment]
@mportuga  thanks
