### ISSUE TITLE
SVG rendering 

### ISSUE THREAD

**Issue by juunp** [angular-ui/ui-grid#6124]
Hello,
I'm trying to add a svg donut chart to my grid. It works well for the first rows but upon scrolling,
the donut chart does not represent the data from its cell. 
Here's the [plnkr](http://plnkr.co/edit/taLtXlKDitr0kwbOm77r)

**Comment by mportuga** [comment]
I saw no issues with scrolling on Mac Chrome. Could this be a browser or OS specific issue? What devices is this issue reproducible in?

**Comment by juunp** [comment]
@mportuga Chrome 56, Chrome 59, Firefox dev edition 54.0a2 on Windows 
For example, in the first rows, you get a half-circle when data is equal to 50 and when you scroll down, you get a full circle for the same value.
I'm going to investigate for a few hours today.

**Comment by mportuga** [comment]
@juunp Thank you!

**Comment by juunp** [comment]
After investigating a little, I think the problem happens when the virtualization is enabled.
I tried with less than 20 rows and couldn't reproduce the issue.
After a few tests, I saw it happened only when the rendered rows are updated (so not after every scroll). Does someone have an idea why it happens?

**Comment by juunp** [comment]
The error was occurring because of the use of JS primitive instead of an object for example. The binding was lost  in the directive I used to display the donut chart.
See: https://github.com/angular/angular.js/wiki/Understanding-Scopes
