### ISSUE TITLE
Selection issues with groupHeader row(s) in single selection grid

### ISSUE THREAD

**Issue by troywoy** [angular-ui/ui-grid#6126]
When implementing a single selection grid via `multiSelect: false`, group header rows do not adhere to this rule. When selecting a group row, it is not deselected when changing your selection (it is only deselected if manually deselected).

As seen in [this plunkr](http://plnkr.co/edit/wTslEK4XN27t7NYO2VQi?p=preview), if you select any group row it will remain selected until you uncheck it directly. This is not an issue for non-group header rows as they adhere to the single selection logic properly.

I can only assume this has to do with the idea of *"selecting a parent selects all it's children"*, but that's not the use case in my grid. If this logic is deemed correct, which I don't think it is, then providing a configuration to truly act as a single selection grid would suffice.

**Comment by twh1808** [comment]
I dug into the source code to provide some more useful information...

The [getSelectedRows](https://github.com/angular-ui/ui-grid/blob/master/src/features/selection/js/selection.js#L542-L546) service method acts upon `grid.rows` which is the flat data array. This data has no reference to group rows, and therefore cannot return selected group rows (which is needed when clearing the current selection).

I have hacked together a local solution, but it is by no means ideal. I'm currently using `gridApi.grid.grouping.groupingHeaderCache` to obtain the group rows to deselect them, if necessary. I'm not sure if that's a solution for fixing this issue, but it's definitely not something that should live in my code.

Hope this helps.
