### ISSUE TITLE
ui-grid expandable-disabling expandable module

### ISSUE THREAD

**Issue by avuthubhargavreddy** [angular-ui/ui-grid#6131]
using expandable grid, while expanding getting below error:
You have not set the expandableRowTemplate, disabling expandable module.
I have defined  $scope.gridOptions = {
expandableRowTemplate:'/../../Scripts/app/components/BatchManagement/expandableRowTemplate.html',
        expandableRowHeight: 150,
        expandableRowScope: {
            subGridVariable: 'subGridScopeVariable',
        }
}

**Comment by mportuga** [comment]
Cannot reproduce: http://plnkr.co/edit/bNbzBODForti2lKCZTf8?p=preview
