### ISSUE TITLE
Use Angular Component in cellTemplate with binding

### ISSUE THREAD

**Issue by profHubertFarnsworth** [angular-ui/ui-grid#6138]
Please take a look at this example - http://plnkr.co/edit/qkMbMHa4swVH9aL1lrRB?p=preview

What I am trying to achieve - I want have cellTemplate as angular component. I want pass data through component binding.  I can show component in cellTemplate , but looks like binding for this component does not work.
My task - pass data from column cell into angular component that will be in column cell. 
Is it achievable with angular ui? Or in that case I should construct DOM html elements in cellTemplate directly

**Comment by FrontPsych** [comment]
You've forgot to separate the attribute on the component by slashes, since your binding is in camel case. Example: http://plnkr.co/edit/5KKlIZ8vPqXDjlxXPK8A?p=preview

**Comment by profHubertFarnsworth** [comment]
It is achievable! Great Thanks @FrontPsych , I close the issue.
