### ISSUE TITLE
Exporting twice in PDF displays invalid image error

### ISSUE THREAD

**Issue by Jozkee** [angular-ui/ui-grid#6142]
I have an image inserted in the pdf header like this

$scope.gridOptions = {
    exporterPdfHeader: {
        margin: [35,15,10,10],
        columns: [ { image: getBase64Image(img), width:150}]
    }
}

 where getBase64Image is defined like this:
function getBase64Image(img) {
    // Create an empty canvas element
    var canvas = document.createElement("canvas");
    canvas.width = img.width;
    canvas.height = img.height;
    // Copy the image contents to the canvas
    var ctx = canvas.getContext("2d");
    ctx.drawImage(img, 0, 0);
    // Get the data-URL formatted image
    var dataURL = canvas.toDataURL("image/png");
    return dataURL;//.replace(/^data:image\/(png|jpg);base64,/, "");
}

So when I call pdfExport in the grid it exports correctly the first time.
If i try to export once again pdfmake displays the next error:
_invalid image, images dictionary should contain dataURL entries (or local file paths in node.js)_

So debugging I found that the image property in columns after the first export was this **image: "$$pdfmake$$1"** instead of the base64 string.

Is it because of the version? I'm in 3.9.2

Any help would be appreciated.

**Comment by ts-de** [comment]
same issue here
