### ISSUE TITLE
getSelectedRows cannot return selected groupHeader rows

### ISSUE THREAD

**Issue by troywoy** [angular-ui/ui-grid#6145]
Obtaining the selected rows when `enableGroupHeaderSelection: true` is applied will never return group rows, as seen in [this plunkr](http://plnkr.co/edit/DnRJflJYYeY70rQC9Ymi?p=preview). If you select row(s) and then click the `console.log(...)` button, it will only ever log child rows regardless of what groups you have selected.

The [getSelectedRows](https://github.com/angular-ui/ui-grid/blob/master/src/features/selection/js/selection.js#L542-L546) service method acts upon `grid.rows` which is the flat data array, there is no `treeBase` traversal.

This can be associated with Issue #6126, as both relate to `getSelectedRows` acting upon `grid.rows` and nothing associated with `treeBase`.

**Comment by RepoCorp** [comment]
I'm experiencing the same problem described here and I can see it is solved in #6556. But then the changes introduced in that PR were reverted in b21096b2c275e365e561a39a7987a3e290b3ee59. 

I just need to have any information on the selected header row, or even in any of the children rows, when the user clicks in a group header row.
