### ISSUE TITLE
NuGet package is outdated

### ISSUE THREAD

**Issue by ChristianHaase** [angular-ui/ui-grid#6153]
The current ui-grid.js file received with NuGet is the 4.0.2 version, whereas getting the files with npm gives me 4.0.4. Just a heads up.

**Comment by MatejQ** [comment]
I thought so too until ui-grid authors wrote me that they have no control of the nuget package, as it is maintained by someone else. I wrote to the author of nuget package and he updated it in a day or so. It is now current and can be used for new version. But I would propose the authors of ui-grid to take the nuget package over from the 3rd party to have it always current and prevent future confusion.

**Comment by ChristianHaase** [comment]
Alright. Thank you.
