### ISSUE TITLE
Error grid in two tabs

### ISSUE THREAD

**Issue by Ederagp** [angular-ui/ui-grid#6154]
**Using version 4.0.4**

I have two grids as shown below, when I choose the tab to see the grid does not fit the sizes of the columns in one of them, this can happen in the two grid, sometimes does not display the data. The main.css contains:
.grid {
   Width: 100%;
   Height: 250px;
}

![captura de pantalla 2017-04-06 a las 2 45 44 p m](https://cloud.githubusercontent.com/assets/23706190/24772842/7883cd0a-1ad8-11e7-81e5-4c44f7aacd90.png)
![captura de pantalla 2017-04-06 a las 2 45 26 p m](https://cloud.githubusercontent.com/assets/23706190/24772843/788719b0-1ad8-11e7-9756-74765d5df7d9.png)

**Comment by troywoy** [comment]
You probably either need to use `ui-grid-auto-resize` or call `gridApi.core.handleWindowResize();` yourself on tab change.

**Comment by Ederagp** [comment]
Solved with `gridApi.core.handleWindowResize();`
