### ISSUE TITLE
update from 4.0.2 to 4.0.4, grid shows nothing and no console error

### ISSUE THREAD

**Issue by RaeCai** [angular-ui/ui-grid#6156]
Hi,
I am updating ui grid from 4.0.2 to 4.0.4 to solve grid menu error(following screen shot) related with ui-grid-exporter.
![capture](https://cloud.githubusercontent.com/assets/8730424/24931006/95324d82-1ed9-11e7-9d1f-9641e20445c1.PNG)
but after ui grid lib updated, grid shows nothing and no error in console, only grid menu shows 2 options.
have anyone has the same issue?
![2](https://cloud.githubusercontent.com/assets/8730424/24931134/18878e18-1eda-11e7-983b-b8f65dfc2f59.PNG)

**Comment by bnaand** [comment]
Are you setting data source with string value? 
Maybe it's related to this issue: https://github.com/angular-ui/ui-grid/issues/6155

**Comment by RaeCai** [comment]
@bnaand yes, I am using string value to set the data source. is there any fix to this issue?

**Comment by RaeCai** [comment]
from 4.0.3, ui grid is not taking data source with string, which is setting data on $scope: $scope.data = data; And then direct the grid to resolve whatever is in $scope.data: $scope.gridOptions.data = 'data'; 
issue solved by using $http.get('/data/100.json') .success(function(data) { $scope.myData = data; $scope.gridOptions.data = $scope.myData; });
Where you do this, you need to take care in updating the data - you can't just update $scope.myData to some other array, you need to update $scope.gridOptions.data to point to that new array as well.
