### ISSUE TITLE
Is it possible to group by array field?

### ISSUE THREAD

**Issue by nhvu1988** [angular-ui/ui-grid#6161]
In this fiddle https://jsfiddle.net/j3dnm6q7/, I have data as

    [
        { "name": "object 1", "category": ["cate 1", "cate 2"] },
        { "name": "object 2", "category": ["cate 1"] },
        { "name": "object 3", "category": ["cate 2"] }
    ]

In the ui-grid, it's ok for showing as the array but I can't make it group by separated category. It means when I press button "Group by category", only "Cate 1" and "Cate 2" will show and following the logic

 - Cate 1: contains "object 1" and "object 2"
 - Cate 2: contains "object 1" and "object 3"

Could ui-grid do that? or do I need to customize something?

Thank you

**Comment by torava** [comment]
I'd like to ask the same question. Is there an answer?

**Comment by nhvu1988** [comment]
> I'd like to ask the same question. Is there an answer?
I have my own solution [here](http://nhvu1988.com/blogs/20170502-how-to-group-on-array-field-with-angular-ui-grid/), hope it helps
