### ISSUE TITLE
this link http://ui-grid.info no response

### ISSUE THREAD

**Issue by jcsalberto** [angular-ui/ui-grid#6162]
this link http://ui-grid.info no response

**Comment by mattbrunetti** [comment]
Anyone needing documentation right away can use the following
- browse https://github.com/angular-ui/ui-grid/tree/master/misc
- clone this repo and build the documentation site yourself locally (will be built from source in /misc/site)
- browse https://github.com/angular-ui/ui-grid/wiki

**Comment by subhayanbanerjee** [comment]
When the site is expected to be up?

**Comment by mattbrunetti** [comment]
It's back up

**Comment by subhayanbanerjee** [comment]
Thank you very much.
