### ISSUE TITLE
bug in exporter.js - loadAllDataIfNeeded ignores exporterAllDataFn() retrun value

### ISSUE THREAD

**Issue by eharshosh** [angular-ui/ui-grid#6163]
using the latest release (4.0.4), found the following bug:
when defining an exporterAllDataFn in the grid.options, the function is called but the result of it is ignored:
```
 loadAllDataIfNeeded: function (grid, rowTypes, colTypes) {
          if ( rowTypes === uiGridExporterConstants.ALL && grid.rows.length !== grid.options.totalItems && grid.options.exporterAllDataFn) {
            return grid.options.exporterAllDataFn()
              .then(function() {
                grid.modifyRows(grid.options.data);
              });
          } else {
            var deferred = $q.defer();
            deferred.resolve();
            return deferred.promise;
          }
        },
```
I see two problems with that:

1. The function loadAllDataIfNeeded assumes that the user function exporterAllDataFn manipulates the grid.options.data value, while in some cases this is not the desired behavior (for example, when the developer decides to use pagination and ignore the 'data' object).
2. I think that the expected behavior is that the csvExport/pdfExport function won't alter the table but rather will use it's current data or call and use exporterAllDataFn() data if needed.

**Comment by miderose** [comment]
+1
I have the same problem...
