### ISSUE TITLE
http://ui-grid.info/ not working 

### ISSUE THREAD

**Issue by faraziny** [angular-ui/ui-grid#6166]
My app was working fine but suddenly it broke today due to unavailability of http://ui-grid.info/

Please find the error below for reference.

Uncaught Error: [$injector:modulerr] Failed to instantiate module chmApp due to:
Error: [$injector:modulerr] Failed to instantiate module ui.grid due to:
Error: [$injector:nomod] Module 'ui.grid' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.3/$injector/nomod?p0=ui.grid
at http://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.js:68:12
at http://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.js:1958:17
at ensure (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.js:1882:38)
at module (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.js:1956:14)
at http://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.js:4362:22
at forEach (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.js:336:20)
at loadModules (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.js:4346:5)
at http://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.js:4363:40
at forEach (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.js:336:20)
at loadModules (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.js:4346:5)
http://errors.angularjs.org/1.4.3/$injector/modulerr?

**Comment by bgx90** [comment]
I get a DNS error when I try to access http://ui-grid.info in my browser.

**Comment by theodoretripp** [comment]
It's also not working for me.  Similar to bgx90.

**Comment by pedroafsouza** [comment]
It is also not working for me. Is it normal to happen?

**Comment by FrancescoRizzi** [comment]
+1 (Southeast US)

**Comment by mbostwick** [comment]
I was using it yesterday, so it was working..

**Comment by jsmtslch** [comment]
In our QA environment, it is working where I just use it as a grid to show some data. But on import functionality it is broken. It was working yesterday.

**Comment by mbostwick** [comment]
There is no a record for the site, does anyone know the IP Information, so we can see if its reachable with out the DNS server ?

**Comment by mbostwick** [comment]
Historic DNS information..
https://mxtoolbox.com/archive/?actionstring=a:ui-grid.info
 The A Record is gone..

**Comment by mbostwick** [comment]
This is definitely a DNS issue. Forging the DNS in my hosts file triggers the page to work..
192.30.252.153	ui-grid.info

https://help.github.com/articles/troubleshooting-custom-domains/#github-repository-setup-errors

**Comment by bhuvangu** [comment]
Till site is not back:
https://github.com/angular-ui/ui-grid/tree/7242092f8d3c0209203981d43e37256fdc59253d/misc

**Comment by pagoenka** [comment]
Site is not working for me as well, till time it is back I am using https://angular-ui.github.io/ui-grid/

**Comment by MJHeijster** [comment]
Judging by the current nameservers (FAILED-WHOIS-VERIFICATION.NAMECHEAP.COM and VERIFY-CONTACT-DETAILS.NAMECHEAP.COM), they need to verify their contact information..

**Comment by mattbrunetti** [comment]
@pagoenka The first link is for ng-grid, which is what it was named before it was rewritten

**Comment by mattbrunetti** [comment]
@faraziny Please look to see if the issue exists already before creating a duplicate. Please close this and let's use the original issue to discuss/complain. #6162
