### ISSUE TITLE
Server was down for last two days. Currently it is very very slow to respond.

### ISSUE THREAD

**Issue by subhayanbanerjee** [angular-ui/ui-grid#6168]
Server is down for last two days. Currently for long time it says "waiting for ui-grid.info". Please see what is the problem.

**Comment by irwanayeah** [comment]
yes, I have same problem.

**Comment by mattbrunetti** [comment]
Please look to see if the issue exists already before creating a duplicate. Please close this and use the original issue to discuss/complain. #6162
