### ISSUE TITLE
selectItem does not work when number of rows is over virtualizationThreshold

### ISSUE THREAD

**Issue by gillius** [angular-ui/ui-grid#617]
From my understanding of selectItem, based on the "Row Selection Example" at http://angular-ui.github.io/ng-grid/ is that it should select items based on their index in the data array. However, this doesn't work if row virtualization is active. For example I make a button that calls selectItem(0, true), then when number of rows is more than virtualizationThreshold, the row that gets selected is based on where I have scrolled in the list, rather than the first row.

A workaround is to set virtualizationThreshold so large that virtualization is never used, but performance is unusable for large datasets.

As a note, what I'm trying to do is sync a list of selected items INTO the list. At first I thought that I could just update the selectedItems field, but due to #231, this does not work. So what I am doing is calling gridOptions.selectAll( false ) and then for each item I want to select, I find the index of it in gridOptions.data, and call gridOptions.selectItem. I also tried selectRow but it appears to have the same behavior as selectItem -- that is, the rows selected for a given index depends on where I have scrolled into the list.

**Comment by abyx** [comment]
@gillius I'm now having the exact same issue. Any chance that you still remember this and can tell whether your workaround introduced any problems?
