### ISSUE TITLE
Error: [$compile:ctreq] Controller 'uiGrid', required by directive 'uiGridMenu', can't be found!

### ISSUE THREAD

**Issue by ganeshvelanki** [angular-ui/ui-grid#6180]
I want to know why this issue arrises in my code(version 4.04), how I fix it. Any help would be greatful. Error strikes when I click on the grid menu button.

![image](https://cloud.githubusercontent.com/assets/11549787/25437345/a53a87a4-2ab3-11e7-9bbf-cf80bc68e624.png)

**Comment by mportuga** [comment]
This issue has been fixed as of version 4.2.1
