### ISSUE TITLE
File picker on editable cell is broken on Chrome

### ISSUE THREAD

**Issue by serpulga** [angular-ui/ui-grid#6182]
I'm trying to use the editable cell option with a file input.
Seeing the example at:
http://ui-grid.info/docs/#/tutorial/201_editable example 

I found out that this tutorial works on **Firefox v48.0**, but not on **Chrome v57.0.2987.133**. In Chrome, when a file is selected there is no file name on the cell, and the "Last Cell Edited" and "Fast file uploaded" information doesn't show up.

I did try to troubleshoot this error, and I found out that the `change` event handler that is registered inside the `uiGridEditFileChooser` directive:

```javascript
$elm[0].addEventListener('change', handleFileSelect, false);
```
Is not triggering for me on Chrome, so the handler  `handleFileSelect` is not running.

I'm 80% sure that this worked before at some point.

**Comment by claudiajohst** [comment]
I'm having the same issue

**Comment by mportuga** [comment]
A fix for this has just been pushed and will be available in the next release.
