### ISSUE TITLE
can we add parameter for cellTemplate in columnDefs?

### ISSUE THREAD

**Issue by xycloud** [angular-ui/ui-grid#6183]
can we add parameter for cellTemplate in columnDefs?

**Comment by deeppatidar** [comment]
@xycloud : question didn't get exactly,  but you can define or add type field in columnDef and on the basis of field type you can use a different template like date and int, string etc..

**Comment by mportuga** [comment]
yes. See the following example: http://ui-grid.info/docs/#!/tutorial/317_custom_templates
