### ISSUE TITLE
ng-grid does not allow 'controller as' syntax for gridOptions.data

### ISSUE THREAD

**Issue by dburgener-ipayables** [angular-ui/ui-grid#6185]
We were using version 3.1.1 and recently upgraded to 4.0.4, and now we are having an issue with the grid not showing our data. We are using controller as syntax.

Here is the gridOptions setup
```
model.gridOptions = {
				....
				data: 'model.data'
			};
```

We perform a "search" feature that returns the data and assigns it to model.data, but it doesn't show up on the grid.
```
model.data = dataFromAPI;
```

But, If I switch it to 
```
model.gridOptions = {
				....
				data: 'data'
			};
.....
$scope.data = dataFromAPI;
```
it works.

**Comment by phyzalis** [comment]
+1

**Comment by mportuga** [comment]
This will be solved by this PR on the next release: https://github.com/angular-ui/ui-grid/pull/6649
