### ISSUE TITLE
How to group column by it's ID and display by it's name

### ISSUE THREAD

**Issue by varunpradhan** [angular-ui/ui-grid#6187]
Hi,
I have to group the name with it's ID and display it's name.
I have tried to group it by name but there are 2 different IDs for the same name which needs to be separated.

How to do that?

Below is the code I used in my project:

inviteSupplierColumnDefs.push({
        displayName: translationService.getTranslation(translationService.SUPPLIER_ORG_NAME),
        width: showSLMColumns(slmAvailable, user) ? '9%' : '15%',
        field: 'user.organization.name',
        grouping: {groupPriority: 0},
        sort: {priority: 0, direction: 'asc'},
        cellTemplate: getSupplierNameTemplate(),
        enableHiding: false
      });

this is the service I created and below is it's cell template:

function getSupplierNameTemplate() {
      return '<div class=\'ui-grid-cell-contents\'><div ng-if="!col.grouping || ' +
        'col.grouping.groupPriority === undefined || ' +
        'col.grouping.groupPriority === null || ' +
        'col.grouping.groupBy === null || ' +
        '( row.groupHeader && col.grouping.groupPriority === row.treeLevel )" ' +
        'class="ui-grid-cell-contents" title="TOOLTIP">' +
        '<a style="cursor: hand" id="supplierDetails{{row.uid}}" href ' +
        'title="{{COL_FIELD CUSTOM_FILTERS}}" ' +
        'ng-click="grid.appScope.openSupplierDetailsPopup(row);">' +
        '{{COL_FIELD CUSTOM_FILTERS}}' +
        '</a></div></div>';

**Comment by nbulusanjr** [comment]
Can you create a plunkr?
