### ISSUE TITLE
[$compile:tplrt] given when using ui-grid

### ISSUE THREAD

**Issue by tanayarc** [angular-ui/ui-grid#6192]
I am using angular1.5.8 and ui-grid version 4.0.4, and kendo 2015.2.624. All these are installed from nuget console. 
My code was:
In APP:
var myApp = angular.module('myApp ', ['ui.router', 'kendo.directives', 'angularUtils.directives.uiBreadcrumbs', 'ngSanitize', 'ui.grid', 'ui.grid.selection']);

In Module:
 $scope.result = [{
        "firstName": "A",        
        "company": "xx"       
    }, {
        "firstName": "B",       
        "company": "yy"       
    }, {
        "firstName": "C",       
        "company": "zz"      
    }];    
    
    $scope.gridOptions = {
        data: $scope.result,      
        enableFiltering: true,
        showGridFooter: true,
        gridFooterTemplate: '<div></div>',      
        columnDefs: [                          
                          { field: 'firstName', width: 125 },                       
                          { field: 'company', width: 275 }
        ]       
    };

In CSHTML:
 Using ui-grid="gridOptionsEmpMaint" in "div" tag

Console error is given below:
angular:1 Error: [$compile:tplrt] http://errors.angularjs.org/1.5.8/$compile/tplrt?p0=uiGrid&p1=ui-grid%2Fui-grid
    at angular:1
    at angular:1
    at angular:1
    at p.$eval (angular:1)
    at p.$digest (angular:1)
    at p.$apply  @(angular:1)
    at et (angular:1)
    at rt (angular:1)
    at XMLHttpRequest.nt.onload (angular:1)

I am failed to resolved this issue. please help...

**Comment by mportuga** [comment]
Can you provide a plunker of the issue?
