### ISSUE TITLE
Sort order number sequencing is not re-adjusting when columns are removed from sort

### ISSUE THREAD

**Issue by santnair** [angular-ui/ui-grid#6195]
Issue - The number sequencing when you sort on more than 2 columns is not adjusting when an intermediate column is removed from the sort. This leads to confusion when a user sees columns with "2" and "3" sorting for e.g, but does not see the column with "1".

Steps to reproduce:

1. Load the UI grid
2. Sort on column "Name"
3. Click on the arrow beside "Age" column and select "Sort Ascending" (or "Sort Descending" doesn't matter). This enables the numbering sequence and assigns "1" to "Name" and "2" to "Age"
4. Click on "Address" column and select "Sort Ascending/Descending". This will assign "3" to that column
5. Now go to "Name column and select "Remove Sort". Now we see the problem. The "1" sort number on "Name" column goes away but "Age" and "Address" still shows "2" and "3". 
The expected behavior is to remove sort on "Name" and readjust the sort numbering of the other columns. 

Plunker URL - http://plnkr.co/edit/qV71EiOXJBkWzDLYRxmT?p=preview

**Comment by mportuga** [comment]
No longer reproducible on the latest version.

**Comment by santnair** [comment]
Thanks. I'll check it out.
