### ISSUE TITLE
Column header click sort sequence is not natural behavior

### ISSUE THREAD

**Issue by santnair** [angular-ui/ui-grid#6196]
Issue - You click on column header, it sorts ascending... click one more time, it sorts descending.. click one more time... it removes the sort.  This behavior is unnatural to what users expect. 

Steps to reproduce -
1. Load the UI grid
2. Click on column header for "Age" (or any) to sort it - it sorts ascending
3. Click again on the same column header - it sorts descending
4. Click again on the same column header - it removes the sort!

Expected - The 3rd click in this case should again sort ascending; if user wants to remove sort he would use the "Remove Sort" option from the column menu.

Plunker URL - http://plnkr.co/edit/qV71EiOXJBkWzDLYRxmT?p=preview

**Comment by mportuga** [comment]
That is customizable behavior, see sortDirectionCycle option on API documentation: http://ui-grid.info/docs/#!/api/ui.grid.class:GridOptions.columnDef
