### ISSUE TITLE
filter function hyphen/dash backslash escaping issue

### ISSUE THREAD

**Issue by joshribakoff** [angular-ui/ui-grid#6208]
http://ui-grid.info/docs/#/tutorial/103_filtering
> the condition field of the filter object can also be a function 

```
function myCustomSorter(searchTerm, cellValue, row, column) {
  // Custom logic that returns true if `row`
  // passes the filter and false if it should
  // be filtered out
  return booleanResult;
}
```

When I use this function & try to filter for `fat-free`, the value of `searchTerm` is `fat\-free`. This is not documented & does not follow any logical escaping convention I know of, so I feel it is a bug. Is true as of 4.0.4, with angular 1.4.x

If I delete myCustomSorter and just set `enableFiltering` `true`, it uses the default filtering which handles the dash fine.

**Comment by rognstad** [comment]
The searchTerm is escaped such that it will work in a RegExp. You can use that for your test or use the filter.rawTerm option to get the unmodified search term.
