### ISSUE TITLE
Color of ui-grid cell template changes on click

### ISSUE THREAD

**Issue by soyiatgit** [angular-ui/ui-grid#6213]
I have a ui-grid column having cellTemplate:

`<div class="ui-grid-cell-contents" ``ng-style="{\'background-color\':row.entity.color}">{{row.entity.value}}</div>`

The color is displayed fine. However, when the user clicks the cell, the color goes way. It is replaced by the `default color on other columns. If the user clicks any other cell, the color is then restored.

Any suggestions?

**Comment by mportuga** [comment]
Cannot reproduce: http://plnkr.co/edit/eqxxQg49D4bJO0vbm1zq?p=preview
