### ISSUE TITLE
Tests fail on master

### ISSUE THREAD

**Issue by McGiogen** [angular-ui/ui-grid#6214]
I'm trying to submit a small pull request about the sort icon (now if the header text is longer than the column width the sort icon is never visible). I followed the [first timer guide](https://github.com/angular-ui/ui-grid/blob/master/FIRST_TIMER.md) forking from master but with `grunt test:e2e` one test fails and `grunt` default task works only with "force" flag.
Another user had [the same problem](https://github.com/angular-ui/ui-grid/pull/6046#issuecomment-293019791).

```
$ grunt test:e2e
Failures:
1) ui-grid tutorial/122_accessibility accessibility tests first grid on page, no virtual data. when column menu is closed by hiding the column should move the focus to the nearest header button unless there is no column then should move to the grid menu
  Message:
    Expected '<very long html>'
Stack:
    Error: Failed expectation
        at expectToBeFocused (/home/scacco/workspace/forks/ui-grid/.tmp/doc-scenarios/doc-tutorial.spec.js:714:11)
        at /home/scacco/workspace/forks/ui-grid/.tmp/doc-scenarios/doc-tutorial.spec.js:740:24
        at ManagedPromise.invokeCallback_ (/home/scacco/workspace/forks/ui-grid/node_modules/selenium-webdriver/lib/promise.js:1379:14)
        at TaskQueue.execute_ (/home/scacco/workspace/forks/ui-grid/node_modules/selenium-webdriver/lib/promise.js:2913:14)
        at TaskQueue.executeNext_ (/home/scacco/workspace/forks/ui-grid/node_modules/selenium-webdriver/lib/promise.js:2896:21)
        at asyncRun (/home/scacco/workspace/forks/ui-grid/node_modules/selenium-webdriver/lib/promise.js:2775:27)
        at /home/scacco/workspace/forks/ui-grid/node_modules/selenium-webdriver/lib/promise.js:639:7
        at process._tickCallback (internal/process/next_tick.js:103:7)
  Message:
>> (node:3870) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
```
```
$ grunt
... <other tasks> ...
Running "karmangular" task
Loading "grunt-karma.js" tasks...ERROR
>> TypeError: Cannot read property 'prototype' of undefined
Warning: Task "karma:angular-1.4.3" failed. Use --force to continue.

Aborted due to warnings.

$ grunt --force
... <other tasks> ...
Running "karmangular" task
Loading "grunt-karma.js" tasks...ERROR
>> TypeError: Cannot read property 'prototype' of undefined
Warning: Task "karma:angular-1.4.3" failed. Used --force, continuing.
Loading "grunt-karma.js" tasks...ERROR
>> TypeError: Cannot read property 'prototype' of undefined
Warning: Task "karma:angular-1.5.0" failed. Used --force, continuing.
... <other tasks> ...

Done, but with warnings.
```
Can you help me to resolve those errors?

**Comment by rdkleine** [comment]
I'm getting the same error when running grunt. 
`Running "karmangular" task
Loading "grunt-karma.js" tasks...ERROR
>> TypeError: Cannot read property 'prototype' of undefined
Warning: Task "karma:angular-1.4.3" failed. Use --force to continue.`

**Comment by ian-gallagher** [comment]
I synced my fork and on master I am getting a similar error.

Running "karmangular" task
Loading "grunt-karma.js" tasks...ERROR
>> TypeError: Cannot read property 'prototype' of undefined
Warning: Task "karma:angular-1.4.3" failed. Use --force to continue.

Any ideas?

**Comment by ABSoftAsia** [comment]
I face the same problem in build release version v4.1.0.
My node.js version now is v9.1.0, then I change different versions of node.js and try to rebuild:

node-v8.9.4-win-x64 - shows the same error
node-v6.12.3-win-x64 - OK

Hope this info world help.

**Comment by riatiger** [comment]
I also see this error in build release v4.1.0.
Node version: 8.9.1

**Comment by caseyjhol** [comment]
The included versions of Karma and grunt-karma are too old. Node 6 support wasn't added until v1.0.0 of Karma (https://github.com/karma-runner/karma/blob/master/CHANGELOG.md#100-2016-06-23). Updating Karma and grunt-karma allowed the tests to run.

**Comment by m4m4m4** [comment]
I had to update selenium server and webdriver to the latest version as well, after that the default grunt task runs without issues (Windows 10)

**Comment by mportuga** [comment]
@m4m4m4 Could you open a pull request with those upgrades? That was one of the things that I wanted done soon.
