### ISSUE TITLE
Pinned column - broken header

### ISSUE THREAD

**Issue by Azbesciak** [angular-ui/ui-grid#6230]
Hello, i have following problem with pinned columns - checked on 3.3.3 and 4.0.4 version:
after creating grid the pinned column's headers differ from others by height  - more over there is no reason for that behavior. To say more, after resize window, everything is alright.
![image](https://cloud.githubusercontent.com/assets/17334466/26400325/ba672dfc-4080-11e7-8dc8-2a46a7b5a1ef.png)

**Comment by mportuga** [comment]
Cannot reproduce:
http://plnkr.co/edit/?p=preview
