### ISSUE TITLE
UI grid refresh issue

### ISSUE THREAD

**Issue by nagamani71093** [angular-ui/ui-grid#6235]
Hi I am facing issue with UI grid data refresh,

Grid data is not displayed in grid after rest API call
I can see "Total Items: 2 (Showing Items: 0)" but grid is empty.

here is the code link - http://plnkr.co/edit/HWdV9XSH95STn7neZEOQ?p=preview

**Comment by ian-gallagher** [comment]
You are attempting to call "match" in this code when "row.entity[field]" is null.

$scope.singleFilter = function( renderableRows ){
    var matcher = new RegExp($scope.filterValue);
    renderableRows.forEach( function( row ) {
      var match = false;
      [ 'JOB_ID', 'SUBMITTED_DATE_TIME', 'STATUS','BENCH_ID', 'BTARGET_ID', 'TEST_DETAILS', 'REPORT_PATH' ].forEach(function( field ){
        if ( row.entity[field].match(matcher) ){
          match = true;
        }
      });
      if ( !match ){
        row.visible = false;
      }
    });
    return renderableRows;
  };

**Comment by nagamani71093** [comment]
Thanks Ian, Its working now :)
