### ISSUE TITLE
AngularJS 1.6 Support

### ISSUE THREAD

**Issue by abyx** [angular-ui/ui-grid#6257]
Hey,

Is there an estimate on a when a release that supports 1.6 will be made?  
A list of known bugs that need help getting there?

I think the project already "officially" supports 1.5 (and dropped 1.3?), but the README says 1.4.
Where is the project really standing?

Thanks!

**Comment by tscislo** [comment]
All plnkr examples use 1.5.0

**Comment by uicoded** [comment]
Can somebody make a list of things that will break on 1.6.x? Upgrade plan

**Comment by mportuga** [comment]
Done as of version 4.1.3
