### ISSUE TITLE
Checkbox (or radio button) in cell template flow when we scroll 

### ISSUE THREAD

**Issue by minhhungit** [angular-ui/ui-grid#6258]
I see an issue with grid when we scoll the grid
I have a custom column with checkbox or radion button, when we scroll down then it will auto select un-selected checkbox, this problem is so weird
Please look at into gif file for more info

https://user-images.githubusercontent.com/2279508/26978432-ba542c7a-4d55-11e7-9ee6-feb58cf5436a.gif

I used latest version 4.0.4

![issue screenshot](https://user-images.githubusercontent.com/2279508/26978432-ba542c7a-4d55-11e7-9ee6-feb58cf5436a.gif)

**Comment by piyush21upadhyay** [comment]
@minhhungit We are also facing the same issue. Could you please let me know as how did you solve it before closing this issue?

**Comment by minhhungit** [comment]
@piyush21upadhyay  I think you need to add **ng-model="xyz"** attribute for the checkbox,  it was so long ago and currently I don't use angularjs anymore so I am not sure if it works for you

**Comment by KumananLingan** [comment]
> @minhhungit We are also facing the same issue. Could you please let me know as how did you solve it before closing this issue?

We also face the same issue. Did the fix provided by Piyush work for you?

**Comment by piyush21upadhyay** [comment]
We added a custom row template, something like below to solve unwanted checkbox issue while scrolling:

`<div ng-class=\"{'ui-grid-row-selected': row.isSelected}\">" +
			'<label><input type=\"checkbox\" ng-model=\"row.isSelected\"' +
			'ng-click=\"row.isSelected=!row.isSelected;selectButtonClick(row, $event)\"><span class="crt-checkmark"></span></label>&nbsp;</div>`
