### ISSUE TITLE
Grid-view's rows and text get selected on resizing column in Safari 10.1 (Mac)

### ISSUE THREAD

**Issue by Gaurav-gs** [angular-ui/ui-grid#6272]
To recreate follow below steps:
[You need to page in Safari(Mac) 10.1]
- Go to http://ui-grid.info/
- Scroll down to "Complex Example"
- Try resizing columns
[you will see rows/text getting selected/deselected randomly]

I create video of the issue: https://drive.google.com/file/d/0B71HBsKyXjJ4ejlpVE85TlpDRHM/view?usp=sharing

**Comment by urielgb413** [comment]
Add
