### ISSUE TITLE
 listen for grid events such as expandable Row ui grid

### ISSUE THREAD

**Issue by estem** [angular-ui/ui-grid#6279]
I using angular ui grid and i want to listen for grid events such as expandable Row ui grid:

  $scope.gridOptions = {
            enableSorting: false,
           // enableRowSelection: true,
           // enableRowSelection: true,
            exporterMenuCsv: false,
            enableGridMenu: true,
            enableSelectAll: true,
            enableColumnResizing: true,
            enableSorting: true,
            expandableRowTemplate: '../../../../MyApp/storyboard/controllers/expandableRowTemplate.html',
            expandableRowHeight: 150,
            //subGridVariable will be available in subGrid scope
            expandableRowScope: {
                subGridVariable: 'subGridScopeVariable'
            },

            columnDefs: [
                { field: 'id',width: '50%',displayName:'ID',cellClass: 'gridField'},
                { field: 'devicetime', cellFilter: 'date:\'yyyy/MM/dd HH:mm:ss\'',width: '20%',displayName:'GPS DATE',cellClass: 'gridField'},
                { field: 'adress',width: '20%',displayName:'ADRESSE',cellClass: 'gridField'},
                { field: 'company',width: '20%',displayName:'COMPANY',cellClass: 'gridField'}

            ],

        };
when i expan a row i want to fire an event..is it posiible??

**Comment by mportuga** [comment]
See the rowExpandedStateChanged event listener on the documentation: http://ui-grid.info/docs/#!/api/ui.grid.expandable.api:PublicApi
