### ISSUE TITLE
Error using ui-grid with requirejs

### ISSUE THREAD

**Issue by RacerDelux** [angular-ui/ui-grid#6288]
I am trying to use ui-grid with requirejs, and I am getting the following error: 

> angular.min.js?bust=v1:2:108 GET http://localhost:63342/ISI-angularjs-requirejs-seed/app/ui-grid/ui-grid 404 (Not Found)

> angular.min.js?bust=v1:2:123 Error: [$compile:tpload] http://errors.angularjs.org/1.6.4/$compile/tpload?p0=ui-grid%2Fui-grid&p1=404&p2=Not%20Found
>     at angular.min.js?bust=v1:2:6
>     at angular.min.js?bust=v1:2:159
>     at angular.min.js?bust=v1:2:134
>     at m.$digest (angular.min.js?bust=v1:2:145)
>     at m.$apply (angular.min.js?bust=v1:2:149)
>     at l (angular.min.js?bust=v1:2:102)
>     at XMLHttpRequest.A.onload (angular.min.js?bust=v1:2:107)

For this error, you have to load the module on a page. `angular.module('isiApp.home', ['ngRoute', 'ui.grid'])`.
I am not sure what is going on here. Currently testing this in an empty project. It only has a single page, and I am only trying to show a grid with some dummy data.

I see many people say it works, so I am inclined to believe that this is something I am doing wrong, but I just can't seem to determine if that is so. Below is my require-config.

> 'use strict';
> 
> if(window.__karma__) {
> 	var allTestFiles = [];
> 	var TEST_REGEXP = /spec\.js$/;
> 
> 	var pathToModule = function(path) {
> 		return path.replace(/^\/base\/app\//, '').replace(/\.js$/, '');
> 	};
> 
> 	Object.keys(window.__karma__.files).forEach(function(file) {
> 		if (TEST_REGEXP.test(file)) {
> 			// Normalize paths to RequireJS module names.
> 			allTestFiles.push(pathToModule(file));
> 		}
> 	});
> }
> 
> require.config({
> 	paths: {
>         jquery: "components/jquery/jquery-3.2.1.min",
> 		angular: 'components/angular/angular.min',
> 		ngRoute: 'components/angular/angular-route',
>         ngIdle : 'components/angular/angular-idle',
>         ngResource : 'components/angular/angular-resource.min',
>         ngCookies : 'components/angular/angular-cookies.min',
>         "angular.css" : "components/angular/angular-css.min",
>         "angular.animate" : "components/angular/angular-animate.min",
>         "angular.ui.bootstrap" : "components/angular/angular-ui-bootstrap",
>         "angular.sanitize" : "components/angular/angular-sanitize.min",
>         "angular.select" : "components/angular/select.min",
> 		'ui.grid' : "components/angular/ui-grid",
>         modernizr : 'components/modernizr/modernizr-2.8.3.min',
> 		text: 'components/requirejs-text/text',
>         "data.config" : 'services/data.config',
>         "data.service" : 'services/data.service',
> 		authentication : 'services/authentication.service',
> 		interceptor : 'services/interceptor'
> 	},
> 	shim: {
> 		'jquery' : {'exports' : 'jquery'},
> 		'angular' : {'exports' : 'angular', deps: ['jquery']},
> 		'ngRoute': ['angular'],
>         'ngIdle': ['angular'],
>         'ngResource': ['angular'],
>         'ngCookies': ['angular'],
>         "angular.css" : ['angular'],
>         "angular.animate" : ['angular'],
>         "angular.ui.bootstrap" : ['angular'],
>         "angular.sanitize" : ['angular'],
>         "angular.select" : ['angular'],
>         "ui.grid": {
>             deps: ['angular','jquery'],
>             exports: 'uiGrid'
>         },
> 		'data.service' : ['data.config']
> 
> 	},
> 	priority: [
> 		"jquery",
> 		"angular"
> 	],
> 	deps: window.__karma__ ? allTestFiles : [],
> 	callback: window.__karma__ ? window.__karma__.start : null,
> 	baseUrl: window.__karma__ ? '/base/app' : '',
> 	urlArgs: 'bust=v1:2'
> });
> 
> require([
> 	'angular',
> 	'app'
> 	], function(angular, app) {
> 		var $html = angular.element(document.getElementsByTagName('html')[0]);
> 		angular.element().ready(function() {
> 			// bootstrap the app manually
> 			angular.bootstrap(document, ['isiApp']);
> 		});
> 	}
> );

**Comment by JGSolutions** [comment]
Any solutions?

**Comment by RacerDelux** [comment]
No, we had to figure out a different solution for requirejs.

**Comment by JGSolutions** [comment]
@RacerDelux Thanks for the reply. So what was the different solution?

**Comment by RacerDelux** [comment]
@JGSolutions Actually got it working, but it was somebody else on the team that played with it until it worked. I will try to figure out what they did.
