### ISSUE TITLE
Row Selection column is not totally rendered for the last rows

### ISSUE THREAD

**Issue by vschimpf** [angular-ui/ui-grid#6292]
This happens when having pagination and showing 25 rows or more.
The height of that panel is less than the table content.

![uigrid](https://user-images.githubusercontent.com/12301370/27796788-a4eb4032-5fe1-11e7-802b-2ae498d1ae87.png)

This could be related to issue #3394 
I've tried with latest version 4.0.6

Here is an example (expand all rows)
http://plnkr.co/edit/eicEjc0diANjhdgoZpWt?p=preview

**Comment by HaroldStruwig** [comment]
I am also experiencing this issue - looks like it incorrectly evaluates the following as ```true``` for the selection column:

```ng-if="colContainer.needsHScrollbarPlaceholder()"```

**Comment by tarzasai** [comment]
In 4.0.7 too, the scrollbar placeholder appears when the horizontal scrollbar is not even there:

![Imgur](https://i.imgur.com/xUpSmBG.jpg)

**Comment by andrewkittredge** [comment]
I might have a hacky fix for this.  

I believe the return value of needsHScrollbarPlaceholder on the pinned, 'left', container needs to change based on whether or not there is a scrollbar on the 'main' container.  Detecting the presence of the scrollbars on elements turns out to be difficult.  My approach is to compare the canvas's width to its parent's width.

I modified GridRenderContainer.prototype.needsHScrollbarPlaceholder on line 8989 of the ui-grid.js I get from npm.
`  
GridRenderContainer.prototype.needsHScrollbarPlaceholder = function () {
      if (this.name === 'left') {
          var $body = $("div[container-id=\"'body'\"]");
          var $bodyCanvas = $body.find('.ui-grid-canvas');
          return $body[0].clientWidth < $bodyCanvas[0].clientWidth;
      } else {
          return this.grid.options.enableHorizontalScrollbar && !this.hasHScrollbar && !this.grid.disableScrolling;
      }
  };
`

**Comment by cwalther** [comment]
I have not tried it but I suspect this will not work
- when the horizontal scroll bar is overlaid on the content (as I mention in #6474, the goal is not to detect whether there is a scroll bar but whether it occupies space)
- when there are multiple ui-grids on the same page.

**Comment by andrewkittredge** [comment]
You are definitely right on #2 and probably right on #1.

Do you agree that this approach would work if we had a reliable algorithm
for determining if the there is a horizontal scroll bar on the main grid?

On Thu, Nov 30, 2017 at 2:22 AM, Christian Walther <notifications@github.com

**Comment by httpete** [comment]
I see cases where the last row scrolls away from the checkbox row when you go to the bottom of the list. Generally the sizing algorithm is squirrely.

**Comment by jeffantosh** [comment]
https://github.com/angular-ui/ui-grid/pull/6244

PR was declined because I couldn't get the unit tests to work. But this can be a starting point for those who wish to look into the issue.

**Comment by jeffantosh** [comment]
Upgraded to 4.2.0, and this issue is still not resolved.

**Comment by nathanbeach** [comment]
I was struggling with this scrollbar blank area using expandable in 4.0.2. finally upgraded to 4.7.1 and now the enableHoriztonalScrollbar option actually works, e.g.:

      enableHorizontalScrollbar: uiGridConstants.scrollbars.NEVER,

Doesn't work with just "false".  Thought this might help someone.
