### ISSUE TITLE
gridApi.selection.clearSelectedRows does not call rowSelectionChanged

### ISSUE THREAD

**Issue by lokeb** [angular-ui/ui-grid#6307]
Using the latest version, the call to clearSelectedRows should call rowSelectionChanged, because technically row selection has changed.

**Comment by gabrieldev30** [comment]
if you want to call rowSelectionChanged() on clearSelectedRows() , you have to set grid.options.enableSelectionBatchEvent = false (it is true by default), otherwise it will call rowSelectionChangedBatch().
