### ISSUE TITLE
Remove Scroll bar for UI-grid and enable for Window.

### ISSUE THREAD

**Issue by nanihub** [angular-ui/ui-grid#6316]
http://plnkr.co/edit/imvWi1xntYvp5OT9GVKX?p=preview

UI-grid table as almost 10-15 rows(may increase in future).
 horizontal scroll bar is coming for the table. 
I want to remove that and make grid width increase w.r.t to the number of rows. And allow user to window scroll.

**Comment by deeppatidar** [comment]
@nanihub : I think you should use custom column like this
customColumn['cellTemplate'] = '<div class="ui-grid-cell-contents">{{grid.appScope.convertNumber(COL_FIELD)}}</div>';
And before  assgining the row to grid data  convert the row's data of that column into integer

**Comment by fatifleu** [comment]
I have the same issue i want to do a scroll vertical and horizontal in windows for user wirhout using it in ui grid

**Comment by fatifleu** [comment]
Did you find a solution to that

**Comment by mportuga** [comment]
You could probably use the workaround provided in this bug: https://github.com/angular-ui/ui-grid/issues/3977
or perhaps the one in this bug:
https://github.com/angular-ui/ui-grid/issues/2549
