### ISSUE TITLE
How to manage auto grid height base of size of row in case of custom pagination?

### ISSUE THREAD

**Issue by rahi-rajeev** [angular-ui/ui-grid#6320]
Hello,
Firstly thanks to all for lovely work. I have post so many time related to grid issues but i did't any solution so please replay.
Query:
1. I want to implement ui grid in multiple tab 
2. when i set width of column and hide column one by one then it showing white space but in case of auto width its working fine so please let me know any solution.
3.i want to implement auto grid mange as per as size of data which are visible on page like(10,5 7.20) because i am using custom pagination for display data .

**Comment by deeppatidar** [comment]
@rahi-rajeev 
Use virtualizationThreshold: "**data size**" in gridOptions.
Basically used for increasing ui-grid height in external pagination(the threshold in rows to force virtualization on)

And use this below the gridOption object defination.
$scope.gridOptions.excessRows = $scope.gridOptions.data.length;
