### ISSUE TITLE
Is ui-grid support angular4?

### ISSUE THREAD

**Issue by binal24** [angular-ui/ui-grid#6342]
Is ui-grid support angular4?

**Comment by michabbb** [comment]
read the [readme](https://github.com/angular-ui/ui-grid/blob/master/README.md):

> UI-Grid is currently compatible with Angular versions ranging from 1.2.x to 1.4.x.

**Comment by RajKann** [comment]
ui_grid 4.0.2 with Angularjs version 1.5.8 & jQuery 2.2.4 is working for me.
