### ISSUE TITLE
Grid not displaying after upgrading from 4.0.2 to 4.0.3 or greater

### ISSUE THREAD

**Issue by kyleThayerXpanxion** [angular-ui/ui-grid#6343]
Any idea why upgrading from 4.0.2 to 4.0.3 or greater would break the grid?  I see nothing in the changelog about breaking changes between the two, and there are no console error, just a grid that doesn't display anymore.

**Comment by kyleThayerXpanxion** [comment]
I found the issue, it had to do with the way we were putting data into the grid was causing issues in 4.0.3+ but not in 4.0.2.

**Comment by elhaard** [comment]
Could you please elaborate? I have the same problem, so your solution may work for us as well.

**Comment by caseyjhol** [comment]
@elhaard See #6155. Setting the data using a string causes the grid to not load. This is a pretty major breaking change, and it seems crazy to me this is not mentioned in the change log.

**Comment by caseyjhol** [comment]
@elhaard See https://github.com/angular-ui/ui-grid/issues/6156#issuecomment-294597162 for a solution/workaround.
