### ISSUE TITLE
Cannot scroll parent container because scrollbar height is added to vertical scroll length 

### ISSUE THREAD

**Issue by haynesgt** [angular-ui/ui-grid#6346]
Vertical scrolling is broken when the grid container height is within 15px of the grid height:
http://plnkr.co/edit/qIzLUjdoboXKG3ZRfAdK?p=preview
You can't scroll down when the cursor is over the grid.

This looks like the cause: [`GridRenderContainer.prototype.getVerticalScrollLength`](https://github.com/angular-ui/ui-grid/blob/21819c57474bf4451f3126985cfccf294c4c01e2/src/js/core/factories/GridRenderContainer.js#L302)
It adds `this.grid.scrollbarHeight` to the vertical scroll length even if `this.grid.isScrollingHorizontally` is false

I'm guessing that `GridRenderContainer.prototype.getHorizontalScrollLength` has the same issue.

**Comment by mportuga** [comment]
Cannot rerproduce.
