### ISSUE TITLE
Possible to use in Angular 2+ app?

### ISSUE THREAD

**Issue by theunreal** [angular-ui/ui-grid#6364]
I've been checking around the web for a way to intergrade ui-grid in angular 2+ application.

I found this: https://github.com/vladotesanovic/ui-grid-angular2

but I couldn't figure out what steps should I take in order to implement it in an existing application.

Any ideas?

**Comment by CaosZero** [comment]
I suppose that is a hybrid app.  
Infact you should able too see here
https://github.com/vladotesanovic/ui-grid-angular2/blob/master/src/app/ng1/grid.component.ts

For more information you can read this guide
https://angular.io/guide/upgrade

**Comment by mportuga** [comment]
We have a plan to migrate the grid to angular 5+
https://github.com/angular-ui/ui-grid/blob/master/planning_5.0.md
