### ISSUE TITLE
Switch language can not effect ui-grid

### ISSUE THREAD

**Issue by halilbay** [angular-ui/ui-grid#6373]
Hi,
Firstly, you know that uigrid.html has static ui-i18n directive static scope as `<div ui-i18n="en" class="ui-grid">` . I used override method for uigrid.html set that to provide this directive has dynamic language option. So, When I switch the language (from English to German), the directive changes like this `<div ui-i18n="de" class="ui-grid">` dynamically but the keywords of the pagination and the columnMenu sections does not update till reload the page.

**Comment by mportuga** [comment]
That issue has been fixed as of version 4.0.7 by making menu items title into a function.

See the tutorial example: http://ui-grid.info/docs/#!/tutorial/104_i18n
