### ISSUE TITLE
Get other cell values other than the current cell value

### ISSUE THREAD

**Issue by jrtobac** [angular-ui/ui-grid#6378]
I am using cell templates to get the current cellvalue with getCellValue(row, col).
I need to also get the cell value in the next column.
Is there something like grid.getCellValue(row, col+1) that will allow me to get the cell value in the next column or am I limited to only be able to work with the data in the current cell?

**Comment by YonatanKra** [comment]
If you know what column you are now you can go for:
`grid.getCellValue(row, grid.columns[index+1]);`
If you don't, you have your column in `$scope` so:
`grid.getCellValue(row, grid.columns[grid.columns.indexOf(col)]);`
Note that the last one is just to show a possibility and I wouldn't recommend using it.
You have `$index` inside the cell's `$scope`, so you could use it for performance:
`grid.getCellValue(row, grid.columns[$index+1]);`
Note here that `$index` would not show the correct number with horizontal infinite scroll.
