### ISSUE TITLE
editFileChooserCallback not triggered (after version 4.0.2)

### ISSUE THREAD

**Issue by frankdenouter** [angular-ui/ui-grid#6384]
as of version 4.0.2 the editFileChooserCallback is not triggered anymore,
because the 'change'-handler of the file-input is removed when the element looses focus. The element looses focus on selecting a file from the open-file-dialog. Thus the result of the open-file-dialog goed nowwhere.

[http://plnkr.co/edit/DnfYnlZRGrMyWyJL5emf?p=preview](http://plnkr.co/edit/DnfYnlZRGrMyWyJL5emf?p=preview)

NOTE: changing the http://cdnjs.cloudflare.com/ajax/libs/angular-ui-grid/4.0.6/ui-grid.js to http://cdnjs.cloudflare.com/ajax/libs/angular-ui-grid/4.0.1/ui-grid.js makes it work again

**Comment by mportuga** [comment]
I believe this commit is responsible: https://github.com/angular-ui/ui-grid/commit/da942e90f082b851a08a3114813af88cc5d8b85e
