### ISSUE TITLE
gridApi.edit.on.afterCellEdit()  : this event is not fired when there is dropdown list in the cellTemplate.

### ISSUE THREAD

**Issue by sumeetsonawane11** [angular-ui/ui-grid#6392]
I want to trigger an event as soon as the user click on the dropdown which is present in the cell template
It works for input type text but not for dropdowns ?
Please suggest some solution

**Comment by GRajaMca** [comment]
You can try some thing like this, it works fine for me
`onRegisterApi : function(gridApi) {
			gridApi.edit.on.afterCellEdit($scope, function(rowEntity, colDef, newValue, oldValue) {
				var data = rowEntity;
				data.action = 1;
				$scope.userList.data[$scope.userList.data.indexOf(rowEntity)] = data;
			});
		}`

**Comment by sumeetsonawane11** [comment]
I have tried the same but its still not working.

gridApi.edit.on.afterCellEdit($scope, function (rowEntity, colDef, newValue, oldValue) {
									if (newValue !== oldValue && colDef.name === 'status.label' ||
										newValue !== oldValue && colDef.name === 'baAdmin.label' ||
										newValue !== oldValue && colDef.name === 'notes') {
										vm.editableFieldChanged = true;
									}
									$log.log("After cell edit");
								});

**Comment by GRajaMca** [comment]
I have created the plunker for you which consist of both custom and default drop-down with in UI-grid

Find the plunker here [http://plnkr.co/edit/1TYAVtzheQAYZivotJQN](url)

**Comment by sumeetsonawane11** [comment]
The link is failing to open

**Comment by GRajaMca** [comment]
Instead of clicking, copy the URL and try access directly

**Comment by sumeetsonawane11** [comment]
Thanks, I have seen your code and it is working correctly.
The only problem I have is I am using Custom Bootstrap Angular directive for dropdown instead of   editableCellTemplate: 'ui-grid/dropdownEditor'


Custom dropdown code:
<div uib-dropdown dropdown-append-to-body class="grid-dropdown"><button class="btn btn-default" uib-dropdown-toggle><span>{{COL_FIELD}}</span><span class="glyphicon glyphicon-menu-down pull-right\"></span></button><ul class=\"grid-menu\" uib-dropdown-menu role=\"menu\">
<li role="menuItem" ng-repeat="item in col.colDef.editDropdownOptionsArray" ng-click='grid.appScope.blurTest(item,row.entity,col.colDef)'>{{item.label}}</li>
</ul>
</div>

**Comment by GRajaMca** [comment]
Could you please make some plunker and share
