### ISSUE TITLE
Regression: uiGridSelection cannot select groupHeaders

### ISSUE THREAD

**Issue by jniles** [angular-ui/ui-grid#6398]
The `uiGridSelection` used to select group headers in ui-grid version 4.0.4, but no longer selects group headers in v4.0.5+.  In previous versions, clicking on a grow that was a group header would select that row.  In the newer versions, clicking on the group header will not select the group header row, but select all children.

I believe this change was introduced in https://github.com/angular-ui/ui-grid/commit/21819c57474bf4451f3126985cfccf294c4c01e2.  The affected code is [selection.jsL#730](https://github.com/angular-ui/ui-grid/blob/cc49916/src/features/selection/js/selection.js#L730).  This patch was a response to https://github.com/angular-ui/ui-grid/issues/6160.

In my view, the best implementation should allow a user to determine exactly the behavior of the grid:
 1. Should a `row.groupHeader` be selectable?
 2. Should children be selected when a `row.groupHeader` be selected?

Currently, option 1. is not supported and 2. is default.  Both these should likely toggles exposed via `gridOptions`.

**Comment by knalbandianbrightgrove** [comment]
@jniles 

Try this [solution](https://github.com/angular-ui/ui-grid/issues/3911#issuecomment-323036717), seems working. but I agree to make it configurable

**Comment by jniles** [comment]
Hey @knalbandianbrightgrove, I appreciate your response!  We did something similar to what you demonstrated.  If I get a chance to work on other projects, this is definitely on my shortlist of bugs to fix.
