### ISSUE TITLE
Wrap-text functionality is not available

### ISSUE THREAD

**Issue by nrbokade** [angular-ui/ui-grid#6400]
Hi, 
I am using **ui-grid v-4.0.4** in my all projects. I want to apply wrap-text property to all cells in my grid.
I have searched a lot in ui-grid docs, but didn't get anything related to that. I don't found any property or directive to achieve the same. 
Please tell me the _solutions or the hint._

**Comment by mportuga** [comment]
I recommend using CSS.

overflow: hidden;
text-overflow: ellipsis;
white-space: nowrap;

**Comment by jgf5013** [comment]
@mportuga, I don't think that answer's OPs question. They (and I) are looking for something that will wrap the text onto the next line, increasing the cell height, when the cell text is especially long.
