### ISSUE TITLE
Pagination Issue in ng-grid

### ISSUE THREAD

**Issue by lvivek1988** [angular-ui/ui-grid#6403]
The page size is set to 2 with 9 items, so the min is 1 and max number of pages max is 5.
Now change page size to 5.
So expected max number of pages, max should get changed to 2.

But still max is 5. :-(

**Comment by mportuga** [comment]
Can you provide a plunker of the issue?

**Comment by mportuga** [comment]
Cannot reproduce issue:
http://plnkr.co/edit/z9kNSqjUUnq4qnLrBNzm?p=preview
