### ISSUE TITLE
Doesn't change language when page is already loaded

### ISSUE THREAD

**Issue by Brenw10** [angular-ui/ui-grid#6404]
I'm trying to change language after page loads.
On first time, when page loads, it works fine.
However, I have a button on my menu that user can change site language. Then it must change the grid language as well. (Change footer text, items per page and others about pagination).
I need to know how to refresh the template and how could I add new languages and replace texts for these languages.

**Comment by cybermerlin** [comment]
Please check in [branch](https://github.com/cybermerlin/ui-grid/tree/develop).

**Comment by mportuga** [comment]
Check out the tutorial for localization. The issue with it not reloading has been resolved recently and you should be able to use that as an example.
