### ISSUE TITLE
Export CSV Not Working Correctly

### ISSUE THREAD

**Issue by FK7** [angular-ui/ui-grid#6421]
Below is my sample data : 
`create TABLE work_order_service_excellence_segment_smcs\nSTORED AS PARQUET\nLOCATION ` 
in one of my column and I am getting this data as a multiline response. 

It is clearly visible in the UI-Grid but after exporting it is taking only  `create TABLE` .

**Comment by mportuga** [comment]
Can you please provide a plunker?
