### ISSUE TITLE
Safari grid's last cell wrapping down in grid.

### ISSUE THREAD

**Issue by ZergRushJoe** [angular-ui/ui-grid#6423]
In a grid with many cols the last cell in the grid wraps into a new row.

![capture](https://user-images.githubusercontent.com/7153267/31557821-5f6f68bc-b018-11e7-9790-553dbaf7bcdc.PNG)

If I make the ui-grid-canvas one pixel larger it fixes it.- v4.0.4

**Comment by mportuga** [comment]
Can you provide a plunker?
