### ISSUE TITLE
enableCellEdit and cellEditableCondition is not working

### ISSUE THREAD

**Issue by sahilkatia** [angular-ui/ui-grid#6430]
Please let me know if you didn't understand my approach. It's based on Angular-UI-grid. I have two controllers(ctrl1.js, ctrl2.js).I am getting data using get method on each controller from different webservices.

timeSeries is object in webservice(getTimeSeriesData) which I called in Ctrl1.js. There are 1500 objects in timeSeries and for last object(1500th) latest is true and for others latest is undefined. I should be able to edit(in ctrl2.js) only if latest is true, else user should not have any feature to edit the column.

Ctrl1.js Code
`$rootScope.test = false;    
        $rootScope.latest = timeSeries.latest;
        if ($rootScope.latest == true){
            $rootScope.test = true;
            console.log($rootScope.test);
        } // everything is good here, I am getting true in console here.`

To enable the cell editing I am using two approaches in Ctrl2.js:-(problem is here its not editable i.e cellEdit is false.)
`
cellEditableCondition: function($rootScope){
                         return $rootScope.test
                         },

enableCellEdit: $rootScope.test;
`

**Comment by mportuga** [comment]
I was able to get it to work by using cellEditableCondition
http://plnkr.co/edit/x8NUAoNs4OJ1twDuWax7?p=preview
