### ISSUE TITLE
How to select top 6 rows after sorting?

### ISSUE THREAD

**Issue by ThotaAshok** [angular-ui/ui-grid#6433]
Angular lib ==>angular-1.2.29/angular.js

I am new to angular. We are currently using above version and I am using ui-grid to display data. In the grid I have data loaded and after loading I clicked on first column to select the multiple rows and the max we are selecting is 6 rows. After selection I clicked on sort and to forget the selection I used the below code and which is making the selection get cleared on sort column changed event.

 gridApi.core.on.sortChanged($scope, function (grid, sortColumns) {                        
                        $scope.gridApi.selection.clearSelectedRows();
                        // $scope.gridOptions.data = $scope.gridApi.core.getVisibleRows().data;
                    });

But after that when I click on first column again (which is to select top 6 rows), it is again remembering the original list I selected and selecting only those rows (which in some where on second page), not the top 6 rows. Why?

I event tried to add the line to reset gridOptions data (see 99 ) but nothing works. I see an infite errors created i guess. How i can resolve this issue. My goal is to select top 6 rows after sorting.

 gridApi.core.on.sortChanged($scope, function (grid, sortColumns) {                        
                        $scope.gridApi.selection.clearSelectedRows();
                        $scope.gridOptions.data = $scope.gridApi.core.getVisibleRows().data; // 99
                    });

Could somebody guide me on this?

`function init() {
            constantsDataService.getConstantData().then(function (result) {
                $scope.phoneBookUrl = result.PhoneBookUrl;
                $scope.forceAllFlagToolTip = result.ForceAllFlagTooltip;
                $scope.IsAdminUser = result.IsAdminUser;
                $scope.GetMassActionTresholdValues = result.ExpenseRequestsSelectThreshold;
            }).catch(function (error) {
                // error handling
            });
            
$scope.ApprovalWorkflow = null;
            $scope.RequestActionButtons = null;
            $scope.ErrorMessage = "";
            $scope.selectedRow = null;
            $scope.MassActionComments = "";
            $scope.sideViewForDetail = false;
            $scope.grid1Width = 'col-md-12 col-sm-12 col-xs-12';

            // Call below method to check if the logged-in user is Admin or not. In below method after evaluation the data is set to scope variable 'IsAdminUser'.
            getIsAdmin();

            // Below method is used to get the upcoming Queue details which will be used to load the data in the approval grid.
            GetUpcomingApproverQueueDetails();

            var fakeI18n = function (title) {
                var deferred = $q.defer();
                $interval(function () {
                    deferred.resolve('col: ' + title);
                }, 1000, 1);
                return deferred.promise;
            };            

            var pinCellTemplate = ' <div class="ui-grid-cell-contents img-responsive"><span ng-if="row.entity.pinFlag==false"><center><img src="/app/assets/images/icon_pin_inactive.png" width="12px" height="12px" /></center></span><span ng-if="row.entity.pinFlag==true"><center><img src="/app/assets/images/icon_pin_active.png" width="12px" height="12px" /></center></span></div>'
            var notesCellTemplate = ' <div class="ui-grid-cell-contents img-responsive"><span ng-if="row.entity.notesFlag==false"><center><img src="/app/assets/images/icon_note_inactive.png" width="12px" height="12px" /></center></span><span ng-if="row.entity.notesFlag==true"><center><img src="/app/assets/images/icon_note_active.png" width="12px" height="12px" /></center></span></div>'
            var escalatedCellTemplate = ' <div class="ui-grid-cell-contents img-responsive"><span ng-if="row.entity.escalatedFlag==true"><center><img src="/app/assets/images/icon_alert.png" width="12px" height="12px" /></center></span></div>'
            var requestIDTemplate = '<div class="ui-grid-cell-contents"><a  href="{{ row.entity.requestURL}}" target="_blank">{{ row.entity.requestID }}</a></div>';
            var requestForSIDTemplate = '<div class="ui-grid-cell-contents"><a  href="{{grid.appScope.phoneBookUrl}}{{row.entity.requestForSID}}" target="_blank">{{ row.entity.requestForName }}</a></div>';
            var currentApproverNameTemplate = '<div class="ui-grid-cell-contents"><a href="{{grid.appScope.phoneBookUrl}}{{row.entity.currentApproverSID}}" target="_blank">{{ row.entity.currentApproverName }}</a></div>';
            var requestBySIDTemplate = '<div class="ui-grid-cell-contents"><a  href="{{grid.appScope.phoneBookUrl}}{{row.entity.requestBySID}}" target="_blank">{{ row.entity.requestByName }}</a></div>';
            var company = '<div class="ui-grid-cell-contents">{{row.entity.company}}</div>';
            var costCenter = '<div class="ui-grid-cell-contents">{{row.entity.costcenter}}</div>';

            $scope.gridOptions = {

                //enableFiltering: true,
                enableSorting: true,

                exporterMenuCsv: false,
                enableGridMenu: true,
                enableColumnResizing: true,
                enableRowSelection: true,
                selectionRowHeaderWidth: 35,
                rowHeight: 35,
                showGridFooter: true,
                paginationPageSizes: [25, 50, 75],
                paginationPageSize: 25,
                enableVerticalScrollbar: 0,
                rowTemplate: "<div ng-click=\"grid.appScope.editRow(grid, row, $event)\"  ng-repeat=\"(colRenderIndex, col) in colContainer.renderedColumns track by col.colDef.name\" class=\"ui-grid-cell\" ng-class=\"{ 'ui-grid-row-header-cell': col.isRowHeader}\" ui-grid-cell></div>",

                
                columnDefs: [
                    { name: 'pinFlag', displayName: 'Pin', width: 50, enableHiding: false, enableColumnResizing: false, cellTemplate: '../app/components/templates/PinTemplate.html' },
                    { name: 'notesFlag', displayName: 'Notes', width: 70, enableHiding: false, enableColumnResizing: false, cellTemplate: notesCellTemplate },
                    { name: 'escalatedFlag', displayName: 'Escalated', width: 100, enableHiding: false, enableColumnResizing: false, cellTemplate: escalatedCellTemplate },
                    { name: 'dateRequested', displayName: 'Requested', width: 108, enableColumnResizing: false, cellFilter: 'date:"MM/dd/yyyy"' },
                    { name: 'application', displayName: 'Application', width: "*", minWidth: 120 },
                    { name: 'requestID', displayName: 'Request ID', width: "*", minWidth: 110, cellTemplate: requestIDTemplate },
                    { name: 'requestDesc', displayName: 'Description', width: "*", minWidth: 150 },
                    { name: 'requestAmount', displayName: 'Amount', width: "*", minWidth: 110, cellTemplate: '../app/components/templates/AmountTemplate.html', headerCellClass: 'text-right' },
                    { name: 'company', displayName: 'Company', width: "*", minWidth: 100, cellTemplate: company },
                    { name: 'Costcenter', displayName: 'Cost Center', width: "*", minWidth: 120, cellTemplate: costCenter },
                    { name: 'costcenter_description', displayName: 'Cost Center Name', width: "*", minWidth: 160 },
                    { name: 'requestForName', displayName: 'Requested For', width: "*", minWidth: 180, cellTemplate: requestForSIDTemplate },
                    { name: 'requestByName', displayName: 'Requested By', width: "*", minWidth: 180, cellTemplate: requestBySIDTemplate },
                    { name: 'oboFlag', displayName: 'OBO', width: "*", minWidth: 80, cellTemplate: '../app/components/templates/OBOTemplate.html' },
                    { name: 'currentApproverName', displayName: 'Approver', width: "*", minWidth: 180, cellTemplate: currentApproverNameTemplate }
                ],

                onRegisterApi: function (gridApi) {
                    $scope.gridApi = gridApi;

                    //interval of zero just to allow the directive to have initialized
                    $interval(function () {
                        gridApi.core.addToGridMenu(gridApi.grid, [{ title: 'Dynamic item', order: 100 }]);
                    }, 0, 1);

                    gridApi.core.on.sortChanged($scope, function (grid, sortColumns) {                        
                        $scope.gridApi.selection.clearSelectedRows();
                        $scope.gridOptions.data = $scope.gridApi.core.getVisibleRows().data;
                    });

                    // gridApi.core.on.enableSorting
                    
                    // CODE 10222017_6_PM
                    //gridApi.core.notifyDataChange($scope, function () {
                    //    $scope.gridApi.selection.clearSelectedRows();
                    //});

                    gridApi.core.on.columnVisibilityChanged($scope, function (changedColumn) {
                        $scope.columnChanged = { name: changedColumn.colDef.name, visible: changedColumn.colDef.visible };
                    });

                    gridApi.selection.on.rowSelectionChanged($scope, function (row) {
                        if ($scope.gridApi.selection.getSelectedCount() > $scope.GetMassActionTresholdValues) {
                            row.setSelected(false);
                        }
                        if ($scope.sideViewForDetail == true && row.isSelected == true) {
                            $scope.row = row;
                            $scope.grid1Width = 'col-md-8 col-sm-8 col-xs-8';
                            $scope.sideViewForDetail = true;
                        }
                        else {
                            $scope.grid1Width = 'col-md-12 col-sm-12 col-xs-12';
                            $scope.sideViewForDetail = false;
                        }
                    });
                }
            };
        }`

**Comment by mportuga** [comment]
1.2.29 is no longer supported
