### ISSUE TITLE
Checkbox in ag-grid Angular JS

### ISSUE THREAD

**Issue by Atul-Raut** [angular-ui/ui-grid#6443]
Hi ,

I want to add check box in ag-grid, 

cellTemplate = "<input type='checkbox' ng-model='row.entity.res_TYP' '>";

Using above line checkbox is displayed in grid but selected value are not able to bind with ng-model

Thanks in advance

**Comment by mportuga** [comment]
Again, this is UI-grid not ag-grid. I think what you want is this:
https://github.com/ag-grid/ag-grid/issues
