### ISSUE TITLE
Why ui-grid accepts null values even if data-type is not null

### ISSUE THREAD

**Issue by sahilkatia1** [angular-ui/ui-grid#6455]
On the official documentation plnkr, I edit some value and didn't give any value(keep it as blank), then that field was accepting it as a null. Which shouldn't happen because they already defined some data-type

**Comment by sahilkatia1** [comment]
On the official documentation plnkr, I edit some value and didn't give any value(keep it as blank), then that field was accepting it as a null. Which shouldn't happen because they already defined some data-type.

**Comment by mportuga** [comment]
I am not sure
