### ISSUE TITLE
Data getting overlapped when large amount of data loads

### ISSUE THREAD

**Issue by nilulande05** [angular-ui/ui-grid#6458]
We have used  ag-grid v6.1.0 and facing issue of data overlapped. You need to scroll the data and sometimes it shows overlapped as per attached screenshot.
![data overlapped](https://user-images.githubusercontent.com/22637970/32646975-287241f0-c615-11e7-8a00-76fa4f141a6c.png)

**Comment by mportuga** [comment]
This is ui-grid, not ag-grid and we have not released 6.0.10 yet. Either way, it looks like you are missing some CSS there.
