### ISSUE TITLE
selectionRowHeaderButtons error closing tag

### ISSUE THREAD

**Issue by pkomni** [angular-ui/ui-grid#6459]
In all versions of ui-grid after 4.0.2 there is an extra closing tag on the `selectionRowHeaderButtons` for the first column with the checkbox that enables the selection of a row.

More specifically in `bower_components/angular-ui-grid/ui-grid.js` on line **29355** you should replace this
 `"<div class=\"ui-grid-selection-row-header-buttons ui-grid-icon-ok\" ng-class=\"{'ui-grid-row-selected': row.isSelected}\" ng-click=\"selectButtonClick(row, $event)\" ng-keydown=\"selectButtonKeyDown(row, $event)\">role=\"checkbox\" ng-model=\"row.isSelected\"> &nbsp;</div>"` 
with this 
`"<div class=\"ui-grid-selection-row-header-buttons ui-grid-icon-ok\" ng-class=\"{'ui-grid-row-selected': row.isSelected}\" ng-click=\"selectButtonClick(row, $event)\" ng-keydown=\"selectButtonKeyDown(row, $event)\" role=\"checkbox\" ng-model=\"row.isSelected\"> &nbsp;</div>"`

**Comment by adamhwang** [comment]
+1. Resolved with #6450

**Comment by pkomni** [comment]
The issue returned on next versions. Please integrate it again on new versions
