### ISSUE TITLE
Directive 'uiGridAutoResize' causes infinite $digest error

### ISSUE THREAD

**Issue by wsion** [angular-ui/ui-grid#6477]
After updating to 4.0.11, my application keeps throwing below error
=================================================
Uncaught Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: [[{"msg":"fn: function (){return b[0].clientHeight}","newVal":104,"oldVal":105}
=================================================

Reading the source code of uiGridAutoResize, I found 4.0.11 had changed the implementation of checking grid width and height. 

I believe the error is easy to reproduce. Please have it fixed ASAP.

**Comment by wsion** [comment]
Caused by my own code. Ignore the issue report please.

**Comment by HaroldStruwig** [comment]
@wsion I am also seeing this since updating to 4.0.11 - what caused this in your code?
