### ISSUE TITLE
enableRowHeaderSelection can't be changed dynamically

### ISSUE THREAD

**Issue by crazyjat** [angular-ui/ui-grid#6491]
I have a method that should remove the row header selection check mark from the grid, but it does not work. Is this even possible to toggle dynamically?

```
toggleRowSelection() {
    this.gridOptions.enableRowHeaderSelection = !this.gridOptions.enableRowHeaderSelection;
    this.gridOptions.enableRowSelection = !this.gridOptions.enableRowSelection;
    this.gridOptions.gridApi.selection.clearSelectedRows();
    this.gridOptions.gridApi.core.notifyDataChange(this.uiGridConstants.dataChange.ALL);
}
```

This does not remove the row header column or disable toggling the checkmark.

**Comment by cybermerlin** [comment]
grid container repaint.
try $scope.$apply(),  grid.refresh()...
