### ISSUE TITLE
 Cannot read property 'options' of undefined

### ISSUE THREAD

**Issue by nanihub** [angular-ui/ui-grid#6492]
Cannot read property 'options' of undefined GridMenu with exporter enabled

ISSUES:
1) Errors in console once if we click on grid Menu 

2) Export to not working on 1st click. (angular.js:13708 TypeError: Cannot read property 'forEach' of undefined
    at Grid.modifyRows (ui-grid.js:4879))

**EXAMPLE**: http://ui-grid.info/docs/#/tutorial/405_exporting_all_data_complex

 **version** am using : ui-grid - v4.0.11 - 2017-11-20

![capture](https://user-images.githubusercontent.com/20196278/33452880-466de410-d5d9-11e7-87bc-81fae5752cf4.PNG)

**Comment by Daniel-Ewers** [comment]
This was fixed here: [https://github.com/angular-ui/ui-grid/blob/master/CHANGELOG.md#v403-2017-03-24]

The fix was to remove the "this." before the options.
But when the Excel Export was added, the "this." was used again, which is causing the break. If you remove the "this." it works.
