### ISSUE TITLE
The main documentation site is not working with 4.1.0 release

### ISSUE THREAD

**Issue by monster910** [angular-ui/ui-grid#6508]
http://ui-grid.info/

Getting script errors - something to do with google

ui-grid.info/:90 A parser-blocking, cross site (i.e. different eTLD+1) script, http://ajax.googleapis.com/ajax/libs/angularjs/1.6.7/angular.js, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.
addTag @ ui-grid.info/:90
ui-grid.info/:90 A parser-blocking, cross site (i.e. different eTLD+1) script, http://ajax.googleapis.com/ajax/libs/angularjs/1.6.7/angular-touch.js, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.
addTag @ ui-grid.info/:90
2ui-grid.info/:90 A parser-blocking, cross site (i.e. different eTLD+1) script, http://ajax.googleapis.com/ajax/libs/angularjs/1.6.7/angular-animate.js, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.
addTag @ ui-grid.info/:90
ui-grid.info/:90 A parser-blocking, cross site (i.e. different eTLD+1) script, http://ajax.googleapis.com/ajax/libs/angularjs/1.6.7/angular-aria.js, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.
addTag @ ui-grid.info/:90
sca.17.4.20.js:19 [Deprecation] Use of the Application Cache is deprecated on insecure origins. Support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
testFunctions @ sca.17.4.20.js:19
sca.17.4.20.js:19 [Deprecation] 'webkitURL' is deprecated. Please use 'URL' instead.

**Comment by sreigle** [comment]
Looks as if the [hashPrefix()](https://docs.angularjs.org/api/ng/provider/$locationProvider#hashPrefix) has changed. The default for the current version of AngularJS is `'!'`, but it looks like the links in documentation site are using a blank hashPrefix `''`.

Copy any link and add a `!` to the hash and you will get routed to the correct page. For example, change: http://ui-grid.info/docs/#/tutorial to http://ui-grid.info/docs/#!/tutorial

**Comment by DracoPL** [comment]
Thank you for this tip. Unfortunately demo part is still broken :-(

**Comment by mportuga** [comment]
@sreigle Thank you for the analysis. I will look into this when i get home tonight.
