### ISSUE TITLE
Package Usage 

### ISSUE THREAD

**Issue by AngularTx** [angular-ui/ui-grid#6509]
Can this package be used with Angular 4 + ? 

Will there be any support for next versions ?

**Comment by monster910** [comment]
It is not easy to integrate. 

https://github.com/monster910/ui-grid-angular2/tree/excel_export

There are other A4 libs but I have found them slow or buggy.

**Comment by AngularTx** [comment]
We have used Ag-grid in our application. But we are integrationg the application with other application that were built on Angular1.x version using UI-grid. Since the look and feel are different, we wanted to check if we could use the Angular-ui-grid in Angular4+.

**Comment by Teamop** [comment]
Currently, seems it's not possible with this package, but there's a v5.0 plan [here](https://github.com/angular-ui/ui-grid/blob/master/planning_5.0.md)

**Comment by mportuga** [comment]
At the moment we do not support Angular 4+, but we have a plan to move to it as mentioned by @Teamop 
https://github.com/angular-ui/ui-grid/blob/master/planning_5.0.md

I am also accepting PRs that help me follow the plan laid out. If the recent angular 1.6.7 upgrade taught me anything is that we really need good and reliable protractor tests.
