### ISSUE TITLE
Tutorial's demo

### ISSUE THREAD

**Issue by atifovac** [angular-ui/ui-grid#6511]
In the tutorial's pages the demo window doesn't work.
The following snapshot shows how it appear in chrome (63.0.3239.108) and the errors printed to console

![schermata da 2017-12-21 10-30-31](https://user-images.githubusercontent.com/29329418/34249706-f832e8dc-e63a-11e7-8e02-0b056416ed1e.jpg)

Even on Firefox (57.0.1) it doesn't work as showed in the following snapshot

![schermata da 2017-12-21 10-42-19](https://user-images.githubusercontent.com/29329418/34250052-fcc4c9aa-e63b-11e7-82a9-efb840171d7d.jpg)

The page http://ui-grid.info/docs/#!/tutorial/320_complex_grouping have been taken as example but the issue is for all tutorial's pages

**Comment by mportuga** [comment]
Okay, so our website was not ready for this angular upgrade earlier. I have now updated all instances of $http.success to $http.then and the data usage to be response.data.

**Comment by atifovac** [comment]
There's still some demo with the issue

![schermata da 2017-12-22 12-45-02](https://user-images.githubusercontent.com/29329418/34297164-d01e4aee-e716-11e7-8906-fef8b2962d29.jpg)

I've found it at the second demo of the page http://ui-grid.info/docs/#!/tutorial/210_selection .

**Comment by mportuga** [comment]
Thanks @atifovac , I must have missed that one. Any other ones that you are aware of?
