### ISSUE TITLE
grouping and selection

### ISSUE THREAD

**Issue by pierrekour** [angular-ui/ui-grid#6520]
Hey,
I was trying to make the grid to behave as follows:
my data is people with ages.
1. The grid should group people with the same name, and display a tree view. 
2. Only actual items is selectable, not group headers.
3. If there is only one person with a given name it should be shown flat (do not need to expand anything to show it).
I was trying to use : 'grouping: { groupPriority: 0 }' in columnDef.
the problem with this solution is that do not meet criteria 3. plunker: https://plnkr.co/edit/iqaBwxTbN1UAfZ8INvC6?p=preview

another approach I was trying is to use treeView and adjusted my data to to match tree structure, and meet criteria 1+3, but here there were two problems: A plus sign (expanding) was shown even when there is nothing to expand even though I was using 'treeRowHeaderAlwaysVisible: false', second I could select group header rows that should have been not selectable since I was using 'enableSelection: false'.
plunker: https://plnkr.co/edit/8RPcFFAEbNjXzRU0OVt6?p=preview

the first solution is far more elegant, but I didn't find a way to prevent grouping single element. could it be done? 
Second, Any idea why in the second solution the flags do not work? and maybe another way to accomplish it?

**Comment by mportuga** [comment]
I believe that what you desire is possible with the latest version of ui-grid. See the plunker bellow:
http://plnkr.co/edit/OvVrhDteZ9No8NdA8bVT?p=preview
