### ISSUE TITLE
How to make cellcontent hyperlink

### ISSUE THREAD

**Issue by varun-snipl** [angular-ui/ui-grid#6526]
I'm new to angular-ui-grid. I'm ui-grid 4.0, I have to implement if grid cell content present http// or https grid cell data, make it as hyperlink. Please tell me how do i implement this feature. Data dynamically loaded on the grid. I found stackoverflow issue https://stackoverflow.com/questions/25848416/angularjs-ui-grid-render-hyperlink. but it's not dynamic table render data.

**Comment by mportuga** [comment]
`$scope.gridOptions.columnDefs = [
     { name: 'firstName' },
     { name: 'lastName'},
     { name: 'Hyperlink',
         cellTemplate:'<div>' +
                   '<a ng-href="{{row.entity.hyperlink]}}">Click me</a>' +
                   '</div>' }
];`
http://plnkr.co/edit/y4mzc2N5ONglgtLLh7Yw?p=preview
