### ISSUE TITLE
Angualar 5 configuration...

### ISSUE THREAD

**Issue by girpate** [angular-ui/ui-grid#6527]
HI,

Please let me know if UI grid supports angular 5 and if yes please let me know configurations required.

I am using below link to use Ui-grid with angular 5 
http://ui-grid.info/

and getting error:
Uncaught ReferenceError: angular is not defined 
Thanks
Girish

**Comment by mportuga** [comment]
It does not support angular 5, but there is a plan in place for supporting it.

**Comment by girpate** [comment]
Please let me know when it will be available to use with Angular 5...
