### ISSUE TITLE
Grid pinning and last row

### ISSUE THREAD

**Issue by jschuler** [angular-ui/ui-grid#6528]
When pinning some columns, I am seeing an issue where the last row is partially cut off when the browser is wide enough where a horizontal scrollbar is not needed.

Reproduced with the plunkr linked from the pinning tutorial:
http://ui-grid.info/docs/#!/tutorial/203_pinning

Working fine as there is a horizontal scrollbar and last row can be fully seen:
![image](https://user-images.githubusercontent.com/869106/34684514-4d5b865c-f473-11e7-9e2e-3bf1c1d5d99e.png)

Making browser wider so that there is no horizontal scrollbar:
![image](https://user-images.githubusercontent.com/869106/34684565-7f627c64-f473-11e7-85dd-dc44d1afd879.png)

**Comment by andrewkittredge** [comment]
Related to https://github.com/angular-ui/ui-grid/issues/6292
