### ISSUE TITLE
Error: [$compile:ctreq] Controller 'uiGrid', required by directive 'uiGridImporterMenuItem', can't be found!

### ISSUE THREAD

**Issue by ashish-sharma4u** [angular-ui/ui-grid#6535]
I am using the import option (CSV File) in the grid, And getting the error  "Error: [$compile:ctreq] Controller 'uiGrid', required by directive 'uiGridImporterMenuItem', can't be found!" . Can any one please help me to solve this.

**Comment by mportuga** [comment]
Can you provide a plunker?
