### ISSUE TITLE
On click of Grid Menu getting following error "TypeError: Cannot read property 'options' of undefined"

### ISSUE THREAD

**Issue by ashish-sharma4u** [angular-ui/ui-grid#6536]
The above mentioned error is thrown at least 22 times on every click on menu of grid , Please help me to understand what is it.

**Comment by screamsyk** [comment]
you'd better show the code associated with this issue

**Comment by mportuga** [comment]
please provide a plunker of the issue.

**Comment by mportuga** [comment]
I cannot reproduce the issue on the latest version of ui-grid on the site and I am seeing no response. So I am closing this issue.
