### ISSUE TITLE
Can't scroll down to the bottom fluently

### ISSUE THREAD

**Issue by screamsyk** [angular-ui/ui-grid#6549]
when the ui-grid's height is higher than  a value  which is not fixed, I scroll down to the bottom, but the ui-grid backs to top immediately. I don't know why and the value usually is 690px @mportuga

**Comment by screamsyk** [comment]
Can anybody help?

**Comment by andrewkittredge** [comment]
Probably related to https://github.com/angular-ui/ui-grid/issues/6292

**Comment by screamsyk** [comment]
I am so happy for that I have found the solution of this problem. 
(1)Viewing the source code, I find that the height of `.ui-grid-canvas` is calculated by the height of row.
(2)the real height of row in my grid is '40px', because I set `font-size` to be '16'px and I set the `padding-top`, and so on
(3)but the defult height of row is `30`
![1](https://user-images.githubusercontent.com/25660357/36886644-6199f8cc-1e28-11e8-9a79-d06cd8079e3b.png)
(4)so the height of '.ui-grid-canvas' is miscalculate
(5)To fix it ,I set `rowHeight` to be 40
(6)Finally, the scrolling is normal
