### ISSUE TITLE
Importer not working anymore.

### ISSUE THREAD

**Issue by mrbormeth** [angular-ui/ui-grid#6550]
Hey :) 

I'm trying to get our importer working again, without luck. 

Worked just perfect for months after updating to 4.2.2 it doesn't work anymore. 

Thought it was a problem with my application, thou I found out that the tutorial doesn't work either. 

http://ui-grid.info/docs/#!/tutorial/207_importing_data

So something is wrong and i have no idea what, no error or anything just doesn't add any data to the grid after importing.

Tried using both the JSON and the CSV sample from the tutorial without luck.

**Comment by mportuga** [comment]
I accidentally causing this regression by adding an unnecessary on destroy event that removed the event listener for it. I will be reverting that change and updating the version soon to fix that issue.
