### ISSUE TITLE
v4.2.2 Style recalculation in a loop cause grid blinking

### ISSUE THREAD

**Issue by falsyvalues** [angular-ui/ui-grid#6561]
`ui-grid` in version 4.2.2 is doing some style recalculation (which does not change anything) in a loop which cause blinking whole grid and forcing reflow which is a perf bottleneck.

![reflow](https://user-images.githubusercontent.com/1199350/35726774-51a56768-0806-11e8-9020-6a9a2bee8dae.gif)

**Comment by mportuga** [comment]
Thanks for the note @falsyvalues, Do you have any guesses as to what change might have caused this recalculation?

**Comment by mportuga** [comment]
I tried recreating that on version 4.2.3 and was unable to. Could you provide a plunker to help me debug as well?

**Comment by falsyvalues** [comment]
@mportuga Its somehow connected to `.ui-grid-header-canvas` as you may see on image its switching from `inherit`  to px value.

**Comment by falsyvalues** [comment]
@mportuga Found it, its `uiGridAutoResize` directive, fef9552 made in #6481. I also described problem here #6470.

**Comment by falsyvalues** [comment]
```
$scope.$watchGroup([
  function() {
    return gridUtil.elementWidth($elm);
  },
  function() {
    return gridUtil.elementHeight($elm);
  }
], function(newValues, oldValues, scope) {
  debounce(newValues[0], newValues[1]);
})
```
Result of this construction is always different and our debounce in called every 400ms thats why we see cycles on performance tab.
