### ISSUE TITLE
UI-Grid - Graphic issues when you delete some rows

### ISSUE THREAD

**Issue by Mond0** [angular-ui/ui-grid#6562]
Hi,
I have some problems with the UI-Grid when I try to remove some rows. Here my plunker
[https://plnkr.co/edit/Q1KwSQ?p=preview](url)

If you click on the button ("Click me") the code should remove the row you have selected. And only on Chrome there are some problems on rendering the grid after this operation.
For example if you try to remove the second row (with the column 'Task Name' equal to 'Project Manager - phase 10') you will still see that row (but that is only a graphic issue because the data are correct if you inspect the $scope.gridOptions.data). 

Like I have said it happens only on Chrome (didnt' notice it on IE and Firefox).

**Comment by mportuga** [comment]
Your link doesn't appear to be working for me. Any chance you can provide a new one?

**Comment by Mond0** [comment]
I'm apparently missing something since I don't understand what I'm doing wrong. Anyway the url is correct. If you copy in a new page you will be rendered in the right place.

**Comment by mportuga** [comment]
I cannot reproduce this issue on the latest version of ui-grid.
