### ISSUE TITLE
Unable to scroll to the latest row

### ISSUE THREAD

**Issue by jingzhaoou** [angular-ui/ui-grid#6571]
No luck even with the cellNav example. If data contains 300 entries and I do 

```
var rowIndex = $scope.gridOptions.data.length - 1;
gridApi.core.scrollTo($scope.gridOptions.data[rowIndex], $scope.gridOptions.columnDefs[0]);
```

No scrolling happened at all. I tracked down the issue to 

```
          percentage = scrollPixels / scrollLength;
          if (percentage <= 1) {
            scrollEvent.y = { percentage: percentage  };
```

and found that `percentage` is a little bit more than 1 in this case. I modified the code to look like

```
          percentage = scrollPixels / scrollLength;
          if (percentage > 1) { percentage = 1; } // <==== added this line
          if (percentage <= 1) {
            scrollEvent.y = { percentage: percentage  };
```

After that, I can successfully scroll to the last data entry.

**Comment by wduminy** [comment]
I also found an issue (seems to be the same). To reproduce:

- Fill the grid with more rows that can fit into the view.
- call `scrollTo()` to go to last row

It seems to scroll to the top of the last row; but the last row is not in the view.

Additional info

It could be related to the horizontal scroll bar.   

One solution might be to scroll to the bottom when the last row is the target of `scrollTo()`.
