### ISSUE TITLE
Aligning of rows are weird when scrolling to the bottom 

### ISSUE THREAD

**Issue by olofvi** [angular-ui/ui-grid#6572]
When I have a lot of rows in display 250-500+ and a scrollbar at the bottom the alignment gets weird. Looks like some problem when the scrollbar at the bottom appears. 
![evul](https://user-images.githubusercontent.com/30499007/36104046-36924a46-1011-11e8-9915-67637bd2213d.png)

**Comment by andrewkittredge** [comment]
Probably related to https://github.com/angular-ui/ui-grid/issues/6292
