### ISSUE TITLE
TypeError: Cannot read property 'options' of undefined at Object.shown (ui-grid.js:19094)

### ISSUE THREAD

**Issue by Tagar** [angular-ui/ui-grid#6578]
From https://issues.apache.org/jira/browse/ZEPPELIN-3238

No exceptions when paragraph changes status to "FINISHED", but when I hover "context menu" on the data grid at the top right side
with three horizontal bars (to see options like "export all data as csv" etc), Chome Console only then throws exceptions like:

> TypeError: Cannot read property 'options' of undefined
>     at Object.shown (ui-grid.js:19094)
>     at o.t.itemShown (ui-grid.js:2359)
>     at fn (eval at compile (vendor.cfb12f83ec630b56.js:39), <anonymous>:4:218)
>     at o.$digest (vendor.cfb12f83ec630b56.js:38)
>     at o.$apply (vendor.cfb12f83ec630b56.js:38)
>     at HTMLDivElement.<anonymous> (vendor.cfb12f83ec630b56.js:40)
>     at HTMLDivElement.dispatch (vendor.cfb12f83ec630b56.js:30)
>     at HTMLDivElement.q.handle (vendor.cfb12f83ec630b56.js:30)

Is this a known issue?

Thanks.

**Comment by Tagar** [comment]
Zeppelin uses ui-grid v4.0.11 - 2017-11-20

**Comment by mportuga** [comment]
Yes, this was an issue on version 4.0.11, it  was resolved as of 4.1.0
