### ISSUE TITLE
ui-grid-selection and ui-grid-tree-view in 4.2.4

### ISSUE THREAD

**Issue by geraldpereira** [angular-ui/ui-grid#6579]
I recently upgraded from 4.1.3 to 4.2.4 and noticed a change in the selection behavior when using a tree.

I created two plunker to explain this:
* [The 4.2.4 version](http://plnkr.co/edit/1hf1v4lo1mnxAiRNSXyP?p=preview)
* [The 4.1.3 version](http://plnkr.co/edit/8VpVQO?p=preview)

I want to select the second row (named Nieves Mack, $$treeLevel set to 1, the child node of the first tree node). In the previous version, it was selected as expected. Now when I select the second row, its parent node in the tree is selected.

Is this a bug or a change in the API?

**Comment by rolsson** [comment]
This change (regression?) seems to have been introduced in the 4.2.3 version.

**Comment by mportuga** [comment]
This was a change meant to address a number of logged issues.

See the following commit:
https://github.com/angular-ui/ui-grid/commit/f3d2a7f1019d269df567047be901e07523cefcb4

And the following bugs:
fix #3911, fix #6126, fix #6145, fix #6263, fix #6398

**Comment by geraldpereira** [comment]
@mportuga so I cannot select the first and only child without also selecting the parent node? Or is there an option to activate in the grid options?

If I activate the `multiselect: true`, when I click on the child node, the parent is also selected. I can then click on the parent node to only have the child selected.

If the multiselect option is set to false, the child node cannot be selected at all!

**Comment by nickxbs** [comment]
Hi, i agree with @geraldpereira, i have the same problem. In a treeview with `multiselect: false` is impossible to select child node.
