### ISSUE TITLE
extraneous lines if data in a column has "\n" character

### ISSUE THREAD

**Issue by Tagar** [angular-ui/ui-grid#6589]
Apache Zeppelin uses angular-ui/ui-grid for data tables visualization. 
If data has "\n" characters present, extra table lines are present.

![image](https://user-images.githubusercontent.com/3013418/36998541-7e6a4fe8-207a-11e8-8ea2-40ad9d1773cb.png)

Is there is an option to switch this behvior off. We think a better options could be:
- display "\n" as whitespace;
- display "\n" as "\n" (backslash, "n" character).

Thanks.

**Comment by mportuga** [comment]
Well, typically, /n is supposed to stand for a new line, so I don't believe the behavior that you are describing makes sense, in fact, it seems counter intuitive in my opinion. I believe that if you desire different behavior, you should strip out the /n from the data prior to passing it to ui-grid, or strip it out as part of a cell renderer.
