### ISSUE TITLE
Pinning and Auto-Resize render issue

### ISSUE THREAD

**Issue by sfebish** [angular-ui/ui-grid#6590]
With the combination of pinned columns and auto-resize, it seems that the grid is always leaving a spacer (.ui-grid-scrollbar-placeholder) even when there is no scrollbar. 

Using [example](http://plnkr.co/edit/pXwgNrAB8L42OKwnrYRN?p=preview), if you hide enough columns to get rid of the horizontal scroll you can reproduce the behavior. 

With scrollbar visible:
![withscrollbar](https://user-images.githubusercontent.com/32653326/37047649-7bb31e94-2163-11e8-903e-2b3eb2f9e12a.PNG)

Without scrollbar visible:
![withoutscrollbar](https://user-images.githubusercontent.com/32653326/37047657-8683e98e-2163-11e8-8bff-2e10f1d8d120.PNG)

The base of the pinned columns should be the same as the base of the unpinned columns. 

I can reproduce this in both I.E and Firefox.

**Comment by mportuga** [comment]
I believe this will be solved by reintroducing the WHEN_NEEDED attribute for scrollbars:
http://ui-grid.info/docs/#!/api/ui.grid.service:uiGridConstants
https://github.com/angular-ui/ui-grid/blob/master/src/js/core/factories/GridRenderContainer.js#L770
https://github.com/angular-ui/ui-grid/blob/master/src/templates/ui-grid/uiGridRenderContainer.html#L9
