### ISSUE TITLE
Cell remained focus causing scrolled up

### ISSUE THREAD

**Issue by BMK91** [angular-ui/ui-grid#6591]
Dear,

While I'm using `ui-grid-edit`, `ui-grid-cellNav` with `enableCellEditOnFocus: true` to use single click edit, I encounter an issue of scrolling up.

Please check the following plunker.
http://plnkr.co/edit/chouuTGlXHuWtQXk2mw1?p=preview

**Steps:**
Click on the first editable cell, then scroll-down.

Thanks.

**Comment by mportuga** [comment]
What is the issue? And was it specific to any browser or OS?

**Comment by BMK91** [comment]
Please read the question properly, I've given plunker with steps provided.

**Comment by mportuga** [comment]
I am sorry, but I am struggling to understand what you mean by "focus causing scrolled up", I tried clicking the first editable cell and scrolling down and nothing of note appeared to happen.

**Comment by BMK91** [comment]
See this video before closing.
https://vimeo.com/262246299

**Comment by m4m4m4** [comment]
I get this behavior too, if I click a cell at the bottom of what is rendered and then scroll upwards making the cell below the rendered rows, the grid scrolls up and sometimes multiple times which is really confusing.
I think it has to do with this commit letting through events that are undefined, previously it only triggered on click and keydowns: https://github.com/angular-ui/ui-grid/commit/cc8144ca8b9138dfd08fffbe8cd4382f853c76e2

**Comment by m4m4m4** [comment]
I should probably do a rebase by now.. The following commit reverts the behavior to how it was before where "beginEdit" function only listens to click and keydown events. But now it also accepts a null object which makes it possible to trigger a cell edit from the api.
