### ISSUE TITLE
Row selection check-mark issue

### ISSUE THREAD

**Issue by BMK91** [angular-ui/ui-grid#6593]
Hi guyz,

I think there's some minor mistake for row selection.
http://plnkr.co/edit/5F6tuNuft7QDhxgKCRPy?p=preview
When no data provided to grid, all selection checkbox remains checked.

Thanks.

**Comment by mportuga** [comment]
Hi, could you help me understand how that is a problem?

**Comment by mportuga** [comment]
This is a duplicate of #6582
