### ISSUE TITLE
Selected page on pagination bar

### ISSUE THREAD

**Issue by RobertCisek** [angular-ui/ui-grid#6596]
Hi guys,

I noticed some bug on pagination bar. Entering a number containing a comma e.g. 1,2 leads to the appearance of strange numbers like a 2.9999999999999996.

<a href="https://ibb.co/eZ5a7n"><img src="https://preview.ibb.co/d1U2nn/Zrzut_ekranu_z_2018_03_12_09_28_58.png" alt="Zrzut_ekranu_z_2018_03_12_09_28_58" border="0"></a>

Any ideas how fix it?

**Comment by mportuga** [comment]
I believe the solution here is to not allow any non-numeric characters, as page only integers make sense as page numbers.

**Comment by RobertCisek** [comment]
Yes but, if some client will write number contain a comma, it does't look like nice (look like as mistake). I have't found a solution to limit such behavior
