### ISSUE TITLE
Typo's in i18n/de.js -> gridMenu

### ISSUE THREAD

**Issue by Simsal** [angular-ui/ui-grid#6610]
Found some errors in german translation:
- exporterVisibleAsExcel: 'sichtbare Daten als Excel exportiere' -> missing n at the end. also it is weird that the command starts lowercase
- same with the other commands. Some start with uppercase ('Alle') and only visible ('sichtbare') are lowercase

If you are open to it, i would send in a pull request tomorrow.

**Comment by mportuga** [comment]
A pull request would be much appreciated.
