### ISSUE TITLE
Enter key press in ngGrid

### ISSUE THREAD

**Issue by sagarwasule** [angular-ui/ui-grid#662]
I require a functionality due to which I will be able to tab out to adjacent cell on enter button pressed in editable cell in ngGrid 

In short I want "enter" key press same as "tab" key press.
Please help.
Thank you

**Comment by mehakjain** [comment]
I did this using a custom directive and few changes in ui-grid-unstable.js

U need to add this directive in ur editable cell template:

angular.module('blablaApp')
.directive('handleEnter', function () {
    return {
        require: '?ngModel',
        link: function (scope, element, attrs, ngModelCtrl) {
            
            $(element).on('keypress', function (e) {
                var code = e.keyCode || e.which;
                if (code == 13) { // ENTER pressed
                    e.preventDefault();
                    document.activeElement.blur();
                }
                else {
                    //any custom code. I am using regex to avoid alphabets
                    if (String.fromCharCode(e.keyCode).match(/[^0-9\.]/g)) return false;
                }
            });
        }
    };
});


And in ui-gird-unstable.js file change modify the following code to make the behavior of enter as tab while traversing through row:

 getDirection: function (evt) {
          if (evt.keyCode === uiGridConstants.keymap.LEFT ||
            (evt.keyCode === uiGridConstants.keymap.TAB && evt.shiftKey) ||
            (evt.keyCode === uiGridConstants.keymap.ENTER && evt.shiftKey)) {
            return uiGridCellNavConstants.direction.LEFT;
          }
          if (evt.keyCode === uiGridConstants.keymap.RIGHT ||
            evt.keyCode === uiGridConstants.keymap.TAB || evt.keyCode === uiGridConstants.keymap.ENTER) {
            return uiGridCellNavConstants.direction.RIGHT;
          }

          if (evt.keyCode === uiGridConstants.keymap.UP) {
            return uiGridCellNavConstants.direction.UP;
          }

          if (evt.keyCode === uiGridConstants.keymap.PG_UP){
            return uiGridCellNavConstants.direction.PG_UP;
          }

          if (evt.keyCode === uiGridConstants.keymap.DOWN) {
            return uiGridCellNavConstants.direction.DOWN;
          }

          if (evt.keyCode === uiGridConstants.keymap.PG_DOWN){
            return uiGridCellNavConstants.direction.PG_DOWN;
          }

          return null;
        },
That' it. Hope this helps.
Happy codding :)
