### ISSUE TITLE
Pagination text should allow user to input page number as well as mouse scroll up/down to move back and forth while paginating

### ISSUE THREAD

**Issue by AnirbanIndecomm** [angular-ui/ui-grid#6650]
ui-grid-pager-control-input currently under pagination (ui-grid-pager-panel class) is set to type number , which doesn't allow user to manually set the page number from there . It satisfies only when we do a mouse scroll up/down.Is there any way / configuration so as a user can enter the page number as well .

Kindly advise

**Comment by mportuga** [comment]
User can enter the page number as well, they just need to select the number then write the new value.

**Comment by mportuga** [comment]
But you could always do a custom pagination template if you wanted a different type of input but.
