### ISSUE TITLE
angular ui-grid Filter and Group Selection issue for Selected Counts

### ISSUE THREAD

**Issue by akash-garg1** [angular-ui/ui-grid#6656]
If we implement grouping in ui-grid (v3 or v4) with column filter, and when we apply filter for any column and we select the filtered grouped row, it is selecting all rows after that filtered row.
It should not be the scenario ideally. It should only select the child rows of selected group, not all groups (those are not in filtered list even) after this.
This is making problem in selected count.

**Comment by mportuga** [comment]
Since I cannot reproduce it and I have received no response, I will close this issue for now. Feel free to reopen it if you can provide me with the information necessary to properly debug and fix this issue.
