### ISSUE TITLE
A case if we have to display data from json with objects and value like data=[{"id":1,"name":"ff"},"bb","cc",{.....}] how can we manage to display it because there was a solution to data of value but what if we have objects and values in the same array

### ISSUE THREAD

**Issue by fatifleu** [angular-ui/ui-grid#6662]
A case if we have to display data from json with objects and value like data=[{"id":1,"name":"ff"},"bb","cc",{.....}] how can we manage to display it because there was a solution to data of value but what if we have objects and values in the same array

**Comment by mportuga** [comment]
If I understand what you are saying correctly, you have rows of data in various different formats. I don't believe that we support that. The closest example that we have is the following tutorial:
http://ui-grid.info/docs/#!/tutorial/106_binding

**Comment by mportuga** [comment]
I suggest using a transformer function and formatting your data to a single format prior to passing it to the grid. For example:
http://plnkr.co/edit/UO9FWD37YaTo8cD1fPWH?p=preview

**Comment by fatifleu** [comment]
thank you so much for your response and your help, i learned a lot here in this ui grid .
