### ISSUE TITLE
v4.4.6 Export to CSV not working or showing errors.

### ISSUE THREAD

**Issue by brandonpearce2** [angular-ui/ui-grid#6666]
The  `exporterMenuCsv` option fails in version 4.4.6. I reverted back to 4.4.5  as a quick fix.

There are no error messages or network calls.

**Comment by mportuga** [comment]
At a quick glance, the only change in 4.4.5 to export feature was the getDisplayName changes that I did. So it stands to reason that it is causing the issue somehow:
https://github.com/angular-ui/ui-grid/commit/4c63239186c73fd3ba1723481ed67618897e9fe4

**Comment by brandonpearce2** [comment]
Just to be clear, 4.4.6 is broken. 4.4.5 is good.

**Comment by mportuga** [comment]
Sorry, I made a typo. Yeah, that is what I meant. 4.4.6 had a change for exporter to change the header names that I did. I suspect that would be the cause. Although, could you describe the issue a little more. I tried clicking the export data as CSV on this plunker and it worked for me: http://plnkr.co/edit/T3IeR2EIuZAj7RlnwsKo?p=preview

**Comment by mportuga** [comment]
I was also able to see it working with the plunker above on Mac Safari and Mac Firefox. What browser and operating system are you currently using?

**Comment by brandonpearce2** [comment]
I've been going through your plnkr, and adding my options, but so far it is working. I'm using windows/chrome. Basically I have an angularjs app that is reading from a REST call and displaying charts and tables. A dashboard essentially.

**Comment by mportuga** [comment]
I see. Well, once you manage to break my plunker let me know. I am curious to see what causes the issue.

**Comment by mportuga** [comment]
@brandonpearce2 Any luck reproducing it in my plunker?

**Comment by brandonpearce2** [comment]
I've spent an hour plugging in my options and templates and a few other fields and haven't been able to find the culprit. Unfortunately it's quite a beast of a dashboard I have so it could be 'n' number of things.

**Comment by jprr773** [comment]
After migrating ui-gris from version v3.2.1 to v4.4.6 , the export menu button is visible but when I click Export to PDF or CSV nothing happens.  3rd party JS libs csv.js and pdfmake.js wre e also updated. Chrome console does not fire any JS error. As recommended by @mportuga , I downgrade to version using 4.4.5.
Thank you for your time

**Comment by brandonpearce2** [comment]
@mportuga  I found it. I'm surprised I didn't try this earlier. I added a hidden field to the grid, and that is what's stopping the download.
All I did was add the following object to the column definitions. 
{
                        'field': 'eod_price',
                        'name': 'eod_price',
                        'type': 'number',
                        'displayName': 'EOD Price',
                        // 'enableHiding': false,
                        'minWidth': 145,
                        'cellClass': 'eod-price',
                        'cellFilter': 'numeraljs: \'0,000.00\'',
                        'visible': false
      },

**Comment by mportuga** [comment]
interesting, and does that work even in the plunker?

**Comment by mportuga** [comment]
I also noticed you have a cellFilter on the hidden column, which was a change in 4.4.5.

**Comment by mportuga** [comment]
I believe @monster910 might have just fixed this issue. Testing it tonight and might be releasing 4.4.7 tonight with the fix.

**Comment by mportuga** [comment]
I have confirmed that @monster910 fixed this issue.

**Comment by mportuga** [comment]
@brandonpearce2 @jprr773 I have released UI-Grid 4.4.7 tonight. I believe your issue is now fixed.

@jprr773 I also added some of the missing portuguese translations.

**Comment by jprr773** [comment]
I can only update the app next Monday and so then i'll let you know.
Thank you so much for all the effort and quick fix.
You guys rock!!!
Kind regards
Joao

**Comment by jprr773** [comment]
@mportuga , yes the issue was certainly related with hidden cols. 
 have many grids in my app, and the behavior was only present for grids with hidden cols (I'm glad you were quicker than me to figure this out).  
I've updated to 4.4.7 release and everything is working smooth including the PT translations,
thank you so much for all the effort and quick help, you guys rock!!!

**Comment by brandonpearce2** [comment]
@mportuga I switched to 4.4.7 and exporting is working for me. Thanks for getting that fix out so quickly.
