### ISSUE TITLE
how to set focus on particular column in ngGrid

### ISSUE THREAD

**Issue by sagarwasule** [angular-ui/ui-grid#667]
Hi

Can anyone help for how to set focus on particular column in editable ngGrid.
Suppose,
On tab/blur of last textbox in the form above grid I want the control to jump to 2nd column 1st row in grid.

Thank You

**Comment by jintoppy** [comment]
I believe this should be available with API. focusing a particular cell and scrolling to focus are common scenarios. Please reconsider
