### ISSUE TITLE
Firefox: Column Resize/Move in "disabled" grid

### ISSUE THREAD

**Issue by Klinton90** [angular-ui/ui-grid#6673]
In my project we use ui-grid with custom editable/validation features. Grid might be part of bigger form. To disable entire form, we put fields and grid inside `<fieldset ng-disabled="some">`. That cause some issues:
1) Actions on Grid Menu-Items are not firing: menu-item is `<button>`, which becomes disabled along with parent fieldset. Fix is easy: change template to replace `<button>` with `<div>` and apply css to `ui-grid-menu-item`. That issue exists in both Chrome and FF.
2) Next issue is reproducible only in FF: when you move/resize column `mouseup` events do not fire if mouse button is released above grid canvas. As soon as you move it outside and click/release - handlers are processed.

No workaround for now. I'll update ticket, if I find something.

**Comment by Klinton90** [comment]
Reason: https://makandracards.com/makandra/47961-firefox-cancels-any-javascript-events-at-a-fieldset-disabled
uiGrid add `mouseup` event listener to `$document`. `mouseup` event bubbles up to `<fieldset disabled>`, where browser "calls" `event.stopPropagation()`, so it never reaches `$document`.

Workaround:
1) Create custom directive on `uiGridHeaderCell` and `uiGridColumnResizer`. Find `var wrapperEl = gridUtil.closestElm("fieldset .ui-grid.grid" + uiGridCtrl.grid.id);`.
2) Listen to `$(element).on('mousedown', downFunc)`
3) In `downFunc` listen to `mouseup` on `wrapperEl`
4) In `upFunc` fire `mouseup` event directly on `$document`.

**Comment by mportuga** [comment]
Thank you for your comments @Klinton90, unfortunately, I believe I will have to close this issue as it is specific to a custom implementation of UI-Grid abd the current team maintaining the grid is very small. If you feel this is something that should be addressed in the main ui-grid repo and can provide a solution, we will gladly accept a pull request.

**Comment by Klinton90** [comment]
NP! I understand that we have very custom implementation. Hope my comments may help somebody else with similar approach.
