### ISSUE TITLE
Running Karma on Node 8.9.4

### ISSUE THREAD

**Issue by monster910** [angular-ui/ui-grid#6688]
With Node 8 I run into issue running Karma

K:\work\dev\github\monster910\ui-grid>grunt karmangular
Running "karmangular" task
Loading "grunt-karma.js" tasks...ERROR
>> TypeError: Cannot read property 'prototype' of undefined
Warning: Task "karma:angular-1.4.3" failed. Use --force to continue.

Check to see if Karma needs to updated or Node 6 is required

**Comment by mportuga** [comment]
I believe this is the same as 6214, which also mentions version support

**Comment by mportuga** [comment]
Fixed by #6696 6696
