### ISSUE TITLE
GRID UI NOT showing  VALUE

### ISSUE THREAD

**Issue by smarthotel123** [angular-ui/ui-grid#6716]
Grid ui not working my code is below

angular.module('myApp', ['ngAnimate', 'ui.bootstrap','ui.grid']);

angular.module('myApp').service('records', function() {
   
    this.data = [{
       
    }];
   
  
   
    this.save = function(record) {
       
        this.data.push(record);
    };
   
    this.delete = function(index) {
        this.data.splice(index, 1);
    };
});

angular.module('myApp').controller('HomeController', function($scope, $uibModal, records) {
    $scope.records=[{
        'date': '2018-04-18 00:00',
        'place': 'Bangalore'
    },{
        'date': '2018-04-18 55:00',
        'place': 'aaaaaaaa'
    }];
   
    records.data= $scope.records;
    $scope.records = records.data;
   
    $scope.openModal = function(record) {
        $uibModal.open({
            resolve: {record: null},
            templateUrl: 'modal.html',
            controller: 'ModalController',
            backdrop: 'static'
        }).result.then(function(newRecord) {
            records.save(newRecord);
        });
    };
     $scope.openModal1 = function(record) {
        $uibModal.open({
            resolve: {record: null},
            templateUrl: 'Test.html',
            controller: 'ModalController2',
            backdrop: 'static'
        }).result.then(function(newRecord) {
            records.save(newRecord);
        });
    };

    $scope.edit = function(record) {
        $uibModal.open({
            resolve: {
                record: record
            },
            templateUrl: 'modal.html',
            controller: 'ModalController',
             backdrop: 'static'
        }).result.then(function(updatedRecord) {
            angular.extend(record, updatedRecord);
        });
    };
   
    $scope.delete = function(index) {
      console.log(index + " in delete function");
      $uibModal.open({
        resolve: {record: index},
        template: '<div class="modal-body">' +
                  '<button class="btn btn-danger" type="button" ng-click="deleteRecord(index)">delete</button>' +
                  '<button class="btn btn-default" type="button" ng-click="cancel()">cancel</button>' +
                  '</div>',
        controller: 'ModalController',
        backdrop: 'static'
      }).result.then(function(deleteIndex) {
        console.log(deleteIndex);
        records.delete(deleteIndex, 1);
      });
    };

    $scope.addwithinCtrl = function() {
        var record = {
            'date': new Date(),
            'place': 'Hyderabad'
        };
        records.save(record);
    };
});

angular.module('myApp').controller('ModalController', function($scope, $uibModalInstance, record) {
   
    $scope.record = angular.copy(record);
   
    // save the input and dismiss the dialog
    $scope.save = function() {
        if($scope.record.status=="fine"){
       
$uibModalInstance.close($scope.record);
}
else{
$scope.error="somwthing wents wrong";
}
       
    };

    $scope.cancel = function() {
        $uibModalInstance.dismiss('cancel');
    };
   
    $scope.deleteRecord = function() {
      $uibModalInstance.close($scope.record);
    };
});

angular.module('myApp').directive('dateDirective', function() {
    return {
        scope: {
            model: '=ngModel'
        },
        restrict: 'A',
        templateUrl: 'date.html',
        controller: function($scope) {
            $scope.format = 'yyyy-MM-dd HH:mm';

            $scope.open = function() {
                $scope.status.opened = true;
            };

            $scope.status = {
                opened: false
            };
        }
    }
});

angular.module('myApp').controller('ModalController2', function($scope, $uibModalInstance, record) {
    $scope.gridOptions = {};
    $scope.record = angular.copy(record);
    $scope.reset = reset;
    $scope.processbar=false;
 
  function reset() {
    $scope.gridOptions.data = [];
    $scope.gridOptions.columnDefs = [];
    $scope.reset1 = "hhhhhhhhhhhhhhhhhh";
  }
    // save the input and dismiss the dialog
    $scope.save = function() {
        if($scope.record.status=="fine"){
       
$scope.processbar=true;
}
else{
$scope.error="somwthing wents wrong";
}
       
    };

    $scope.cancel = function() {
        $uibModalInstance.dismiss('cancel');
    };
   
    $scope.deleteRecord = function() {
      $uibModalInstance.close($scope.record);
    };
});

angular.module('myApp').directive('fileread', function() {
     return {
    scope: {
      opts: '='
    },
    link: function ($scope, $elm, $attrs) {
      $elm.on('change', function (changeEvent) {
        var reader = new FileReader();
       
        reader.onload = function (evt) {
          $scope.$apply(function () {
            var data = evt.target.result;
           
            var workbook = XLSX.read(data, {type: 'binary'});
           
            var headerNames = XLSX.utils.sheet_to_json( workbook.Sheets[workbook.SheetNames[0]], { header: 1 })[0];
           
            var data = XLSX.utils.sheet_to_json( workbook.Sheets[workbook.SheetNames[0]]);
           
            $scope.opts.columnDefs = [];
            headerNames.forEach(function (h) {
              $scope.opts.columnDefs.push({ field: h });
            });
           
            $scope.opts.data = data;
           
            $elm.val(null);
          });
        };
       
        reader.readAsBinaryString(changeEvent.target.files[0]);
      });
    }
  }
});

<style>
   body {
  /* font-family: Verdana; */
  padding: 20px;
}

.grid {
  width: 100%;
  height: 400px;
}

.grid-msg-overlay {
  position: absolute;
  top: 0;
  bottom: 0;
  width: 100%;
  background: rgba(0, 0, 0, 0.4);
}

.grid-msg-overlay .msg {
  opacity: 1;
  position: absolute;
  top: 20%;
  left: 20%;
  width: 60%;
  height: 50%;
  background-color: #eee;
  border-radius: 4px;
  border: 1px solid #555;
  text-align: center;
  font-size: 24px;
  display: table;
}

.grid-msg-overlay .msg > .center {
  display: table-cell;
  vertical-align: middle;
}

.grid input[type="file"] {
  font-size: 14px;
  display: inline-block;
}
.modal-dialog { width:900px;
  }

#loader {
  position: absolute;
  left: 50%;
  top: 50%;
  z-index: 1;
  width: 150px;
  height: 150px;
  margin: -75px 0 0 -75px;
  border: 16px solid #f3f3f3;
  border-radius: 50%;
  border-top: 16px solid #3498db;
  width: 120px;
  height: 120px;
  -webkit-animation: spin 2s linear infinite;
  animation: spin 2s linear infinite;
}

@-webkit-keyframes spin {
  0% { -webkit-transform: rotate(0deg); }
  100% { -webkit-transform: rotate(360deg); }
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}

.full-height {
  height: calc(100vh - 2px - 30px);
}
</style>
<div>
    
        <div class="modal-header bg-primary">
            <h4 class="modal-title">Income>>>>>>>>>>> <span>{{error}} </span></h4>
        </div>
        <div class="modal-body">
    
          <button type="button" class="btn btn-success" ng-click="reset()">Reset Grid</button>
      <br />
      <br />
      <div id="grid1" ui-grid="gridOptions"  class="grid full-height">
        <div class="grid-msg-overlay" ng-show="!gridOptions.data.length">
          <div class="msg">
            <div class="center">
              <span class="muted">Select <span>".xls,.xlsx,.ods"</span> File</span>
              <br />
              <input type="file" accept=".xls,.xlsx,.ods" fileread="" opts="gridOptions" multiple="false" />
            </div>
          </div>
        </div>
        <div class="grid-msg-overlay" ng-show="processbar">
          <div>
            <div class="center">
               <div id="loader"></div>
            </div>
          </div>
        </div>
      </div>
      
        </div>
        
        <div class="modal-footer">
            <button type="button" class="btn btn-success" ng-click="save()">save</button>
            <button type="button" class="btn btn-default" ng-click="cancel()">Cancel</button>
  
   
</div>

**Comment by mportuga** [comment]
@smarthotel123 Please provide a plunker or code pen. As it is, I cannot debug this code. Also, please use stackoverflow or gitter for questions.

**Comment by mportuga** [comment]
Here is a plunker for you to use in your future queries: http://plnkr.co/edit/dLZtflGVWmg0wYXt9xMS?p=preview
