### ISSUE TITLE
$scope is not defined on afterCellEdit event

### ISSUE THREAD

**Issue by rockbass2560** [angular-ui/ui-grid#6735]
I got the error $scope is not defined

    angular.module('GridCtrl', []).controller('GridController', function(Nerd, $scope) {
    $scope.cambios = [];
    
    var vm = this;

    vm.gridOptions = {};
    vm.gridOptions.enableSorting = true;
    vm.gridOptions.columnDefs = [
        { name:'Nombre', field: 'nombre' },
        { name:'Edad', field: 'edad', type:'number' },
        { name:'nacionalidad.nombre', displayName:'Nacionalidad', editableCellTemplate: 'ui-grid/dropdownEditor', editDropdownIdLabel: 'codigo', editDropdownValueLabel: "nombre",
        editDropdownOptionsArray: [{codigo: "MX", nombre: "Mexico"}, {codigo: "USA", nombre : "USA"}] },
        { name:'Bandera', field:"nacionalidad.codigo", cellTemplate: '<img ng-src="http://www.countryflags.io/{{grid.getCellValue(row, col)}}/flat/32.png" lazy-src>', enableCellEdit: false}
    ];
    vm.gridOptions.onRegisterApi = function(gridApi) {
        //set gridApi on scope
        $scope.gridApi = gridApi;
        gridApi.edit.on.afterCellEdit($scope, function(rowEntity, colDef, newValue, oldValue) {
            console.log(rowEntity._id + ' Nuevo Valor: ' + newValue);
            $scope.$apply(); //error is here
        });
    };

    Nerd.get(function(success){
        var datos = success.data;

        vm.gridOptions.data = datos;
       
    }, function(error){
        alert(error);
    });
});

`

I wanted to use the $scope when the event afterCellEdit is fired, but I received an error saying me that $scope doesn't exist. This code I took from an example from official web page.

I tried to find what I have to do, but I didn't find an answer, thanks.

**Comment by mportuga** [comment]
What is nerd above?
