### ISSUE TITLE
cellFilter on columnDefs not working with Time

### ISSUE THREAD

**Issue by Boscagoo** [angular-ui/ui-grid#6736]
I try to render a time in a column. From db, the type is time(0) (MSSQL). I try this:

`{
                                                name: 'Ora Match',
                                                field: 'Time',
                                                type: 'date',
                                                cellFilter: 'date: "shortTime"',
                                                enableSorting: false,
                                                enableFiltering: false,
                                                enableColumnMenu: false,
                                            },`
But not working. I also try custom filter, such as `cellFilter: 'date: "HH:mm"'` But not working. Bug or something wrong?

**Comment by mportuga** [comment]
This appears to be working for me:
http://plnkr.co/edit/FTiqdNzC7DCAy9AnFEUP?p=preview

**Comment by Boscagoo** [comment]
Hi @mportuga , i see the example. The difference is this: in Your example, You have a DateTime (like 1991-02-21T23:02:31+06:00). My case is this: I have Date and Time in 2 different attributes in the table: I have Date (1991-02-21) and Time (06:00). I would like to render the date and the time in different column. With date I have no problem, but with time, uigrid render Time with HH:mm:ss, but I only want to render HH:mm. Is this possible?
I do not know if my problem is clear.
Thanks
M.

**Comment by mportuga** [comment]
@Boscagoo Could you please provide a plunker to better demonstrate your issue? I don't see how having two separate columns would make a difference for this.

**Comment by Boscagoo** [comment]
Sorry for late!
Here the Plunker: http://plnkr.co/edit/YSpjqiCtmXGassmkj86d?p=preview

The problem is this: I have a "Time" filed in the array that is a time only DB type (in example: 21:00:00). I want to render in uigrid only Hour and Minute. Is this possible?
Thanks
M.

**Comment by mportuga** [comment]
@Boscagoo The problem is that you are not using a date object. If you create a filter that coverts the string that it receives from the back end to a date object first, then it will work. See my example here:
http://plnkr.co/edit/YpnzbdzBf34wAMri2hLQ?p=preview

**Comment by Boscagoo** [comment]
Thanks a lot for the help!
