### ISSUE TITLE
Translate Ui-grid Angular displayName Dynamic Change

### ISSUE THREAD

**Issue by DiskProphet** [angular-ui/ui-grid#6740]
In this link http://plnkr.co/edit/KnrKTst5dWXvlZNeIy9c?p=preview

When i click the header menu to change language, **The header text does not change after grid is rendered.**

If have any solution to fix it ? (When i change language, The header text will change too)

Thank you

**Comment by mportuga** [comment]
This is not an ui-grid issue. $translate is a separate thing from the ui grid translations. Regardless, you can achieve the desired behavior with an ng-change function on that dropdown, see my example code here:
http://plnkr.co/edit/f8ZOfp2VEzel73oKO4C1?p=preview
