### ISSUE TITLE
ng grid Export excel to mail

### ISSUE THREAD

**Issue by priyasv** [angular-ui/ui-grid#676]
Hi,
ng grid Export to excel function works as per the site - http://plnkr.co/edit/keci2Y?p=preview

Need a link as "Export to mail" which does the functionality of opening the mail box and attaching the exported excel sheet of ng grid.

Can someone provide me suggestion how to implement it?

**Comment by sirajudeen013** [comment]
Is there any luck to send data as attachment mail now?
