### ISSUE TITLE
ui-grid, array selection on gridApi, selectRow does not select more than one selection

### ISSUE THREAD

**Issue by mutlumot** [angular-ui/ui-grid#6786]
Hi all,

I have a page that shows records in a grid. This page has refresh timer for 5 seconds for instance.
As you all understand refresh timer is $interval for us to keep data update.
So, in each 5 sec. I'm refreshing grid data, so if we have selected row in the grid, I can re-select with; 

`$scope.gridApiDowntimes.selection.selectRow($filter("filter")(vm.grid.data, { StartTime: selectedItemsOfGrid[cnt].StartTime }, true)[0]);`

But when you select more than one item, I can not re-select them in refreshed data, I tried to do with above code in a for loop, but it did not work, it selects just once.

Do you have any solutions about that?

Thanks in advance

**Comment by mportuga** [comment]
Well, selectRow only selects one row at a time, you might need to look on the rows that you want to select.
