### ISSUE TITLE
Calculating Total for the data present in the column

### ISSUE THREAD

**Issue by sagarwasule** [angular-ui/ui-grid#679]
Hi,
I want to calculate the total for the data present in the column. Suppose I have a column with principal amount. I want to display the net total amount at the bottom of the grid or footer of the grid.

How can I implement this ?
Thanks

**Comment by SalasSanchez** [comment]
You can include a custom footer template on the gridOptions. I looked for the default formatting of the footer in the source code and copied that, but added the function that calculates the totals. Something like this:

$scope.gridOptions = {
data: 'hereGoesTheData',
columnDefs : [list of your column names],
showFooter: true,
footerTemplate: '<div ng-show="showFooter" class="ngFooterPanel" ng-class="{\'ui-widget-content\': jqueryUITheme, \'ui-corner-bottom\': jqueryUITheme}" ' +
                'ng-style="footerStyle()"><div ng-style="{ \'cursor\': row.cursor }" ng-repeat="col in renderedColumns" ng-class="col.colIndex()" ' +
                'class="ngCell {{col.cellClass}} " ng-cell style="text-align:right;">' +
                '{{getTotal(col.field)}}</div></div>'
};


And the define $scope.getTotal to do whatever you want it to do.

**Comment by SalasSanchez** [comment]
See here: http://stackoverflow.com/questions/19100601/what-is-best-way-to-do-column-totals-in-ng-grid/29550327#29550327

**Comment by PaulL1** [comment]
This is a pretty old issue to be commenting on.  ui-grid has native footers that can do aggregation.  I think ng-grid 2.x also has, and those would be the right way to go about it.

**Comment by SalasSanchez** [comment]
I couldn't find that functionality on ngGrid, so that's interesting. I also think many people are not onto ui-grid yet, and so considered my answer helpful.
