### ISSUE TITLE
Row selection example broken

### ISSUE THREAD

**Issue by AmyBlankenship** [angular-ui/ui-grid#6797]
We have an issue in our project where if enableRowHeaderSelection is set to false, the grid disappears, so I wanted to look at your example in plunker to see if I could spot the difference. Unfortunately, the example does not work in any browser I tried it in, so I didn't get very far.

**Comment by mportuga** [comment]
Here you go. There is an issue with our site right now and having the dependency on angular-aria does not come with the plunker:
http://plnkr.co/edit/pmoITJty8dW0HOzn5UE7?p=preview
