### ISSUE TITLE
 impoting fabric-js UI components to angular 4 project

### ISSUE THREAD

**Issue by shankargurutarikere** [angular-ui/ui-grid#6802]
I have followed the following step to install fabric js UI components in my project

npm install ng-office-ui-fabric --save

provided in this link(https://github.com/ngOfficeUIFabric/ng-officeuifabric#installation)

I have to get these css files
1)/node_modules/office-ui-fabric/fabric.min.css
2) /node_modules/office-ui-fabric/fabric.components.css"
 in node_modules folder  after installation,But i am not.
![capture](https://user-images.githubusercontent.com/31584520/42796374-672600de-89a7-11e8-9cd5-799a1a583c69.PNG)

I am stuck here.I know that, this is not the ui-grid issue but i am trying hard solve this issue.please help me out.

**Comment by mportuga** [comment]
Per the instructions, you also have to download the office-ui-fabric-core library, and that is where you will find the CSS.

https://www.npmjs.com/package/office-ui-fabric-core

> Install the library (which should also download the Angular & **office-ui-fabric dependent libraries**:
