### ISSUE TITLE
isRowSelectable with style

### ISSUE THREAD

**Issue by luzhiy123** [angular-ui/ui-grid#6805]
I use isRowSelectable , and all check boxes have the same style, what can I do to let them has different style

**Comment by mportuga** [comment]
Sadly, this issue made me notice a bug with the selection tool that makes it impossible to see whether or not a row is selectable by just inspecting the DOM. I will try to work on it soon, but in the mean time, you can use the following workaround:
http://plnkr.co/edit/U7buR1ZldHqEAhqQ73JO?p=preview

**Comment by luzhiy123** [comment]
ok, thanks
