### ISSUE TITLE
Display Cell Text of 1 Cell on Hover of another Cell in UI Grid

### ISSUE THREAD

**Issue by dheerajarmy** [angular-ui/ui-grid#6807]
In my UI Grid, I have 3 columns
1. Table Name
2. Error Description
3. Logged Date Time

I want to remove Error column and I want to show those errors on hover of table name.
Please help
Thanks in Advance

**Comment by mportuga** [comment]
I recommend using the cellTooltip attribute. No hidden columns needed. See the following plunker for an example.
http://next.plnkr.co/edit/gOnOulFq2Pi56n5B
