### ISSUE TITLE
ui-grid.ttf is not a valid font file

### ISSUE THREAD

**Issue by ESPNSTI** [angular-ui/ui-grid#6809]
In 4.6.2, when double clicking on src/font/ui-grid.ttf in Windows, it shows a dialog that indicates "The requested file ...\ui-grid.ttf is not a valid font file".

Looking at a diff of the file between commit 8096ed043b and ec13255f61, it looks like a "0D 0A" was changed to just a "0A", so it appears that a CRLF to LF conversion was done.

The ui-grid.eot file seems to also have gone through a CRLF to LF conversion.

**Comment by IceDune** [comment]
@ESPNSTI hi, can i take this issue?

**Comment by IceDune** [comment]
shall i replace the older working files with the present ones?

**Comment by ESPNSTI** [comment]
Yes, go ahead.

**Comment by IceDune** [comment]
i have done a PR

**Comment by nickxbs** [comment]
Hello, i think that the same error was introduced with the commit https://github.com/angular-ui/ui-grid/commit/7f2d079c69a7ec3f5a34a4934d26cde4dbcc9827

**Comment by jmuker** [comment]
This is still an issue in v4.10.3, when can we see this in a release?

**Comment by orneryd** [comment]
Thanks for contributing! This repository has been transferred, and we're preparing the new 5.x release. We're closing older issues and pull requests as part of the reset. Please join us on Discord to follow the work or continue the conversation: https://discord.gg/Baz4w8ZWN
