### ISSUE TITLE
move GridMenu to left side

### ISSUE THREAD

**Issue by Xavierantony1982** [angular-ui/ui-grid#6811]
We are just adding the grid menu by adding the statement enableGridMenu=true, This creates the grid menu in the right side of the grid.

Is there a way to enable it in the left side of the grid.

**Comment by mportuga** [comment]
CSS would be the way to do that

**Comment by mportuga** [comment]
Here is an example: http://plnkr.co/edit/aveJXIcqPDprhRZ9zmjK?p=preview
