### ISSUE TITLE
Exporter Excludes Parent Nodes (TreeView)

### ISSUE THREAD

**Issue by TehCupcakes** [angular-ui/ui-grid#6819]
The "All data" option for the exporter is insufficient because it does not actually export all data. When combined with TreeView, it presumes that any parent nodes are merely for grouping and categorizing data, and not part of the data itself. It seems to me that there should be another gridOption to use with exporter that lets you include _all_ data, not just leaf nodes. (And in my opinion that should be the default behavior.)

This is regardless of which export format is chosen. It comes down to the getData and getDataSorted functions in ui-grid.exporter.js.

**Comment by ak-yaps** [comment]
So is there any solutions to get parent nodes in export all data? I'm trying with gridMenuCustomItems but only get same data as 'export all data', only children, not parents

**Comment by SanJagDar** [comment]
I am having the same trouble exporting data inside a Tree View. Only leaf nodes get exported and not the parent nodes. Applies across all file formats chosen.

**Comment by DeanDevlos** [comment]
I would love to see this fixed as well, but thanks to @SanJagDar for the tip about Export visible!
