### ISSUE TITLE
Custom Header Template ONLY Works when ui-grid="options" is used in html

### ISSUE THREAD

**Issue by WorkMAE** [angular-ui/ui-grid#6823]
This has to be a bug because if not it is a terrible design decision.
Check this fiddle out below, then change ui-grid="options" to anything else and change the appropriate other items where options is used to whatever you changed it to and it no longer works. What happens if you have multiple grids on a page that need custom headers?  Only one of them could use "options" and the rest simply won't work.

https://jsfiddle.net/wexmj2Lw/228/

**Comment by mportuga** [comment]
I am not sure what you mean... Are you talking about changing the variable name, because that works? I am sorry, I am certain the misunderstanding is on my side, but I can't understand what you are trying to do here.

**Comment by WorkMAE** [comment]
When you declare a ui-grid in the div.

<div ui-grid="options"> works
<div ui-grid="myOptions"> or any other name other than options does not with a custom header template

**Comment by m4m4m4** [comment]
I dont see anything breaking by changing the options variable to something else:
https://jsfiddle.net/pvj8q4r5/

The "grid.options" in the template is bound to the grid instance, if you need to access any other variable in the scope have a look at grid.appScope
