### ISSUE TITLE
Documentation issue : 112 Add/Delete/Swap Data -> error 404

### ISSUE THREAD

**Issue by Kitcat711** [angular-ui/ui-grid#6833]
Bonjour,
I am having an issue accessing this aprt of the documentation:
http://ui-grid.info/docs/#!/tutorial/Tutorial:%20112%20Add/Delete/Swap%20Data

This is probably because of the "/" in the name of tutorial entry:
**112 Add/Delete/Swap Data**

That is ruining my day :-/

Thanks for your work guys.
Kitcat

**Comment by unaccomplished** [comment]
I'd like to give this issue at try.
