### ISSUE TITLE
how can I use this o vm instead $scope to declare functions to use in ui-grid?

### ISSUE THREAD

**Issue by anibalardid** [angular-ui/ui-grid#6845]
Hi ! 
I'm trying ui-grid.
And I have a lot of methods/functions. For example to call when click/select row.
It works if I put into template something like that:
` ng-click="grid.appScope.deleteModal($event,row.entity.id)"`

And having method like this:
```
$scope.deleteModal = function(event, id) {
}
```

But it doesn't work If I declared as:
`this.deleteModal = function(event, id) {}`

best regards

**Comment by ProSpartan** [comment]
If you have your controller using `controllerAs` for vm, then do the following.

Set `var vm = this;` if you have not already.
Next, in the grid options, set `vm.gridOptions.appScopeProvider = vm;`. This provides vm as the appScope.
Then set your function on `vm` as well: `vm.deleteModal = function(event, id) {}`.

That should get it for you. I had this issue when I started as well, and this is what solved it for me.

**Comment by anibalardid** [comment]
thanks ! I fixed with: gridOptions.appScopeProvider = this 
:+1: 

:100:
