### ISSUE TITLE
getting Cannot read property 'replace' of undefined error for ui-grid dropdown implementation

### ISSUE THREAD

**Issue by sachinwakade** [angular-ui/ui-grid#6849]
I have referred http://next.plnkr.co/edit/1TYAVtzheQAYZivotJQN?preview, 
also I have added below dependencies into module, 
ui.grid.edit
ui.grid.cellNav

is there any other dependency needed ?

angular.js:12722 TypeError: Cannot read property 'replace' of undefined
    at beginEditAfterScroll (ui-grid.js:17020)
    at ui-grid.js:16877
    at processQueue (angular.js:14991)
    at angular.js:15007
    at Scope.$eval (angular.js:16251)
    at Scope.$digest (angular.js:16069)
    at angular.js:16290
    at completeOutstandingRequest (angular.js:5729)
    at angular.js:6006

**Comment by pakornsak** [comment]
@sachinwakade Could you please provide the steps to reproduce the error?
