### ISSUE TITLE
CellNav Shift+Click

### ISSUE THREAD

**Issue by ProSpartan** [angular-ui/ui-grid#6850]
Currently, the code only checks the event for Ctrl and Meta keys at [line 1076](https://github.com/angular-ui/ui-grid/blob/1051dee51fab1eba72e5f9497975c1f7c3f21b51/src/features/cellnav/js/cellnav.js#L1076).

The [CellNav GridOptions API](http://ui-grid.info/docs/#!/api/ui.grid.cellNav.api:GridOptions) states that it uses Shift+Click, but that is incorrect.

**Comment by pakornsak** [comment]
When using Shift+Click, the grid should clear a previous selection and make a range selection from the last focused cell to a new selected cell.

**Comment by ProSpartan** [comment]
Bump
