### ISSUE TITLE
Ui-Grid refresh/Reload issues

### ISSUE THREAD

**Issue by VardhamanH** [angular-ui/ui-grid#6853]
[Ui-GridView.zip](https://github.com/angular-ui/ui-grid/files/2407989/Ui-GridView.zip)

**Comment by VardhamanH** [comment]
Please find the above attached .zip file, we are using angular 6 version, initially page load event grid is trigger, once button click event trigger then ui-grid is not trigger, only DOM fired.

**Comment by jniles** [comment]
Hi @VardhamanH,  please note that ui-grid is tested with AngularJS, not Angular 2+.  You are probably better served using an Angular grid.
