### ISSUE TITLE
Error when try to hide column if don't use grid-menu

### ISSUE THREAD

**Issue by SvichV** [angular-ui/ui-grid#6857]
When we don't use grid menu for grid and try to hidden column through the clumn menu - grid hide the column but throw the error.

You also can see it at ui-grid.info in complex example
Screenshot:
![image](https://user-images.githubusercontent.com/29715425/46197900-b992ca00-c313-11e8-9595-44d88fd77a7a.png)

Steps to reproduce: 
1) In config disable grid menu, enable column menu and hidding column
2) Try to hide column through the column menu
3) See error in the console

**Comment by pakornsak** [comment]
When selecting "Hide Column" menu, the grid tries to set a focus back to Column Menu button without checking that the column is already hidden.

As you can see the warning in console, the grid cannot get the Column Menu button of the hidden column. I believe this is a bug.

To fix this issue, maybe grid should check if the column is hidden or not before setting back the focus.
