### ISSUE TITLE
Add a property to column

### ISSUE THREAD

**Issue by morgs32** [angular-ui/ui-grid#686]
I'd like to add my own tooltip, using a header cell template. To do so I'd like to create a column property called "tooltip" for instance. Tried that and it doesn't show up in the col  properties. What do you think about giving us that functionality. Otherwise I create a new template in each case?

Going to reference this closed issue: https://github.com/angular-ui/ng-grid/issues/317

**Comment by lmessinger** [comment]
Hi, 
The native ui-grid implementation provide an ellipsis if the field is too big for the column width.I would like to add a tooltip to this, so the user can see the whole field when hovering. I tried to add a simple template:

<script type="text/ng-template" id="cell-general.tpl.html">

    <div title="{{COL_FIELD}}">{{COL_FIELD}}</div>
</script>

but then, the initial text word-wraps and it  looks aweful. 

any ideas?

many thanks
Lior
