### ISSUE TITLE
how to determine if cell is editable in ui grid?

### ISSUE THREAD

**Issue by alex-mendy** [angular-ui/ui-grid#6862]
How do I determine if a particular column is Editable in UI Grid? I do have cellEditableCondition defined which controls whether cell is Editable or Read-Only. Does colDef has a property that can be interrogated to determine if column is Editable?

**Comment by pakornsak** [comment]
If I understand correctly, there will be both editable and read-only cell in the same column. Have you try cellTemplate with cellEditableCondition?

**Comment by alex-mendy** [comment]
Correct, I am using the cellEditableCondition which makes my cell editable or read-only. I am looking for a way to determine if my cell is editable in the controller logic.

**Comment by pakornsak** [comment]
Could you please provide me an example when you use the editable cell in the controller?

What I am thinking is to set row.isEditable property when cellEditableCondition is called.

**Comment by alex-mendy** [comment]
I have below condition defined on my column. 
cellEditableCondition: function($scope){
return $scope.row.entity[utAppConstants.gridColumns.stampDutyName.field] != utAppConstants.notApplicable;
				},

I need to know in the controller if the column is editable. For example,
if (col.isEditable){
  // do sometging
}

**Comment by pakornsak** [comment]
col.isEditable cannot be evaluated since the column can contain both editable and normal cells.

**Comment by alex-mendy** [comment]
I am aware of that. Hence, was trying to find out if anything else is available to determine if the cell is in Edit mode.

**Comment by pakornsak** [comment]
I just made an example of row.isEditable [here](http://plnkr.co/edit/3B5VWqaStIFk3G9BmcJO?p=preview).

I use `registerDataChangeCallback` to set `row.isEditable` when grid.data is set.

**Comment by alex-mendy** [comment]
Thanks. That is a work around. I thought something is readily available (out of the box) to interrogate cell if it is editable.

**Comment by mportuga** [comment]
Thank you for all your help @pakornsak !
