### ISSUE TITLE
Cannot read property '$$phase' of null while using ng-grid in tabset 

### ISSUE THREAD

**Issue by dineshmickey** [angular-ui/ui-grid#6864]
```
Uncaught TypeError: Cannot read property '$$phase' of null
    at Object.n.digest (ng-grid-1.3.2.js:139)
    at Object.n.BuildStyles (ng-grid-1.3.2.js:125)
    at Object.n.RebuildGrid (ng-grid-1.3.2.js:137)
    at ng-grid-1.3.2.js:467

```

How could i resolve this ???
This makes the ng grid hidden 
and when i do 

`$window.resize()`

I get the view visible
But i get the above error in the console every time i toggle the tabset

**Comment by dineshmickey** [comment]
ng-grid-1.3.2.js:139 :  I could see 
`    e.$root.**$$phase** || e.$digest()`

**Comment by mportuga** [comment]
ng-grid is no longer supported.
