### ISSUE TITLE
Possibly unhandled rejection: not-element

### ISSUE THREAD

**Issue by SvichV** [angular-ui/ui-grid#6871]
Angular.js version: 1.7.3;
ui-grid.js version:  4.6.3;
plunker: https://plnkr.co/edit/GV64cnmcTBedfyA160gW?p=preview

I prepared plunker with different column definition options.

1. If `enableColumnMenu: true` and `enableHiding: false, enableSorting: false` we have empty column menu and we try to open it we got `Possibly unhandled rejection: not-element` error in console.
Steps to reproduce:
   - Open plunker which linked before and Run it
   - In scripts can see that first column definition have options which described before.
   - Try to open 1st column menu
   - Got error in console

2. If `enableColumnMenu: true` and `enableHiding: true, enableSorting: false`  we have column menu with 1 menu item inside `Hide column` and when we try hide it we got `Possibly unhandled rejection: not-element` error in console.
Steps to reproduce:
   - Open plunker which linked before and Run it
   - In scripts can see that second column definition have options which described before.
   - Try to open 2nd column menu
   - Got error in console

**Comment by MartijnWelker** [comment]
I've pinned the issue to the [menu-hidden](https://github.com/angular-ui/ui-grid/blob/master/src/js/core/directives/ui-grid-column-menu.js#L382) callback, it's trying to focus on the column even though `$scope.col.visible` is false (and therefore the column is not rendered and not focusable). I'm currently making a PR to fix the issue.

**Comment by MartijnWelker** [comment]
There's another issue in the [menu-shown](https://github.com/angular-ui/ui-grid/blob/master/src/js/core/directives/ui-grid-column-menu.js#L401) callback. If there are no buttons in the dropdown it's still trying to focus the first element which will then also throw the error.

**Comment by gm-tm** [comment]
On UI-Grid 4.8.0 with AngularJS 1.7.8 I'm still getting the aforementioned error.

I was getting the error while calling the `pageLastPageClick` function on `uiGridPager` directive while using an external pagination system.

In my case it seems connected to the `gridUtil.focus.bySelector()` function not having its 
`.catch(angular.noop)`.
