### ISSUE TITLE
Is it possible to set expandableRowTemplate inline? 

### ISSUE THREAD

**Issue by shogan94** [angular-ui/ui-grid#6875]
I'm trying to set expandableRowTemplate inline, but can't get it working..

something like 
    `expandableRowTemplate: '<div ui-grid="row.entity.subGridOptions" style="height:150px;"></div>',`

**Comment by mportuga** [comment]
I have no problem doing it. See here:
http://plnkr.co/edit/tgMwoSyDnQQiebL5m9Vj?p=preview
