### ISSUE TITLE
scroll one row at a time when scroll button is clicked 

### ISSUE THREAD

**Issue by nallagondaa** [angular-ui/ui-grid#6876]
how can i control the uigrid to scroll one row a time right now its scrolling by 2 rows with click on scroll button (scroll arrows). how can I access that scroll arrows(butons) in the angular .JS file and then apply 1 row at a time

**Comment by nallagondaa** [comment]
anybody help I need this functionality only on user clicking on arrow of the scroll of grid

**Comment by mportuga** [comment]
Since we use a default browser scroll bar, not a custom one, I don't believe that this is possible.
