### ISSUE TITLE
ui-grid is inside Angular bootstrap Modal tab collapsing

### ISSUE THREAD

**Issue by ps-1993** [angular-ui/ui-grid#6899]
When ui-grid is used inside a tab on Angular modal it's loading first in collapse mode. On click on the grid or on scroll of grid it expands and comes up fine. 
Also on change of tab it's collapsing first and then expands after few seconds.
Tried the $scope.gridApi.grid.handleWindowResize() approach. No help

**Comment by rpinco** [comment]
I can confirm, i've been fighting with this too. My grid is on a uib-tab, and has variable width on 1 column (although it used to be on several): 
` columnDefs: [ 
                    { name: this.$filter ('translate')('name'), field: 'name', width: '20%', cellTooltip: true },
                    { name: this.$filter ('translate')('Description'), field: 'description', width: '20%', cellTooltip: true},
                    { name: this.$filter ('translate')('Value Type'), field: 'valueType', width: '20%', cellTooltip: true},
                    { name: this.$filter ('translate')('Regex'), field: 'regex', width: '*', cellTooltip: true },
                    { name: this.$filter ('translate')('Actions'), field: 'actions', enableSorting: false, enableHiding: false, width: '15%'}
                ], `

It seems that if the ui-grid is out of focus on page load, the width of the columns is not beign calculated. 
A workaround i found for this is to trigger an event on tab click (or modal load, in your case), that switches a flag, and use an ng-if on the ui-grid to load it when the event fires: 

On template: 
` <div id="grid2"  ng-if="$ctrl.showTable" ui-grid="$ctrl.gridOptions" class="grid customerserviceorders" ui-grid-pagination ui-grid-resize-columns  ui-grid-move-columns></div>`

On controller: 
`
constructor ( $rootScope) {
    this.$rootScope = $rootScope
    this.showTable = false
}

$onInit () {
    this.$rootScope.$on('tabSwitch', (data, event)=>{
                this.showTable = true
   })
}
`

This is far from an acceptable answer, but for now, it seems to work. I've tried: 
1- several plugins such as `ui-grid-auto-resize` and `ui-grid-auto-fit-columns` 
2- call handleWindowResize, on the onRegisterApi function, using the onGridRendered events, on ng-init, on $onInit, nothing works

Without the event and the ng-if, it just shows every tab collapsed to the left. Any help would be appreciated

**Comment by ps-1993** [comment]
Thanks a lot for the detailed explanation. After incorporating above suggested changes the grid is no longer collapsing to left side, but there is a bit of flickering effect on tab change each time. Do you have anything in mind that might resolve this effect ?

**Comment by rpinco** [comment]
By flickering you mean it takes like half a second to "snap" and go from collapsed to full size? 
I had that too, it was because either I had " * " as a width on a columnDef, (to make ui-grid calculate the size of the column), or i was using the auto-resize plugins. 
I've given up on dynamic column sizes for my page, it works great when its not in a tab or modal, but its just not working when its in one.
Me and my team have been trying for a few days ways to work around this, but without forking the project and going in to see whats causing it, I don't see an easy solution to it. 
Honestly I would switch to ng-table or some other component, if "dynamic column size" wasn't an actual requirement from my client 

Cheers!

**Comment by mportuga** [comment]
@rpinco If you happen to know the cause and/or fix for it, I would be happy to accept a pull request with the fix and merge it

**Comment by ps-1993** [comment]
Closing this issue as reported collapse issue is been resolved with the suggested changes. Still if someone finds a solution to the flickering effect feel free to reopen this or open a new issue.
