### ISSUE TITLE
UI grid v4.0.6 not working with Korean locale 'ko'

### ISSUE THREAD

**Issue by pradeep014** [angular-ui/ui-grid#6951]
Hello,
I am using ui grid js v4.0.6.
But its not rendering the grid data for korean language having language code 'ko' (even after grid instance is properly initialized with grid data).
In ui-grid.js I can see, in i18nService 'ko' language delegate is present already.
Could you please help here?

**Comment by mportuga** [comment]
You can use i18nService.setCurrentLang('ko');

http://plnkr.co/edit/tJbCK8aHL6eREZG2Uve2?p=preview
