### ISSUE TITLE
Official website

### ISSUE THREAD

**Issue by EDGDK** [angular-ui/ui-grid#6970]
What is the official document address?
Although I have used ui-grid, some apis are not very familiar.

**Comment by jniles** [comment]
Hi @EDGDK, I believe the official documentation is http://ui-grid.info/.

**Comment by EDGDK** [comment]
> Hi @EDGDK, I believe the official documentation is http://ui-grid.info/.

Thanks ！I couldn’t get in this URL before. It turned out to be a problem with my network.
