### ISSUE TITLE
module ui.grid.autoResize calling $elem.is which isn't defined on the element

### ISSUE THREAD

**Issue by oostmeijer** [angular-ui/ui-grid#6971]
This bug occurs in version 4.8.0 with a grid with the autoResize module attached.

It also appears on the tutorial page:
http://ui-grid.info/docs/#!/tutorial/Tutorial:%20213%20Auto-Resizing

error:
```
Uncaught TypeError: $elm.is is not a function
    at gridResize (ui-grid.js:4841)
    at defaultHandlerWrapper (angular.js:3780)
    at eventHandler (angular.js:3768)
```

reproduce:
try resizing the window with the developer console open.

**Comment by SobolevLexa** [comment]
I created PR https://github.com/angular-ui/ui-grid/pull/6976
