### ISSUE TITLE
grid columns are collapsed inside bootstrap tab (#6899)

### ISSUE THREAD

**Issue by tolgato** [angular-ui/ui-grid#6983]
hello,
I am facing the same issue with #6899 after upgrading ui-grid to 4.7.1.
Whether in a modal or not, If I put my grid into the tab other than the main one,
grid is initially shown with collapsed columns.
When I click anywhere on the page or resize window, then grid is returning to normal.

![collapse](https://user-images.githubusercontent.com/50654261/58083243-2a8b3880-7ba8-11e9-9022-7d477f1a5bba.jpg)

Also I have tried updating to 4.8.0 and its not changed.

**Comment by tolgato** [comment]
As a workaround, I am fixing with a code as follows :

```
$scope.$watch('currentTab', function (newVal) {
        if (newVal == 2) {
          $scope.gridApiMyTable.core.refresh();
        }
 });
```
But I think, it's not the right way and it stills flickering on init.

**Comment by olcayguzel** [comment]
I also faced. @tolgato  Did you find any solution?

**Comment by tolgato** [comment]
Not yet, I'm still waiting for help
