### ISSUE TITLE
using infinite scroll while menu is open throws a [$rootScope:inprog] $digest already in progress exception

### ISSUE THREAD

**Issue by Joel-Kornbluh** [angular-ui/ui-grid#6989]
### Bug Description
With the infiniteScroll fetaure, when the grid is loading additional data (i.e. page) while a menu or column menu is open, it will throw a `[$rootScope:inprog] $digest already in progress` exception.

### Cause
This bug was introduced in [v4.2.0](https://github.com/angular-ui/ui-grid/releases/tag/v4.2.0) by [this commit](https://github.com/angular-ui/ui-grid/commit/076df7181ef8d041c668debaad1f3ddf9fa01c2b) which replaces `$timeout` with `$scope.$apply` in many places for performance reasons.

Specifically, [`dataLoaded`](https://github.com/angular-ui/ui-grid/blob/9cf645057b5898106e42e147e9a132a6c93c47dd/src/features/infinite-scroll/js/infinite-scroll.js#L103) - which is what users call once additional data has finished loading - calls [`adjustScroll`](https://github.com/angular-ui/ui-grid/blob/9cf645057b5898106e42e147e9a132a6c93c47dd/src/features/infinite-scroll/js/infinite-scroll.js#L106) which calls [`$rootScope.$applyAsync`](https://github.com/angular-ui/ui-grid/blob/9cf645057b5898106e42e147e9a132a6c93c47dd/src/features/infinite-scroll/js/infinite-scroll.js#L368) [and ](url)[indirectly ](https://github.com/angular-ui/ui-grid/blob/9cf645057b5898106e42e147e9a132a6c93c47dd/src/features/infinite-scroll/js/infinite-scroll.js#L398)[wraps ](https://github.com/angular-ui/ui-grid/blob/9cf645057b5898106e42e147e9a132a6c93c47dd/src/features/infinite-scroll/js/infinite-scroll.js#L432)[a](https://github.com/angular-ui/ui-grid/blob/9cf645057b5898106e42e147e9a132a6c93c47dd/src/js/core/factories/Grid.js#L1771) [`beginScroll`](https://github.com/angular-ui/ui-grid/blob/9cf645057b5898106e42e147e9a132a6c93c47dd/src/js/core/factories/Grid.js#L161) event trigger which has a [registered handler in the column menu](https://github.com/angular-ui/ui-grid/blob/9cf645057b5898106e42e147e9a132a6c93c47dd/src/js/core/directives/ui-grid-menu.js#L213) which in turn calls [`$scope.$apply`](https://github.com/angular-ui/ui-grid/blob/9cf645057b5898106e42e147e9a132a6c93c47dd/src/js/core/directives/ui-grid-menu.js#L163) again in `applyHideMenu`.

### Possible Fix
1. Restore the `$timeout` in `applyHideMenu` in place of `$scope.$apply`, or:
2. Use some kind of "safe" `$apply` wherever we use `$scope.$apply`/`$scope.$applyAsync`

**Comment by Lilipi** [comment]
Hi,
Any news about this please ?
The problem still exists. Replace $scope.$apply by $timeout in applyHideMenu doesn't seems to fix that. In fact, doing this, the menu open and close instantly...
