### ISSUE TITLE
row selection does not work correctly on mobile

### ISSUE THREAD

**Issue by tolgato** [angular-ui/ui-grid#6990]
If I open my website in mobile and select any row in grid, it doesn't change selected row item.
Dispite being highlighted, gridApi.selection.getSelectedRows() function returns empty array and gridApi.selection.on.rowSelectionChanged is not being called.

Previously I was using version 4.0.4 and it was working. 
I am facing this issue after upgrading to 4.7.1 or 4.8.0
(Angular version 1.7.5)

**Comment by wuzhenda** [comment]
is it responsive on mobile?

**Comment by tolgato** [comment]
it was working previously with ui-grid version 4.0.4

**Comment by tolgato** [comment]
I'am still waiting for help

**Comment by wuzhenda** [comment]
> I'am still waiting for help

which browser on which mobile platform，and what versions  both browser and the mobile OS ?

**Comment by tolgato** [comment]
chrome 76 & android 8.0 on my mobile but my friends also faced with different versions
