### ISSUE TITLE
[UI Performance Enhancement] Achieving 60fps Scrolling

### ISSUE THREAD

**Issue by NightlyFox** [angular-ui/ui-grid#6996]
Both horizontal and vertical scrolling is not very smooth. This mainly has to do with the UI-Grid is not using passive event listeners.

In the latest version of chrome it replaces these with non-passive ones and everything seems to work fine (no bugs). The fact that chrome has to replace it so much is probably what still causes very jank scrolling that sometimes that on average is around 8-10fps when scrolling. 

reading this short page from google explains how touch events can cause this.
**READ**: https://developers.google.com/web/updates/2016/06/passive-event-listeners

Really any scroll/touch/wheel event that is non-passive can cause this issue while scrolling.
when looking through the code i saw some  non-passive event listeners being created and destroyed a lot. 

.on(), .onXXXX() methods all use non-passive event listeners.
**READ**: https://stackoverflow.com/questions/39152877/consider-marking-event-handler-as-passive-to-make-the-page-more-responsive

Basically we should try **transitioning from .on() and .onXXXX() event listeners to javascript built in, document.addEventListeners() and make them passive**. 

Other scrolling performance enhancements:
Where it can be done, **setTimeout and timeout events should be replaced with requestAnimationFrame to increase performance**.
Example code here to help with replacing: https://gist.github.com/joelambert/1002116

To learn more about requestAnimationFrame to see when it can replace setTimeout/timeout uses
**READ**: https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame

**Remove preventDefault()/stopProgragation() where it can be removed.**
Other issues that cause performance lag are when preventDefault() and stopPropagation() are used. Passive event listeners are suppose to indicate preventDefault() will never be used and if it is, will ignore it. 
**READ**: https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener

There are places in the code where these methods are used, and where it can be removed without any bugs, it should be removed. (if all event handlers are properly made passive, then we should not have to worry about preventDefualt())

Finaly, CSS Animation smoothness is another key thing.
**READ**: https://www.html5rocks.com/en/tutorials/speed/high-performance-animations/
**READ**: https://blog.teamtreehouse.com/increase-your-sites-performance-with-hardware-accelerated-css
**READ**: https://www.smashingmagazine.com/2016/12/gpu-animation-doing-it-right/
This area will probably not improve performance as much as the others, so not a lot of time should be spent on this. There was one area where TranslateY was used. it could be changed to Translate3d in order to see if there are any performance increases. Although, if css gpu acceleration is not used properly it could slowdown css animation (still learning myself on when to use/not use it). 

PageSpeed can be used to find problem areas.
https://developers.google.com/speed/docs/insights/v5/get-started

If all of this is done, at the least ui-grid will have much smoother scrolling by v5.0.0!
Hopefully it will be around 60fps.

**Comment by mdentremont** [comment]
Good investigation work! Chrome has started to be quite vocal about it not liking the non-passive listeners as well, so I suspect this is going to start becoming more & more noticed
