### ISSUE TITLE
UI grid expandable rows not working as expected on latest chrome version (77)

### ISSUE THREAD

**Issue by amitjain24524** [angular-ui/ui-grid#7035]
After the update, google chrome (ver:77) from (ver:76) expanded row not working as expected. Before update google chrome expanded row of 'angular-UI-grid' was working properly, However, It's working fine in other browsers like Mozilla Firefox and Microsoft Edge and also working in older Version(76.0.3809.132) of chrome.

**Before Update**
![ui-grid01-before-update](https://user-images.githubusercontent.com/6824048/65685449-9d894c00-e07f-11e9-8111-7ddf4c410dd5.png)

**After Update**
![Capture1](https://user-images.githubusercontent.com/6824048/65685459-a11cd300-e07f-11e9-8ae6-4636a7d7ac4a.png)

**Comment by mjohnson1122** [comment]
Experienced the same thing.

**Comment by javcode** [comment]
exact same problem

**Comment by mjohnson1122** [comment]
Our ui-grid was greatly out of date.  Upgrading fixed the problem.  Specifically, the inclusion of .ui-grid_row {clear : both} in the .css.
