### ISSUE TITLE
'Unpin' action hides column filter

### ISSUE THREAD

**Issue by dmitry-borzov** [angular-ui/ui-grid#7049]
**Steps to reproduce:**
- Open simple example http://plnkr.co/edit/QbPXl1ghRtB707lwP93U?p=preview
- Open the **first** column menu (the column is pinned to left)
- Click 'Unpin'

**Actual result:**
- The first column filter gets hidden

**Expected result:**
- The first column filter is available

![pinning](https://user-images.githubusercontent.com/10911688/67141291-5e0ee380-f26a-11e9-96a8-6534561626d6.png)

**Comment by goncaloalface** [comment]
This problem also happens to me when I try to hide and then show the column again, where the filter box is missing, being this with the default filter or a custom one.

**Comment by dmitry-borzov** [comment]
@goncaloalface  I checked, #6969 does not solve this problem.

I found #7010 is the same bug as I reported above. It was closed with no fix.
