### ISSUE TITLE
i18n: empty translation displays error message instead of empty string

### ISSUE THREAD

**Issue by icguy** [angular-ui/ui-grid#7063]
Problem:
The grid allows translations of ui labels but displays an error instead when a translation is missing. There are languages where some of these need to be set to empty string, which is not currently possible.

Steps to reproduce:
Go to [the home page](http://ui-grid.info/) and set the locale to turkish.
![image](https://user-images.githubusercontent.com/12735493/70162396-e08a2000-16bd-11ea-8809-6352305e1fef.png)

**Comment by Git-Saravana** [comment]
Is this issue fixed? even I am facing the same issue for the strings "items per page" and "of" strings.

**Comment by icguy** [comment]
@Git-Saravana 
As a workaround you can set the "of" token to " / ", it looks relatively nice
![image](https://user-images.githubusercontent.com/12735493/70916489-0dbec280-201c-11ea-8adf-46b7c5779ae5.png)

**Comment by icguy** [comment]
I hate to be that guy but it's broken again. With the original repro steps i get this:

<img width="955" height="141" alt="Image" src="https://github.com/user-attachments/assets/9a582741-5ee8-4c02-9462-473b2abf87b4" />
