### ISSUE TITLE
UI Grid gridApi.selection.getSelectedRows() is not giving the rows in the order in which it was selected

### ISSUE THREAD

**Issue by piyush21upadhyay** [angular-ui/ui-grid#7068]
I have the below use case to implement in ui grid(pagination is already implemented) with 'Select All' button:

1) Load initial 50 records for first page with columns as name, id, age.
2) Click on 'Select All' to select all the rows rendered, using below code:
**Selection code: gridApi.selection.selectRow(gridOptions.data[rowIndex]);**

**Fetching the selected code: gridApi.selection.getSelectedRows();**

Till here things are working fine.

3) Now, Click on the ID column to apply sorting on ID.
4) Click on 'Select All' to select all the rows rendered, using below code:

**gridApi.selection.selectRowByVisibleIndex(rowIndex);** //rowIndex is the index of a loop running from 0 to 49.

But when i'm fetching the data with the logic defined in step 3, its giving in a unsorted order. So, overall my use case is to select the rows after the column sort one by one and fetch in the same order as its displayed on the UI.

Below is the pseudo code for the same:

    vm.selectAll = function selectAll() {
            var rowIndex;
            vm.gridApi.grid.modifyRows(vm.gridOptions.data);
            for (rowIndex = 0; rowIndex < MAX_SELECTION_ALLOWED; rowIndex++) {
                if(vm.isUISortingApplied){
                    //vm.gridApi.selection.selectRow(vm.gridApi.core.getVisibleRows()[rowIndex].entity);
                    vm.gridApi.selection.selectRowByVisibleIndex(rowIndex);
                }else{
                    vm.gridApi.selection.selectRow(vm.gridOptions.data[rowIndex]);
                }
            }
        };

**Comment by gracehhc1029** [comment]
Hi, do you find any way to solve this?

**Comment by piyush21upadhyay** [comment]
Unfortunately I didn't find any way to crack this. Any heads up from your side?

**Comment by piyush21upadhyay** [comment]
So, in one line i should ask what is the function provided by ui-grid to select and then fetch the selected rows after sorting is applied?

**Comment by piyush21upadhyay** [comment]
Got resolution for the issue by using **gridApi.core.getVisibleRows()** function which gives the rows in the correct order after sorting. I recommend using selection of rows by opting this function where ever sorting is implemented. Thanks!

An example where I had to select top 50 rows with/without sorting:
`vm.selectMax = function selectMax() {
			var rowIndex;
			vm.gridApi.grid.modifyRows(vm.gridOptions.data);
			for (rowIndex = 0; rowIndex < MAX_SELECTION_ALLOWED; rowIndex++) {
				vm.gridApi.selection.selectRow(vm.gridApi.core.getVisibleRows()[rowIndex].entity);
			}
		};`
