### ISSUE TITLE
Relax package.json to allow angular@1.8.0

### ISSUE THREAD

**Issue by Den-dp** [angular-ui/ui-grid#7088]
Right now all ui-grid packages describe angular dependency as [`"angular": ">=1.4.0 1.7.x"`](https://github.com/angular-ui/ui-grid/blob/master/packages/core/package.json#L7) which forces npm to install the extra package in the case when we use angular@1.8.0.

Here is how it looks like:
```
> npm init -y
> npm i angular angular-ui-grid
```
```
> npm ls
demo@1.0.0 C:\dev\temp\demo
+-- angular@1.8.0
`-- angular-ui-grid@4.8.3
  `-- angular@1.7.9
```
```
> tree
C:.
└───node_modules
    ├───angular
    └───angular-ui-grid
        ├───css
        ├───fonts
        ├───i18n
        ├───less
        └───node_modules
            └───angular
```
It would be nice to have only one angular installation per project.

---

Also want to notice that it looks like the current "range" syntax isn't valid according to https://semver.npmjs.com

![image](https://user-images.githubusercontent.com/1770529/85155146-127d6100-b261-11ea-8be2-e8dfc8015c11.png)

and it probably should be described as `>=version1 <=version2` or just `version1 - version2` (see more about syntax https://docs.npmjs.com/files/package.json#dependencies)

**Comment by natpicone** [comment]
See also https://github.com/angular-ui/ui-grid/issues/7091

**Comment by cristianpascottini** [comment]
Hi guys, **v4.8.5** published on npm registry [still depends on AngularJS 1.7.9](https://github.com/angular-ui/ui-grid/pull/7117#issuecomment-698989413).

**Comment by mportuga** [comment]
v4.8.5 has addressed this issue

**Comment by Den-dp** [comment]
@mportuga as I mentioned above - the current "range" syntax that is used in `package.json` isn't valid.

![image](https://user-images.githubusercontent.com/1770529/94431380-e21d5b00-019d-11eb-935e-188a7f918b09.png)

In practice, if the consumer wants to use angular@1.7.9, he/she will also get 1.8.0.
```
> npm add angular@1.7.9 angular-ui-grid
> npm ls
C:\dev\temp\ui-grid
+-- angular@1.7.9
`-- angular-ui-grid@4.9.0
  `-- angular@1.8.0 extraneous
```

And to fix that, the range must be specified as `>=version1 <=version2` or `version1 - version2`

![image](https://user-images.githubusercontent.com/1770529/94431288-c023d880-019d-11eb-8c4d-fe7b56e68f41.png)

See more about syntax https://docs.npmjs.com/files/package.json#dependencies
