### ISSUE TITLE
Custom filters hidden in the background

### ISSUE THREAD

**Issue by dkozul** [angular-ui/ui-grid#7097]
Hi,

I have a problem implementing custom filter. It is similar to select list filter but I need the ability to select multiple values. I created the directive with the logic that opens custom list below with checkboxes. The problem is that this list is not visible.

![image](https://user-images.githubusercontent.com/29822082/89445154-0f77fa80-d753-11ea-993b-3c913253f2da.png)

If I make css changes to header to make overflow:visible

.ui-grid-header-viewport {
    overflow: visible !important;
}
.ui-grid-top-panel {
    overflow: visible !important;
}

then my table falls apart since it is big table with vertical scrolling.

![image](https://user-images.githubusercontent.com/29822082/89447131-c8d7cf80-d755-11ea-93a7-b09c03207b2d.png)

How should I make custom filter when it remains hidden?

**Comment by mportuga** [comment]
Can you provide a fiddle or plunkr?
