### ISSUE TITLE
Problem translating field displayName values in ng-grid

### ISSUE THREAD

**Issue by jnmoons** [angular-ui/ui-grid#711]
I have a multilingual application that is using the pascalprecht.translate module (https://github.com/PascalPrecht/angular-translate) to translate all fixed data (labels etc) in my application. The only thing that is not translating are the field displayName values of my ng-grid. This is currently my config (without the translations for the headers):

```
  $scope.projectsGridOptions = {
      data: 'projectDataList',
      columnDefs: [
      { field: 'name', displayName: 'Name' },
      { field: 'description', displayName: 'Description' },
      { field: 'internal', displayName: 'Internal' },
      { field: 'client.name', displayName: 'ClientName'},
      { field: '', cellTemplate: '<a class="btn btn-success" data-ng-href="#/projects/detail/{{row.entity.id}}">{{"VIEW" | translate}}</a> <a class="btn btn-alert" data-ng-href="#/projects/update/{{row.entity.id}}">{{"EDIT" | translate}}</a> <button class="btn btn-danger" data-ng-click="delete(13)">{{"DELETE" | translate}}</a>' },

      ],
      enableRowReordering: true,
      enableRowSelection: false,
      showFilter: true,
      filterOptions: {
          filterText: "",
          useExternalFilter: false
      },
  };
```

What I would like to do is this:

$scope.projectsGridOptions = {
          data: 'projectDataList',
          columnDefs: [
          { field: 'name', displayName: '{{"NAME"|translate}}' },
          { field: 'description', displayName: '{{"DESCRIPTION"|translate}}' },
          { field: 'internal', displayName: '{{"INTERNAL"|translate}}' },
          { field: 'client.name', displayName: '{{"CLIENTNAME"|translate}}'},
          { field: '', cellTemplate: '<a class="btn btn-success" data-ng-href="#/projects/detail/{{row.entity.id}}">{{"VIEW" | translate}}</a> <a class="btn btn-alert" data-ng-href="#/projects/update/{{row.entity.id}}">{{"EDIT" | translate}}</a> <button class="btn btn-danger" data-ng-click="delete(13)">{{"DELETE" | translate}}</a>' },

```
      ],
      enableRowReordering: true,
      enableRowSelection: false,
      showFilter: true,
      filterOptions: {
          filterText: "",
          useExternalFilter: false
      },
  };
```

but unfortunately this only renders the text {{"NAME"|translate}} in the column header. Any idea how this would be possible?

**Comment by DonLiborio** [comment]
PauL1, I'm trying to implement what you suggest (headerCellFilter: 'translate'). I confess I'm a complete fraud as a coder so I need a working example. I'm missing something but I don't know what it is. Can we see a working example of this? Thanks.

**Comment by PaulL1** [comment]
Here is a plunker: http://plnkr.co/edit/KnrKTst5dWXvlZNeIy9c?p=preview

I wanted to put it into the i18n tutorial, but haven't worked out how to include external scripts - I'll try again later.

**Comment by DonLiborio** [comment]
I'm sorry if I'm missing something but the column names are not getting translated when I try the dropbox in your plnkr (I'm switching between "de" and "en"). It does show the correct language if I change the "preferredLanguage" in app.js.

**Comment by PaulL1** [comment]
Correct, I didn't wire up the language settings, I assumed you'd already have that because you said you already had angular-translate working in your app.  The key thing was just to show that it was translating the column headers.

**Comment by DonLiborio** [comment]
Well, then that's exactly what I don't know how to do. I'll try to figure it out, don't worry. Thanks for your time, Paul!

**Comment by PaulL1** [comment]
OK, there are some good tutorials for that out there, such as this one I wrote: http://technpol.wordpress.com/2013/11/02/adding-translation-using-angular-translate-to-an-angularjs-app/#comment-773.  

But basically you just call `$translateProvider.preferredLanguage('de');` whenever the dropdown gets changed (refer http://angular-translate.github.io/docs/#/guide/07_multi-language)

One trick is to make sure the string you're using to represent languages is consistent - so you can't be using 'en-US' in some places, and 'en' in other places.

**Comment by DonLiborio** [comment]
I think your tutorial is just the ticket. I am switching languages with this

`$scope.changeLanguage = function (langKey) {
    $translate.use(langKey);
  };`

but I see on your tutorial that's not enough for ui-grid's headers. Time to go through your tutorial. I appreciate your patience and promptness! Thanks again.

**Comment by DiskProphet** [comment]
@PaulL1 
Hi PaulL1,  For this link http://plnkr.co/edit/KnrKTst5dWXvlZNeIy9c?p=preview, 
you say "header text does not change after grid is rendered.", 
If have any solution to fix it ?
Thank for your help
