### ISSUE TITLE
Maintainers

### ISSUE THREAD

**Issue by Scrum** [angular-ui/ui-grid#7133]
@alexanderchan @mportuga @anteriovieira @douglasduteil

Hello everyone, I would like to submit my candidacy for the maintainers role. I understand that the project has not been supported for a long time, but I assure you that many monolithic projects still live on these technologies and they need to be developed and supported.

Let me know what you think about it anyway. Thanks.

**Comment by Scrum** [comment]
@alexanderchan @mportuga @anteriovieira @douglasduteil ping ?

**Comment by Scrum** [comment]
@petebacondarwin @nateabele @shaungrady @ProLoser ping ?

**Comment by nateabele** [comment]
Fine with me!

**Comment by Scrum** [comment]
> Fine with me!

I see you are a member of an organization, you have no opportunity to empower me?

**Comment by ProLoser** [comment]
@Scrum I sent you an invite for the ui-grid team

**Comment by nateabele** [comment]
> I see you are a member of an organization, you have no opportunity to empower me?

Wanted to give it a minute to see if anyone else spoke up.

**Comment by Scrum** [comment]
@nateabele @ProLoser Thanks a lot, guys, can I wait for the right from the `npm` to publish the changes?

**Comment by ProLoser** [comment]
It looks like @mportuga has been publishing to NPM. I don't know if any other contributors have access to the npm registry package, may need to add multiple publishers or (ideally) setup tag-based automation like Github Actions

**Comment by Scrum** [comment]
Yes, now `npm` keys are stored in `Travis` for migration to `Github Actions` you must have access to `npm` to create a key or have the key itself. 

Now it is enough that there is a mechanism for publishing through Travis. Thank you again !
