### ISSUE TITLE
Slovak language pinning not defined

### ISSUE THREAD

**Issue by IbrahimCarbuga** [angular-ui/ui-grid#7145]
Hi,

I'm using ui-grid for Slovak language. But when I use pinning property I take a error (Cannot read property 'pinLeft' of undefined). 
Then solve the problem, I tried change ui-grid.min.js file and I searched "sk" text then I couldn't see pinning property. But for other languages it was defined. Then I defined 
`  pinning: {
              pinLeft: "Pripnúť doľava",
              pinRight: "Pripnúť doprava",
              unpin: "Uvoľniť"
                    },`
my problem solved. And but publish the code, noone reached my editable code. Could you add pinning property in "sk" language?

![image](https://user-images.githubusercontent.com/47526592/119522167-6c957900-bd84-11eb-8501-306ac3adf81e.png)
![image](https://user-images.githubusercontent.com/47526592/119522432-a1093500-bd84-11eb-8914-79ec225fc5b6.png)

**Comment by mportuga** [comment]
Hi @IbrahimCarbuga,

I see the translations that you require in the sk language today: https://github.com/angular-ui/ui-grid/blob/master/packages/i18n/src/js/sk.js#L58-L61

May I ask which version of ui-grid you are using?
