### ISSUE TITLE
'Open plunker' link does not have discernible text

### ISSUE THREAD

**Issue by msftedad** [angular-ui/ui-grid#7228]
### Issue: 
'Open plunker' link does not have discernible text

### Repro steps:
1. Open [AngularJs Accordion - Plunker (plnkr.co)](https://embed.plnkr.co/BoQi5vDIDivY1aqts1fW/) code Pen.
2. Navigate to 'Open plunker'
3. Inspect using F12
4. Observe 'Open plunker' link dosen't have discernible text.

### Actual Result:
'Open plunker' link does not have discernible text

### Expected Result:
'Open plunker' link should have discernible text

### Screenshot:
![image](https://user-images.githubusercontent.com/93735775/176520448-3226ee4e-7852-46fe-b184-8867bee48b56.png)

**Comment by msftedad** [comment]
Hi Team, could you please share timeline for fixing this issue.

**Comment by msftedad** [comment]
@mportuga I've seen you add some accessibility tags on other issues - any update on this issue?

**Comment by SritejaGolla** [comment]
@mportuga can you please help us with this issue?

**Comment by mportuga** [comment]
This issue appears to be on the plunker page, which is not controlled by the UI-Grid team, so I am closing it. Sorry, I can't help with plunkr issues as we don't control plunkr
