### ISSUE TITLE
The Tables present under 'Angular Excel Style filtering example' page do not have accessible name.

### ISSUE THREAD

**Issue by msftedad** [angular-ui/ui-grid#7232]
**Test Environment:**
OS: Windows_11
Version: 21H2
OS Build: 22000.795
Browser: Version 103.0.1264.71 (Official Build) (64-bit)
URL: https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/excel-style-filtering
Screen Reader: NVDA (2021.3)

**Repro Steps:**
1. Open https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/excel-style-filtering in edge browser.
<img width="958" alt="MAS4 2 3_Table name not available (1)" src="https://user-images.githubusercontent.com/93735775/182786726-2ccf0495-36aa-42cc-ba91-6effd9e73d30.png">

2. Angular excel style filtering page will open.
3. Reach to the main landmark content where ' Examples' tab is selected.
4. With 6-tab press, reach to the column header of the available table.
5. Verify the issue that the table has proper accessible name or not.

**Actual behavior:**
The Tables present under the 'Angular Excel Style filtering Example' page do not have an accessible name.

**Expected behavior:**
The Tables present under the 'Angular Excel Style Filtering Example' page should have an accessible name.

**Comment by mportuga** [comment]
This defect is not for UI-Grid, but for Ignite UI, which is managed by a completely different team.
