### ISSUE TITLE
In 320*256 Pixels, Desc, x, submenu icon >, apply button present under 'Name filter' are truncated.

### ISSUE THREAD

**Issue by msftedad** [angular-ui/ui-grid#7237]
**Test Environment**
OS: Windows_11
Version: 21H2
OS Build: 22000.795
Browser: Version 103.0.1264.71 (Official Build) (64-bit)
URL: https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/excel-style-filtering
Screen reader: Non-Visual Desktop Access (NVDA) (2021.1)

**Repro Steps:**
1. Open https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/excel-style-filtering
2. Grids excel style filtering pen page will open.
3. Reach to the main landmark content where ' Examples' tab is selected.
4. With 6-tab press, reach to the column header of the available table.
5. Press ctrl + shift + L, the context menu opens.
6. Resize the screen to get 320x256 viewport.
7. Verify the issue that Desc, x, submenu icon is getting cropped or not.

**Actual Behavior:**
In 320*256 Pixels, Desc, x, submenu icon >, apply button present under ' Product Name filter' are truncated.

**Expected Behavior:**
In 320*256 Pixels, Desc, x, submenu icon >, apply button present under ' Product Name filter' should not be truncated. All the content and controls should be clearly visible.
<img width="864" alt="MAS1 4 10-MCIO DCX-Name filter" src="https://user-images.githubusercontent.com/93735775/184079678-277907a0-22ef-420f-8b20-6b7617764f15.png">

**Comment by mportuga** [comment]
This defect is not for UI-Grid, but for Ignite UI, which is managed by a completely different team.
