### ISSUE TITLE
 Text area missing label

### ISSUE THREAD

**Issue by msftedad** [angular-ui/ui-grid#7239]
**Test Environment:**
OS: Windows_11
Version: 21H2
OS Build: 22000.795
Browser: Version 103.0.1264.71 (Official Build) (64-bit)
URL: https://www.osgwiki.com/wiki/Asimov/Access#Step2:_Request_Access

**Repro Steps:**
1. Open the URL https://www.osgwiki.com/wiki/Asimov/Access#Step2:_Request_Access in the Edge Browser.
2. Navigate to the Asimov/Access heading section.
3. Run the Accessibility insight for web.
4. Observe the issue.

**Actual Behavior:**
Under Asimov/access heading in the content section doesn’t have any label defined.

**Expected Behavior:**
A proper label should be defined for Asimov/access heading in the content section and ATs should read the same when focus lands on it.
<img width="1896" alt="Text Area Missing Label" src="https://user-images.githubusercontent.com/93735775/184886509-c9279d61-8077-4075-96d9-94f812afabcd.png">

**Comment by mportuga** [comment]
The UI-Grid team is not responsible for the website in question.
