### ISSUE TITLE
Export to CSV with CSV injection in C# code - Issue with (-) index

### ISSUE THREAD

**Issue by devasena123490** [angular-ui/ui-grid#7240]
Hi Team,

I've implemented a logic to export data to CSV using C# and it has negative values (example: -10.0000) 
As per CSV injection, I added (') in the front . Something like below. 

            if(value.StartsWith("-"))
            {
                value = value.Replace("\"", "\"\"");
                return $"\"\'{value}\"";
            }
            
            When I export to CSV , I could see the (') in excel cell. But I have to format that from the code. How to fix that? I dont want to see (') when I export to CSV
                        
![image](https://user-images.githubusercontent.com/112111943/186726584-29deadbd-3874-40c4-a976-c692657bdb77.png)

**Comment by devasena123490** [comment]
Hi @All, Can someone look into this issue? Please

**Comment by mportuga** [comment]
I am not sure this qualifies as an UI-Grid defect
