### ISSUE TITLE
 Keyboard focus doesn't land on the first interactive element( asc) of the 'Name' popup as soon as it is opened.

### ISSUE THREAD

**Issue by msftedad** [angular-ui/ui-grid#7241]
**Test Environment:**
OS: Windows_11
Version: 22H2
OS Build: 22598.200
Browser: Version 104.0.1293.70 (Official Build) (64-bit)
Screen reader: Non-Visual Desktop Access (NVDA) (2021.1)
URL: https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/excel-style-filtering

**Repro Steps:**
1. Open [Angular Grid | Excel Style Filtering | Infragistics](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/excel-style-filtering)
2. Grids excel style filtering pen page will open.
3. Reach to the main landmark content where ' Examples' tab is selected.
4. With 6-tab press, reach to the column header of the available table.
5. Press ctrl + shift + L, the context menu opens.
6. With 9-tab press, reach to the search box of the opened pane.
7. Verify the issue that the focus lands on the first interactive control of the pop-up.

**Actual Behavior:**
Focus doesn't land on the first interactive element( asc) of the 'Name' popup as soon as it is opened.

**Expected Behavior:**
Keyboard focus should land on the first interactive element( asc) of the 'Name' popup as soon as it is opened.
[Focus not on interactive controls(2.4.3).zip](https://github.com/angular-ui/ui-grid/files/9468227/Focus.not.on.interactive.controls.2.4.3.zip)

**Comment by mportuga** [comment]
This defect is not for UI-Grid, but for Ignite UI, which is managed by a completely different team.
