### ISSUE TITLE
[Keyboard Navigation-MCIO DCX-'Site Selection' page]: The checkboxes of the filter of 'Name' pane of the context menu of the table are not receiving keyboard focus.

### ISSUE THREAD

**Issue by msftedad** [angular-ui/ui-grid#7248]
Description:
Users who rely on the keyboard will be as needed to type to select a filter. Some extra effort is needed to filter.

Test Environment:
OS Build: Version 21H2(22000.856)
Browser: Microsoft Edge Version 105.0.1343.33 (Official build) (64-bit)
Screen reader: Non-Visual Desktop Access (NVDA) (2022.2)

Repro Steps:
1. Open [Angular Grid | Excel Style Filtering | Infragistics](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/excel-style-filtering)
2. Grids excel style filtering pen page will open.
3. Reach to the main landmark content where ' Examples' tab is selected.
4. With 6-tab press, reach to the column header of the available table.
5. Press ctrl + shift + L, the context menu opens.
6. Verify the issue that 'check box' controls are receiving keyboard focus.

Actual Result:
The checkboxes of the filter of the 'Product Name' pane of the context menu of the table are not receiving keyboard focus while navigating with the tab key or arrow key.

Expected Result:
The checkboxes of the filter of the 'Product Name' pane of the context menu of the table should receive keyboard focus while navigating with the tab key or arrow key.

Additional Notes:
Same Issue Reproes in the same dialog present throughout the application.

Attachment:
[MAS2.1.1_check box not accessible.zip](https://github.com/angular-ui/ui-grid/files/9556050/MAS2.1.1_check.box.not.accessible.zip)

**Comment by mportuga** [comment]
This defect is not for UI-Grid, but for Ignite UI, which is managed by a completely different team.
