### ISSUE TITLE
[Accessibility]: Role defined for "Azure Sign in" is document. 

### ISSUE THREAD

**Issue by msftedad** [angular-ui/ui-grid#7253]
**Test Environment:**
Download [Eclipse IDE](https://www.eclipse.org/downloads/download.php?file=/oomph/epp/2022-06/R/eclipse-inst-jre-win64.exe&mirror_id=1248)
OS: Windows_11 Version: 22H2 (OS Build: 22598.200)

**Application/Product Impacted:**
Eclipse IDE for Enterprise Java and Web Developers 
Version: 2022-03 (4.23.0) 

**Pre-Requisites (if any):**
1. Download latest version of Eclipse 
2. Download “Azure Toolkit for Eclipse” from “Help” window (Navigation: Open Eclipse -> Help -> Eclipse Marketplace) 

**Repro Steps:**
1. Tab till tools-->Azure-->Azure Sign in and press enter 
2. Open "Accessibility Insights for Window" to Inspect "Azure Sign in". 
3. Verify "Azure Sign In" element MAS Compliant. 

**Actual Result:**
Role for "Azure Sign In" element present under "Azure Sign In" text is defined as "document". 

Similar issues for the following. 
Eclipse Installation and Sign-in_Eclipse Select Subscriptions scenario----> Open Java EE - Eclipse application-->Install 'Azure Toolkit for Eclipse' from Marketplace-->Tab till tools-->Azure-->Azure Sign in and press enter-->Select 'Device login' and tab till sign in and press enter--> Tab till 'Copy and Open' button and press enter-->Paste the code in the browser and click on next--> Verify "Select subscription(s) you want to use." element is MAS Compliant. 

 
Deploying web app to Azure_Deploy Web App scenario---->Open Java EE - Eclipse application-->Install 'Azure Toolkit for Eclipse' from Marketplace.-->Tab till tools-->Azure-->Azure Sign in and sign into Azure account and select any subscription-->Tab till File-->New-->Project--->Dynamic Web Project-->Tab till Next button and press enter--> In Project Explorer view, right-click your project, choose Azure-->Publish as Azure Web App-->Opens "Deploy Web App" dialog box.-->Verify the "Select App Service to deploy to:" element is MAS compliant. 
Deploying web app to Azure_Create New Web App scenario---->Open Java EE - Eclipse application-->Install 'Azure Toolkit for Eclipse' from Marketplace.-->Tab till tools-->Azure-->Azure Sign in and sign into Azure account and select any subscription-->Tab till File-->New-->Project--->Dynamic Web Project-->Tab till Next button and press enter--> In Project Explorer view, right-click your project, choose Azure-->Publish as Azure Web App-->Opens "Deploy Web App" dialog box.-->Tab to "Create" and enter. Verify the "Create Azure App Service" is MAS compliant. 

**Expected Result:**
"Azure Sign in" element shouldn't be defined as "Document". It is rather a normal text. 

**Attachments:**
![1952147_A11y_JavaToolingEclipse_Azure Sign-in_Role](https://user-images.githubusercontent.com/93735775/191514659-72794b77-820f-447d-8a0a-655da6e96ce8.png)
![1952147_Similar Issue_Select Subscriptions](https://user-images.githubusercontent.com/93735775/191514689-ea76f0a7-20e9-4478-88a0-b084f4ec3d80.png)
![1952147_Similar Issue_Deploy Azure web App](https://user-images.githubusercontent.com/93735775/191514712-d2829178-b55c-470a-b1f9-19362b76598b.png)
![1952147_Similar Issue_Create web app service](https://user-images.githubusercontent.com/93735775/191514734-b683410a-5bf4-44ca-87bd-bfa539a79362.png)

**Comment by mportuga** [comment]
We are not responsible for the azure sign in page, that is managed by someone else.
