### ISSUE TITLE
[Accessibility]: NVDA is reading the table as list. 

### ISSUE THREAD

**Issue by msftedad** [angular-ui/ui-grid#7255]
**Test Environment:**
Download [Eclipse IDE](https://www.eclipse.org/downloads/download.php?file=/oomph/epp/2022-06/R/eclipse-inst-jre-win64.exe&mirror_id=1248)
OS: Windows_11 Version: 22H2 (OS Build: 22598.200)

**AT (include version number):**
NVDA version 2021.3.1 

**Pre-Requisites (if any):**
1. Download latest version of Eclipse 
2. Download “Azure Toolkit for Eclipse” from “Help” window (Navigation: Open Eclipse -> Help -> Eclipse Marketplace) 

**Repro Steps:**
1. Download and Install Eclipse([Eclipse IDE](https://www.eclipse.org/downloads/download.php?file=/oomph/epp/2022-06/R/eclipse-inst-jre-win64.exe&mirror_id=1248)) 
2. Tab till tools-->Azure-->Azure Sign in and press enter 
3. Select 'Device login' and tab till sign in and press enter 
4. Tab till 'Copy and Open' button and press enter 
5.  Paste the code in the browser and click on next 
6. "Select Subscription" dialog box opens. 
7. Turn on the NVDA. 
8. Verify the "Subscription list" present in "Select Subscription" section are accessible and MAS Compliant.

**Actual Result:**
NVDA is announcing the table of "Subscriptions" as "list". The subscription list visually appears to be a table. When we traverse through the subscriptions, each cell is announced with its associated header column name, Row number etc. just like in tables. But defined using list. 

Similar Issue observed in the following. 
Eclipse Installation and Sign-in_deploy Web App scenario-->Open Java EE - Eclipse application-->Install 'Azure Toolkit for Eclipse' from Marketplace.-->Tab till tools-->Azure-->Azure Sign in and sign into Azure account and select any subscription-->Tab till File-->New-->Project--->Dynamic Web Project-->Tab till Next button and press enter--> In Project Explorer view, right-click your project, choose Azure-->Publish as Azure Web App-->Opens "Deploy Web App" dialog box.-->Turn on the NVDA.-->Verify the "App service list" is MAS compliant. 
Deploying web app to Azure_Create New Web App scenario---->Open Java EE - Eclipse application-->Install 'Azure Toolkit for Eclipse' from Marketplace.-->Tab till tools-->Azure-->Azure Sign in and sign into Azure account and select any subscription-->Tab till File-->New-->Project--->Dynamic Web Project-->Tab till Next button and press enter--> In Project Explorer view, right-click your project, choose Azure-->Publish as Azure Web App-->Opens "Deploy Web App" dialog box.-->Enter on "Create" button-->Turn on the NVDA-->Verify the "App Service" table is MAS compliant. 
 
**Expected Result:**
Subscription list should be announced as a Table by Screen Reader. For that to happen it should be defined using <table> tag. 

**Attachments:**
https://user-images.githubusercontent.com/93735775/191563575-325e2e82-85a4-45e2-a022-cdaaca11d2bc.mp4
![1952165_SimilarIssue](https://user-images.githubusercontent.com/93735775/191563798-e59c801c-0d15-4f68-9872-6081005528f9.png)
![1952165_SimilarIssue (2)](https://user-images.githubusercontent.com/93735775/191563824-be6eeea5-fcde-4560-85fc-6f5dabcc167c.png)

**Comment by mportuga** [comment]
we are not responsible for the azure page, that is managed by someone else.
