### ISSUE TITLE
[FEATURE] Add documentation for Vue3 save-state

### ISSUE THREAD

**Issue by AquaMCU** [angular-ui/ui-grid#7295]
**Is your feature request related to a problem? Please describe.**
I fail big time adding the save state plugin to my vue3 app. I

**Describe the solution you'd like**
Sample code on how to implement save-state.

**Describe alternatives you've considered**
I tried / here are my questions:
1. require ( "@ui-grid/save-state"); --- "reqire does not exists
2. import savestate from ("@ui-grid/save-state") -->  Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.

I am not sure if createApp(App).use(save-state) will work

I am not sure if adding ui-grid-save-state to my <ag-grid-vue> will do the trick either

**Additional context**

**Comment by Valuemark-Dev** [comment]
Hi,
I have a question.
Why are you using 'save-state'?
As my expertise, it would be better to use pinia, it's very easy to implement and understand.

**Comment by kissu** [comment]
Hi, please add a reproduction.
