### ISSUE TITLE
Formatting is not applied to header column if we export to excel with mobile number

### ISSUE THREAD

**Issue by ravindragullapalli** [angular-ui/ui-grid#7298]
**Describe the bug**
When we export the data to excel and if the data have mobile number, that column header is not coming with formatting

**To Reproduce**
1. Generate excel of the uigrid data which has mobile number using excel builder 
2. See error
3. The contact number column is coming without formatting. This is a column having a number with 10 digits.

**Expected behavior**
Like other columns, it should come along with the formatting

**Screenshots**
![image](https://github.com/angular-ui/ui-grid/assets/3313079/6772bbc7-c4bd-4edc-8335-6cdf44db2b40)

**Desktop (please complete the following information):**
 - OS: Tested both in Windows and Kubutu
 - Browser Firefox and Chrome

**Comment by K-Vishwak** [comment]
I will work on it.
