### ISSUE TITLE
[BUG] Concatenating filter strings not working

### ISSUE THREAD

**Issue by matthiaswolf** [angular-ui/ui-grid#7319]
Hi,

I'm trying to update an old project of mine using uigrid version 4.4.11. Updating to the latest version 4.12.7 worked just fine with one exception. With the old version of uigrid the following filter string was valid *red*|*blue*. Resulting in all rows, that either contain "red" or "blue", being shown. Using the latest version this results in no rows being shown. I tried downgrading uigrid version by version. The concatenation of filter strings using a pipe seems to be working up to version 4.10.2 and is not working from 4.10.3 onwards.

I'm not sure if this change of behavior is intended or indeed a bug, as there is no mention of it in the changelog.

I hope not to have wasted anyones time with this. :-)

Edit: changed version numbers

**Comment by mportuga** [comment]
Looks like an unintended side effect of a Change that went into 9.3, I will try to. Check it out this weekend

**Comment by matthiaswolf** [comment]
Hi,

thanks alot for looking into this problem and excuse my late response. Did you have any success in finding the problem?

Matthias
