### ISSUE TITLE
How to transform http text into link using a cellfilter

### ISSUE THREAD

**Issue by ghost** [angular-ui/ui-grid#746]
Greetings,

I've a text column which may or may not content among text, some http adresses.
I've added a cellFilter to that column which parse the cell content and add html tag to links.

My problem is, it seems ng-grid filter the opening and closing brackets to &lt; and &gt; (html values).

Is there any ways to avoid that?

Thanks

**Comment by anilnatha** [comment]
Thank you @wattsbn. Your post helped shed some light on an issue I was having that I was able to resolve.
