### ISSUE TITLE
AngularJS NgGrid data loading issue for IE8 browser

### ISSUE THREAD

**Issue by sivakp** [angular-ui/ui-grid#795]
Hi,
## Windows Internet Explorer

Stop running this script?

A script on this page is causing your web browser to run slowly.
If it continues to run, your computer might become
## Yes   No   

I tried changing the setTimeout() method time duration in getPagedDataAsync. Still did not find the reosoltion. Some ones help is really appreciated.  

Code snippet:

var getSuccessCallback = function (data, status) {
        $scope.gridData = data;
        $scope.getPagedDataAsync($scope.pagingOptions.pageSize, $scope.pagingOptions.currentPage);
    };
$scope.getPagedDataAsync = function (pageSize, page, searchText) {
                setTimeout(function () {
                    var data;
                    if (searchText) {
                        var ft = searchText.toLowerCase();
                        var largeLoad = $scope.gridData;
                        data = largeLoad.filter(function (item) {
                            return JSON.stringify(item).toLowerCase().indexOf(ft) != -1;
                        });
                        $scope.setPagingData(data, page, pageSize);
                    }
                    else
                    {  
                        $scope.setPagingData($scope.gridData, page, pageSize);
                    }
                }, 100);
            };        

$scope.gridOptions = {
        data: 'myData',
        multiSelect: false,
        enableColumnResize: true,
        columnDefs: 'Columns',
        enablePaging: true,
        showFooter: true,
        totalServerItems: 'totalServerItems',
        pagingOptions: $scope.pagingOptions,
        filterOptions: $scope.filterOptions    };
Thanks,
Siva.

**Comment by LalitSingh** [comment]
Hi Roblarsen,

I am using angular-ng-grid in my salesforce and retrieving more than 50000 records through rest API but in grid it showing only 2000 records.
Grid is restricted pagination for 2000 records only.
Is there any way to show more than 50000 records in grid.
