### ISSUE TITLE
Grids only show after I toggle the chrome inspector

### ISSUE THREAD

**Issue by zhenghao1** [angular-ui/ui-grid#799]
I just wanted to throw this out here, to see if anyone else is experiencing a similar problem as I am.  

I have 3 grids with 3 different gridOptions.  When the page loads, the grid fails to display data.  I mean, if I inspect the dom, the grids are there with data, but nothing is displayed on the page other than the CSS border I set for each grid.  

However, once I toggle the Google chrome inspector, the grids appear on the page.  I find this really weird.
## Digging deeper

I realized that the width of the grid was set at an initial 2px, but after toggling the inspector, it changes to 1385px, or however wide my screen is.

**Comment by vanslly** [comment]
When opening Chrome DevTools you are likely docking the window in your main window, causing the viewport of your web page to be smaller, hence causing a window resize. ngGrid rebuilds on a window resize (the column widths are calculated on render, so a resize means the grid needs to rerender to cause the columns to fill the new width.). Just resize the browser to cause the same effect.

There is an existing issue with ngGrid and ng-show: #855

**Comment by miteshjha007** [comment]
use window.dispatchEvent(new Event('resize'));
.. this works for me..

ref: https://www.techiedelight.com/trigger-window-resize-event-javascript/
