### ISSUE TITLE
Unable to style a cell tooltip 

### ISSUE THREAD

**Issue by MayaGi** [angular-ui/ui-grid#800]
Hi,
I am new to web development in general (angular, bootstrap, css etc.) so I wont be surprised if it is just a meter of knowledge :)
ngGrid was so easy to work with, I have no idea why I fail to do this simple task...

I am trying to add a tooltip to my cells. Using the title attribute works, but the style is different from the rest of the page (bootstrap styling) 
![image](https://f.cloud.github.com/assets/5850000/1464297/29d0aff6-4544-11e3-8618-10b7e820fd0b.png)

Changing the title attribute to tooltip doesn't work - it looks like it hides the tooltip under the next cell (changing the coordination of the tooltip to something within the range of the cell, made it partially visible).

(tooltip)
![image](https://f.cloud.github.com/assets/5850000/1464712/a2408f68-4550-11e3-90c9-4d19460aced4.png)

(title)
![image](https://f.cloud.github.com/assets/5850000/1464718/d6ea51ea-4550-11e3-8b9f-d844576e4243.png)

Any idea whats wrong?

Thank you.

**Comment by Raghunandan-MS** [comment]
@roblarsen -> It is sure an issue if you are styling your own tooltip on hovering over the ui gird element. I am facing the same issue. Even setting the z-index of the tooltip container seems to hide the tooltip behind the UI Grid Rows.

@MayaGi -> In case you are using ui bootstrap based tooltip, try **tooltip-append-to-body='true'**. It should work.
