### ISSUE TITLE
ng-grid columns overflowing grid width on chrome

### ISSUE THREAD

**Issue by logicware** [angular-ui/ui-grid#808]
![on firefox - version 25 0](https://f.cloud.github.com/assets/2248704/1508132/1f5d88d0-49d8-11e3-9cff-ebbcbaaa029a.png)
![on chrome - version 30 0 1599 101 m](https://f.cloud.github.com/assets/2248704/1508133/20134ce2-49d8-11e3-9431-13a86f80b491.png)

Please see the attached images. 

On chrome the columns overflow the width of the grid. On resizing any column the grid adjusts all the columns and a horizontal scroll bar appears. The columns are being dynamically defined depending on the data returned by the server. 

On FireFox and surprisingly on IE 10, the grid columns are adjusted properly on loading  the page with a horizontal scroll bar already there.

The behavior is the same whether I let the columns auto-size or define a width for every column.

angularjs version: 1.1.5
ng-grid version: 2.0.7

The browser versions are included in the names of the images.

Regards
Matloob

**Comment by juliusakula** [comment]
@logicware Think you could post those media queries?
