### ISSUE TITLE
multiple grids on one page

### ISSUE THREAD

**Issue by bhomass** [angular-ui/ui-grid#809]
I can follow the example and make one grid work for a page. 

if I have more than one grid, though, I need a way to tell them apart. 

for example, when I get an event
$scope.$watch('pagingOptions', function (newVal, oldVal) {

is it possible to also get an identifying parameter to know which grid fired the event?

**Comment by bitf09a013** [comment]
This seems to be an existing issue with latest release as well. In my case, I have multiple ui-grid's with gridOptions (inside an ng-repeat). In my case, pagination doesn't work if there are more than one element in the collection (meaning more than one uigrids).

**Comment by vpgayakwad** [comment]
@bitf09a013 I have same scenario like yours. But I am facing issue while making the editable cells in each grid. When I edit cell in one grid it will also modify other grids same column cell. Just like two way binding. Don't know how to avoid it. By chance did you face any such issue or any idea to fix it?

**Comment by bezabeth** [comment]
@bhomass ,, could you please post the solution to this matter?
I'm facing the same thing right now. I build the grids dynamically and the pager only works with the last grid that is renderized. Your help will be really appreaciate it.

**Comment by samboustani** [comment]
Here's how I'm doing it.  Each button for each grid has its own function.  However, I'm refactoring to put all button functions under the same generic function.

`<div style="overflow-y:auto; overflow-x:hidden; width:815px; max-height: 500px !important;">
                <div class="gridStyle2" id="gridOptionsTI" ng-grid="gridOptionsTI" />
            </div>
            <div class="pagination">
                <ul>
                    <li ng-class="{disabled: currentPageTI == 1}">
                        <a ng-click="prevPageTI()">« Prev</a>
                    </li>
                    <li ng-repeat="n in range(GridPagingOptionsTI.totalPages)" ng-class="{active: n == currentPageTI-1}"
                        ng-click="setPageTI()"><a ng-bind="n + 1">1</a></li>
                    <li ng-class="{disabled: currentPageTI == GridPagingOptionsTI.totalPages}">
                        <a ng-click="nextPageTI()">
                            Next »
                        </a>
                    </li>
                </ul>
            </div>`

`$scope.currentPageFA = 1;

        $scope.GridPagingOptionsFA = {
            pageSizes: [10, 20, 30],
            pageSize: 10,
            totalServerItems: 0,
            totalPages: 1
        };
        
        $scope.$watch('gridOptionsFA.sortInfo', function (newVal, oldVal) {
            if (newVal !== null && newVal !== undefined && newVal.fields.length > 0) {
                $scope.sortNameFA = newVal.fields[0];
                $scope.SortDirectionFA = newVal.directions[0];
                setPagingDataFA();
            }
        }, true);

        // pick the slice we currently want to see
        function setPagingDataFA() {
            $scope.myDataFA = [];
            if (!$scope.$$phase) {
                $scope.$apply();
            }

            $timeout(function () {
                $scope.GridPagingOptionsFA.totalServerItems = $scope.ForcedAuthorizationRequests.length;
                $scope.myDataFA = $scope.ForcedAuthorizationRequests.slice(($scope.currentPageFA - 1) * $scope.GridPagingOptionsFA.pageSize, $scope.currentPageFA * $scope.GridPagingOptionsFA.pageSize);
                $scope.myDataFA = setIndexing($scope.myDataFA);
                var pages = $scope.GridPagingOptionsFA.totalServerItems / $scope.GridPagingOptionsFA.pageSize;
                $scope.GridPagingOptionsFA.totalPages = pages > Math.round(pages) ? Math.round(pages) + 1 : Math.round(pages);
                if ($scope.sortNameFA !== null && $scope.sortNameFA !== undefined && $scope.SortDirectionFA !== null && $scope.SortDirectionFA !== undefined) {
                    $scope.myDataFA = SortNow($scope.myDataFA, $scope.sortNameFA, $scope.SortDirectionFA);
                }
                if (!$scope.$$phase) {
                    $scope.$apply();
                }
            }, 25);
        }

        $scope.prevPageFA = function () {
            if ($scope.currentPageFA > 1) {
                $scope.currentPageFA--;
                setPagingDataFA();
            }
        };

        $scope.nextPageFA = function () {
            if ($scope.currentPageFA < $scope.GridPagingOptionsFA.totalPages) {
                $scope.currentPageFA++;
                setPagingDataFA();
            }
        };

        $scope.setPageFA = function () {
            $scope.currentPageFA = this.n + 1;
            setPagingDataFA();
        };

        $scope.gridOptionsFA = {
            data: 'myDataFA',
            enablePaging: true,
            pagingOptions: $scope.GridPagingOptionsFA,
            sortInfo: { fields: [], columns: [], directions: [] },
            useExternalSorting: false,
            rowHeight: $scope.rowHeight,
            virtualizationThreshold: 100,
            showFooter: false,
            columnDefs: $scope.gridColumns
        };`
`
.pagination {
    height: 36px;
    margin: 18px 0;
}

    .pagination ul {
        display: inline-block;
        *display: inline;
        /* IE7 inline-block hack */
        *zoom: 1;
        margin-left: 0;
        margin-bottom: 0;
        -webkit-border-radius: 3px;
        -moz-border-radius: 3px;
        border-radius: 3px;
        -webkit-box-shadow: 0 1px 2px rgba(0, 0, 0, 0.05);
        -moz-box-shadow: 0 1px 2px rgba(0, 0, 0, 0.05);
        box-shadow: 0 1px 2px rgba(0, 0, 0, 0.05);
    }

    .pagination li {
        display: inline;
    }

    .pagination a {
        float: left;
        padding: 0 14px;
        line-height: 34px;
        text-decoration: none;
        border: 1px solid #ddd;
        border-left-width: 0;
    }

        .pagination a:hover,
        .pagination .active a {
            background-color: #f5f5f5;
        }

    .pagination .active a {
        color: #999999;
        cursor: default;
    }

    .pagination .disabled span,
    .pagination .disabled a,
    .pagination .disabled a:hover {
        color: #999999;
        background-color: transparent;
        cursor: default;
    }

    .pagination li:first-child a {
        border-left-width: 1px;
        -webkit-border-radius: 3px 0 0 3px;
        -moz-border-radius: 3px 0 0 3px;
        border-radius: 3px 0 0 3px;
    }

    .pagination li:last-child a {
        -webkit-border-radius: 0 3px 3px 0;
        -moz-border-radius: 0 3px 3px 0;
        border-radius: 0 3px 3px 0;
    }

.pagination-centered {
    text-align: center;
}

.pagination-right {
    text-align: right;
}`
