### ISSUE TITLE
Radio-buttons instead of checkboxes?

### ISSUE THREAD

**Issue by m48u** [angular-ui/ui-grid#82]
This is just a nice2have feature!

Using ng-grid in "multiSelect: false" - mode there are still checkboxes displayed in front of every row.
This could mislead the user to be able to select more than one row.
This could be avoided by using radio-buttons instead.

Thx!

**Comment by tooshar** [comment]
[LATEST] Very Simple! (after you read below, hehe)

Step 1: In columnDefs: {checkboxSelection: false} // Add this to your object

Step 2: Add this to the same object where you added 'checkboxSelection' 

            cellRenderer: function cellTitle(params) {
				let cellValue = '<div class="ngSelectionCell"><input name="selected" type="radio"></div>';
				return cellValue;
			},

Step 3: Add this code to your local css file :

        .ag-body {
           .ag-row {
              .ag-cell {
                 input[type=checkbox]:checked:after, 
                 input[type=radio]:checked:after{
                 display: none;
                 }
                 input[type=checkbox]:after, input[type=radio]:after{
                  display: none;
                 }
              }
            }
          }`

Hope it helps you!

**Comment by KAVYA-PUJARLA** [comment]
Above code is Working fine, but can u please tell me how to get selected row(which is selected with radio button).

**Comment by KAVYA-PUJARLA** [comment]
> [LATEST] Very Simple! (after you read below, hehe)
> 
> Step 1: In columnDefs: {checkboxSelection: false} // Add this to your object
> 
> Step 2: Add this to the same object where you added 'checkboxSelection'
> 
> ```
>         cellRenderer: function cellTitle(params) {
> 			let cellValue = '<div class="ngSelectionCell"><input name="selected" type="radio"></div>';
> 			return cellValue;
> 		},
> ```
> 
> Step 3: Add this code to your local css file :
> 
> ```
>     .ag-body {
>        .ag-row {
>           .ag-cell {
>              input[type=checkbox]:checked:after, 
>              input[type=radio]:checked:after{
>              display: none;
>              }
>              input[type=checkbox]:after, input[type=radio]:after{
>               display: none;
>              }
>           }
>         }
>       }`
> ```
> 
> Hope it helps you!

Above code is Working fine, but can u please tell me how to get selected row(which is selected with radio button).Thanks in advance.
