### ISSUE TITLE
Feature Request: Save Grid State

### ISSUE THREAD

**Issue by encircle** [angular-ui/ui-grid#838]
Would it be possible to write a plug-in to allow the grid state to be saved?

This state object would hold the grouping options, filters, paging options, sort columns, etc... which have been set by the user while interacting with the grid.

The grid state would be saved to a list which the user can access in future, either locally as a cookie or persisted on the backend.

Happy to contribute to this, if it's possible!

**Comment by waheedahmed55** [comment]
I have columns in ag-grid if user moves column C to first position it stays there but upon refreshing the page column C goes back to original position , basically user preference isn't retained. Any suggestion?
