### ISSUE TITLE
Sorting, Pagination and Filtering on Server Side ng-grid.

### ISSUE THREAD

**Issue by ecs-guptap** [angular-ui/ui-grid#840]
Hi,
I am using ng grid 2.0.7 and AngularJS 1.0.8.

I use the server side example like in the demo to load content dynamically using JSON files which are generated from the server.

The content loads fine, however, it's important for my app to enable sorting. The number or rows can be in thousands at times, and I show 25 or 50 of them at a time. However, the enabled sorting would only sort them for the 25 or 50 being displayed at the time, also filtering/searching doesn't work at all.

Also, I was wondering is there an option to reload the grid when someone changes their "Page Size" option from the select?

My grid options are like

<pre>
    $scope.gridOptions = {
        data: 'myData',
        enableRowSelection: false,
        enablePaging: true,
        headerRowHeight: 45,
        rowHeight: 45,
        enableColumnResize: true,
        showFooter: true,
        totalServerItems: 'totalServerItems',
        pagingOptions: $scope.pagingOptions,
        showFilter: true,
        filterOptions: $scope.filterOptions,
        useExternalSorting: true // for some reason, with this, the sorting doesn't works at all
    };
</pre>

and filter options are like

<pre>
    $scope.filterOptions = {
        filterText: "",
        useExternalFilter: true
    };
</pre>

Thanks a lot, really appreciate your help.

**Comment by rmyemul** [comment]
Can you fix these automatic pagesize pick up in the code

**Comment by vijender1256** [comment]
@c0bra 
I am getting error when the pagesize is changed when I add above code :

TypeError: Object doesn't support property or method 'fillGrid'

I get this error, any suggestions plz

**Comment by ericnewton76** [comment]
what about the filtering ?
