### ISSUE TITLE
Feature Request: Rowspan/Merged Cells

### ISSUE THREAD

**Issue by bastienJS** [angular-ui/ui-grid#845]
I would like to pull a feature request that you implement a rowspan over 2 or more rows.

This feature greatly help me improving my cell templates when I have a double lessons to prepare!

It should be possible to decide during runtime wether to render a row with a single cell or a merge cell/cells depending on a viewmodels property.

![rowspan](https://f.cloud.github.com/assets/5945955/1596234/6ab4930e-52f8-11e3-9687-da40e2e74af1.png)

**Comment by trupti18** [comment]
Hi, Has the ROWSPAN feature added to ui-grid or not? I am not able to find any inforamtion about it.
