### ISSUE TITLE
Grid not rendered correctly when using ng-show / ng-hide

### ISSUE THREAD

**Issue by goloroden** [angular-ui/ui-grid#855]
Steps to reproduce:
- Create a grid
- Add the `ng-show` directive and tell the grid to only show when more than 0 items are available
- Initialize your items with an empty array
- Fill in data to your items array at a later point in time (web service, timeout, …)

Expected result:
- The grid is initially hidden, and gets shown once the data are set.

Actual result:
- The grid is initially hidden, and stays hidden once the data are set.

Versions used:
- AngularJS 1.2.2
- ngGrid 2.0.7

**Comment by vanslly** [comment]
This issue still exists in the v2.0.14 of ngGrid.

As people above have suggested, rebuild the grid and apart for a little flicker from the grid while it rebuilds it's a suitable workaround. Example:

    $scope.$watch('isLoading()', function (newVal) {
        if (!newVal && $scope.gridController.rebuildGrid) {
            $scope.gridController.rebuildGrid();
        }
    }, true);

**Comment by pankas87** [comment]
I'm having this exact same problem. Any clues?

Seems to be related to https://github.com/angular-ui/ng-grid/issues/799

**Comment by yeahoffline** [comment]
same here while using different bootstrap tabs the grid stays empty unless i resize the browser ....

**Comment by ankittharwani** [comment]
Doesn't solve for me with angular 1.4.

The quickest option is to add 'ui-grid-auto-resize' in your dom element - 
<div ui-grid="gridOptions" ui-grid-edit class="grid" ui-grid-auto-resize></div>

**Comment by Vinodang** [comment]
@pmacmillan using ng-if instead of ng-show is correct!  ng-if fixed my issue! thank u very much!

**Comment by jklaus** [comment]
Just for the sake of redundancy... ng-if also worked for me.

**Comment by sendittokeith** [comment]
ng-if also works for me but it is not as smooth as ng-show.  I was showing/hiding a custom loader, the show/hide makes it smooth, the ng-if makes it bounce and is hard on the eyes.  Would be nice if it worked with ng-show instead.

**Comment by asdkalluri** [comment]
ng-if is slowing down the rendering. I'm having to wait longer :(

I have this inside a bootstrap tab and toggle buttons to show hide grids.
They won't render fine (especially in IE) until I do a resize.

ng-if works in IE but it is slowing things down.

**Comment by jklaus** [comment]
@sendittokeith @asdkalluri, If you know the desired height you might try ng-showing/hiding a containing div of the required height with the ng-if within.  Maybe..?  
My company has moved to more of a Chrome / FF user base so I spend less time ensuring things look spectacular in IE.

**Comment by DiHuang1986** [comment]
add ui-grid-auto-resize attribute to your ui grid will solve your problem. 
don't use ng-if while ui grid got involved, that is really SLOW operation while your data is big.

good luck.

**Comment by josephoun** [comment]
The solution is very easy ! ignore the other comments.

instead of initializing the grid data with an empty array (this is not what angular ui grid is expecting) , initialize it with an empty array with an empty OBJECT (this is what angular is expecting). 

this.gridData = [ ]         // wrong
this.gridData = [ { } ]     // correct

**Comment by mamarley** [comment]
This is still an issue for me with ui-grid 4.0.7.

**Comment by tkdindarl** [comment]
same issue, i can manage for non-IE browser but ng-show/hide is having issues

**Comment by mukulchakane** [comment]
ng-if instead of ng-show/ng-hide worked for me

**Comment by ljiljana0207** [comment]
ng-if instead of ng-show/ng-hide worked for me too

**Comment by carlbargain** [comment]
> ng-grid is not rendering the correct height of row if the parent is hidden at load using ng-show and shown on a different event triggered by user. I tried couple of solution which are working in ng-grid version prior 2.0.7 but not with 2.0.7 with angular 1.2.12.
> 
> ng-if might work as it will inject the content to the DOM and recreate the scope each time the expression is true, which is a costly operation if your content is static for an instance.





https://stackdev.space/questions/start-by-setting-up-a-pricey-component-using-ng-if-and-then-control-its-display-using-ng-showng-hide
