### ISSUE TITLE
Rows randomly not rendered

### ISSUE THREAD

**Issue by rschooley** [angular-ui/ui-grid#860]
This is occurring in 2.0.7.

Sometimes (4/5 times) not all rows are added to the grid.  They are missing from the markup, however the height of the canvas is calculated correctly.  Resizing the browser results in the missing items being added.

Given a data source of 10 rows, maybe 5 are shown, the other 5 are not in the markup.  Resizing then adds the remainder of the rows.

**Comment by thynctank** [comment]
@lwalden thanks a ton for pointing this out.

I was tearing out my hair here, loading 30ish rows of csv content into a grid instance and only seeing 4 (!?) rows render. I thought, surely some are just hiding behind the "viewport" limits or whatever, but no, *4 rows in the DOM*.

I'm on 3.0.6 and the default is 20 for `virtualizationThreshold`, which I'm still not completely clear on, though I have looked over the source briefly.

Anyway somehow this was only affecting us in Firefox at first, until we stripped away some options or other that revealed the issue across browsers. (not sure why Firefox was behaving differently yet, just happy to be moving forward again)

I'm sure I'll be returning to this property again to get a better understanding, but just wanted to say thanks as **this would have been a showstopper for us**.

**Comment by thefewminutes** [comment]
@lwalden thanks for the tip this fixed the problem

**Comment by vpgayakwad** [comment]
Thanks @lwalden  , I had a same issue in my app. You fix worked for me too.

**Comment by evirca** [comment]
Thanks **@lwalden**  this worked for me too

**Comment by Odravison** [comment]
I have a issue that the scenario is:
has two grids, one has only one column with custom cell template with a custom html with all necessary classes to ui-grid work.

when access the page that has this two grids, wait 5 sec, and click on tab that have this grid that I have mentioned, data isn't showed util I resize the window (browser). Curiously, if I click on the tab before this 5 sec, the data is showed properly. 

I have tried all kind of solution and nothing works. Any one passed by this?
