### ISSUE TITLE
Using editableCellTemplate with <input type="checkbox"> never unedits cell

### ISSUE THREAD

**Issue by ncourtial** [angular-ui/ui-grid#862]
Hi,
I Would like to use editableCellTemplate with a checkbox input but editableCellTemplate remains after cell lost of focus.
How could I do to correct this behaviour?

Cheers,
Nathan

**Comment by bhaidar** [comment]
Is this still valid?
I am facing an issue with editableCellTemplate here: 
https://github.com/angular-ui/ui-grid/issues/6174

Thanks
