### ISSUE TITLE
ngGridEventStartCellEdit events in ng-input directive are received each times ng-grid is manually bootstrapped in a Single page application

### ISSUE THREAD

**Issue by ncourtial** [angular-ui/ui-grid#877]
- add a console log TRACE in ng-input directive :
  scope.$on('ngGridEventStartCellEdit', function () {
             console.log('startEvent SCOPE :',$scope);
              elm.focus();
              elm.select();
          });
- Add enableCellEdit gridOption.
- Manually bootstrap ng-grid in a SPA multiple times.
- Try to edit a field.
- The ngGridEventStartCellEdit TRACE log is displayed the number of times you bootstrap your module.

=> In my case, execution time becomes very long with huge dataList.

**Comment by vijayvora079** [comment]
I'm facing same issue with the combination of third-party libs. please have a look

http://plnkr.co/edit/Jg0jjwajrjuzehks0dnl?p=preview

issue 1) ngGridEventEndCellEdit is working but ngGridEventStartCellEdit isn't working.

issue 2) steps are below

1. edit last cell
2. insert value
3. press enter for add
4. cell focus is not going to set at the last cell, I need to focus (cell) on next cell

will you please help me to find out the solution.
