### ISSUE TITLE
Want Help with Nested grids using ng-grid

### ISSUE THREAD

**Issue by syedjuned** [angular-ui/ui-grid#883]
Hi,

Its Recently we started using angular js in our project. its really amazing framework, ng-grid is just like "life made easy library", we have all features in ng-grid but I'm missing just one feature which is "Nested Grids"  like as in image.

I know ng-grid has grouping which is good , but it doesn't work for complex collections. It will be even more appreciative if ng-grid team will add this feature to their list and i tried lot of work around but it didn't work. and if any one has an hack kindly reply with the solution, it will be great help and It will be much appreciated. Thanks in advance
![index](https://f.cloud.github.com/assets/5379296/1740777/08106f0c-63d3-11e3-815b-7dd025582e12.jpg)

**Comment by sushanzh** [comment]
I have the same issue with ng-grid. Can you share the solution/workaround please?

**Comment by MangeshPimpalkar** [comment]
@syedjuned Can you share how you fixed this problem.
