### ISSUE TITLE
How to setup a custom filter function 

### ISSUE THREAD

**Issue by jaydeepk** [angular-ui/ui-grid#903]
Hi

I am trying to implement a custom filter function for a  ng grid but it doesn't seem to work.

What I want is some way to pipe the data binded to the grid via a filter function.

This is mainly to avoid keeping a duplicate copy of the entire data on the controller.

This is how I ideally want it to work :

  $scope.gridOptions = {
        data: 'clientsData|gridFilter:filterFunction',  
        filterOptions: $scope.filterOptions,

  $scope.filterFunction = function (elem) {
            // Filtering logic

```
};
```

  $scope.filterOptions = {
        filterText: '',
        useExternalFilter: true
    };

It seems that something similar has been attempted : 
https://github.com/angular-ui/ng-grid/issues/165

But I'm unable to get it working ... any ideas ?

Thanks

**Comment by tmpathak-cygnet** [comment]
@baonhan Can you please provide me proper plunker for the same  and the link which you have mentioned is also not working.

Seek help  !! Avid for you reply.

**Comment by rashmingadhvi** [comment]
I've got below solution to have 4 different types of filters in UI Grid. you can add more conditions to add more types/falvours.

 filter:{
                    condition:function(searchTerm, cellValue){
                        if(searchTerm.startsWith("%") && searchTerm.endsWith("%")){
                            //contains
                            searchTerm = searchTerm.replace(new RegExp("%","g"),"");
                            return new RegExp(searchTerm, "i").test(cellValue);
                        }else if(searchTerm.startsWith("%")){
                            //ends with
                            searchTerm = searchTerm.replace(new RegExp("%","g"),"");
                            return new RegExp(searchTerm + "$", "i").test(cellValue);
                        } else if(searchTerm.endsWith("%")){
                            //starts with
                            searchTerm = searchTerm.replace(new RegExp("%","g"),"");
                            return new RegExp("^" + searchTerm, "i").test(cellValue);
                        }else{
                            //exact
                            return new RegExp("^" + searchTerm + "$", "i").test(cellValue);
                        }
                    }

**Comment by SourabhRanka** [comment]
Simplified version -

filter:{
condition:function(searchTerm, cellValue){
var x = $(filter)('yourcustomfilter')(a,b);
if(x.length)
return true; // if you want to show the cell value
}
}

**Comment by umairnow** [comment]
condition: function is not invoked when I type a special character like steric "*". Anyone faced this issue?
