### ISSUE TITLE
Column headers can span over multiple columns enabling a hierarchical structure

### ISSUE THREAD

**Issue by wolf1860** [angular-ui/ui-grid#963]
I want to display hierarchical column headers by the property "headerRowTemplate",but I don't know how can I do this, thanks a lot!

**Comment by nmeeda** [comment]
is this feature available on "ui-grid - v3.0.0-rc.20-8199eb5 - 2015-04-13"  ? if so please provide us step by step guide?

**Comment by PaulL1** [comment]
No, this enhancement request is still open

**Comment by vvardhanz** [comment]
we need this feature #644

**Comment by anilnatha** [comment]
+1. We need to show how multiple columns are related to each other by having another row in the header that we can 'span' across columns with a label we specify as pretty much like what was proposed in ticket #644

**Comment by AdamDiment** [comment]
We need this too, thanks!

**Comment by jmsunseri** [comment]
I've been working on something in this plunker.  Your results may vary...  What would I need to do to make this ready for inclusion with ui-grid?

**Comment by MadUser** [comment]
Very nice jmsunseri, but unfortunately doesn't fit RTL.

**Comment by jmsunseri** [comment]
Feel free to implement RTL support and send back your changes

**Comment by MadUser** [comment]
well, it seems to me that there is a bug in ui-grid css file.
 in the code below I omitted the first line(which make all the mess) and it looks much better,
I am not sure if it is needed in other scenarios but I couldn't find one:
/*.ui-grid[dir=rtl] .ui-grid-header-cell,*/
.ui-grid[dir=rtl] .ui-grid-footer-cell,
.ui-grid[dir=rtl] .ui-grid-cell {
  float: right !important;
}

the other thing is missing in your category object is description property (for text other then English) then I use this description in the template instead of the name. now it looks fine. there is some padding issues but that's minor. thanks :)

**Comment by hchinthapally** [comment]
Please add this feature as early as possible. Also, please help me out with multi-level column grouping.
    animals                           |                         birds
-----------------------------------------------------------------------------------
mammals     |    reptiles       |  flying                |     flightless |  galliformes
-----------------------------------------------------------------------------------
tiger  | man  | snake | lizard  | sparrow | parrot | penguin     | hen | goose | peacock

**Comment by Mobidick** [comment]
+1

**Comment by mportuga** [comment]
Thank you for this information! I am moving this to our new support page as it is not an actual issue with UI-Grid, but a request. Someone from the Dev team should reply to your request there.
https://groups.google.com/forum/#!topic/ui-grid-support/Ehjgch4pP1A

Regards,

Marcelo

**Comment by 29er** [comment]
was this ever implemented ?? I need this !

**Comment by uncledb** [comment]
look at this:
http://stackoverflow.com/questions/31847615/header-grouping-of-ui-grid-angular/39740803#39740803

**Comment by jrkim123us** [comment]
I hope that this can be what you want.
https://jsfiddle.net/jrkim123/wexmj2Lw/

**Comment by JSlain** [comment]
Is there some work going on related to this?
Plans, or discussions about the way to go?

I'ld want something reusable, localizable, not bound to a scope, working with other modules, and, most importantly, built-in to the library!
If nothing's currently going on this way, i'll start working on a pull request.

I think this feature is a must.

**Comment by WorkMAE** [comment]
@jrkim123us that is badass!  Nice work...but it shouldn't take this much code/markup to do something this simple.

**Comment by WorkMAE** [comment]
@jrkim123us I cannot get this working in my setup.  I am loading a grid in a uib-modal and it loads everything fine up to `<tr ng-repeat="pos in modalQSGridOptions.headerAppends.index">`

where it just shows  and nothing after it as if it cannot find the $scope object in the modal controller.

in the modal controller:

```
$scope.modalQSGridOptions = {
                    enableSorting: true,
                    enableGridMenu: true,
                    enableFiltering: true,
                    enableColumnResizing: true,
                    onRegisterApi: function (gridApi) {
                        $scope.gridOpenApi = gridApi;
                    },
                    headerTemplate: 'QSHeader.html',
                    headerAppends: {
                        index: [0, 1],
                        height: 35
                    },
                    columnDefs: colDefsQualScore,
                    data: qualityScoreData
}

```

What I get is the data loading fine without any headers.  Any idea why this is happening?  I modified your version on the QSFiddle to use the $scope object and it works fine by removing the controller as syntax and replacing this.options with $scope, but I can't get it working in my example at all.

Any help?
