### ISSUE TITLE
rowItem.rowIndex not map to the index of data array after sorting?

### ISSUE THREAD

**Issue by earlyfai** [angular-ui/ui-grid#965]
I tried to highlighted a row by adding a class into ng-class.

After that, I tried to sort the grid by another column; however, the highlighted row didn't change along with the sorting order.

demo here:
http://plnkr.co/edit/ZWsGzdFYtU9if2kj94Q2?p=preview

Is my code wrong or anything I've missed? please help. Thanks.

**Comment by Syndicated-string-parsin** [comment]
i’ve nailed the answer https://stackdev.space/questions/what-is-the-best-way-to-organize-data-that-has-been-refined
