### ISSUE TITLE
 horizontal scroll very slow

### ISSUE THREAD

**Issue by wmacgyver** [angular-ui/ui-grid#980]
I created a simple ng-grid with 75 rows. each row has 17 columns. 
I also use ngGridFlexibleHeightPlugin to help auto sizing the grid.

vertical scrolling it works pretty well, but horizontal scroll is very slow to the point of not responsive in both firefox and chrome.

Is this normal?

**Comment by vcollado** [comment]
Increasing the value of the property `gridOptions.columnVirtualizationThreshold`  works for me
